### ISSUE TITLE
Under the solarized light theme, the display of the ls command is incorrect 

### ISSUE THREAD

**Issue by LuoZhongYao** [microsoft/terminal#10027]
### Windows Terminal version (or Windows build number)

10.0.19042.928

### Other Software

ls (GNU coreutils) 8.32 (inside wsl)

### Steps to reproduce

 Use solarized light theme, open wsl and run ls command 

### Expected Behavior

ls command displays accurate colors 
![img](https://user-images.githubusercontent.com/3121740/116986405-54d85100-ad00-11eb-904d-be1411af61b9.png)

### Actual Behavior

The ls command displays the wrong color 
![img](https://user-images.githubusercontent.com/3121740/116986465-66215d80-ad00-11eb-9393-ae0103035e19.png)

**Comment by zadjii-msft** [comment]
### [DAYS SINCE I'VE REGRETTED SHIPPING SOLARIZED: ~~15~~ 0](https://github.com/microsoft/terminal/issues/6997#issuecomment-822380261)

Solarized is an unfortunately bad theme for commandline applications, if you follow it exactly as authored. The majority of the bright colors are all basically just grayscale, which IMO is useless in a color scheme:

![image](https://user-images.githubusercontent.com/18356694/117002077-b8cf2b00-aca8-11eb-920b-395a8e40d002.png)

I bet whatever terminal you're using in the "expected" screenshot has a modified version of solarized that's actually useful. We decided to follow the standard exactly as is, to much pain. 

I think this is broadly /dup #6997
