### ISSUE TITLE
Issue with Kanji

### ISSUE THREAD

**Issue by LexPrima** [microsoft/terminal#10069]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Steps to reproduce

![Screenshot 2021-05-10 181248](https://user-images.githubusercontent.com/12571344/117690947-adee2c00-b1bb-11eb-9242-011b8e639933.jpg)

This file name, track 36, contains Kanji. OneDrive shows an error but displays the kanji. Explorer doesn't show the kanjis at all. cmd.exe (top left) shows with placeholder and Terminal (boton left) does something really weird. Looks like it kinda fuses its name with Track 35.

### Expected Behavior

Showing the actual filename

### Actual Behavior

Behaving weird. Pic related

**Comment by LexPrima** [comment]
It's actually not kanji. It was a Japanese song, so I wrongly assumed it be kanji. They are U+0090 and U+008D

**Comment by DHowett** [comment]
It's curious that we're not emitting this through conpty as a C1 control character and not in fully-realized UTF-8. 🤔

Can you capture the output to a file, and share that with us?

```
dir > blah.txt
type blah.txt
REM - ensure that it still reproduces in the copy^ :)
```

**Comment by DHowett** [comment]
We're wondering whether the filenames are encoded in SHIFT-JIS (and that's why OneDrive's failing and has replaced them with an unexpected character?)

**Comment by LexPrima** [comment]
[output.txt](https://github.com/microsoft/terminal/files/6474781/output.txt)

**Comment by LexPrima** [comment]
[output.txt](https://github.com/microsoft/terminal/files/6474788/output.txt)

**Comment by j4james** [comment]
It looks like those control characters have just been converted to question marks when piped to the file. However, this is really quite easy to reproduce. If you open a WSL bash shell, you can do something like this to create an equivalent file:

```echo Test > $'\u0090Shinjitsu no Shi \u008D(TV-Size).flac'```

Then go and view that file from a cmd shell in conhost and Windows Terminal.

In conhost, the C1 controls are displayed as error glyphs, and in Windows Terminal they are interpreted. The `U+0090` is the start of a DCS sequence, so that eats all the following characters up to the `U+008D`. And `U+008D` is a _Reverse Index_ control, which moves the cursor up to the previous line. You then end up overwriting the start of the previous filename with the remaining characters - `(TV-Size).flac`.

**Comment by j4james** [comment]
> It's curious that we're not emitting this through conpty as a C1 control character and not in fully-realized UTF-8. 🤔

I'm assuming it is converted to UTF-8, but that doesn't change its meaning. It probably starts out as a single byte value in code page 850 (e.g. `0x90`), is converted to a two byte UCS-2 value (`0x00 0x90`) when read in by an ANSI API and stored in the text buffer, and finally converted to a UTF-8 sequence (`0xC2 0x90`) when written out to the conpty pipe. No matter what the encoding, though, it's still the same value. And on the other side of the pipe, that UTF-8 sequence is just going to be converted back to the UCS-2 code point and interpreted as the C1 control character `U+0090`.

**Comment by zadjii-msft** [comment]
Okay, great explanation! This sounds exactly like #4363 to me then!

/dup #4363
