### ISSUE TITLE
Context menu 'Open in WT' should/could open in existing WT window

### ISSUE THREAD

**Issue by TomByrne** [microsoft/terminal#10084]
When using the context-menu in Explorer to open a new WT instance, it would be great if it opened as a new tab in the currently running WT window (if there is one). 

There should probably be a setting to control this behaviour, but IMO this behaviour should be the default.

**Comment by DHowett** [comment]
We're still working on our multi-window support, but _right now_ in the Preview (and in stable, maybe?) you can configure the "New instance behavior" ("Attach to the most recently used window on this desktop" will do what you want.)

Otherwise, we're tracking finer-grained control of this in /dup #7071
