### ISSUE TITLE
Focus terminal when pressing ctrl-` (ctrl-backtick)

### ISSUE THREAD

**Issue by WouterFlorijn** [microsoft/terminal#10081]
# Description of the new feature/enhancement

Most terminals, even ones developed by Microsoft (e.g. the one in VS Code), focus when pressing ctrl-`. Microsoft Terminal doesn't. It would be great if it did, as I currently can't really use it effectively since it breaks my workflow too much.

If this option already exists, please let me know. I couldn't find it anywhere.

# Proposed technical implementation details (optional)

.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/653> appears to cover this. It has been implemented but the binaries have not been released yet.

**Comment by zadjii-msft** [comment]
Yep, that sure looks like it to me!

/dup #653

**Comment by WouterFlorijn** [comment]
@KalleOlaviNiemitalo @zadjii-msft cool! I'm not entirely sure if that's exactly what I'm looking for, but the #653 thread is very long. It refers to the terminal opening on a specific monitor (e.g. the one the cursor is on). That's not what I'm looking for. I simply want the terminal window - that I've already opened - to focus when I press ctrl-`, but remain in its current location. If this is different from #653, perhaps a checkbox could be added to the settings like:

- [ ] Move terminal to cursor location when pressing focus hotkey

**Comment by zadjii-msft** [comment]
Yea, just about everyone wants something different from that feature. That's why I wanted to make it as customizable as possible. Currently, there's about [12 different ways of summoning the terminal ](https://github.com/microsoft/terminal/blob/main/doc/specs/%23653%20-%20Quake%20Mode/%23653%20-%20Quake%20Mode.md#which-window-and-where)that we've come up with. 6 of those are going to land in 1.9 right now. 

The most up to date thread is now #8888, which is tracking all the future work for `globalSummon` and `quakeMode`.

**Comment by WouterFlorijn** [comment]
@zadjii-msft cool. As far as I can tell that would cover my use case (and this issue). Thanks!
