### ISSUE TITLE
[SUI] Simplified Chinese translation recommendation - Part 2

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#10174]
From #10043 and my own observation, this is for Terminal 1.9 (selfhost preview).

| Key | Recommendation | Comment|
| -- | -- |-- |
| Globals_TrimBlockSelection.Header  | 矩形选中复制时删除行尾空格 |  The current translation is hard to understand. For some reason even the English text does not mention "copying". I added it in Simplified Chinese translation to make it easy to understand. |
| Globals_ForceFullRepaint.Header | 显示内容更新时重绘整个屏幕 | The current translation of "display" ("显示屏") is confusing. |
| Globals_ForceFullRepaint.HelpText | 未选中时，终端将根据帧的内容进行局部重绘 | The current translation is hard to understand. My translation here is a bit off the original text but makes more sense to users. |
| Globals_TabWidthMode.HelpText | Change ”专注" to "聚焦" . Make it "紧凑会将未聚焦的选项卡缩小为图标大小"  | I know, I know. This is confusing. I brought up "专注" in #9328 but this one has different context than some of the text in #9328 | 
| Profile_BackgroundImageStretchMode.Header | Drop the “的"  | To make it simplified |
| Profile_BackgroundImageOpacity.Header | Drop the “的"  | To make it simplified | 
| Profile_BackgroundImageStretchModeUniform.Content | 均匀 | The current translation is hard to understand. The most complete translation would probably be "保留纵横比", but it seems a bit lengthy. | 
| Profile_BackgroundImageStretchModeUniformToFill.Content | 均匀填充 | Same as above |
 | ColorScheme_Foreground.Text | 前景 | The current translation is confusing. |
| ColorScheme_SelectionBackground.Text | 选中背景 | The current translation is confusing. A more complete translation would be "选中区域的背景" but that is just too lengthy. |
| DirectionUp | 上 |  The current translation "竖起大拇指" is hilariously wrong |
| DirectionDown | 下 | To avoid duplicate "向”  |

**Comment by skyline75489** [comment]
The more I dig into this, the more I realize that there seems to be no existing terminal that has good i18n support, be in on Windows, Linux or macOS (@lhecker is it just for CJK languages or something? Correct me if I'm wrong).  Kudos to all the members of the i18n team in MS. I think we're making fantastic progress here in a better-localized terminal for people around the world.

**Comment by JingHuaMan** [comment]
Maybe phrases like the following should also be translated.

![image](https://user-images.githubusercontent.com/49118946/119438658-486d7400-bd53-11eb-9bd9-aad1835390dd.png)

**Comment by skyline75489** [comment]
@JingHuaMan  I'm actually not sure if that's possible. 

@zadjii-msft Is it possible to localize those? I found no corresponding strings for them in Resources.

**Comment by lhecker** [comment]
> The more I dig into this, the more I realize that there seems to be no existing terminal that has good i18n support, be in on Windows, Linux or macOS (@lhecker or maybe is it just for CJK languages or something? Correct me if I'm wrong).

i18n is probably a lot more robust in my language (German) than CJK, since it works with ASCII.

l10n has similar issues though. I always have a good chuckle when something as innocuous as "Close all tabs after the current tab" is literally translated into the absolute behemoth of "Alle Registerkarten nach der aktuellen Registerkarte schließen".

Of course there's also completely wrong translations like:
"Resize pane down" is translated to "Bereich niedergeschlagen skalieren", which basically means something like "scale area with depression" which really hits me in the feels. Me too German Windows Terminal, me too...

At one point I asked how I can contribute changes to our localization, but I forgot to follow up on it. It's currently not open source unfortunately, making it a bit harder to merge in community contributions.

**Comment by lhecker** [comment]
This is tracked as MSFT:33937071.

**Comment by skyline75489** [comment]
Fixed in 1.10
