### ISSUE TITLE
Can Windows Terminal support "F1" to launch the Ctrl+Shift+P Command Palete by default, to help handicapped users? 

### ISSUE THREAD

**Issue by animehunter123** [microsoft/terminal#10189]
Can the _default_ Windows Terminal Keyboard Layout support pressing the "F1" key to launch the Ctrl+Shift+P Command Palete? Other apps such as VSCode support F1 by default as well. This will help handicapped users with carpel tunnel syndrome or similar to use the f1 key to be able to access the command palette by default.

Thank you to everyone for continuing to make Windows Terminal a great tool. 

Kind regards.

**Comment by WSLUser** [comment]
You could try using a keybinding to allow "F1" to open the command pallete. I'm not sure if the function keys are supported as I've never considered using them.

**Comment by DHowett** [comment]
I think this is a great idea. Especially since "F1" is the key folks are accustomed to using for _help_... this will serve a dual purpose in making it both more accessible and more discoverable.

@zadjii-msft or @carlos-zamora, ack this and take off the triage tag if you agree.

**Comment by LuanVSO** [comment]
psreadline version 2.2-beta is using f1 to access help on the current typed command

**Comment by animehunter123** [comment]
It will definitely be helpful, thank you for looking into this request as my friends were curious as well. I appreciate your feedback!

 I think its a valuable feature to have as default. The json file for custom key will work for now, but I pray that it can be set as a default, as it will help handicapped users.

**Comment by zadjii-msft** [comment]
Stealing F1 by default, in `defaults.json`, seems like far too aggressive of a breaking change for me. I'm extremely reluctant to be stealing an unmodified key from client apps by default. 

I'm thinking the only way we can do this is for new users in `userDefaults.json`. If it's in `userDefaults`, then at least there's a 5% chance that someone will read their settings and realize that's been bound to something in the Terminal, and then they can easily remove it.

**Comment by lhecker** [comment]
We've had a lengthy discussion internally about this today and ultimately have decided to not bind F1 by default at the moment. There's some genuine concern that F1 is already being used by other applications and we want to prevent any conflicts with those if possible.

This is also the reason why the command palette is bound to `Ctrl+Shift+P` in the first place: `Ctrl+Shift+letter`-combinations are the only key bindings that (except in really specific cases) can't conflict with CLI applications. The past and future UX improvements in the actions menu of our settings UI should allow people to easily adopt such key binding changes themselves if they require this.
Lastly Windows Terminal's out-of-box-experience (OOBE) will see some significant improvements in the long-term. It's not unlikely that we could add a setting then, asking you to choose a "level" of key bindings, similar to how you can choose a default settings profile in Visual Studio.

Due to this I'll close the issue for now and would kindly ask to use our regular support for key bindings in the settings UI (and `settings.json`) to customize Windows Terminal in the meantime. 🙂

**Comment by animehunter123** [comment]
Thank you very much for your kind response. I understand and will continue to manually edit settings.json on each box with the setting of editing the **settings.json** file to add this at the top of the file (for anyone who wants to use it):

```
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            // This makes the commandPallete open with the F1 key instead of Ctrl+Shift+P for handicapped keyboard
            // users. The Windows Terminal team said that PSReadline defaults to F1, so this will need to be 
            // manually added to your settings.json file. My settings.json file that I added the below to was
            // in: C:\Users\MYUSERNAME\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json
            "command": "commandPalette",
            "keys": "f1"
        }
}
```
