### ISSUE TITLE
Quake Mode has incorrect window size after toggling fullscreen mode

### ISSUE THREAD

**Issue by JensMertelmeyer** [microsoft/terminal#10199]
### Windows Terminal version (or Windows build number)

Windows: 10.0.19043.0, Terminal: 1.9.1445.0

### Other Software

I am using 125 % DPI scaling

### Steps to reproduce

1. Invoke Quake Mode overlay
2. Press F11
3. Press F11 again

https://user-images.githubusercontent.com/1827784/119619525-61822d80-be04-11eb-91c1-004cdaefc9b1.mp4

### Expected Behavior

After leaving fullscreen mode, the quake bar should have the same size as before

### Actual Behavior

The window is moved to the right, there is a very noticeable gap between the window and the border of the screen
![image](https://user-images.githubusercontent.com/1827784/119619872-b756d580-be04-11eb-842e-84fd107357b6.png)

**Comment by skyline75489** [comment]
Yea I can also repro this. Thanks for the report!

**Comment by zadjii-msft** [comment]
Note to self: This doesn't only apply to the quake window, it's just more prevalent. 

Any window in focus mode that's left aligned with the edge of the monitor will repro this behavior. This is due to the code in https://github.com/microsoft/terminal/blob/0fefdac414f4e1f31ac6bd9a8ad68543c588264d/src/cascadia/WindowsTerminal/IslandWindow.cpp#L889-L904
