### ISSUE TITLE
How to chain two or more commands after "commandline": "cmd.exe /k ..."

### ISSUE THREAD

**Issue by DanyGee** [microsoft/terminal#10200]
Hi,
I can't figure out how to properly chain two commands in the following scenario 🤔 
This is a line from the json file:
`"commandline": "cmd.exe /k \"C:/Windows/System32/doskey.cmd\"&&\"D:/path/to/scriptsfolder/script.bat\"",`
The first command is working, the second is not.
Current approach gives me an error ⚠️ 
 **The filename, directory name, or volume label syntax is incorrect.** (script is 100% working when invoked manually in Terminal)
 
_Windows Terminal
Version: 1.8.1444.0_

**Comment by zadjii-msft** [comment]
okay this is dumb, but what if you made a _third_ file called `do-the-thing.bat`

```
@echo off
C:/Windows/System32/doskey.cmd
D:/path/to/scriptsfolder/script.bat\
```

then make the commandline `cmd /k do-the-thing.bat`? 

Obviously this is a workaround, but it _should_ work

**Comment by DanyGee** [comment]
It - by all means - is not dumb, actually your solution works pretty well🥳 
THANK YOU!

**Comment by vefatica** [comment]
What if someone really wanted/needed cmd.exe to start up executing the likes of this?

`"a b c.bat" && "d e f.bat"`

I tried a few things which didn't work.

**Comment by DHowett** [comment]
I mean, I just did this:

```
wt -- cmd /k echo hi && echo bye
```

and it worked fine?

![image](https://user-images.githubusercontent.com/189190/119695949-50411d00-be14-11eb-9928-ff385faa7c2f.png)

It also works with quoted things.

**Comment by DHowett** [comment]
```json
            {
                "commandline": "cmd.exe /k echo hi && echo bye && echo \"this has quotes\" && echo \"so does this\"",
                "name": "Profile 16"
            }
```

output

```
hi
bye
"this has quotes"
"so does this"

C:\Users\duhowett>

```

**Comment by DanyGee** [comment]
Does it work two *.bat files?

**Comment by DHowett** [comment]
Honestly, I can't even get it to work _outside_ of Terminal. Look:

```
C:\Users\duhowett>cmd.exe /k "C:\Users\duhowett\hello_world.bat" ^&^& "C:\Users\duhowett\eat_my_shorts.bat"
The filename, directory name, or volume label syntax is incorrect.

C:\Users\duhowett>exit
```

Note the `^&` are required to -escape the original `&`s. Without those, _second_ instance of cmd runs `hello_world` while the _**first**_ runs `eat_my_shorts`. Of course that will appear to work -- it's two different instances of CMD handling it for you making it look like they're running back to back. You can tell it's not right, however, because you must `exit` the inner instance before the second batch file happens:

```
C:\Users\duhowett>cmd.exe /k "C:\Users\duhowett\hello_world.bat" && "C:\Users\duhowett\eat_my_shorts.bat"

[--- CONTROL MOVES TO CHILD CMD ---]

C:\Users\duhowett>echo sup
sup

C:\Users\duhowett>
C:\Users\duhowett>exit

[--- CONTROL RETURNS TO SPAWNING CMD ---]

C:\Users\duhowett>echo pithy simpsons reference
pithy simpsons reference
```

If I check the commandline of the process that failed to run:

```
cmd.exe  /k "C:\Users\duhowett\hello_world.bat" && "C:\Users\duhowett\eat_my_shorts.bat"
```

that's correct alright.

So ... uh, is this supposed to work in _Windows_?

**Comment by DanyGee** [comment]
I don't know if it should. That's why I've asked, cause I needed to run 2 different things at terminal start.
Ultimately a bat with the following did the trick:
```
@echo off
call C:/Windows/System32/doskey.cmd
call D:/path/to/the/other/script.bat
```

**Comment by vefatica** [comment]
It's kind of strange.  From the WinKey+R dialog, `cmd /k "v:\a b.bat" && "v:\c d.bat"` gives

```
'v:\a' is not recognized as an internal or external command,
operable program or batch file.
```

The problem seems to be with the first of multiple commands being a quoted file name containing spaces.  If I add a kludge as the first command, it works.  `cmd /k echo This is a kludge! && "v:\a b.bat" && "v:\c d.bat"` produces

```
This is a kludge!
Hello!  This is 'a b.bat'.
My PID is ...
4556
Hello!  This is 'c d.bat'.
My PID is ...
4556
```
