### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by schernichkin** [microsoft/terminal#10223]
# Description of the new feature/enhancement

Add a "workspace" feature which would allow to define a custom workspace as a combination of profiles and windows layout. Clicking on the specific "workspace" should run associated profiles and tile windows accordingly.

# Proposed technical implementation details (optional)

Consider following image:

![image](https://user-images.githubusercontent.com/1202933/119737329-c3d04200-be87-11eb-988a-bc4207f66096.png)

Here I have 4 tiled widows. Each runned with the specific profile and aligned manually. I also had to execute some commands (such as ssh connections) in the each window. This is my "workspace". It suited to perform my tasks.

If I close the terminal, I'll have to re-launch these 4 profiles manually and position windows on the screen one by one. 

I want to have a feature, which would allow me to script "workspace". I.e. to run several profiles at once and open them  in predefined layout by one click.  I want to have an option to define several workspaces and run them as I need.

**Comment by zadjii-msft** [comment]
Have I got the command for you!

I've added the following command to my `actions`:

```json
{ "command": { "action": "wt", "commandline": "new-tab --title OpenConsole cmd.exe /k #work 15 ; split-pane -s .30 --title OpenConsole cmd.exe /k #work 15 ; split-pane  -s .25 -H cmd.exe /k media ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },

```

(you could probably make it shorter by replacing `new-tab`/`split-pane` with `nt`/`sp`, respectively).

I add that to the `keybindings`/`actions`. This creates a new command in the [Command Palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette) named "Good Morning". That opens up a few tabs & panes, running various build environments. I like having it in a command rather than `startupActions`, because I only really want this in _one_ terminal window, not _every single one I launch_. It's personal taste. 

You could repeat this for multiple different "session"s if you wanted. That way you could have layouts pre-defined for various different dev environments. 

We're also tracking adding commands to the new tab dropdown in #1571.

Does that work for you?

**Comment by schernichkin** [comment]
Yes. Looking like my request is already implemented. I am newbie in MS Terminal and not familiar with all it's features yet. Nevermind closing the request.
