### ISSUE TITLE
Scrollbar height, width is not same with system value.

### ISSUE THREAD

**Issue by professor93** [microsoft/terminal#10226]
### Windows Terminal version (or Windows build number)

10.0.19042.746 1.7.1033.0

### Steps to reproduce

I changed system value of scrollbar's height and width. By default they were 17px. I changed to 8px. But in the Microsoft terminal still 17px.

### Expected Behavior

After changing scrollbars style system wide, should be changed in the Microsoft terminal too.

### Actual Behavior

Scrollbars style (height,width) not same with system value.

**Comment by professor93** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/5443574/119743921-5252bc80-bea4-11eb-91ae-438703854595.png)

**Comment by zadjii-msft** [comment]
How did you change the scrollbar width?

Does the new scrollbar width apply to any scrollbars in UWP XAML Apps? The Xaml Controls Gallery is a great example. 

I'm guessing this is a WinUI issue, but I'd love to know more details.

**Comment by DHowett** [comment]
I'll throw this out there:

I looked up "how to change Windows scrollbar width." The _only_ results started with either "open regedit" or "launch WinAero" (which will just... edit the registry)

I'm going to go out on a limb and say that this just isn't a supported scenario since Windows removed the customization options for scrollbar size.
