### ISSUE TITLE
Running on Windows 7

### ISSUE THREAD

**Issue by aateeque** [microsoft/terminal#10236]
In my corporate environemnt we only have Windows 7 :(. Sadly that means I can't use this beauty out of the box. This is just a discovery thread to investigate what it would take to run wt on win7 (if at all possible); or if such previous attempts have spectacularly failed?

**Comment by WSLUser** [comment]
So there is a WPF control that is used to run on Windows 7 that Visual Studio employs. Additionally there are some architecture changes coming that will separate the different components of Windows Terminal such as the UI framework that would also make it easier for someone to more easily port to Windows 7. But since this OS is EOL, I think the business should be pressured to upgrade to 10. It's cheaper than paying for support of Windows 7.

**Comment by electronic-dk** [comment]
AFAIK Windows Terminal uses XAML Islands which are not available even on all Windows 10 versions (only on 1903 and newer if I recall correctly) let alone Window 7. So I think it's unlikely that it's going to be ported to older versions of Windows since it would essentially mean writing a completely new app.

**Comment by WSLUser** [comment]
> AFAIK Windows Terminal uses XAML Islands

I think you missed part of my comment. XAML Islands is part of WinUI, the UI framework currently in use. Since that is being stripped as a required building component, someone could write up something supporting a different UI framework, to the point that from a UI point of view, it could even run on Linux or Mac. (GTK or QT could be used for example, or to make it easier, just use Uno as it helps tremendously with the x-plat conversions.)

**Comment by zadjii-msft** [comment]
Admittedly, I wrote this comment referring to "earlier versions of Windows 10", but it applies _extra_ to Windows 7.

### https://github.com/microsoft/terminal/issues/1643#issuecomment-505971691
> Sorry. Right now, there's two big blockers to adoption on 1809.
> 
>     * XAML islands was a technology preview and didn't support high-DPI, DPI changes, or accessibility in 1809. We rely on them heavily.
> 
>     * 1903 added support for side-by-side WinRT component activation, something deep in the COM stack that lets us find our DLLs when they're right next to our EXE.
> 
> 
> We just can't go back to 1809.


### https://github.com/microsoft/terminal/issues/1909#issuecomment-510042323
> 
> 
> > the Windows Terminal **REQUIRES** features from the latest Windows release.
> 
> Unfortunately, there's really no workarounds available to us. XAML Islands is the technology we use to host our XAML UI in a Win32 process. Without that, we'd be unable to display anything. Since XAML Islands is only complete as of the latest Windows 10 release, there's nothing we can do about it.
> 
> If you'll want to use the terminal, you'll _need_ to be on the latest Windows 10 version.


### https://github.com/microsoft/terminal/issues/841#issuecomment-492940388

### https://github.com/microsoft/terminal/issues/498#issuecomment-490091740
> 
> 
> There are no plans currently.
> 
> We're dependent upon C++/WinRT and XAML Islands (UWP XAML) for our UI. We're also using DX/DWrite for the text renderer. Unless those are ported to linux sometime, then I'd say there's very little chance we ever support linux.
> 
> Furthermore, our entire build system is MsBuild-based, and I could be wrong, but I don't think our build system will work on linux.


### https://github.com/microsoft/terminal/issues/1893#issuecomment-509728952
### https://github.com/microsoft/terminal/issues/2024#issuecomment-512788360
### https://github.com/microsoft/terminal/issues/2480


<hr>

>  Since that is being stripped as a required building component

That's not entirely true. We're trying to strip that out of _specific parts of the `TerminalControl`_ in our own codebase. The point of that effort is to help unify the code for the UWP control and the WPF control. Yes, theoretically that means someone could use that core code in another framework. What that _isn't_ is "remove WinUI from the Terminal application". That's never going to happen, and the Terminal will _always_ be a WinUI application.
