### ISSUE TITLE
Always jump to where the cursor is

### ISSUE THREAD

**Issue by pplmx** [microsoft/terminal#10283]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Steps to reproduce

Due to always jump to where the cursor is, so you cannot choose a word.
So the first reproduce case: 
- case 1. You can choose a world
- case 2. You can scroll up to check the former info(For me, I cannot check the former info, because it always jumps to the cursor some seconds later.)

### Expected Behavior

- case 1: I can choose a word
- case 2: I can check the former info

### Actual Behavior

Both of them, I cannot.

**Comment by zadjii-msft** [comment]
Okay correct me if I'm wrong, but it sounds like you're trying to select text in the history, but you can, because every time you scroll up, the Terminal just jumps back down. Right?

That's definitely a little weird, the Terminal is only supposed to do that when you input a character. I wonder if mouse mode is triggering this.

@pplmx what commandline shell are you using? `cmd`, `powershell`, `bash`, something else...? Are you using any full-screen applications like `vim` or `tmux`?

**Comment by pplmx** [comment]
1. Your guess is right.
2. Any shell opened with Terminal(WSL, Bash, PowerShell, etc.) will produce that.
3. No full-screen application.
4. Sorry, I cannot give you the terminal version because my PC is not here. However, its version is the latest Microsoft Store Version(It's updated yesterday).

**Comment by pplmx** [comment]
Both of the following versions will occur that.

![image](https://user-images.githubusercontent.com/26994103/120476546-45225a00-c3dd-11eb-8ca2-24aeba4dd762.png)

**Comment by pplmx** [comment]
When I change to another monitor, the problem disappeared. Not sure whether this problem is caused by the monitor or not.
