### ISSUE TITLE
suddenly refuses to start

### ISSUE THREAD

**Issue by black-snow** [microsoft/terminal#10294]
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Steps to reproduce

Idk. Worked fine for ages. Now after a week-end and a reboot due to a windows update and apparently also a Windows Terminal update done automatically (installed via store) it refuses to start.

### Expected Behavior

Windows Terminal starts up.

### Actual Behavior

Application is active in task bar for about 2 seconds then just crashes without showing even a window.

```
Name der fehlerhaften Anwendung: WindowsTerminal.exe, Version: 1.8.2105.24004, Zeitstempel: 0x60ac2e94
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.19041.789, Zeitstempel: 0x2bd748bf
Ausnahmecode: 0xc0000409
Fehleroffset: 0x000000000007286e
ID des fehlerhaften Prozesses: 0x2aa4
Startzeit der fehlerhaften Anwendung: 0x01d755f363c37cd6
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\ucrtbase.dll
Berichtskennung: e744ecdd-b0f3-43d0-af28-00fa2abbbea6
Vollständiger Name des fehlerhaften Pakets: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: App
```

![grafik](https://user-images.githubusercontent.com/579733/120162857-1d729c80-c1f9-11eb-9a16-ce7efac77b90.png)

/edit: dupe of https://github.com/microsoft/terminal/issues/8358

**Comment by black-snow** [comment]
P.S.: `wsl` from power shell works fine

**Comment by swahilli** [comment]
I have the same issue. It was working fine on Friday, then, following a silent upgrade, it's not doing anything.

**Comment by Rafagd** [comment]
+1

It was working on Thursday, openned it on Friday for a job interview and it instantly crashed on me. 
It has not worked since.

**Comment by swahilli** [comment]
I uninstalled and reinstalled from the app store and it's now working, but I obviously lost all my settings

**Comment by gfraiteur** [comment]
Same here. Broken after silent update.

**Comment by timanstey** [comment]
Opening the App Settings for Windows Terminal Preview (Start -> Windows Terminal Preview -> on the jump list expand it and choose App Settings; or Settings -> Apps -> Windows Terminal Preview -> Advanced Options) then choosing the Repair option appears to fix this. Repair doesn't erase any settings (or didn't for me anyway).

**Comment by zarunet** [comment]
Can confirm. Here's a short clip of what happens in the taskbar :

https://user-images.githubusercontent.com/43345608/120176096-2ff3d280-c207-11eb-8083-da5b68b906d0.mp4

Same crash report as @black-snow afterwards.

Unfortunately, @timanstey's suggestion did nothing for me :/

**Comment by Rafagd** [comment]
> 
> 
> Opening the App Settings for Windows Terminal Preview (Start -> Windows Terminal Preview -> on the jump list expand it and choose App Settings; or Settings -> Apps -> Windows Terminal Preview -> Advanced Options) then choosing the Repair option appears to fix this. Repair doesn't erase any settings (or didn't for me anyway).

I tried uninstalling and reinstalling, and I just have tried both the Repair and the Reset options. No luck.

**Comment by hagronnestad** [comment]
> Opening the App Settings for Windows Terminal Preview (Start -> Windows Terminal Preview -> on the jump list expand it and choose App Settings; or Settings -> Apps -> Windows Terminal Preview -> Advanced Options) then choosing the Repair option appears to fix this. Repair doesn't erase any settings (or didn't for me anyway).

This worked perfectly for me as well.

**Comment by TheThing** [comment]
> 
> 
> > Opening the App Settings for Windows Terminal Preview (Start -> Windows Terminal Preview -> on the jump list expand it and choose App Settings; or Settings -> Apps -> Windows Terminal Preview -> Advanced Options) then choosing the Repair option appears to fix this. Repair doesn't erase any settings (or didn't for me anyway).
> 
> I tried uninstalling and reinstalling, and I just have tried both the Repair and the Reset options. No luck.

This occured on both my machines. Uninstalling and installing fixed the problem for me.

**Comment by zadjii-msft** [comment]
Huh. The `ucrtbase.dll` is definitely new. We've got a bunch of other crashes, but none coming from the CRT iirc. Best way to get to the bottom of this would be a feedback hub trace: /feedback

**Comment by black-snow** [comment]
Now after lunch break it works again ... I have just installed the feedback hub and wanted to record when WT suddenly just worked again ...

**Comment by zarunet** [comment]
Still broken for me :/ I sent a feedback from the hub ; did not get a link to share heer, tho.

**Comment by whereisaaron** [comment]
Windows Update struck yesterday and since it installed Windows Terminal will no longer start. Well it appears to run for 2-5 seconds then exits again. Using 1.8.1444.0 from Windows Store.

```
Faulting application name: WindowsTerminal.exe, version: 1.8.2105.24004, time stamp: 0x60ac2e94
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process ID: 0x6cd4
Faulting application start time: 0x01d75614900bd9f6
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: 78473d8b-303a-4caf-b8c9-b77587623e04
Faulting package full name: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by smiler** [comment]
This is also being discussed in https://github.com/microsoft/terminal/issues/8358. Doing the repair dance seems as mentioned above seems fix the issue (I've had this on two systems so far).

**Comment by Eric2203** [comment]
Hi, I'm having the exact same error. Repairing does NOT help in my case. Uninstall/reinstall does not either. It was working a few days ago. I've not rebooted since then.

From the Event viewer:

`Faulting application name: WindowsTerminal.exe, version: 1.8.2105.24004, time stamp: 0x60ac2e94
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x6e2c
Faulting application start time: 0x01d7566cb1e7e12d
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: b996e0eb-a6bc-40dd-a27e-f4e9a8463d49
Faulting package full name: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App`

And:

`Fault bucket 1320776192965560009, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.8.2105.24004
P4: 60ac2e94
P5: ucrtbase.dll
P6: 10.0.19041.789
P7: 2bd748bf
P8: 000000000007286e
P9: c0000409
P10: 0000000000000007

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE811.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREAF0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREB30.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREB3D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREB9C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_bb1488c3939d65a4e3fed65bb628a3e554bf88_19389ec9_075e3dda-3c75-4edf-9061-4048fca64605

Analysis symbol: 
Rechecking for solution: 0
Report Id: b996e0eb-a6bc-40dd-a27e-f4e9a8463d49
Report Status: 268435456
Hashed bucket: 4ba5cd02f28599e4625456f3218146c9
Cab Guid: 0`

**Comment by matthewstuartedwards** [comment]
Also having the issue starting up, and repair did not work for me.

**Comment by bsmely** [comment]
+1

**Comment by zadjii-msft** [comment]
Nevermind, I'm crazy. The `ucrtbase.dll` crash is /dup #10211
