### ISSUE TITLE
Make the TabView span the entire window width

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#10320]
# Description of the new feature/enhancement

The TabView currently stops after the add button. This is a problem because it has a shadow which gets interrupted.
It's harder to see with the default gray titlebar, but if you could change it to white it would be noticeable.

It would be ideal if the TabView would span the entire window.

![tabviewcurrent](https://user-images.githubusercontent.com/84711285/120685914-14a7f200-c4a9-11eb-8f80-8e38ecc09f9c.png)
![tabviewfixed](https://user-images.githubusercontent.com/84711285/120685920-15d91f00-c4a9-11eb-9318-e36599cb817f.png)

# Proposed technical implementation details

It can be achieved by moving the drag bar and caption buttons inside the TabStripFooter.

**Comment by zadjii-msft** [comment]
So this is a cool idea, but also fraught with peril. We're doing all sorts of wonky Win32 hacks to let the user drag that region as it is. I'd love to have the shadow work across that entire region, but we'll need to be careful to not break that behavior.

**Comment by DHowett** [comment]
Yep -- if we do this, we'll need to make sure that AppHost can still communicate with NonClientIslandWindow to let it know where the draggable region is.

We used to do this because we had to punch a hole in the XAML window where no content could be displayed -- now it's just an implementation of convenience (read: software engineering is lazy and optimizes around local maxima sometimes :grin:) since we have a different drag bar implementation. :smile:

**Comment by zadjii-msft** [comment]
Oh hey we did this in #12916
