### ISSUE TITLE
Always-on-top quake mode window

### ISSUE THREAD

**Issue by cerebrate** [microsoft/terminal#10372]
# Description of the new feature/enhancement

The way I use the _quake window (for a one-off command or series of commands), it usually has my attention for as long as it's up, but on the occasions where I turn away to do other things, it can easily get lost in the mess and/or confused with one of my regular terminal windows. Having it always-on-top such that it is either dropped-down on-top or not makes this less likely to happen in my workflow.

# Proposed technical implementation details (optional)

While just making the _quake window always-on-top by default would fit the letter of the request, I'd much rather have always-on-topness added as a parameter that can be used with _quakeMode_ and _globalSummon_ to influence the parameters of windows they create. It would also be useful to have it as a command-line option for use with _-w_ -- I currently use a `_C:\Users\avatar\AppData\Local\Microsoft\WindowsApps\wt.exe -w _quake` to automatically open the _quake window when I log on, and while I can toggle on always-on-topness after opening it, I would prefer to be able to have that in the shortcut.

**Comment by WSLUser** [comment]
If you have the "AlwaysOnTop" enabled in your `settings.json`, does launching via quake mode ignore this?  If it does, then I'd call it dupe https://github.com/microsoft/terminal/issues/9992

**Comment by zadjii-msft** [comment]
Yea, this is gonna fall under /dup #9992

**Comment by vanitum** [comment]
Hello! I found a workaround for getting “Always on top” only for Quake mode, I figured I should share it here since the PR that implements this feature hasn’t been merged yet.

If you enable “Always on top” but launch a new terminal via a batch script, that new window will not inherit the “Always on top” behavior.

For example, here’s a `.bat` that opens PowerShell in the windows terminal without being "Always on top":

```
@echo off
pwsh
```

Hopefully this helps anyone who comes across this issue before the feature is implemented.
