### ISSUE TITLE
CMD prompt [error 0x800702e4 when starting "CMD. Exe)]

### ISSUE THREAD

**Issue by whiteS18** [microsoft/terminal#10377]
我的Windows Terminal设置默认打开cmd.exe程序，当我今天打开Windows Terminal程序后，cmd提示[启动“cmd.exe”时出现错误 0x800702e4]。请问应该如何解决？

My windows terminal setting opens the cmd.exe program by default. When I open the Windows terminal program today, the CMD prompts [error 0x800702e4 occurred when starting "cmd.exe". How should I solve it?

**Comment by whiteS18** [comment]
![Uploading 图片.png…]()

**Comment by skyline75489** [comment]
Does the solution in #4272 works for you?

**Comment by whiteS18** [comment]
> Does the solution in #4272 works for you?

Oh,I open Windows Terminal as administrator and then cmd.exe was work. and I  wanna know how to unmarked cmd.exe
 run as administrator

**Comment by zadjii-msft** [comment]
Honestly, I'm not sure where that checkbox is. I know where it is for _shortcuts_, but not for an actual executable. @DHowett help me out here?

**Comment by DHowett** [comment]
Actually, I don't know either. This is not a normal configuration...

**Comment by whiteS18** [comment]
I dont't know what's happend, It's just can used by it self....

**Comment by DHowett** [comment]
@skyline75489 Mind taking a look at this? We think we know what the issue is, but we can't tell if the last comment means "it is working fine now."

**Comment by skyline75489** [comment]
It is. It means “it works for me now”

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dustin L. Howett ***@***.***>
发送时间: Friday, July 9, 2021 4:05:59 AM
收件人: microsoft/terminal ***@***.***>
抄送: Chester Liu ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/terminal] CMD prompt [error 0x800702e4 when starting "CMD. Exe)] (#10377)


@skyline75489<https://github.com/skyline75489> Mind taking a look at this? We think we know what the issue is, but we can't tell if the last comment means "it is working fine now."

―

**Comment by whiteS18** [comment]
> @skyline75489 Mind taking a look at this? We think we know what the issue is, but we can't tell if the last comment means "it is working fine now."
 indeed

**Comment by whiteS18** [comment]
> @skyline75489 Mind taking a look at this? We think we know what the issue is, but we can't tell if the last comment means "it is working fine now."

indeed

**Comment by DHowett** [comment]
Thanks!

**Comment by BA7JCM** [comment]
i have the same problem,when i run terminal witout administrator and start cmd ,it say "[启动“cmd.exe”时出现错误 0x800702e4]"
