### ISSUE TITLE
Fira Font

### ISSUE THREAD

**Issue by chargen** [microsoft/terminal#10441]
Will we have the FIRA family of fonts embedded in Windows Terminal,  that would be xyzzzy awesome.

# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by PhyX-Meow** [comment]
I can not see why will.......
You can just install fira font yourself.

**Comment by DHowett** [comment]
Thank you for the request. It looks like you made the same feature request 18 days ago in /dup #10288! Our opinion has not changed -- it is 3rd party code that we will not be including with the Terminal, because that would make it automatically available to every application on Windows and make it more difficult for the creator of Fira Code to make updates.
