### ISSUE TITLE
Pin or bookmark as favorite directory on windows terminal

### ISSUE THREAD

**Issue by silvesterwali** [microsoft/terminal#10460]
Hi, thank's for the great idea to create this app.  I have tried this terminal for several weeks, and whenever I go to a specific directory on my windows, I should type like  below
```bash
   cd C://xampp/htdocs/myProject
````

it would be nice to pin this current directory as a favorite so when we come back to the current directory, just go with our favorite directory with pinned as the favorite one.

![image](https://user-images.githubusercontent.com/40487188/122638798-cccfce80-d128-11eb-8588-9b2d7d8cb033.png)

Thank's

Sorry for my bad English to explain it

**Comment by KalleOlaviNiemitalo** [comment]
With <https://github.com/microsoft/terminal/issues/8166> and <https://github.com/PowerShell/PowerShell/issues/15469>, PowerShell can inform Windows Terminal about the working directory. I don't see any technical obstacle to changing Windows Terminal so that the user can bookmark the directory and later select the bookmark to open a new pane, tab, or window in that directory. However, if you want Windows Terminal to tell a previously started shell to `cd` to a bookmarked directory, that is more difficult.

**Comment by KalleOlaviNiemitalo** [comment]
On the other hand, if you need this only in PowerShell, then it would be pretty easy to define a set of aliases named like `cd-MyProject` and then type `cd-` and press Tab to get a list.

**Comment by silvesterwali** [comment]
Hi, @KalleOlaviNiemitalo  thank's for your advice, but I think to create the alias for every project that we have maybe we cannot remember all of them, in my own experience I just open vscode , but not running the server development within vscode terminal because my screen is small, so I running the server dev from windows terminal (Power Shell or CMD) and it helps me to focus on my code and save space, and finally this is only my opinion.

**Comment by zadjii-msft** [comment]
Couldn't you just create a profile, where the `startingDirectory` is set to `C://xampp/htdocs/myProject`? That's generally what I do - one profile for each of the projects I like to work on
