### ISSUE TITLE
Midnight Command (mc.exe) doesn't accept mouse input (selects text instead)

### ISSUE THREAD

**Issue by DrPepperBianco** [microsoft/terminal#10505]
I installed Midnight commander on my system (Windows 10). If I launch it "C:\Program Files (x86)\Midnight Commander\mc.exe" via Windows Terminal and try to click on anything it doesn't work. It instead only selects the text.

If I try to google this problem, I only get results, telling me, that "Windows Terminal" support mouse input for Midnight Commander from around March 2020. These articles mean linux though, either via SSH or via WSL. And if I connect via SSH to linux and then use midnight commander the mouse works. But if I start a midnight commander session locally, it doesn't.

I actually had the same problem, when I just started "mc.exe" in a regular console window. But there I opened the properties and deactivates "Quick Edit". Thus selection had to be activated explicitly and other mouse clicks works as expected.

But I didn't found a similar option in the settings of Windows Terminal.

**Comment by zadjii** [comment]
What version of the terminal are you using? And what version of mc.exe?

**Comment by KaranKad** [comment]
Mouse input support for windows applications was added in v1.9.1445.0 Preview. Try using that.

**Comment by DHowett** [comment]
Yep! This is correct.

Now, if you're using 1.9+ and mouse input doesn't work for MC (Windows), it could be the case that it is not managing the mouse mode in a way that Terminal can detect.

For maximal compatibility with Windows applications, we had to make a couple compromises in how mouse mode was detected. Otherwise, *all* windows applications would try to eat cursor input events ... which would be significantly worse from a user experience standpoint 😦
