### ISSUE TITLE
[Question]: Is there a way to try out build artifacts?

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#10506]
Each commit fires off a build (for testing/CI). Let's say I want to manually test out a particular commit, for example 265bdc777a7e6d141e9a90507817aa8f9e0c7ea3

I clicked on the little green checkmark and went to Azure pipelines page, and downloaded the Release artifact (for x64) - named `drop.zip`. (link [here](https://dev.azure.com/ms/terminal/_build/results?buildId=184228&view=artifacts&pathAsName=false&type=publishedArtifacts))

I tried both appx and Release folders (wt.exe and WindowsTerminalUniversal.exe), tried merging the relevant folders (for x64) and all, but everytime I clicked on wt.exe, the cursor spun for a second and then nothing happens.

So my question is, is there no way to test any commits out without actually building the VS solution?

**Comment by WSLUser** [comment]
There used to be artifacts that you could use to test but when they updated the build pipeline early on last year, the artifacts ceased to be generated as often in order to increase the speed of the build (as slow  as it is, it used to be much slower as a result of generating an  artifact with almost every PR). So if there's a specific commit you want to test, you'll need to build it. VSCode should be able to be used instead  by default in this project if you have the necessary configuration set up.

**Comment by WSLUser** [comment]
Yeah, it's way easier to build in VS as it'll tell you what to install. There are still some random artifacts created (or not, depends if a test build is needed by the MS devs) but you won't find one for every commit.  In order to use an artifact, you'd have to go the unsupported route of running wt.exe directly rather than installing the msix. Also, this project doesn't use Rust so that's not even a factor. I don't think there any plans for a long time to switch to Rust. Alot of deps used are C++ specific though a few are fed in from Nuget.

**Comment by rashil2000** [comment]
> In order to use an artifact, you'd have to go the unsupported route of running wt.exe directly rather than installing the msix.

Yes, that's what I did.

> Also, this project doesn't use Rust so that's not even a factor. I don't think there any plans for a long time to switch to Rust.

I was not saying that this project uses Rust. I was just mentioning why I had Visual Studio Build Tools installed.

**Comment by rashil2000** [comment]
I got it working. The artifact was complete, I was just looking at the wrong msix file.

According to the Readme:
> ### I built and ran the new Terminal, but it looks just like the old console
> 
> Cause: You're launching the incorrect solution in Visual Studio.
> 
> Solution: Make sure you're building & deploying the `CascadiaPackage` project in
> Visual Studio.

I extracted the `CascadiaPackage_0.0.1.0_x64.msix` and used that. Bold text looks awesome!

**Comment by DHowett** [comment]
Glad you got it working! I'd like to provide nightlies and runnable CI artifacts, but we haven't done the leg work to make sure they're code signed and deployable anywhere easily. Alas!

**Comment by rashil2000** [comment]
I imagine it'd be too much trouble to code sign the builds for every commit/PR, but thanks for the consideration!
