### ISSUE TITLE
Windows Terminal randomly closes.

### ISSUE THREAD

**Issue by jhakeinson** [microsoft/terminal#10522]
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Steps to reproduce

Use the Windows Terminal app. This issue is random and hard to reproduce.

### Expected Behavior

Windows Terminal should not close all  my sessions unless I tell it to.

### Actual Behavior

When using the Windows Terminal app, the app suddenly closes. It happens randomly, more than twice, every day. For example, when I am typing a command or waiting for the result of an executed command.  It closes all my sessions, which is annoying.

Here's my Feedback Hub link: https://aka.ms/AAd1c6q

**Comment by zadjii-msft** [comment]
Huh. There's unfortunately no cabs in the feedback link, which makes me think the Terminal didn't actually crash during the feedback hub recording. 

Maybe it just got updated, and force-closed by the Store? Does this still repro for you on 1.8.1521.0?

**Comment by jhakeinson** [comment]
Thanks for responding @zadjii-msft. 

I'm sure that the Terminal is not in the middle of updating when this issue happened. And it happened multiple times randomly (mostly when I'm using my WSL Ubuntu distro). I already tried the following but with no luck:
- Uninstall and reinstall Windows Terminal
- Uninstall and reinstall my WSL distro.
- I set the "Profile termination behavior" options of my Ubuntu profile to "Never automatically terminate".

I'm not really sure how to reproduce this issue because it happens randomly. I'm not sure what triggers it.

**Comment by zadjii-msft** [comment]
Weird. Well, without a consistent repro, or a stack trace, or something, I'm not sure what we can do with this. If you've got windbg installed, you could maybe collect a dump with ["post-mortem debugging"](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/enabling-postmortem-debugging). Otherwise I'm not sure how to get something actionable here 😕

**Comment by jhakeinson** [comment]
Thanks. I will try to repro the issue later with windbg or other debug tools that I can find and send the details here.

**Comment by jhakeinson** [comment]
@zadjii-msft Sorry for the late follow-up for the additional details on this issue.

I tried reproducing the bug and I used Feedback Hub to record everything. Please check this Feedback Hub link:

https://aka.ms/AAd1c6q

Thank you.

**Comment by FurmanSK** [comment]
I've had this happen twice now. I believe I'm using the one from MS store. The programs are still running though and I'm not sure if there's a way to get back to their output without using task manager to close them and restart them. Any more updates on this?

**Comment by zadjii-msft** [comment]
@FurmanSK You're probably looking for #9914. 

I've looked high and low for the crash reported by OP here, and unfortunately, I think it's just lost to the backend. I'm not sure it ever got plumbed all the way through, for whatever reason. If this is still happening, could you try following the steps in [this post](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm) to set up automatic crash dumps? If that works, then you should be able to automatically get a `.dmp` of the terminal when it crashes. Then, can you zip that dump up and send it to us, so we can investigate? Thanks!

**Comment by pif17** [comment]
3 years later, it's still a problem.
No error message, No error number, No stack trace, nothing to help user to have real informations to understand the problem.

**Comment by zadjii-msft** [comment]
@pif17 Almost certainly, you got hit by #18119. We recently pushed an update. The Store probably killed the Terminal to install that update. We tried to ask the store to not do that, but alas, we didn't specify **all** the magic incantation to get the Store to not do that.

**Comment by pif17** [comment]
Thanks for your answer, you may have the good reason.
As simple user, loosing works without explanation is very frustrating.
As advanced user, discovering that is done because you don't have the hand on update and someone far away take you for a child, is very, let's says, disappointing.
As developer, it gives you a taste of unfinished work without plan to back to the original state after crash.
To finish, as embedded and OS developper, we just ask why don't Ms do something reliable  with 2 versions of DLL or EXE loaded in memory, one updated, an other to keep software that use it alive. Waiting for a reload to update.
Your program is nice, it gives more eyes candies that command.com but make it just reliable please, don't let user think they don't do valuable work with uncontrollable update that kills days of work. 
In a perfect world, every opened terminals must be conditions to stop every updates, including windows update, because someone do valuable work on his computer.

**Comment by zdm** [comment]
Same problem for me, all opened terminal windows suddenly closing.
This is very annoying, especially if some jobs were started there.

**Comment by 7F11** [comment]
+1.
In the past two weeks Windows Terminal started to crash randomly. MTBF is about two days.
No keypress is necessary, the idle terminal windows just disappear suddenly.

**Comment by vient** [comment]
Happened and is still happening for me, last time was 5 minutes ago. Store shows that I have v1.21.10351.0 installed - not sure why not v1.22 which seems to be last stable version on github. Maybe v1.21 does not have a fix for mentioned #18119?

**Comment by lhecker** [comment]
If you have crashes please follow our guide for setting up the collection of crashdumps: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically
Then please post a new issue and provide the dump file to us, whether that's as a zipped attachment or via mail. You can find all our mail addresses on our GitHub profiles.

**Comment by vient** [comment]
Found a crash event and from that there is already an issue for my case, #18458. Sorry for the nuisance.

**Comment by arafatjamil01** [comment]
I am facing this issue currently. I open multiple tabs, and suddenly, everything crashes
