### ISSUE TITLE
Fragments with "hidden" field are masked by our generated "hidden" field in the profile stub

### ISSUE THREAD

**Issue by ZeroCoolGOS** [microsoft/terminal#10539]
I am working with the fragments and it is so handy.  One thing I would like to see is a way to allow us to set some of the fragments to hidden within the file.  This way we can easily swap in and out fragments without having to delete entries.

I have a bunch of projects on the go but not all of them are active so I would like to just update my fragment json file and hide them when not in use.

# Proposed technical implementation details (optional)
Just as we have with the regular "Profiles", allowing us to use a [ "hidden": false ] flag in our fragments.

**Comment by PankajBhojwani** [comment]
Thank you for the suggestion!

So this is awkward primarily because of the naming - we cannot call the setting `"hidden"` because technically a fragment can update a profile's `"hidden"` setting, and we won't be able to distinguish between "don't apply this fragment" and "hide this profile". It'll have to be some other special name we think of that should never collide with a future profile setting, and that's the especially tricky part. I'm sure we could probably come up with one, it just bears a little more thinking about!

**Comment by ZeroCoolGOS** [comment]
@PankajBhojwani 

A fragment can update a profile's "hidden" setting?  I am new to the fragments so I will need to do more research on how it works and how I can take more advantage of it.

I also see a flaw in my request.  I am looking for the ability to hide a profile within the fragment.

As you mentioned that "we won't be able to distinguish between "don't apply this fragment" and "hide this profile".", that is what I was going for.  It's fine to apply the fragment, I was just wanting some profiles to be hidden mode so it does not show up on my profile list but still be available in settings.  If I did not want the profile at all then I would just remove it.

I was looking at fragments as just an extension of the standard list of profiles that had all the same functionality but just in a separate json.  Having the ability to have color schemes , backgrounds and such.

**Comment by DHowett** [comment]
So I think the issue is a little sillier than it seems. Not like, "this is a dumb request." More like _Terminal did something that, in retrospect, was silly._

When we generate a profile from an extension _or a fragment_, we insert this snippet into the user's* JSON file:

```
{
    "guid": "{whatever}",
    "name": "My Whatever Profile",
    "hidden": false
}
```

That snippet, which we emitted for a specific reason[^1], is now making it hard for Fragment authors to customize the way they want. The user settings contains `hidden: false`, which _overrides whatever the fragment says for `hidden`_.

We should _seriously_ just fix the overlay generator.

[^1]: Before we had a settings editor UI, we used the JSON snippets for "user discoverable" documentation.

**Comment by DHowett** [comment]
I've renamed this issue to address the need :smile:

**Comment by ZeroCoolGOS** [comment]
@DHowett 

How do we handle Cleanup?  If I remove a profile from my fragment will it be removed from the users's JSON file?

**Comment by zadjii-msft** [comment]
> How do we handle Cleanup? If I remove a profile from my fragment will it be removed from the users's JSON file?

I believe it should be - at least that's what's supposed to happen with dynamic profiles. For those, when the original source doesn't exist for a profile with a `source`, then we automatically hide that profile. 

If that's _not_ happening, then that's another bug 😝

**Comment by DHowett** [comment]
Actually, when a fragment disappears we treat it just like a dynamically generated profile that disappeared ... which is likely to be somewhat incorrect. It will remain in the user's JSON, but it will not appear in the dropdown list.

We did this so that if you deleted Ubuntu, we would keep your customizations for when you eventually reinstalled it. Hopefully.
