### ISSUE TITLE
Left side of text is cut off when maximizing windows terminal on non-primary monitor

### ISSUE THREAD

**Issue by adiviness** [microsoft/terminal#1055]
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```
Microsoft Windows [Version 10.0.18892.1001] 

# Steps to reproduce

Press the maximize button when the terminal is on a non-primary monitor

# Expected behavior

All text should be visible

# Actual behavior

A portion of the leftmost column of cells is cut off. 

The text is fine when maximized on the primary monitor.

**Comment by Archomeda** [comment]
I hope I can provide more information.

For me, this happens when using it on the second display on a dual monitor setup of primary 2560×1440 and secondary 1920x1080. When using two equal displays with 1920x1080, it doesn't happen at all.

Also, it seems that when using it in the first setup, the + button on the titlebar is cut off at the top (possibly the entire titlebar). But in the second setup, it's totally fine.

**Comment by dkter** [comment]
I can reproduce this only with the `showTabsInTitlebar` setting enabled. It looks like about 10px from the top and left are being cut off.

**Comment by mani2jeff** [comment]
I can reproduce on Surface Pro with 19" external monitor (with or without showTabsInTitlebar setting enabled) with all terminal types,
![TerminalExternalLeft](https://user-images.githubusercontent.com/34294809/59958909-34d07900-946b-11e9-9566-f83e79a8bb8c.jpg)

**Comment by YihaoPeng** [comment]
1920x1080 primary display and 3840x2160 non-primary monitor, each has a high DPI scaling factor of 150%.

Terminal on non-primary monitor, left and top is cut off.
![屏幕截图(15)](https://user-images.githubusercontent.com/26923506/59998172-59a63580-9691-11e9-8b89-31777876d136.png)

Terminal on primary monitor, everything is good.
![屏幕截图(16)](https://user-images.githubusercontent.com/26923506/59998200-6aef4200-9691-11e9-9f94-c57a4153bbd9.png)

**Comment by gmckeown** [comment]
Seeing this issue on Dell Precision 5520 with Intel and Nvidia GPUs. Internal screen 1920x1080, external screen one 1920x1080, external screen two 3840x2160. Internal screen is set as primary.

Only see this issue on the 3840x2160 (4K) display. Scaling factor doesn't seem to affect it (tried 100%, 150%, 175%).

Orientation of the screens doesn't obviously make a difference. Normally I have Left (scr two) - Middle (Internal) - Right (scr one). Switched the external screens around so that Windows thinks screen two is on the right, and the issue stays with screen two (the 4K one).

Occurs with PowerShell, PowerShell Core, Windows Cmd, and Ubuntu sessions, including those started after the window is maximised.

**Comment by mani2jeff** [comment]
After my initial post on Friday, when I first noticed the problem, I tried again on Sunday (yesterday) and it was working fine. I don't know why it changed, and I don't think there was an update. However, I am glad it is now working. The external monitor is an older 1280x1024 while the main Surface Pro display is 2736x1824. I give those details for context.

**Comment by gmckeown** [comment]
Still seeing the issue here.

**Comment by benjisoft** [comment]
I am also suffering with this issue. All of my monitors are the same size and scale. (The only difference is the colour profile of the monitor.

**Comment by troybailey36** [comment]
I am also seeing the bottom of the terminal cut off by taskbar as well as the left side
![image](https://user-images.githubusercontent.com/20546806/60196848-17553380-980c-11e9-9314-1ee881a2ba2e.png)

**Comment by miniksa** [comment]
Just FYI, I tried this locally.

It is working fine on my non-primary monitors.
When I change the DPI/scaling of my monitors, it's still OK.

I still will have to go get the 4K monitor and test that way.
And then I'll try with a Surface device and an external monitor after that.

**Comment by gmckeown** [comment]
@miniksa Is there any information we can provide to help track down the cause?

**Comment by davidsantos-br** [comment]
Windows 10.0.18362.207
Terminal 0.2.1715.0 from the Store

My setup is a 1920×1080 main screen and a 1600×900 screen to the left, both at 100% scaling. In the main screen there is no problem, but the problem described in this issue happens in the secondary monitor, at the top, left, and bottom of the window.

**Comment by miniksa** [comment]
@gmckeown, that's a catch-22. If I knew what could help, I'd probably know what was going wrong. Right now, it's just a mystery to me so I need to see it happening and get a debugger on it, or find someone with this issue externally who has the confidence to debug it themselves and tell us what's going wrong.

**Comment by miniksa** [comment]
OK, it does repro on the 4K monitor I found around here. I'll debug it.

**Comment by dsafa** [comment]
I believe it has to do with this [block](https://github.com/microsoft/terminal/blob/d8485079cd8d676cea7dd4400a5233d31ea49829/src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp#L610) where the `_maximizedMargins` is calculated. This check 
```cpp
if (rcMaximum.left == 0)
{
    offset = windowPos->x;
}
else if (rcMaximum.top == 0)
{
    offset = windowPos->y;
}
```
does not work for non primary monitors that are positioned with an offset where `left` and `top` won't be 0.

What I mean by not monitors aligned.
![ApplicationFrameHost_nnfjcbW3g4](https://user-images.githubusercontent.com/7334282/60566209-13994380-9d1b-11e9-9947-4aa927c0eb22.png)
I can reproduce the issue with an arrangement like in the above example. If I change it so that they are arranged side-by-side, then `rcMaximum.top` becomes 0 and it maximizes properly on the second monitor.

**Comment by gmckeown** [comment]
@dsafa I think that fits with my issue. Normally I use:

![image](https://user-images.githubusercontent.com/22765233/60583679-5858c500-9d83-11e9-81c3-65c6dcece9d0.png)

With this, I get the alignment issue. If I change to:

![image](https://user-images.githubusercontent.com/22765233/60583789-90f89e80-9d83-11e9-985f-c7d63efbb382.png)

The problem isn't seen.

**Comment by rw3iss** [comment]
Can confirm this also happens if the monitor alignment in display settings is not aligned to the top or bottom of the main monitor exactly. Thanks for the fix @dsafa

**Comment by davidsantos-br** [comment]
Confirmed. This is my setup, and the issue happens when the window is in monitor 2. If I align the screen to the top of the other, then the issue disappears once I restore and maximize the window again. Notice that this happens to me even when the bottom of the secondary screen is aligned with the bottom of the main screen (it only disappears when the tops of both screens are aligned).

![image](https://user-images.githubusercontent.com/39162/60683891-d0e97f80-9e70-11e9-9983-4cfe7848531b.png)

**Comment by dsafa** [comment]
If its not picked up, I can try and get a PR done later.
