### ISSUE TITLE
Save and open group of tabs in specific directories on single-click

### ISSUE THREAD

**Issue by sheharyarshahid** [microsoft/terminal#10565]
# Description of the new feature/enhancement
Let's say a user work on the set of repositories every day but he has to open a new tab, then navigate to that directory, change the tab's title, set its color, etc. If we could store directory info in some group along with extra arguments (tab title, 
color). So the next time user just clicks on that group and all saved tabs open in their respective directories.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
I like to do like the following:

```json
{ "command": { "action": "wt", "commandline": "new-tab --title OpenConsole cmd.exe /k #work 15 ; split-pane -s .30 --title OpenConsole cmd.exe /k #work 15 ; split-pane  -s .25 -H cmd.exe /k media ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },

```

(you could probably make it shorter by replacing `new-tab`/`split-pane` with `nt`/`sp`, respectively).

I add that to the `keybindings`/`actions`. This creates a new command in the [Command Palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette) named "Good Morning". That opens up a few tabs & panes, running various build environments. I like having it in a command rather than `startupActions`, because I only really want this in _one_ terminal window, not _every single one I launch_. It's personal taste. 

You could repeat this for multiple different "session"s if you wanted. That way you could have layouts pre-defined for various different dev environments. 

We're also tracking adding commands to the new tab dropdown in #1571. So I think I'm gonna call this /dup #1571
