### ISSUE TITLE
Content Resize Slower Than Window Resize

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10635]
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

Resizing the window - the content lags enough so that there's a visual "artifact" of a gray border on the right or bottom where the content hasn't been filled into yet.

I am aware that lots of programs have this problem, even Firefox, the new Windows 11 Microsoft Store, Discord, new Windows 11 Settings App, etc. I don't know if it's like Windows, the GUI frameworks being used, the events being too slow, etc. But it's a pretty common problem, even on other platforms like Linux.

Fixing this would polish up people's systems in general, and make things more enjoyable to use, so I definitely think it's something all programs should work towards fixing.

I was surprised to see some older Windows applications don't have this problem, including Windows 10 Calculator, File Explorer, and a few others.

### Expected Behavior

The content resizing should be as smooth as possible to the window resizing.

### Actual Behavior

> Resizing the Windows - the content lags enough so that there's a visual "artifact" of a gray border on the right or left where the content hasn't been filled into yet.

https://user-images.githubusercontent.com/4098042/125316128-70ae3380-e2fd-11eb-9fa8-68829434341f.mp4

**Comment by zadjii-msft** [comment]
Frankly, this seems like it's not really a Terminal-specific issue, this sounds like something that's better reported at https://github.com/microsoft/microsoft-ui-xaml/. They own the WinUI stack. Though, I'm unsure if this is something that _is_ broadly solvable, considering the breadth of applications that it affects. Firefox certainly isn't a WinUI application, so they must have chosen to implement a similar behavior independently. \<conjecture> IIRC Discord is an electron app, so that's chromium, so same deal - probably convergent evolution. \</conjecture> 

Regardless, that's probably the better issue tracker for interesting discussion on the subject.

**Comment by krixano** [comment]
Ok, I'll just copy this over to that repo then.
