### ISSUE TITLE
Settings Page Animation Restarts When Switching To Settings Tab

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10632]
When you have a setting tab already open and switch back and forth between the Settings tab and any other tab, the animation of the page (where the page content appears vertically centered and moves upward - which is a bit of an odd animation itself) will restart again, even though this isn't the first time opening the page.

It might have been intended, but I find it a little.... odd.

# Proposed technical implementation details (optional)

A different animation might make this appear less odd. Like fade, or any number of animations.

https://user-images.githubusercontent.com/4098042/125307353-9a635c80-e2f5-11eb-896f-d39a75b7345c.mp4

**Comment by DHowett** [comment]
I wonder if this is because of us doing a `Navigate` to the root content view when the settings page comes visible. Perhaps there's something we can do to bind the root content such that it doesn't animate at all on first / subsequent launches. @carlos-zamora this might be related to the view model stuff we were talking about (since doing the navigation in the "code behind" versus as an intrinsic part of the page state may be to blame).

**Comment by DHowett** [comment]
(Thanks for filing this!)

**Comment by carlos-zamora** [comment]
> I wonder if this is because of us doing a `Navigate` to the root content view when the settings page comes visible. Perhaps there's something we can do to bind the root content such that it doesn't animate at all on first / subsequent launches. @carlos-zamora this might be related to the view model stuff we were talking about (since doing the navigation in the "code behind" versus as an intrinsic part of the page state may be to blame).

I did a trace because I was curious. Looks something like this:
- `TerminalPage::_OpenSettingsUI()`: select the settings tab and update content
- `MainPage::SettingsNav_Loaded()`:
   - `if (SettingsNav().SelectedItem() == nullptr)` --> `false`
   - _nothing happens_. Surprisingly, `_Navigate()` is not called!

So yeah, looks like XAML is just doing it for us.

Playing with the XAML controls gallery, I agree that perhaps a [DrillIn](https://docs.microsoft.com/en-us/windows/apps/design/motion/page-transitions#drill) or [Suppress](https://docs.microsoft.com/en-us/windows/apps/design/motion/page-transitions#suppress) may work best. Definitely odd!

**Comment by carlos-zamora** [comment]
> @carlos-zamora - do you have a preference between Drill in or Surpress? 😊

Let's try DrillIn!

**Comment by Don-Vito** [comment]
![DrillIn](https://user-images.githubusercontent.com/4639110/129257459-d9d868ba-541c-4809-adf8-c1a7ae116552.gif)

**Comment by Don-Vito** [comment]
@carlos-zamora - WDYT?

**Comment by Don-Vito** [comment]
OK. Committing :)
