### ISSUE TITLE
Print Dialog Shown Off Screen

### ISSUE THREAD

**Issue by juvtib** [microsoft/terminal#10693]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.9.1942.0

### Other Software

vim 8.2 outside WSL

### Steps to reproduce

1. Install Windows Terminal 1.9 and Vim 8.2 on a new Windows 10 box. 
1. Execute `"C:\Program Files (x86)\Vim\vim82\vim.exe"`
2. Print via `:hardcopy`

### Expected Behavior

I expect the print dialog to be centered on the screen or on the shell like console host. 

### Actual Behavior

The print dialog is positioned past the top-left of the screen. 

To bring the dialog into view: 
1. Click to focus on the dialog. 
2. Press Alt + Space
3. Press m
4. Press Up Arrow to attach the dialog to the mouse cursor. 
5. Move the mouse cursor to drag the dialog into view.

**Comment by zadjii-msft** [comment]
I'm gonna guess that this is /dup #2988. This just has all the same hallmarks of that bug.

**Comment by juvtib** [comment]
I don't think this is a duplicate. I'm talking about x,y not z. When I type `start .` I don't have the same problem as reported in 2988. My issue reproduces today.

**Comment by zadjii-msft** [comment]
Okay yea, I see how that was confusing. Lemme try to explain better:

I'm guessing the root cause of your issue here is that `vim` can't reliably find the HWND of the Terminal. It probably wants to display the print dialog relative to the window that it's running in. I'm guessing that they use `GetConsoleWindow` for that value. However, when running in the Terminal, that value is a garbage value. So instead of it opening near the Terminal, it just defaults to (some location). 

The `start .` repro for #2988 is intermittent, but shares the same root cause.

**Comment by zadjii-msft** [comment]
Okay, even after investigating down all the other leads in #2988, `:hardcopy` is still busted. I'm quite confident that `vim.exe` is getting the actual position of the console window here to try and center the print dialog on top of it. Problem is, `GetConsoleWindow` in any ConPTY session (read: terminal) is going to have a 0x0 sized window as the result of that API. 

This is gonna require some changes on the part of `vim.exe`. They'll need to do some combo of
* maybe use GetAncestor() to try and find the Terminal's HWND as a ROOTOWNER of the console HWND
* Before 1.14, detect that the HWND that's returned is totally transparent (WS_TRANSPARENT), or 0x0 and then just display the print dialog in the center of the screen 

So this is no longer a duplicate issue, it's actually something we can't solve. Sorry!

**Comment by juvtib** [comment]
Thanks for checking into this.
