### ISSUE TITLE
Insert Windows Engineering C++ Compliance Task into Pipelines

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#10735]
Windows engineering compliance requires us to add a task to our pipelines to validate that our code builds with the appropriate compiler/linker options for operating system inclusion. This task represents inserting that task into our pipeline. Follow ons will likely be required for mitigating the warnings/errors and correcting our code or requesting exemptions formally.

**Comment by lhecker** [comment]
In testing I found that `/O2` has the following benefits over the default `/Oxs` for conhost:
* +13% overall throughput with termbench in ConPTY
* -2% binary size -- We make heavy use of C++ templates throughout conhost. I assume that due to this `/O2` despite not using `/Os` produces smaller binaries, as `/O2` implies `/Gy` and `/GF` which allows the many template instances to be deduplicated.

**Comment by miniksa** [comment]
The PkgES side of this particular task will not be updated to fix its blocking issues in time for me to call this 1.11 so kicking it out.
