### ISSUE TITLE
Can't click outside of dropdowns in Settings to dismiss and shadow behind them gets stuck on top

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/terminal#10741]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

Open settings.
Open default profile dropdown

### Actual Behavior

instead the shadow appears on top of the dropdown box

and it can't be light dismissed

**Comment by DHowett** [comment]
Thanks for the report! It looks like this is two bugs.

1. The dropdown cannot be dismissed -- /dup https://github.com/microsoft/microsoft-ui-xaml/issues/3961
2. Shadows overlaying on top of the dropdown -- we're tracking this one internally and hope to have a fix "soon."

**Comment by Poopooracoocoo** [comment]
any chance that we'll see a fix to this?

**Comment by zadjii-msft** [comment]
The bug is pretty firmly out of our hands, it's an upstream bug with XAML Islands: https://github.com/microsoft/microsoft-ui-xaml/issues/3961

I'd reckon that when the Terminal moves to WinUI 3, we'll get this for free, though there's still a few gaps we're working on with the WASDK team to get closed before we can do that.
