### ISSUE TITLE
Debug Assertion Failure 'Expression: vector subscript out of range'"

### ISSUE THREAD

**Issue by compnerd** [microsoft/terminal#1074]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18908.1000]
Windows Terminal version (if applicable): 71e19cd82528d66a0a7867cbed85990cfc1685f1
```

# Steps to reproduce

launch Terminal
create cmd tab
close PowerShell tab via x on tab
type `word^W` into cmd

# Expected behavior

Close the terminal (really, I would like readine completion)

# Actual behavior

Invalid vector access.

Seems that the `_GetFocusedTabIndex` is returning the index unadjusted for the closing of the tab.  I think that `_RemoveTabViewItem` is not readjusting the index. The `shared_ptr` is constructed by indexing into `_tabs` by `_GetFocusedTabIndex`.  That calculates the index by `_tabView.SelectedIndex`  The `_RemoveTabViewItem` does not update the index.  I can not seem to track down where the implementation for the tab bar renderer is handled (I suspect due to the Xaml bits).  Some pointers as to where to start digging would be appreciated.

**Comment by zadjii-msft** [comment]
This might need some deep dive debugging to find out exactly what's happening here. 

You're correct that the tab bar is out of our control - the code is from the Microsoft.UI.Xaml nuget package.

It's entirely possible that there's a bug in the tab bar implementation, because we're using a super early prerelease version. I think it's more likely we're moving the focus ourselves incorrectly.

**Comment by compnerd** [comment]
The one other thing that I noticed that took some time was that the process is not immediately terminated but continues to execute in the background (I was attaching to the wrong conhost!).  I can try to see if I can trace where the focus is adjusted - although pointers would certainly be welcome :-)
