### ISSUE TITLE
Quake Mode only uses default profile

### ISSUE THREAD

**Issue by alexanderrichards** [microsoft/terminal#10796]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

simply summon quake mode window

### Actual Behavior

I can find nowhere in the documentation any way for Quake mode to use anything other than the default profile. I'd like to switch it to use a different profile while keeping the default for the normal terminal window unchanged. Is this possible?

**Comment by zadjii-msft** [comment]
At the moment, not really. 

* You could do something like `wt -w _quake -p {your profile name}` - that'll launch the Terminal into quake mode with the profile of your choice.
* You could always rebind `quakeMode` to a generic [`globalSummon`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-commands) action. That'd let you just summon any Terminal window, not just the quake one.
* Otherwise, you could wait for #9992 to be able to change the `defaultProfile` of the `_quake` window separately from the normal default

**Comment by alexanderrichards** [comment]
Thank you

**Comment by DanEdens** [comment]
I hadn't known about "-w _quake" that is very cool. Thank you!

**Comment by Aonodensetsu** [comment]
linking to a temporary solution for setting up quake on boot:
[start wt minimized](https://github.com/microsoft/terminal/issues/7374#issuecomment-1399518730)
