### ISSUE TITLE
Key combination win+enter not working for global summon

### ISSUE THREAD

**Issue by Areyus** [microsoft/terminal#10817]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

Set "win+enter" as keycode for the globalSummon action in the config and press the buttons. This is the exact line I have in settings.json:
```
{ "command": { "action": "globalSummon", "toggleVisibility": true }, "keys": "win+enter"}, 
```

### Expected Behavior

globalSummon works like it does with other key combinations.

### Actual Behavior

Nothing happens. From what I understood, you cannot bind globalSummon to key combinations that are already used by Windows default shortcuts, but I could not find any action bound to that combination, neither by testing nor by searching online.

**Comment by zadjii-msft** [comment]
Thanks for the report! I'm afraid that <kbd>Win+Enter</kbd> might be one of those keystrokes that's reserved by the system for some reason. I'm not sure why, but we _never_ get that keystroke. There are more details in #4760.

If we ever get to the root cause of that issue, we'll probably follow up in that thread. Thanks!

/dup #4760
