### ISSUE TITLE
`SM ? 25h` by conhost is paired wrongly with a `SM 25 l` (missing `?`)

### ISSUE THREAD

**Issue by christianparpart** [microsoft/terminal#10829]
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

while trying to debug my own terminal emulator i noticed that conhost sends me `SM 25 l`, which is missing the `?` questionmark if it was meant to the the invert of `SM ? 25 h`.

See https://vt100.net/docs/vt510-rm/DECRQM.html#T5-8

ANSI SM does not even have a mode 25 (IIRC) but
DECSM does have, which shows/hides the cursor. I think that was the intend here.

### Steps to reproduce

oh that's hard to tell ya. I don't want to get you to compile my project, but I am pretty sure it is findable without that. Maybe just be looking at what VT sequences conhost generates (`SM 25 l` vs `SM ? 25 h`)?

### Expected Behavior

`SM ? 25 h` is paired with `SM ? 25 l` :)

### Actual Behavior

no question mark :)

**Comment by j4james** [comment]
I believe this was fixed in PR #5181 (see  commit https://github.com/microsoft/terminal/pull/5181/commits/466e8fc654793dd655bf5ddd408b15fe8be7b964).

**Comment by skyline75489** [comment]
Well then it will have to wait for the next related  “Windows Update” to really fix it.😅

**Comment by j4james** [comment]
If you want to make sure that Contour has all the latest fixes, I think it's actually possible to bundle a recent build of openconsole with your app, and use that instead of the conhost that's included in Windows. Although not officially supported yet, apparently both WezTerm and Visual Studio do something like that. For more info, see the discussion in https://github.com/alacritty/alacritty/pull/4501#issuecomment-735445218.

**Comment by christianparpart** [comment]
Thanks James. That is a very appealing idea. :)

**Comment by zadjii-msft** [comment]
@christianparpart The Terminal itself actually also that same method of shipping a conhost side-by-side in our package so we can ingest conpty fixes faster haha. 

For now I guess I'll call this /dup #5181
