### ISSUE TITLE
Vim cursor skips forward on single-letter replace

### ISSUE THREAD

**Issue by LRitzdorf** [microsoft/terminal#10827]
### Windows Terminal version (or Windows build number)

WT v1.9.1942.0; MS Windows v10.0.19043.1110

### Other Software

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  2 2021 22:02:47)
64-bit console version for Windows, downloaded from https://github.com/vim/vim-win32-installer/releases/tag/v8.2.2825#:~:text=Signed%2064-bit%20installer. Patch version 2825.

Powerline v2.7 (Python3). `powerline-status` module, installed via `pip`.
This is not likely to be related to the issue, but I thought I'd include it nonetheless.

### Steps to reproduce

- Open vim. Of the following, set `t_EI` and either of the `t_S*` variables:
```vim
let &t_EI .= "\<Esc>[1 q"
let &t_SR .= "\<Esc>[3 q"
let &t_SI .= "\<Esc>[5 q"
```
- Trigger single-letter replacement mode by pressing `r`.
- The cursor jumps forward, by five characters in my case.

### Expected Behavior

The cursor should not jump forward when single-letter replacement mode is triggered.

### Actual Behavior

The cursor jumps forward, as noted above.

Note that I've tested this same combination of factors in WSL Vim, and the jump does not occur.

**Comment by zadjii-msft** [comment]
> I've tested this same combination of factors in WSL Vim, and the jump does not occur.

Ooooh. That's a good observation. The issue might have a root cause in Win32's VT parser. @DHowett will take a look.

**Comment by DHowett** [comment]
This is unfortunately a vim issue.

When it is printing the `t_SR` value to the screen (and `t_SI`!), it's dumping the escape characters **directly to the screen without letting us parse them.** Here's what it looks like in the console host:

![vim-win32-bad](https://user-images.githubusercontent.com/189190/128424702-4bd6c9fa-5cf5-4a0e-9463-19283a2ac5bb.gif)

This likely stems from the fact that **vim.exe does not support escape sequences on Windows**. When it is connected to Terminal, they _accidentally_ work. This is only an accident -- vim has not put the console in the correct mode to handle this. As a result, though, the cursor virtually moves over to cover the raw sequence (as it should.)

The real bug is unfortunately that Terminal doesn't handle it like Console does.

**Comment by LRitzdorf** [comment]
Rats, that's unfortunate. Thanks for the information, though!

**Comment by alexeicolin** [comment]
If you add a space before the escape sequence, the replace mode becomes usable: the cursor still jumps forward but the extra characters are not shown.

```
  " insert
  let &t_SI = " \e[6 q"
  " replace
  let &t_SR = " \e[4 q"
  " normal
  let &t_EI = " \e[2 q"

  " 1 or 0 -> blinking block
  " 2 -> solid block
  " 3 -> blinking underscore
  " 4 -> solid underscore
  " Recent versions of xterm (282 or above) also support
  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
```

For a true fix, there's a plugin using a native library:
https://github.com/gustaphe/winterm.vim
