### ISSUE TITLE
Switching tabs clears the selection

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#10857]
### Windows Terminal version (or Windows build number)

1.9.1942.0 (repros on WT Preview as well)

### Steps to reproduce

1. Open a new tab (doesn't matter if it's a `SettingsTab` or `TerminalTab`)
2. Go to an open `TerminalTab`
3. Create a selection
4. Switch to the other tab
5. Switch back to the tab with the selection

### Expected Behavior

The selection should still be present.

### Actual Behavior

The selection is missing.

**Comment by Don-Vito** [comment]
This behavior results from `_doResizeUnderLock` clearing active selection, rather than recomputing its position. An additional artifact of this implementation is that resizing the window clears the selection as well.
The long-term solution is to recompute selection position. I will create  a ticket for this.
A short-term solution for this ticket is to avoid resizing if the new view port size equals to the old one.
