### ISSUE TITLE
List of keyboard shortcuts or an accessibility statement?

### ISSUE THREAD

**Issue by mlekkerkerk** [microsoft/terminal#10883]
Can someone point me to a list of keyboard shortcuts or an accessibility statement for Terminal? Thank you!

**Comment by zadjii-msft** [comment]
I'd say the most definitive list of all the keyboard shortcuts is in the raw source itself:

https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/defaults.json#L279-L376

All the things in `actions` that have `keys` with them will act as keybindings. Granted, the user is free to modify the keybindings however they like, so that list may not be entirely correct for all users (depending on their own settings). 

You can also view all the currently bound keys in the Settings UI, on the "Actions" page:
![image](https://user-images.githubusercontent.com/18356694/128417776-ef7e5b02-95f4-4c0b-bd4d-4af1772be712.png)


I believe @cinnamon-msft might have a link to a more definitive "accessibility statement". 

Can I ask what your particular use case is? We might be able to give better advice.

**Comment by mlekkerkerk** [comment]
Hi Mike,
Thank you for this link of the keybindings. I am helping out with an accessibility audit of developer tools to help guide a few students with visual impairments. Trying to understand how accessible tools are so we can support students.


--
Michelle Lekkerkerk, M.A.
Instructional Designer III
P: 800.798.0584 x11987
C: 858.432.8601
zovio.com­­­­<http://www.zovio.com/>

**Comment by carlos-zamora** [comment]
Closing this because it seems answered. Let us know if you need anything else though :)
