### ISSUE TITLE
Shift-click shouldn't extend the selection in VT mouse more

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#10963]
### Windows Terminal version (or Windows build number)

19043.1165

This occurs wit WT-1.9.1942.0 and both with Emacs-27-2 (nox) and NOX builds from master (Emacs28), i.e. running Emacs (from MSYS2 or WSL packages) in WT.

I added this to the `init.el` file:

```
(setq mouse-drag-copy-region t)
```

This means that selecting text double clicking with the mouse or dragging it [*] should copy the selection to the clipboard and it allows for pasting the selection in other apps.

This does not work when running Emacs, MSYS2 package or WSL builds, in WT. 

It DOES WORK when running the same app from MinTTY (MSYS2 or WSL + Emacs nox).

BTW, it works also in Termux+Emacs nox on Android.

So the issue seems related to WT.

-----
[*] Remember that when running Emacs in a terminal, you have to hold down the SHIFT key while clicking or dragging.

**Comment by zadjii-msft** [comment]
> you have to hold down the SHIFT key while clicking or dragging.

Curious, I wasn't aware that there was any sort of input sequence that terminals send to client applications in this scenario to indicate "the user made a selection". I'd imagine that this functionality would only work with emacs's built-in selection handling, and not rely on the Terminal's selection.

@j4james any ideas on this one?

**Comment by DHowett** [comment]
This could be VT200 highlight tracking, perhaps...

**Comment by j4james** [comment]
I have no idea. I also thought it might have been highlight tracking, but it doesn't look like Mintty supports that either, so I don't think it's that. Will require some digging to see what exactly emacs is doing.

**Comment by angelog0** [comment]
Regarding the SHIFT key, see [this](https://www.gnu.org/software/emacs/manual/html_node/emacs/Text_002dOnly-Mouse.html) from the Emacs manual.

**Comment by DHowett** [comment]
We _may_ need a bit more of your `init.el` than that -- `mouse-drag-copy-region` on its own does not enable mouse support here with emacs-nox 26.1 Debian.

**Comment by angelog0** [comment]
Maybe do you mean this:

```
(require 'mouse)                                                                    |
(require 'mwheel)                                                                   |
(unless window-system                                                               |
  (xterm-mouse-mode t)                                                              |
  (mouse-wheel-mode t))

(setq mouse-drag-copy-region t)
```

To select the above text I had to run WSL-Emacs-nox from a MinTTY terminal, dragging the mouse holding SHIFT down and then usin CTRL-v here. Tha same steps from WT did not work.

**Comment by j4james** [comment]
OK, I've had a chance to play in Emacs now and I think I know what's going on. But I don't think it really has anything to do with Emacs.

Basically when app has enabled one of the mouse modes and is intercepting mouse clicks, the terminal obviously loses the ability to use the mouse in the way it usually would (e.g. selecting text and copying it to the clipboard). But if you're holding down shift when you click, those clicks _don't_ get converted to escape sequences, so they'll still be handled by the terminal.

But the problem is that shift-clicking typically means you want to extend the selection, rather than starting a new one, which makes it somewhat difficult to use. As a workaround for this, Mintty seems to disable that shift functionality when an app has enabled mouse mode, which I think is probably a reasonable approach to take - I don't know if that's common behaviour in other terminals though.

The other problem is that auto-copying doesn't seem to be working at all (nothing to do with mouse modes). I'm not sure if this is expected or not, but I thought the "Automatically copy selection to clipboard" option would mean any text that was selected would automatically be copied to the clipboard, but that doesn't seem to be the case - I have to right click to copy. I've only looked briefly, but I didn't see an existing issue for this.

**Comment by j4james** [comment]
I've tried a few other terminals now, and not everyone supports extending a selection with shift-click, but those that do, seem to follow the same behaviour as Mintty, i.e. they disable extended selections when an app has enabled a mouse mode. That way you can use shift-click to get the equivalent of a regular click that will be handled by the terminal.

The terminals I've seen with this behavior include Gnome Terminal, Konsole, and Rxvt.

**Comment by zadjii-msft** [comment]
Wait after having re-read this yesterday, is this the same thing as #9608?

**Comment by j4james** [comment]
Yeah, I think so.

**Comment by zadjii-msft** [comment]
/dup #9608

Thanks for the sanity check!
