### ISSUE TITLE
Can't load see or load profile after changing bellStyle setting

### ISSUE THREAD

**Issue by bcalvery** [microsoft/terminal#10964]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

Ubuntu 20.04

### Steps to reproduce

I have Ubuntu as my default profile in Windows Terminal. And Windows Terminal configured to start automatically.
Open Settings > Profiles > Ubuntu 20.04 > Advanced > Bell Notification Style
Uncheck "Audible"

My resulting settings.json file looks like this:
![image](https://user-images.githubusercontent.com/15043460/129727408-e65a5c54-0ff2-413a-9c6a-ebce4c9271da.png)

This setting change works correctly correctly until the next time I restart the computer. After restarting the computer when Windows Terminal opens I get this:
![image](https://user-images.githubusercontent.com/15043460/129727751-52cc3977-1d1d-4839-b466-3cedf6e238ce.png)
and Ubuntu is no longer visible in the new tab or settings menu:
![image](https://user-images.githubusercontent.com/15043460/129729061-91519ec9-549b-4347-87d0-8cf2a88451c7.png)

If I then go to settings, open the settings.json and delete the line `"bellStyle": "none",` from the Ubuntu profile, that profile immediately becomes visible again.

### Expected Behavior

I expect changing a profile's "Bell Notification Style" (bellStyle) property by unchecking "Audible" (changing value to "none") to **not** cause the profile to fail to load.

### Actual Behavior

Changing a profile's "Bell Notification Style" (bellStyle) property by unchecking "Audible" (changing value to "none") causes terminal to be unable to load that profile.

**Comment by zadjii-msft** [comment]
Alright so I think the bell style thing might just be a [red herring](https://c.tenor.com/PACZT4i8fEIAAAAC/communism-red-herring.gif) here. WSL is actually notoriously bad at telling the Terminal in a reasonable period of time what the list of profiles is. 

See for example: #6160, #7199, #9905. The "restarting the computer" bit of the repro also is a good givaway that the issue is due to the fact that the _first_ time wsl.exe is launched, it starts up fairly slowly.

/dup #6160
