### ISSUE TITLE
Automatic gift character

### ISSUE THREAD

**Issue by he852100** [microsoft/terminal#11013]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Other Software

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19043.0 Microsoft Windows NT 10.0.19043.0

### Steps to reproduce

 $d=iwr https://camtasia-help.netlify.app/feed.xml
 $d.RawContent

### Expected Behavior

ps >

### Actual Behavior

PS > [?1;0c

**Comment by he852100** [comment]
Windows Terminal
版本: 1.9.1942.0

**Comment by zadjii-msft** [comment]
Does this repro in the vintage console host window (i.e. `cmd.exe`), or only in the Windows Terminal? Does this repro after running `Remove-module PsReadline`?

**Comment by j4james** [comment]
I believe this is a variant of #10310 and #10069. The content of the feed is encoded as UTF-8, but it looks like PowerShell is interpreting it as an 8-byte charset, so any bytes in the range 0x80 to 0x9F are going to be interpreted as C1 control characters. Code point 0x9A in particular is the equivalent of the `DECID` command, and thus triggers the _primary device attributes_ response.

Changing the code page to 65001 didn't seem to make any difference, but maybe that's the way `RawContent` is meant to work.

**Comment by j4james** [comment]
Note that this probably won't show in the vintage console, because we didn't support all C1 control characters until PR #7340, and I don't think that would have been included in build 19043 of Windows.

Also note that it's not necessarily dependent on PowerShell. You can reproduce the same think in a WSL shell by switching to 8-bit first (with something like `printf "\e%%@"`), and then using `curl` to fetch the feed content.
