### ISSUE TITLE
Weird fonts on Windows Server 2022

### ISSUE THREAD

**Issue by faxx1080** [microsoft/terminal#11032]
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

Fresh install of Windows Server 2022 Evaluation, straight from https://www.microsoft.com/en-us/evalcenter/. Did not yet check for updates.

### Steps to reproduce

Install latest preview appxbundle using Add-AppxPackage.
Running Windows Server on VMWare Workstation 16.1.2 build-17966106.

### Expected Behavior

![Capture](https://user-images.githubusercontent.com/5386539/130711009-6386559b-4483-464b-b29a-cc1f7aa3e98f.PNG)

This is how cascadia code normally looks.

### Actual Behavior

This is what I got. Doesn't quite seem right.

![Capture-bad](https://user-images.githubusercontent.com/5386539/130711034-f689df41-172c-43c1-ae8c-3ade7a1e0649.PNG)

**Comment by zadjii-msft** [comment]
Okay this is wild. If you go into something like Microsoft Word, or anything that has a font picker, and go through that list, does "Cascadia Code" appear in that list? And does it appear in the dropdown list in the Terminal? We just got an internal report of the same thing that suggested that the font was uninstalled?

**Comment by rmbolger** [comment]
I'm having the same issue on a recently installed, non-domain joined, Windows Server 2022 Standard (version 21H2, build 20348.202) VM. It sure seems like whatever the default font is just doesn't get installed.

The `Font face` field in the Terminal appearance settings is just empty for the profile. I haven't tried to make any settings changes yet.

![terminal-settings-no-fontface](https://user-images.githubusercontent.com/2327255/131880540-fe0148c0-2f4a-4a23-853f-4bd2e9b519b9.png)

Word Pad doesn't show any Cascadia related fonts in the list.

![wordpad-no-cascadia](https://user-images.githubusercontent.com/2327255/131880597-ccec4f05-65ca-4789-a0ab-90ed8b969df8.png)

I installed the `Microsoft.WindowsTerminal_1.10.2383.0_8wekyb3d8bbwe.msixbundle` via Add-AppxPackage. The only other things I currently have installed on this box are Pwsh 7.1.4, the latest VS Code (user install), and VMware Tools 11.1.

**Comment by zadjii-msft** [comment]
> The `Font face` field in the Terminal appearance settings is just empty for the profile. It's also not listed in the picker.

> WordPad doesn't show any Cascadia related fonts in the list.

WHAT THE 

That's WILDLY unexpected, but definitely explains why you're seeing what you're seeing. It doesn't make sense, but that at least explains it. The Cascadia family of fonts should be shipping in our package:
https://github.com/microsoft/terminal/blob/6268a4779c9b3f49b7f3c30471bda7ae292ac423/src/cascadia/CascadiaPackage/Package.appxmanifest#L140-L149

But if they're not getting installed when you install the Terminal, then a bunch of stuff will break. We pretty consistently rely on those fonts existing.

**Comment by rmbolger** [comment]
I notice in that same file, there's a Dependencies section that seems to only target `Windows.Desktop`. Might that be part of the problem? (just grasping at straws)

https://github.com/microsoft/terminal/blob/6268a4779c9b3f49b7f3c30471bda7ae292ac423/src/cascadia/CascadiaPackage/Package.appxmanifest#L29-L31

**Comment by j4james** [comment]
Something interesting I noticed about the `SharedFonts` extension: the documentation [here](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap7-sharedfonts) suggests it's in the `uap7` namespace, the linked article [here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#share-fonts-with-other-windows-applications) claims it's in the `uap2` namespace, and the example package in that article uses the `uap4` namespace. It also lists `uap4` in the `IgnorableNamespaces` attribute, which seems like a good idea, because clearly nobody knows what namespace it really belongs to! 😉

I also noticed that example includes the extension at the `Application` level rather than the `Package` level, which might make a difference.

I too know zero about MSIX, so maybe none of this matters.

**Comment by zadjii-msft** [comment]
That seems unlikely to me - #11041 looks like the same thing, and that wasn't on a Server SKU, and the internal report we had of this wasn't either. But I like where your head is at!

We've had some notorious difficulty with the MSIX platform and our font in the past. In the last release, this actually just caused the Terminal to crash on startup if the font wasn't found. Now I suppose we survive, but find ourselves in a state where the font can't be found in XAML. We'll need to think about this.

**Comment by zadjii-msft** [comment]
> Something interesting I noticed about the `SharedFonts` extension: the documentation [here](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap7-sharedfonts) suggests it's in the `uap7` namespace, the linked article [here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#share-fonts-with-other-windows-applications) claims it's in the `uap2` namespace, and the example package in that article uses the `uap4` namespace. It also lists `uap4` in the `IgnorableNamespaces` attribute, which seems like a good idea, because clearly nobody knows what namespace it really belongs to! 😉

What the _heck_. That's a great observation

**Comment by DHowett** [comment]
> I notice in that same file, there's a Dependencies section that seems to only target `Windows.Desktop`. Might that be part of the problem? (I know zero about MSIX, just grasping at straws)
> 
> https://github.com/microsoft/terminal/blob/6268a4779c9b3f49b7f3c30471bda7ae292ac423/src/cascadia/CascadiaPackage/Package.appxmanifest#L29-L31

I believed that Windows.Desktop covered "all things where Windows presents as a normal desktop OS" (including Server), but we can validate that. That dependency, however, blocks _installation_ if it is not present...

**Comment by DHowett** [comment]
Would one of you mind collecting a recursive export of the registry key `HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Fonts`?

**Comment by rmbolger** [comment]
That key exists, but is empty on my Server 2022 VM. Here's the export and a view from the regedit GUI.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Fonts]
```

![hkcu-fonts](https://user-images.githubusercontent.com/2327255/131909737-aa815140-53ef-4f71-8755-a26e547401a7.png)

**Comment by DHowett** [comment]
A-HA!

It looks like the "Shared Font" deployment helper (a deployment helper is something that runs when an MSIX is installed) isn't built into Windows Server. That's _great_ for us to know. Thanks!

**Comment by DHowett** [comment]
The thing I don't totally understand is why our side-by-side font loader didn't load it. @miniksa might know more, or be able to troubleshoot it from here. We explicitly look for fonts in our own package and try to load them...

This might suggest a root cause for the weird letter selection, if it's not working totally properly, or if we're doing font fallback with a collection that doesn't contain Cascadia.

**Comment by ianjoneill** [comment]
I was intrigued by this, so I span up a Windows Server 2022 VM and deployed the code from `main` to it using the VS remote debugging tools.

The `DxFontInfo` class is successfully finding the font files next to the application. The first time it deployed it didn't copy the Cascadia fonts into the remote deployment directory, which lead to the font falling back to Consolas and the fallback font dialog being displayed.

I then copied the font into the remote deployment directory and got the weird font rendering.

Adding in some simple `OutputDebugString()` statements to `DxFontInfo::_FindFontFace()`, I found that `_NearbyCollection()` is successfully finding the fonts, and `_FindFontFace()` is successfully loading the font family and creating the font face.

Unfortunately I haven't had time to do any further debugging, but it looks like the issue is higher up in the application than the font loading.

**Comment by ianjoneill** [comment]
I've got it working in a _very_ bodgy way - need to work out how to do this properly.

![image](https://user-images.githubusercontent.com/5821575/132647819-948ecdfc-7eb8-4ad5-b1f8-56a0182b9c52.png)

**Comment by zadjii-msft** [comment]
@ianjoneill woah, great progress on this! I'm glad someone's got a beat on fixing this, because I was fairly lost on where to go next.

**Comment by miniksa** [comment]
> I've got it working in a _very_ bodgy way - need to work out how to do this properly.
> 
> ![image](https://user-images.githubusercontent.com/5821575/132647819-948ecdfc-7eb8-4ad5-b1f8-56a0182b9c52.png)

Can you show the branch with the bodgy fix? What was the underlying problem?

**Comment by ianjoneill** [comment]
@miniksa the _very_ bodgy fix is here - https://github.com/ianjoneill/terminal/commit/6427bf842408b1a4fad1de1628ca3b1414eeade1 - it is just a proof of concept to show the problem.

I made `_nearbyCollection` public, and updated `DxFontRenderData::_BuildTextFormat()` to use `_nearbyCollection` rather than the system font collection.

With regards to doing this properly, I don't know if there's some way of creating a view over both the system font collection and the nearby collection, or whether a custom "container" would need to be created and stored in a field. Unfortunately I have zero knowledge of DirectWrite.

**Comment by miniksa** [comment]
I have non-zero knowledge and access to the OS source behind it. Let me noodle on this a bit.

**Comment by ianjoneill** [comment]
On a related note, the settings UI won't show the Cascadia font either, because it only loads the fonts from the system font collection.

**Comment by miniksa** [comment]
Nnnnnnnnnnnnnnnnnnnnn. OK. Thanks.

**Comment by miniksa** [comment]
OK I think I've got it. We need to change the way we handle the fallback to the font in the package.

Instead of running this process where we check the system collection and then fallback and check the nearby collection... I believe we need to make it so there's just one merged collection of both and then use that ANYWHERE in the application where a collection is needed.

So the _nearbyCollection is probably no longer a property of DxFontInfo as it has little to do with the chosen font and is more just a representation of the world.

We just need to... on startup of the rendering pipeline... use `::GetSystemFontCollection` on one of the `IDWriteFactory` levels to get the system collection. (Probably `IDWriteFactory3` so it gives us a `IDWriteFontCollection1` straight up.) Then we need to use `IDWriteFontCollection1::GetFontSet` to get the underlying `IDWriteFontSet` from it. We then follow most of the contents of `DxFontInfo::_NearbyCollection` to create an `IDWriteFontSetBuilder` and use `IDWriteFontSetBuilder::AddFontSet` to put the system font set into the set builder first. Then we continue to use `IDWriteFontSetBuilder2::AddFontFile` to append the files next to our binary into the collection. Then we return that as a `IDWriteFontCollection/1` and use that anywhere in the application where we're currently passing `nullptr` and having it load the system collection like for creating the `IDWriteTextFormat` and probably somehow exposing it to TerminalSettingsModel so it can pick it up and use it in `ProfileViewModel::UpdateFontList()`.

**Comment by DHowett** [comment]
If you do this, is it possible to ensure that the system fonts win over the nearby ones? Eventually, when we decouple Cascadia, we will be able to freeze down a "backup" version and we don't want it to defeat the system-installed version if it is newer.

**Comment by miniksa** [comment]
> If you do this, is it possible to ensure that the system fonts win over the nearby ones? Eventually, when we decouple Cascadia, we will be able to freeze down a "backup" version and we don't want it to defeat the system-installed version if it is newer.

I am 78% sure that putting the System Font Set in first and then appending the package one next will make that be the order of priority.

**Comment by miniksa** [comment]
@fdwr... opinion on my shenanigans?

**Comment by fdwr** [comment]
> I am 78% sure that putting the System Font Set in first and then appending the package one next will make that be the order of priority.

@miniksa : Yes, a tie between two of the same font in the font set (or in the old hierarchical WWS collection) is broken by addition order, favoring earlier indices. (there was a brief bug in Win 8.1 selfhost where it was sometimes not fully deterministic if you overflowed the font collection cache size, but I fixed that, and it should AFAIK still behave where first-wins-in-tie)

> This is what I got. Doesn't quite seem right.

Interesting screenshot. It seems the `m` and `w` are being uniformly scaled to fit into the grid cell (maybe for the sake of fat emoji). At least for m and w (and other alphabetic letters), it *might* look better to scale them with a non-uniform aspect ratio (that is, only squeeze them horizontally to make them skinnier - granted, this would make the stems thinner too). Though, I'm assuming Terminal (under *normal* circumstances) doesn't select proportional fonts in the first place.

**Comment by miniksa** [comment]
> > I am 78% sure that putting the System Font Set in first and then appending the package one next will make that be the order of priority.
> 
> @miniksa : Yes, a tie between two of the same font in the font set (or in the old hierarchical WWS collection) is broken by addition order, favoring earlier indices. (there was a brief bug in Win 8.1 selfhost where it was sometimes not fully deterministic if you overflowed the font collection cache size, but I fixed that, and it should AFAIK still behave with first-index-wins-the-tie)

Excellent. Thank you.

> > This is what I got. Doesn't quite seem right.
> 
> Interesting screenshot. It seems the `m` and `w` are being uniformly scaled to fit into the grid cell (maybe for the sake of fat emoji). At least for m and w (and other alphabetic letters), it _might_ look better to scale them with a non-uniform aspect ratio (that is, only squeeze them horizontally to make them skinnier - granted, this would make the stems thinner too). Though, I'm assuming Terminal (under _normal_ circumstances) doesn't select proportional fonts in the first place.

Yes and yes. You're correct that my scaling algorithm is probably suboptimal here using a uniform aspect ratio and that the Terminal strongly avoids selecting proportional fonts under normal circumstances.

**Comment by faxx1080** [comment]
I've been keeping up with this intermittently and really want to say a thank you!! to all I've learned about font edge cases here, as well as what's really changed since classic Windows (XP and up).

Not being familiar with most (sadly) of the C++ code of terminal; I "solved" this on my VM by going into the appx directory, right clicking install on all the Cascadia Code fonts. But that's even worse than the above quick fix, since I needed admin for that, and that was a system-level change. But it did solve the issue!

I also had a Windows 11 test nearby and installed Windows Terminal Preview there, and found that Cascadia Code works fine in the terminal and settings; as well as Notepad / Old Conhost, but doesn't appear in C:\Windows\Fonts; nor does it appear in the old Fonts control panel.

**Comment by fdwr** [comment]
> but doesn't appear in C:\Windows\Fonts; nor does it appear in the old Fonts control panel.

IIRC, the old fontext.dll enumerated the registry itself directly rather than going through GDI or DirectWrite. So it would not know about "per user" fonts, unless additional work was done to it 🤔. I *think* the shell verb "Install" (forget which OS version this happened) now installs fonts into `%LOCALAPPDATA%\Microsoft\Windows\Fonts\` (e.g. c:\Users\fdwr\AppData\Local\Microsoft\Windows\Fonts\NotoColorEmoji.ttf) using `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`, whereas "Install for all users" installs to the old `c:\Windows\Fonts\` using `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`.

**Comment by elevul** [comment]
Problem was solved for me on 2 Server 2022 installs after installing the Cascadia Code fonts: https://github.com/microsoft/cascadia-code
