### ISSUE TITLE
ssh features

### ISSUE THREAD

**Issue by Mortaza-Seydi** [microsoft/terminal#11034]
# Description of the new feature/enhancement

i want to suggest some new features about ssh.
1. password: store ssh passwords in ssh profiles and perform auto connect. so the user does not need to type passwords every time.
2. sftp: users can see host files and abale to upload or download files.
3. dynamic port forwarding: when user connect to ssh, he could add or remove any port forwards.

**Comment by WSLUser** [comment]
Windows Terminal is not the place for storing passwords. Putty offers this as it's a dedicated to remote connections and includes a built-in password manager. However since VSCode allows this via extension such as https://github.com/SchoofsKelvin/vscode-sshfs or the official Remote-SSH, WT can support this via extension as well. Just needs to be tagged up in https://github.com/microsoft/terminal/issues/4000
