### ISSUE TITLE
Bug Report Flickering background if background image is set

### ISSUE THREAD

**Issue by Summon528** [microsoft/terminal#1103]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.145]
Windows Terminal version (if applicable): 880272c74

Any other software?
```

# Steps to reproduce
1. Set terminal to light theme
2. Set a dark background image in a profile
3. Open a new tab with that profile

# Expected behavior

# Actual behavior
Screen flickered
[Imgur](https://i.imgur.com/K102pTf.gif)

Related to #853, probably because dxrender layer overwrites background image for a little bit amount of time

**Comment by DHowett** [comment]
This could also be #1082?

**Comment by Summon528** [comment]
Actually I believe not, that one is happening when acrylic is on and background image is off. This one is the opposite. Also the draft fix (#1092) does not fix this one

**Comment by DHowett-MSFT** [comment]
Perhaps the real issue in both #1082 and this issue is that the control is added to the UI tree before the background change is propagated into the renderer.

https://github.com/microsoft/terminal/blob/097f7d32a632d2bc5480bdb17fff1fb2622c5e46/src/cascadia/TerminalControl/TermControl.cpp#L287-L289

This function dispatches the background update into the settings/down into the renderer only after the root control's dispatcher has a free cycle, which will almost certainly be after it's been installed into the TermApp's content grid.

Good catch, @summon528.

@d-bingham If you don't mind terribly, would you consider this for #1092 as well? Let's try to knock out all the flashing bugs at once.

**Comment by d-bingham** [comment]
Easy enough to add to #1092, but in fiddling with it for a few minutes I don't have much of a reproduction -- @Summon528 can you provide a profiles.json that shows it?

**Comment by DHowett-MSFT** [comment]
Actually, yeah, I'm trying with this and I can't repro it:

```json
        {
            "guid": "{dec46506-2b06-458e-975d-5f04d0b9927f}",
            "name": "Repro",
            "colorScheme": "URXVT",
	    "background": "#ff0000",
	    "backgroundImage": "C:\\windows\\system32\\FeatureToastBulldogImg.png",
            "historySize": 9001,
            "snapOnInput": true,
            "cursorColor": "#de00de",
            "cursorShape": "filledBox",
            "commandline": "cmd.exe",
            "fontFace": "Consolas",
            "fontSize": 12,
            "acrylicOpacity": 0.85,
            "useAcrylic": false,
            "closeOnExit": true,
            "padding": "8"
        },
```

maybe it needs to be a large image/something slow to load/something from a remote server? I see some very minor flickering when I use an image directly from the web.

**Comment by d-bingham** [comment]
I haven't been able to get the flicker on a new tab to happen reliably (with using an image over the network to introduce _some_ sort of delay), but can get it to happen reliably by opening a tab and then closing it (causing the flicker to happen after the tab close but before the original tab is re-displayed).

From doing some testing the flicker is the default background brush (which will be white-ish in the Windows light theme and black-ish int he Windows dark theme) being drawn while it waits for the image to be loaded into the brush -- so if you've got a dark image in the dark theme it's not particularly noticeable, but it is definitely so with a dark image and a light theme.

Working on getting the async handling of image loading working a bit better by setting up a solid color brush on the background (using the profile's default background color) while waiting for the image to load, _and_ keeping the image itself in the profile instead of each individual tab, so it can be reused effectively.

**Comment by Summon528** [comment]
> maybe it needs to be a large image/something slow to load/something from a remote server? I see some very minor flickering when I use an image directly from the web.

I guess this is the key, cause I'm loading a gif from the web 😜

**Comment by Muchiachio** [comment]
This repros with or without a background/acrylic on bash from `Git for Windows (2.28.0)` maybe related and easier to repro?
Pressing backspace/arrow keys on empty terminal always flashes white color.
![flashing](https://user-images.githubusercontent.com/6647444/90341584-71fdb000-e009-11ea-8e35-6e17da4c660b.gif)

**Comment by Summon528** [comment]
Yeah sure, it's way less annoying now
