### ISSUE TITLE
Show Tabs in Quake Mode

### ISSUE THREAD

**Issue by i-love-code** [microsoft/terminal#11085]
# Description of the new feature/enhancement

When you have the quake-style console open, show the "Tab Bar" above the console so you can visualize & navigate between multiple open consoles.

The only way to do this today is to open the quake console (Win+`) and then use Win+Shift+T to open new tabs and Cntrl+T to navigate between them. It works, but it's almost impossible to know how many consoles/tabs you have open and select the correct one.

![gif](https://i.gyazo.com/6a17d21109cdca29ecb500a799850e6e.gif)

**Use Case**

It's a very common case for local .NET development I'm running:
- A console at the source control root (for git purposes)
- A console at (each) .NET project folder (running each "dotnet watch run")
- A console at (each) frontend application
- A console for running NPM unit tests

Having each of these in the quake-style console is ideal, which I can do, but I never know which tab is where since you can't see those tabs easily.

# Proposed technical implementation details (optional)
Ideally, it would just reuse the existing tab interface of the non-quake windows terminal and remove the top right minimize/maximize UI.

![image](https://user-images.githubusercontent.com/1737733/131409082-3ae1e79b-335f-4fcd-8c73-22bf662b38d7.png)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #9992 for more discussion.

/dup #9992

**Comment by jrogers512** [comment]
#9992 doesn't look like a duplicate of this.  Or at least, it is a much more complex/broad issue than this rather simple one.  

As it stands now, while in quake mode:

- I cannot see what tabs or open, or how many of them are open.
- I cannot quickly switch to the tab I'd like to (other terminals allow this by pressing alt+window number, or allow you to click on the tab.  We cannot see the tab in the quake window, so there is nothing to click)
- when pressing Ctrl-D, typing `exit`, or `logout`, you see `[process exited with code 127]`, but there is no way to close the tab (again, since I cannot see the tab at the top of the window, there is no option to select an `X` to close the tab, or right click the tab)

**Comment by zadjii-msft** [comment]
It's a little confusing how #9992 gets what you want, but lemme try to clarify:

* The `_quake` window is a kind of special window right now. Imagine that it has properties `launchMode:focus, snapTo:top, minimizeToTray:true` set. 
* #9992 will let you change the properties for certain window names. So that would let you remove the `launchMode:focus` aspect of the `_quake` window.
* You can always just bind <kbd>win+\`</kbd> to a plain-old `globalSummon` action. The terminal won't automatically snap to the top like the `_quake` window does, but we'll add that feature soon<sup>tm</sup>
* In the `_quake` window, you can always leave focus mode with the Command Palette (on <kbd>Ctrl+Shift+P</kbd>)
* You can always close tabs with <kbd>Ctrl+Shift+w</kbd>
* You can already [switch to various tabs](https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalSettingsModel/defaults.json#L330-L338) with <kbd>Ctrl+alt+1-9</kbd>
* with `"tabSwitcherMode": "inOrder",` or `"tabSwitcherMode": "mru",` the tab switcher on <kbd>Ctrl+tab</kbd> will show you a list of tabs

Did I miss anything?

**Comment by ninjasitm** [comment]
Hello,

Chiming in here. The solution proposed here is very ineligant.

A simple tab bar as described by @i-love-code would be the most efficent solution. For reference check out the solution implemented here https://github.com/flyingpie/windows-terminal-quake which does provide this UI.

**Comment by i-love-code** [comment]
For @ninjasitm and @jrogers512 and anyone finding this thread later:

I also don't agree with "Quake" mode not a better UI natively, but here's a quick workaround that works super well. It's not well documented but you can open the Quake mode and then `Control + P` which brings up the command palette **inside** the quake window and you search for "Focus" and you'll find an option called `Toggle Focus Mode`. It brings up tabs in the quake mode.

The setting doesn't get saved and it's super annoying to enable each time, but it is what it is.

**Comment by nathanvv** [comment]
You could also set the shortcut for the Toggle Focus mode on your profile to make @i-love-code suggestion easier  {  "command": "toggleFocusMode", "keys": "shift+f12" },

**Comment by NSurtsev** [comment]
Tabs in Quake mode should be displayed like in Linux, in the bottom of Quake-Terminal.
Just copy Linux. Everything has already been invented years ago.

**Comment by sryze** [comment]
I think the placement of tabs should be configurable, e.g. top or bottom, or hide them altogether / hide when only one tab is open (for tmux users).

**Comment by zadjii-msft** [comment]
@sryze We're tracking that in #835 and #7210, go 👍 those 😉

**Comment by zohozer** [comment]
I accidentaly got into this Quake mode and I can't find any way to return to the normal windows. How to disable this mode?

**Comment by b-hayes** [comment]
quake mode should just be a normal terminal that appears at from the top. No need for it to be different in any way. Its rpety silly not having the tabs imo. The so called duplicate issues seem to be covering a lot more than simply keeping tabs visible in quake mode. No need to customize them or do anything special just dont hide the tabs in quake mode.

**Comment by ivellios** [comment]
Is this ever going to be addressed? I like Terminal and use it a lot, but since I am using iTerm2 in Quake Mode the same way on my other computer, I'd like to have it consistent across the setups. And lack of tabs is just frustrating - I have to remember what's what...

**Comment by Neoony** [comment]
Same here
I use ConEmu for quake mode and it has tabs
I wanted to switch to Terminal, but this is holding me back

The screenshot in "Proposed technical implementation details" looks perfect, thats all we need

EDIT: after a lot of messing with it, trying to somehow make it show the tabs.
Eventually found out
After it starts (have to do every time), press CTRL + SHIFT + P and "Toggle focus mode"
Then it starts showing the tabs in quake mode

Another issue is that this must be done every time it starts.
Can bind it to a key in Actions
At least something

This does not seem to help
"startupActions": "toggleFocusMode",

**Comment by b-hayes** [comment]
Issue is closed so they dont care. I dont see what the issue is hey. Either make the focus toggle the default or just get rid of quake mode and make the global shortcut just activate and minimise a regular window.

Either approach is would literally take less time to implement than reading the comments on this issue.

**Comment by zadjii-msft** [comment]
> Issue is closed so they dont care

my dude, it's closed as a _duplicate_. There's literally another thread tracking the work for fixing this. Having multiple threads for the same discussion creates unnecessary noise.

**Comment by b-hayes** [comment]
As other have said the duplicate is not the same issue but that point was ignored.
Additionally the duplicate is 3 years old now.
THIS issue is literally a 10 minute job.

**Comment by DHowett** [comment]
> THIS issue is literally a 10 minute job.

We would love to review a pull request and credit you as a contributor!
