### ISSUE TITLE
Documentation Issue: Debugging closes running instances

### ISSUE THREAD

**Issue by shuffle2** [microsoft/terminal#1110]
Compiling and debugging a Debug build will cause all currently running Release instances of Terminal to close. This is inconvenient if you actually use Terminal and also wish to debug it.

Maybe this is expected WinRT behavior, but it seems crazy and unexpected to me; there should be a warning in the documentation somewhere (or preferably, the behavior should be prevented).

**Comment by DHowett-MSFT** [comment]
This is expected and non-negotiable. We ship a second application manifest that’s used for official builds so that those _won’t_ be closed when you deploy an in-development build.

**Comment by DHowett-MSFT** [comment]
We'll provide some guidance here.

**Comment by DHowett-MSFT** [comment]
On account of this having not come up in quite some time, not gotten any significant community traction or concern, I'm gonna close this one out. The number of people using WindowsTerminalDev (the development build) in the wild as their _actual day-to-day terminal emulator_ is dangerously close to zero now that we've released the public preview, so the impact of this issue is significantly reduced.
