### ISSUE TITLE
Crashing when trying to read address 0x0000000000000000

### ISSUE THREAD

**Issue by herkulessi** [microsoft/terminal#11142]
### Windows Terminal version (or Windows build number)

Win32NT 10.0.19043.0 Microsoft Windows NT 10.0.19043.0

### Steps to reproduce

1. Wake up PC from Hibernation
2. Quickly open Wintows Terminal twice (I used Win+1)

I could NOT reproduce this.

### Expected Behavior

Two Windows Terminal windows opening.

### Actual Behavior

One Terminal Window opened and I got the following Error message: 
<img width="299" alt="WinTerm Crash" src="https://user-images.githubusercontent.com/31536990/132104701-b6f58213-1741-410c-8909-d8ddfdb91bef.png">
Loose translation from german to English:
WindowsTerminal.exe - Error in Application
The instruction at 0x00007FF87423790E points to RAM at 0x0000000000000000. The action read couldn't be carried out in RAM.

Press "OK" to end the Application.

**Comment by zadjii-msft** [comment]
Weird. I've never seen this particular error dialog ever before. [Looking around the web](https://www.google.com/search?q=%22points+to+RAM+at+0x0000000000000000%22&oq=%22points+to+RAM+at+0x0000000000000000%22&aqs=edge..69i57.643j0j1&sourceid=chrome&ie=UTF-8), it seems that this is something that can happen to any program, randomly. Also see [this search](
https://www.google.com/search?q=%22Attempt+to+write+data+to+address%22&sxsrf=AOaemvK3eGdIEtP1zFM-DozoTz-FeQvlXA%3A1631639920360&ei=cNlAYYmsFYWF9PwPh-eksAw&oq=%22Attempt+to+write+data+to+address%22&gs_lcp=Cgdnd3Mtd2l6EAMyBggAEAUQHjoHCAAQRxCwA0oECEEYAFCEvhlYhL4ZYMrAGWgCcAJ4AIABlgGIAZYBkgEDMC4xmAEAoAECoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwiJpOqu_P7yAhWFAp0JHYczCcYQ4dUDCA4&uact=5). Might be that your RAM just got hit with a cosmic ray, or it's dying. I'm especially inclined to believe that hypothesis since

> I could NOT reproduce this.

If you can get this to repro with any regularity, maybe we can reopen and see what what we find.
