### ISSUE TITLE
Word Not Snipping windows terminal properly

### ISSUE THREAD

**Issue by mehulminat** [microsoft/terminal#11151]
### Windows Terminal version (or Windows build number)

10.0.19041.1110

### Other Software

Word 2019 Pro Plus

### Steps to reproduce

Open a word document and try to add photo using Insert-> screenshot.
It will be showing a preview of grayed screen . 
![image](https://user-images.githubusercontent.com/72225679/132140789-aa2306f9-3a4e-49b8-b501-58f4dadcf4ec.png)

### Expected Behavior

It was expected to show the contents of that specific terminal chosen including the text . Like it word with any other window

### Actual Behavior

It just snipped gray window.
![image](https://user-images.githubusercontent.com/72225679/132140842-8dcf23f8-11c2-4499-9570-5cf53e8b6aa1.png)

But manual snipping using snip tool is working perfectly fine.

**Comment by elsaco** [comment]
This issue manifest in other MS Office products. I tried Excel & PowerPoint and the content of WT is not showing when using "Insert->Screenshot->Available Windows" option. It grabs the content of a PowerShell session, the old style not launched in a WT session.

However, this issue seems to be more than what was reported by mehulminat. In World no content from other application is being inserted by this method. Trying a screenshot from Chrome browser it resulted in a gray box inside the document. Maybe this should be a MS Office bug.

**Comment by mehulminat** [comment]
> However, this issue seems to be more than what was reported by mehulminat.

Yes , this seems to be an bug with MS Office Products because it can't grab Calculator and many other window but successful in grabbing cmd, powershell , controlpanel, windows explorer

**Comment by WSLUser** [comment]
This is an issue with UWP, which WT pretends to be. (Technically WT is Win32 with a UWP wrapper). I'd file a suggestion in Feedback Hub for each of the Office products requesting this support be added. I'm pretty sure they all use the same code for this, so a change in one product hopefully makes it to the others.

**Comment by zadjii-msft** [comment]
> This is an issue with UWP, which WT pretends to be. (Technically WT is Win32 with a UWP wrapper

Lets just stop using these terms, because they frankly don't reflect the state of Windows in 2021. The Terminal is a Win32 application that uses XAML. 

My guess would have been that Office is having troubles with things that render with DX to a swapchain, but if they're having troubles with Calculator as well, then they might just have problems with all XAML applications. I don't see anything about it on the WinUI repo though...

**Comment by zadjii-msft** [comment]
Filed this on Office to start the discussion. For my own notes, the string `fdcl_v4_eb5f5d37884552d38d2fe68af744570b` should return exactly one email in my inbox. 

There's likely nothing for us to do on our end here, other than apply pressure where possible. For janitorial purposes, I'm gonna close this one out. Thanks!
