### ISSUE TITLE
WT not respecting new tab index defined in default.json

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11173]
### Windows Terminal version (or Windows build number)

10.0.19043.0 1.9.1942.0

### Steps to reproduce

- open a new tab with ctrl+shift+1 for tab index 0
- open a new tab with ctrl+shift+8 for tab index 7
- open a new tab with ctrl+shift+9 for tab index 8
- open a new tab with crtl+shift+0+9 <--this key combination should not be allowed but it opens a new tab

### Expected Behavior

New tab to be assigned to the index specified in default.json.

### Actual Behavior

New tabs are added sequentially. Using above example when opening a new tab with  ctrl+shift+9  it became tab index 1. If crtl+shift+9 is used again tab index 2 is opened. So, crtl+alt+9 will not switch to tab index 8, because there is no such tab index.

crtl+shift+0+9 or any other 1-9 key should not open a new tab when an extra key is added to the combination. In fact, any additional key (numbers + letters) added to crtl+shift+number will open a new tab, i.e crtl+shift+a+1.

**Comment by zadjii-msft** [comment]
So, the Terminal doesn't actually receive any keyboard events that are like `modifier+modifier+key+key` - it's only going to get `modifier+modifier+key`. So one of those non-modifier keys was surely pressed first, and that's the one that the terminal is going to perform.

Also, `ctrl+shift+0` isn't bound to _anything_, so that definitely won't do anything. 

https://github.com/microsoft/terminal/blob/0a48836e831023e3a3411ab5471fe21feb5e0b0a/src/cascadia/TerminalSettingsModel/defaults.json#L314-L322


What might be happening though is pressing `crtl+shift+0+9` is sending a `ctrl+shift+0` and a `ctrl+shift+9`.

Does that help explain what's going on?
