### ISSUE TITLE
Bug: ctrl+break is not ctrl+c

### ISSUE THREAD

**Issue by Cologler** [microsoft/terminal#1119]
# Steps to reproduce

1. open windows terminal for cmd.exe
1. execute command `ping 8.8.8.8 -t`
1. press `ctrl`+`break`

# Expected behavior

windows terminal show ctrl+break

# Actual behavior

windows terminal show ctrl+c

**Comment by Cologler** [comment]
ctrl+break and ctrl+c have a different meanings in ping command.

``` txt
Usage: ping [-t] [-a] [-n count] [-l size] [-f] [-i TTL] [-v TOS]
            [-r count] [-s count] [[-j host-list] | [-k host-list]]
            [-w timeout] [-R] [-S srcaddr] [-c compartment] [-p]
            [-4] [-6] target_name

Options:
    -t             Ping the specified host until stopped.
                   To see statistics and continue - type Control-Break;
                   To stop - type Control-C.
```

**Comment by MrAusnadian** [comment]
See attached. Ctrl+Break works in standard command prompt, however Windows Terminal processes Ctrl+Break as pressing Ctrl+C:
![Capture](https://user-images.githubusercontent.com/9650258/59328846-4a42e780-8ca2-11e9-9051-d383366ef364.JPG)

**Comment by szalapski** [comment]
Is there a workaround?  How do I send an actual Ctrl+Break?

**Comment by int19h** [comment]
This is affecting some apps that only respect Ctrl+Break. For example, it appears to be impossible to stop a tox+pytest test run without closing the tab, or killing the process from another one.

**Comment by zadjii-msft** [comment]
Alright, I finally dug out my keyboard that has a break key to investigate this. 

#### In `conhost`

<kbd>ctrl+break</kbd>
```
Down: 1 Repeat: 1 KeyCode: 0x11 ScanCode: 0x1d Char: \0 (0x0) KeyState: 0x28
Down: 0 Repeat: 1 KeyCode: 0x3 ScanCode: 0x46 Char: ^C (0x3) KeyState: 0x128
Down: 0 Repeat: 1 KeyCode: 0x11 ScanCode: 0x1d Char: \0 (0x0) KeyState: 0x20
```

<kbd>ctrl+c</kbd>
```
Down: 1 Repeat: 1 KeyCode: 0x11 ScanCode: 0x1d Char: \0 (0x0) KeyState: 0x28
Down: 0 Repeat: 1 KeyCode: 0x43 ScanCode: 0x2e Char: ^C (0x3) KeyState: 0x28
Down: 0 Repeat: 1 KeyCode: 0x11 ScanCode: 0x1d Char: \0 (0x0) KeyState: 0x20
```

#### In `gnome-terminal`, `xterm`

This is the part that gets interesting: <kbd>ctrl+break</kbd> isn't actually encoded as _anything_. I can't find any documentation that <kbd>ctrl+break</kbd> should send anything in VT - presumably because that's supposed to send a signal of some kind, not a key that the client app can understand.

#### Conclusions

Since conpty at this point is limited to things that can be encoded in VT, there's no way for us to be able to send a sequence specifically for <kbd>ctrl+break</kbd>. #879 is our megathread that's tracking adding support for additional keys that currently aren't encodable in VT - I'm going to parent this bug to that thread.

**Comment by lempax** [comment]
I also experienced this issue on v0.10.781.0. I do hope this will be fixed as I am already accustomed to command prompt using this feature. Thanks.
