### ISSUE TITLE
Incorrect contextual menu text (as if you had the Preview version installed) in Spanish.

### ISSUE THREAD

**Issue by franzarmas** [microsoft/terminal#11197]
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Steps to reproduce

Right click on the desktop.

### Actual Behavior

I have installed the Windows Terminal (No Preview), Embark the text of the contextual menu when the system has the SPANISH LANGUAGE Set out: "Abrir en Terminal Windows en vista previa".

But when I change the language of my system to English, it comes out correctly: "Open in Windows Terminal"

- When my language is in Spanish.
![](https://i.imgur.com/ZPfhP3h.png)

- When my language is in English.
![](https://i.imgur.com/gdgegQT.png)

**Comment by zadjii-msft** [comment]
Curious. Must be a localization bug. Thanks for filing this!

**Comment by lhecker** [comment]
We've renamed "Windows Terminal" to "Terminal" and we'll soon release a new version where the context menu says "Abrir en la versión preliminar de Termina". So technically we can close this issue now.

I don't speak spanish, but it shouldn't it be translated as "Abrir en vista previa de Terminal"? Or is "Abrir en la versión preliminar de Termina" perhaps fine as well?

**Comment by rubenalamina** [comment]
I speak Spanish natively and I guess it can go both ways but I think the most appropriate one should be "Abrir en vista previa de Terminal". Just because Microsoft products in general have been using preview more as "vista previa" instead of "versión preliminar" recently if memory doesn't fail me. I've seen both used interchangeably though. As a side note, it's complicated when something as simple as preview can have different meanings or uses in some languages.

Maybe someone else has a different or more informed opinion on this.

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/180468960-0246b8b0-9f90-40a5-8134-35f23512dc1d.png)

Looks like this is what the loc team settled on.
