### ISSUE TITLE
Please merge the + and v buttons, so you can hold it.⋯ is for the other options, just like Edge.

### ISSUE THREAD

**Issue by kevincrans** [microsoft/terminal#11223]
# Description of the new feature/enhancement

It's to merge 2 buttons with the same purpose. This will make it more clean and match the Edge GUI.

# Proposed technical implementation details (optional)

Settings, command palette and default move to the ⋯ menu, + will become the V hold menu with default under the pointer for quick release, to keep the same functionality.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I don't think we should do this, since it totally hides the presence of the dropdown menu. If we did this, there would be no indication that there's any reason to press and hold the plus button to find the dropdown. Plus, there's no <kbd>...</kbd> button currently, so we'd be removing one button and then immediately adding another 😉
