### ISSUE TITLE
some key combinations are not sent to console (PowerShell)

### ISSUE THREAD

**Issue by MohammadMD1383** [microsoft/terminal#11271]
### Windows Terminal version (or Windows build number)

10.0.19043.0

### Other Software

PowerShell 7

### Steps to reproduce

![image](https://user-images.githubusercontent.com/69088224/133889538-80905a49-4c2e-4250-99cf-f696fce93364.png)

### Expected Behavior

pressing ctrl+up -> move terminal one line up

### Actual Behavior

nothing happens.
the key combination is not being sent to PowerShell

**Comment by zadjii-msft** [comment]
Are you trying to do this in the Windows Terminal or a vintage console window (`conhost.exe`, i.e. what you get from running `pwsh.exe` directly)?

**Comment by MohammadMD1383** [comment]
I'm using windows terminal with default profile of `pwsh.exe`

**Comment by j4james** [comment]
I'm not much of a PowerShell user, so forgive my ignorance, but is the intent of the `ScrollDisplay` functions to pan the viewport over the scrollback buffer? Because if that's the case, I wouldn't expect it to work. The key combinations are probably getting through fine, but PowerShell would have no way of controlling the viewport position in Windows Terminal. This is essentially the same problem as issues #9622 and #10191.

**Comment by zadjii-msft** [comment]
> is the intent of the `ScrollDisplay` functions to pan the viewport over the scrollback buffer

I am pretty sure that's how that works.

You may be interested in the [various different scrolling actions in the Terminal](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#scrollback-commands), which are bound by default to:

https://github.com/microsoft/terminal/blob/0a7310dee4c36f1c423c58b958ffbdbb164ce140/src/cascadia/TerminalSettingsModel/defaults.json#L383-L390

**Comment by MohammadMD1383** [comment]
@zadjii-msft thank you. that helped
