### ISSUE TITLE
command line text editors in Linux (nano,vim) are not working

### ISSUE THREAD

**Issue by oholimoli** [microsoft/terminal#11291]
### Windows Terminal version (or Windows build number)

1.11.2421.0, Microsoft Windows [Version 10.0.18363.1679]

### Steps to reproduce

When I connect to a linux server with SSH and I try to edit a file with a command line editor like nano or vim it is not possible to edit the text file. Is it possible to fix this?

### Expected Behavior

When I use the git bash in Windows everything is ok:

```
[root@server~]# echo "test" > test.txt
[root@server~]# cat test.txt
hello
[root@server~]# nano test.txt
```

![image](https://user-images.githubusercontent.com/47213738/134128306-38a975f0-ebde-49b3-8ff4-745a73875fcf.png)

### Actual Behavior

```
[root@server~]# echo "test" > test.txt
[root@server~]# cat test.txt
hello
[root@server~]# nano test.txt
```

![image](https://user-images.githubusercontent.com/47213738/134128695-b7332276-9a83-40c7-908d-b6379f81c3be.png)

**Comment by zadjii-msft** [comment]
Which version of `ssh` are you using? What's `TERM` set to once you log into the remote machine? Does this repro in a vintage console window (i.e. `conhost.exe`?)

**Comment by oholimoli** [comment]
I just updated ssh to `OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3`

Still the same problem :(. Somehow I can use nano only in the GitBash.

**Comment by zadjii-msft** [comment]
> What's `TERM` set to once you log into the remote machine? Does this repro in a vintage console window (i.e. `conhost.exe`?)

**Comment by zadjii-msft** [comment]
The Windows Terminal doesn't set `TERM` itself, but the git bash terminal (mintty) likely does. I'd be curious to know what `TERM` was set to on that machine when you first remoted into it. The Windows Terminal should be roughly equivalent to `TERM=xterm-256color`, but yea I'd guess that `linux` would work too.

**Comment by oholimoli** [comment]
The server runs CentOS. The value of `TERM `was `dumb`??. I changed it to linux:
`echo "export TERM=linux" >> ~/.bashrc`

Now everything seems to work fine.

**Comment by zadjii-msft** [comment]
Well, that sure is `dumb` 😝 glad you figured this out!

**Comment by samvanbrussel** [comment]
`vim `and `nano `used to work in the past on my Ubuntu Server 20.04.3 LTS and Raspberry Pi OS 10 (buster). Since I had to do an install of Raspberry Pi OS 11 (bullseye), I noticed that it didn't work any more.

After a lot of research, I noticed it stopped working everywhere, not just on bullseye, so it should be related to my client (Windows Server 2019, ssh via native PowerShell, PowerShell 7 and Command Prompt). So something has changed in Linux (via updates) or Windows (via updates).

Executing `export TERM=linux` before using `nano `or `vim `works. Otherwise, they also work but you get a blank screen and can't see what you're typing (unless you close you editor and go back to the prompt, then everything you did appears).
