### ISSUE TITLE
Option for a confirmation prompt before closing a tab

### ISSUE THREAD

**Issue by aminya** [microsoft/terminal#11335]
# Description of the new feature/enhancement

It would be nice to have an option so that there is a confirmation prompt before the user closes a tab. 

This is useful for long-running tabs that are doing something in the background and the user might close them by mistake.

# Proposed technical implementation details (optional)

**Comment by heysujal** [comment]
I would like to work on this issue. Can you please guide me on how to proceed ?

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6549 for more discussion.

/dup #6549

@heysujal I wrote a pseudo-spec for this over in https://github.com/microsoft/terminal/issues/6549#issuecomment-675494526. I haven't had the opportunity to socialize that with the rest of the team really, but if we had code in front of us I'm sure we'd find the time 😝 If you can find a way to detect that there are multiple client apps connected, that might be a useful place to start. `ConptyConnection` is the class that actually represents the connection between the Terminal and the client app, so that's where I'd start.
