### ISSUE TITLE
Command palette search issue

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11503]
### Windows Terminal version (or Windows build number)

main a89c3e2f

### Other Software

Windows 10.0.22471.0

### Steps to reproduce

1. ctrl+shift+p to open command palette
2. enter a search string
3. observer results

### Expected Behavior

1. command names containing searched string

### Actual Behavior

Commands not containing the searched string are being shown. In this case "select" was entered and two commands were returned:

1. Select color scheme <--expected
2. Close all tabs after the current tab <--unrelated to "select"

Please note the bold fonts (red underline) in the screenshot, all part of "select":

![wt_select_string](https://user-images.githubusercontent.com/3933920/137235695-d1afd3d2-f15c-47c5-9d5c-adad6879bb76.png)
:

**Comment by zadjii-msft** [comment]
This is absolutely by design - the command palette offers "fuzzy matching", so something like `sls` will get you "Select color scheme":
![image](https://user-images.githubusercontent.com/18356694/137236450-c6b54ce7-2e96-4c01-8d07-84048c0894ba.png)

or `nt` will get you "new tab" (et. al.)
![image](https://user-images.githubusercontent.com/18356694/137236522-a17b53d6-fd09-446b-b5c7-4db36dfd372e.png)


As described in the spec:
https://github.com/microsoft/terminal/blob/main/doc/specs/%232046%20-%20Command%20Palette.md#action-mode-1
