### ISSUE TITLE
Add a setting to trim out `Administrator: ` if it's the start of the title

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#11502]
talked with someone internally. They suggested this, it was a good idea.

_hot take_: on by default. Meshes nice with the shield in #11224.

linking: #5000

**Comment by DHowett** [comment]
Linking #984!

**Comment by malxau** [comment]
Note "Administrator" is a localized string.

Is there a way that CMD can detect it's running under WT and change its behavior?  This string was added right at the end of Vista when there wasn't time to do something better - the shield icon that WT now has is the kind of thing we really wanted back then.

**Comment by zadjii-msft** [comment]
I'm closing this one out as rejected, because of the aforementioned localization issue with `cmd.exe`. I'm 99% sure we won't be able to reverse engineer what that string is, nor will we get our localization to exactly match, since cmd.exe is localized in more languages than the Terminal. 

Setting the title with the commandline, or manually with an action, is probably a better solution. Thanks to @malxau for some (all important) historical context here!

**Comment by dmitrii-fediuk** [comment]
[A working solution for `cmd`](https://df.tips/t/topic/1566)

**Comment by DHowett** [comment]
Making modifications to system files that are under the protection of SFC or are part of the WinSxS store can cause reliability issues and--in particularly bad cases--break Windows Update. I appreciate that you've found a solution (and thank you for sharing it!), but since this is a Microsoft-moderated repository I can't in good conscience direct users to it.

(I wouldn't care so much usually, but we just had a bunch of reports of people being unable to upgrade because they deleted curl.exe from System32.)
