### ISSUE TITLE
Preference for font size

### ISSUE THREAD

**Issue by aruehl** [microsoft/terminal#11516]
# Description of the new feature/enhancement

New Terminals starts on my system with a to large font size. I have to decrease four or five steps.

# Proposed technical implementation details (optional)

An option to set the default font size for each terminal app would be great.

**Comment by j4james** [comment]
Is there some reason you can't use the _Font size_ option on the _Profile Appearance_ page?
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#font-size

And if you're using the Windows Terminal Preview, you can set a default size for all profiles on the _Defaults_ page.
https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-10-release/#user-defaults

Otherwise if you're using the retail version, you should still be able to set the default value in `"defaults"` section of the settings.json file.

**Comment by zadjii-msft** [comment]
Couldn't have answered it better myself. Thanks!
