### ISSUE TITLE
Re-registered WSL distro profiles do not get auto generated on terminal restart unless state.json is deleted.

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#11510]
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19043.1237]

### Other Software

WSL

### Steps to reproduce

- close terminal
- re-register an existing WSL distribution which had an existing profile in WT before
- remove that profile from WT's config
- open terminal
- config file does NOT contain the new distribution's auto-generated profile

### Expected Behavior

An auto-generated profile for the WSL distro which was registered.

### Actual Behavior

A profile is not added automatically, to make WT add the profile, the state.json file must be deleted, and the terminal must be reopened.

I'm just blindly guessing but I'm assuming this bug as to do w caching existing profiles in state.json, wt looks at the guid in state.json, assumes thats already generated, and skips trying to generate it again for the config.

Also, just for my own curiosity, how are the GUIDs generated for a distro? Is it a uuid v5 with the terminal uuid namespace? I registered a custom distro using `wsl --import` and it gave it a GUID too. A uuid v5 is what i could tell from the source code, but i tried generating some UUID v5s myself using the terminal's runtime namespace and the name of the distro, and the results weren't the same.

**Comment by nosed1ve** [comment]
Ok so I may have found the cause,

Before:

![image](https://user-images.githubusercontent.com/67145097/137368092-4cc0921b-e68b-4b8e-a0da-692718a4171c.png)


As you can see, `state.json` has the `Ubuntu` distro's GUID in the `generatedProfiles` array.

Now lets assume that the user decides to uninstall Ubuntu, and hence removes the Ubuntu profile from `settings.json`,

![image](https://user-images.githubusercontent.com/67145097/137368291-74b52954-5df6-469e-ac6e-ed7f16a546d2.png)


As you can see, the GUID of `Ubuntu` isn't removed from `state.json` upon removing it from `settings.json`.

Now lets assume that the user decides to reinstall Ubuntu again, and restarts Windows Terminal, since the GUID of Ubuntu is still in the generatedProfiles array even thought the profile IS NOT generated, the Ubuntu profile won't be regenerated this time, hence causing the bug.

The workaround has been to remove the GUID of that distro which is still stuck in state.json and make any modification to the config causing the state.json file to be rewritten.

**Comment by andreyvdl** [comment]
So i had this problem just now when re-registering Debian, i notice that it didn't created the Debian profile even when i wanted to duplicate.

To resolve what i did was delete all `generatedProfiles` in `state.json` that wasn't in use in `settings.json`, then i go to duplicate a profile, and this time Debian was a option.
