### ISSUE TITLE
Add support for Double-Height and Double-Width text to Windows Terminal

### ISSUE THREAD

**Issue by german-one** [microsoft/terminal#11595]
# Description of the new feature/enhancement

At least Windows 11 ships with a conhost version which supports `DECDHL` and `DECDWL`. I'm used to telling people who are asking for a better VT support something like "Hey, check out the shiny Windows Terminal. It supports quite some escape sequences that the console host does not, and you can even set it as default terminal app." Now I have to add "... unless you're looking for double height/width text where you explicitly have to use the good ol' console." This feels rather odd 😄

# Proposed technical implementation details (optional)

Consider adding this feature to Windows Terminal. 
However, from what I've read, the current architecture of conpty doesn't seem to be ready yet. So, I suppose a lot of refactoring would be necessary to get to the preconditions 😧

Related: #7865, #8664
cc @j4james

**Comment by j4james** [comment]
FYI, I've been playing around with part two of this recently, and I've got a solution which I think is not too terrible.

By default it won't affect the conpty output at all, but once you write anything with a double size, it switches to a mode where every line will be output with a line rendition prefix (it has to do this because it has no easy way of tracking the line rendition state in the client terminal). It remains in this mode until you do something like a cls, which resets everything to single width, and then it can safely switch back the initial mode.

So it's a bit hacky, and not exactly optimal when you're using double size text, but that's still better than nothing. And for anyone that isn't using line attributes, it shouldn't impact them at all.

What do you think? Would you be happy to accept a PR with this approach?

**Comment by german-one** [comment]
@j4james 
I second your ...
> that's still better than nothing

... as long as you are satisfied. (I know you're actually fighting to get as close to the original behavior as possible.)
<br>

> but once you write anything with a double size, it switches to a mode where every line will be output with a line rendition prefix

Sorry for my ignorance about graphics. This doesn't mean that the whole viewport is turned to double size incl. the existing text, right? 
<br>

> It remains in this mode until you do something like a cls

I hope something less drastic would work, too 😆
<br>

> Would you be happy to accept a PR with this approach?

I guess you didn't ask me since my approval is worth nothing. However, yes I would.

**Comment by j4james** [comment]
> > but once you write anything with a double size, it switches to a mode where every line will be output with a line rendition prefix
> 
> Sorry for my ignorance about graphics. This doesn't mean that the whole viewport is turned to double size incl. the existing text, right?

No, it's not as bad as that. Each line has its own state - could be single width, double width, the top half of a double height line, or the bottom half of a double height line. What I mean is that we have to write out that line rendition state every time we refresh a line. So even if everything is single width, you'll still see all the lines prefixed with a single-width sequence (`\e#5`), until the system figures out that it's safe to stop doing that.

> > It remains in this mode until you do something like a cls
> 
> I hope something less drastic would work, too 😆

It's basically any event that will force the full viewport to repaint. Clearing the screen is just the most common case. Some forms of scrolling could probably trigger it too. I suspect all of these cases are likely to be fairly drastic though.

That said, I would have thought most times you're using double size text would be in a full screen application from which you'd exit with a clear screen, or alt buffer switch. And if not, worst case is you're getting a bunch of unnecessary 3-byte prefixes in your output for a while.

If this turns out to be a massive performance issue, we can always look at optimising it further in the future. I just didn't want to overcomplicate the initial fix if it wasn't absolutely necessary. And long term I'm still hoping we'll get full passthrough mode working, but that seems to be stalled at the moment with miniksa gone.

**Comment by german-one** [comment]
Haha, I've been under the impression that cls was necessary for turning back to default size 😄 Apparently I missed the fact that you've been only talking about the additional line state. I don't expect this to be a big performance issue btw.

> I would have thought most times you're using double size text would be in a full screen application from which you'd exit with a clear screen, or alt buffer switch.

Not necessarily. It's a nice way to emphasize a heading to separate it from body text.
