### ISSUE TITLE
Terminal window does not focus when UWP apps are focused

### ISSUE THREAD

**Issue by r33int** [microsoft/terminal#11601]
### Windows Terminal version (or Windows build number)

10.0.22000.0 1.11.2921.0

### Steps to reproduce

- Use WIndows Terminal as a default terminal (new feature in Windows 11)
- Open an UWP app and focus its window
- Run any shell program from Search or Win+R (cmd.exe, powershell.exe)

### Expected Behavior

Windows Terminal window should open in the foreground and be focused, as it does when a Win32 window is focused.

### Actual Behavior

Windows Terminal opens in the background, and maximizing the window is needed to reveal it. I have attached a video that shows the problem.

https://user-images.githubusercontent.com/22567851/138613233-dc9a7980-049a-4c53-8eec-58388b20651b.mp4

**Comment by zadjii-msft** [comment]
Hey it's been a few months since this was filed, and hopefully some fixes have flowed out. I can't say for sure, but I suspect if this was in fact the [issue we were thinking of](https://github.com/microsoft/terminal/issues/11601#issuecomment-953046385), then it should probably have shipped by now. Any chance you're still seeing this on a newer Win11 build?
