### ISSUE TITLE
"Open with Windows Terminal" context menu starts Windows Terminal at wrong path

### ISSUE THREAD

**Issue by Namorzyny** [microsoft/terminal#11652]
### Windows Terminal version (or Windows build number)

10.0.22000.0, 1.11.2921.0

### Steps to reproduce

Create a folder named `[xxxx` and `[xxxx]`, open them, and use the "Open with Windows Terminal" context menu to open Windows Terminal.

### Actual Behavior

If you start Windows Terminal with the "Open with Windows Terminal" option in a folder that name begins with `[`, it will switch the current directory to `C:\`, or a folder that name begins with `[` and ends with `]` it will switch the current directory to `C:\Windows\System32\WindowsPowerShell\v1.0`.

**Comment by DHowett** [comment]
Unfortunately, this is a PowerShell issue. The version of PowerShell that comes with Windows cannot handle being started in a folder that has `[]` in it. PowerShell 6+ _does_ properly handle it, however.

**Comment by Namorzyny** [comment]
Is there a workaround for this issue? Using the context menu with holding shift key and select the option "Open with Powershell" works well.

**Comment by zadjii-msft** [comment]
Well, that's certainly interesting, but I'd expect that's an artifact of how they implemented theiy context menu handler (rather than just fixing the underlying bug...?)

The workaround would be update to the latest PowerShell, which supports this just fine. If you're really stuck on Windows PowerShell (v5), then I'm not sure there's much else that can be done here I'm afraid ;__;
