### ISSUE TITLE
"Open in Windows Terminal Preview" context menu launch 2 window even if "open windows from a previous session" option selected

### ISSUE THREAD

**Issue by prime167** [microsoft/terminal#11662]
### Windows Terminal version (or Windows build number)

19043.1288,1.12.2931.0

### Steps to reproduce

1. Install Preview 1.2
2. Select "open windows from a previous session" option
3. Open some tabs in window terminal
4. close window
5. Open a folder
6. Right click in folder, click "Open in Windows Terminal Preview" 
7. 2 Windows Terminal windows opened, one with pervious session, one with a default profile tab

### Expected Behavior

Only 1 window with tabs in previous session open 

### Actual Behavior

2 Windows opend 

Note:
1. open in start menu has correct behavior
2. Open in powertoy's power run has correct behavior

**Comment by zadjii-msft** [comment]
This is by design - the Terminal is opening a new tab in the directory you chose. As the Terminal launches, it sees that you had some tabs saved, and that you would also like to open a new tab, so it restores the old tabs, then also opens a new window for the new tab. 

This is kinda like the way a browser behaves, if you have some tabs saved in Chrome and then run `chrome github.com`, it'll open the saved tabs _and_ a new window for github.com. 

If we didn't do this, then opening a terminal with the context menu like this would overwrite any saved state, which I don't think anyone wants 😆 

Thanks!
