### ISSUE TITLE
Weird behavior when terminal is focused

### ISSUE THREAD

**Issue by qubisc** [microsoft/terminal#11673]
### Windows Terminal version (or Windows build number)

1.10.2714.0

### Other Software

Any

### Steps to reproduce

Set focus on Windows Termial(any app) 
hold control and any char like a,b,c...
Go over minimize/maximize/close

or

While holding the combination click on mazimize and then drag the terminal to set the default size

### Expected Behavior

Nothing should happen

### Actual Behavior

While hovering over minimize/maximize/close the symbols disappear. 
While maximizing and dragging the terminal to default size, the app freezes.

**Comment by zadjii-msft** [comment]
Can you maybe capture a video of what you're seeing? (something like ScreenToGif would work well). I'm not sure I'm seeing this locally. 

I am seeing the mouse pointer hiding, but that's... kinda by design, with the whole "hide pointer on input" thing. It's definitely weird, but not totally unexpected. 

If the caption button icons were missing though, or the Terminal was hung, then that's definitely unexpected. 

If the hang is reproducible, when the Terminal is frozen like this, could you grab a dump with Task Manager and send it to us? 

![image](https://user-images.githubusercontent.com/18356694/135876584-e48514d6-26c0-49da-ae28-b8c5d66dc2a3.png)
