### ISSUE TITLE
Can't reorder tabs when opened as administrator

### ISSUE THREAD

**Issue by sfreed141** [microsoft/terminal#11681]
### Windows Terminal version (or Windows build number)

10.0.22000.0

### Steps to reproduce

Open Windows Terminal as admistrator and create a new tab (so you have at least 2). Try to reorder the tabs (click + drag).

### Expected Behavior

Ability to reorder tabs (works when Windows Terminal is launched without admin privileges).

### Actual Behavior

Can't reorder tabs.

**Comment by zadjii-msft** [comment]
This is by design. Please make sure to [search for duplicates ](https://github.com/microsoft/terminal/issues?q=is%3Aissue+reorder+tabs+administrator+)when filing new issues.  This is something that we can't support right now due to some platform limitations. Turns out, even if we tried to support reordering tabs while elevated, the application would actually just crash 😨. See #4874, #5564 and others for more details.

/dup #6893
