### ISSUE TITLE
Font size change via scroll wheel does not work when in tmux

### ISSUE THREAD

**Issue by fredrikaverpil** [microsoft/terminal#11744]
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

WSL2: Ubuntu 20.04 LTS
ZSH: 5.8
tmux: 3.0a-2ubuntu0.3 amd64
tmuxinator: focal 1.1.4-3

### Steps to reproduce

Using .tmux profile:

```
# enable mouse
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# use zsh as the default shell
set-option -g default-shell /bin/zsh
```

I would have expected to be able to use the scroll wheel on my mouse (while pressing Ctrl) to be able to change the font size. This, however, does not work. I can use <kbd>Ctrl</kbd> + <kbd>+</kbd> and <kbd>Ctrl</kbd> + <kbd>-</kbd> but the scroll wheel would've been much nicer.

### Expected Behavior

While pressing <kbd>Ctrl</kbd> the scroll wheel would change the font size in tmux sessions.

### Actual Behavior

While pressing <kbd>Ctrl</kbd> the scroll wheel has no effect in tmux sessions.

**Comment by zadjii-msft** [comment]
I feel like we've had this discussion somewhere else on the repo before. Since tmux requested mouse mode, we give them the first shot at all mouse events. tmux can't say "I didn't handle that" for a mouse message, we have to just assume they always did. Typically, the way we get around that is but including the <kbd>shift</kbd> modifier in any of the Terminal-level bindings, but alas, <kbd>ctrl+shift+wheel</kbd> is "bound" to "adjust opacity", so that won't work. Lemme keep looking.

**Comment by zadjii-msft** [comment]
#4875? maybe?

**Comment by fredrikaverpil** [comment]
@zadjii-msft let's 🤞 and close this?
