### ISSUE TITLE
GetConsoleWindow() returns nonsense instead of NULL in 1809 when there is no console.

### ISSUE THREAD

**Issue by EricYoungdale** [microsoft/terminal#1175]
Up to and including 1803, a call to GetConsoleWindow() will return NULL if the process has no console.  In 1809, it seems to just return some uninitialized variable instead.

The enclosed testcase demonstrates this.  It launches a child using the CREATE_NO_WINDOW flag, and passing pipe handles as the std handles.  The child reports back (via the pipe) to the launcher what it sees.

Expected behavior (both Win7 and 1803) give something like this:

Parent console handle is 00330654
child says: stdin handle is 000000FC
stdout handle is 00000108
stderr handle is 00000110
hConsole is 0000000F
Console hWnd handle is 00000000
Cannot get window class

The last two lines are the ones that are of the most interest.  In 1809, we instead get:

Parent console handle is 00420AEE
child says: stdin handle is 0000029C
stdout handle is 000002A8
stderr handle is 000002B0
hConsole is 00000298
Console handle is 004035E8
Cannot get window class

The console handle that is obtained is non-zero, and it is not even a valid HWND.

[testcase.zip](https://github.com/microsoft/terminal/files/3268549/testcase.zip)

**Comment by DHowett-MSFT** [comment]
This was fixed in 1903, but we have not been able to drum up the business justification to service it back to 1809. Sorry!

**Comment by EricYoungdale** [comment]
Sigh.  We use 3rd party software that is not yet certified for 1903, so that's not an option.  I just upgraded to 1809 from Win7, and I am still trying to get the system to be stable for daily use.  Not looking forward to a feature upgrade and even more destabilization.  If I had known, I would have installed 1803 instead.

We may be forced to add a workaround for just this one build in the event that one of our customers is on 1809.

**Comment by zadjii-msft** [comment]
Out of personal curiosity, @EricYoungdale what are you using GetConsoleWindow for?

**Comment by EricYoungdale** [comment]
Basically to detect whether two different processes are sharing a console or not, or whether a given process has no console.  Strictly speaking, we never use the hWnd as a window handle - it is treated more like a unique console ID.

**Comment by eryksun** [comment]
> Basically to detect whether two different processes are sharing a console or not, or whether a given process has no console. Strictly speaking, we never use the hWnd as a window handle - it is treated more like a unique console ID.

That's not a reliable "console ID". Your example uses the creation flag `CREATE_NO_WINDOW`, which causes a process to attach to a new console that has no window, so you already know that `GetConsoleWindow` can return `NULL` when a process actually has a console. To determine whether two processes share a console, I'd attach to the console of the first process via `AttachConsole` and check for the PID of the second process in the list of attached processes from `GetConsoleProcessList`.

Getting a console without a window is a more permanent state than using `STARTUPINFO` to hide the window. The other alternative is to create the process without a console via `DETACHED_PROCESS`, but, unlike a windowless console, that's not inheritable by child processes. `CREATE_NO_WINDOW` is also generally more compatible than `DETACHED_PROCESS` because console programs may misbehave when executed without a console.
