### ISSUE TITLE
Process has no package identity error

### ISSUE THREAD

**Issue by Riqky** [microsoft/terminal#11760]
### Windows Terminal version (or Windows build number)

Microsoft Windows NT 10.0.19043.0

### Steps to reproduce

I am unsure what the cause of this problem is.
My system admin blocked wt.exe using Admin By Request, so it could not start as administrator. Then it completely stopped working,

The rule in ABR has been removed, yet the problem persists.

I tried installing from the github release and from the windows Store.

### Expected Behavior

Windows terminal starting.

### Actual Behavior

This error is shown when Terminal is opened from the Windows Store.

![image](https://user-images.githubusercontent.com/43852754/141748494-62cc5a75-8baa-4681-9e8d-045b878ee310.png)
Translation: The process has no package identity.

When opened from powershell, not happens, but I can see it running in task manager. When opened from the start menu, nothing happens.

`profile.json` does not exist

**Comment by zadjii-msft** [comment]
Honestly, this sounds like a bug that should be filed on [Admin by Request](https://www.adminbyrequest.com/), though I'm not sure they have a public issue tracker. This certainly isn't an issue that I've heard of before. Seems to me like the root cause is removing the rule in ABR left the Terminal install permenantly corrupted. 

Does uninstalling the Terminal and re-installing the Terminal fix the issue? Does installing the Preview version of the Terminal work?

**Comment by Riqky** [comment]
Ah, it is solved! It turns out that the ABR rules wheren't completly removed, causing my install to go corrupt every time I install it. No the rules are completly gone, and I purged my Terminal install.

After reinstalling everything works now. Thank you for your response.
