### ISSUE TITLE
Quake mode Elevated

### ISSUE THREAD

**Issue by pr1malc0de** [microsoft/terminal#11828]
# Description of the new feature/enhancement

Elevated session (admin) quake mode

# Proposed technical implementation details (optional)

Nearly everything i need to do requires elevation, so most of the time quake mode is not usefull for me, would be great if there was a way to prompt for elevation when i activate quake mode, maybe this is already possible, just dont see how

**Comment by zadjii-msft** [comment]
Well, technically, you could just manually spawn the quake window by running `wt -w _quake` elevated. Or if you're already running the Terminal elevated (and only an elevated window), then pressing the quake mode keybinding will create the quake window elevated. 

Otherwise, there's #632 for configuring a profile (or every profile) to launch elevated. Does that sound like it'd work?

**Comment by FalconNL93** [comment]
You can also use "gsudo" to run elevated processes as an alternative for now. It wil run an elevated proces in the same terminal window instead of spawning a new one.

**Comment by pr1malc0de** [comment]
@zadjii-msft that sounds perfect! Thank you! Also @FalconNL93 thanks!
