### ISSUE TITLE
Rendering problems after accepting omnicompletion in vim nested in tmux

### ISSUE THREAD

**Issue by SuperSandro2000** [microsoft/terminal#11863]
### Windows Terminal version

1.12.2931.0

### Windows build number

10.0.19044.1387

### Other Software

vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 08 2021 14:19:29)
Included patches: 1-2434, 3402-3403, 3409, 3428, 3487, 3564, 3581-3582

tmux -V
tmux 3.1c

### Steps to reproduce

I have YouCompleteMe installed in vim. When I am trying to complete a local directory in a shell file through omnicomplete I get broken rendering until vim redraws or tmux refreshes the pane.

I have vim open in a tmux which I attached to both Windows Terminal Preview and the normal Windows Terminal.

Enforcing a full redraw through the experimental setting does not change this. This is also not happening in other terminals or when I have vim open without tmux.

### Expected Behavior

After accepting a suggestion it should look like it does in Windows Terminal

![image](https://user-images.githubusercontent.com/7258858/144336444-d3ccad4f-ec22-4439-a232-09527dbe69b9.png)

### Actual Behavior

but I get the following in Windows Terminal Preview:

![image](https://user-images.githubusercontent.com/7258858/144336456-28eed5a9-f9fc-463f-993d-49d901fff2d0.png)

**Comment by zadjii-msft** [comment]
Huh, it regressed in Terminal Preview? That should be easy enough to find the root cause... Usually @j4james is the VT guy, so i'd reckon it's one of his PR's, but looking at them, none of them seem related here
* https://github.com/microsoft/terminal/pull/11345
* https://github.com/microsoft/terminal/pull/10492
* https://github.com/microsoft/terminal/pull/11152

So this has gotta be something else. 

Can you try repro'ing this with the [debug tap](https://github.com/microsoft/terminal/wiki/Enabling-the-debug-tap) to get a trace of all the input and output? Once the bug starts occurring, send us a screenshot and we might be able to figure out what the Terminal thinks it's getting here. We should be able to see whatever output VIM is producing to get into this state. (It might only work in the Preview version)

**Comment by SuperSandro2000** [comment]
> Huh, it regressed in Terminal Preview?

It was until I tried to reproduce it today. I had the bug for multiple weeks on different machines and now that it would have been closer observed I can no longer reproduce it. I try to remember the debug tap and record the log when I find a way to reproduce the bug.

**Comment by cpof-tea** [comment]
I have same issue with tmux and vim but in Alacritty, so it's not terminal's issue

**Comment by zadjii-msft** [comment]
Hmm. Seems like OP's issue is gone, and I'd reckon that any issues anyone else sees like this are just a riff on #6987. I'm gonna close as a dupe, even if OP's issue wasn't strictly the same root cause, just to keep future readers pointed in the right direction. 

/dup #6987
