### ISSUE TITLE
Terminal should also restore runtime tab titles

### ISSUE THREAD

**Issue by jzymx50** [microsoft/terminal#11878]
# Description of the new feature/enhancement

I am using version 1.12 and the window restoration feature is great. But I find it only memorizes the number of panes or tabs you opened last time. It would be better if it can also restore:
- The name of the tabs. (I often open a tab for the server running and another for git commands. So I rename the tab to make it clear.)
- The working directory of each tab or pane.

Thanks! 😸

# Proposed technical implementation details (optional)

**Comment by Rosefield** [comment]
For the name of tabs, that can be added to #9800. It saves the tab title attached to a pane, but missed the one that can be set otherwise at runtime. 

For the working directory, if you have configured your shell to use the OSC 9;9 code to tell the terminal what your directory is, it will save that currently. https://github.com/MicrosoftDocs/terminal/pull/449 has documentation for how to add that.
