### ISSUE TITLE
Scrolling doesn't work sometimes

### ISSUE THREAD

**Issue by TheBicPen** [microsoft/terminal#11928]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19044

### Other Software

I've only seen the bug when running this program: https://github.com/JustArchiNET/ArchiSteamFarm.
I tried running `cat *` in a folder with many files to see if the same issue occurs, but it does not. 
Nor does it occur with `for ($i=0; $i -le 10; $i++) {echo 'a'; sleep 1}`.

### Steps to reproduce

Download the program and prerequisites from: https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.2.0.10 (win x64)
Run it in a powershell tab in terminal.
While the program is running, scrolling with the scrollwheel does not work. 
Ctrl+Shift+up/down and dragging the scrollbar both work as expected.

### Expected Behavior

Scrolling with the scrollwheel works while the program is running. 
I don't know if the program is somehow capturing the scroll events, but I wouldn't expect a program to be able to do that.

### Actual Behavior

While the program is running, scrolling with the scrollwheel does not work. 
Ctrl+Shift+up/down and dragging the scrollbar both work as expected.

**Comment by zadjii-msft** [comment]
OH HO HO

look who's disabling quick edit!

https://github.com/JustArchiNET/ArchiSteamFarm/blob/07348a5958550c6c3fa9ddef18f8db51c3818c54/ArchiSteamFarm/Core/OS.cs#L260-L278

**Comment by zadjii-msft** [comment]
So this is kinda like what's happening with `vim.exe` in: https://github.com/microsoft/terminal/pull/9970#issuecomment-850536589

ArchiStreamFarm is disabling quick edit when it starts up: https://github.com/JustArchiNET/ArchiSteamFarm/blob/07348a5958550c6c3fa9ddef18f8db51c3818c54/ArchiSteamFarm/Core/OS.cs#L107-L110

That's being combined with the fact that the console is already in mouse input mode, so now they're getting mouse input events (including scrolling/mouse-wheel events), rather than letting them be handled by the Terminal. This has the end result of the Terminal not scrolling when you wheel over it, because we're just sending those to the client application. 

This should be filed upstream over at https://github.com/JustArchiNET/ArchiSteamFarm/issues, they should be able to patch this to disable `ENABLE_MOUSE_INPUT` when they're also disabling quick edit.
