### ISSUE TITLE
Combining Diacritic Marks are broken under AtlasEngine

### ISSUE THREAD

**Issue by reli-msft** [microsoft/terminal#11925]
### Windows Terminal version

1.13

### Windows build number

Any

### Steps to reproduce

Type

```powershell
echo "[e`u{0301}`u{0301}]"
```

In PowerShell v6+

### Expected Behavior

Text like this should appear in the window:

![image](https://user-images.githubusercontent.com/50213618/145647680-bf033226-e39b-48a3-aa40-85f5281a24df.png)

The two acute accents should stack above letter `e`.

### Actual Behavior

![image](https://user-images.githubusercontent.com/50213618/145647627-1947af02-2204-479a-8e00-6c30d5f2d94e.png)

The acute accents are not properly placed.

**Comment by reli-msft** [comment]
It looks like AtlasEngine doesn't do GPOS at all -- however GPOS is the key to support combining diacritics.

**Comment by Perlence** [comment]
Is it related to #3546?

**Comment by lhecker** [comment]
@Perlence It's somewhat related but the cause is different. It's not "expecting the quantity of glyphs [to] equal [...] the cells allocated for each line" and it handles unicode correctly. But it's missing a piece of text analysis to recognize combining diacritics in order to not split text in the wrong locations.

The Jewish word "ﭏלה‎" consists of the 3 clusters "ל", "ﭏ" and "ה" which can be cached independently without affecting text layout (the first one is a ligature). The "AtlasEngine" has a system to break unicode text into exactly such "clusters" of related characters. Such clusters are cached together so that they only need to be drawn once and all future drawings can refer to the cached one.

What this issue implies is that the `canBreakShapingAfter` field of `DWRITE_SHAPING_TEXT_PROPERTIES` isn't enough to decide whether a run of glyphs forms a "cluster", because it doesn't handle combining diacritics, meaning we unfortunately will have to call `IDWriteTextAnalyzer::GetGlyphPlacements`. This is quite unfortunate, because we only need to draw text once and most of the time we actually only want to segment text without being interested in almost everything `GetGlyphPlacements` returns.

I'll tackle this issue in the near term though.
