### ISSUE TITLE
Quake Mode - Can we have Tab title to show how many tabs we have on quake mode?

### ISSUE THREAD

**Issue by amithegde** [microsoft/terminal#11935]
# Description of the new feature/enhancement

When in quake mode, if we have multiple tabs open, it's hard to notice there are multiple tabs. On ConEmu, we get this little title to show list of tabs open which makes it convenient.

# Proposed technical implementation details (optional)

If we can have a title at the top which shows tabs open which can be selected and organized if need be (drag and drop), will come handy.

**Comment by Rosefield** [comment]
On the quake window you can make the tabs show if you disable focus mode using the `Toggle focus mode` action in command palette. This will make it show the normal tab interface like other terminal windows.

**Comment by zadjii-msft** [comment]
Thanks for the feedback! This is a known limitation atm. You can always exit focus mode, with <kbd>ctrl+shift+p</kbd>, "Toggle Focus Mode" (or whatever that's localized to). Otherwise, I'm gonna call this /dup #9992, which should enable adding a setting to disable this for the `_quake` window by default.

**Comment by xorinzor** [comment]
@Rosefield @zadjii-msft why is this issue closed when this is clearly a bug though?
Launch mode can only be configured to "Default", "Maximized", "Full screen", "Focus" or "Maximized Focus".

In quake mode I won't be using Maximized or Full screen and I'm trying to disable Focus mode because I want the tabs to always be visible. Having it set to "Default" I'd expect Focus mode to be disabled.

Yet every time Quake mode is launched it is showing no tabs and I first need to do the `ctrl+shift+p` trick to Toggle focus mode.

This really sounds like the app not respecting the configured settings when lauched in quake mode and thus a bug.

What's worse is how this is an issue that's been known since Dec 2021, and it still hasn't been addressed..

**Comment by zadjii-msft** [comment]
> Why is this closed?

Because ultimately, we're going to solve this by doing #9992, so it doesn't make sense for us (from a project management perspective) to have multiple threads all for the same root cause/fix.

Quake mode has always been an "easter egg" version of `globalSummon`, which is more general-purpose. The only real thing from the _quake window you can't accomplish with generic `globalSummon` actions is the "snap to the top" behavior (which is tracked by a point in #8888 but apparently doesn't have it's own thread).

> What's worse is how this is an issue that's been known since Dec 2021, and it still hasn't been addressed

Alas, I haven't had any cycles to work on anything `globalSummon` related in a long while. You'll note there are _many_ issues on the backlog even older than #9992 that are still open. We're doing our best, but engineering work does take time. 

If there's interest, I could probably add a writeup to #9992 for how I'd implement it. It'd be a lot of code shuffling, but not anything _too_ hard, I don't think. Alternatively, the `snapToSide` global setting would be pretty easy, which could then be combined with `globalSummon` so you didn't need to use specifically the _quake window.
