### ISSUE TITLE
After some operation there are some ghost char and cannot be deleted by clear screen

### ISSUE THREAD

**Issue by SigmaStar** [microsoft/terminal#11941]
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.348

### Other Software

vim 8.2 with airline
posh for windows amd64 5.2.1
powershell 7.2.0

### Steps to reproduce

1. Run vim from Powershell 
2. executing :read !dir
3. maximize Windows Terminal
4. quit vim with :q!

### Expected Behavior

the window of the Windows Terminal should be clear and if I run vim again it should be ok.

### Actual Behavior

The lower part of Windows Terminal is still the content of closed vim and vim cannot be run again because the content is shuffled.
![image](https://user-images.githubusercontent.com/22829962/146142933-961d69f0-9928-4fa4-8078-e11e195d5e42.png)

**Comment by SigmaStar** [comment]
Again, a new vim instance looks like this:
![image](https://user-images.githubusercontent.com/22829962/146143116-478fcebc-f390-4856-93b0-77e6a063cff7.png)

**Comment by zadjii-msft** [comment]
This looks a bit like #202, even though that one's years older than the Terminal (or even conpty). I suspect there's a better dupe somewhere else on the repo. 

I'd bet that this is due to windows vim.exe using another screen buffer to host the vim buffer, and when you exit vim, it restores the original screen buffer, which is still at a different size. When running as conpty, we probably shouldn't have different screen buffer sizes like that. We should probably keep them in sync manually. (or at very worst, sync the size of the second buffer to the first buffer when closing the second buffer)

**Comment by SigmaStar** [comment]
But I found that this problem has gone and I don’t know how

从 Windows 版邮件发送

发件人: not-AMM
发送时间: 2022年1月6日 16:30
收件人: microsoft/terminal
抄送: SigmaStar; Author
主题: Re: [microsoft/terminal] After some operation there are some ghost char and cannot be deleted by clear screen (Issue #11941)

Same here.
Windows Terminal version
1.12.3472.0 (Preview)
Windows build number
19043.1415
Other Software
• Vim 8.2.3908
• Powershell 7.2.1
I censored the content since I wrote some personal information.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zadjii-msft** [comment]
Hey look, I found the dupe!

/dup #4389
