### ISSUE TITLE
Untie "active control" from "currently XAML-focused control"

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1205]
> I think there are some issues in tying "active control" to "control currently focused in the XAML stack".. what do you think? Should we just holistically fix this all up by making active/focused not the same?

A tab should have a notion of its "active control", even if that control isn't currently focused. Right now, we have some problematic mixing of user intent and UI state that cause us to have tabs with no active control and tabs whose titles flicker when they become "focused" even though what's "active" hasn't changed.

Changes in which control is active can be propagated out through a single "ActiveTerminalChanged" event.

**Comment by zadjii-msft** [comment]
The bug reported in 1862 is super annoying, so this should definitely go in for 1.0.

**Comment by zadjii-msft** [comment]
Another excellent manifestation of this problem: open another application, and the terminal with multiple tabs. Switch focus between the Terminal and the other app, by clicking specifically on the tabs. Eventually, the tab will lose it's title, because no control is focused:
![image](https://user-images.githubusercontent.com/18356694/65050933-0ef92a00-d91d-11e9-8c9a-ad45520b44c0.png)
