### ISSUE TITLE
error 0x800700e2 when launching `powershell.exe' 

### ISSUE THREAD

**Issue by NareshChinnusamy** [microsoft/terminal#12067]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000

### Other Software

Software: Powershell
Version: 5.1

### Steps to reproduce

- I opened the windows terminal application from start.
- Default profiles have been set for the PowerShell application in the windows terminal.
- Powershell tab is opening with an error showing [error 0x800700e2 when launching `powershell.exe']
- But the PowerShell is working fine during standalone launch.
- And I have been able to access PowerShell via visual studio's terminal.

### Expected Behavior

I'm expecting a new tab of PowerShell opening in the windows terminal without any issues.

### Actual Behavior

The new tab of PowerShell always shows [error 0x800700e2 when launching `powershell.exe'].
I tried different fix approaches like adding PATH of PowerShell to environment variables but nothing is working.

**Comment by eryksun** [comment]
0x8007 in the high word means it's an `HRESULT` code for a Windows error code. 0x00E2 (226) in the low word is the Windows error code `ERROR_VIRUS_DELETED`. I doubt the same executable would be repeatedly reported as being infected by a virus instead of the file being moved to a quarantine location. Maybe Terminal is misreporting the exit status.

**Comment by NareshChinnusamy** [comment]
@eryksun Is there any other way to resolve this issue?

**Comment by elsaco** [comment]
@NareshChinnusamy you might try setting `CMD` as the default profile, launch windows terminal then start `powershell.exe` from `CMD` prompt or another tab ant try to narrow down which is the `potentially unwanted application`

Since your terminal crashes upon launch you might have to directly edit `settings.json` file.

**Comment by zadjii-msft** [comment]
What's your `PATH` set to in a cmd.exe tab? 

Are you using any sore of antivirus software?
