### ISSUE TITLE
Update the display name of the app to be shorter, punchier, more fun

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#12091]
MSFT-32778085 suggests that we may want to make ourselves more easily discoverable in the start menu, by coming up with under "T" for "Terminal" instead of "W" for "Windows ...."

**Comment by zadjii-msft** [comment]
(that certainly can't be the right internal issue...)

**Comment by malxau** [comment]
I think it should be 32778085

**Comment by zadjii-msft** [comment]
That's the one, thanks!

**Comment by zadjii-msft** [comment]
Pasting notes here so I don't forget

![image](https://user-images.githubusercontent.com/18356694/149389361-217508b9-a045-4908-8f73-9bd3e4679428.png)

* Try to use the context menu loc files, cause those get localized to more languages
* Unlock the "Windows Terminal" wherever its a locked resource, because localization
* manually install and switch the OS to the `qps-ploc` locale, for testing. Just type it in, and the OS will go "yep sure that's a thing"
* You can fake localize a dev build by making a directory next to the `en-us` one (see screenshot)
* Probably don't need to worry about the tile, (RIP the tile)
* Check the localization in the elevation dialog too
