### ISSUE TITLE
Setting to close tab when Ctrl-D with non-0 $?

### ISSUE THREAD

**Issue by sdegutis** [microsoft/terminal#12122]
# Description of the new feature/enhancement

I open and close tabs often. I like to close it with Ctrl-D because it's easier than Ctrl-Shift-W and ensures I'm closing something with a blank shell prompt and no running process by accident.

But right now, if the last command exited with non-zero status, the tab won't close, but just shows an exit status message. It only closes all the way if $? was 0 (using bash language).

# Proposed technical implementation details (optional)

Maybe a setting to allow it to close even if status != 0?

**Comment by Rosefield** [comment]
Each profile (or the default), under the `Advanced` tab has a "Profile termination behavior" that you can set so that it closes on all exit codes instead of just 0. This probably captures what you want?

![image](https://user-images.githubusercontent.com/6185249/148662722-7289b55d-32c0-4c21-92e6-ef7aa89bf7c2.png)

**Comment by DHowett** [comment]
Indeed! Thanks @Rosefield

**Comment by sdegutis** [comment]
I saw that but didn't realize it meant when the shell (e.g. bash) closes, so that setting confused me. Oops. Thanks 👍
