### ISSUE TITLE
Figure out how to support bindings for "VK_OEM" keys

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1212]
https://github.com/microsoft/terminal/blob/ecfaa76a895da18a2997c4e7dbd4b3fccdf2d889/src/cascadia/TerminalApp/KeyChordSerialization.cpp#L75-L85

**Comment by DHowett-MSFT** [comment]
Yanking the triage tag. This is a `TODO` from code.

**Comment by shanselman** [comment]
I’m looking to have CTRL+| (which is ctrl shift \ on my keyboard) split vertical. Not possible today. 

For horizontal I’m using CTRL+SHIFT+- which is CTRL+_ 

FYI+context

**Comment by timheuer** [comment]
One way maybe to be able to handle this would be to allow VK_** int values to be used in the binding 'language' to avoid a bunch of hard coding of VK and missing ones.  enables you to you say "ctrl+(vk)32" ? -- just a wild idea.

I think in @shanselman use case, supporting a keybinding that already involves a modifier might be tough (I don't see cmder/conemu handle this either).  But even supporting CTRL+\ (the non-shifted pipe character that maps to VK_SEPARATOR) doesn't work right now.

**Comment by zadjii-msft** [comment]
I'd really love it if there was a way that we could just take a character and get the vkey from it. That way, if a user put `ctrl+|` in their json, we'd try to find the key from the char in our map, fail, then ask the OS what vkey that should be. We'd look up what the actual vkey is, find `VK_OEM_5, Shift`, and use that key+modifiers at runtime. There's a pretty good chance there's a relative of `MapVirtualKey` that might work for that purpose. However, we'd need to make sure that when we re-serialize the key, that we don't lose the original. (granted, that would be fixed by #754, so maybe we should do that one first or just live with it for now...)

**Comment by binarycrusader** [comment]
> I'd really love it if there was a way that we could just take a character and get the vkey from it.

I think this is what you're looking for in this case:

https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-oemkeyscan

And then for keys on the "Main" keyboard, there's also:

https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-vkkeyscanexa

Finally, see also:

https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-mapvirtualkeyexw
