### ISSUE TITLE
Terminal doesn't respect "start /max" and "/min" parameters when running a console app as default terminal

### ISSUE THREAD

**Issue by bzzrak** [microsoft/terminal#12154]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.434

### Other Software

Seemingly any console application (cmd, powershell, python, batch file) -- I'm using python as an example here.

### Steps to reproduce

1. set terminal as default terminal
2. open command prompt in terminal
3. run for example "start /max python.exe" (or powershell, or cmd, or some batch file)
4. the window will show windowed, not maximised

### Expected Behavior

New window starts maximised, as it does when the default Windows console is set.
The correct behaviour also happens if you run wt.exe itself, i.e. "start /max wt python"
<img width="960" alt="image" src="https://user-images.githubusercontent.com/77467869/149321239-c48273ac-9792-478b-b183-a1c8f189fd24.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/77467869/149321623-33e95f07-c73f-4dad-9e9d-da0634cdf8fa.png">

### Actual Behavior

New window starts windowed
<img width="960" alt="image" src="https://user-images.githubusercontent.com/77467869/149321035-19809f07-334e-48fe-9320-29de937f9e1c.png">

**Comment by bzzrak** [comment]
BTW, the /min parameter is even worse. "start /min python.exe" starts the classic console, while "start /min wt python.exe" does make a minimised WT window, but you can't switch to it for some reason.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/77467869/149322631-e15ab497-a415-4f2c-bd55-65e337d6672f.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/77467869/149322963-65b55f15-29e4-4b07-a5fc-a4e7855d6519.png">

**Comment by zadjii-msft** [comment]
Alright, so there are three elements here. From the bottom up:

* `start /min wt python.exe` we're tracking in #9053, so feel free to continue that element there.

**Comment by eryksun** [comment]
Without knowing the details of what's possible, I'd expect Terminal to honor relevant fields in [`STARTUPINFO`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow) after a handoff from conhost. When a new tab (not a window) is created, I'd expect it to use `lpTitle` and -- if they're still relevant in any way -- `dwXCountChars`, `dwYCountChars`, and `dwFillAttribute`. When a new window is created, I'd expect it to honor the window's initial show state, position, and size: `wShowWindow`, `dx`, `dy`, `dwXSize`, and `dwYSize`. If honoring a setting isn't possible or isn't relevant when using Terminal as the default, please document it for `STARTUPINFO`, or document it in the console docs.

I understand skipping the handoff to Terminal if `wShowWindow` is `SW_HIDE` (0). A hidden Terminal window would be dysfunctional since a console app can't programmatically restore the window, and neither can the user. I don't understand skipping the handoff for `SW_SHOWMINIMIZED` (2), `SW_MINIMIZE` (6), `SW_SHOWMINNOACTIVE` (7), and `SW_FORCEMINIMIZE` (11). In principle, the user can easily restore a minimized terminal. Maybe this was implemented because Terminal doesn't support `wShowWindow` properly. For example, as mentioned above, `start /min wt` is [broken](https://github.com/microsoft/terminal/issues/9053). It's better to use the classic console until that gets fixed.

**Comment by miniksa** [comment]
> Without knowing the details of what's possible, I'd expect Terminal to honor relevant fields in [`STARTUPINFO`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow) after a handoff from conhost. When a new tab (not a window) is created, I'd expect it to use `lpTitle` and -- if they're still relevant in any way -- `dwXCountChars`, `dwYCountChars`, and `dwFillAttribute`. When a new window is created, I'd expect it to honor the window's initial show state, position, and size: `wShowWindow`, `dx`, `dy`, `dwXSize`, and `dwYSize`. If honoring a setting isn't possible or isn't relevant when using Terminal as the default, please document it for `STARTUPINFO`, or document it in the console docs.

I get doing `lpTitle`. That should be easy even if inserting a tab into an existing window. I guess same for `dwFillAttribute`.

But for the other ones related to sizing and visibility... I think what I'd do is... if the inbound connection specified any of those, I'd ensure the monarch/peasant granted them a fresh window to manipulate however they specified without tampering with the user's existing window. So they can only "join" automatically if they're not going to mess with what is existing and are flexible with the layout.
 
> I understand skipping the handoff to Terminal if `wShowWindow` is `SW_HIDE` (0). A hidden Terminal window would be dysfunctional since a console app can't programmatically restore the window, and neither can the user. I don't understand skipping the handoff for `SW_SHOWMINIMIZED` (2), `SW_MINIMIZE` (6), `SW_SHOWMINNOACTIVE` (7), and `SW_FORCEMINIMIZE` (11). In principle, the user can easily restore a minimized terminal. Maybe this was implemented because Terminal doesn't support `wShowWindow` properly. For example, as mentioned above, `start /min wt` is [broken](https://github.com/microsoft/terminal/issues/9053). It's better to use the classic console until that gets fixed.

This was just a matter of scoping it. You're right, Terminal doesn't support `wShowWindow` completely/properly yet and we hadn't thought through all those scenarios, so the minimum scope to get the "hard part" of the actual handoff out of the way was my goal. Additionally, when I was doing my testing, two things stood out to me: 1. Applications that don't set any of the flags or any settings and ask for a completely blank console session are most commonly destined for an interactive session. 2. Applications that mess with all the flags during the `::CreateProcess` call are usually extraordinarily sensitive to changes and performance characteristics, so I didn't want to impact them right away.

**Comment by zadjii-msft** [comment]
conhost reads the Cac, decides if it wants to handoff. It does not drain the Cac from the driver
openconsole gets handed off to, it reads the driver. The message in flight has the original Cac


so OpenConsole can read the startup info, without rev'ing the defterm interface

**Comment by zadjii-msft** [comment]
> **Note**: For discussion: 

I'm leaning towards closing this out with the combo of #14222 and #13838. We can pass the startup info into the Terminal now, but I'm reluctant to change the behavior where defterm filters out `start /min cli-app.exe` invocations. `start /min wt cli-app.exe` will work, and `start /max cli-app.exe` will both launch into the terminal, and `start /min cli-app.exe` will open a minimized conhost running `cli-app.exe`.
