### ISSUE TITLE
Create a separate taskbar entry of Windows Terminal of a specific profile

### ISSUE THREAD

**Issue by 3N4N** [microsoft/terminal#12218]
I have been using WT for cmd and pwsh and the other console, whatever it's called, for the Ubuntu bash.

![image](https://user-images.githubusercontent.com/32037751/150649052-c303d214-4e8f-4ad1-afcf-33b13d11bba5.png)

I know WT can open bash as well, but I use tmux with bash, so I don't need the extra functionalities of WT. What I need is a way to switch between the Ubuntu bash and Windows cmd with a single stroke. Having separate taskbar entries let me do just that (<kbd>Win</kbd>+<kbd>1</kbd> and <kbd>Win</kbd>+<kbd>2</kbd>).

Now my question is: can I have a separate taskbar entry for a single specific profile of WT? MSYS2 has separate exe files for launching separate terminals for each of their shells, and the exe files are essentially cmd-scripts inside. But making exe out of those shell scripts let the terminals pinnable in taskbar. I want that for Ubuntu bash of WT.

&nbsp;

Sorry for asking what may be a question irrelevant to this project.

**Comment by zadjii-msft** [comment]
Having separate taskbar entries is a bit tricky... 

We've been discussing something similar over in #12135. Basically you'd have different taskbar shortcuts that each summon the terminal window that has whatever profile you're looking for. The taskbar entries wouldn't get highlighted separately (only the actual Terminal window would get focused), but it would otherwise effectively work the same. 

You think that would work for you?

**Comment by treed-at-nucleus** [comment]
I'm running into a similar issue now that I'm on Windows 11.

I'd like my profiles (WSL, CMD, etc.) to have different slots on the taskbar, as it's easier for me to organize that way. Having everything clumped into one icon on the task bar makes it harder to find what I need. Instead of 1 easy click, it's 2 clicks with some pausing to see what I'm actually after.
