### ISSUE TITLE
Add the whole Cascadia font family

### ISSUE THREAD

**Issue by ericbrownz** [microsoft/terminal#12217]
# Description of the new feature/enhancement

For `oh-my-posh` needs some special characters, considering add the whole `Cascadia` font family including `Cascadia Code PL` and `Cascadia Mono PL` so there is no need to download it separately.

# Proposed technical implementation details (optional)

[microsoft/cascadia-code](https://github.com/microsoft/cascadia-code)

**Comment by zadjii-msft** [comment]
@cinnamon-msft can answer why we're not shipping PL with the Terminal by default 😉

**Comment by DHowett** [comment]
We have felt _so much pain_ shipping even PART of the Cascadia font family in Terminal: all manner of platform issues, font selection issues, versioning bugs, etc. We're also part of Windows now, and any font that we add becomes a _de facto_ Windows system font.

Because of all that, we're not planning on shipping _any_ fonts inbox that are not already shipped today. Sorry!
 :smile:
