### ISSUE TITLE
Ctrl+F doesn't bring up find dialog in cmd+PS

### ISSUE THREAD

**Issue by asklar** [microsoft/terminal#1226]
# Environment

```none
Windows build number: 10.0.18362.86
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
cmd then launch powershell, ctrl+F prints ^F on the command line instead of bringing up the find dialog

# Expected behavior
find dialog is brought up

# Actual behavior
^F is displayed

![image](https://user-images.githubusercontent.com/22989529/59378767-efdd7180-8d09-11e9-857d-015d420807f7.png)

**Comment by zadjii-msft** [comment]
I'm pretty sure this is because of PSReadline using raw input mode. If you `Remove-Module PSReadline`, the find dialog will work again, but break a bunch of other powershell functionality psreadline provides. 

For the record, Ctrl+F doesn't work in wsl for the same reason.

While it may not be the best behavior, it is *by design*, and hopefully something we can fix in the new terminal (by providing custom keybindings)

**Comment by DHowett-MSFT** [comment]
@lzybkr may be interested in the PSReadline angle -- perhaps there's a binding that'll work for this?

**Comment by lzybkr** [comment]
See this [comment](https://github.com/PowerShell/PSReadLine/issues/280#issuecomment-441338880).
