### ISSUE TITLE
Arrow keys don't work in Git-Bash 2.35 and 2.35.1 for `less` and `git log` locally and `vim` over ssh

### ISSUE THREAD

**Issue by IceTDrinker** [microsoft/terminal#12298]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.0

### Other Software

Git Bash 2.35.1, 2.35.0 also had the issue, 2.34.0 did not as far as I could tell

### Steps to reproduce

open a git repo with enough commits to fill the screen.

git log, try to move around with the arrow keys -> does not work

Or use less on a file big enough to fill the screen use up/down arrows -> does not scroll

ssh-ing into an ubuntu 20.04 open a file with vim -> arrow keys don't work

### Expected Behavior

Working arrow keys

### Actual Behavior

Arrow keys not working in some situation and some other inputs behaving in a weird way

**Comment by zadjii-msft** [comment]
Does the issue repro in `conhost.exe` directly? Or only in Windows Terminal?

**Comment by ueffel** [comment]
Using the arrow keys is also broken in `conhost.exe` (simply running "<git>/bin/bash.exe -l -i")
so it might be an issue with git-for-windows?

I also noticed, that pressing <kbd>Ctrl</kbd>+<kbd>c</kbd> in a ssh session kills ssh locally instead of sending the key combo to the remote session, but that may be unrelated.

For the record using `<git>/git-bash.exe`, which runs bash in a mintty 3.5.2 terminal, all of the above work as expected.

**Comment by zadjii-msft** [comment]
No worries, glad we were able figure it out!

**Comment by IceTDrinker** [comment]
Found the proper issue and workaround if others bug you with the same issue: https://github.com/git-for-windows/git/issues/3657#issuecomment-1028037890
