### ISSUE TITLE
WT 1.12.10334.0 not available in msstore, winget source only

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#12362]
### Windows Terminal version

1.12.10334.0

### Windows build number

10.0.19044.0

### Steps to reproduce

- install latest WT release available in `msstore`

### Expected Behavior

- terminal 1.12.10334 to be installed

### Actual Behavior

- terminal 1.11.3471.0 is being installed when source is `msstore`

- msstore query:
```
PS C:\> winget search 'Terminal' --source 'msstore'
Name                                         Id           Version
-----------------------------------------------------------------
Windows Terminal                             9N0DX20HK701 Unknown

```

- winget query:
```
PS C:\> winget search 'Terminal' --source 'winget'
Name                          Id                                Version      Match
----------------------------------------------------------------------------------------------
Windows Terminal              Microsoft.WindowsTerminal         1.12.10334.0 Moniker: terminal
```

**Comment by zadjii-msft** [comment]
This happens literally every release. The Store doesn't roll the newest release out simultaneously to everyone. Presumably, `winget` is subject to the same delays in this regard. I believe manually installing the release off the Releases page will upgrade in-place.

**Comment by DHowett** [comment]
For the stable version, since we have upwards of four million installs, we roll updates out slowly _on purpose_. There's a 1-2 week delay while we go through the flighting rings. Insiders get it first, then Beta insiders, then ... (etc.)

If we didn't do that, probably at least two million people would have simultaneously filed feedback that Terminal switched to English and any/all of their language selections were totally lost. _Bad._
