### ISSUE TITLE
Empty path to OSC 9;9; crashes Terminal window

### ISSUE THREAD

**Issue by kstauffer** [microsoft/terminal#12378]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19042.1466

### Steps to reproduce

In WSL bash, `echo $'\e]9;9;\e\\'`

### Expected Behavior

Terminal should keep running. I don't know if the devs think an empty path should be treated as a no-op or like a well-formed path to a non-existent directory. For example, `\e]9;9;/foo\e\\\` sets the directory to /.

### Actual Behavior

Terminal window hangs immediately (tested by running  `date` in a tight loop in the background) and crashes a second later.

**Comment by j4james** [comment]
This was something I was planning to look at as a followup PR #12247. In the same way that `AdaptDispatch` and `ConGetSet` are designed to throw exceptions for error handling, the equivalent Terminal classes `TerminalDispatch` and `ITerminalApi` should be doing the same thing. That way exceptions like this would be caught in the `StateMachine` and recovered gracefully.

I had initially planned to leave this till I was further along refactoring the conhost side of things, but maybe it's a good idea to get it done sooner rather than later if it'll save users from having a crashed terminal. Any objections to that?

**Comment by j4james** [comment]
I should add that this isn't necessarily a fix for the `OSC 9;9` handling - I'm not sure what the correct behaviour is for that. I just want to make sure the terminal isn't needlessly crashing in situations like this.

**Comment by zadjii-msft** [comment]
I agree. At the very least, we should fix this crash now, so we can service the fix to the in-market builds.

**Comment by zadjii-msft** [comment]
Hey @j4james should this be closed by #12432? Since the crashing doesn't happen anymore? I think right now we just ignore an empty path, which sure seems reasonable to me

**Comment by zadjii-msft** [comment]
Fine by me ☺️ I _am_ gonna move it out of the 1.14 milestone though, just for the sake of work tracking. The bug that needed immediate fixing is gone. We can double check the real behavior later. Thanks again!
