### ISSUE TITLE
Ubuntu - less command centers the text

### ISSUE THREAD

**Issue by Turum** [microsoft/terminal#12380]
### Windows Terminal version

 1.12.3472.0

### Windows build number

10.0.19044.1466

### Other Software

Ubuntu-20.04

### Steps to reproduce

1. Create text file with several lines.
2. Open this file with "less" command.

### Expected Behavior

![image](https://user-images.githubusercontent.com/19665888/152613282-2adde7ab-2306-47d1-923c-53975431badb.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/19665888/152613559-6873100c-9904-414b-a1f4-7bdb0773fc74.png)

**Comment by j4james** [comment]
I believe this is working as expected. I'm assuming your command prompt was half way down the page when you started `less`, and it just starts writing out the content at the line you were on. I see the exact same behaviour in XTerm, Gnome Terminal, and Mintty.

The fact that the old conhost shell is displaying the output at the top of the page was a bug that has since been fixed (PR #10843). It was originally resetting the cursor position to the top left whenever an application switched to the alternate buffer (which `less` is doing), but that was a mistake.
