### ISSUE TITLE
Copy-Paste in some editors

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#12411]
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.22000.0

### Other Software

micro:
```
Version: 2.0.10
Commit hash: b9763856
Compiled on August 07, 2021
```
far:
```
Far Manager, version 3.0.5961.0 x64
Copyright © 1996-2000 Eugene Roshal, Copyright © 2000-2022 Far Group
```

### Steps to reproduce

Paste copied text that contains leading spaces in an editor.

### Expected Behavior

Text should be pasted as is, without corrupted formatting

### Actual Behavior

Leading spaces grows with each line. The behavior is the same in both editors (  `far -e`   `micro`  )
This is not observed in any other terminal where launched editor.

![micro](https://user-images.githubusercontent.com/78153320/152793238-a343f205-5ed1-49cc-9164-ca9e9b8a2fa1.png)

**Comment by lhecker** [comment]
I can't replicate the issue with Far Manager 3.0.5961.0 x64.

micro indeed produces the behavior from the screenshot above. Curiously however this only happens when run natively under Windows. If you run micro with WSL2 inside Windows Terminal everything works as expected, even though we're still the exact same terminal. Could this perhaps be a bug in micro? 🤔

**Comment by 237dmitry** [comment]
> I can't replicate the issue with Far Manager 3.0.5961.0 x64

I turned off autoindent in `far:config`. And autoindent set to false in micro's settings.json  And this solve the problem in both editors. I do not know why the terminal affects autoindent.

**Comment by zadjii-msft** [comment]
relevant: #7041, #9034. I'd bet it's related to bracketed paste mode.
