### ISSUE TITLE
wt.exe not found after upgrading from windows 10 to 11

### ISSUE THREAD

**Issue by mortenn** [microsoft/terminal#12454]
I just upgraded a laptop from a fully up to date Windows 10, and discovered that right clicking the start menu had replaced the old command prompt with windows terminal, but clicking windows terminal resulted in an error message that wt.exe was not found.

I downloaded the .msixbundle from github and installed it, that fixed the issue, but windows terminal definitely should be included with windows 11 when you upgrade!

**Comment by zadjii-msft** [comment]
> windows terminal definitely should be included with windows 11 when you upgrade!

It definitely should have been! It is supposed to ship with the OS, so it's a little troubling that it wasn't. Which OS version specifically did you install?

I'm not sure we'll be able to get more info from your machine about this, unfortunately 😕 I know I hit something similar once when we first made the Win10 -> Win11 switch internally, but after re-installing the Terminal I never had another issue with it.

**Comment by mortenn** [comment]
My OS build is 22000.493

**Comment by mortenn** [comment]
This is the wrong place for this, but I can also mention that windows security is missing after the upgrade.
![image](https://user-images.githubusercontent.com/640095/153482840-05733cf2-f098-4b5c-9d13-1cf7b2c1a0be.png)

**Comment by zadjii-msft** [comment]
> I can also mention that windows security is missing after the upgrade.

SURPRISINGLY, I had that _exact_ same symptom myself!

This might be MSFT:38047373 internally. That's got a good deal of investigation happening, I'll report back if that finds anything interesting. Unfortunately, this does seem to be an issue that's outside our scope. I'm gonna close this out, since I don't think there's going to be anything else for us to do here. 

/dup https://task.ms/38047373
