### ISSUE TITLE
Windows Terminal hangs when shell exits

### ISSUE THREAD

**Issue by fefrei** [microsoft/terminal#1250]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): d82eab44d076e441f0b630d9b53a19dfa884c3ab
```

# Steps to reproduce

1. Open Windows Terminal
2. Have your shell terminate, e.g. by typing `exit`

# Expected behavior

The tab, or the whole window, closes.

# Actual behavior

Windows Terminal hangs, leading to a _WindowsTerminal.exe is not responding_ eventually.

**Comment by fefrei** [comment]
After some experimenting and bisecting, I can add that it doesn't reproduce all the time, and it's a regression from the most recent commit, d82eab44d076e441f0b630d9b53a19dfa884c3ab.

**Comment by DHowett-MSFT** [comment]
This will be impacted by #970. I'll take this on and make sure it's fixed with that change.

**Comment by robleg88** [comment]
expected behavior tab closes happens whether you type exit or close the tab as long as it is not the last tab open. If it is the last tab regardless of the type of terminal tab open if you close the tab the window closes.
If you type exit on the last tab it crashes …. windows terminal not responding.  It does close if end the task.
Windows terminal does open when you relaunch it. It seems to only open happen when you type exit on the last remaining tab that is open.

**Comment by fefrei** [comment]
I can confirm this is fixed now. Thanks, @DHowett-MSFT!
