### ISSUE TITLE
use font in "show all fonts" has render issues

### ISSUE THREAD

**Issue by yingking** [microsoft/terminal#12522]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19042.1466

### Steps to reproduce

open windows terminal, in settings simply choose "appearance -> Font face",check "Show all fonts",and choose "Ink Free" or some font not in the default font face,like this:
![image](https://user-images.githubusercontent.com/32102128/154673771-5b8a9aa5-19c0-4358-8401-b0205e9f99e3.png)
and it will render a long whitespace,but i did not type anything......
![image](https://user-images.githubusercontent.com/32102128/154673916-e30a84c4-a5ef-4595-adb9-427707628cc2.png)
and in vim where are also lot of whitspace,but acturelly where are nothing...
![image](https://user-images.githubusercontent.com/32102128/154674073-f4b3fa58-fab1-4e4b-9f08-61ebd15b35b9.png)
I try it in another computer with windows terminal config with powershell,and meet the same issue.

### Expected Behavior

right whitespace rendering,seems transparent error too.

### Actual Behavior

![image](https://user-images.githubusercontent.com/32102128/154673916-e30a84c4-a5ef-4595-adb9-427707628cc2.png)
![image](https://user-images.githubusercontent.com/32102128/154674073-f4b3fa58-fab1-4e4b-9f08-61ebd15b35b9.png)

**Comment by zadjii-msft** [comment]
Alas, this it probably gonna fall under the category of "play silly games, win silly prizes". Terminals are fundamentally hosting a _grid_ of characters, so they can only reliably work with monospaced fonts. "Ink Face" isn't a monospace font, so its characters aren't entirely filling their grid spaces. So when you see something like:
![image](https://user-images.githubusercontent.com/18356694/154677773-0047c4ee-45ce-4ff4-ae7a-aee38350044f.png)
what's happening there is roughly:
* the terminal renders the '77    ' with gray on a black background
* the terminal switches to blue on black to render the '/'. It renders that where it believes the character should be in the grid, which is a good distance to the right of the end of the spaces from the previous run. Because nothing was rendered there, the acrylic behind the text is now visible instead. 
* same thing happens again for each of the runs in the row. 

I'd stick with monospace fonts for the best experience.
