### ISSUE TITLE
Can’t rename a template via fragments

### ISSUE THREAD

**Issue by didrocks** [microsoft/terminal#12520]
### Steps to reproduce

Ship a template fragment with something like:
```
"profiles": [
      {
        "updates": "{f184b75f-6c82-5ea5-9b3e-3203d66c5f82}",
        "name": "My new profile name",
      },
    ]
  }
```
Then restart the terminal to take the new fragment in account.

### Expected Behavior

"My new profile name" should appear as the profile name

### Actual Behavior

The old name still appears, "name" in case of "update" is discared.

The rationale here is to replace the generated named in WSL, which is using the registered WSL ID (`Ubuntu2004LTS` for instance) instead of the Display Name registered (and used as the tab name entry) like the more readable `Ubuntu 20.04 LTS`.
Other kind of entries are overridden by the fragment, but not the `name` one.

The workaround right now is to hide the generated template with `hidden: true` and add a whole new entry.

**Comment by zadjii-msft** [comment]
Huh. It should be able to do that. Why doesn't that work? I bet this regressed in one of the many settings refactors over the last few months. 

Thanks for filing this! Let's make sure to get this fixed.

**Comment by lhecker** [comment]
I'll debug this issue starting next week. 🙂

**Comment by lhecker** [comment]
The problem here is that fields in a user's settings.json take precedence over fragments. Since profiles are created and written with a "name" field, the "name" field in fragments usually has no effect. If you were to remove the "name" field from your settings.json this would work as expected.

What is unexpected however is that we don't respect such updates when the dynamic profile is first added. I'm going to submit a PR for that.
