### ISSUE TITLE
Show/Hide Operations on ::GetConsoleWindow() do not work against Terminal through ConPTY

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#12570]
In attempting to make the Windows Terminal be the default terminal (#7414), we've discovered in testing that there are a lot of scenarios that were relying on manipulating the window handle from `::GetConsoleWindow()` in one way or another to show or hide the window state.

While we strongly discourage this as it isn't guaranteed to work in a universal way across platforms and systems... and is one of the APIs we have listed as "deprecated" on `docs.microsoft.com` for that exact reason... we're going to make a compromise solution here to try to make it work in enough scenarios that it will maintain compatibility with existing tooling that is relying on it. (One of the primary tenets of moving to Virtual Terminal sequences and the ConPTY is to make everything work in the "universal language" that all platforms support, so we strongly resist doing things "for Windows only".)

It looks like **XTWINOPS** (see https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) is an existing sequence that will allow us to translate the window operations coming in and send them to the remote Terminal window. 

This may also work for some of the z-ordering issues of #2988 going forward.

The test case here specifically is doing:

```
::ShowWindow(::GetConsoleWindow(), SW_HIDE);
```

Or one of the other `SW_*` actions.

**Comment by PhMajerus** [comment]
GetConsoleWindow is pretty important when doing mixed CUI + GUI Windows apps.
For example, an app that uses CUI as its main interface but requires to use GUI for some features will display these windows (+ dialogs, msgbox, etc...) as children of the conhost window.
Failure to do so makes them appear behind the current conhost window, as the Windows API has been updated around the Windows 98 timeframe to avoid apps stealing the focus and foreground space, and therefore showing them behind the active window. This is very unintuitive for users and breaks the workflow when the window really is created by the running app, but considered as being a separate app because from the system point of view, anything running in conhost is a background app and conhost is the foreground app.
When doing modal dialogs, I don't even think there is another way to properly handle them than attaching them to the conhost window.

Of course, ideally, a CUI app shouldn't use GUI components, but when mixing libraries, 3rd party COM components, or when doing a CUI-first utility but providing a GUI for some complex task from that CUI, it really makes sense.

The API should be supported even if just for compatibility with legacy apps, and should probably return NULL when redirected to a non-local terminal.

**Comment by miniksa** [comment]
Yes, I've realized that and I'm working out situations where we can resolve this for at least on the local machine. It will of course not work if/when remoted and we will discourage mixing these things for that reason.

**Comment by hwti** [comment]
nzbget uses `GetWindowThreadProcessId()` on `GetConsoleWindow()` to try to determine if it's launched from a terminal or not (which doesn't work when Terminal is set as default on Windows 11).
It will then minimize itself to tray, allowing to show/hide the console window.

See https://github.com/nzbget/nzbget/issues/792 and https://github.com/nzbget/nzbget/blob/develop/daemon/windows/WinConsole.cpp#L89.

While having command line options behind this check might be avoided (which could fix run as startup and from start menu), there are probably still two issues :
 - the ability to show/hide the console
 - When launched without arguments, is there a way to determine if it is launched from a terminal (to display the help) or "standalone" (to hide the window and minimize to tray) ?

**Comment by PhMajerus** [comment]
Not sure if this is a temporary fix or considered final, but propagating show/hide from another window handle fixes only a minor part of this issue and won't work for child windows, which is required for proper focus handover and modal windows.

I think it should work the other way around, the terminal should give the window handle of its window to the ConPTY layer, which would then give it to Win32 apps calling GetConsoleWindow. The ability to use that handle to create child windows that are properly handled as such by the window manager is required for compatibility and even for some current Win32 CUI apps scenarios.

**Comment by DHowett** [comment]
> I think it should work the other way around, the terminal should give the window handle of its window to the ConPTY layer,

Hard NAK on that one! 😁 

1. msys uses the window handle to determine what processes are running in the same "session"; doing so would make it believe that all msys applications in all terminal tabs were part of the same session.
2. I _firmly believe_ that a console application--a single console application hosted in a pane--should not be able to effect window-global changes for other console applications that are co-hosted with it. We *already* have a problem with that with the legacy console, where folks are telling the shell to do something(a) to a window they don't technically own and we can't detect.

Anyway, we have a solution for this that appeases the espoused use cases. See the flowchart in https://github.com/microsoft/terminal/issues/2988#issuecomment-1081076551

a: set a progress bar

**Comment by DHowett** [comment]
In short, Terminal will contain "pseudoconsole hosting windows" that reflect the visibility of the Terminal, pane OR tab to the connected console application but still propagate modal blocking, foreground rights and window "ownership" to the right places.

**Comment by PhMajerus** [comment]
Great, that sounds even better! 😊

My only concern is making sure common scenarios such as MessageBox with GetConsoleWindow() as its owner hWnd with the MB_APPLMODAL type still works as it did in the last 25 years.

Does this mean child windows will automatically get hidden when another terminal tab is selected, if you switch the owning hosting window to hidden to reflect the unselected corresponding tab? This would improve the mixed CUI+GUI experience and avoid having separate windows visible when they are owned by a non-displayed console app.

**Comment by zadjii-msft** [comment]
> Does this mean child windows will automatically get hidden when another terminal tab is selected, if you switch the owning hosting window to hidden to reflect the unselected corresponding tab? This would improve the mixed CUI+GUI experience and avoid having separate windows visible when they are owned by a non-displayed console app.

This is kinda a big open question at the moment. Modal dialogs in tabbed UIs are a bit of an unsolved problem at the moment, one we're hoping to work out the design for soonish. 1.14 certainly won't have that support, but probably some time this year we'll have a plan for that. 

I believe the plan of record is to have modal windows (own/parent)ed to a per-tab HWND, and cloak that per-tab HWND when the tab isn't active, so that all modal windows would also get cloaked. So the Terminal UI wouldn't be disabled when a tab has a modal dialog open, but clicking on the terminal when it has a modal open would make sure to place that messagebox on top of the Terminal.

It's still a work in progress ☺️
