### ISSUE TITLE
closing an issue with no useful comment - is not helpful

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#12610]
> I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
> 1. If I delete this entire template and go my own path, the core team may close my issue without further explanation or engagement.

☝️ feel free. the same way this issue got closed.... https://github.com/microsoft/terminal/issues/3600#issuecomment-1055926441

no comment other than "meh, we went in a different direction"... seriously though - what is up with that?

**Comment by dovholuknf** [comment]
oh and https://github.com/microsoft/terminal/issues/3601 too... just a simple "what we are doing now" is all i ask for

**Comment by zadjii-msft** [comment]
Well, those threads didn't really have any updates in them in over a year. We clearly weren't using them anymore. I kinda figured no one would care, since they were _so incredibly stale_ 😄 We're trying out GitHub Discussions for our releases now: https://github.com/microsoft/terminal/discussions/categories/announcements. They seem to be working fairly well, and get automatically generated when we post new releases, so that's nice.
