### ISSUE TITLE
Support of EUC-JP code page setting

### ISSUE THREAD

**Issue by konemsnq** [microsoft/terminal#12679]
### Windows build number

11

### Other Software

WSL2,  power Shell7

### Steps to reproduce

same problem like #3373

when i try to open EUC-JP encoding file, the japanese will show ????????,
and i tried to using WSL or powershell, well got same issue.

maybe can supports encoding setting in windows terminal? 
just like mac terminal.

### Actual Behavior

the test file is EUC-JP encoding, 
i can't read it in WSL or powershell. is any possible to setting it?

![488295FAE4C14DE1B20020F3C9C173B7](https://user-images.githubusercontent.com/6245459/158007084-7c60ca31-b1f2-45b1-9eb4-04f8abba7b8a.png)

**Comment by LuanVSO** [comment]
on powershell you can do
```powershell
gc file.txt -encoding euc-jp
```
on cmd you have to
``` cmd
chcp 20932
type file.txt
```
on wsl you have to
```bash
cat file.txt | iconv -f euc-jp -t utf-8
```

**Comment by konemsnq** [comment]
thank you for reply, it can work in localhost, 
but i tried to connect other server using ssh, it not working

like #3373 said, it's a open-ssh bug
i also update open-ssh to 8.6 latest, it still error.
so i don't know how to solve this problem

it's my first time using windows to connect server
maybe i miss something,
the encoding problem is difficult to me....

commands like it 
on cmd  
```batchfile
chcp 20932
type test
:: ->テスト

ssh ubuntu
cat test
:: -> ??????????
```
or on Powershell 
```batchfile
$PSDefaultParameterValues['*:Encoding'] = 'EUC-JP'
$OutputEncoding = [Console]::OutputEncoding
Get-Content test
:: ->テスト

ssh ubuntu
cat test
:: -> ??????????
```

**Comment by LuanVSO** [comment]
did you tried this one in your ssh session?
```bash
cat file.txt | iconv -f euc-jp -t utf-8
```

**Comment by LuanVSO** [comment]
![image](https://user-images.githubusercontent.com/43626415/158228922-2cc4b055-c9c0-47d8-9d47-5e76bd64ca84.png)

**Comment by LuanVSO** [comment]
also, which ssh are you using? 
is it the one included or are you using another one?

**Comment by konemsnq** [comment]
> also, which ssh are you using?
> is it the one included in windows or are you using another one?

i using  [Win32-OpenSSH V8.6.0.0p1-Beta](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/V8.6.0.0p1-Beta)
`iconv` can show file normally, 
if need to edit file , `iconv` is not good solution.(i can't convert file encode on server)

because Win32-OpenSSH only supports utf-8,  
maybe `lunt` is only solution.
[Win32-OpenSSH #1855](https://github.com/PowerShell/Win32-OpenSSH/issues/1855#ref-issue-1087903141)

sorry I didn't ask very well, 😢
my brain isn't functioning when i post this issue. 🥱 

thank you for help, give me very good ideas

**Comment by sky9linez32** [comment]
> if need to edit file , iconv is not good solution.(i can't convert file encode on server)  

I recommend @konemsnq to change the issue title, for example, to "Support of EUC-JP code page."
I doubt it is only the Win32-OpenSSH bug because Windows Terminal doesn't support the EUC-JP code page (or it is not selectable) yet, as far as I know. 

Although it is out of topic, one of the other solutions is to use [VS Code editor](https://code.visualstudio.com) with [SSH-Remote extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) in your local computer. You can edit the remote EUC-JP file via VS Code on your local computer.

![VSCodeWithSSHRemoteExtention](https://user-images.githubusercontent.com/33828859/158303573-6cb82a93-ba0a-42d7-a96e-4d1bec560d7d.png)

Appendix)
This problem is also reproduced on WSL2, whose locale is "jp_JP.EUC-JP," so it seems not to be only the Win32-OpenSSH bug.
I think that WSL2 itself supports EUC-JP, but Windows Terminal doesn't have the EUC-JP code page and cannot interpret them.

![wtWithWSL_LocaleEUC](https://user-images.githubusercontent.com/33828859/158304324-cf4548eb-66df-4770-b2b3-ceb07ff236bc.png)

This can also be confirmed by doing ssh to myself (localhost) from another WSL2 distribution with Windows Terminal.
The right of the following figure is ssh remote(ja_JP.EUC-JP), the left is ssh client(C.UTF-8). The ssh is NOT Win32-OpenSSH. However, the problem is reproduced (the `date` command doesn't show Japanese properly).
So, again I doubt that this is a Win32-OpenSSH bug.

![sshofWSL2](https://user-images.githubusercontent.com/33828859/158324980-7079c345-4434-4c2c-9d3a-859c1664d09f.png)

I can't find the other Terminal Emulators that support EUC-JP page code, but I found that [PuTTYrv](https://www.ranvis.com/putty) is one of the ssh clients that supports EUC-JP page code. When I use it and do ssh localhost, it shows Japanese correctly. 

![PuTTYconfig](https://user-images.githubusercontent.com/33828859/158326845-b333e478-ba88-47af-94df-fc2d85994f30.png)
![PuTTY](https://user-images.githubusercontent.com/33828859/158327138-acc8732f-d7fa-477e-afa9-eb7b58faa543.png)

In the future, I think that the servers whose locale is ECU-JP will be replaced with UTF-8. On the other hand, surprisingly, EUC-JP servers were not so rare five years ago for me. 
Therefore, I am also grad if Windows Terminal supports such other code pages. I'm not a skillful developer, but I will help this as far as possible.

**Comment by sky9linez32** [comment]
> if need to edit file , iconv is not good solution.(i can't convert file encode on server)  

I recommend @konemsnq to change the issue title, for example, to "Support of EUC-JP code page."
I doubt it is only the Win32-OpenSSH bug because Windows Terminal doesn't support the EUC-JP code page (or it is not selectable) yet, as far as I know. 

Although it is out of topic, one of the other solutions is to use [VS Code editor](https://code.visualstudio.com) with [SSH-Remote extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) in your local computer. You can edit the remote EUC-JP file via VS Code on your local computer.

![VSCodeWithSSHRemoteExtention](https://user-images.githubusercontent.com/33828859/158303573-6cb82a93-ba0a-42d7-a96e-4d1bec560d7d.png)

Appendix)
This problem is also reproduced on WSL2, whose locale is "jp_JP.EUC-JP," so it seems not to be only the Win32-OpenSSH bug.
I think that WSL2 itself supports EUC-JP, but Windows Terminal doesn't have the EUC-JP code page and cannot interpret them.

![wtWithWSL_LocaleEUC](https://user-images.githubusercontent.com/33828859/158304324-cf4548eb-66df-4770-b2b3-ceb07ff236bc.png)

This can also be confirmed by doing ssh to myself (localhost) from another WSL2 distribution with Windows Terminal.
The right of the following figure is ssh remote(ja_JP.EUC-JP), the left is ssh client(C.UTF-8). The ssh is NOT Win32-OpenSSH. However, the problem is reproduced (the `date` command doesn't show Japanese properly).
So, again I doubt that this is the Win32-OpenSSH bug only.

![sshofWSL2](https://user-images.githubusercontent.com/33828859/158324980-7079c345-4434-4c2c-9d3a-859c1664d09f.png)

I can't find the other stand-alone terminal emulators that support the EUC-JP code page, but I found that [PuTTYrv](https://www.ranvis.com/putty) has ssh a client and/or a terminal emulator that supports the EUC-JP code page. I'm not sure which ssh client or terminal emulator (or both) supports EUC-JP, but it shows Japanese correctly anyway.  

![PuTTYconfig](https://user-images.githubusercontent.com/33828859/158326845-b333e478-ba88-47af-94df-fc2d85994f30.png)
![PuTTY](https://user-images.githubusercontent.com/33828859/158327138-acc8732f-d7fa-477e-afa9-eb7b58faa543.png)

In the future, I think that the servers whose locale is ECU-JP will be replaced with UTF-8. On the other hand, surprisingly, EUC-JP servers were not so rare five years ago for me. 
Therefore, I am also glad if Windows Terminal supports such other code pages. I'm not a skillful developer, but I will help this as far as possible.

**Comment by zadjii-msft** [comment]
After re-reading this thread, yea this sounds like an OpenSSH issue. I'm not sure there's a better thread on their repo, so I'll just link this to /dup https://github.com/PowerShell/Win32-OpenSSH/issues/1855
