### ISSUE TITLE
Terminal Tab does not allow to type after resize

### ISSUE THREAD

**Issue by buehler** [microsoft/terminal#12689]
### Windows Terminal version

1.11.3471.1

### Windows build number

10.0.22000.0

### Other Software

- git bash: git version 2.35.1.windows.2 (loaded via terminal json)
- git bash was installed in terminal via git installer
- installed ZSH inside git bash (zsh --version: zsh 5.8 (x86_64-pc-msys))
- oh-my-zsh

### Steps to reproduce

1. Open a terminal with the git bash zsh tab
2. Test out writing something
3. Resize the terminal (or make it full screen and back)
4. Try to type again

![Terminal](https://user-images.githubusercontent.com/1067213/158156553-31759b11-475b-45d2-a265-e7d1c9ec2ed1.gif)

### Expected Behavior

It should be able to use my keyboard after resizing the terminal :)

### Actual Behavior

I cannot type anything.

It *only* works when I start the terminal, then resize the window and then type. If I resize the window after I typed something, I cannot type anything after resizing the window.

**Comment by zadjii-msft** [comment]
curious. Does this repro for other shells(cmd, powershell)? Do you have anything like X Mouse Button or WizMouse installed? Do you have PowerToys installed?

**Comment by buehler** [comment]
Hey @zadjii-msft 

Just tested:
- with powershell: it works as intended
- with git bash only (ZSH deactivated): works as intended

darn. :-(

I know... it is "not your problem" now :-) but do you have any insights into what the problem might be?

**Comment by zadjii-msft** [comment]
Honestly, no 😕 

Maybe they've got a bug in how they handle resizes that gets the shell into a bad state?

It may have to do with your prompt - you've got that path on the right side of the window - perhaps that's confusing the shell. Maybe try disabling the prompt customization, see if that helps? 

I'm gonna close this out since this seems like a bug that needs to be moved upstream to `zsh` (or even `oh-my-zsh`), but feel free to link the thread back to this one, so others who run into this can follow up as well.

**Comment by buehler** [comment]
@zadjii-msft 
Just to keep you in the loop: effectively, it is an error of "oh my zsh". There is a local function `git_prompt_info` that is causing the error as referenced in the issue (https://github.com/ohmyzsh/ohmyzsh/issues/9953)

Thank you for the help!

**Comment by nofacer** [comment]
They says it's not from them  https://github.com/ohmyzsh/ohmyzsh/issues/9953
