### ISSUE TITLE
Terminal editor keeps running even when closed

### ISSUE THREAD

**Issue by ZuixAlias** [microsoft/terminal#12714]
### Windows Terminal version

1.12.10393.0

### Windows build number

10.0.22000.556

### Other Software

Helix 0.6.0 [[Download from Github](https://github.com/helix-editor/helix/releases/tag/v0.6.0)]

### Steps to reproduce

Shown in video
Video showing the issue : [wt_issue.mp4](https://mega.nz/file/Q4liUTCD#Qyk-s5Oba0swJWuJmrLO6hdQvQpfjlvrPd5AoJOBgOU)

### Expected Behavior

[Everything shown in video] 
'hx.exe' (helix) should close when terminal is closed

### Actual Behavior

[Everything shown in video] 
- 'hx.exe' keeps running in background after terminal is closed
- Happens only with helix, 'nvim.exe' (neovim) runs in background just like 'hx.exe' but it closes with terminal (then maybe a helix issue? Idk...)

**Comment by ZuixOff** [comment]
Okay, actually it's working fine with other files. Just checked the logs and turns out that the issue is related to `rust-analyzer` being run when .rs files are opened and helix doing something with it...something is happening and something closes in between or something like that, i am not sure...

So i am guessing the issue is on helix's side...with open an issue there.

**Comment by zadjii-msft** [comment]
Well cool, thanks for following up!

/dup https://github.com/helix-editor/helix/issues/1828
