### ISSUE TITLE
Issues with Nerd Font icons

### ISSUE THREAD

**Issue by Super-Pizza** [microsoft/terminal#12763]
### Windows Terminal version

1.13.10734.0

### Windows build number

1.0.22000.0

### Other Software

Starship (https://starship.rs)
(Using it as a prompt)

### Steps to reproduce

-Copy this: 者 (Shows as a Windows Icon with Nerd Font)
-Paste it in the prompt
(`Cascadia Mono` is used here)

### Expected Behavior

1-wide box showing

### Actual Behavior

2-wide box showing

**Comment by Super-Pizza** [comment]
Just as a note, it *sometimes* shows as 1-wide on Nerd Fonts

**Comment by zadjii-msft** [comment]
Interesting. So, this is a full-width Windows logo, or it's supposed to be.

(this is what it looks like with JetBrains NF: ![image](https://user-images.githubusercontent.com/18356694/160376445-0c848012-cb65-430b-8a1b-9252712d123e.png))

The character there looks like I copied [`U+8005`](https://www.fileformat.info/info/unicode/char/8005/index.htm)

But I'm not sure that's a supported NF codepoint:
![image](https://user-images.githubusercontent.com/18356694/160377244-a412c043-ebd9-4b34-abc9-3c3900444c1f.png)

From those results:

* `f17a` -  - this works as a single-width in the Terminal for me
* `e70f` -  - same, this works as a single-width in the Terminal for me
* `fab2` - 者 - This one repros the "the icon is single wide, but the Terminal thinks it's double wide"
  * Of course, [U+FAB2](https://www.fileformat.info/info/unicode/char/fab2/index.htm) does look double wide, so that makes sense

**Comment by zadjii-msft** [comment]
I can't find anything myself in starship's docs about where they'd set up the prompt to display the Windows icon as a default. Did you do something to configure starship manually with that icon? Do the other versions of that icon work?

**Comment by Super-Pizza** [comment]
@zadjii-msft Yes, it’s a configuration I made, specifically an environment variable.

I will also note that it’s fixed with a Zero-Width character before, though it adds a space(?)

I tested it elsewhere and it always was 1-wide with Nerd Font.

I will just change the icon.

**Comment by DHowett** [comment]
Right, so the issue here is that Nerd Fonts is using ranges of characters that it should not be using. U+FAB2 is officially declared as being "full-width", and so any compliant terminal emulator will render it as two columns.

That codepoint is a "CJK Compatibility Ideograph". Nerd Fonts is incorrect to assign a Windows logo to that codepoint.

We have some rendering issues when zero-width and multi-width characters are placed next to eachother, but we're tracking those issues over in #8000 and (a different issue as well, I can't find it right now).
