### ISSUE TITLE
Click "Open in Windows Terminal" returns an error.

### ISSUE THREAD

**Issue by freejool** [microsoft/terminal#12765]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.556

### Other Software

explorer.exe

### Steps to reproduce

1. open a folder in any path
2. right click -> Open in Windows Terminal
3. error occurs 

### Expected Behavior

a WT window opens in this path

### Actual Behavior

![](https://raw.githubusercontent.com/freejool/My-Image-Bed/master/img/%7B2D72FAB8-14F9-4312-AFA2-10941533F36D%7D.png)

**Comment by zadjii-msft** [comment]
Does running `wt.exe -d {whatever path}` from the commandline, or from the Run dialog work?

That error seems to imply that explorer couldn't even find `wt.exe`. Like, the error isn't coming from `WindowsTerminal.exe`, it's coming from `explorer.exe`.

Have you rebooted you machine since installing the Terminal? Sometimes explorer is weird and caches context menu entries, and the only surefire way to update them is to reboot explorer.exe

**Comment by freejool** [comment]
no.

it seems to be a link issue. 

i reinstalled it and it works well now (sacrificing my profiles :( )
