### ISSUE TITLE
Changing Defaults icon overrides existing profile's icon

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#12766]
### Windows Terminal version

1.13.10733.0

### Windows build number

10.0.19044

### Steps to reproduce

Change `Icon` in `Defaults` profile. `ms-appx:///ProfileIcons/pwsh.png` used for testing.

### Expected Behavior

Existing profiles to keep `Icon` setting.

### Actual Behavior

`Icon` changed for all profiles.

Before change:
![before_default_icon](https://user-images.githubusercontent.com/3933920/160241834-aeec56ef-4430-45d6-8f25-6addc270420f.png)

After change:
![after_default_icon](https://user-images.githubusercontent.com/3933920/160241854-123b7876-17ea-40c7-894d-915014aa49eb.PNG)

Q to devs: does `Settings defined here will apply to all profiles unless they are overridden by a profile's settings` apply to current profiles or new ones only, after a change is made in `Defaults` profile?

**Comment by zadjii-msft** [comment]
So, this is by design (albeit, contentious). 

Settings defined in `profiles.defaults` apply to profiles _after_ settings from dynamic profiles, and after settings from fragment profiles. 

> does `Settings defined here will apply to all profiles unless they are overridden by a profile's settings` apply to current profiles or new ones only, after a change is made in `Defaults` profile?

It just applies to all profiles, period. The base layer settings apply to all profiles, regardless of when chronologically they were defined. Base Layer sets the `profiles.defaults` settings in the JSON file. 

@cinnamon-msft I coulda swore we had a doc detailing all the layering, do we not?
