### ISSUE TITLE
chunkier scroll bar not rounded on w10 

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#12780]
### Windows Terminal version

1.13.10733.0

### Windows build number

10.0.19044.1586

### Steps to reproduce

open windows terminal on windows 10

### Expected Behavior

![image](https://user-images.githubusercontent.com/43626415/160509608-a8442e90-1677-463a-8335-21dccb297da1.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/43626415/160509471-d65eb4b6-1462-4b0d-b811-429245c97825.png)

**Comment by zadjii-msft** [comment]
Oh, I suppose it's not called out in the PR, but we did this as a part of #12608: https://github.com/microsoft/terminal/commit/da2cf8c3f667dfa1d1e25d1be083da6b0c47a83e#diff-b1a4ecfbe545b0b1bdff197c9a1f6484cc98943bf0923c635cb76c94c2b34d6bR58

We intentionally turned off the rounding on the corners, because it didn't really seem to mesh well with the top of the window.

As far as the rounding on the arrows and the thumb, that looks like that's by design. See

https://github.com/microsoft/terminal/commit/da2cf8c3f667dfa1d1e25d1be083da6b0c47a83e#diff-b1a4ecfbe545b0b1bdff197c9a1f6484cc98943bf0923c635cb76c94c2b34d6bR353-R360

(you'll have to load TermControl.xaml)

We copied in the styles from WinUI directly, and that section of the scrollbar style looks like it's responsible for changing the appearance of the arrows & thumb depending on whether the user is running Windows 11 or not.
