### ISSUE TITLE
Cascidia Mono Font not found: Release fix to stable

### ISSUE THREAD

**Issue by maxgerhardt** [microsoft/terminal#12879]
### Windows Terminal version

1.12.10732.0

### Windows build number

10.0.19044.1586

### Steps to reproduce

Start the terminal.

### Expected Behavior

No error messages, font works fine.

### Actual Behavior

Error message 

![grafik](https://user-images.githubusercontent.com/26485477/162626091-9cc66dfe-e2fa-4993-b483-298c97c640e3.png)

>"Warning: The selected font "Cascadia Mono" was not found.
> "Consolas" was selected instead
> Install missing fonts or choose a different one.

Most suspiciously, looking in the Microsoft Windows Store, it shows that an update has been executed *just today*, so it heavily suggests that an update broke it.

![grafik](https://user-images.githubusercontent.com/26485477/162626137-90b61c79-0f98-49dc-86d8-5047585541e7.png)

https://github.com/microsoft/terminal/issues/12420#issuecomment-1079498501 says this was fixed in the release version more than 2 weeks ago, can this land in the stable release?

**Comment by csi-lund** [comment]
Interesting that seems to affect VS as well
![image](https://user-images.githubusercontent.com/1974225/162687506-2d5a574d-e076-49f3-9675-8dada0873006.png)

**Comment by maxgerhardt** [comment]
The terminal in the preview version works for me (https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-13-release/) and when you look on disk where the preview terminal is there is also that font file. Maybe just installing the preview version fixes VisualStudio too?

**Comment by zadjii-msft** [comment]
> it shows that an update has been executed _just today_, so it heavily suggests that an update broke it.

Alas, that's actually how this issue occurs. Something about the update process leaves the font file locked in a way such that we can't read the file any longer.

As mentioned, this is already fixed in Preview, _hopefully_. I think we're gonna let this one bake there for a little while to make sure it A. actually worked and B. doesn't make things worse somehow. 


... Though, looking at #12554, I think we ended up servicing that to a 1.12 version, but I'm not sure which. @DHowett we may want to push the latest 1.12 release actually to GH.

**Comment by srdjanjovcic** [comment]
This issue is reproducible in Preview 1.13.10983.0 for me.
