### ISSUE TITLE
Bring back the old titlebar color

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#12939]
# Description of the new feature/enhancement
The black titlebar looks incredibly bad. I literally can't believe you did this, maybe it's a bug. It is catastrophically bad without focus. I can't watch it. So much so that I'm willing to reinstall the terminal to the previous release every time after an automatic update.

# Proposed technical implementation details (optional)
![image](https://user-images.githubusercontent.com/35394377/164107883-7f9264f6-4a92-48ec-9a5e-1ca759e8b14a.png)
Please friends

**Comment by zadjii-msft** [comment]
@gabbybilka, @cinnamon-msft as FYIs for feedback.

**Comment by antcodd** [comment]
Try enabling "show acrylic in title bar", it looks less bad. I personally preferred the old titlebar colour too, though I think most of the ugliness I've noticed is from #11561.

**Comment by Mystic8b** [comment]
> Try enabling "show acrylic in tab row", it looks less bad. Though it that mode the active and inactive tab are very hard to distinguish. I personally preferred the old titlebar colour too, though I think most of the ugliness I've noticed is from #11561.

Acrylic enabled. Previously, I achieved the same color for the titlebar and the terminal window, and in focus the entire window was transparent in the same color, and without focus, it was gray, but also without an explicit separation of titlebar and terminal. 
![image](https://user-images.githubusercontent.com/35394377/164254259-34f51d9d-7a47-43ee-b20b-cbf31cd97291.png)

Now, in focus, I have a different shade of acrylic on the titlebar and the terminal itself, and without focus - that's horror. The first thing I will do in the office the day after tomorrow is to roll back the terminal to the old version. I have no idea how this was missed in the release.

**Comment by Diogo-Rossi** [comment]
I agree. I don't know if it is the same issue, but now the active tab is not with the same color of the background.
I am used to think that the active tab has the background with the same black color as its title.

In the following example I think that the active tab is the first, but actually it is the second tab. It is confusing.

![image](https://user-images.githubusercontent.com/57204023/164283200-cc009889-2972-4bb6-9a5a-96bf5f5a886f.png)

I think it wasn't like that before. Please bring back the previous approach (or make it optional)

**Comment by bkshoemaker** [comment]
I agree with all the issues raised here, and would add that the black background on the tab bar is visually confusing because it bleeds into and is all but indistinguishable from the contents of the window (assuming your console background is black, which it is by default). From a usability standpoint, this is troubling since it's not immediately clear where you're clicking on the titlebar to drag the window, and where you're simply clicking inside the terminal.

The ideal solution in my view is to allow user customization of the tab and tab bar background colors, but assuming that's not a trivial addition, at a minimum the black tab bar background should be changed to a shade of gray that's easy to distinguish at a glance from the black console background. The previous color scheme of black active tab + gray inactive tabs and gray tab bar background was perfectly intuitive, as @Diogo-Rossi demonstrates (and a simple reversion would be fine by me).

Thanks for your work on Terminal, it's really been improving by leaps and bounds.

**Comment by robinmalik** [comment]
Could this be related at all? I'm currently running Terminal 1.12.10982.0 and I believe it updated to that yesterday, and since then I've seen:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/8790561/164674468-379b7b09-dcfc-4c5d-8967-1cc3184efd98.gif)

![image](https://user-images.githubusercontent.com/8790561/164676179-f2fbfa66-8ad5-4182-b093-29fc1aefc36b.png)

This problem has impacted the Windows Store application for me for at least 1 year (and I've been unable to fix it despite trying). Sadly now it's come to Windows Terminal.

**Comment by dansmor7** [comment]
You can still get the acrylic to match with the titlebar if you set the opacity to 50%:
![image](https://user-images.githubusercontent.com/101892345/164949301-97c111fb-c85c-4b8d-9cdc-ba9eb53861bb.png)
However, you can notice that there is now a border, which was added to the tab control with the last visual update.

In a recent PR it was made to span the entire window like it was supposed to:
![image](https://user-images.githubusercontent.com/101892345/164949336-90792698-c93b-407a-bd31-00dc526a6cf4.png)

This unfortunately makes it so that the titlebar and terminal can't be seamless anymore.

@zadjii-msft until the xaml theming is done, this could be fixed temporarily by making that border transparent.

**Comment by Mystic8b** [comment]
> You can still get the acrylic to match with the titlebar if you set the opacity to 50%

The problem is not in this, but in the fact that when the window is not in focus - completely black color looks catastrophically miserable. I sincerely do not understand why they did this, before the terminal was just perfect, now I can't look at it.

**Comment by dansmor7** [comment]
With the new visual design, the tab needs to have that specific color, and the titlebar needs to be darker. 
Would something like this be better? This is `#161616`.

![image](https://user-images.githubusercontent.com/101892345/164986741-4ad0606c-85ba-41e6-af49-d33fd79a918c.png)

**Comment by Diogo-Rossi** [comment]
@dansmor7 my point is that the color of the active tab and the color of the terminal should match, so I can see what tab is active.

This is the approach of tabs in Edge and Chrome browsers, look:

In this example in Chrome, I can say the active bar is the second.

![image](https://user-images.githubusercontent.com/57204023/165000282-1188bad2-6900-4472-9534-19b29d436a81.png)

In this example in Edge, I can say the active bar is the third.

![image](https://user-images.githubusercontent.com/57204023/165000316-647fb9c7-54e9-4712-b9f9-c15297dc313d.png)

To make it clear: I got a screen shot from the documentation using the previous color.
In this screen shot, I can say that the active tab is the third. That is because the colors match.

![image](https://user-images.githubusercontent.com/57204023/165000326-c0d6fc0f-b7d0-4a7b-92f3-30a7e6a3c256.png)

**Comment by zadjii-msft** [comment]
Thanks for all the feedback here folks. You've definitely been heard loud and clear - the new colors aren't great. We tried to better align to the new Windows 11 visual styles, but without Mica it all looks a bit like a mess. We've been meaning for some time now to let folks customize the colors of the titlebar and the tabs. We've got a lot of stuff planned here - including the potential to match the tab or titlebar to the terminal BG color automatically. 

I think this discussion has finally given us the kick in our pants to finally do that. I'm gonna finish whipping up some prototypes for #3327 while we work on merging the spec over in #12530.

**Comment by Kolobamanacas** [comment]
Dear Windows Terminal team, you are doing a great job and I personally appreciate it a lot as current Windows Terminal is the best multi-tab terminal application I've seen for the last 20 years. And I know there were a lot of discussions already, but I still wish to emphasize the importance of the matter to a mainstream developer. The first thing, that "feels" wrong is changing the coloring logic to the exact opposite of what is was before.

Here are two examples: old and new.

![WT1 Before](https://user-images.githubusercontent.com/20444060/165942950-377e989f-92e8-49f1-9da9-3b25fc142433.jpg)

![WT2 After](https://user-images.githubusercontent.com/20444060/165943010-caba5bfc-ca74-467d-8642-ce53c60f8d14.png)

Both screenshots have second tab highlighted, yet in fact, old example has the first tab as active and the new example has the second tab as active. This change obviously confuses people who use the Terminal for some time. And I believe most of new users would also loose a "guess an active tab" game.

The second and the most important point is that changes are ok as soon as they lead to better experience and/or are aligned with the best UI/UX practices. Yet with this change I believe the case is opposite. As [Diogo-Rossi](https://github.com/Diogo-Rossi) rightly noted, most modern apps utilize approach of having highlighted tab color matched with tab's background. And the change did the opposite of that. Again, as mentioned earlier, Edge, Chrome, VS Code, previous coloring of the Terminal, and even GitHub's comment widget are good examples of how tabs coloring could work decently and be something no one would complain about.

I really hope you'll take our concerns into consideration and make some adjustments in the upcoming releases.

Thanks.

**Comment by zadjii-msft** [comment]
@Kolobamanacas Yep, we're definitely working on that. I've got the prototype over in [`dev/migrie/f/702-link-tab-to-terminal`](https://github.com/microsoft/terminal/compare/dev/migrie/f/702-link-tab-to-terminal), and we're broadly tracking that in #702.
