### ISSUE TITLE
CMD Exit fails after running diskraid

### ISSUE THREAD

**Issue by JustinWebDev** [microsoft/terminal#12946]
### Windows Terminal version

1.12.10733.0

### Windows build number

10.0.22000.613

### Steps to reproduce

run Terminal as admin
issue cmd "diskraid"
issue cmd "exit"

### Expected Behavior

the terminal to exit and close

### Actual Behavior

C:\Users\hammack>exit
[process exited with code 4 (0x00000004)]

-> and it does not close

![image](https://user-images.githubusercontent.com/40804543/164247685-29c32481-32db-475d-a3b4-0c6027cf99b1.png)

**Comment by zadjii-msft** [comment]
[Please read the FAQs.](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#why-am-i-seeing-process-exited-with-code-)

**Comment by JustinWebDev** [comment]
This was incorrectly close.  CMD didn't crash.  The cmd failed, but CMD is operational.

**Comment by zadjii-msft** [comment]
No where in the "Why am I seeing `[process exited with code ...]`?" section does it talk about crashing...

The diskraid command returned a non-zero exit code. When you typed `exit` into `cmd.exe`, `cmd.exe` returned that exit code as it's own exit code. Because you've got the `closeOnExit` setting set to the default value of `"graceful"`, the Terminal will only close the pane when the client app returns with a exit code of 0. So what you're seeing here is the Terminal informing you that the client application you launched (`cmd.exe`) returned a non-zero value (the `4` that was returned by `diskraid`).

Does that make sense?

**Comment by zadjii-msft** [comment]
Sure okay - that's referring to the client commandline application crashing, not the terminal, and super not the point here 😉
