### ISSUE TITLE
Batch file issues

### ISSUE THREAD

**Issue by RichardD2** [microsoft/terminal#12967]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Other Software

Windows 11 File Explorer

### Steps to reproduce

Set the default shell terminal to Windows Terminal.

Create a batch file which executes multiple `robocopy` commands.

Find the folder in Windows Explorer, and double-click the batch file.

### Expected Behavior

The batch file should run to completion, and the terminal should either close or display the "process exited with code ..." message.

The `robocopy` output should fill the visible screen before scrolling off the top.

### Actual Behavior

If there are changes for the first `robocopy` to replicate, the batch file seems to be terminated part-way through a subsequent `robocopy` command.

The output often only occupies the first couple of lines of the visible window. It never fills the screen.

**Comment by AlanJWoodward** [comment]
Also suffering from this exact issue.

Windows Terminal version: 10.12.10983.0 (updated on 21st April 2022)
Widows OS build no: 22000.613

The issue didn't exist before upgrading to 10.12.10983.0

When running the batch file with robocopy, the batch file will stop at a random point and display:

[process exited with code 1 (0x00000001)]

Will run satisfactorily for one run, then fail.

**Comment by SemnoSao** [comment]
same problem when running ant commands

**Comment by zadjii-msft** [comment]
This is bizarre - there's something similar in #13185 but I honestly can't repro this. Maybe it's just my build (both of the OS and the Terminal)? 

That thread has a more minimal repro in it (rather than some specific robocopy commands). Anyone in this thread who was seeing this - does the minimal repro also cause the same thing for you (on a 1.14/1.15 Terminal)/?

**Comment by AlanJWoodward** [comment]
I'll check that out and get back to you soon.

**Comment by AlanJWoodward** [comment]
OK, so it does look as if the issue has now been fixed (unable to now reproduce with the ren files batch files, or my robocopy batch files).

I hadn't tried my robocopy commands in Terminal since it stopped working for me, but it looks like 1.14.11963.0 now works as it used to do before 1.12.10983.0 broke it.

The part screen loading also looks fixed too.

**Comment by zadjii-msft** [comment]
That's great, thanks for confirming! Who knows what part of the last few months fixed it, but I'm glad it's sorted out!
