### ISSUE TITLE
Unable to find the selected font "Cascadia Mono".

### ISSUE THREAD

**Issue by edward-ellis** [microsoft/terminal#12970]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19042

### Steps to reproduce

Open recently updated application

### Expected Behavior

For the app to open so that I can start using it.

### Actual Behavior

App opens popup window with message:
Unable to find the selected font "Cascadia Mono".
"Consolas" has been selected instead.
Please either install the missing font or choose another one.

Internet search says Font is included with the app.

**Comment by edward-ellis** [comment]
Installed font with chocko.  Said removing font, installing new font.  Installed successfully.  No change in the application's behavior.  Still complains every time I open it.

**Comment by jeffbeechg** [comment]
I have the same problem.

**Comment by jeffbeechg** [comment]
If you go to "Apps and Features" and select Terminal you can choose to "Repair" it. That did indeed fix it.

**Comment by FanShupei** [comment]
I have the same problem, and it's fixed by "Repair" it in "Apps and Features".  Thank you, jeffbeechg.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+Unable+to+find+the+selected+font+%22Cascadia+Mono%22+) when filing new issues.

See also [the FAQs](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#unable-to-find-the-selected-font-cascadia-mono).

The latest incarnation of this bug was /dup #12420, which was fixed in #12904, which unfortunately is not in the `1.12.1098*` family of builds, but should be in the next hotfix.
