### ISSUE TITLE
Improve VS2017 detection by leveraging VSWhere.exe

### ISSUE THREAD

**Issue by khouzam** [microsoft/Terminal#13]
With support for multiple versions of VS2017, using vswhere.exe to detect the location of an appropriate install would be easier.

**Comment by amweiss** [comment]
Happy to get a PR in for this @zadjii-msft , would the preferred approach be to require `choco install vswhere`, just require a version of `vswhere` be on the PATH before running razzle or something else?

**Comment by DHowett-MSFT** [comment]
Is it possible to use the VSWhere that ships with the installer? @heaths may know if that’s okay.

________________________________

**Comment by amweiss** [comment]
I have VS2019 and VS2019 Preview installed through the installer and the included VSWhere was not added to my path by default. I can try to locate `vswhere` to then locate `msbuild`, or just require it be on the path _somehow_ for it to run.

**Comment by heaths** [comment]
We don't add it to the PATH because it's not an oft-enough used tool. Every directed added to PATH merely increases lookup time.

I recommend you acquire vswhere.exe via nuget or chocolatey, as described [here](https://github.com/microsoft/vswhere/wiki/Installing). You can use the version we always install to "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" but you're rolling the dice on what features you get. For example, I just resolved a bug against vswhere because someone was using that path and trying to use the `-find` parameter that was added later. The only way to be sure you get the features you want is either use the ones we added initially (but that started in 15.2) or acquire it yourself. You can also redist it, which is what build systems like Azure Pipelines do (it's used by various built-in tasks).

**Comment by amweiss** [comment]
Thanks, I just got a version of `razzle.cmd` working with the chocolatey version and the `-find` parameter actually. It seems a bit heavy handed to put a `choco install vswhere` in `razzle.cmd`, but that would ensure it's a one step setup process. I'll post a PR in a few hours we can worth though, but on my environment it worked well.

**Comment by heaths** [comment]
Then why not use nuget? You already are using nuget generally, so put "vswhere" in your .nuget\packages.config file and it will get pulled if needed* whenever `nuget restore` is run in the repo. That's what a lot of our repos do - even vswhere [itself](https://github.com/microsoft/vswhere/blob/develop/.nuget/packages.config). You could assume a hardcoded path in your script even, but you'll have to remember to update it if you ever update to a newer version in packages.config. Or [do what we do](https://github.com/microsoft/vswhere/blob/develop/tools/test.ps1) and scan for it.

**Comment by amweiss** [comment]
I have a version started here: #606 but I can't get the build tools v141 working in VS2019. I don't want to mix that into this change so I want to get that sorted out before I make it a real PR.

**Comment by amweiss** [comment]
@khouzam you should be able to close this now that #606 was merged.

**Comment by DHowett-MSFT** [comment]
Fixed in #606,
Thanks!
