### ISSUE TITLE
Add an option to set the path of splits panes

### ISSUE THREAD

**Issue by moon250** [microsoft/terminal#13022]
# Description of the new feature/enhancement

Add an option to manage the start path of split panes.
This can take the form of an option in the ``settings.json`` file. It can take different parameters: 
 - ``default`` (the start path defined in the profile) (default value)
 - ``same`` (the current path of the pane where you split)
 - _custom_ (a path that will be used as the start path in each split pane)

# Proposed technical implementation details (optional)
 /

Sorry for my horrible english.

**Comment by zadjii-msft** [comment]
Largely, these are already settings:

Check out the docs: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#split-a-pane

`"splitMode": "duplicate"` will open the pane in the tab's CWD, if you've [configured the shell to tell the Terminal what it's CWD is](https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory).

You could always run the command `wt -w 0 sp -d .`, and that would always split a new pane, in the CWD of the shell, in the current Terminal window. The `-d .` here is extra convenient because it relies on the shell's own rules for evaluating what directory `.` is, without any extra config from your side. Downside there is that it only works at a shell prompt.
