### ISSUE TITLE
Problem using new-tab, move-focus, split-pane together

### ISSUE THREAD

**Issue by saeidjoker** [microsoft/terminal#13063]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Steps to reproduce

From wsl (Ubuntu-20.04) run this:
```bash
cmd.exe /c "wt.exe" --title frontend --suppressApplicationTitle \; sp -V \; nt --title backend --suppressApplicationTitle \; sp -V \; sp -H \; mf left \; sp -H
```

### Expected Behavior

title of the second tab should be __backend__. Something like this:

![image](https://user-images.githubusercontent.com/20520614/167376514-13055e5f-3b2c-42ea-abc1-6de28f273001.png)

### Actual Behavior

title of the second tab is the default wsl tab title.
I observed, that `mf left` causes this behavior. Also running this command is extremely slow (but this one requires another issue I guess?)

![image](https://user-images.githubusercontent.com/20520614/167376413-784f3cc2-5827-44d0-84b9-284e9e3efd77.png)

**Comment by zadjii-msft** [comment]
Ah so, this is basically by design. The `--title` parameter can be used both for [creating a new tab](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#new-tab-command), but also when [splitting new panes](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#split-pane-command). The title that's actually displayed on the tab is just the title of the focused pane within the tab.
