### ISSUE TITLE
Box-drawing characters in the Fira Mono font are not connected in the latest preview version of Terminal

### ISSUE THREAD

**Issue by MatejKafka** [microsoft/terminal#13064]
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Download the following font: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraMono/Regular/complete
2. Configure both Terminal and Terminal Preview to use this font
3. Run the following PowerShell command: ```echo "╦═════════`n╚╣"```
4. Zoom to various scales, compare the rendering in both Terminal versions.

### Expected Behavior

In both versions, the glyphs should be connected into uniform lines.

### Actual Behavior

Terminal Preview v1.13.10983.0:
**disconnected glyphs** – the vertical line is always broken, the horizontal line is rendered correctly at some font sizes, and incorrectly at others
![Screenshot 2022-05-09 134109](https://user-images.githubusercontent.com/6414091/167396376-da00158a-c27e-4317-96c2-2bfe66facd92.png)

Terminal (Stable) v1.12.10982.0:
**rendered correctly**
![Screenshot 2022-05-09 134133](https://user-images.githubusercontent.com/6414091/167396481-5276fcb8-0e25-445a-8aaa-fc2b40f9e421.png)

**Comment by christianparpart** [comment]
Out of curiosity. And you did not update the Fira Code font files in between the WT updates? To me this looks like a metric change. Box drawing characters are never easy to be rendered from font files in a monospaced grid system (TEs), and because of that, most terminals do implement pixel perfect rendering for certain codepoints explicitly, bypassing the font file all along for them. 
I am not sure if WT does that (to some degree already), but my point of view is, there's always one font file that has shitty glyphs for box drawing codepoints and will always fail. :)

**Comment by MatejKafka** [comment]
> And you did not update the Fira Code font files in between the WT updates?

Nope, I installed both versions of WT side-by-side and used the same font for both.

**Comment by kindermannhubert** [comment]
I have the same problem with Cascadia Code (I have WT 1.16.10261.0).
![image](https://user-images.githubusercontent.com/11704036/224552017-1c499d91-f499-4c0d-bb50-d2c93d8239ab.png)

vs this screenshot from cmd.exe:
![image](https://user-images.githubusercontent.com/11704036/224552087-bb4f3286-f042-4f1b-bc6b-2280ebe3858f.png)

**Comment by carlos-zamora** [comment]
This may be fixed definitively by #14959. If not, we'll soon be releasing a preview update that allows you to configure the line height #14255.
