### ISSUE TITLE
Extreme sluggishness and CPU usage when using Atlas inside a VM

### ISSUE THREAD

**Issue by jessey-git** [microsoft/terminal#13079]
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19044.1645

### Other Software

None

### Steps to reproduce

- Use Terminal inside a typical VM
- Switch to the experimental Atlas engine
- Observe CPU load
- Try to type and experience sluggishness and even higher CPU load etc.  There's a decent amount of lag and output from long commands tends to stutter into view; it's not very smooth

### Expected Behavior

Was expecting that Atlas, in default/easy cases, would perform better than the old engine.

Looking ahead: IF atlas becomes the default and IF Terminal replaces all old cmd windows, then using this inside VMs is going to be a non-starter.

### Actual Behavior

Extreme CPU usage and general sluggishness. Witness the firepower of this fully operational battle... I mean barely affordable Azure VM displaying nothing but the flashing cursor inside a blank Terminal window:

![atlas-perf](https://user-images.githubusercontent.com/7989986/167744410-1576f18e-27e4-4b72-a4d4-457db9d059b9.png)
![atlas-dxdiag](https://user-images.githubusercontent.com/7989986/167744490-c0cf7d48-d8e6-4c6b-a441-7e1391e253b1.png)

**Comment by DHowett** [comment]
Hmmmm....

I wonder if this is because we don't do differential rendering with the Atlas engine, so we're making the RDC server diff and compress at >=60fps.

@lhecker One of the main reasons we wanted to use `Present1` with dirty regions was to give the graphics stack--including the remote desktop server--as much information as it needs to be successful. Is that totally off the table for Atlas? Over remote desktop, full region presentation might be so expensive that it's worthwhile for us to burn some CPU up front in Terminal.

**Comment by lhecker** [comment]
I think this is `19041.1620.vb_release_svc_prod3.220311-1803`.
I've created a similar VM using TDP and I have a RDP latency of >200ms:

![image](https://user-images.githubusercontent.com/2256941/168333956-da1d7e94-8c2d-4889-ba04-ee1342936ad9.png)

![image](https://user-images.githubusercontent.com/2256941/168334074-2f4ef8f5-8aca-43a7-9642-302646d386ad.png)

I could not replicate the extreme sluggishness. The CPU load however is at around 14% compared to 4% for DxEngine. Additionally the perceived framerate while printing text is much better with DxEngine.

**Comment by lhecker** [comment]
I investigated this over the last few hours. My findings:
* Scroll rects/offsets, etc. don't help
* Device creation with `D3D_DRIVER_TYPE_HARDWARE` works, but there's no difference to `D3D_DRIVER_TYPE_WARP`, which indicates that there's no GPU. This makes sense, since it's a VM and Intel Xeons don't have iGPUs.
* `AtlasEngine` has "dependent texture lookups" which I believe are killing the VM. I modified the shader to just draw a screen full of the cursor texture and that uses 40% "GPU", whereas the full shader uses exactly twice that. This indicates that each additional texture lookup uses 40% "GPU" and since AtlasEngine does twice as many as the old DxEngine, it's twice as bad.

Proposed solutions:
* Meet and greet with the RDP folks to figure out how they got Direct2D to be fast
* Dynamic resolution scaling during scrolling: We simply draw 4x less pixels while the screen is scrolling and drop the GPU load from 80% down to 20%.

In the meantime I believe that the `AtlasEngine` is unusable on Azure VMs without dedicated GPU.

**Comment by lhecker** [comment]
@jessey-git Do you have VS Code installed in your VM? Does it's builtin terminal stutter just as bad for you? In my testing it does...
(Alternatively any other Terminal based on [xterm.js](https://xtermjs.org/), or an IDE made by Jetbrains, or any other software which isn't based on Direct2D.)

--

Some thoughts for the team:
We have this problem now, where the new renderer significantly improves performance on any GPU conceived in the last 10 years, but is significantly worse on any hardware older than that and those without a GPU at all (like your server), because they fall back to a pure software-GPU called WARP. How do we now reconcile the wishes for performance by the "many" who have long had such "new" hardware with the fundamental needs of a working terminal by the "few" who don't have such hardware?
My idea is that we could just implement a "poor man's DxEngine" inside AtlasEngine. One that supports all basic functionality, but is not the main-goal of development. It would work well on such problematic hardware, but I wouldn't necessarily implement double-height/width text or sixels, etc. Basically I'd focus on basic text rendering when no GPU is available only, with added support for all basic text attributes, color and selection. Thoughts?

**Comment by jessey-git** [comment]
@lhecker Yeah, that sucks too. Here's a comparison of what it looks like when holding down a key between Terminal DxEngine and VS Code's integrated terminal window:

[Terminal DxEngine Holding key]
![Terminal_DxEngine_HoldingKey](https://user-images.githubusercontent.com/7989986/168497922-b074ea9e-eb48-462f-a37b-516b256ab954.png)

[VS Code Integrated Holding key - nearly 4x higher]
![Code_Integrated_HoldingKey](https://user-images.githubusercontent.com/7989986/168497907-b28e1248-b371-4be6-ac53-3d638a397ada.png)

**Comment by DHowett** [comment]
> My idea is that we could just implement a "poor man's DxEngine" inside AtlasEngine.

Honestly that just sounds like "keep the DxEngine" which is a lot easier ;)

**Comment by lhecker** [comment]
> Honestly that just sounds like "keep the DxEngine" which is a lot easier ;)

Does it make sense to switch between the two engines, if you connect via RDP to your PC?
Also, we can reuse the DirectWrite parsing in AtlasEngine and deduplicate the code.
