### ISSUE TITLE
Thick white border around window when showTabsInTitlebar enabled

### ISSUE THREAD

**Issue by dkter** [microsoft/terminal#1307]
# Environment

```none
Windows build number: 10.0.18362.145
Windows Terminal version (if applicable):
```

# Steps to reproduce

Set `showTabsInTitlebar` to true in the settings file, and then start up Windows Terminal.

# Expected behavior

The window should be surrounded with a thin grey border:

![image](https://user-images.githubusercontent.com/34610081/59715770-9205c980-91e2-11e9-8de9-7e9307e1ab4e.png)

# Actual behavior

A thick, non-Windowsy white border is shown instead.

![image](https://user-images.githubusercontent.com/34610081/59715568-2c194200-91e2-11e9-96b0-7ac1e3f61e86.png)

**Comment by DHowett-MSFT** [comment]
This will be addressed as part of #872.

**Comment by sznedalm** [comment]
Even though the issue was closed on Jun 18, I still have the same problem described in the OP. My Windows build number is `18362.30` and my Windows Terminal version is `0.5.2681.0`. Note that the border was still present when using the terminal on my Windows Insiders machine on the Fast update ring.

![bug](https://user-images.githubusercontent.com/55198473/65840374-831dcf80-e318-11e9-902c-e11e8faa6169.png)

**Comment by zadjii-msft** [comment]
I'm gonna track this as part of #1625. I'm not sure that it's totally fixable in a good way, but I want to spend more time trying.

**Comment by zadjii-msft** [comment]
(We think that this is going to be closely related to a bucket of things, #3136 #1859 #3064 #1307)

**Comment by wolf99** [comment]
I have v0.7 on 1903. 
This issue is still present, in fact I only started noticing it in the last week,  so am assuming it only _started_ on my system with v0.7 🤦‍♂

**Comment by DHowett-MSFT** [comment]
There is a pinned issue for your concern; please continue discussion there.
