### ISSUE TITLE
Deleting all profiles crashes Windows Terminal

### ISSUE THREAD

**Issue by lhecker** [microsoft/terminal#13125]
### Windows Terminal version

1.13.11373.0

### Steps to reproduce

1. Delete all profiles

### Expected Behavior

* Shouldn't crash

### Actual Behavior

* Crash

**Comment by carlos-zamora** [comment]
A few quick thoughts...
1. this is probably relatively new behavior now that you're allowed to delete _any_ profile (instead of just the custom ones, since we blocked deleting CMD before state.json got added)
2. back in the JSON-only days, we would throw a warning/error and (I believe) fallback to the default settings
3. Wouldn't this be a case of "play stupid games..."? 100% agree we shouldn't crash, but I feel like solution would be that we fallback to the default settings (like before) until you fix it, but then that might cause a weird state with the SUI. I'm just concerned we'd need major changes to fix a crash that presumably very few (if any) people are accidentally hitting.

**Comment by j4james** [comment]
Is this perhaps the same thing as #13017?

**Comment by lhecker** [comment]
No those are separate issues as far as I can tell. #13017 occurred when you saved your settings and you deleted a profile afterwards. Due to a bug in the UI code it crashed.

But I noticed that we also crash if you simply delete all profiles.
