### ISSUE TITLE
Freezing upon autocomplete when line ends in semicolon.

### ISSUE THREAD

**Issue by alexrusselldev** [microsoft/terminal#13135]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.0

### Other Software

Ubuntu 20.04 (WSL2)

### Steps to reproduce

1. Open bash
2. Type in a line that ends in s semicolon
3. Press tab to autocomplete

### Expected Behavior

An error bell

### Actual Behavior

The terminal freezes for 20-30 seconds before resuming.

**Comment by DHowett** [comment]
This is because you are completing the name of an executable, and WSL by default considers all Windows `exe` files to be executable. It takes a while to search the entire Windows `PATH`.

Unfortunately, it is not a Terminal problem. Fortunately, however, there are issues about this on the WSL repository.
