### ISSUE TITLE
Feature Request: Please copy the content of highlighted text, after press Enter.

### ISSUE THREAD

**Issue by zhwghl** [microsoft/terminal#1315]
Please copy the content of highlighted text, after press Enter as the regular cmd.exe will do. When I was using cmd.exe I got used to copying something by highlight them and press enter, please bring this to the new Windows Terminal.

**Comment by zadjii-msft** [comment]
Well this will certainly need a spec. I believe @carlos-zamora is working on a spec for mouse bindings currently, maybe this should be called out in it.

This one's tricky though, since it's technically a keybinding that only applies when there's a selection. Perhaps I should be doing the calling out in #1142. Perhaps we need to somehow still have a "selection mode" like conhost did, and keybindings that only apply to that mode. I don't know how we'd manage that, but that's what the spec is for.

**Comment by eraineri** [comment]
I would also like to see when you highlight the text the data is automatically copied with no need to do anything else.

**Comment by zhwghl** [comment]
> I would also like to see when you highlight the text the data is automatically copied with no need to do anything else.

I don't think that's a good idea to automatically copy any highlighted content. This might confuse the uses.

**Comment by zhwghl** [comment]
> Well this will certainly need a spec. I believe @carlos-zamora is working on a spec for mouse bindings currently, maybe this should be called out in it.
> This one's tricky though, since it's technically a keybinding that only applies when there's a selection. Perhaps I should be doing the calling out in #1142. Perhaps we need to somehow still have a "selection mode" like conhost did, and keybindings that only apply to that mode. I don't know how we'd manage that, but that's what the spec is for.

If I didn't get it wrong, I believe we have mouse binding for copying by right clicking the mouse, which is now the only way to copy and pasted the highlighted content. I did not know that we don't have the selection mode and the keybinding and mousebinding are handled separately.

**Comment by DHowett-MSFT** [comment]
We're moving all copy selection issues to #524
