### ISSUE TITLE
WT -f <myApp.exe> causes glitched window

### ISSUE THREAD

**Issue by jredfox** [microsoft/terminal#13181]
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19044.1706

### Other Software

java.exe

### Steps to reproduce

`wt -f java` --> produces a window in which you cannot close there is no x button.

### Expected Behavior

it open up the default profile with the batch icon on the top left and it execute normally. `wt java` will produce the proper result

### Actual Behavior

bordless window you cannot close.
![java 5_25_2022 10_09_28 PM](https://user-images.githubusercontent.com/9736369/170407931-b05795ff-db64-4eac-b8e0-3fb5efa22ccd.png)

running `wt new-tab -f java` seems to fix it. but why isn't' there an error message if `-f` requires the new tab?

**Comment by zadjii-msft** [comment]
This is totally by design. [`-f` before any subcommands](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#options-and-commands) opens the window in fullscreen mode. There's no frame in fullscreen mode by design. There's a variety of QoL improvements to fullscreen mode we're tracking in #3486

**Comment by jredfox** [comment]
It's not in Fullscreen. Its in a normal window missing the buttons

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jredfox** [comment]
@zadjii-msft reproducable with `wt --focus java`

**Comment by zadjii-msft** [comment]
Derp. 

`-F` is fullscreen.

`-f` is "focus mode". It should still have borders around the window though. Something that looks like:
![image](https://user-images.githubusercontent.com/18356694/170477502-d12e2c3a-200b-4e81-98b2-fd1e02fbaf51.png)

You should be able to leave focus mode with the "Toggle Focus Mode" command in the Command Palette

**Comment by jredfox** [comment]
![Capture](https://user-images.githubusercontent.com/9736369/170477759-a869f731-1e02-413b-b8bb-d9820d9334da.PNG)

**Comment by zadjii-msft** [comment]
Focus mode is a feature. An intentional mode for the window without any other chrome. There are still tabs in focus mode, they're just hidden. 

![fomo-sample-000](https://user-images.githubusercontent.com/18356694/170480174-0144b900-eea6-4679-b00a-aacfad49703e.gif)




> the `--focus` usual behavior is to focus the right tab or window so the user doesn't have to look for it

Pretty sure that `--focus` has been used to launch in focus mode for the Terminal since we introduced that argument.
