### ISSUE TITLE
GUI apps still don't open in the foreground, from a default terminal launch

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#13211]
A TCC user said that GUI apps started by TCC in WT don't get focus (unlike other shells in WT and unlike TCC in a console).  I said I didn't think I could get TCC and/or WT to act that way if I tried.  Have I overlooked anything ... any ideas?  Thanks!

**Comment by DHowett** [comment]
This is not actionable without knowing the version of Windows Terminal the TCC user has installed -- we made some significant windowing changes in Preview 1.14.

**Comment by vefatica** [comment]
His setup is the same as mine.  I have no such problem.

v:\> ver
TCC 28.02.18 x64
Microsoft Windows 10 Pro for Workstations
10.0.19044.1706 (2009, 21H2)
WindowsTerminalPreview 1.14.1432.0

**Comment by vefatica** [comment]
The user in question is using WindowsTerminalPreview 1.14.2205.25002.  I am using WindowsTerminalPreview 1.14.2205.23002.

Is that newer build available on GitHub?

**Comment by zadjii-msft** [comment]
I don't think the revision numbers make a difference here. 

Do you have a link to the original bug report?

There was a LOT of work in this area in 1.14, in #2988, #12515, and every thread linked to those. How are the GUI apps getting spawned by TCC? Via `ShellExecute`?

**Comment by vefatica** [comment]
Here's a [link](https://jpsoft.com/forums/threads/tcc-does-not-pass-focus-to-applications-launched-by-tcc-from-windows-terminal.11203/#post-63560) to the original report.

I suspect with CreateProcessW.  WinDbg isn't being very cooperative:

0:001> bp shell32!ShellExecuteW
0:001> bp shell32!ShellExecuteExW
0:001> bp kernel32!CreateProcessW
Couldn't resolve error at 'kernel32!CreateProcessW'

It does not break on ShellEXecute[Ex].

**Comment by vefatica** [comment]
I tried again.  WinDbg does break at CreateProcessW when I issue "notepad".

**Comment by vefatica** [comment]
Mike, if you're following, you'll be  interested in [#18](https://jpsoft.com/forums/threads/tcc-does-not-pass-focus-to-applications-launched-by-tcc-from-windows-terminal.11203/post-63576).  The user reports that whatever shell is in WT's FIRST tab will exhibit this problem.

In a nutshell ... it's not only TCC.

**Comment by vefatica** [comment]
And, if I read his comments accurately, he has a setup in which WT is the default handler for console apps (as opposed to conhost).  Musy be (?) he has some sort of insider status.

**Comment by ohenryx2** [comment]
I was the originator of this bug report, over on the JPSoft forums.  I mistakenly thought the problem was limited to TCC, but that is not the case.

I am not an “Insider”, this is a public build of Windows Terminal Preview, and a public build of Windows.

Microsoft Windows
Version 21H2 (OS Build 22000.708)


Windows Terminal Preview
Version 1.14.1452.0

I obtained Windows Terminal Preview from the Microsoft Store.  It offered to make itself the default handler for shells, and I accepted the offer.  I have shortcuts on the desktop for cmd.exe and tcc.exe (Jpsoft).  If I click on either of those shortcuts, they start in a new Windows Terminal Preview tabbed window.  And from there, if I start an application (notepad, for instance), the focus stays in the Windows Terminal Preview window, it does not shift to the newly launched application.  The same behavior for tcc and for cmd.  Doesn’t matter if I type in “notepad” or “start notepad”.

Also, if I launch Powershell Preview from the Start Menu, it starts up in a Windows Terminal tabbed window, and exhibits the same behavior.

Now once I have a window up for Windows Terminal Preview, if I start another tab, the problem does not exist in the secondary tab.  And it doesn’t matter what’s running in the secondary tab, cmd, tcc, pwsh, all behave normally.  Launch an application, that new application gets the focus.

And if I kill the primary tab, so the secondary tab becomes the primary tab, there is now no problem in the new primary tab.  

I also have Windows Terminal Version: 1.12.10983.0
Installed on this system.  I have placed a shortcut on the desktop for
C:\Users\Henry\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt.exe c:\tcmd\tcc.exe

That launches tcc under the older version of WT, and the problem does not then exist.

**Comment by zadjii-msft** [comment]
Thanks for all the background guys. I had a feeling this was related to defterm, and everything here confirms that suspicion. I bet the focus/foreground handler isn't triggered for defterm connections. I'll take a look.

**Comment by zadjii-msft** [comment]
`TerminalPage::_InitControl` - tells the control the window is visible (but not focused). It also tells the connection about the owning hwnd. 

I'm betting that the owner is never set for that pane. If it were set, then deactivating and reactivating that pane would re-mark the pane as focused, fixing the issue. I bet the conpty here never knows the owner, so when it checks if the owner is focused - it never is.

**Comment by miniksa** [comment]
@zadjii-msft sorry to leave you with this headache but great analysis and I'm glad that process information I left behind was worth it!
