### ISSUE TITLE
is this a memory leak?

### ISSUE THREAD

**Issue by lost4git** [microsoft/terminal#13233]
### Windows Terminal version

1.13.22053001

### Windows build number

10.0.22000.0

### Steps to reproduce

![image](https://user-images.githubusercontent.com/65008815/172135890-ab0ea5de-4a86-4132-9c55-c6154075a8ed.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/65008815/172136362-f68a320a-c137-49b7-884f-960e5f3bf0a1.png)

**Comment by zadjii-msft** [comment]
That sure looks like a memory leak to me. What were you doing at the time this occurred? Is it reproducible for you/?

**Comment by lost4git** [comment]
I don't know how to reproduce the problem, so only continue to observe

**Comment by zadjii-msft** [comment]
Welp, that's... not super helpful by itself. We've had another leak in recent memory, but also without a clear cause. I'm gonna leave this open for a week to see if you can find a repro. Of course, feel free to comment here if you find one even after that week.

**Comment by lhecker** [comment]
A fellow Process Hacker user! 😻

If you encounter such a bug again and would like to help us out, please consider using the "Create dump file..." option:
![image](https://user-images.githubusercontent.com/2256941/172193899-07af4cc2-abfc-431e-8e7d-57a7ccb983e1.png)

This process might take a few minutes and create a potentially very large `.dmp` file (up to ~9GB in your case), but it would help us a lot at finding the root cause. (Those `.dmp` files may contain private information and should only be shared privately / via mail however.)
