### ISSUE TITLE
PSReadLine's -ViModeIndicator "Cursor" doesn't work correctly

### ISSUE THREAD

**Issue by nlguerra2003** [microsoft/terminal#13235]
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22621.0

### Other Software

PSReadLine

### Steps to reproduce

- Activate PSReadLine's Vi mode: `Set-PSReadLineOption -EditMode Vi`
- Activate "Cursor" as mode indicator: `Set-PSReadLineOption -ViModeIndicator Cursor`
- Since you start in INSERT mode, just type Esc to change to NORMAL.

### Expected Behavior

Cursor should, as it happens in "pure" powershell, be a box in NORMAL mode, and the default one in INSERT (it doesn't matter what cursor you set up in WT).

### Actual Behavior

Cursor won't change no matter what mode you select. It will always be the configured cursor.

**Comment by nlguerra2003** [comment]
```
PS Version: 7.2.4
PSReadLine Version: 2.2.5
```

**Comment by juliekoubova** [comment]
Happy holidays, folks! Any update on this?

**Comment by j4james** [comment]
The problem was that PSReadLine was originally using the .NET `Console.CursorSize` API to change the cursor size, and that relies on the Win32 `SetConsoleCursorInfo` API, which isn't supported in Windows Terminal (that's more or less tracked in issue #7382).

The good news is that PSReadLine recently merged a PR (https://github.com/PowerShell/PSReadLine/pull/3374) which updates the `ViModeIndicator` implementation to use escape sequences to change the cursor shape (switching between a block cursor and underscore cursor), and that should work in Windows Terminal.

Unfortunately it doesn't look like that fix has been released yet, but I'm guessing it will likely be included in the next PSReadLine release.
