### ISSUE TITLE
Bring back ShowWindow functionality

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [microsoft/terminal#13248]
# Description of the new feature/enhancement
Bring back ShowWindow functionality as after #13164 only hiding the window works.

# Proposed technical implementation details (optional)

**Comment by FoxtrotSierra6829** [comment]
Yes, I got a node application using https://github.com/felixhao28/node-systray and https://github.com/hetrodoo/hetrodo-node-hide-console-window-napi which is intended to be hidden to tray by default but which can be un-hidden to allow watching status information. While this works very well with windows console host set as default terminal application, it does not with windows terminal.

https://github.com/flybywiresim/simbridge

<details>
<summary>Windows Console Host</summary>

https://user-images.githubusercontent.com/50082450/172674510-04a2487e-2a92-461a-887d-375766216b0a.mp4




</details>

<details>
<summary>Windows Terminal Preview</summary>



https://user-images.githubusercontent.com/50082450/172674633-c0f39503-fc81-44aa-b990-983a8d852eee.mp4


</details>

**Comment by zadjii-msft** [comment]
Out of curiosity - how do you expect your app to work in a multi-tab, multi-pane scenario? We don't have a lot of folks even attempting this in the wild, so any and all feedback is appreciated ☺️ 

* What would you expect if you tried to `ShowWindow(GetConsoleWindow(), SW_SHOW) `from an inactive tab? (e.g. user starts the script, switches to another tab and starts working there, and eventually the script in the inactive tab calls ShowWindow)
* Same question, but for an inactive pane 
* Same as the above questions, but now you've minimized the Terminal (e.g. an inactive tab, in a minimized window, calls ShowWindow)
* Would outputting the [XTWINOPS sequences `CSI 1 t` and `CSI 2 t`](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) for show/minimize be possible for you rather than calling ShowWindow on `GetConsoleWindow`? I don't think that works today, but that might be easier to fix.

**Comment by DHowett** [comment]
(I'm not asking to discourage you, I'm asking because these are the kinds of things that Terminal forces us to think about. Since it's an upending of the Console infrastructure that has existed on Windows for a few decades, we have to get these things right.)

**Comment by FoxtrotSierra6829** [comment]
> - What would you expect if you tried to ShowWindow(GetConsoleWindow(), SW_SHOW) from an inactive tab? (e.g. user starts the script, switches to another tab and starts working there, and eventually the script in the inactive tab calls ShowWindow)

I would expect it to switch the tab to the previously inactive one and focus on it.

> - Same question, but for an inactive pane

I'd expect it to focus on the pane which is tied to the call

> - Same as the above questions, but now you've minimized the Terminal (e.g. an inactive tab, in a minimized window, calls ShowWindow)

It should maximize the Terminal, focus on the tab which is tied to the call and if applicable, focus the specific pane.


> - Would outputting the [XTWINOPS sequences CSI 1 t and CSI 2 t](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) for show/minimize be possible for you rather than calling ShowWindow on GetConsoleWindow? I don't think that works today, but that might be easier to fix.

Given my previous answers, this would not behave exactly as described, but at least it would provide some basic functionality.

> - If there are multiple panes currently visible, and the application in one of them decides to hide its "console window", does that pane get sent away? 

I'd expect it to ask for confirmation to hide the entire window, same for tabs. I can't really think of a scenario where one would want to temporarily hide one pane as in that case tabs or multiple windows would be more suitable.

> - How should this work user-driven preferences like "always on top" or the use of the Quake-style window (which is docked at the top of the screen and can be summoned with a hotkey)?

Always on top should be affected in the same way as a minimize call does now, as I expect show and hide calls to be user-desired. Else an option to disable this functionality entirely could be considered. The Quake-style window should be hidden when ShowWindow is being set to false, and restored when ShowWindow is being set to true.
