### ISSUE TITLE
Scroll wheel no longer works correctly in OpenConsole

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#13253]
### Windows Terminal version

Commit ed27737233714dea77877624d1beeb49e2ccd36e

### Windows build number

10.0.19044.1706

### Steps to reproduce

1. Checkout commit ed27737233714dea77877624d1beeb49e2ccd36e or later.
2. Build and run OpenConsole.
3. Perform a few directory listings or something to get a couple of pages into the buffer.
4. Use the scroll wheel to scroll back in the buffer.
5. Use the scroll wheel to scroll forward again.

### Expected Behavior

Scrolling should work correctly in both directions.

### Actual Behavior

When I attempt to scroll forward, the viewport immediately jumps back to the start of the buffer.

I did a git bisect, and it looks like this problem may have been introduced by commit ed27737233714dea77877624d1beeb49e2ccd36e.

/cc @lhecker

**Comment by lhecker** [comment]
I'll check this out as soon as I can. Quite curious that this happens because I did notice this exact bug while I was developing the PR and fixed it.
It can occur when you aren't careful when extracting the wheel delta, as it's stored as a signed 16-bit integer in the high word of the `wParam`: https://github.com/microsoft/terminal/blob/4e20a8631cbb5b20defe549a0e75bc7719969bee/src/interactivity/win32/windowproc.cpp#L653

Initially I had replaced all `(short)` with `(til::CoordType)` which caused large jumps during scrolling. This appears to be the exact same bug? Scrolling down (e.g. wheel delta `int16_t(-3)`) gets passed around as a very large but equivalent positive number (`uint16_t(65532)`). And now with everything as `int32_t` this doesn't work anymore.

**Comment by elsaco** [comment]
Building 4e20a86 wheel scrolling works as expected:

https://user-images.githubusercontent.com/3933920/172752195-bd0e093e-f26c-470c-821b-4f9f45e303e6.mp4

200 one-line git log entries were used to fill the buffer. Does it need more data in the buffer to trigger the bug?

**Comment by j4james** [comment]
FYI, I think the issue might be here:
https://github.com/microsoft/terminal/blob/ed27737233714dea77877624d1beeb49e2ccd36e/src/host/scrolling.cpp#L145

We're dividing a short by an unsigned long, which I think is treated as an unsigned division, and that results in a massive positive delta. Previously the `ulActualDelta` was cast to `short` here, so it was a signed division.
