### ISSUE TITLE
Windows terminal crashes suddenly without any visual output

### ISSUE THREAD

**Issue by ThakurKarthik** [microsoft/terminal#13262]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19043.0

### Steps to reproduce

Ok I can help better if you can guide me on how to give you any error logs. But right now the issue is that windows terminal just closes/crashes without any error feedback. My use case is simple I open the terminal and navigate to some path and open vscode and I keep the terminal open to run some npm commands. I am not sure when but the terminal crashes if I have one or two or multiple tabs open at once.

### Expected Behavior

Windows terminal should not crash as I change to multiple directories and if it crashes then I have to open the terminal again and navigate to those paths again.

### Actual Behavior

As I mentioned the terminal window crashes

**Comment by zadjii-msft** [comment]
If you've got a consistent repro, then the Feedback Hub should be able to capture the crash dump. /feedback

**Comment by ThakurKarthik** [comment]
The issue is intermittent, feel free to close it for now. I will reopen it back when I can reproduce the issue.

**Comment by zadjii-msft** [comment]
Thanks!

**Comment by ThakurKarthik** [comment]
@zadjii-msft I was able to run the feedback hub recording and (un)fortunately the terminal crashed too, here is the link https://aka.ms/AAh9yy4 Let me know if you need any thing

**Comment by ThakurKarthik** [comment]
@zadjii-msft any progress over here ?

**Comment by zadjii-msft** [comment]
Sorry, was out on vacation. Just catching up now. 

The only crash I'm seeing is for something called `AW.WinPC.Updater.exe` - any chance you've got something called "Air Watch" installed? I honestly have no idea what that is or why that crashing would bring down the Terminal. Unfortunately, there wasn't really anything else that the Feedback Hub captured about the Terminal, so it seems to suggest that the problem lies outside the Terminal itself...

**Comment by simeyla** [comment]
I've given up on using Terminal since it just crashes and disappears leaving processes still running.
I'm sure it's happening when memory is low, but that's no excuse. I just look for it and it's gone.

I never seem to see anything in EventLog but that doesn't necessarily mean anything since I don't immediately always notice or look.

**Comment by kentcb** [comment]
I'm about to give up too, found this issue when searching for answers. It's happened to me twice today: two separate terminal windows open, each with several tabs. They just disappear without any feedback at all (except I notice things in my dev process stop working, since processes in those terminals are critical).

It's kind of silly that one must be recording to capture the problem, since the problem appears completely random in nature. There should be some kind of ability to turn on a log so one can check retrospectively what caused the crash.

**Comment by omair2084** [comment]
I experienced the same and landed here.
So, for me the issue is actually automatic updates to the Terminal which causes this problem.
![image](https://github.com/microsoft/terminal/assets/18167139/6b809201-cdc3-4b4d-ab8d-539ccfd1e131)

This seems to be a known problem https://github.com/microsoft/terminal/issues/6726

**Comment by CrazySqueak** [comment]
I have this issue as well.

Found this in Event Viewer > Windows Logs > System:
![Image](https://github.com/user-attachments/assets/4cc9dd8a-b3e1-4e36-b8d4-504f848ce92a)

I did not click any "update now" button or anything like that. I had processes running that I'd prefer weren't interrupted abruptly by the system.
Luckily I was only idling for 20 minutes or so before realising it had stopped, and luckily it was able to be resumed once I manually re-opened the terminal and re-ran the command.

Windows version:
Windows 10 Home (x64)
Version 10.0.19045 Build 19045

Terminal version:
Before update: not sure.
After update: 1.21.10351.0
