### ISSUE TITLE
[DxD] `closeOnExit` should be sensible when launched via defterm

### ISSUE THREAD

**Issue by Andrew1988123123** [microsoft/terminal#13325]
### Windows Terminal version

Windows Terminal Version: 1.13.11432.0

### Windows build number

Microsoft Windows [Version 10.0.22000.739]

### Steps to reproduce

1. Turn PC on
2. Wait approximately 30min
3. Windows Terminal opens with error "ERROR: The specified directory does not exist."

### Expected Behavior

Windows Terminal shouldn't opens every time I turn PC on. 

### Actual Behavior

Every time I turn PC on and approximately after 30min Windows Terminal automatically opens new windows terminal with error "ERROR: The specified directory does not exist." WT startup is turned off. I don't use additional script to open WT.
Screenshot of the error https://prnt.sc/OTSf0FKHT9Dt
Full tab path C:\WINDOWS\System32\forfiles.exe

**Comment by zadjii-msft** [comment]
> Full tab path C:\WINDOWS\System32\forfiles.exe

Sounds like you've got the Windows Terminal set up as the default terminal emulator, and something you have installed is running a `forfiles` command. That `forfiles` is automatically launching in a Terminal window, instead of a console window. However, the Terminal doesn't automatically close when a commandline application exits with an error, unlike the console. 

Now, trick here is that `forfiles` here isn't actually telling you what the missing directory is, just that it couldn't find it. I honestly don't know how you'd figure out who's launching that.

You might be able to mitigate this by setting [`closeOnExit: always`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#profile-termination-behavior) in the `profiles.defaults` part of the settings. 

I think we had previously discussed defterm invocations defaulting to that value - lemme bring that up with the team again.

**Comment by zadjii-msft** [comment]
discusssion: 
* is "close on exit" for _things started by the Terminal_? Can we just reframe `graceful` to "always" for defterm?
* Meh, lets do the optional thing above?
* Meh lets just just do always as the default? 
* Maybe we should have an setting between always and graceful "always so long as we actually got some bytes out of the connection"
* but uhg, that's not actually helpful for defterm
* you can't actually _set_ graceful explicitly in the SUI - the profile will already say you're set to "graceful"
* **Maybe there needs to be "gracefulIfLaunchedByTerminal", which is the new default, which is "always" for defterm. It's annoying but okay.**
