### ISSUE TITLE
Run profile as Administrator is not allowed

### ISSUE THREAD

**Issue by wolf99** [microsoft/terminal#13334]
### Windows Terminal version

1.13.11431.0

### Windows build number

21H2 (19044.1706

### Steps to reproduce

Windows is managed by my organisation.
Usually UAC will allow me to run things locally as an administrator as my org has not blocked this.

- Create a cmd prompt profile with `Run this profile ad Administrator` switched `On`
- Try to open a new tavb using this profile

### Expected Behavior

- Security policy requests confirmation of execution
- User confirms execution
- Tab opens in administrator mode

### Actual Behavior

- Security policy requests confirmation of execution _(for `unknown` app)_
- User confirms execution
- Windows warns that the app has been blocked

![image](https://user-images.githubusercontent.com/281700/174566129-b38091a6-9eed-4212-af31-4797fa926f75.png)

Spitballing; perhaps policy is not specifically blocking WT, but _is_ blocking "unknown" apps, which would mean that this is related to https://github.com/microsoft/terminal/issues/12357

Note that using gsudo to achieve admin access instead of the WT-native feature, does not suffer from this same issue. There the execution is on `gsudo` though...

https://www.howtogeek.com/789658/how-to-open-powershell-as-admin-in-windows-terminal/

**Comment by zadjii-msft** [comment]
Can you run the terminal successfully as admin via the right click on taskbar, right click on app, run as administrator shortcut?

![image](https://user-images.githubusercontent.com/18356694/174586342-fb5a9085-81e4-4621-adaa-696923f5f9fc.png)

I suspect this is because the app isn't installed for the admin profile, but I can't be sure. Can you contact your sysadmin for clarification on what policy specifically blocked this/? That might help us get to the root cause on our end.

FWIW I believe the "unknown program" thing is a known bug in Windows 10 that _should_ be getting serviced.
