### ISSUE TITLE
Lag when opening

### ISSUE THREAD

**Issue by Leohige** [microsoft/terminal#13379]
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22000.0

### Other Software

Fresh Windows 11 Install

### Steps to reproduce

Open Terminal

### Expected Behavior

Open smoothly

### Actual Behavior

Takes 5 seconds to open, the window is frozen

![image](https://user-images.githubusercontent.com/7697524/175658665-eee8a679-f939-416f-a419-8129a8d369ea.png)

**Comment by Leohige** [comment]
I don't know why, but it seems to be related to Alienware Command Center software.

If it's installed the terminal always froze, even with a windows 11 fresh install.

https://www.dell.com/support/home/pt-br/drivers/driversdetails?driverid=1nn4h

**Comment by lhecker** [comment]
If it only occurs when the Alienware Command Center software is installed, is it still a bug in Windows Terminal? 🤔

Does the Terminal (or maybe any other application) use a lot of CPU during those 5 seconds?

**Comment by Leohige** [comment]
> If it only occurs when the Alienware Command Center software is installed, is it still a bug in Windows Terminal? 🤔 Does the Terminal (or maybe any other application) use a lot of CPU during those 5 seconds?

The CPU usage stays 5 - 10% when opening terminal, nothing else gets frozen when terminal is opening too

**Comment by linuxlc** [comment]
I met same problem since WT 1.13 (1.12 is ok, 1.14 just like 1.13) on win10 (currently I'm using 10.0.19043.1826).
It happens not only when opening wt.exe, all the operations (Like "open a new tab", "duplicate tab", "split tab") to create a "OpenConsole.exe" subprocess can trigger the problem.
Cpu usage seems OK just like @Leohige 's observation.
Btw, I don't have Alienware Command Center installed.

**Comment by zadjii-msft** [comment]
If it's not Alienware Command Center, then maybe there's something else that's delaying the boot of OpenConsole.exe. Y'all have any sort of antivirus installed? Maybe there's an overzealous A/V that's scanning OpenConosle.exe every time it launches. 

1.13 was the first version that had the transparent window backdrop, which is what's causing the transparent window frame here. Before that, then the window would have appeared with probably a black BG, until the first tab loaded. Did the same delay happen on 1.12, but with a solid window instead of a transparent one/? (that's tracked over in #11561)

**Comment by linuxlc** [comment]
> If it's not Alienware Command Center, then maybe there's something else that's delaying the boot of OpenConsole.exe. Y'all have any sort of antivirus installed? Maybe there's an overzealous A/V that's scanning OpenConosle.exe every time it launches.
> 
> 1.13 was the first version that had the transparent window backdrop, which is what's causing the transparent window frame here. Before that, then the window would have appeared with probably a black BG, until the first tab loaded. Did the same delay happen on 1.12, but with a solid window instead of a transparent one/? (that's tracked over in #11561)

@zadjii-msft Thanks for the help. Problem solved, it's antivirus delaying wt.exe/windowsterminal.exe/openconsole.exe.
Transparent window frame happens very fast so it's ok with me.

**Comment by Leohige** [comment]
> If it's not Alienware Command Center, then maybe there's something else that's delaying the boot of OpenConsole.exe. Y'all have any sort of antivirus installed? Maybe there's an overzealous A/V that's scanning OpenConosle.exe every time it launches.
> 
> 1.13 was the first version that had the transparent window backdrop, which is what's causing the transparent window frame here. Before that, then the window would have appeared with probably a black BG, until the first tab loaded. Did the same delay happen on 1.12, but with a solid window instead of a transparent one/? (that's tracked over in #11561)

I'm not using antivirus, only windows defender by default. But i'm using transparent background

**Comment by zadjii-msft** [comment]
Yea, I'm gonna reckon that this is just /dup #11561. Before that release, the Terminal opened with a solid BG, which at least looked sensible. Now it looks a little more insane. Thanks!
