### ISSUE TITLE
Solarized Light scheme is not correct.

### ISSUE THREAD

**Issue by kgfly** [microsoft/terminal#13383]
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19044.1766

### Steps to reproduce

In VS22 dev profile, add

                "colorScheme": "Solarized Light",

### Expected Behavior

For warning string, the font color does not have any special color.

![image](https://user-images.githubusercontent.com/12282281/175831412-f498253f-43a8-41ac-a4c6-f08eeeabcfed.png)

### Actual Behavior

waring string should have a different color than normal font color. etc, in above, blue circle should different color than red circle

**Comment by zadjii-msft** [comment]
### [DAYS SINCE I'VE REGRETTED SHIPPING SOLARIZED: ~~301~~ 0](https://github.com/microsoft/terminal/issues/11171#issuecomment-914624178)

I'm suspecting that this tool is outputting text in "bright yellow", which in the default Solarized scheme is basically just gray. 

![image](https://user-images.githubusercontent.com/18356694/177303775-fb8f5beb-0746-4e94-b13f-632dbb483816.png)

Alas, by design, solarized doesn't have both a bright and dark yellow - [it's only got one yellow](https://ethanschoonover.com/solarized/). We're following the Solarized spec here, but feel free to modify it by hand to have both `yellow` and `brightYellow` be the same value.
