### ISSUE TITLE
Acrylic open it from the Ubuntu WLS shortcut

### ISSUE THREAD

**Issue by maisondasilva** [microsoft/terminal#13452]
### Windows Terminal version

1.13.11432.0

### Windows build number

Windows 11 22622.290

### Steps to reproduce

I would like to know why when I open a shortcut from my terminal tab, the background is acrylic and when I open it from the Ubuntu WLS icon, only the tabs are in acrylic and the background is not?

![image](https://user-images.githubusercontent.com/11423362/177804598-286e20a9-6ce4-44a3-b06f-7f8db9de28cc.png)

![image](https://user-images.githubusercontent.com/11423362/177804696-749ded95-84a4-4d24-a612-ebe53ecdcefe.png)

### Actual Behavior

Open Ubuntu WLS Acrilic

**Comment by zadjii-msft** [comment]
I'd bet this is due to "profile matching" not exactly working for WSL shortcuts directly. I bet in the second case, the target is something like `ubuntu.exe`. We try our best to match the commandline of the started console application to one of your profiles. However, `ubuntu.exe` doesn't really get matched to the "Ubuntu" profile. It's generally pretty **H**ard to try and figure out if an `exe` is the executable for a specific distro. 

Ultimately, this looks like #12755, or /dup #12582 to me.

**Comment by maisondasilva** [comment]
@zadjii-msft Thanks for the answer.
