### ISSUE TITLE
Settings Not Closable in Quake Mode

### ISSUE THREAD

**Issue by say25** [microsoft/terminal#13518]
### Windows Terminal version

1.15.1862.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Open Quake Mode
2. Open settings (`CTRL + ,`)
3. Try to close settings

### Expected Behavior

Ability to close settings

### Actual Behavior

Quake mode is basically unusable now

**Comment by DHowett** [comment]
Ah, good call. Thanks for the report. For a quick fix, you should be able to close it like any other tab with Ctrl+Shift+W or switch away from it with Ctrl+Tab.

**Comment by zadjii-msft** [comment]
Marking this up for discussion because I don't know what the good fix for this is. 

* Maybe something like #7210, where we opt quake mode into focus-lite mode? (Or merge that with #11130 for "show multiple tabs even in focus/fullscreen") 
* Alternatively, #5677, to show the tabs when you hover the top of the window?

**Comment by carlos-zamora** [comment]
(Sync meeting notes)
Proposing these as options (not edicts):
- ~if there's multiple tabs, show tab bar~ focus-lite mode
- if there's a settings tab, show tab bar

Short-term:
> #7210

Long-term:
> #5677

**Comment by zadjii-msft** [comment]
Great, so sounds like we can close this one as a combo dupe?

**Comment by carlos-zamora** [comment]
> Great, so sounds like we can close this one as a combo dupe?

Oh yeah, good point.
