### ISSUE TITLE
Duplicate active half when duplicating split pane

### ISSUE THREAD

**Issue by vertigo220** [microsoft/terminal#13579]
# Description of the new feature/enhancement

When a pane is split then duplicated, the right half is always the one duplicated. It should duplicate whichever half has focus when right-clicking the tab.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Hmm. This is with the right-click context menu on the tab itself, yea? 
![image](https://user-images.githubusercontent.com/18356694/180624997-27577c7d-34c6-4a33-85a2-326087d0ca72.png)

Seems like whenever the inactive tab is split, it's like we make a new _default_ profile pane, rather than duplicating the active pane. Curious. Thanks for the bug report! It should probably do the same thing when the tab is inactive, as it does when the tab is active.

**Comment by vertigo220** [comment]
Yes, but I'm actually referring to the "Duplicate Tab" option. Open a tab, split it, change the directory on one half, then duplicate it, and the new tab created by the duplication has the path of one or the other of the split tab's panes, obviously. The problem is that it's very insistent on using whichever pane it feels like for the path in the new, duplicated tab. When I first tested it, it was always the right pane. Testing again just now, it was the left pane, then somehow I got it to switch to using the path from the right pane and I can't get it to switch back. It _should_ use the path from whichever pane is active when the tab is duplicated.

The same problem applies to splitting an already split tab. The new pane has the same behavior as the new tab created when duplicating, and should have the path of the active pane when the tab is further split.

**Comment by vertigo220** [comment]
To add to this, I've found more unexpected behavior I think may be related. I have the starting directory for a new tab set to use the parent process directory, which I apparently wrongfully assumed meant the parent tab, but AFAICT it uses the first tab's CWD. This appears to be what issue #3158 deals with, and if that's correct this isn't a bug, but definitely, as mentioned, unexpected. However, what definitely _does_ appear to be a bug is that even duplicating a tab results in the new tab having the CWD of the first tab, and I suspect that's the source of the previously mentioned problems.

**Comment by 4wk-** [comment]
Hello. I was about to create my own issue with a somewhate-related subject: **shouldn't the "Duplicate tab" duplicate also the split pane layout?**
From my understanding, when I right click on a tab that is splitted in 4 ways, I'm expecting the new created tab to be the same: being split in 4.
Am I the only one? Am I missing something?

**Comment by zadjii-msft** [comment]
@4wk- That we're more specifically tracking in a combo of #4674 and #9957.

**Comment by zadjii-msft** [comment]
To add, I think this was fixed at some point in the past. I at least can't repro it on the 1.18 selfhost build build I'm on currently. I'd suspect this was at least fixed in 1.17, probably sooner. I can't really recall which PR fixed this.

Of course, duplicating the CWD of a pane that assumes that you've got [shell integration enabled](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory), but this all looks working to me.

I tried both

1. Open a non-default profile in a second tab
2. Open a new pane in that tab with another non-default profile
3. focus the first tab
4. Right-click inactive tab...split tab -> Always splits the focused pane, and creates a copy of the focused pane


and also

1. Open a tab, 
2. split it, 
3. change the directory on one half, 
4. then duplicate it -> new tab is created with the profile (and CWD if shell integration is enabled) of the active pane.

**Comment by 4wk-** [comment]
@zadjii-msft Thanks for your reply. If I understand correctly, I need [shell integration enabled](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory) for keeping my split panes when using the "Duplicate tab" button? 
I though shell integration was for CWD (current working directory), and I do not wish to have my duplicate tab on my current working directory.
I am on `Version: 1.16.10261.0` so maybe I should just wait :)

**Comment by CBR-EPT** [comment]
@zadjii-msft After more reading, I can confirm that what I'm asking for is #4674: when using the "Duplicate tab" feature, panes should be kept the same (so if a tab is split in 3 panes, "Duplicate tab" should create a new tab with 3 panes in it).
And if I understand correctly, #9957 is needed before #4674 can be worked on. Thanks!
