### ISSUE TITLE
Updates via the Microsoft Store break Visual Studio 2022 due to font sharing

### ISSUE THREAD

**Issue by IanKemp** [microsoft/terminal#13611]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.0

### Other Software

Visual Studio 2022 17.2.6

### Steps to reproduce

Whenever Windows Terminal updates via the MS Store it modifies the installed Cascadia fonts on the machine. As Visual Studio 2022 also uses these fonts, this breaks VS (all code windows render as white with no text) and VS can only be fixed by restarting the machine. This is an extremely poor developer/productivity experience.

I am not filing this as a VS bug because it is Terminal that is pulling the rug out from under VS and causing the latter to fall over. VS may need to be fixed to be more tolerant, but that is the Terminal team's conversation to have with the VS team, not mine.

Possibly related to/dupe of #10482, which was closed because... the team doesn't care about developer experience? I dunno.

### Expected Behavior

VS2022 works.

### Actual Behavior

VS2022 does not work.

**Comment by DHowett** [comment]
> closed because... the team doesn't care about developer experience?

We've pursued this issue to the ends of the earth--seriously, the people who own packaged fonts are tired of hearing from us--but as it stands today we're just _in a bind_.

Terminal ships with Windows 11, and the inclusion of Cascadia in the package has made Cascadia a de-facto system font. If we remove the font from the package, we're risking breaking any application that has taken a dependency on it as a system font (VS, Teams comes to mind, Stack Overflow and a few other sites have also chosen to depend on it, but that's neither here nor there as they're a website.) If we _don't_ remove the font from the package, older versions of the OS have an issue with the font being locked during upgrade.

If we remove it from the package and add it as a dependency package (there's no such thing as an optional dependency, for what it's worth), we complicate distribution _and_ OS ingestion. We've gotten enough bug reports from people who cannot find the VCLibs package that we ship as part of our own releases to know that installing dependency packages is nearly a no-go for some folks. The downstream effect is that everybody gets a deployment error because they haven't installed the font first.

I guess we could just remove it, get it into an OS update (Windows 12?), and take the heat.

Of note is that it's fixed in Windows 11, and reports like yours help us work up the organizational will to get that fix backported to Windows 10.
