### ISSUE TITLE
Export Text when in Admin mode filename suggestion has invalid character ":"

### ISSUE THREAD

**Issue by restartedwill** [microsoft/terminal#13664]
### Windows Terminal version

1.14.1963.0

### Windows build number

22000.795

### Steps to reproduce

Open Windows Terminal (Admin).
Have text in console window.
Right click on tab and choose "Export Text".

### Expected Behavior

Cleanse out the colon character and other invalid characters for filenames based on the tab name.

### Actual Behavior

Observe filename provided has "Admin: " as the leading text, and on Windows, a colon is not valid in filenames.

**Comment by zadjii-msft** [comment]
I mean, I guess why not? We'd probably accept this as a contribution

**Comment by EliaSchiavon** [comment]
If @restartedwill is not willing to work on this issue, I would try to tackle this, but I'll need guidance to identify what files need to be examined and edited

**Comment by restartedwill** [comment]
Yes, I am not able to tackle this change; just raising awareness in the hopes another developer could pick it up.

**Comment by zadjii-msft** [comment]
That'd be great! I'd start right here:

https://github.com/microsoft/terminal/blob/74cdffe9215740a2c783c2d1f393fd303286b2b5/src/cascadia/TerminalApp/TabManagement.cpp#L435-L436


That's the line where we set the proposed text. I don't think we have any existing helpers for trimming a string so that it's a viable filename - I'll leave that as an exercise for the reader 😉

**Comment by EliaSchiavon** [comment]
Ahah thank you! Started working on it, I will raise a PR in the next few days
