### ISSUE TITLE
That one NanoServer regression

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13671]
Just filing this here, because it should be tracked. Go look at MSFT:40435912

**Comment by SpyassL** [comment]
eg Надіслано з програми Пошта для Windows Від: Mike GrieseНадіслано: 4 серпня 2022 р. о 18:00Кому: microsoft/terminalКопія: SubscribedТема: [microsoft/terminal] The Nanoserver regression (Issue #13671) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by DHowett** [comment]
Fixed!

**Comment by zadjii-msft** [comment]
Did we need to git2git that back out?

**Comment by DHowett** [comment]
It'll come back with the next merge set (I'd like to bring main out to inbox before merging inbox back into main)
