### ISSUE TITLE
Switch it to background and foreground fast multiple will crash.

### ISSUE THREAD

**Issue by Cricle** [microsoft/terminal#13699]
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19043.0

### Steps to reproduce

Switch it to background and foreground fast multiple.

### Expected Behavior

Click terminal in the taskbar, Window will block and can't switch to foreground

![image](https://user-images.githubusercontent.com/26201412/183276921-de6bb821-9476-4e4a-91b9-b66d3db972a4.png)
here is evtx file
[e.zip](https://github.com/microsoft/terminal/files/9276236/e.zip)
here is my terminal setting
[settings.zip](https://github.com/microsoft/terminal/files/9276238/settings.zip)

### Actual Behavior

Click terminal in the taskbar, switch to foreground

**Comment by Cricle** [comment]
Already send feedback

**Comment by zadjii-msft** [comment]
Great, can you click 
![image](https://user-images.githubusercontent.com/18356694/183637905-17bf2d19-6ce8-4872-99d1-1279093f2d7f.png)

and paste the link here/? It's pretty impossible to look the feedback up in the backend without the direct link to it.

**Comment by Cricle** [comment]
I send same feedback again. @zadjii-msft  
https://aka.ms/AAhnrko

**Comment by zadjii-msft** [comment]
Hmm. For whatever reason, Feedback hub didn't capture this as a crash. It's got conhost dumps in there, but there's no `windowsterminal.exe` crash. I suppose since this is a _hang_, it's not technically a crash.

The repro steps make this sound like #13589. I'm tempted to just wait to ship that as a hotfix, and see if that resolves the issue for you. 

Unfortunately, I don't _think_ that issue could result in a hang as you're reporting, but who knows. User32 is a dark and mysterious world. Maybe the OS knows that it sent a "restore" to the Terminal, but the WT HWND didn't actually start processing any window messages (the pty HWND did).\</conjecture>

**Comment by Cricle** [comment]
I try in two different physical computer, but has same result. 
I thought max cpu and RAM use will get this problem, I try in almost 0% cpu and has free 6G RAM time, or preview version but the result is still the same.

**Comment by zadjii-msft** [comment]
I think this might have been fixed in Preview https://github.com/microsoft/terminal/releases/tag/v1.15.2282.0 - can you try that build and see if this is still happening/?

**Comment by Cricle** [comment]
> I think this might have been fixed in Preview https://github.com/microsoft/terminal/releases/tag/v1.15.2282.0 - can you try that build and see if this is still happening/?

It won't happen again, thinks !
