### ISSUE TITLE
Windows cannot scroll up or down in Screen mode

### ISSUE THREAD

**Issue by hijkzzz** [microsoft/terminal#13703]
### Windows Terminal version

 1.14.1963.0

### Windows build number

Win10 or Win11 x64

### Steps to reproduce

Connect to any ubuntu 20.04 server or WSL2
screen -S test
Enter a lot of commands
You'll find that you can't scroll through commands that are off-screen

### Expected Behavior

I can scroll up and down to view the history commands

### Actual Behavior

I can't scroll up and down to view the history commands

**Comment by j4james** [comment]
I'm afraid this is just the way `screen` works. See #13670.

**Comment by zadjii-msft** [comment]
Yep.

/dup #13670

**Comment by hijkzzz** [comment]
However, both iTerm2 and VSCode support this feature well~

**Comment by j4james** [comment]
@hijkzzz Screen manages the scrollback history itself, since you can have multiple sessions, each with their own history, so it doesn't make much sense to use the terminal's scrollback. But if that's really what you want, you can configure that in your .screenrc as described here:

https://stackoverflow.com/a/1125947

**Comment by hijkzzz** [comment]
> @hijkzzz Screen manages the scrollback history itself, since you can have multiple sessions, each with their own history, so it doesn't make much sense to use the terminal's scrollback. But if that's really what you want, you can configure that in your .screenrc as described here:
> 
> https://stackoverflow.com/a/1125947

Hi, this solution is not easy to use. How can I roll back WS Terminal to a version that supports screen rolling?

**Comment by kushwavez** [comment]
ust a note on this:
This issue was affecting my work as I mostly work with screens. After I don't know what release update it suddenly didn't work, I started using Hyper as an alternative, but because it crashed 3 times now in critical times I decided to try and "fix" this issue with the Windows Terminal.

After I rolled back to v1.13.11432.0 the issue was not there, so something is changed around the new releases.
I'll stay on this ver until a fix is developed for this.

**Comment by DHowett** [comment]
Unfortunately, a fix will not be developed for this. There's a better description of what's up in https://github.com/microsoft/terminal/issues/13670, as well as James' comments here.

We are not intending on breaking alternate screen buffer support, as it is a critical underpinning of any application that wants control over the entire screen... such as `screen`.

**Comment by urza** [comment]
https://stackoverflow.com/a/1125947

This has worked for me. I did exactly what the SO answers suggestst and now I can scroll in screen sessions from Windows Trerminal.
