### ISSUE TITLE
Windows Terminal no longer builds in Visual Studio 2019

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#13708]
The [prerequisites](https://github.com/microsoft/terminal#prerequisites) in the developer guidance documentation suggest you only need VS 2019 and v142 of platform tools to build Windows Terminal, but it seems that's no longer the case.

Building the last revision (ffe9a0f09bc7b3cb96908d265c93bcd1a4e75fa2) in VS 2019 (version 16.11.17) I get the following errors:

    The build tools for v143 (Platform Toolset = 'v143') cannot be found.
    To build using the v143 build tools, please install v143 build tools.

    The "GetFrameworkSdkPackages" task was not found.

I think the `GetFrameworkSdkPackages` error started with commit b0396f174127a9d23590a5cd0ae38872791a13f5 (PR #13535), and the v143 requirement came from 4e5a0c137b045d9f1f34114d12bc3b0ed0a03800 (PR #13621).

I'm not in a position to upgrade at the moment, but I'm assuming a switch to VS 2022 would fix those errors. I know at least that v143 of the build tools comes with VS 2022.

If these new requirements are intentional, we need to update the developer guidance.

**Comment by lhecker** [comment]
Oh no. 😥
Unfortunately I did this intentionally. bd403dc8e71ff0e377f2c887c4c7f2032e3718d9 changed the requirement from VS 2019 to VS 2022, because I intended to use C++20 in this project, which requires VS 2022 for full support as far as I know (= v143 build tools). I forgot to update the documentation. 😥

v142 has (incomplete) support for `/std:c++20` as well, so I can revert those commits to somewhat restore support for VS 2019 for now, until everyone gets a chance to switch to VS 2022. But I'm not sure how long this will hold as we potentially integrate more and more C++20 features over time...

**Comment by j4james** [comment]
I'm totally OK with the switch to VS2022 if it's necessary for moving forward with C++20, so don't feel you have to revert anything on my account. I just can't upgrade right now, but I'll get to it soon enough.

The main thing is getting the docs updated, because it's not immediately obvious from those errors message that an upgrade is required, and the developer guidance made me think I was still OK on VS2019.

**Comment by lhecker** [comment]
After talking with @DHowett we've decided to not do any reverts and restore support for VS 2019.
