### ISSUE TITLE
CMD, [process exited with code 3762504530 (0xe0434352)]

### ISSUE THREAD

**Issue by kevincrans** [microsoft/terminal#13736]
### Windows Terminal version

1.14.196.3.0

### Windows build number

1?.?.22518.1000

### Other Software

At least any windowed app with a console in any relevant prompt except the powershell hotfix for this, when restarting for example after the app updated. Look at steps to reproduce for similar software having this issue.

### Steps to reproduce

The program I'm using is unofficial, but Similar issues are #4981 and #6287.

### Expected Behavior

I expected to application to continue and restart. I also expected terminal to be fixed and not powershell.

### Actual Behavior

It showed me my system specifications like supposed, but gave me the following error:
`[process exited with code 3762504530 (0xe0434352)]`

**Comment by zadjii-msft** [comment]
I mean, it just kinda sounds like whatever application you're running is returning a non-zero exit code. Refer to:

[Why am I seeing `[process exited with code ...]`?](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#why-am-i-seeing-process-exited-with-code-)

I'd file an issue upstream with whatever software you're using. If the application should be exiting cleanly, it should be returning `0`. The Terminal displays that message by default so that when an application does return an error, you can view its output.

**Comment by Mrgaton** [comment]
i got the same problem tryng to run my c# app 😢

[proceso terminado con el código 3762504530 (0xe0434352)]

**Comment by Mrgaton** [comment]
aparently is when i write something in the console.readline()

**Comment by DHowett** [comment]
This error code means that your C# application is crashing with a "COM+" error. Terminal has displayed it so that you know what is going on!

**Comment by Mrgaton** [comment]
But only happens when i runned on windows terminal

**Comment by kevincrans** [comment]
> This error code means that your C# application is crashing with a "COM+" error. Terminal has displayed it so that you know what is going on!

For my application as well and probably also for the powershell app, so I'm re-opening it.

**Comment by kevincrans** [comment]
@zadjii-msft < Someone already did, but it's lazy to say all the app makers fix it individually, while it's clearly a terminal issue, like @Mrgaton stated.
Did u even look into the powershell issue?

**Comment by zadjii-msft** [comment]
Of course it only happens on the Windows Terminal, conhost (the vintage console) never had any code to handle anything like this. If an app crashed running in conhost, it'd just disappear itself, which doesn't provide any useful information. Providing an error code is certainly useful - best practice has _always_ been to return 0 if your process exits cleanly, and I'd want to know if my app wasn't for whatever reason. 

You can always tell the terminal to just ignore this by settings `closeOnExit: always`. 

I haven't looked more into the root of this, because there were no minimal repro steps in the OP 😉

**Comment by Mrgaton** [comment]
I only know that's the program crashes on the console.readlline() I tested out

**Comment by lamplt** [comment]
I encountered it while obfuscating the dlls via a post build script. It looks like .exe was invoked before the obfuscation was completed. But the .exe is working well after that. So I just ignored it.

**Comment by GitHub-source-42** [comment]
Same Error Code when Lauching Powershell through VS Code or directly from "C:\Program Files\PowerShell\7\pwsh.exe"

PowerShell 7.4.5

An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.Management.Automation.CmdletInvocationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'. The system cannot find the file specified.
File name: 'WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'
   at WinRT.ProjectionInitializer.InitalizeProjection()
   at .cctor()
   --- End of inner exception stack trace ---
   at Microsoft.WinGet.Client.Commands.FindPackageCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.WinGet.CommandNotFound.WinGetCommandNotFoundFeedbackPredictor.WarmUp()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by DHowett** [comment]
You are commenting with a powershell issue on a thread that clearly seems to be about CMD.
Please file your bug on [the powershell repository](https://github.com/powershell/powershell).
