### ISSUE TITLE
Try to flow together JSON serialization for keybindings

### ISSUE THREAD

**Issue by Jaykul** [microsoft/terminal#1378]
# I would love it if we could see all the keybindings ...

Wouldn't it be better if the default profiles.json could be formatted like ... 

```json
        "keybindings": [
            { "command": "closeTab",       "keys": [ "ctrl+w" ] },
            { "command": "newTab",         "keys": [ "ctrl+t" ] },
            { "command": "newTabProfile0", "keys": [ "ctrl+shift+1" ] },
            { "command": "newTabProfile1", "keys": [ "ctrl+shift+2" ] },
            { "command": "newTabProfile2", "keys": [ "ctrl+shift+3" ] },
            { "command": "newTabProfile3", "keys": [ "ctrl+shift+4" ] },
            { "command": "newTabProfile4", "keys": [ "ctrl+shift+5" ] },
            { "command": "newTabProfile5", "keys": [ "ctrl+shift+6" ] },
            { "command": "newTabProfile6", "keys": [ "ctrl+shift+7" ] },
            { "command": "newTabProfile7", "keys": [ "ctrl+shift+8" ] },
            { "command": "newTabProfile8", "keys": [ "ctrl+shift+9" ] },
            { "command": "nextTab",        "keys": [ "ctrl+tab" ] },
            { "command": "prevTab",        "keys": [ "ctrl+shift+tab" ] },
            { "command": "openSettings",   "keys": [ "ctrl+," ] },
            { "command": "scrollDown",     "keys": [ "ctrl+shift+down" ] },
            { "command": "scrollDownPage", "keys": [ "ctrl+shift+pgdn" ] },
            { "command": "scrollUp",       "keys": [ "ctrl+shift+up" ] },
            { "command": "scrollUpPage",   "keys": [ "ctrl+shift+pgup" ] },
            { "command": "switchToTab0",   "keys": [ "ctrl+1" ] },
            { "command": "switchToTab1",   "keys": [ "ctrl+2" ] },
            { "command": "switchToTab2",   "keys": [ "ctrl+3" ] },
            { "command": "switchToTab3",   "keys": [ "ctrl+4" ] },
            { "command": "switchToTab4",   "keys": [ "ctrl+5" ] },
            { "command": "switchToTab5",   "keys": [ "ctrl+6" ] },
            { "command": "switchToTab6",   "keys": [ "ctrl+7" ] },
            { "command": "switchToTab7",   "keys": [ "ctrl+8" ] },
            { "command": "switchToTab8",   "keys": [ "ctrl+9" ] }
        ],
```

And I just mean getting rid of the terribly redundant white space so that all the keys fit on screen at the same time ... not the fact that these key defaults are clearly superior (who's idea was it to use ALT for switching tabs, anyway?).

**Comment by fedfigca** [comment]
Yes, please.
If the configuration is going to be via text file, which I'm perfectly fine with, there should be some good information architecture in the layout and order of the items.
IMHO, alphabetic order is not the best way to sort the items here, because it hurts discoverability of all the features and related items, since a human is reading the file, fields like `name` or `guid` should come first, and then grouped by what the features modify, layout, colors, fonts, cursors, etc so that the user can find the group it's interested in and explore only those options instead of having to read through some 15 items and figure out what each one is for.

Thanks for the great work, I'm really happy to see it come to reality, it's going to make our developer lives even better.

**Comment by zadjii-msft** [comment]
@fedfigca Hopefully this won't be as much of a problem once #754 is complete. The "defaults" file will be in a sane, non-alphabetic order, similar to how they were before #1005. Then, the user settings will be in whatever order the user puts them in.
