### ISSUE TITLE
Experimental text engine renders terminal window larger compared to default setting

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#13812]
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.19044.0

### Steps to reproduce

Toggle "Enable experimental text rendering engine" 

### Expected Behavior

Terminal size to be consistent

### Actual Behavior

Top is with Atlas engine on, bottom with default setting. No other changes were altered:

![wt_experimental_compare](https://user-images.githubusercontent.com/3933920/185975569-03a39b30-bd33-44cd-b64a-e7768640703c.png)

**Comment by zadjii-msft** [comment]
@lhecker lmao someone noticed

**Comment by lhecker** [comment]
The previous renderer used `round()` to determine the size of a single cell in the terminal and then shrank/grew the font size to match that cell size. So you said you want 12pt, but you actually got 11.9945pt or something, which lead to the slightly blurry text in Windows Terminal (blurriness depends on the font family, font size and most importantly on the glyph).

My goal was to stop that font size adjustment and improve text clarity. To ensure glyphs aren't cut off with the possibly larger font size, I used `ceil()` to determine the cell size instead of `round()`. But I'm not saying that I'm 100% sure that `ceil()` is the correct choice there - I was just going by my intuition and I'm open to any and all change suggestions.

That said I don't consider this issue to be a bug, since I did do it intentionally.
