### ISSUE TITLE
Windows Terminal won't stay pinned to the Windows 11 task bar across restarts

### ISSUE THREAD

**Issue by SCWells72** [microsoft/terminal#13878]
### Windows Terminal version

1.14.2282.0

### Windows build number

10.0.22000.918

### Steps to reproduce

Every time Windows 11 restarts, the task bar loses its pinned Windows Terminal entry. This seems to be a relatively recent behavior as I'd had it stably pinned to the task bar for a very long time (since Terminal was in relatively early beta). It's not a huge thing as I just start terminal and pin it again each time it happens, but my guess is that you'd want to know. And I don't know if this is an issue with Terminal or Windows 11 itself, though I have another dozen or so pinned apps that aren't lost across restarts.

### Expected Behavior

Windows Terminal remains pinned across restarts.

### Actual Behavior

The pin for Windows Terminal is lost after a restart.

**Comment by zadjii-msft** [comment]
How did you install the Terminal/? FWIW I've never seen this on Windows 11, and I've got two different versions of the Terminal perpetually pinned to the taskbar. 

The one I do lose from time to time is the Dev build of the Terminal, and that's usually when I'm deploying a fresh version of the dev build. Does this happen on _every single_ restart of your machine? There's also the very real likelihood that the Store took this restart as an opportunity to update the Terminal package, and possibly lost the taskbar pin during the upgrade. That wouldn't surprise me. Especially since 1.14.2282 _just_ rolled out

**Comment by SCWells72** [comment]
@zadjii-msft in the early days I had it installed using the standalone installers, but once it was made available via the Microsoft Store, I uninstalled the standalone installer version and installed from the store. Now that's the only version installed on my machine:
![image](https://user-images.githubusercontent.com/7671043/187285870-9c6a3c8e-94b5-4e0f-9525-58d79ae085eb.png)
and:
![image](https://user-images.githubusercontent.com/7671043/187285994-6d414d6b-d18f-468a-9e8b-0646c525ef6e.png)
Based on what you said about the Store update, I'll keep an eye out for it disappearing again and, if it does, report back here. I guess for now feel free to close this if you'd like.

**Comment by zadjii-msft** [comment]
Yea, I'll close this out for now, but if this is seriously unpinning _every_ restart (we don't update _that_ often), then this is feedback that probably needs to be directed to the Taskbar team via the Feedback Hub, if I'm totally honest. 

Thanks for the follow up!
