### ISSUE TITLE
Clear-Host does not clear the entire Windows Terminal contents

### ISSUE THREAD

**Issue by theJasonHelmick** [microsoft/terminal#13940]
### Windows build number

10.0.22000.0

### Steps to reproduce

Please see https://github.com/PowerShell/PowerShell/issues/15432

After terminating Rick-roll, clear-host should clear the terminal, but does not.

### Expected Behavior

Clear-Host to clear the terminal

### Actual Behavior

Does not clear

**Comment by DHowett** [comment]
_Hmm._ @theJasonHelmick are you using PowerShell installed as a `dotnet global` tool?

**Comment by daxian-dbw** [comment]
@DHowett The root cause is that calling [SetConsoleWindowInfo](https://docs.microsoft.com/en-us/windows/console/setconsolewindowinfo) to change the window size doesn't work in Windows Terminal.

A simple repro can be found at https://github.com/PowerShell/PowerShell/issues/15432#issuecomment-846295116. It attempts to change the windows size by setting `$host.UI.RawUI.WindowSize` in PowerShell. The setter of that `WindowSize` property calls into the `SetConsoleWindowInfo` to change the window size, which works in console host, but not in Windows Terminal.

In Windows Terminal, after calling `SetConsoleWindowInfo`, it turns out the .NET `Console.BufferHeight`, `Console.BufferWidth`, `Console.WindowHeight`, and `WindowWidth` all reflect the specified value, but the Windows Terminal window doesn't change, and that causes the text on the exceeding part of the window to linger around and cannot be cleared. Here is a screenshot to demonstrate the problem:

![image](https://user-images.githubusercontent.com/127450/189005314-38c3aac0-6f28-4032-8e0d-0ce428b3709f.png)

**Comment by j4james** [comment]
> The root cause is that calling [SetConsoleWindowInfo](https://docs.microsoft.com/en-us/windows/console/setconsolewindowinfo) to change the window size doesn't work in Windows Terminal.

That's essentially issue #5094.

**Comment by zadjii-msft** [comment]
Oh yea, for sure. /dup #5094
