### ISSUE TITLE
Renderer encountered an unexpected error: -2147024809

### ISSUE THREAD

**Issue by noinkling** [microsoft/terminal#13985]
### Windows Terminal version

1.16.2523.0

### Windows build number

10.0.19044.1889

### Other Software

I'm on an Intel Core i5-2500K CPU, using its integrated HD 3000 GPU. Graphics driver version 9.17.10.4459

### Steps to reproduce

Open Windows Terminal

### Actual Behavior

A "Warning" dialog pops up saying "Renderer encountered an unexpected error: -2147024809".

If I click OK it just pops up again, ad infinitum.

I assume it's related to the Atlas renderer that is now enabled by default in the preview version of Terminal.

**Comment by zadjii** [comment]
@lhecker there's an internal bug for this too. I thought the internal person was on DX but I might have been mistaken

**Comment by lhecker** [comment]
-2147024809 is `E_INVALIDARG`. Could you run [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) and check if any failure messages are visible when launching Windows Terminal With AtlasEngine enabled?

**Comment by noinkling** [comment]
@lhecker I might be using it wrong but nothing is logged, except when I close the Terminal app via the task bar ("Suspending").

**Comment by lhecker** [comment]
I think I found the internal bug: MSFT-41000959, but that one is -2005270527 (`DXGI_ERROR_INVALID_CALL`).

The biggest problem is that the oldest, still functional Intel hardware that I personally have is an i7-6600U, which is clearly far newer than a i5-2500K. I can't really think of any reason why our engine would fail, as I ran it with the reference Direct3D driver all the way down to DirectX 9.1.

@noinkling If you'd like to help with this investigation, another thing you could try is to run `dxcpl` from the start menu. That application isn't entirely intuitive, but basically you do this:
![dxcpl](https://user-images.githubusercontent.com/2256941/190035983-b41e5daa-1a27-424b-8be2-083ae1afced8.png)

Afterwards you can modify the DirectX settings for Windows Terminal. For instance:
![dxcpl](https://user-images.githubusercontent.com/2256941/190036121-6cd2c491-c126-464e-b4d7-8f90d28492cd.png)

Just hit "Apply" afterwards and restart Windows Terminal. Once you're done with testing I strongly suggest to do this:
![dxcpl](https://user-images.githubusercontent.com/2256941/190036276-ea44ce22-37cc-4969-b60c-369fdf454aeb.png)

If that doesn't yield any insights, another option would be for you to send us a ETL trace as described here: https://github.com/microsoft/terminal/wiki/Capturing-a-Debug-ETL-Trace
However that requires you to install Windows Performance Recorder (WPR).

It's fine if you don't have the time to investigate this further. But unfortunately it might take a little bit to procure your hardware first.

**Comment by noinkling** [comment]
@lhecker With just the debug setting on, DebugView now shows this message:

> [8796] D3D11 ERROR: ID3D11Device::CreatePixelShader: Shader uses features (Raw or Structured Buffers) not supported by this device. Use the CheckFeatureSupport() API with D3D11_FEATURE_D3D10_X_HARDWARE_OPTIONS to discover support for these features if using D3D_FEATURE_LEVEL_10_*. [ STATE_CREATION ERROR #192: CREATEPIXELSHADER_INVALIDSHADERBYTECODE]

Terminal does work when selecting 9_3 or below for the feature level limit. The error happens again when selecting 10_0 or above.

I can confirm that it's supposed to support the DirectX 10.1 feature level, dxdiag and GPU-Z say the same thing.

**Comment by Brawl345** [comment]
> In the meantime I'd suggest to disable AtlasEngine in the settings tab (there's a switch under "Rendering").

FYI for anyone who can't access the settings due to the error making the Terminal unusable: Edit the settings JSON file manually (see https://docs.microsoft.com/en-us/windows/terminal/install#settings-json-file it's under `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json` for the Windows Store release & Terminal Preview) and add:

```json
"defaults": {
  "useAtlasEngine": false
},
```

into `profiles` or `"useAtlasEngine": false` to any profile.

**Comment by igorskyflyer** [comment]
> ```json
> "useAtlasEngine": false
> ```

Thank you, this workaround fixed the issue. 😃

**Comment by SeeJayEmm** [comment]
What version should this fix appear in? Because I just started encountering this problem today.
Version: 1.16.2530.0

**Comment by lhecker** [comment]
We haven't committed to any specific date yet, but it'll be sometime soon. There's a few more issues around the new text renderer, which we'd like to address as well, but haven't merged yet. This issue will be updated by a bot once the fix has been released.

**Comment by asteinarson** [comment]
My windows terminal got infinitely locked up in the _Renderer encountered an unexpected error_.  So I found this page and applied the suggested fix (in _settings.json_). Then, however, as I type commands, the terminal app starts to blank out the text entry lines, once they are long enough (so one cannot see the command and its response). 

I attach a screenshot where the command _sudo service apache2 status_ has been blanked out by the preview terminal engine. 

To me, as a SW developer and engineer, it appears like shaky behavior to go after effects of "shading" and "fading" ... at the expense of breaking the functionality (on lots of combinations of hardware) of a critical app. 

My rescue was to go back to the non preview version of the terminal. 
 
![WindowsTerminalPreview_NewBugAfterSuggestedFix](https://user-images.githubusercontent.com/8819538/190900147-5ed2f3e1-3414-4cfe-bf4e-41ec54431596.PNG)

**Comment by lhecker** [comment]
> To me, as a SW developer and engineer, it appears like shaky behavior to go after effects of "shading" and "fading" ... at the expense of breaking the functionality (on lots of combinations of hardware) of a critical app.
> 
> My rescue was to go back to the non preview version of the terminal.

If you did set `"useAtlasEngine": false` then you re-enabled the same text renderer that has been virtually untouched since at least half a year and is also used in the non-Preview version of Windows Terminal. As such the bug you describe can't be related to the new text renderer and instead sounds like something else entirely. I've created an issue for you: #14027

BTW I'm not sure what you mean with "shading and fading", but if you saw me write "shading" in relation to anything "AtlasEngine", that's just a term to _basically_ describe "colorize text". The new text renderer solves some fundamental performance issues we've had.

**Comment by asteinarson** [comment]
I got these two issues after a Windows upgrade had run. I guess it also updated the Terminal Preview app (or the Preview app ran just fine before the Windows update). 

For shading / fading - sorry if quickly jumping to conclusions. It is the preview version and there will be issues. I guess I'm fed up with going for "bells and whistles" in various contexts - often then dragging down performance / footprint and reliability.

**Comment by DHowett** [comment]
> I guess I'm fed up with going for "bells and whistles" in various contexts - often then dragging down performance / footprint and reliability.

You and me both! Yeah, we've been staying pretty technical when we talk about the "atlas" text engine. At the end of the day, it uses a GPU shader to draw text to the screen as fast as we can produce it. It _also_ happens to support the flashy bells-and-whistles kinds of shaders that you may be thinking of, but even when doing that it's still more performant than the older text rendering engine.

That is, _when it works._

I'd love if you could file an issue w/ a video or something showing what you see when the text is flickering. That's definitely something it should never do, and something we'll want to address regardless of which engine is putting text on the screen!

**Comment by lhecker** [comment]
Since no one on the team can reproduce this issue, would anyone be willing to test our upcoming build before we submit it to the Microsoft Store? It's properly signed and if it works it would end up being the build we publish.

Just re-enable AtlasEngine again and open a new tab, or restart the app. But be careful not do to the update while Terminal Preview is already running, as this will potentially force-quit the application during the update.

* Windows 10: [Microsoft.WindowsTerminalPreview_Win10_1.16.2641.0_8wekyb3d8bbwe.msixbundle](https://terminalnuget.blob.core.windows.net/packages/Microsoft.WindowsTerminalPreview_Win10_1.16.2641.0_8wekyb3d8bbwe.msixbundle)
* Windows 11: [Microsoft.WindowsTerminalPreview_Win11_1.16.2642.0_8wekyb3d8bbwe.msixbundle](https://terminalnuget.blob.core.windows.net/packages/Microsoft.WindowsTerminalPreview_Win11_1.16.2642.0_8wekyb3d8bbwe.msixbundle)

**Comment by noinkling** [comment]
@lhecker I can confirm that it fixes the error for me.
