### ISSUE TITLE
cursor stops blinking and leaves artifacts after sshing into a linux hosts and starting vim.

### ISSUE THREAD

**Issue by darthpale** [microsoft/terminal#13996]
### Windows Terminal version

1.16.2524.0

### Windows build number

11.0.22000978

### Other Software

vim 9.0.246 from via 
OpenSSH-8.7p1
to Fedora 35 ARM

### Steps to reproduce

launch terminal
ssh remote host
vim some file.
[notice cursor stops blinking]
navigate with cursor 
[notice artifacts]

### Expected Behavior

cursor continues to blink, no artifacts

### Actual Behavior

cursor stops blinking and when navigating with the "arrow" keys, the cursor leaves artifacts

Before invoking vim cursor blinks,  during vim and after exiting cursor does not blink after exiting the ssh session the cursor still doesn't blink.

![Terminal-artifacts-20220914](https://user-images.githubusercontent.com/48268993/190196375-63694aac-2602-403e-97ca-006342a5d9a2.png)

**Comment by lhecker** [comment]
I'm not exactly sure which issue is tracking that vim doesn't turn the blinking cursor on again on exit, but it is mentioned here for instance: https://github.com/microsoft/terminal/issues/10754#issuecomment-885185039

The artifacts when moving around is very worrying, but unfortunately I can't reproduce this when SSHing into Arch Linux and running a vanilla vim instance. (Yours seems to be customized?)
Since I can't reproduce the issue I unfortunately can't fix it. 😓

Although, we do have a couple issues about tmux causing display corruptions (e.g. #6987). We aren't 100% sure what causes those either, but I feel like my ongoing efforts to simplify our rendering stack might fix those issues as a drive-by.

**Comment by lhecker** [comment]
@darthpale Do those artifacts still occur for you?

**Comment by carlescufi** [comment]
I have the same problem but it happens even without sshing into a Linux host, it also happens in my case with Cygwin running locally: I load `vim`, the cursor stops blinking (no artifacts).
