### ISSUE TITLE
Special glyphs slightly malformed / text slightly blurry with Atlas Engine and Meslo Nerd font

### ISSUE THREAD

**Issue by itsTyrion** [microsoft/terminal#14057]
### Windows Terminal version

1.16.2523.0

### Windows build number

10.0.19044.0

### Other Software

PARTIALLY affects MacType (better font AA) but I'm mainly reporting the malformed glyphs

### Steps to reproduce

Use WT preview with Atlas Engine and Meslo Nerd Font
Just to make sure, the exact font files [MesloLGS-NF.zip](https://github.com/microsoft/terminal/files/9621188/MesloLGS-NF.zip)

### Actual Behavior

This is without Atlas Engine (MacType enabled)
![2022-09-22_02-14](https://user-images.githubusercontent.com/17730120/191632157-858cf40a-c451-4195-843f-3f53b44f4f6c.png)
This is with Atlas Engine (MacType enabled). Less clear, shapes malformed.
![image](https://user-images.githubusercontent.com/17730120/191632355-e395599a-9810-4b84-a92f-ecbaef127c3a.png)
With Atlas (MacType disabled, so only clarity/sharpness is slightly affected)
![image](https://user-images.githubusercontent.com/17730120/191632479-d23886af-c484-4f8f-bf2d-617d9ce489a9.png)

Without Atlas (MacType disabled, very visible in the Windows glyph. Just for reference)
![image](https://user-images.githubusercontent.com/17730120/191632431-4effcd83-b574-4714-88fb-490c6a62732e.png)

**Comment by lhecker** [comment]
FYI If you're curious about some of these changes, there's a lengthy discussion over here with the latest update being: https://github.com/microsoft/terminal/issues/13936#issuecomment-1254302780
In short, the blurriness appears to be correct actually.

In the soon to be released next 1.16 update you'll be able to specify precise fractional font sizes which will allow you to restore the previous look of glyphs. Text clarity can be improved if you enable ClearType in your settings. Finally, the reason those rounded corners look worse is because I'm incorrectly handling glyph sizes in AtlasEngine and assume that they're 1 cell wide, even though they're actually 2 cells wide. This is an issue that's specific to Nerd Fonts and is something I'm currently working on as fast as I can.

**Comment by itsTyrion** [comment]
Good to know, thanks for the fast reply. I'll keep it disabled for the time being and use MacType. Especially the NF symbols (OS logo, folder, git..) look a lot better for the time being

**Comment by itsTyrion** [comment]
What I don't understand is why exactly *some* text gets blurry with Atlas AND MacType

**Comment by lhecker** [comment]
FYI I'm going to continue tracking nerd font glyphs in #14022, which was the first issue to report it.
