### ISSUE TITLE
Atlas Engine: Way to get back spaces between lines?

### ISSUE THREAD

**Issue by leimath** [microsoft/terminal#14068]
### Windows Terminal version

1.16.220921001-preview

### Windows build number

10.0.19044.0

### Other Software

[helix-editor](https://github.com/helix-editor/helix)

### Steps to reproduce

Font: [Overpass Mono](https://github.com/RedHatOfficial/Overpass)

### Expected Behavior

![without atlas terminal](https://user-images.githubusercontent.com/96306150/192085377-e0366cda-2557-4b1c-98f0-78d74eeb5863.jpg)

![2022-09-24-000125](https://user-images.githubusercontent.com/96306150/192086078-ebbdbbbc-a21d-464b-8ec8-8d822ec272c5.jpg)

This is without Atlas Engine in the current terminal preview. In the helix editor there are some space around the 1.

### Actual Behavior

![with atlas engine](https://user-images.githubusercontent.com/96306150/192085388-b985e6e0-ea85-4e84-9680-ae2edc2d138b.jpg)

![2022-09-24-000126](https://user-images.githubusercontent.com/96306150/192086098-3a2b9768-7e93-4289-ab2e-98de0e50f644.jpg)

This is with Atlas Engine, latest terminal preview.

A small query -
Is there a way to get back the space above the 1? I understand that it is intentional that line-gaps are intentionally ignored as per the release notes. Or is there any advantage over not having the space around the one?

**Comment by leimath** [comment]
Please close the issue if I misunderstood this feature.

**Comment by lhecker** [comment]
It's somewhat ridiculous how annoying it can be to deal with fonts... 😅
So some fonts incorrectly specify a line gap, even though they don't want one, and some fonts do specify one without which there's no proper line spacing. Additionally I assumed that terminals technically don't have any gaps between character cells anyways (https://github.com/microsoft/terminal/pull/14014). So what should we do now?

I'll try to download your font and try to find a solution that works for both, "Terminus TTF" and "Overpass Mono" simultaneously, but I suspect either of the two fonts will need to be broken, depending on whether we want to support line gaps or not.

**Comment by ninlil** [comment]
The same occurs with "Comic Code" ($0 "demo-purchase" available from https://www.myfonts.com/products/demo-regular-comic-code-474333 - actually to the point of cutting of the top 1 or 2 rows of pixels on high characters (like "f" and "8")

Yes, I understand that "technically" characters fill an entire "cell", but IMO:
* the release-version works just fine (i.e as the font says)
* there is no need to ignore it due to "visual considerations" like empty space between blocks (the user chooses the font)
* if you really want it the add an option to enable/disable the extra line-height
* or just add a custom "line-height" setting to allow users to have extra spacing between lines (some fonts are really tight, and some people have hard time reading -> "Accessability-feature")

So, please don't cut this extra line-height
