### ISSUE TITLE
WSL file not found

### ISSUE THREAD

**Issue by usarral** [microsoft/terminal#14149]
### Windows Terminal version

1.15.2524.0

### Windows build number

10.0.19044.0

### Other Software

WSL

### Steps to reproduce

I set Ubuntu as default when I open Windows Terminal.

### Actual Behavior

When I Open Windows Terminal OR a new tab on it it says:
![image](https://user-images.githubusercontent.com/41452910/194358984-cc3c8c89-85f8-4b4b-a2c9-a7fb467d12af.png)
but if I open wsl typing _wsl_ on powershell it opens good
![image](https://user-images.githubusercontent.com/41452910/194359427-d9cd6472-f1b0-46cc-8308-7a593326482d.png)

**Comment by sergiodomingo** [comment]
It seems to be related to this: https://github.com/microsoft/terminal/issues/14157

**Comment by lhecker** [comment]
Could you post a screenshot of your Ubuntu profile similar to this screenshot of my PowerShell profile?

![image](https://user-images.githubusercontent.com/2256941/195456236-9e043a25-825b-4c3b-9cb6-ef8e9cf8d010.png)

**Comment by usarral** [comment]
That's my config

![image](https://user-images.githubusercontent.com/41452910/195667066-5d19d6e2-2fae-4c68-a54d-a244c4fc7d16.png)

**Comment by zadjii-msft** [comment]
Hey, sorry for losing track of this one. We've got a theory that this was due to an older version of WSL that might just be fixed on newer Windows versions. Are you still seeing this? 

If you are, we think that you might be able to work around this by changing the `commandline` of your Ubuntu profile to:

```
wsl -d Ubuntu ~
```

Does that work/?
