### ISSUE TITLE
Using coordinates terminal window not positioned as intended by user

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#14176]
### Windows Terminal version

main 43dbbd5

### Windows build number

10.0.19044.0

### Steps to reproduce

- build terminal with commit 43dbbd590 included
- set `Center on launch` is SUI
- start terminal with `wtd.exe --pos 100,100`

### Expected Behavior

- terminal to be closer  to the upper left corner (x=100, y=100)

### Actual Behavior

- terminal window is centered

**Comment by DHowett** [comment]
Thanks for the report!
The interplay between these options is complicated.

When `center on launch` is set, the position is used to determine _which monitor_ to center on. If you have multiple monitors, and you set `X = -1` + `Center`, Terminal will be launched in the center of the monitor to the left of primary.

This is poorly explained, but it is by design.

**Comment by DHowett** [comment]
To be fair, perhaps this position specified on the command line should override the center option.
