### ISSUE TITLE
Unable to find the selected font

### ISSUE THREAD

**Issue by ggutenberg** [microsoft/terminal#14173]
### Windows Terminal version

1.16.264

### Windows build number

10.0.22621.521

### Other Software

Nerd Fonts (https://www.nerdfonts.com/font-downloads)

### Steps to reproduce

Download and install a Nerd Font from https://www.nerdfonts.com/font-downloads

Within Windows Terminal, go to:

Settings > Ubuntu > Appearance > Font Face > Pick a Nerd Font (I've tested this with CodeNewRoman NFM and CaskaydiaCove Nerd Font Mono) > Save

Open a new Ubuntu tab. All is good.

Close Windows Terminal. Re-open it. An error is displayed:

![image](https://user-images.githubusercontent.com/1128406/194919885-81a730b2-2f57-40cd-8d7b-243ff7befc90.png)

And the Nerd Font is not used. Going back into Settings > Ubuntu > Appearance and just hitting Save allows the font to render correctly within that terminal instance. Closing it and opening it again causes the issue to repeat.

Note that this only started occurring after upgrading to 22H2.

### Expected Behavior

No error appears and the font that's set is used.

### Actual Behavior

An error is displayed:

![image](https://user-images.githubusercontent.com/1128406/194919885-81a730b2-2f57-40cd-8d7b-243ff7befc90.png)

And the font is not used.

**Comment by GabrielDuarteM** [comment]
I have a slightly similar problem. Some days ago when I opened wsl, it asked me to update it to the windows store, or something like that, asking me to run `wsl.exe --update`. I found weird, because I was already using the windows store version of ubuntu, but I ran it anyway, and everything was fine for that day. After that, on the next day I restarted the computer, and when I opened windows terminal I got the following message: 

```
Unable to find the selected font "Hack Nerd Font Mono".

"Consolas" has been selected instead.

Please either install the missing font or choose another one.
```

I then uninstalled the Hack font and reinstalled it, restarted the computer as prompted, and now it shows

```
Unable to find the selected font "Hack Nerd Font Mono".

"Hack" has been selected instead.

Please either install the missing font or choose another one.
```
(it picks hack now instead of Consolas)

It correctly picks Hacks, but any nerdfont specific characters are not rendered (cause its not the nerdfont variant I specified)

as you can see below, the font is present and it is installed, and I can use it normally on notepad for example, its only on windows terminal that I have this issue, and I'm downloading the official hack font, which already includes the nerdfont variant, but I also tried downloading the specific one from the nerdfont gh repo, but still the same problem

![image](https://user-images.githubusercontent.com/7675500/195132967-abfc4453-8273-450d-bb4f-fbc5d657a139.png)

**Comment by dwmuller** [comment]
Having a similar problem. Bash for Git and Powershell work, but a WSL terminal fails render a character in my prompt, specifically \u276f . All are configured to use the same nerd font.

**Comment by ggutenberg** [comment]
This issue appears to be resolved with the `2022-10 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5018427)` update. At least for me. Closing this particular issue.

**Comment by simsrw73** [comment]
I've been experiencing this also. Only since upgrading to 22H2. Reinstalling the Meslonerd font fixes it until Windows is restarted. I've spot checked a few other nerd fonts with same result. The fonts correctly appear in the `C:\Users\<user>\AppData\Local\Microsoft\Windows\Fonts`  directory. Fonts are usable in other apps. But Terminal does not see them until I reinstall them (`.\install.ps1 -WindowsCompatibleOnly Meslo`). Tried latest stable and preview releases.

**Comment by j4james** [comment]
I suspect this might be the same issue as #3257.

**Comment by FDUZS** [comment]
> This issue appears to be resolved with the `2022-10 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5018427)` update. At least for me. Closing this particular issue.

well, it appears exactly after the installation of this cumulative update on my PC...

and, can you find the nerd fonts installed in the font settings (not the classical control panel)? the answer is no for me.

**Comment by arafatm** [comment]
I had to add to .bashrc

```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
```

**Comment by kjeske** [comment]
For me just restarting the `Windows Font Cache Service` was enough.

**Comment by yooakim** [comment]
After recent updates to font settings in Windows 11 (I suspect) Windows Terminal doe not find my font. I use the `CaskaydiaCove Nerd Font Mono` font.

My system ahs been wrking fine but all of a sudden Windows Terminal doesnot find the font.

If I re-install the fonts it works. But after a re-boot it doesnot find the font so I have to re-install again.

I have not yet tried installing the font for `All users` - but will do that next.

I just wanted to add more info to this open issue.

I am using `Windows Terminal Version: 1.22.10352.0` running on `Windows 11 Business 10.0.26100`

Here are the relevant lines from my settings:
````json
    "profiles": 
    {
        "defaults": 
        {
            "colorScheme": "Cobalt2",
            "font": 
            {
                "face": "CaskaydiaCove Nerd Font Mono",
                "weight": "semi-light"
            }
        },
```

**Comment by vemundha** [comment]
I fixed the issue (also after a win11 restart) with: 
```powershell
net stop wuauserv 
net stop FontCache del /F /Q Remove-Item -Path "C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache\*" -Force -Recurse 
net start FontCache 
net start wuauserv
```

**Comment by preetmyob** [comment]
> I fixed the issue (also after a win11 restart) with:
> 
> net stop wuauserv 
> net stop FontCache del /F /Q Remove-Item -Path "C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache\*" -Force -Recurse 
> net start FontCache 
> net start wuauserv


Your code has some formatting problems, so I've corrected it here. Also I didn't need the `DEL`

```powershell
net stop wuauserv 
net stop FontCache 
Remove-Item -Path "C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache\*" -Force -Recurse 
net start FontCache 
net start wuauserv
```

**Comment by apuppy** [comment]
> For me just restarting the `Windows Font Cache Service` was enough.

Thank you, worked for me.

**Comment by oguzhane** [comment]
> > I fixed the issue (also after a win11 restart) with:
> > net stop wuauserv
> > net stop FontCache del /F /Q Remove-Item -Path "C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache*" -Force -Recurse
> > net start FontCache
> > net start wuauserv
> 
> Thank you for this, it's worked. There was a slight problem with your code's formatting, so I've corrected it here. Also, I didn't need the `DEL`
> 
> # in an administrator shell 
> stop-service wuauserv 
> stop-service FontCache 
> Remove-Item -Path "C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache\*" -Force -Recurse 
> start-service  FontCache 
> start-service wuauserv

Thank you worked for me!
