### ISSUE TITLE
Add Settings Page

### ISSUE THREAD

**Issue by ArtexJay** [microsoft/terminal#1423]
# Summary of the new feature/enhancement

Users who do not want to tinker in the js file to get the desired settings would have a better time in the settings enabling or disabling certain features. Or changing the font much more easily.

# Proposed technical implementation details (optional)

When clicking on the settings option it should open up a page where one would be able to easily change their settings as they please via a GUI and not through a JS text editor.

**Comment by imjasonmiller** [comment]
> Users who do not want to tinker in the js file ...

Aren't most active users of the terminal familiar with `.json` files? It makes it much easier to share settings with other users and devices. They briefly touched on this during [this talk](https://www.youtube.com/watch?v=KMudkRcwjCw&t=1040) and mentioned that it was a big ask from the community.
I can imagine that the current implementation might allow developers to move faster as well.

**Comment by josh-degraw** [comment]
@imjasonmiller I personally don't mind that the config is in json, for me the issue is knowing what can go where. The schema documentation page took me a while to find and was less clear than it could be, and there were things I'd seen other people try with the terminal but couldn't find out how to do it.

What I would love is basically just a wrapper on top of the config file, in a similar way as how VsCode handles configuration. You can use the GUI if you want, or if you prefer or need more advanced config you can open the json file.

Another annoyance for me was that when I hit settings it launched visual studio, and I thought my system was trying to relaunch that after rebooting, so I hit settings again a couple of times and it launched like 5 instances of Visual Studio before it actually opened.

I'm aware that's because VS is the default for that on my machine for some reason, which I will change, but it was still a confusion/hassle.

**Comment by csm10495** [comment]
I'm going to agree that a settings GUI would be nicer than a json file. I guess if someone really wants to mess with the raw file, they still could. A GUI works better for me since its easier to read and layout than a raw file. We can also have descriptions for the different options. 

... reminds me of the similar changes that were made to VS Code to have a settings GUI instead of just a raw json.

**Comment by cinnamon-msft** [comment]
#1564

**Comment by diligamer** [comment]
I believe that users who even use the terminal can tinker in raw json, so this is useless.
