### ISSUE TITLE
cannot pin to taskbar from start menu

### ISSUE THREAD

**Issue by pizzacrystal** [microsoft/terminal#14262]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. install windows terminal from microsoft store
2. pin WT to taskbar from program list of start menu -- **failure**
![1666255681519](https://user-images.githubusercontent.com/11605580/196901938-99b24b60-a342-4afb-b405-c48979474591.png)
3. pin WT to start menu as tile -- ok
4. pin WT to taskbar from tile -- **failure**
![1666255847207](https://user-images.githubusercontent.com/11605580/196902594-c6cadb75-5e98-41cc-ae97-3082e05725df.png)
5. run WT by clicking tile -- ok
6. pin WT to taskbar **on taskbar** -- **ok**
![1666256013366](https://user-images.githubusercontent.com/11605580/196903270-a19559aa-c67f-46a8-8f06-dea5e9805465.png)
7. **run WT by left clicking directly on taskbar icon** -- **failure**
8. **run task (i.e., powershell or gib-bash) of WT by right clicking taskbar icon then clicking task** -- **ok**

### Expected Behavior

1. pin to taskbar normally as other apps
2. run it by left clicking on taskbar icon directly

### Actual Behavior

as described in steps of reproducing.

**Comment by lhecker** [comment]
We don't really handle this part of Windows. You should file a feedback in the "Feedback Hub" app under "Desktop Environment > Taskbar".

But the issue you're seeing doesn't really seem to happen to a lot of people. Looking through our GitHub for instance, only 3 people have reported this over the last 3 years as far as I can see. So if I'm being realistic I believe it's not likely that the team working on the taskbar will fix it soon and instead work on fixing bugs that affect more people.

So as annoying as it sounds, what I'd personally do as a Windows user it to just reinstall Windows at some point in the future. Especially since this isn't the only thing broken with your taskbar - all the icons in the jumplist are missing as well:
![image](https://user-images.githubusercontent.com/11605580/196903270-a19559aa-c67f-46a8-8f06-dea5e9805465.png)

**Comment by DHowett** [comment]
Thanks for the quick triage, @lhecker! It does look like this is some sort of Taskbar/app model issue. Unfortunately, there isn't much we can do about those apart from recommending filing feedback.

Really sorry for the inconvenience!
