### ISSUE TITLE
Weird output log format when run gradle command

### ISSUE THREAD

**Issue by zeroarst** [microsoft/terminal#14287]
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2130

### Steps to reproduce

I have a andriod project and run `./gradle testDebugUnitTest`. I assume any other gradle project that could run `test[Variant]UnitTest` should be able to reproudce the issue.
I can see it keeps printing prograss bar instead using the same one which messes up the log.

### Expected Behavior

Tested in WIndows Command Prompt, the progress bar should display correct.
![image](https://user-images.githubusercontent.com/1834837/197453625-01dc8319-48b2-4e9b-ad8b-1f26e610eaff.png)

### Actual Behavior

Looks like progress bar does not display correct. 
![image](https://user-images.githubusercontent.com/1834837/197453743-ae3f859c-f0d6-4aba-bf5a-f78c9641d26f.png)

**Comment by DHowett** [comment]
So, unfortunately, this is another instance of "client application is not using `ENABLE_VIRTUAL_TERMINAL_PROCESSING`". The terminal goes to _great_ lengths to make sure that it's always enabled, but Gradle or the Java runtime or msys/cygwin is **explicitly** disabling it. There's nothing we can do when the application requests that it VT sequence processing be disabled (because it might be doing so for compatibility reasons.)

/dup https://github.com/gradle/gradle/issues/13279

**Comment by zeroarst** [comment]
That issue is "colours are not escaped". But I don't see those colour code. Is it still the same issue?

**Comment by zeroarst** [comment]
Looks like for now, adding `TERM=cygwin ./gradlew` to `./bashrc` is the right solution in that link. Thanks.
