### ISSUE TITLE
unfocusedAppearance in "defaults" overwrites unfocused background in all profiles

### ISSUE THREAD

**Issue by thgross** [microsoft/terminal#14337]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.0

### Steps to reproduce

use this in the "defaults" profile:
```JSON
"unfocusedAppearance": {
    "foreground": "#a0a0a0"
}
```
and something like this in a profile:
```JSON
{
    "background": "#101050",
    "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "hidden": false,
    "name": "PowerShell",
    "source": "Windows.Terminal.PowershellCore",
    "tabColor": "#202080"
}
```

### Expected Behavior

when the pane is out of focus, only the foreground-color should change to #a0a0a0.

### Actual Behavior

when the pane is out of focus, not only the foreground-color changes, but also the background-color goes black.

**Comment by carlos-zamora** [comment]
This is actually confusing, but by design. The unfocused appearance in defaults inherits from the regular appearance in defaults. So when `background` isn't found in `defaults.unfocusedAppearance`, we go ahead and use the one in `defaults` instead. Assuming you have a `background` defined in `defaults`, this is probably what's going on.

If you're curious, here's the spec: https://github.com/microsoft/terminal/blob/main/doc/specs/%233062%20-%20Appearance%20configuration%20object%20for%20profiles.md

That said, we probably should mention this weird behavior over in the docs site.
