### ISSUE TITLE
Terminal icon is awfully small in win11 new task manager's autoload apps section

### ISSUE THREAD

**Issue by DoctorKrolic** [microsoft/terminal#14395]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.819

### Other Software

Windown 11 new task manager design 😁

### Steps to reproduce

1. Ctrl + Shift + Esc to bring task manager
2. Go to "autoloaded apps" section (I am using windows not in English, so the actual name of the section might differ. You gotthe idea anyway)

### Expected Behavior

Size of terminal icon is about the same as size of other icons

### Actual Behavior

Terminal's icon is awfully small:
![Taskmgr_SsHjzpfbW8](https://user-images.githubusercontent.com/70431552/202021404-767ee99e-492a-4c17-bf98-a0c2ca911e3f.png)

**Comment by zadjii-msft** [comment]
Hmm. Coulda swore I reported this before to the rest of the OS folks. Lemme see if I can't dig out the original report...


* There was MSFT:34141087 which was duped to MSFT:38185151, but that was for the Settings app, not the Task manager. 
* MSFT:39136857 does reference the Task Manager, but that got duped to MSFT:38996457, which... can't be right. 
* There it is! MSFT:38919648 is the one. 

/dup https://task.ms/38919648

This issue is being tracked internally. I can report back here when the bug ultimately gets resolved.

**Comment by zadjii-msft** [comment]
os.2020!8964972 was merged this Monday, so I bet this will be fixed at some point in the future
