### ISSUE TITLE
can not run after offline install have no any logs

### ISSUE THREAD

**Issue by KnightBlood** [microsoft/terminal#14465]
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19044.1288

### Steps to reproduce

offline install by commd add-appxpackage xxxx
than run

### Expected Behavior

run ok

### Actual Behavior

can not run without any log

**Comment by zadjii-msft** [comment]
> without any log

There's nothing in Event Viewer? Does the window appear then crash/? Is there a `settings.json` that's created in [one of these places](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)? 

It's also possible that some of the dependencies might be missing, because you're doing a offline install. When you do `add-appxpackage`, which file are you installing, _specifically_? The Win11 msixbundle doesn't bundle our dependencies with it (but the Win10 one _should_)
