### ISSUE TITLE
tmux over ssh freezes for the first attempt, works fine for the second+ attempts

### ISSUE THREAD

**Issue by thammegowda** [microsoft/terminal#14494]
### Windows Terminal version

 1.15.2875.0

### Windows build number

 10.0.22621.819

### Other Software

`wsl.exe --version` 
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819

`ssh -V`
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020

`lsb_release -a` Ubuntu 20.04.5 LST

### Steps to reproduce

* ssh into a remote server and run `tmux a`, or simply `ssh -t <remote> tmux a`
* The very first time I run ssh + tmux, connection freezes.
* The second and subsequent runs works as expected
* So, I need two attempts to ssh  and restore tmux. The issue is similar when `htop` is used instead of tmux command. My guess is the issue is because of something common with tmux, htop, etc (perhaps ncurses?) 
* This issue happens especially when VPN connection is reset, and I reconnect VPN. I am using  
<img width="80" alt="image" src="https://user-images.githubusercontent.com/1865964/205761264-f1cc9690-19c7-43d9-a4cf-832f35605ea6.png">

### Expected Behavior

 `ssh -t <remote> tmux a` should work fine in the first attempt.

### Actual Behavior

When I run `ssh -t <remote> tmux a` for the first time, the session freezes; oit doesnt respond to any keys (only way to exit is close the tab). 
When I run `ssh -t remote tmux a` it works fine for the second and subsequent times. We need to two attempts to get ssh + tmux work. I am new to windows and all my have been accessible over VPN only. And this issue happens every time my VPN is disconnected and reconnected. 
I have attached the video demo for your reference

https://user-images.githubusercontent.com/1865964/205760332-4db18180-d3c1-4e13-b7e0-800126fa0884.mp4

**Comment by thammegowda** [comment]
I am not 100% sure the issue is in terminal app. It might ass well in ssh+VPN or remote host, so I am closing it for now, if I find more evidence that issue is indeed in the terminal app, we can reopen it.

**Comment by ritheshh** [comment]
I am seeing the same issue, and it seems to be with WSL and not with terminal.
The first time SSH to a remote server followed by tmux works fine with powerShell. But, the same if done in WSL doesn't work. 
For me the issue is not just seem on the first time, this continues to happen the first couple of times. Then, it suddenly it starts to work.
 
ssh -V
OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

wsl.exe --version
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.2899
