### ISSUE TITLE
Terminal not working when installed from .msixbundle file in a Microsoft Store disabled computer

### ISSUE THREAD

**Issue by atlasfoo** [microsoft/terminal#14539]
Hello. I'm having lots of trouble trying to install Windows Terminal in a work organization computer with several network and configuration restrictions, including to have disabled the Microsoft Store and the `winget` command.

Because of this, we usually install the app via the release distributed `.msixbundle` file, doing this graphically (double clicking the file and clicking install in the installing wizard), it installs correctly but when we try to open it, results in the following error message:

![image](https://user-images.githubusercontent.com/25232701/207148796-34b4b5d6-49d3-4597-bc90-97b99ddd1353.png)

If we do the installation via the `Add-AppxPackage` command, and try to open the installed terminal, it never opens nor shows any kind of feedback, it only shows the icon in the start menu like it's trying to download something from the store (that we can't use).

![image (21)](https://user-images.githubusercontent.com/25232701/207155937-0e1564ff-7212-45de-8b77-e0777dc99a73.png)

We follow the instructions on this [site](https://4sysops.com/archives/install-windows-terminal-without-the-store-on-windows-server/), that shows how to install Terminal on Windows Server (without Store and winget), we follow all the steps including the installation of the VCLibs, but the installation only works on machines that have the winget command enabled. I've looked for this error in google and in the issues of this repo but all references to old versions of Windows Terminal.

Computer Specifications:

- Windows 10 Pro for Workstations 22H2
- Network/Internet connection via organizational proxy
- Microsoft Store not usable (blocked by network policy)
- winget command disabled (deleted by network policy)
- There is not any chance to use the Store and the winget command in this computer

**Comment by DHowett** [comment]
Thanks for the report! For full offline deployment, you'll want to use the "preinstallation kit" that is mentioned in the release notes. It contains an offline provisioning license.

**Comment by atlasfoo** [comment]
Excuse my ignorance, but how can I use the provisioning license for the installation to work? :(

I tried to find something about it in the docs btw.

**Comment by miles-smiles** [comment]
Not sure why this issue was closed.  According to the documentation on [this page](https://learn.microsoft.com/en-us/windows/terminal/distributions) the preinstallation kit seems to be for a different use case and assumes access to the Microsoft store. When I install using the msix bundle, the installation seems to complete but launching the terminal fails.  

I'm getting an error message that says: “Windows cannot access C:\Program Files\WindowsApps\Microsoft…\WindowsTerminal.exe”. Sure enough there's no C:\Program Files\WindowsApps directory.

Is there another way around this problem for machines that don't have network access?

**Comment by DHowett** [comment]
Not sure how I missed your request, atlasfoo! Sorry about that.

You should be able to provision Terminal for offline use using `Add-AppxProvisionedPackage` (rather than `Add-AppxPackage`) plus the contents of the preinstallation kit. You'll need to pass the path to the main package, the dependency packages, and the license XML file.
