### ISSUE TITLE
New Tab Menu overlaps Close Dialog

### ISSUE THREAD

**Issue by Lo0oG** [microsoft/terminal#14535]
### Steps to reproduce

Have more than one tab open and then click on the down arrow next to the new tab button to make the tab menu option appear. Then click on the close window.

### Expected Behavior

New tab menu should not overlap close dialog

### Actual Behavior

Some of the close dialog is hidden behind the new tab menu.
![image](https://user-images.githubusercontent.com/50969206/207101427-b1416dcc-c389-4e39-b187-3da4b54beed3.png)

**Comment by zadjii-msft** [comment]
What OS, Terminal version are you on/? I can't repro this locally on `10.0.25267.1001`. This might be an OS bug that was fixed, or it might have even been fixed in the Terminal itself...

**Comment by Lo0oG** [comment]
Sorry for missing those out initially.
Terminal is 1.15.2874.0
OS is 10.0.19044

**Comment by elsaco** [comment]
@Lo0oG try adding a 3rd tab or more and the drop-down moves further left. It overlaps when there are only 2 tabs open:

![close_all_tabs](https://user-images.githubusercontent.com/3933920/207116488-2fa09294-8eb4-461a-87d1-c213679bf351.png)

Test was done on Windows 10.

**Comment by Lo0oG** [comment]
Yes, if the window is big enough or there are more tabs then the menu does not cover the dialog, but you can't really call that a fix.
Also, the menu doesn't get greyed out when the rest of the window does, but that's just a minor issue.

**Comment by zadjii-msft** [comment]
Yea, okay, I'm seeing this on my 19041 VM as well. I reckon this was probably a XAML islands bug that got sorted out between Windows 10 and Windows 11. I can try and dig up the internal bug number if we really need, but that might take a while for something of fairly low value. There's almost no chance that this gets backported to Windows 10, unfortunately 😕 

Interesting catch though! The Flyout is always in the "topmost" layer of our window. I reckon this is due to the ContentDialog not dismissing any Popups in the PopupRoot, so the flyout ends up sticking around over the window.
