### ISSUE TITLE
color scheme is causing wierd visuals since Powershell 7.3 update

### ISSUE THREAD

**Issue by HymanZHAN** [microsoft/terminal#14543]
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.0

### Other Software

Powershell 7.3, using One Half Dark theme

### Steps to reproduce

Install Powershell 7.3 and run it in Windows Terminal

### Actual Behavior

![image](https://user-images.githubusercontent.com/26806995/207200348-76a9c493-3163-48e6-9f7b-1e2e7f702565.png)

The background color and foreground color of directory entries are reversed and don't look good at all...

**Comment by elsaco** [comment]
@HymanZHAN this must be from the effort of the PS team to use ANSI formatting via `$psstyle`. In a pwsh session type `$psstyle.fileinfo` to see all the coloring. I don't know if setting blue backgrounds for directories was intentional or an oversight. If you change the ANSI escape to colorize the foreground instead the listing looks like:


![wt_14543_test](https://user-images.githubusercontent.com/3933920/207237198-a6c2c4ee-e107-4776-a3b2-4f60ae16c0ef.png)

**Comment by HymanZHAN** [comment]
Ah I get it. Sorry I wasn't in my right mind when posting the issue here. I sure hope that's an oversight though... I will create another issue over in the Powershell repo.

**Comment by DHowett** [comment]
> Sorry I wasn't in my right mind when posting the issue here.

No need to apologize! Thank you for following up.
