### ISSUE TITLE
Feature Request: Option to change location of profiles.json

### ISSUE THREAD

**Issue by logonoff** [microsoft/terminal#1455]
# Summary of the new feature/enhancement
Going though local appdata is hard and it'd be nice if you could change where it fetches the config file. a usecase could be people who have dotfiles repos to place their config in the user dir or config folder instead of making a symlink

# Proposed technical implementation details (optional)
Maybe put the path of it in a json file and have it configurable via a gui?

**Comment by fredrikaverpil** [comment]
I'm symlinking from `~\dotfiles\profiles.json` to `C:\...\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json" right now. But I am curious about that `8wekyb3d8bbwe` identifier in the path.

What is it for and will it change?

**Comment by kumarharsh** [comment]
I think `8wekyb3d8bbwe` identifier is a fixed string (perhaps related to it's Store ID or something similar), and won't change.

**Comment by Cologler** [comment]
I guess 8wekyb3d8bbwe is the store publisher id of Microsoft.

**Comment by DHowett-MSFT** [comment]
We're probably not going to do this. A symbolic link will work. The identity, `8wek...`, is based on the name used to sign the app bundle. This one means "Microsoft." It won't change.

**Comment by franjozen** [comment]
The problem with a symbolic link is that the terminal doesn't react to the settings changing.

**Comment by fredrikaverpil** [comment]
@franjozen are you sure?
I am 90% sure my terminal reacts to changes immediately when editing the profile and I have a symlink set up to my dotfiles.

**Comment by franjozen** [comment]
@fredrikaverpil Yes, I've created the symlink like this:
new-item -itemtype symboliclink -path .\ -name profiles.json -value ..\..\..\..\..\dotfiles\WindowsTerminal\profiles.json
Nothing happens when I save, I have to restart Terminal to see the changes.

**Comment by fredrikaverpil** [comment]
@franjozen oh, it seems I have the very same behavior here as on your end.

**Comment by Renalrazi** [comment]
Sorry for bumping this closed post. Posting if somebody hasn't figured yet. 
You need to create a junction/SymbolicLink to the LocalState folder that link to a folder that contains the WT settings.json instead of linking the settings.json directly, if you want the settings to update right away when you edit the settings.json. 

Something like this:
New-Item -Force -Type Junction -Path "$ENV:LOCALAPPDATA\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState" -Value "<path>\<to>\<myfolder>\<withtheWTsettings.json>\<insideit>"
