### ISSUE TITLE
Feature Request -  List Icons in the default profiles.json

### ISSUE THREAD

**Issue by JushBJJ** [microsoft/terminal#1456]
# Summary of the new feature/enhancement

It took a while for me to figure out how to change the icons using the JSON file somewhat, I looked into https://github.com/microsoft/terminal/tree/master/src/cascadia/CascadiaPackage/ProfileIcons to see if I can use them and it turns out, yes.

# Proposed technical implementation details (optional)

```
    "Icons":
    [
        {
            "Powershell" : "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "Linux" : "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.scale-100.png",
            "CMD" : "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png"
        }
    ]
```
This example could be added in the auto-generated profiles.json file to make things easier for users to choose icons if they wanted to do so.

**Comment by zprood** [comment]
+1 for this feature request, I'd like to change the icon to Ubuntu logo instead of Linux logo. 
Cheers !

**Comment by cinnamon-msft** [comment]
If you'd like to change the icon of a profile, feel free to change the path of the "icon" property to where your desired icon is 😊
In terms of creating an object to store all of the icons, we'd like to keep the icons separated by profile because it'll directly translate to the settings UI once it's implemented i.e. we won't be having a page for only icons, however we'll have a page for individual profiles.

**Comment by parsivan** [comment]
Same I want to change the icons but I don't want the new icons to be in another folder. Where are the default icons folders? I tried finding the new terminals src folder but I can't find them.
