### ISSUE TITLE
Tabs UI is unusable in windows' dark mode

### ISSUE THREAD

**Issue by alex-jitbit** [microsoft/terminal#14574]
Look at the tab bar screenshot

1. You can't really tell which tab is active
2. You can't even see where each tab starts/ends

(well, unless your desktop background is white or something)

![image](https://user-images.githubusercontent.com/33555768/208238210-4d6cb6dc-b1e2-4ab8-bd8c-91d568f25bdb.png)

**Comment by zadjii-msft** [comment]
What version are you on/? We changed the default tab contrast in 1.16, but also added [a whole pile of new settings](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/themes) to configure how the tabs/titlebar/anything really look.

**Comment by alex-jitbit** [comment]
@zadjii-msft I'm on the latest version from Windows store AKA the version that is installed when you click the "Install Windows Terminal" on this Microsoft's page https://learn.microsoft.com/en-us/windows/terminal/

Which hasn't been updated since 2019 by the way.

**Comment by zadjii-msft** [comment]
* "I'm on the latest" is not a version number. You can copy the version number from the About dialog. Open the About dialog by opening the menu with the "V" button (to the right of the "+" button that opens a new tab) and choosing About from the end of the list.
* The latest release is https://github.com/microsoft/terminal/releases/tag/v1.15.3465.0, which came out _five days ago_. That version's in the Store too. The store is kinda annoying for not showing _when_ the latest update was released, but :shrug:
* I reckon, since you're on Terminal (stable), that you're on 1.15, not 1.16, which is only in Terminal Preview currently. I'd give that a shot if you're really bothered by this, or wait till next month when we push the current preview builds to the stable channel.
