### ISSUE TITLE
Allow for adjustable delay when opening New Tab Menu Customizations

### ISSUE THREAD

**Issue by DennisGaida** [microsoft/terminal#14756]
The New Tab Menu customization implemented in #13763 by @FWest98 are awesome! The sub-menus pop out a bit too late for my taste when hovering over them and I would love to show the sub-menus quicker than currently implemented.

Secondly I would love to be able to click on sub-menus to open them directly/quicker. This is currently not possible and I have to wait for the on-hover delay to open the menu.

I would love to be able to set the delay before sub-menus pop out - in my case I want them more responsive / faster. It currently feels like it is almost a second before the sub-menus pop out.

Just for reference here is a screencast showing how "slow" (subjective) the sub-menus open:
![WindowsTerminal_1heG0EJ4yc](https://user-images.githubusercontent.com/2392217/215439894-0252181b-86b8-4497-b864-3d55c70fbc3d.gif)

**Comment by zadjii-msft** [comment]
Hmm, this isn't a bad idea, but I'm not sure there's much we can do ourselves about this. It doesn't look like there's anything we can do to control the responsiveness of a [`MenuFlyout`](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.menuflyout?view=winrt-22621) by itself. We'll probably need to move this request upstream to WinUI

**Comment by FWest98** [comment]
I think the delay is there from a usability perspective to prevent menus from opening/closing accidentally by just moving the cursor past them. The delay is to make sure it's an intentional hover instead of "passing by". The delay for closing is to make sure that someone just hovering slightly outside doesn't immediately collapse the entire tree.

I did notice that when using keyboard navigation, the menus open instantly. So that might be an option for you.

**Comment by j4james** [comment]
Have you tried turning off the "Show animations in Windows" option in the "Ease of Access" section of the OS Settings? There's still a delay before menus are triggered on hover, but there's no expanding animation as the menu is rendered, so I think it does make it feel a bit faster.

**Comment by zadjii-msft** [comment]
Thanks for the discussion everyone!
