### ISSUE TITLE
How to prevent PowerShell from opening in Windows Terminal Preview?  

### ISSUE THREAD

**Issue by oshihirii** [microsoft/terminal#14765]
Windows Terminal Preview
Version: 1.17.1023

PowerShell
Version:  PowerShell 7.3.1

I have my Windows Terminal Preview environment set up as I like it (all `Git Bash` windows):

 - A left side panel 
 - A right side panel with an upper and lower panel 

I have set it so that it retains this layout after exiting.  

I.e. the next time I open Windows Terminal Preview, it looks the same.  

However, when I open `PowerShell 7 (64)` from the Start menu:    

 - It opens up Windows Terminal Preview (with my desired layout)
 - It opens up another instance of Windows Terminal Preview with just a `PowerShell 7 (64)` tab  

If I then:

 - Close the instance of Windows Terminal Preview with my desired layout
 - Close the instance of Windows Terminal Preview with the PowerShell tab only  

The next time I open Windows Terminal Preview, it opens up an instance of Windows Terminal Preview with a PowerShell tab.

Rather than the desired behaviour, which is opening Windows Terminal Preview with my desired layout.  

I am on a new PC and don't think this dynamic used to occur - I think previously PowerShell just opened up in, um, PowerShell?  

How do I prevent PowerShell from opening in Windows Terminal Preview?

**Comment by zadjii-msft** [comment]
You could turn off the "default terminal" feature:

![image](https://user-images.githubusercontent.com/18356694/215738367-d0171aab-10c3-4a0d-b026-d5030584e3e1.png)

By setting it back to "Console Host"

Or, you could "quit" the Terminal instead of closing the windows one-by-one:
![image](https://user-images.githubusercontent.com/18356694/215738641-c7083512-eb8b-4b07-9ee4-f4fdbf2c4bae.png)
That'll close all the windows (and save their state), like a browser would. 

That what you're looking for/?

**Comment by oshihirii** [comment]
You first suggestion did the trick, thank you 👍.
