### ISSUE TITLE
Setting Appearance to "Use Windows Theme" only half respects it

### ISSUE THREAD

**Issue by blowdart** [microsoft/terminal#14760]
### Windows Terminal version

1.16.10261.09

### Windows build number

10.0.22621.0

### Steps to reproduce

Change settings in Terminal to Use Windows Theme
Set Windows to have WIndows Mode as Dark and App Mode as Light
Glare at tab background colour in disgust

### Expected Behavior

In mixed dark/light other apps, such as Edge and Explorer, use the app colour for the tab background, I would expect Terminal to do the same, rather than end up with a dark tab background

![Screenshot 2023-01-30 045815](https://user-images.githubusercontent.com/796298/215484145-03b00ed1-a166-468f-a6ba-cfaafd602b12.png)

### Actual Behavior

![Screenshot 2023-01-30 045258](https://user-images.githubusercontent.com/796298/215483707-e5c48a7d-4125-4a2a-aaab-09607ea4cbc9.png)

The tab background is always dark.

**Comment by zadjii-msft** [comment]
Ah so, yes, this might need to be clarified too. This is a side effect of some of the Theme changes in 1.16. I'm workshopping some messaging in https://github.com/MicrosoftDocs/terminal/issues/635#issuecomment-1405272392. I'll add a note about this.

Basically, in 1.16, the default themes will always use the Terminal's background color as the default color for the tab. So, in the default case, with a black terminal window, you're going to get a black tab. With a blue color scheme (like Campbell PowerShell), you'll get a blue tab. This is to give the Terminal that "seemless" feel. 

In light mode, that obviously creates a bit of a weird case where you get a black tab on a white tab row. No worries though! With 1.16, you can customize the theme of the Terminal in lots of new ways. So, if you want a theme where the tabs are white again, you can do something like:

```json
    "theme": "White Tabs",
    "themes":
    [
        {
            "name": "White Tabs",
            "tab":
            {
                "background": "#ffffffff",
            },
            "window":
            {
                "applicationTheme": "light"
            }
        },
    ]
```

ALTERNATIVELY, you could set the color scheme of the Terminal to something with a white background. If you're using light theme, then maybe that's what you want?

1.17 is going to make this even better, because we've added the ability to set different color schemes depending on the theme of the window, so you can set your scheme like:

```json
"colorScheme":
{
    "light": "One Half Light",
    "dark": "One Half Dark",
},
```
 
and now presto - the terminal background will change in accordance with the `window.applicationTheme` of the Terminal. 


Does that all make sense/?

**Comment by fxzxmic** [comment]
![image](https://user-images.githubusercontent.com/54622331/217779689-d21aa5c9-9995-4c19-8bee-1bc06989c2df.png)
I'm glad to see that there is still a solution, because I really don't like this feature, which is too odd. I prefer dark interfaces but bright tabs.

And it seems that 1.17 has made an interesting attempt to provide more customizable features.

**Comment by fireattack** [comment]
To me, the UI, and the "content" inside (or the "canvas"), are two different parts. 

The UI should be controlled by the theme, while the canvas should be controlled by something else (in WT's case, the color scheme for that profile). 

Just like the you can set page color in Word without affecting the UI elements. Or how tabs look like in browsers.

Another change I don't understand is why it defaults to dark instead of "use Windows theme".

**Comment by zadjii-msft** [comment]
I'm gonna close this to merge the discussion with /dup #14815
