### ISSUE TITLE
Use Mica Alt as tab bar's backdrop instead of bare Mica

### ISSUE THREAD

**Issue by fitojb** [microsoft/terminal#14785]
When using Mica as the terminal's background, there is no visual differentiation between the app's UI and the terminal content or SUI. This can be fixed by using MicaAlt in the tab bar, as tabbed Windows Explorer and Windows Notepad do.

![image](https://user-images.githubusercontent.com/554953/216754052-7868b792-0547-4478-9441-d5e0b55cc4a8.png)

**Comment by 237dmitry** [comment]
> When using Mica as the terminal's background, there is no visual differentiation between the app's UI and the terminal content or SUI.

In my opinion, there is a difference. Or did I misunderstand you? I don't know how to change the color of the settings tab.

![Screenshot 2023-02-04 113417](https://user-images.githubusercontent.com/78153320/216757790-1d4527b0-1115-4dda-be28-fce0deedd126.png)

**Comment by zadjii-msft** [comment]
So, this is an interesting scenario. We can only have one Mica surface for the entirety of the Terminal window, since we're using the DwnSetWindowAttribute version of mica. We can either get Mica or alt mica, but _not both_. I believe that Explorer is either using WinUI 3, or multiple XAML islands to try and achieve the combo effect, neither of which are really options for the Terminal window. 

I think we're unfortunately just going to have to reject this request, for architectural reasons. We might be able to revisit if we ever move to WinUI 3, but that seems indefinitely far out for the time being.

**Comment by yujinlin0224** [comment]
@zadjii-msft If now it is impossible to use both Mica and Mica Alt, how about add an option to use Mica Alt only?

**Comment by BreeceW** [comment]
This should be reopened. The effect achieved in apps using Mica Alt like Explorer is not done by using both Mica and Mica Alt, but rather by laying a solid color brush (built in to WinUI 2 as `LayerOnMicaBaseAltFillColorDefault` which is SolidColorBrush #733A3A3A in dark mode) on top of just Mica Alt. Therefore there is no architectural issue in applying the Windows 11 design guidelines to Terminal in this case and using Mica Alt.

So a XAML Islands window with `DwmSetWindowAttribute` `DWMWA_SYSTEMBACKDROP_TYPE` `DWMSBT_TABBEDWINDOW` and a panel with the brush `LayerOnMicaBaseAltFillColorDefault` woud look like this:
![XAML Island window with a tab view with translucency over Mica Alt](https://github.com/microsoft/terminal/assets/18747724/e1f9cc9f-1227-4199-a640-60a5d0eeb939)
And this provides the visual contrast requested in the issue.
