### ISSUE TITLE
Windows terminal can get stuck completely and ignore any input

### ISSUE THREAD

**Issue by lesleyrs** [microsoft/terminal#14793]
### Windows Terminal version

1.15.3465.0

### Windows build number

10.0.19045.0

### Other Software

WSL

### Steps to reproduce

I have reproduced this before but it doesn't seem that easy to do.

Sometimes when making a typo, then quickly retyping and hitting enter, windows terminal will no longer take any input unless you close the session and open a new one. It will accept ctrl-C once or twice which will make the cursor jump to start of the current line on top of your name as seen in the screenshot below. Then it ignores all input again.

### Expected Behavior

I expected that it would not get stuck and continue to take input regardless of how quickly I'm using commands.

### Actual Behavior

![image](https://user-images.githubusercontent.com/19632758/216858864-ef6fea04-5d42-4ce0-b1e1-c01152e57cfc.png)

I just realised this screenshot only shows 1 typo, but I made 2. The second one causing the terminal to get stuck.

Haven't had this happen outside of WSL yet.

Not sure if this belongs here or at https://github.com/microsoft/WSL

**Comment by lhecker** [comment]
Hmm... Unfortunately for us to debug this, we'd first need a consistent repro. 😕
Otherwise what you could check is if any process below WindowsTerminal.exe or related to WSL is suddenly dying when this issue happens (I'd suggest using [Process Hacker (now System Informer)](https://systeminformer.sourceforge.io/nightly.php) or [Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer)), or a memory dump of WindowsTerminal.exe and OpenConsole.exe once it gets stuck. However I'm not confident that this would help as much as a consistent repro unfortunately...

**Comment by DHowett** [comment]
Hey there! So, this is actually a weird interaction between WSL and the rest of _Windows_. One of the keys that you're hitting might be <kbd>Tab</kbd> or some other thing that triggers completion.

The problem is, tab completion inside WSL is by default very slow[^1]. It enumerates every `.exe` and `.dll` in the Windows system folder.

Unfortunately, this is out of our control. You can turn off the path sharing behavior in the [interop settings](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) section of your WSL config.


[^1]: This is because it automatically copies the Windows `%PATH%` into `PATH` on the Linux side.
