### ISSUE TITLE
Automatically submit winget packages when we release a new version

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#14795]
We don't currently. We should.

PowerToys has this handy script for automating their release to winget. We could probably copypasta with minimal changes.

https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml

**Comment by DHowett** [comment]
FWIW I haven't done this yet because we do post-release-build vetting and release on a schedule, rather than "every time the release pipeline builds."

That is: We build the final releases on Thursdays or Fridays (as if 🤣) and then publish them the following Tuesday.

WinGet requires a durable public asset URL, which for us would be GitHub.

We may prefer to automate this off the tail end of a GitHub Action that fires when a release is published...

**Comment by zadjii-msft** [comment]
You know, that's right, the script above might actually just work based off a GH action on publishing the _release_. It's been so long since I opened that tab, I had forgotten. I'll clarify.

**Comment by sitiom** [comment]
This can be done via [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser). I have opened up a PR:
- #14965
