### ISSUE TITLE
Tapping the + button with a touchscreen opens the menu rather than the default profile

### ISSUE THREAD

**Issue by WillPittenger** [microsoft/terminal#14801]
### Windows Terminal version

1.16.10261.0

### Windows build number

Edition	Windows 11 Pro Version	22H2 Installed on	‎12-‎8-‎2022 OS build	22621.1194 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Other Software

PowerShell 7.3.2

### Steps to reproduce

Using a touchscreen rather than a mouse, tap the + rather than the drop down menu.

### Expected Behavior

WT should immediately open the default profile

### Actual Behavior

WT opens the drop menu.

**Comment by DHowett** [comment]
Thanks for the report! This one is actually by design. The owners of the Windows UI controls have decided that the touch target for the `+` and the `v` are too small or too ambiguous, and that any tap on _either_ of them should open the dropdown menu.

This behavior is conserved anywhere there's a dropdown combined with a button using the modern UI.

Notes from /duplicate https://github.com/microsoft/microsoft-ui-xaml/issues/178

> This behavior is intentional because the chevron button is smaller than the recommended touch target size and would be too difficult to reliably hit, so touch tap always expands. I'll let adambarlow discuss whether in practice users like this behavior.

> We have been having a few conversations about this and this while we haven't had negative end user feedback yet, we have had feedback from teams utilizing the control that it should work like mouse for touch.

It has not, as yet, been addressed. ☹️
