### ISSUE TITLE
Fixing Open in Terminal shortcut

### ISSUE THREAD

**Issue by snoopiedoom** [microsoft/terminal#14804]
# Description of the new feature/enhancement

Currently, using the Windows right-click context menu option **Open in Terminal** is slow and painful, due to it executing in a new Window, for which I have to face an elevatation prompt. It is simply faster and more practical to copy paste the path from explorer w/ keyboard shortcuts than using the context menu option.
To get most things done on Windows, you need to run applications as elevated processes, which results in a prompt I have to face every time I use the Open in Terminal shortcut. And if it isn't bad enough, idk why, but the Windows work machine I'm using always loses focus off of elevated prompts, so I have to use the mouse to confirm.
I also believe that with the introducion of tabs, there is a bit of purpose in increasing the number of tabs, not windows.

# Proposed technical implementation details (optional)
Haven't gotten around to looking at the code yet.

Using the **Open in Terminal** option in Windows Explorer right-click context menu would open and focus on the tab. Option would be set in Windows Terminal settings.

**Comment by lhecker** [comment]
You can have it attach to an existing window:
![image](https://user-images.githubusercontent.com/2256941/217271259-47bf8521-5c7e-4111-a0c0-0f00db99f575.png)

I'm not sure if it's possible to skip the second elevation prompt. I'm not an expert in that area, but I don't think so, since a unelevated process like explorer wouldn't be able to send a message to elevated Windows Terminal process in the first place, as unelevated processes can't mess with elevated ones in general.

**Comment by snoopiedoom** [comment]
Damn, I can't believe I missed that, my apologies for the late reply, but I didn't want to respond without testing. The option works well, and the elevated prompt makes sense and luckily it doesn't lose focus so my hands can stay on the keyboard, yay 😄
Thanks for the quick work!
