### ISSUE TITLE
Epic: Support non-en-US locales

### ISSUE THREAD

**Issue by Dabraleli** [microsoft/terminal#1484]
# Summary of the new feature/enhancement

I think that any software needs translation on other languages, especially Console which is used very often even by people that are not using it for administrative and programming purposes.
I should admit that English is very common and widely used language, but in not English speaking countries it's sometimes hard to understand what some buttons do.

# Proposed technical implementation details (optional)

I spent some time to look at code and app's resources and I think we can make same files like en-US/Resources.resw for other languages and store all strings there.
I think it's better to implement two ways to select language:

1.  Configuration file parameter "preferredLanguage"
2.  Using system locale/language

As for me I can prepare Russian translation for buttons, labels, hints, etc.
Also I can try to implement feature like this.

**Comment by Dabraleli** [comment]
@DHowett-MSFT, should I try to implement this feature or is it Spec-Needed?

**Comment by DHowett-MSFT** [comment]
@Dabraleli My main concern is that we're not properly set up for resource loading because our project is a frankenstein's monster of win32 and UWP and everything else all together. It's not going to be _easy_, but it doesn't need a spec. If you want to dig into _getting the infrastructure in place_, knock yourself out. I don't know what it looks like to _actually translate_ the project this early in its lifecycle. It may be too early.

**Comment by zadjii-msft** [comment]
Uh, pretty sure we've actually been doing this for a LONG time now. Gonna close this one out, thanks!
