### ISSUE TITLE
Profile with multiple SSH sessions in splitted screens

### ISSUE THREAD

**Issue by dadodasyra** [microsoft/terminal#14841]
### Windows Terminal version

1.16.10262.0 & 1.17.1023

### Windows build number

10.0.22621.0

### Other Software

OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

### Steps to reproduce

1. Open a SSH server on localhost (or replace localhost in the command by your own server IP) and create a SSH key to root
2. Create a profile with a command opening multiple SSH sessions such as 
```
wt -w 0 nt --title Session1 --suppressApplicationTitle ssh -t root@localhost "htop" `; split-pane --title Session2 -s .35 --suppressApplicationTitle ssh -t root@localhost "htop"
```
4. Open this profile

### Expected Behavior

Both terminal should open normally to the "htop" precised command, it was working a week ago~.

### Actual Behavior

Only the last opened SSH session is kept alive, all sessions created before are closed with this error
```
bash: -c: line 1: unexpected EOF while looking for matching ``'
bash: -c: line 2: syntax error: unexpected end of file
Connection to localhost closed.

[processus terminé avec le code 2 (0x00000002)]
Vous pouvez maintenant fermer ce terminal avec Ctrl+D, ou appuyez sur Entrée pour redémarrer.
```
This error is the one in 1.17.1023 and in 1.16.10262.0 you can only see `[processus terminé avec le code 2 (0x00000002)]`

The actual behavior is obtainable by just executing the command in "Steps to reproduce" in a normal cmd or powershell and it works.

In the video below the command in the profile and the command sent in Powershell 7.3.2 is exactly the same

https://user-images.githubusercontent.com/44753923/218478727-56fef992-1f2a-4659-9cdd-aff99724a6e6.mp4

**Comment by zadjii-msft** [comment]
Passing a `wt.exe` commandline as a profile's commandline is certainly unexpected, but it should generally work...

I think part of the trick here is the difference between what happens when you're running that command at the **PowerShell** prompt, vs running that as a `commandline`.

PowerShell uses backtick (``` ` ```) as an escape character, so you're right in using that to help separate the subcommands when you're running that command at the shell. (at roughly 18s in the video)

However, when passing that command as a `commandline`, PowerShell isn't involved in the parsing at all, so the backtick gets passed straight to ssh. That causes ssh to try running essentially ```"htop" `; split-pane --title Session2 -s .35 --suppressApplicationTitle ssh -t root@localhost "htop"```, which is why it gives you the error ```unexpected EOF while looking for matching ``'```.

Instead, I'd try:

```json
"commandline": "wt -w 0 nt --title Session1 --suppressApplicationTitle ssh -t root@localhost \"htop\" ; split-pane --title Session2 -s .35 --suppressApplicationTitle ssh -t root@localhost \"htop\""
```

Does that work/?

**Comment by dadodasyra** [comment]
It seems to work with the backslashes, the thing is that the command that I sent with ` worked pretty well one week ago on both preview & stable terminal versions. That's why I thought it was worth an issue.

**Comment by zadjii-msft** [comment]
Weird, nothing about that should have changed (and I'm _greatly_ surprised it ever worked 😄). Anywho, glad you figured it out!
