### ISSUE TITLE
Solarized-dark color scheme colors are wrong.

### ISSUE THREAD

**Issue by Newbrict** [microsoft/terminal#14887]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1265

### Other Software

Ubuntu 22.04 LTS from the windows store

### Steps to reproduce

Change the color scheme to solarized-dark, type `systemctl status docker` (or any service you have running), see the colors are wrong.

### Expected Behavior

I'm expecting the colors to match the solarized theme.

Look at the settings the the config file:
![image](https://user-images.githubusercontent.com/1683041/220185125-b523188b-e040-4bbd-8d26-c537b87cf9f8.png)
These colors are not bright, see:
![image](https://user-images.githubusercontent.com/1683041/220185142-febaa7fe-6af9-446e-8cd7-3f4b3b7592d2.png)
![image](https://user-images.githubusercontent.com/1683041/220185155-87c7662c-f332-4fc9-97de-7b6d90bd0587.png)
![image](https://user-images.githubusercontent.com/1683041/220185167-b942d2c0-7447-495b-bb9a-1120bd3b465a.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/1683041/220184983-ffaf8910-cf5d-421a-9eae-b26e7055aae1.png)

**Comment by zadjii-msft** [comment]
### [DAYS SINCE I'VE REGRETTED SHIPPING SOLARIZED: ~~35~~ 0](https://github.com/microsoft/terminal/issues/14684#issuecomment-1383951956)


Solarized is just plain a bad terminal theme[^1]. You'll note we're using it [as defined](https://github.com/altercation/solarized#the-values), and yea, the bright colors are all pretty much just grayscale. 

I'd either modify the scheme manually to put the "dark" color values in the bright entries, or just pick a sensible scheme. 

[^1]: I deeply regret including it in the default color schemes list. I just wanted something common that people could recognize as a color scheme to demo how that worked. We never took the time to really re-evaluate if it was a good choice or not before shipping 0.2, and the rest is history.

**Comment by Newbrict** [comment]
Okay, well, for anyone else having this issue, here are actual good settings to use:

```JSON
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#268BD2",
            "brightCyan": "#2AA198",
            "brightGreen": "#859900",
            "brightPurple": "#6C71C4",
            "brightRed": "#DC322F",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#B58900",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
```
![image](https://user-images.githubusercontent.com/1683041/220190051-6ca02d97-f64f-4437-b8a2-acf00d082484.png)


Also, I'm glad you shipped the theme, despite it being weird. Wasn't hard to update it like this.
