### ISSUE TITLE
Windows terminal akward border

### ISSUE THREAD

**Issue by redfer13** [microsoft/terminal#14889]
### Windows build number

Microsoft Windows [Version 10.0.22621.1265]

### Steps to reproduce

None, i think its a default problem?

### Expected Behavior

Even padding along all edges

### Actual Behavior

The padding is uneven across the top and bottom edges which makes it look really ugly.
![image](https://user-images.githubusercontent.com/62601155/220267908-5c407af7-428b-425f-aaf7-51f9c2720b53.png)

**Comment by zadjii-msft** [comment]
That's the space that's reserved for the scroll bar. That's why the right side seems to have more "padding" than the other sides. Neovim might be using the alt buffer, and not need the scrollbar, but it's still there. 

The crux of the issue here is that your neovim scheme uses a different color than the "default background" color, which means you can see the padding in the default BG color around the outside of the actual text viewport. In the past I believe we've called this by design. That's what neovim asked for, so we gave it to them. 

Now, one could maybe do some sort of dumb heuristc to try and fix this. Maybe something with the alt buffer, and recieving a clear screen with a non-default BG color. Maybe something to look in to...

**Comment by lhecker** [comment]
I've been considering to just extend the closest background pixel to the edge of the viewport like so:
![D3D11_TEXTURE_ADDRESS_CLAMP](https://learn.microsoft.com/en-us/windows/win32/direct3d9/images/clamp.png)

**Comment by carlos-zamora** [comment]
Hi @redfer13. Thanks for the feedback. You make a good point. We're actually going to consolidate this with #10422 to track it better.

/dup #10422

**Comment by tom-huntington** [comment]
> I've been considering to just extend the closest background pixel to the edge of the viewport

@lhecker Do you have some work around? The purple ubuntu boarder looks really ugly 

![Image](https://github.com/user-attachments/assets/598be5dc-c953-4bbf-9794-abc85d4e08aa)

**Comment by lhecker** [comment]
Ubuntu installs a so called "fragment" to override the default color scheme for its Windows Terminal profile. To change it
* Open the settings
* Click on the Ubuntu profile
* Click on "Appearance"
* Change the color scheme from "Ubuntu-ColorScheme" to whatever you prefer ("Campbell" is the default).
