### ISSUE TITLE
Active tab rounded corner graphics misaligned/incorrect in the tab row when Windows Display Scale set to 150% (recommended default settings on 14" FHD laptops)

### ISSUE THREAD

**Issue by mullnerz** [microsoft/terminal#14905]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1265

### Steps to reproduce

Set Windows display scale to 150% and open a new Windows Terminal window/tab.

### Expected Behavior

Rounded corners for the active tab in the tab row should be displayed correctly.

### Actual Behavior

Rounded corners displayed incorrectly:
<img width="890" alt="Screenshot 2023-02-24 195700-zoom" src="https://user-images.githubusercontent.com/197506/221268085-971f2899-eab1-4823-8a8c-89affd89ed46.png">
<img width="819" alt="Screenshot 2023-02-24 195317" src="https://user-images.githubusercontent.com/197506/221268097-f7144fda-ed35-4bea-9223-71d2e97edb5b.png">

**Comment by zadjii-msft** [comment]
You know, this was reported before in https://github.com/microsoft/terminal/issues/13725#issuecomment-1301192938 but we never promoted it to a full issue. We should figure this out!

I bet this is due to the wacky way we're setting resources on the TabViewItems, though. Might need a fix in TabView itself. No way to know without deeper investigation.

**Comment by zadjii-msft** [comment]
Looks like this was fixed in #15708, in MUX 2.8. Neat!
