### ISSUE TITLE
Find window's process in Process Explorer doesn't locate the active tab process for Windows Terminal

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/terminal#14902]
### Steps to reproduce

Launch Process Explorer from https://live.sysinternals.com/procexp.exe, go to toolbar and drag the "Find Window's Process (drag over window)" over a Windows terminal window.

### Expected Behavior

The current shell/process for the active active tab under WindowsTerminal.exe should be highlighted in Process Explorer. 

### Actual Behavior

The WindowsTerminal.exe process is highlighted in Process Explorer.

I understand it could be that WindowsTerminal.exe owns the window which is shared by all the tabs, but making this work could be helpful to locate the processes in the current tab through Process Explorer, or I need go though all the child processes to find it out.

**Comment by zadjii-msft** [comment]
Yea, I think I'm gonna have to call this by-design.

I'm not sure we can associate the individual client processes with the top-level Terminal HWND. I also don't know if it'd be possible to "dissociate" them when the tab that's hosting them becomes inactive. We'd need to do that so that _only_ the active tab's client apps showed up, but even then, you could have multiple panes per tab... It's just not something I think we'll ever be able to truly support. 

Furthermore, I'm about to make this _even worse_ in #14843. I'm about to make _all_ the windows owned by a single process. So you'd only ever get the root WindowsTerminal.exe, regardless of which HWND you examined.
