### ISSUE TITLE
Cmd issue

### ISSUE THREAD

**Issue by CODE-A-DUCK** [microsoft/terminal#14937]
Some error when I open terminal
**[error 2147942402 (0x80070002) when launching `%SystemRoot%\System32\cmd.exe']**

I have changed enviroment(path) but it still not working on me

**Comment by zadjii-msft** [comment]
That error code is `ERROR_FILE_NOT_FOUND`, though, it's weird to me that it's displaying `%SystemRoot%` literally, not expanded. Is that environment variable configured correctly? 

Does CMD.exe work from the run dialog / start menu? Does any other shell work/?

If you change the `commandline` in the settings to `C:\windows\system32\cmd.exe` (instead of `%SystemRoot%\System32\cmd.exe`), does it work?

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!
