### ISSUE TITLE
Feature Request: PuTTY style text selection

### ISSUE THREAD

**Issue by lancenz** [microsoft/terminal#1496]
Please, please (please!) add a setting to enable PuTTY style text selection behavior in the new terminal.

1. Randomly left clicking on a terminal should not select 1 character, it should just focus (or keep focus if already focused) the window. Nowhere in windows other than terminal does clicking select a character. This is really annoying in multi-monitor scenarios when you are unsure if a window is focused and you click in and it selects a character...

2. Selecting text with your mouse should automatically copy to the clipboard onmouseup, there are not many scenarios when selecting text in a terminal does not result in copying to the clipboard so it is weird to have to right-click on press enter to copy.

3. Selected text should automatically be deselected when the clipboard changes, quite helpful to visually see that the selected text is no longer in the clipboard. Surprisingly useful.

4.  Right click should always be paste (not copy!), regardless of if text is currently selected or not. Very annoying, especially with the first issue, if you select a window which was already focused a character is selected, then right clicking to paste ends up copying the selected character.. grr! 

5. Selection should not be lost when typing in the terminal, if you select some text then type a command, it is helpful for the selection to remain selected. This way you know what is in the clipboard (if the 3rd suggestion is implemented).

Please, please, please implement these, thanks! :)

**Comment by 0xabu** [comment]
There's a lot of overlap with #524 here. I personally agree with all of it except point 4 (I prefer middle click paste). From discussion on #524 is looks like they're headed towards configurable mouse button mappings, so rather than a single "putty-style" option I would suggest that:

 1. I agree unconditionally; this seems likely just a bug.
 2. Copy-on-select should be an option
 3. I agree; this makes sense when tied to the same copy-on-select option IMO -- if the selection represents the clipboard, then it makes sense to clear it if the clipboard changes
 4. Personally I prefer middle-click paste, right-click context menu. I think that's a mouse button mapping option.
 5. I agree, unconditionally. I suspect the current behaviour stems from legacy conhost which clears the selection when you start typing, but it makes a bit more sense there, because in conhost selecting also suspends new output.

So I'd propose that rather than "putty-style" we have two options: a mouse-binding for what happens when you middle/right-click, and a "copy-on-select" option that enables 2, 3, and maybe 5 above. This is also close to the way these options are broken out in mintty.

**Comment by TCB13** [comment]
This is non-sense. Every terminal app out there supports basic copy on select.

**Comment by DHowett-MSFT** [comment]
> The new Windows Terminal is non-sense

Cool. If you don't have anything nice to say, don't come to our repository to say mean things about us.

I'm moving the rest of the content of this issue to 524.
