### ISSUE TITLE
Open In Terminal feature does not open specific folder.

### ISSUE THREAD

**Issue by GarThor** [microsoft/terminal#14962]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19042.0

### Other Software

PowerShell v5

Side Note: I have a PowerShell profile set up that sets the default location for where PowerShell should start, using the "Set-Location" cmdlet.  The "open PowerShell window here" context menu feature seems to bypass that "Set-Location" which is what is desired in this scenario.

### Steps to reproduce

1) right-click folder
2) select open-in-terminal
3) Terminal opens, but not in the directory selected

### Expected Behavior

Terminal opens in selected directory, the same as if I had pressed shift-rightclick->open powershell window here

### Actual Behavior

Terminal opens in default directory (set in PowerShell profile, using the "Set-Location" cmdlet)

**Comment by DHowett** [comment]
So, this is an interesting case study in how Terminal's "disavowing" of any shell knowledge makes this not work too well.

PowerShell's built-in "open in powershell" shell extension launches `powershell ... -c set-location c:\foo\bar`. That command runs after the profile.

Terminal can't promote the starting directory to an after-the-profile `Set-Location` because it doesn't _actually know_, to any meaningful extent, that it is launching something that looks like PowerShell.

**Comment by GarThor** [comment]
Yep, pretty much @zadjii-msft.  There's some documentation on how powershell profiles work here: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1

Interesting @DHowett ... I wonder if there's a workaround I can implement in my profile script, where it detects if it's running within the terminal application rather than standalone?

**Comment by GarThor** [comment]
I think I've come up with a reasonable workaround.

To my powershell configuration in the terminal app, I've added the following command line params to tell it specifically to _not_ load any profiles at all, and then execute a specific script, which does everything that my normal profile does, excpet setting the directory.

<path-to-powershell>\powershell.exe -noprofile -noexit -file "<path-to-terminal-specific-profile>\terminal_profile.ps1"

**Comment by DHowett** [comment]
I think that's an acceptable workaround. The problem is, I don't think we can fix it out-of-the-box. Having a profile that always modifies inherited state (like the location! but also the console window size and a couple other bits) isn't tenable in the long run.

There is a category of (poorly-authored) build scripts that forget to pass `-NoProfile` when they shell out to PowerShell to do something; there are also applications that spawn PowerShell as a subshell to do something that also don't pass `-NoProfile`. I have a debug print in my own profile, and it shows up in the strangest places. Each of those things is utterly unprepared for state pollution.

The problem is, there are way more of those than there are instances of your profile in existence. :smile:

**Comment by GarThor** [comment]
That workaround didn't really work either... so I added an if-then clause... if it starts up in the regular working directory it switches to the one I define... otherwise it goes with whatever directory I selected in explorer.

I also had to add a clause in my profile to refresh environment variables, because apparently that doesn't happen on new tab either, but that's a separate issue.
