### ISSUE TITLE
Allow to customize (lower) the priotity of the main process being spawn by each profile (cmd.exe, powershell.exe, ...)

### ISSUE THREAD

**Issue by aurelienrb** [microsoft/terminal#15004]
# Description of the new feature/enhancement

Hello,

I do a lot of C++ project compilation in command line, and by default this tends to make my system quite slow and unresponsive because all CPUs are used to build source code.

So what I manually do each time I open a new Terminal to be used for a built is to lower its priority (from "Normal" to "Below Normal"). This way I can building code in the background while still working on something else.

![image](https://user-images.githubusercontent.com/8517069/225698590-1ce113ce-eb4f-45d1-9fb8-90cfbfd5d92b.png)

It would be great to a have a profile setting that allows to customize / decrease the priority level of the spawned command prompt so that I don't have to manually do on each launch. 😍 

# Proposed technical implementation details

Add a config setting at the profile level that allows to specify the process priority as supported by Windows
https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass

**Comment by lhecker** [comment]
I'm not against this, and it does seem like a nice feature, but I feel like it might be a little bit too niche to implement it right away. (I'm not sure if the others on the team would agree with my assesment.)

For PowerShell you could easily do this already by creating a separate profile that runs this command on start:
```pwsh
[System.Diagnostics.Process]::GetCurrentProcess().PriorityClass = [System.Diagnostics.ProcessPriorityClass]::BelowNormal
```

For cmd.exe I don't have an immediate solution since its scripting language is severily limited and I don't know it well. But you could create a shortcut with this command which will launch Windows Terminal with a below-normal priority:
```
cmd.exe /C start "" /BELOWNORMAL wt.exe
```

**Comment by carlos-zamora** [comment]
@aurelienrb does Leonard's workaround work for you? As a workaround, you can also use this in a profile like this:
```js
{
   "name": "Low Priority Powershell",
   "commandline": "cmd /s /c start /b /low powershell.exe",
}
```

**Comment by zadjii-msft** [comment]
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!
