### ISSUE TITLE
COOKED_READ (cmd.exe) doesn't properly support emoji input

### ISSUE THREAD

**Issue by peter-bertok** [microsoft/terminal#1503]
# Environment

```none
Windows build number: 1903
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce
Paste text containing complex Unicode characters such as emoji into a PowerShell tab as a string literal.
Emoji will be displayed as "??" placeholders, but then display correctly when the literal is "output" by pressing enter.

# Expected behavior

Unicode characters such as Emoji should be consistently displayed, including in string literals, input text, command-line arguments, etc...

# Actual behavior

Inconsistent display:

![Screenshot](https://user-images.githubusercontent.com/14988123/59984055-60b94d80-9669-11e9-9d48-bc4a8ed85e9b.png)

**Comment by DHowett-MSFT** [comment]
This one is fascinating. I spy two bugs here. One is with the emoji input (this could just be PSReadline's fault), and the other is that some emoji are _still_ too tiny!

**Comment by Shorotshishir** [comment]
dumping any of the two files in the terminal doesn't render any data properly. these two files ocntails all the emojis that windows provide.

- [emoji.txt](https://drive.google.com/open?id=1QjnGdp_mA6v8M30ZGj52Vn2bb3_Y-fmk)
- [emoji.docx](https://drive.google.com/open?id=1C--OnOKwHzCdAczeFy-PjRG4gpGnB22D)

**CMD**:
use `more` or `type` to dump content into the terminal. 
shows garbage text, but _doesn't crash_

**PowerShell**
use `get-content` to dump the data into the terminal
_nothing shows , hangs the terminal app and crashes_

**WSL**
use `cat` to dump the content into the terminal
_nothing shows, hangs the terminal app and crashes_

**N.B.  -->  Crash doesn't terminate terminal app**

**Comment by davidhewitt** [comment]
Pasting emoji input is also an issue with `cmd`. In the screenshot below, I paste a string of smileys in, but they come out as invalid glyphs.

Hitting `enter` and `up` displays the correct input string though, so it _is_ making it into the console buffer correctly.

![image](https://user-images.githubusercontent.com/1939362/71823514-4f78e100-308f-11ea-9241-061d48f30d16.png)

**Comment by zadjii-msft** [comment]
For me later:

<details>
<summary>Emoji.txt</summary>

😁😁😂🤣😃😄😅😆😉😊😋😎😍😘🥰😗😙😚☺🙂🤗🤩🤔🤨😐😑😶🙄😏😣😥😮🤐😯😪😫🥱😴😌😛😜😝🤤😒😓😔😕🙃🤑😲☹🙁😖😞😟😤😢😭😦😧😨😩🤯😬😰😱🥵🥶😳🤪😵🥴😠😡🤬😷🤒🤕🤢🤮🤧😇🥳🥺🤠🤡🤥🤫🤭🧐🤓😈👿👹👺💀☠👻👽👾🤖💩😺😸😹😻😼😽🙀😿😾🐱‍👤🐱‍🏍🐱‍💻🐱‍🐉🐱‍👓🐱‍🚀🙈🙉🙊🐵🐶🐺🐱🦁🐯🦒🦊🦝🐮🐷🐗🐭🐹🐰🐻🐨🐼🐸🦓🐴🦄🐔🐲🐽🐾🐒🦍🦧🦮🐕‍🦺🐩🐕🐈🐅🐆🐎🦌🦏🦛🐂🐃🐄🐖🐏🐑🐐🐪🐫🦙🦘🦥🦨🦡🐘🐁🐀🦔🐇🐿🦎🐊🐢🐍🐉🦕🦖🦦🦈🐬🐳🐋🐟🐠🐡🦐🦑🐙🦞🦀🐚🦆🐓🦃🦅🕊🦢🦜🦩🦚🦉🐦🐧🐥🐤🐣🦇🦋🐌🐛🦟🦗🐜🐝🐞🦂🕷🕸🦠🧞‍♀️🧞‍♂️🗣👤👥👁👀🦴🦷👅👄🧠🦾🦿👣🤺⛷🤼‍♂️🤼‍♀️👯‍♂️👯‍♀️💑👩‍❤️‍👩👨‍❤️‍👨💏👩‍❤️‍💋‍👩👨‍❤️‍💋‍👨👪👨‍👩‍👦👨‍👩‍👧👨‍👩‍👧‍👦👨‍👩‍👦‍👦👨‍👩‍👧‍👧👨‍👨‍👦👨‍👨‍👧👨‍👨‍👧‍👦👨‍👨‍👦‍👦👨‍👨‍👧‍👧👩‍👩‍👦👩‍👩‍👧👩‍👩‍👧‍👦👩‍👩‍👦‍👦👩‍👩‍👧‍👧👩‍👦👩‍👧👩‍👧‍👦👩‍👦‍👦👩‍👧‍👧👨‍👦👨‍👧👨‍👧‍👦👨‍👦‍👦👨‍👧‍👧👭👩🏻‍🤝‍👩🏻👩🏼‍🤝‍👩🏻👩🏼‍🤝‍👩🏼👩🏽‍🤝‍👩🏻👩🏽‍🤝‍👩🏼👩🏽‍🤝‍👩🏽👩🏾‍🤝‍👩🏻👩🏾‍🤝‍👩🏼👩🏾‍🤝‍👩🏽👩🏾‍🤝‍👩🏾👩🏿‍🤝‍👩🏻👩🏿‍🤝‍👩🏼👩🏿‍🤝‍👩🏽👩🏿‍🤝‍👩🏾👩🏿‍🤝‍👩🏿👫👩🏻‍🤝‍🧑🏻👩🏻‍🤝‍🧑🏼👩🏻‍🤝‍🧑🏽👩🏻‍🤝‍🧑🏾👩🏻‍🤝‍🧑🏿👩🏼‍🤝‍🧑🏻👩🏼‍🤝‍🧑🏼👩🏼‍🤝‍🧑🏽👩🏼‍🤝‍🧑🏾👩🏼‍🤝‍🧑🏿👩🏽‍🤝‍🧑🏻👩🏽‍🤝‍🧑🏼👩🏽‍🤝‍🧑🏽👩🏽‍🤝‍🧑🏾👩🏽‍🤝‍🧑🏿👩🏾‍🤝‍🧑🏻👩🏾‍🤝‍🧑🏼👩🏾‍🤝‍🧑🏽👩🏾‍🤝‍🧑🏾👩🏾‍🤝‍🧑🏿👩🏿‍🤝‍🧑🏻👩🏿‍🤝‍🧑🏼👩🏿‍🤝‍🧑🏽👩🏿‍🤝‍🧑🏾👩🏿‍🤝‍🧑🏿👬👨🏻‍🤝‍👨🏻👨🏼‍🤝‍👨🏻👨🏼‍🤝‍👨🏼👨🏽‍🤝‍👨🏻👨🏽‍🤝‍👨🏼👨🏽‍🤝‍👨🏽👨🏾‍🤝‍👨🏻👨🏾‍🤝‍👨🏼👨🏾‍🤝‍👨🏽👨🏾‍🤝‍👨🏾👨🏿‍🤝‍👨🏻👨🏿‍🤝‍👨🏼👨🏿‍🤝‍👨🏽👨🏿‍🤝‍👨🏾👨🏿‍🤝‍👨🏿👨🏿‍🤝‍👨
👩👨🧑👧👦🧒👶👵👴🧓👩‍🦰👨‍🦰👩‍🦱👨‍🦱👩‍🦲👨‍🦲👩‍🦳👨‍🦳👱‍♀️👱‍♂️👸🤴👳‍♀️👳‍♂️👲🧔👼🤶🎅👮‍♀️👮‍♂️🕵️‍♀️🕵️‍♂️💂‍♀️💂‍♂️👷‍♀️👷‍♂️👩‍⚕️👨‍⚕️👩‍🎓👨‍🎓👩‍🏫👨‍🏫👩‍⚖️👨‍⚖️👩‍🌾👨‍🌾👩‍🍳👨‍🍳👩‍🔧👨‍🔧👩‍🏭👨‍🏭👩‍💼👨‍💼👩‍🔬👨‍🔬👩‍💻👨‍💻👩‍🎤👨‍🎤👩‍🎨👨‍🎨👩‍✈️👨‍✈️👩‍🚀👨‍🚀👩‍🚒👨‍🚒🧕👰🤵🤱🤰🦸‍♀️🦸‍♂️🦹‍♀️🦹‍♂️🧙‍♀️🧙‍♂️🧚‍♀️🧚‍♂️🧛‍♀️🧛‍♂️🧜‍♀️🧜‍♂️🧝‍♀️🧝‍♂️🧟‍♀️🧟‍♂️🙍‍♀️🙍‍♂️🙎‍♀️🙎‍♂️🙅‍♀️🙅‍♂️🙆‍♀️🙆‍♂️🧏‍♀️🧏‍♂️💁‍♀️💁‍♂️🙋‍♀️🙋‍♂️🙇‍♀️🙇‍♂️🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️💆‍♀️💆‍♂️💇‍♀️💇‍♂️🧖‍♀️🧖‍♂️🤹‍♀️🤹‍♂️👩‍🦽👨‍🦽👩‍🦼👨‍🦼👩‍🦯👨‍🦯🧎‍♀️🧎‍♂️🧍‍♀️🧍‍♂️🚶‍♀️🚶‍♂️🏃‍♀️🏃‍♂️💃🕺🧗‍♀️🧗‍♂️🧘‍♀️🧘‍♂️🛀🛌🕴🏇🏂🏌️‍♀️🏌️‍♂️🏄‍♀️🏄‍♂️🚣‍♀️🚣‍♂️🏊‍♀️🏊‍♂️🤽‍♀️🤽‍♂️🤾‍♀️🤾‍♂️⛹️‍♀️⛹️‍♂️🏋️‍♀️🏋️‍♂️🚴‍♀️🚴‍♂️🚵‍♀️🚵‍♂️🤸‍♀️🤸‍♂️🤳💪🦵🦶👂🦻👃🤏👈👉☝👆👇✌🤞🖖🤘🤙🖐✋👌👍👎✊👊🤛🤜🤚👋🤟✍👏👐🙌🤲🙏🤝💅
🎈🎆🎇🧨✨🎉🎊🎃🎄🎋🎍🎎🎏🎐🎑🧧🎀🎁🎗🎞🎟🎫🎠🎡🎢🎪🎭🖼🎨🧵🧶🛒👓🕶🦺🥽🥼🧥👔👕👖🩳🧣🧤🧦👗🥻👘👚🩲🩱👙👛👜👝🛍🎒👞👟🥾🥿👠👡👢🩰👑🧢⛑👒🎩🎓💋💄💍💎⚽⚾🥎🏀🏐🏈🏉🎱🎳🥌⛳⛸🎣🤿🎽🛶🎿🛷🥅🏒🥍🏏🏑🏓🏸🎾🥏🪁🎯🥊🥋🥇🥈🥉🏅🎖🏆🎮🕹🎰🎲🔮🧿🧩🧸🪀🎴🃏🀄♟♠♣♥♦🔈🔉🔊📢📣🔔🎼🎵🎶🎙🎤🎚🎛🎧📯🥁🎷🎺🎸🪕🎻🎹📻🔒🔓🔏🔐🔑🗝🪓🔨⛏⚒🛠🔧🔩🧱⚙🗜🛢⚗🧪🧫🧬🩺💉🩸🩹💊🔬🔭⚖📿🔗⛓🧰🧲🦯🛡🏹🗡⚔🔪💣🔫☎📞📟📠📱📲📳📴🚬⚰⚱🗿🔋🔌💻🖥🖨⌨🖱🖲💽💾💿📀🧮🎥🎬📽📡📺📷📸📹📼🔍🔎🕯🪔💡🔦🏮📔📕📖📗📘📙📚📓📒📃📜📄📑📰🗞🔖🏷💰💴💵💶💷💸💳🧾🏧✉📧📨📩📤📥📦📫📪📬📭📮🗳✏✒🖋🖊🖌🖍📝🗒💼📁📂🗂📅📆🗓📇📈📉📊📋📌📍📎🖇📏📐✂🗃🗄🗑⌛⏳⌚⏰⏱⏲🕰
🍕🍔🍟🌭🍿🧂🥓🥚🍳🧇🥞🧈🍞🥐🥨🥯🥖🧀🥗🥙🥪🌮🌯🥫🍖🍗🥩🍠🥟🥠🥡🍱🍘🍙🍚🍛🍜🦪🍣🍤🍥🥮🍢🧆🥘🍲🍝🥣🥧🍦🍧🍨🍩🍪🎂🍰🧁🍫🍬🍭🍡🍮🍯🍼🥛🧃☕🍵🧉🍶🍾🍷🍸🍹🍺🍻🥂🥃🧊🥤🥢🍽🍴🥄🏺🥝🥥🍇🍈🍉🍊🍋🍌🍍🥭🍎🍏🍐🍑🍒🍓🍅🍆🌽🌶🍄🥑🥒🥬🥦🥔🧄🧅🥕🌰🥜💐🌸🏵🌹🌺🌻🌼🌷🥀☘🌱🌲🌳🌴🌵🌾🌿🍀🍁🍂🍃
🚗🚓🚕🛺🚙🚌🚐🚎🚑🚒🚚🚛🚜🚘🚔🚖🚍🦽🦼🛹🚲🛴🛵🏍🏎🚄🚅🚈🚝🚞🚃🚋🚆🚉🚊🚇🚟🚠🚡🚂🛩🪂✈🛫🛬💺🚁🚀🛸🛰⛵🚤🛥⛴🛳🚢⚓🚏⛽🚨🚥🚦🚧🏁🏳‍🌈🏳🏴🏴‍☠️🚩🌌🪐🌍🌎🌏🗺🧭🏔⛰🌋🗻🛤🏕🏞🛣🏖🏜🏝🏟🏛🏗🏘🏙🏚🏠🏡⛪🕋🕌🛕🕍⛩🏢🏣🏤🏥🏦🏨🏩🏪🏫🏬🏭🏯🏰💒🗼🌉🗽🗾🎌⛲⛺🌁🌃🌄🌅🌆🌇♨💈🛎🧳🪑🚪🛏🛋🚽🧻🚿🛁🧼🧽🧴🪒🧷🧹🧺🧯☁⛅⛈🌤🌥🌦🌧🌨🌩🌪🌫🌝🌑🌒🌓🌔🌕🌖🌗🌘🌙🌚🌛🌜☀🌞⭐🌟🌠☄🌡🌬🌀🌈🌂☂☔⛱⚡❄☃⛄🔥💧🌊
❤🧡💛💚💙💜🤎🖤🤍💔❣💕💞💓💗💖💘💝💟💌💢💥💤💦💨💫🕳☮✝☪🕉☸✡🔯🕎☯☦🛐⛎♈♉♊♋♌♍♎♏♐♑♒♓🆔⚕♾⚛🈳🈹🈶🈚🈸🈺🈷✴🆚🉑💮🉐㊙㊗🈴🈵🈲🚼🅰🅱🆎🆑🅾🆘⛔🛑📛❌⭕🚫🔇🔕🚭🚷🚯🚳🚱🔞📵❗❕❓❔‼⁉💯🔅🔆🔱⚜〽☢☣⚠🚸🔰♻🈯💹❇✳❎✅💠🌐Ⓜ🈂➿🛂🛃🛄🛅♿🚾🅿🚰🚹🚺🚻🚮📶🈁🆖🆗🆙🆒🆕🆓#️⃣*️⃣0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣🔟🔢▶⏸⏯⏹⏺⏭⏮⏩⏪🔀🔁🔂◀🔼⏫🔽⏬⏏🎦➡⬅⬆⬇↗↘↙↖↕↔🔄↪↩⤴⤵ℹ🔤🔡🔠🔣🔃🔛🔝🔜☑🔚🔙〰➰✔💲💱➕➖✖➗©®™🔘🔴🟠🟡🟢🔵🟣🟤⚫⚪🟥🟧🟨🟩🟦🟪🟫⬛⬜◼◻◾◽▪▫🔶🔸🔷🔹🔺🔻🔲🔳💭🗯💬🗨👁‍🗨🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛🕜🕝🕞🕟🕠🕡🕢🕣🕤🕥🕦🕧


;-)¯\_(ツ)_/¯( •_•)>⌐■-■(⌐■_■):-P:-((•_•)( ´･･)ﾉ(._.`)༼ つ ◕_◕ ༽つ(ˉ﹃ˉ)(╯°□°）╯︵ ┻━┻ಠ_ಠಥ_ಥ:-Dᓚᘏᗢ(┬┬﹏┬┬)^_^:-)(^///^)╰(*°▽°*)╯☆*: .｡. o(≧▽≦)o .｡.:*☆(*/ω＼*)(●'◡'●)(❁´◡`❁)(☞ﾟヮﾟ)☞☜(ﾟヮﾟ☜)(¬‿¬)(¬_¬ )(T_T)(⊙_⊙;)


😁 is ["\uD83D\uDE01"](https://www.fileformat.info/info/unicode/char/1f601/index.htm), or 0n55357, 0n56833 

</details>

```c++
OutputCellView OutputCellIterator::s_GenerateView(const std::wstring_view view,
                                                  const TextAttribute attr,
                                                  const TextAttributeBehavior behavior)
{
    const auto glyph = Utf16Parser::ParseNext(view);
    DbcsAttribute dbcsAttr;
    if (IsGlyphFullWidth(glyph))
    {
        dbcsAttr.SetLeading();
    }

    return OutputCellView(glyph, dbcsAttr, attr, behavior);
}
```

As the two `wchar_t`s get written to the buffer by `WriteCharsLegacy`, we create an `OutputCellIterator` to write each half of the emoji. Unfortunately, we write each half one char at a time. `Utf16Parser::ParseNext` doesn't like that. It knows the first `wchar_t` is a leading byte, but can also tell there's no trailing byte, so it just returns a Replacement char.

The character does end up getting inserted into the cooked read data correctly, which is why hitting enter to submit the commandline in `cmd` works just fine. The data in the cooked read data is correct, but the text buffer has the wrong data.

Presumably, the cooked read is just writing the text buffer wrong. `COOKED_READ_DATA::ProcessInput` can only handle one `wchar_t` at a time.

When you use the emoji picker to input the character, it first comes through `ConversionAreaInfo::WriteText` straight to `_screenBuffer->Write` to draw the composition buffer. Then, once the dialog is dismissed, the keys get sent to the input buffer in `ConsoleImeInfo::_InsertConvertedString`, where again the cooked read gets them one char at a time to display broken in the buffer.
