### ISSUE TITLE
Bug Report - Transparency lost when out of focus.

### ISSUE THREAD

**Issue by callumvh** [microsoft/terminal#1505]
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
Windows Terminal 0.2.1715.0
```

# Steps to reproduce

1. Enable acrylic on a profile such as cmd or ubuntu
2. Click on terminal window, the window becomes transparent.
3. Click on a different window, the window loses the transparency.

# Expected behavior

The terminal window should remain transparent

# Actual behavior

Terminal loses transparency when out of focus.

**Comment by brunovieira97** [comment]
AFAIK, that's something specific to Windows's Acrylic Blur, works like that on all apps.

**Comment by DHowett-MSFT** [comment]
Yep, this is by design for Windows acrylic.

**Comment by JamieCorkhill** [comment]
Do you know if it's possible (or is there any workaround) to maintain the opacity whether the terminal is focused or not? The open-source terminal Terminus does this, for instance.

I don't really understand why you'd want to have the terminal revert to fully opaque when not in focus since it would be an extremely common use-case to wish to be able to see behind the terminal window on another monitor when working in a separate program/browser/IDE.

Thanks.

**Comment by voronin-de** [comment]
This is really a bummer. Windows Terminal is such a great appliaction and is very appealing in terms of visuals, but the fact, that it cannot at least keep the opacity (or even change it) on lost focus, makes it less appealing in comparison to e.g. the Git Bash. Yeah, it can handle much more and it really looks great, but even if we are not allowed to keep acrylic look (due to some Microsoft policies or whatever), I'd at least would want to be able to set the opacity.

Sadly I am no good at Windows Programming, but to my knowledge (back when I used XAML and WinForms for appearance), it was pretty easy to change a forms opacity.

I mean .. Windows Terminal is beautiful as long as it has focus, but becomes simply ugly when it loses it.

**Comment by samurusov** [comment]
This issue should be fixed.
