### ISSUE TITLE
Can conhost be prevented from scrolling to bottom when new input is received

### ISSUE THREAD

**Issue by clinton-r** [microsoft/terminal#15059]
# Description of the new feature/enhancement
I really like that I can scroll up in Windows Terminal, and it won't snap back down to the bottom when new output is written.  Is there a way to trick conhost into behaving the same way?  If not, I suggest adding that feature to conhost.
I'm asking because when developing with CodeBlocks, it launches the code in conhost/cmd.exe and (AFAIK) doesn't allow choosing to use Windows Terminal instead.
#6062 is related

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Hmm, I don't know if this is something we'd be able to bring back to conhost. We're largely not bringing "UX" features back to it, and I'm also sure this would somehow break an oil rig somehow 😝 

BUT

On Windows 11, where the "Default Terminal" feature is available, then CodeBlocks _should_ launch into a Terminal window instead of a conhost one. Does that seem acceptable?

**Comment by clinton-r** [comment]
Fair enough.  I'm still on Windows 10 for now, but will upgrade eventually...
Thanks for the quick response!
