### ISSUE TITLE
Improve glyph spacing for serif fonts

### ISSUE THREAD

**Issue by SharpBritannia** [microsoft/terminal#15181]
# Description of the new feature/enhancement

I know that this may sound psychopathic to most developers but I'd like to use a font like Times New Roman or Garamond for my console. I use Cmder/ConEmu as well which does render these fonts just fine so please fix this:

<img width="594" alt="Capture" src="https://user-images.githubusercontent.com/20170702/231964138-80e3a08a-8ef1-4f96-835d-a833a10fb14e.PNG">

Here is Cmder:
![image](https://user-images.githubusercontent.com/20170702/231965455-750d20a8-174b-49e0-badd-0ee746764ee4.png)

**Comment by lhecker** [comment]
Would text rendering like this already be fine for you:
![image](https://user-images.githubusercontent.com/2256941/232035760-0583e651-0204-4fed-bf36-5baa2f726096.png)

Or do you specifically want to have proportional text rendering like in Cmder?

**Comment by SharpBritannia** [comment]
That certainly looks more consistent and I'd appreciate it but I kind of expected an advanced terminal such as Windows Terminal to be able to beat Notepad in rendering text.

**Comment by lhecker** [comment]
> but I kind of expected an advanced terminal such as Windows Terminal to be able to beat Notepad in rendering text.

I‘m open to improving our support for proportional fonts, but I don’t understand what you’re trying to say here. The first half of your response sounds like improving the spacing would be enough, but the second half (the one after "but") sounds like it isn’t? In what other way would you like us to beat Notepad besides making the spacing more consistent? I don’t mean to be rude, but could you please be more precise in your feature request(s)? Otherwise I‘ll repurpose this feature request as one just asking for us to improve the spacing of proportional fonts, if that’s fine, because from a technical standpoint I don’t think we‘ll support full proportional rendering the way Cmder does it soon, due to the unclarity around cell-wise background coloring.

**Comment by SharpBritannia** [comment]
Well yes; I would like fully proportional rendering. But since that'd be diffucult, fixing the spacing would do for now. Thank you in advance.

**Comment by j4james** [comment]
See also #13389.

**Comment by DHowett** [comment]
Proper support for proportional fonts _in a primarily monospaced ecosystem_ should not be prioritized over any other requests. That's honestly probably the _last_ thing we should work on. :smile:

**Comment by DHowett** [comment]
After a discussion with the team, we're feeling pretty ready to close this out. I appreciate that some folks want to use proportional fonts, but right now it's not in plan for our engineering team and we don't have the capacity to review a community pull request that adds support for them.

We may make improvements to how they're displayed in the future, but we'll probably never commit to being as competent at it as Word or Notepad or richedit... or even cmder.

FWIW: How does cmder handle midnight commander? o_O

I'd be worried it turns out like this:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/189190/234708404-1b0b731d-cd6f-4661-b081-e96c5f89ea18.png">
