### ISSUE TITLE
Terminal blinks once when getting focus with AtlasEngine on

### ISSUE THREAD

**Issue by Avi0** [microsoft/terminal#15248]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1555

### Steps to reproduce

1. Enable AtlasEngine.
2. Open a terminal tab.
3. Do something away from this tab for a while (in other tabs or not in Terminal).
4. Focus the tab opened in step 2.

It's not clear exactly what needs to be done in step 3. Maybe actively do something with a system, maybe just wait. In practice, when I'm focusing a tab after it's been idle for an hour or two, it blinks when getting focus.

### Expected Behavior

Terminal does not blink.

### Actual Behavior

Terminal blinks once (maybe it redraws everything)?

**Comment by lhecker** [comment]
Can you try to run any elevated (admin) application in step 3? Like, let's say, open `regedit` from the start menu? I'm pretty sure it'll "blink" afterwards.

Generally speaking, however I'm pretty sure that I know what you're talking about, and that issue got fixed in #14959 and so I'll close this issue for now. 🙂
This line fixes it: https://github.com/microsoft/terminal/blob/4d5962e7b5b3bedcc4f52c0950510b9d9841fcec/src/renderer/atlas/AtlasEngine.r.cpp#L147

**Comment by Avi0** [comment]
@lhecker, yes, it does blink after opening any elevated application. Thanks for the explanation and for the fix.
