### ISSUE TITLE
Hibernating causes active pane to hang

### ISSUE THREAD

**Issue by Vampire** [microsoft/terminal#15301]
# Description of the new feature/enhancement

In ConEmu there was an action and shortcut to restart a tab, also with the option to restart as administrator.
It would be nice if WT would have the same.
For example I right now was not able to input anything in one of the tabs.
Actually, even closing the whole Terminal and starting it again even made it worse.
Besides that all the Tab titles were not remembered, the tab in question also just does not start any process it seems.
It just sits there with a blinking caret, doing nothing.

**Comment by zadjii-msft** [comment]
Alright, so there's like, a bunch of parts to this thread. Lemme try and untangle this:


* In ConEmu there was an action and shortcut to restart a tab, 
  - This was tracked by #3726, which just merged, and will be in 1.18
* also with the option to restart as administrator.
  - Well, this we can't do in the same window (for reasons discussed elsewhere on the repo), but you can always ctrl+click on a profile in the new tab dropdown to open it in an elevated window. There's also #12985, #4459, and #14517 which are all QoL improvements in this area. 
* For example I right now was not able to input anything in one of the tabs ... the tab in question also just does not start any process it seems ... It just sits there with a blinking caret, doing nothing.
  - That's certainly very unexpected! What were you trying to run in that tab/? (also what version of the Terminal are you on?) 
* all the Tab titles were not remembered, 
  - That's something that should work if you enabled `"firstWindowPreference": "persistedWindowLayout",` in the settings - did you have that setting enabled?
  
I'm gonna try and pivot this thread to track just the 3rd bullet point, since the rest are all things the Terminal can already do (or are already tracked elsewhere)

**Comment by Vampire** [comment]
Sorry that I overloaded this report obviously. :-(

re 1) I searched for it, but probably missed to include the closed ones, sorry.

re 2) well, I guess I have to accept the "reasons", whatever they may be. :-D It was just super handy, but I can live without it.

re 3)
> That's certainly very unexpected! What were you trying to run in that tab/?

Nothing specifically.
It was running a Git Bash instance from Git for Windows.
I used it all day long quite fine.
I don't remember right now what the last command was, probably some Git or Gradle call.
Then I sent the laptop to hibernate mode to go from work to home
At home I unlocked the box and tried to type a command in the terminal, but nothing happened.
The other tabs still worked without a problem.

> (also what version of the Terminal are you on?)

1.16.10261.0

>> all the Tab titles were not remembered,
>
>That's something that should work if you enabled "firstWindowPreference": "persistedWindowLayout", in the settings - did you have that setting enabled?

Yes, that setting is enabled.
The tabs were restored just fine.
Just the tab titles were all the default again (which is different from the Profile name if that is relevant).
After I've seen that I looked in the state.json and also there the tab titles were not there anymore.
I then closed the terminal, put the tab names back from a backup of that file and started the terminal again and had the tab titles how they should be.

Just then it was, that the bash didn't start up in the first tab (which is also the one that hung before) for whatever reason.
By splitting / unsplitting / opening new tab / closing tab, I was somehow able to make it work like expected again for now.
But if there is anything I can do to investigate next time, don't hesitate to tell me.

**Comment by PankajBhojwani** [comment]
Thank you for filing this! We will use this thread to follow issue number 3 in your list, could you open up a separate issue for number 4 (the one about the tab names disappearing after a hibernate)? With whatever repro steps got you into that state

**Comment by PankajBhojwani** [comment]
The next time you get this to repro, could you test whether the renderer is still running by attempting to highlight any text? If the renderer is still working, it probably is the client application that hung on the hibernate, and not an issue on Terminal's side.

**Comment by Vampire** [comment]
> Thank you for filing this! We will use this thread to follow issue number 3 in your list, could you open up a separate issue for number 4 (the one about the tab names disappearing after a hibernate)? With whatever repro steps got you into that state


Sure, no problem.
New issue is at #15354.
That one is definitely not related to hibernation I think so I did not mention it there.

> The next time you get this to repro, could you test whether the renderer is still running by attempting to highlight any text? If the renderer is still working, it probably is the client application that hung on the hibernate, and not an issue on Terminal's side.

Up to now this did not reproduce.
Maybe the relation to hibernation is even a red herring, I regularly use hibernation.
It could as well just have been a coincidence that this happened right after waking up from hibernation.
If it happens again, I for sure will try whether I can highlight text.

I'm closing the issue for now so that I'm able to reopen it if it happens again, because I guess you cannot do much without being able to reproduce and if the microsoft-github-policy-service bot closes the issue, I'll not be able to reopen it. Let alone if he double-closes it. :-D
