### ISSUE TITLE
When I scroll down or up the wheel, some lines will disappear

### ISSUE THREAD

**Issue by Cricle** [microsoft/terminal#15330]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.0

### Other Software

None

### Steps to reproduce

1. Run other program, generate many lines of content(Like benchmark)
2. Scroll down or up the wheel(The disappearing row must be moved to an invisible area before it can be seen again)
3. Some lines will disappear

![image](https://github.com/microsoft/terminal/assets/26201412/b0985848-ec39-4918-bb2b-2813adcd5a1c)

### Expected Behavior

Some lines will disappear

### Actual Behavior

Nothing to do

**Comment by lhecker** [comment]
Reading https://github.com/nushell/nushell/issues/9166 it does seem a little unclear to me whether this is a bug in Windows Terminal, nushell or starship. I do know however that this is easily reproducible with starship because I had this issue myself before, but I simply assumed that this is a bug in starship.

Reading through the various, linked issues however, I think this might be due to #8698.

**Comment by j4james** [comment]
@lhecker Is they're using an `SU` sequence to scroll (which is the impression I got from your comments on the nushell issue), then this is potentially a dup of #11078.

If the `SU` is triggered by a terminfo `indn` command, it's kind of our problem, because we're identifying as `xterm-256color`, which defines `indn` as an `SU` sequence (that's what #11078 is all about). But if they're invoking `SU` directly, then I'd say it's more their problem, because they're relying on an interpretation of `SU` which isn't standard.

**Comment by lhecker** [comment]
Thank you for looking into this! As you probably already saw they’re invoking it directly. I personally agree with everything you said in #11078 btw - I feel like we should make that change irregardless of the ambiguity of the sequence and that it should best be avoided, if not at least because of `indn`.

**Comment by zadjii-msft** [comment]
That lines up with the theory we were discussing in triage yesterday. I'll tentatively call this a dupe, with the note that Leonard did have a live repro of this, so it should be fairly easy to validate if the fix for #11078 fixes this. 

/dup #11078
