### ISSUE TITLE
`persistedWindowLayout` does not preserve tab titles

### ISSUE THREAD

**Issue by Vampire** [microsoft/terminal#15354]
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045 Build 19045

### Steps to reproduce

- have `firstWindowPreference` set to `persistedWindowLayout`
- have a `state.json` with some tabs defined that have custom manually set tab titles
- start terminal, the tabs get properly restored
- use the terminal for some time
- have a look at `state.json`

Things that might maybe be relevant additionally:
- the restored window is in quake-mode and after terminal restart I once disable focus mode manually
- the profile I use for all those tabs is "Git Bash", but with `tabTitle` set to `bash`

### Expected Behavior

The custom tab titles are preserved

### Actual Behavior

All tab titles are reset to `bash`.

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file), and the `state.json`/?


My theory was that:
* there's a `profile.tabTitle`,
* but we for some reason preserve `"tabTitle": ""`, like, because the _runtime_ title is empty
* when we go build the `NewTerminalArgs` for the state restore, use the `tabTitle` with the empty string from the state.json
* we evaluate the `NewTerminalArgs.TabTitle` as an empty string then go use the profile.name instead of the `profile.tabTitle`


but looking at my `state.json`, I do have some `tabTitle`s that match the profile's. Maybe your raw jsons will help figure this out.
