### ISSUE TITLE
Terminal pagination breaks after resize

### ISSUE THREAD

**Issue by stephenatwork** [microsoft/terminal#15386]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1702

### Other Software

git version 2.39.2.windows.1

### Steps to reproduce

- start a terminal
- run a command which uses a pager e.g. git log
- Maximize the terminal pane
- Page down (space) a few pages
- Terminal goes unresponsive (i.e. the 'less' prompt does not reappear)

### Expected Behavior

Scrolling down keeps working normally
Pressing 'q' quits the pager

### Actual Behavior

One must interrupt to get the prompt back.
For some reason terminal within vscode cannot be interrupted with keyboard & one must kill the task.
See https://github.com/microsoft/vscode/issues/180406

**Comment by stephenatwork** [comment]
Yes, same behavior with conhost and sizes equal.

<img width="139" alt="image" src="https://github.com/microsoft/terminal/assets/1640758/96fe4198-9c68-4bf6-a564-9aae788fbc54">

**Comment by carlos-zamora** [comment]
Looks like this is an issue with the Windows port of "less". We'll raise the issue with the upstream project. Thanks!

**Comment by zadjii-msft** [comment]
@dqgthb Could you maybe provide any more info? When this got ported out to https://github.com/gwsw/less/issues/411, OP couldn't repro the issue anymore. Are you using the Terminal or conhost? Which version? Which version of `less`, and how are you running it (basically, is this WSL `less`, `less.exe`, git bash `less`, some `less` via ssh...)

It might warrant your own issue, since clearly whatever was at the root of OP's issue was transient, and we might not want to cross-pollute your bug report with the one from OP.
