### ISSUE TITLE
The background color of the terminal cannot be completely black

### ISSUE THREAD

**Issue by November20** [microsoft/terminal#15392]
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1555

The background color of the terminal cannot be completely black

**Comment by o-sdn-o** [comment]
Translation:
### Windows Terminal version
1.16.10262.0

### Windows build number
10.0.22621.1555

### Other Software
no response

### Steps to reproduce
The background color of the terminal cannot be pure black (0x000000).

### Expected Behavior
no response

### Actual Behavior
The background color of the terminal cannot be set to pure black, only dark black or sort of gray, which annoys people with obsessive-compulsive disorder, reduces the contrast of the text, and is very dazzling after long-term use. Some people may use OLED screens, and pure black can also be used for power saving.

**Comment by o-sdn-o** [comment]
You can use Windows Terminal Settings UI to configure color palette applied to any profile you run

![image](https://github.com/microsoft/terminal/assets/11535558/bc8c81e6-5de7-4130-8735-1399caedf6e1)

![image](https://github.com/microsoft/terminal/assets/11535558/1d4f91bb-9a91-40b1-826b-368626b53869)

![image](https://github.com/microsoft/terminal/assets/11535558/e084e857-7a8d-4bc3-b98e-c2c2ac11f2bf)

**Comment by November20** [comment]
![image](https://github.com/microsoft/terminal/assets/28748827/f0d45e04-20d1-4782-b4cc-34de4750d418)
This plan seems very dark.But the actual effect is as follows:
![image](https://github.com/microsoft/terminal/assets/28748827/273b7b7b-fbe7-4a6d-8394-f12e3f6ae4f3)

**Comment by November20** [comment]
The color I saw in the background settings is different from the actual color presented. I can see a significant difference in both a 6-bit TN screen and a limited limit RGB

**Comment by November20** [comment]
![image](https://github.com/microsoft/terminal/assets/28748827/5d3cfaea-8d26-40a0-9dba-198edb6bd39a)
If it is a parameter setting issue, please advise!

**Comment by November20** [comment]
Even if I change the theme of the operating system to high contrast mode, it still won't work
