### ISSUE TITLE
Renderer encountered an unexpected error: -2005270527

### ISSUE THREAD

**Issue by DennisGaida** [microsoft/terminal#15433]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22624.0

### Steps to reproduce

1. Start Terminal Preview with `powershell.exe -NoLogo` profile
2. Either Maximize Window or resize window
3. Receive "Renderer encountered an unexpected error: -2005270527" modal error

### Expected Behavior

No rendering error

### Actual Behavior

Can't resize the initial window. Can't type / typing is slow.

Secondly I can not work at all in any of my profiles (i.e. weird text glitches). I'm using the Cascadia Code Nerd Font (https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode).

Does not happen with e.g. default cmd profile. Might be related to https://github.com/microsoft/terminal/issues/15414 and maybe even in turn https://github.com/microsoft/terminal/pull/15403 because I don't have custom fonts for the default cmd profile?

**Comment by zadjii-msft** [comment]
Thanks for following up! I'll call this /dup #15416. I've gone ahead and pinned that one to the top of the repo. We should have that serviced ASAP.

**Comment by Melanpan** [comment]
Weirdly enough, this exact issue ("Renderer encountered an unexpected error: -2005270527") has been happening to me for weeks now. Even when I was running version 1.16, and I updated it to 1.17 earlier today but alas. I'm not getting any weird visual glitches or anything. Just that occasionally resizing the window or maximizing it will trigger this. Sometimes the error is "This terminal has encountered an issue with the graphics driver and it could not recover in time. It has been suspended."

Which actually makes the terminal really unusable, because any resize has the chance to lose all open sessions.
