### ISSUE TITLE
Terminal Preview returns ERROR_FILE_NOT_FOUND when launching relative path

### ISSUE THREAD

**Issue by ChrisKnue-MSFT** [microsoft/terminal#15487]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Attempt to launch a terminal from command line with a relative path for a file to launch. (ex: "wt .\test.ps1")

### Expected Behavior

In 1.16.10262.0 this would launch the file

### Actual Behavior

[error 2147942402 (0x80070002) when launching `.\test.ps1`]
is printed in the console.

**Comment by zadjii-msft** [comment]
Undoubtably, I broke this in #15280. Or at least, forgot about this scenario 🤦

**Comment by zadjii-msft** [comment]
But it's not just `{{startingDirectory}}/{{commandline}}`. It's more like the search path has to be `{{terminal's vCWD when that connection was created}}/{{commandline}}`.

**Comment by ChrisKnue-MSFT** [comment]
@zadjii-msft We were trying some work arounds (absolute path) and it seems like environment variables are not being passed to the child wt process either. Is there already a bug about that?

**Comment by zadjii-msft** [comment]
Talked this over internally - The fix (as in #16028) for this bug is.... unbelievably gross, and probably even incorrect. This is just gonna have to remain a breaking change post-1.18. The workaround being to always pass absolute paths to the `wt` commandline (which will work on old versions as well as new).
