### ISSUE TITLE
Terminal preview does not accept environment variables from parent process

### ISSUE THREAD

**Issue by ChrisKnue-MSFT** [microsoft/terminal#15496]
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Create a batch file "test.bat" with contents
```bat
echo %TEST%
pause
```
open cmd terminal profile
run `SET TEST=wow`
run `wt test.bat`
run `./test.bat`

### Expected Behavior

New terminal window should open up with output (this is the behavior in 1.16)
```
>echo wow
wow
>pause
press any key to continue . . .
```
Then outputs in parent window
```
>echo wow
wow
>pause
press any key to continue . . .
```

### Actual Behavior

New terminal window is opened with output
```
>echo
ECHO is on.
>pause
Press any key to continue . . .
```
Then outputs in parent window
```
>echo wow
wow
>pause
press any key to continue . . .
```

**Comment by DHowett** [comment]
This was already a bit "wacky" for window grouping, even in Preview 1.16 (and 1.15, 1.14, ...):

```
SET TEST=wow
wt -w 0 cmd
```

has different environment block behavior than...

```
SET TEST=wow
wt -w -1 cmd
```

Between the two, they are now at the very least _consistent_ as of 1.18 😄

**Comment by carlos-zamora** [comment]
@ChrisKnue-MSFT Thanks for filing! Going to close this based on Dustin's responses.

**Comment by timmydo** [comment]
We have hundreds of developers relying on windows terminal for running about 6 tabs of applications to run our platform. Not propagating environment variables is a pretty large breaking change--I hope you will provide a workaround for passing environment variables to new tabs or at least give us some time to rearchitect things before the preview becomes the standard version. @DHowett

**Comment by DHowett** [comment]
(I'm gonna reopen this and mark it for discussion among the team.)

There's roughly one quarter of a year until this ships broadly, which is the big win we get from having a preview channel :smile:

**Comment by zadjii-msft** [comment]
quick notes

* collect the env when `wt` is run. Package that up with the CommandlineArgs to send to the monarch
* add a `--flag` to tell NewTab/SplitPane to use those env vars instead of the regenerated ones
* don't just keep using those vars for future tabs/panes

**Comment by DHowett** [comment]
Maybe the `--flag` should be to _disable_ inheritancez

**Comment by zadjii-msft** [comment]
Argument for `--flag` disabling inheritance
* this is how the `wt` CLI has always operated since inception in 0.9

Argument against:
* Can we tell if `wt` was invoked for the commandline, vs just _started by explorer.exe_? There have been myriad issues in the past that our env vars are just plain wacky. I'd rather that a fresh "click the icon" launch not try to inherit, but idk if we can differentiate

**Comment by zadjii-msft** [comment]
Notes from discussion:

We're gonna approach this as many bits:
* `wt -E foo=bar` to manually pass env vars to the `NewTerminalArgs`. This'll let a caller _manually_ pass env vars on the commandline. Great!
* `wt --inheritEnvironment`
  * This one's more complicated.
  * On `wt` launch, bundle the entire environment that `wt` was spawned with, and put it into the `Remoting.CommandlineArgs`, and give them to the monarch (and ultimately, down to `TerminalPage` with the `AppCommandlineArgs`). DO THIS ALWAYS.
  * IF there was _no_ overridden commandline, anywhere, in any subcommand, then we'll default to what we're doing in 1.18 Preview - _don't inherit_. Terminal act's like file explorer, and just starts up the profile with a fresh env block[^1].
  * IF THERE WAS AN OVERRIDDEN commandline, then default this to "inherit from the caller of WT". 
* part the third: Convert the `compatibility.reloadEnvironmentVariables` setting to a per-profile one.  
  

At the end of this:
* `wt`, `wt -p foo` will still use a fresh env block, instead of the inherited one. Yay!
* `wt -- cmd`, `wt foo.bat`, `wt --inheritEnvironment` will all use the inherited one. Just like in 1.17, yay.
* `set TEST=failure && wt -E TEST=wow cmd.exe /k echo such %TEST%` will set `TEST` in the spawned cmd to `wow`, and that'll be a good boy. 

[^1]: Plus the `environment` setting, of course.
