### ISSUE TITLE
Cannot install Terminal 1.17.11461.0 on Windows Server 2022

### ISSUE THREAD

**Issue by PGomersall** [microsoft/terminal#15512]
### Windows Terminal version

1.17.11461.0

### Windows build number

20348.1726

### Other Software

OS is fully patched Windows Server 2022

### Steps to reproduce

Run Add-AppxPackage C:\temp\Microsoft.WindowsTerminal_1.17.11461.0_8wekyb3d8bbwe.msixbundle

This then will error if Microsoft.VCLibs.140.00.UWPDesktop is not installed. If that package is installed, it will then also error if Microsoft.UI.Xaml.2.7 is not installed.

Only if these 2 packages are installed will Microsoft Terminal install. It is noted that for 1.17 VCLibs is still required, but I have not seen any info that UI.Xaml 2.7 is also needed.

### Expected Behavior

Note to say Microsoft.UI.Xaml.2.7 is needed.

### Actual Behavior

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.
Windows cannot install package Microsoft.WindowsTerminal_1.17.11461.0_x64__8wekyb3d8bbwe because this package depends
on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.7" published by "CN=Microsoft
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and
minimum version 7.2208.15002.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.7"
currently installed are: {}

**Comment by PGomersall** [comment]
Version of Microsoft.UI.Xaml seems to specifically need 2.7, as having latest version also prevents install.

**Comment by DHowett** [comment]
Thanks for letting us know. In general, we _haven't_ noted our dependencies down[^1], because the _preinstallation kit_ distribution contains everything you'll need to perform an offline deployment of Terminal at the minimum versions you'll need to install it.

For Server editions of Windows, manual installation with the preinstallation kit is going to be a lot smoother than any other packaged options.

For Desktop editions of Windows, the "Desktop App Installer" automatically sources any necessary dependencies.

[^1]: except for VCLibs, because 1.18 removed this dependency; however, those notes only apply to the "portable" and "unpackaged" distributions.

**Comment by PGomersall** [comment]
Thanks for quick response Dustin. I was just looking at simple way to automate updating Terminal on Server 2022 using PowerShell and pulling from GitHub and came cross this issue. I suppose I could do the same but extract the contents from the preinstallation kit zip.

**Comment by carlos-zamora** [comment]
I'm going to close this based on Dustin's response, but if Dustin or Pete disagree, happy to reopen. Thanks!
