### ISSUE TITLE
The RecentFiles List has wrong icon and uninstalled item

### ISSUE THREAD

**Issue by void-mian** [microsoft/terminal#15556]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

Vistual Studio

### Steps to reproduce

right click the windows terminal in taskbar

### Expected Behavior

not showing last two item and show the Ubuntu icon

### Actual Behavior

When I click either the cmd of vs preview or powershell, it open a normal powershell in windows terminal.
<img width="234" alt="image" src="https://github.com/microsoft/terminal/assets/36444200/3969c827-7403-4bb0-b5a6-6dd25055c4a9">

<img width="572" alt="image" src="https://github.com/microsoft/terminal/assets/36444200/56733848-4a0e-4a83-8a66-cf4177613f66">

<img width="379" alt="image" src="https://github.com/microsoft/terminal/assets/36444200/66c10b7a-0507-4797-b862-d63ef00b9ee9">

**Comment by zadjii-msft** [comment]
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?

**Comment by void-mian** [comment]
there do have extra profile for vs preview, and do disappear when I delete them. but the Ubuntu icon still not there.

<img width="239" alt="image" src="https://github.com/microsoft/terminal/assets/36444200/74112069-a3bd-492a-8158-6e8f15c80d79">

**Comment by void-mian** [comment]
```json
{
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": true,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
```

**Comment by carlos-zamora** [comment]
Hi @void-mian. If you save your settings again (just click Save in the settings UI, even though there aren't any changes), does fix the list?

**Comment by gmonteir** [comment]
Not sure why this is closed, this is still an issue.

**Comment by zadjii-msft** [comment]
Well, it was closed because we asked OP a question, and they disappeared. A lot of those times, the OP figured it out, but didn't feel the need to come back and update the thread. For those cases, we have a bot to just close out old threads where we're waiting for a reply from OP and thye haven't replied.

Now, what part in particular do you think is still an issue here?
* The ubuntu logo from the profile not showing up in the jump list?
  * This is tracked over in #10552 in greater detail
* Extra entries in the jumplist for the VS profiles?
