### ISSUE TITLE
Update VT docs?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#15577]
I've been going here: [https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences).

Is there a better place?

It doesn't mention SGR 2 (or does it?) ... probably others,

**Comment by DHowett** [comment]
There's not a better place. It's been on my to-do list for a while to go and (1) update these docs and (2) do some version dissection so that I can communicate when a given control sequence became supported.

**Comment by j4james** [comment]
See also https://github.com/MicrosoftDocs/Console-Docs/issues/91

**Comment by vefatica** [comment]
For now, are there any control sequences related to ESC#3 and ESC#4 (double height text)?  Can double height be turned on/off mid-line?

**Comment by j4james** [comment]
The double-width and double-height styles are known as line attributes, because they apply to the entire line. You can't change them half way through a line.

You can read the DEC VT500 documentation for them here:
* [DECDHL](https://vt100.net/docs/vt510-rm/DECDHL.html)
* [DECDWL](https://vt100.net/docs/vt510-rm/DECDWL.html)
* [DECSWL](https://vt100.net/docs/vt510-rm/DECSWL.html)

**Comment by carlos-zamora** [comment]
Thanks for filing @vefatica. We're gonna mark this as a /dup of https://github.com/MicrosoftDocs/Console-Docs/issues/91
