### ISSUE TITLE
The edges are blank

### ISSUE THREAD

**Issue by kohnish** [microsoft/terminal#15597]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1848

### Steps to reproduce

Open some tui application like tmux, vim of different background colour, you see blank edges especially on the right side, causing the applications to occupy slightly smaller screen.

### Expected Behavior

All screen area is used by the applications.

### Actual Behavior

All screen area cannot be used. 
You need to migrate to something like alacritty for real full screen experience.

**Comment by 237dmitry** [comment]
This happens if in the default profile is set padding. At the same time, the dimensions of the terminal window take into account the size of the indents in pixels, which does not correspond to the size of the printed characters.

The screenshots show that there is no padding, since I made Far the default application and in the settings the padding is zero.
And for the powershell profile, the padding is 4 pixels, but it starts after the Far and does not resize the window.

![Screenshot 2023-06-24 102003](https://github.com/microsoft/terminal/assets/78153320/c9e842a3-9d15-48a5-bb66-b3c2ee7925d0)

![Screenshot 2023-06-24 102349](https://github.com/microsoft/terminal/assets/78153320/197f27f2-3450-48b2-8dbb-4785466784c5)

**Comment by kohnish** [comment]
I missed that configuration. By setting it to 0 and removing scroll line, the problem is solved. thank you very much.
