### ISSUE TITLE
Heavy Check Mark symbol `\u2714` isn't rendered with supposed font and foreground color

### ISSUE THREAD

**Issue by fadeevab** [microsoft/terminal#15592]
### Windows Terminal version

 1.17.11461.0

### Windows build number

10.0.19045.0

### Other Software

WSL2+Ubuntu, `bash`, `starship` command prompt, "FiraCode NFM Retina" font

### Steps to reproduce

```bash
echo -e "\033[91m\u2713\u2714"
```

### Expected Behavior

![image](https://github.com/microsoft/terminal/assets/5967447/75624a59-4acd-412a-9ffb-a0a505cc157c)

It's in VSCode integrated Terminal.
Font is the same "FiraCode NFM Retina"

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/5967447/9b085c3a-9064-4c3b-9124-6b3d9a0e183a)

**Comment by j4james** [comment]
I think this is essentially the same problem as #13110. Some emoji are meant to use a text presentation by default (those with "Emoji_Presentation=No" in the [Emoji Data for UTS](https://www.unicode.org/Public/15.0.0/ucd/emoji/emoji-data.txt) list), and we don't currently follow that rule. As far as I can see, both U+2714 and U+265F fall into that category, so should _not_ be using an emoji presentation by default.

**Comment by lhecker** [comment]
Yep, I agree, it's essentially #13110. /dup #13110

Fixing this issue is not too difficult. When we encounter such emojis - those that are supposed to be `Emoji_Presentation=No` we simply need to set skip the enumerator contruction here: https://github.com/microsoft/terminal/blob/191eb00f43cce6f0a7c35404937ab1a870aef775/src/renderer/atlas/BackendD3D.cpp#L1303

To recognize such glyph indices that map to such emoji code points, I already did something similar here:
https://github.com/microsoft/terminal/blob/191eb00f43cce6f0a7c35404937ab1a870aef775/src/renderer/atlas/BackendD3D.cpp#L1154-L1172

I just haven't had time to get to this and probably won't in the near term.
