### ISSUE TITLE
Responsiveness regression in Windows Console Host

### ISSUE THREAD

**Issue by averms** [microsoft/terminal#15607]
### Windows Terminal version

1.17.11461.0

### Windows Console Host version

1.17.2305.26001 (From right-click -> properties -> details)

### Windows build number

10.0.19045.3086

### Other Software

[Typometer 1.1.0](https://github.com/frarees/typometer/releases/tag/v1.1.0)

### Steps to reproduce

1. On Windows 10, run `conhost.exe` and use typometer to measure the latency of a `cmd` prompt. I get an average of 16.3 ms with a standard deviation of 0.3 ms. Marvelous. See the first screenshot.
2. Download the latest Windows Terminal zip and measure the latency of `OpenConsole.exe`. I get an average of 28.9 ms with a standard deviation of 7.2 ms. See the second screenshot.

![image](https://github.com/microsoft/terminal/assets/29077900/81445d83-0748-4d74-a25b-438d30a0bd39)
![image](https://github.com/microsoft/terminal/assets/29077900/df2d981b-a8da-4ff7-95bf-4dfc5405ab50)

### Expected Behavior

I would like the new versions of conhost to have latency numbers closer to that of old conhost.

### Actual Behavior

Latency in new versions of conhost is quite a bit worse.

**Comment by lhecker** [comment]
FYI the trick to launch the application with JDK 17 is to use
```
java --add-opens=java.desktop/java.awt=ALL-UNNAMED -jar typometer-1.1.0.jar
```
Furthermore, the application only works if the display is set to 100% scale.

---

I could reproduce the issue immediately, although the latencies are 1 frame higher for me because I'm ✨blessed✨ with Windows 11. But the window borders are rounded so it's all good. Yay. Progress.

![image](https://github.com/microsoft/terminal/assets/2256941/084dee56-bbb7-45e4-8a5f-84e414bb4383)

Fixing it is very simple, so I'll submit a PR shortly. Thanks for letting us know about this!

**Comment by elsaco** [comment]
Building with 72b44888 when maximizing the terminal window latency is worse:

![wt-dev-latency](https://github.com/microsoft/terminal/assets/3933920/540fded7-41b6-42a4-8e6d-a443ef7abf55)

Tests 4 and 5 were done with the patch applied. Test 4 was maximized window, and test 5 was full screen. Test 1 was done with terminal 1.18.1462.0. All test were done on Windows 10.
