### ISSUE TITLE
Right click context menu "Open in Terminal"  terminal behaves differently than launched directly from search

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#15640]
### Windows Terminal version

1.17.11461.0

### Windows build number

Version	10.0.22631 Build 22631

### Steps to reproduce

Right click in a folder. Click "Open in Terminal" .
Type in e.g. `git st`  a defined user shortcut in my git dotfile

### Expected Behavior

If I launch the Terminal directly through windows search, applications, e.g. `git` correctly read in user profile configs
`git st` works (st is a defined shortcut in my git dotfile)

### Actual Behavior

error since the config is not read.

**Comment by lhecker** [comment]
This is very similar to a number of bug reports we've received recently like #15624 for instance.

**Comment by zadjii-msft** [comment]
Does this work with [Terminal Preview](https://github.com/microsoft/terminal/releases/tag/v1.18.1462.0)/?  There were a number of changes to way the Terminal loads env vars in 1.18 to make it more consistent.

**Comment by musm** [comment]
> Does this work with [Terminal Preview](https://github.com/microsoft/terminal/releases/tag/v1.18.1462.0)/? There were a number of changes to way the Terminal loads env vars in 1.18 to make it more consistent.

Unfortunately, I do not have a right-click option with Windows Terminal Preview. Do you know how I could add it or simulate that behavior?

**Comment by lhecker** [comment]
Explorer can behave weird with extensions sometimes, because it's just not particularly robust. For instance, when I boot my PC, the first time I right click I never get Windows Terminal to show up in my context menu, ever. Only when I right click the second or third time it works.

So... Did you already try if Terminal Preview shows up if you reboot your PC?

**Comment by musm** [comment]
> So... Did you already try if Terminal Preview shows up if you reboot your PC?

I reinstalled Terminal Preview but it doesn't show up as a right-click option?

**Comment by zadjii-msft** [comment]
> I reinstalled Terminal Preview but it doesn't show up as a right-click option?

That's super weird! It _should_ be there, by all accounts. Mind filing feedback on "Desktop Environment > Right-click context menu"?

![image](https://github.com/microsoft/terminal/assets/18356694/022dcd18-6e26-4899-8a98-07a1ca3c5a21)

That's just to try and get _that_ bug to the right people. (there are dupes of that laying around somewhere)

---

Now, back to the Terminal. Since we can't get the Preview version to the same state to repro this, we'll just do more debugging manually. 

Are your environment variables the same when you launch the Terminal via the right-click menu, vs through the Start Menu/? We've had reports of the variables being different in the past. (Namely, `PATH`, ala #11777)
