### ISSUE TITLE
Windows Store cannot update terminal

### ISSUE THREAD

**Issue by Fightinging1997** [microsoft/terminal#15715]
The terminal displays version 1.17 in the Windows Store, but the newly downloaded version 1.12 locally does not show that it can be updated

![image](https://github.com/microsoft/terminal/assets/66704794/80d51e1a-b180-44c0-89aa-e09de6504852)

![image](https://github.com/microsoft/terminal/assets/66704794/ff8a3d23-50f8-439b-bff4-914a8d9c0a95)

**Comment by zadjii-msft** [comment]
This sounds like feedback that needs to be filed on the Microsoft Store app itself. 

You can always manually install the latest builds off of `winget`[^1] or [our releases page](https://github.com/microsoft/terminal/releases)


[^1]: though, due to a bug in `winget` 1.17 stable isn't actually available yet, but _they're working on it_.
