### ISSUE TITLE
Preview icon error

### ISSUE THREAD

**Issue by JZP1996** [microsoft/terminal#15719]
### Windows Terminal version

1.17.1023

### Windows build number

1000.22658.1000.0

### Steps to reproduce

- Install Preview version
- Pin Preview Terminal to taskbar
- Icon is not show the "PRE".

### Expected Behavior

Show "PRE" in the bottom right in the blue box.

### Actual Behavior

Not show "PRE" in the bottom right in the blue box.

**Comment by zadjii-msft** [comment]
This is by design. Our icons don't have the text on them at smaller resolutions, because it ultimately made the icons too cluttered and hard to read. 

I believe that 36px is the first size that includes the text: https://github.com/microsoft/terminal/blob/main/res/terminal/images-Pre/Square44x44Logo.targetsize-36.png

Thanks!
