### ISSUE TITLE
SendInput with newlines in it outputs the text backward

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#15788]
### Windows Terminal version

latest build of main

### Other Software

Powershell 7

### Steps to reproduce

Make a 'sendInput' command with newlines in the settings json, example:

```
            "command": 
            {
                "action": "sendInput",
                "input": "a\nb\nc"
            },
            "name": "test sendinput"
```

Invoke the command in terminal

### Expected Behavior

The text output should be a, then b, then c as below

<img width="357" alt="image" src="https://github.com/microsoft/terminal/assets/26824113/85f62b7c-5749-4671-8bac-eb37318bce4a">

### Actual Behavior

The actual output is reversed, and goes c->b->a

<img width="353" alt="image" src="https://github.com/microsoft/terminal/assets/26824113/d428823a-a653-479e-ab2e-2a3b9849dc5e">

**Comment by PankajBhojwani** [comment]
Update: with command prompt instead we get:
<img width="172" alt="image" src="https://github.com/microsoft/terminal/assets/26824113/19d3a7d2-e7ae-4c11-9216-0a3e03910e60">

I.e. the text is still backward but there's no new lines at all

**Comment by DHowett** [comment]
Sooo this is actually adjacent to a paste issue we had! You want `\r` or both `\r\n`.

**Comment by lhecker** [comment]
Should `sendInput` maybe just behave like `ENABLE_PROCESSED_INPUT` is enabled?

**Comment by zadjii-msft** [comment]
My thought is that `InputStateMachineEngine::_DoControlCharacter` attempts to translate `\n` to <kbd>ctrl+j</kbd>. But that doesn't _seem_ like what's happening, because <kbd>ctrl+j</kbd> is bound to `MenuComplete` (at least, on my machine). I'd probably need to step through it more precisely. 


Key      |        Function       |     Description
---      |        --------           | -----------
Ctrl+Enter | InsertLineAbove| Inserts a new empty line above the current line without attempting to execute the input

Now, that's pretty dang close to what we're seeing. That would also explain why nothing happens in CMD - <kbd>ctrl+enter</kbd> doesn't do anything there.

**Comment by HDJINJIN** [comment]
@
