### ISSUE TITLE
Random crash due to process closing too fast

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [microsoft/terminal#15789]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19041.3271

### Steps to reproduce

Unknown, this is pretty much random. The fastest way to reproduce it is to run the following:
```pwsh
Invoke-Command -ComputerName $servers -Credential $cred -ScriptBlock {
    netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 50 0
    netsh interface ipv6 set prefixpolicy ::1/128 40 1
    netsh interface ipv6 set prefixpolicy ::/0 30 2
    netsh interface ipv6 set prefixpolicy 2002::/16 20 3
    netsh interface ipv6 set prefixpolicy 2001::/32 5 5
    netsh interface ipv6 set prefixpolicy fc00::/7 3 13
    netsh interface ipv6 set prefixpolicy fec0::/10 1 11
    netsh interface ipv6 set prefixpolicy 3ffe::/16 1 12
    netsh interface ipv6 set prefixpolicy ::/96 1 4
}
```
Run a lot of independent processes that closes quickly.  Make sure Windows Terminal is set to the default console host.

**NOTE:** After testing, reset your policies with (for instance) `netsh interface ipv6 reset` and reboot. `netsh interface ipv6 show prefixpolicies` should produce:
```
Precedence  Label  Prefix
----------  -----  --------------------------------
        50      0  ::1/128
        40      1  ::/0
        35      4  ::ffff:0:0/96
        30      2  2002::/16
         5      5  2001::/32
         3     13  fc00::/7
         1     11  fec0::/10
         1     12  3ffe::/16
         1      3  ::/96
```

### Actual Behavior

We noticed some of the crashing process reported 0x800700e8 (The pipe is being closed) and then crashes

[eventlog.zip](https://github.com/microsoft/terminal/files/12235868/eventlog.zip)

**Comment by lhecker** [comment]
I've updated your comment with the Windows Terminal and Windows version numbers from your eventlog.zip. Please always add them to your bug reports. I've also included steps to restore the proper IPv6 policies.

---

Your command
```pwsh
Invoke-Command -ComputerName $servers -Credential $cred -ScriptBlock {
```
won't work because we don't have access to your `$servers`. I tried reproducing the issue in Windows Terminal 1.17.11461.0 without the two arguments (= locally) and the issue didn't occur. This implies to me that your repro steps really only work if an `Invoke-Command` is used on a remote machine.

How does `Invoke-Command` work on a remote machine? Does it spawn a Windows Terminal window on the remote and that's why it breaks?

**Comment by zadjii-msft** [comment]
Honestly, the fastest way to a root cause might be a crash dump. Either via feedback hub:

/feedback

Or manually: https://github.com/microsoft/terminal/wiki/Toubleshooting-Tips#capturing-and-sending-dumps
