### ISSUE TITLE
why isn't possible to scroll anymore in a linux screen

### ISSUE THREAD

**Issue by TheRealEiskaffee** [microsoft/terminal#15796]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3208

### Steps to reproduce

1. Connect to a Server over SSH
2. Create a screen (in Linux) = screen -S Name
3. Then go into a screen and create outputs or something like that where you must scroll

### Expected Behavior

i use the version v1.12.1073 because there wasnt the problem and we could scroll egal no matter how much the output was.

### Actual Behavior

with the new version i cant scroll in a screen. I have try everything but nothing helps me.

**Comment by zadjii-msft** [comment]
This is behavior that's fairly highly preserved across terminal emulators. I wasn't sure that there were any that let you scroll the alt screen buffer. 

Prior to #12561 (1.14), you could seemingly scroll the "alt buffer" in Terminal, but that was just because Terminal didn't actually support the alt buffer yet 😅

I know it's possible to configure `tmux` to scroll it's buffer with the mouse, but I'm not so sure about `screen`.
