### ISSUE TITLE
Incorrect behavior of ANSI '\033[K' at the end of a line.

### ISSUE THREAD

**Issue by latlaj** [microsoft/terminal#15802]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
grep (GNU grep) 3.0

### Steps to reproduce

First ssh to linux.
Creat a file 'test.txt' like this:
```txt
abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef
```
```bash
grep 'abcd' test.txt --color=always
```
If Colored String at the end of the line, the last character will be lost. If Colored String at the begin of the line, the last character of the previous line will be lost.
```bash
grep 'abcd' test.txt --color=always > test.color
```
download the test.color file, it looks like:
```txt
\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef\033[01;31m\033[Kabcd\033[m\033[Kef
```
It seems like \033[K clean the last character. How can I avoid it?

### Actual Behavior

![char-lost](https://github.com/microsoft/terminal/assets/39641430/48074be8-d484-4aa1-856d-9d1e904d879c)

**Comment by zadjii-msft** [comment]
_what_

@lhecker any ideas if is this the same thing you were also just seeing with `ssh`?

**Comment by lhecker** [comment]
No, that one only happens with OpenConsole.

**Comment by j4james** [comment]
There are two issue to be aware of here:

1. When you write out a line of text that's exactly the width of the screen, the cursor doesn't immediately wrap onto the next line, but instead sets a flag and leaves the cursor in the last column. If more text is received while that flag is set, the cursor will move to the next line before adding the new content to the buffer. But if the terminal receives an `EL` command at that point, it's going to erase the character in the last column, because that's still where the cursor is positioned.

2. There are a number of operations that are expected to reset that "end of line" flag, and `EL` is one of them. So after you've executed that `EL` command, any additional text you output at that point is expected to start in the last column rather than on the next line.

What we're seeing in the screen capture above is the effect of part 1, but not part 2. So that's why one of the characters is being blanked out rather than overwritten. We only implemented part 2 in PR #14936, which I don't think is included in version 1.17.

Either way you're going to end up with a missing character if you execute `EL` at the end of a line, but that's expected behavior. This is technically a bug in grep, because it really shouldn't be using `EL` like that. You can read more about it in the [XTerm FAQ](https://invisible-island.net/xterm/xterm.faq.html#grep_colors).

**Comment by j4james** [comment]
I should also note that there was a workaround for this issue that was mentioned in the grep bug report. If you do something like this:
```
GREP_COLORS="ne" grep 'abcd' test.txt --color=always
```
Then grep won't inject those `EL` sequences everywhere, so you shouldn't lose any characters.

**Comment by latlaj** [comment]
@j4james Thanks a lot for finding the answer for me.

**Comment by zadjii-msft** [comment]
Well, I think that answers that. Thanks for the detailed writeup!
