### ISSUE TITLE
Implement the `Ctrl + T` shortcut to open a New Tab from the currently active Tab / default Tab

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/terminal#15816]
# Description of the new feature/enhancement

Implement the `Ctrl + T` shortcut to open a New Tab from the currently active Tab.

File Explorer and Browsers all implement this shortcut to open a new tab. So almost all of them are familiar with this shortcut key combination.

Optionally, this can further be enhanced with the option to use the config of Active Tab or Default Tab.

# Proposed technical implementation details (optional)

Implement the Keyboard Accelerator to open a New Tab.

**Comment by zadjii-msft** [comment]
`newTab` is already bound to `ctrl+shift+t` by default. You're free to rebind it to whatever key combo you'd like. 

[Docs link](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#new-tab)

We've discussed elsewhere on this repo at length about our preference for `ctrl+shift+` keybindings by default, as opposed to `ctrl+` ones, to avoid conflicts with CLI applications. 

You may also be interested in [`duplicateTab`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#duplicate-tab) to duplicate the active tab, rather than use the default.
