### ISSUE TITLE
Starting Directory being ignored for WSL

### ISSUE THREAD

**Issue by HiDannyZ** [microsoft/terminal#15827]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22621.2134

### Other Software

WSL 

### Steps to reproduce

I am trying to set my starting directory to a folder on my Desktop.

These are the steps I am following and I have been trying for the last 40 mins following guides online.

1. Open Ubuntu Profile on windows terminal via UI or settings.json file
2. Set Starting Directory to ```/c/Users/Danny/Desktop/Projects``` or ```/mnt/c/Users/Danny/Desktop/Projects```
``` 
            {
                "elevate": false,
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc",
                "startingDirectory": "/mnt/c/Users/Danny/Desktop/Projects"
            },
```

### Expected Behavior

Windows terminal Ubuntu will now open in the projects folder on my desktop

### Actual Behavior

Windows Terminal Ubuntu ignores all changes that I make to the starting directory.

No matter the change I always start at ```/home/hidanny```.

Only when the starting directory is invalid, there is an effect via error on the ubuntu instance in windows terminal.

**Comment by 237dmitry** [comment]
What if you set the traditional Windows path as the starting directory? Ubuntu will detect it or not?

**Comment by zadjii-msft** [comment]
Ah, this is that `ubuntu.exe` bug. The `CanonicalGroupLimited.Ubuntu*` profiles don't ever respect the startingDirectory. You'll want to use one of the `Microsoft.Terminal.Wsl` ones, or replace the commandline with `wsl -d Ubuntu`.

/dup #12961

**Comment by aplotor** [comment]
> Ah, this is that `ubuntu.exe` bug. The `CanonicalGroupLimited.Ubuntu*` profiles don't ever respect the startingDirectory. You'll want to use one of the `Microsoft.Terminal.Wsl` ones, or replace the commandline with `wsl -d Ubuntu`.
> 
> /dup [#12961](https://github.com/microsoft/terminal/issues/12961)

hi @zadjii-msft, just curious why this happens? i did `wsl --install Ubuntu` as usual on a new laptop and it installed a Ubuntu profile with `"source": "Microsoft.WSL"` (and a different guid) instead of the usual `"source": "Windows.Terminal.Wsl"`

and is there a way to switch the `"source": "Microsoft.WSL"` ubuntu to the `"source": "Windows.Terminal.Wsl"` one?

**Comment by zadjii-msft** [comment]
I've forgotten the exact details, but newer iterations of the Terminal and WSL intentionally changed that. Part of this is with the new `Microsoft.WSL` source - WSL in now in charge of managing the profiles, rather than Terminal. That should make things better for a variety of cases, though, I haven't been close enough to the project for the last year to know for sure. 

@DHowett will know more than me here

**Comment by DHowett** [comment]
@aplotor The new WSL integration @zadjii-msft mentioned had a bug. which they fixed.

For now, you can edit your `commandline` property to remove `--cd ~` from it.

WSL bug: https://github.com/microsoft/WSL/issues/13346
WSL fix: https://github.com/microsoft/WSL/pull/13350

I'm locking this issue because it is a two-year-old duplicate. If you continue to have issues, please file a new bug.
