### ISSUE TITLE
I can't change order of tabs by dragging and dropping

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/terminal#15839]
### Windows Terminal version

1.17.11461.0

### Windows build number

22621.2134

### Steps to reproduce

Open several tabs. try to change order by dragging and dropping like in microsoft edge.

### Actual Behavior

nothing happens.

**Comment by zadjii-msft** [comment]
Are you running the Terminal as an Admin / elevated/?

**Comment by kotenok2000** [comment]
Yes

**Comment by zadjii-msft** [comment]
This is by design. Please make sure to [search for duplicates ](https://github.com/microsoft/terminal/issues?q=is%3Aissue+reorder+tabs+administrator+)when filing new issues.  This is something that we can't support right now due to some platform limitations. Turns out, even if we tried to support reordering tabs while elevated, the application would actually just crash 😨. See #3581, #4874, #5564, #6893 and others for more details.

/dup #6661
