### ISSUE TITLE
CTRL + SHIFT + 2 Does not get registered when Google Chrome is open

### ISSUE THREAD

**Issue by DjordjeMandic** [microsoft/terminal#15871]
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Open Google Chrome, Open Terminal, Go to Settings, Actions, try to change any action to hotkey and Press CTRL+Shift+2

### Expected Behavior

Having pressed key combination recognised.

### Actual Behavior

Nothing happens, also `New Tab, profile index: 1` does not work

**Comment by lhecker** [comment]
I was unable to reproduce the issue unfortunately. I opened Chrome, then Windows Terminal 1.17 > Settings > Actions, then changed the "Open Settings" action to Ctrl+; and saved. Ctrl+Shift+2 still worked.

Do you have any extension in Chrome that might cause this issue?

**Comment by zadjii-msft** [comment]
Does this only happen with certain actions? I idly wonder if `newTab, index:1` doesn't work in the SUI (some actions don't, but I thought newTab should...).

Can you bind _other_ <kbd>ctrl+shift+num</kbd> keys to actions in the SUI/? 

DO you have _anything_ else running? PowerToys? AutoHotKey? Anything that might try to bind a global hotkey or install a keyboard hook?

<kbd>ctrl+shift+2</kbd> is interesting, because that should be `ctrl+@` on a en-us keyboard, which is often encoded as NUL, but that's probably not the issue here.....

**Comment by DjordjeMandic** [comment]
Solved. Extension [streamkeys](https://github.com/berrberr/streamkeys) had hook on it. 
![image](https://github.com/microsoft/terminal/assets/6750655/8f625f49-5823-4aa6-90b0-c62f2f5e5461)

**Comment by DHowett** [comment]
Thanks for following up!
