### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by lvzhuangzhuang** [microsoft/terminal#1591]
连接linux rz 命令无法使用 出现乱码
![image](https://user-images.githubusercontent.com/20833242/60084000-4c5c7a00-9769-11e9-8055-a13a7d8b675d.png)

**Comment by carlos-zamora** [comment]
Closing because this does not follow the template provided on GitHub's "New Issue" button. Please either:
- edit report to meet the template provided, then reopen.
or
- open a new issue that meets the template provided.

The template can be found by clicking the "New Issue" button on our repo on GitHub. 😊

**Comment by lonnywong** [comment]
For anyone stuck on using `lrzsz ( rz / sz )` in Windows Terminal #1999. You can try [`trzsz ( trz / tsz )`](https://trzsz.github.io/go).

It is recommended to use [`trzsz-ssh ( tssh )`](https://trzsz.github.io/ssh):

```sh
# Install trzsz-ssh ( tssh ) in Windows Terminal
scoop install tssh / winget install tssh / choco install tssh

# Log in to the remote server using tssh. It works similar to ssh.
tssh remote_server

# Install trzsz-go on the remote server. Please check https://trzsz.github.io/go
brew install trzsz-go / yay -S trzsz / sudo apt install trzsz / sudo yum install trzsz / etc...

# Upload files like rz
trz

# Upload directories
trz -r

# Download files like sz
tsz file
tsz /path/to/file

# Download directories
tsz -r dir
tsz -r /path/to/dir
```
