### ISSUE TITLE
[1.19+] Too many scrollbar marks slow down scrolling significantly

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#15955]
I think this is what's happening. Fill a buffer and then search for a really short needle like `e`.

Scroll.

It will be really unusually slow.

It gets better if the needle is longer.

**Comment by DHowett** [comment]
FWIW: The viewport has no bearing on what content exists for search :)

**Comment by lhecker** [comment]
This doesn't happen due to searching the buffer again, but rather because WinUI struggles with the number of layers in the scrollbar canvas. I prototyped a solution based on my earlier bitmap proposal here: https://github.com/microsoft/terminal/compare/dev/lhecker/15955-optimize-scrollbar-marks
(It also includes a bug fix for `ControlCore`. The branch works but is still missing: A code cleanup, Shortening the canvas area by 16px on the top and bottom, The `std::clamp` code seems kinda bad)
