### ISSUE TITLE
Characters have black background in Terminal Preview 1.18.1462.0

### ISSUE THREAD

**Issue by tanc** [microsoft/terminal#15960]
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22622.0

### Steps to reproduce

I'm not sure yet what the reproduction steps but the rendering issue seems to present itself immediately upon opening the terminal application.

### Expected Behavior

Rendering of text to be normal

### Actual Behavior

Each character has a black background which is very noticeable if using a light colour scheme, for example:

![image](https://github.com/microsoft/terminal/assets/76320/b45a552c-562d-4f28-93b7-823e198118ca)

Changing the font or font size does not seem to have any effect.

**Comment by tanc** [comment]
I know right! Why is always me with the rendering problems? 😬😉

Do you use something like MacType?
Nothing like that, just standard Windows rendering

Does it happen if you disable ClearType Anti-Aliasing?
Same issue with ClearType disabled

Registry values for this single display:
![image](https://github.com/microsoft/terminal/assets/76320/67398f08-d4da-45e5-abec-25d6b2c68e74)

This is the dialog when opening the options:
![image](https://github.com/microsoft/terminal/assets/76320/a604b7f1-652e-4b11-a5cd-fd56f30f3f26)

I then picked Power saving NVIDIA 2070 Super and re-opened Terminal Preview but the black background to the characters is still there.

I also tried adjusting the clear type options until the registry values were the same as yours but the result is the same in Terminal preview.

**Comment by lhecker** [comment]
Ugh... I was hoping that it's a bug with the Avalon settings. If it's not too much to ask, could you please install PIX? You can find it here: https://devblogs.microsoft.com/pix/download/
It'll ask you a couple questions on the first launch and it doesn't really matter what you pick. It's just for their user/market research.

You then need to launch it as Admin (it'll allow you to launch as non-Admin but silently won't record any GPU metrics). Quit all instances of Windows Terminal Preview. Then, do this (the important bits are "Launch UWP" and "Launch for GPU capture"):
![image](https://github.com/microsoft/terminal/assets/2256941/54c0ce4f-5b15-4274-b25f-c213d59ddb7d)

After clicking "Launch", it'd be nice if you could choose a light theme like you did before, insert an emoji like 🌯, and then press Ctrl+A to select all text. Like so:
![image](https://github.com/microsoft/terminal/assets/2256941/275d7a29-b785-4892-b1c3-b0b49b14d059)

Back in PIX, press Ctrl+Shift+N. Make sure the green box looks like this:
![image](https://github.com/microsoft/terminal/assets/2256941/04a618ec-ed21-4c11-a2b4-b5e90090af6d)

Then press Ctrl+N (or click the camera icon) and then focus the terminal again. It should quickly create a capture like so:
![image](https://github.com/microsoft/terminal/assets/2256941/1b792b7a-d8d5-4dd3-865e-6f3f6f0804fd)

Double click the capture and then press Ctrl+S. If you could send this file to `<my github username>@microsoft.com`, that'd be really helpful!

---

You can also investigate it yourself if you're curious or just prefer that. To do that, after opening the capture, click on the little start arrow in the top right:
![image](https://github.com/microsoft/terminal/assets/2256941/88881c0c-77cd-4a60-a559-4c6641f6ee5a)

Then pick graphics queue 1 (WinUI unfortunately uses its own graphics queue = 0):
![image](https://github.com/microsoft/terminal/assets/2256941/6787704e-5d3d-4df8-963f-c42c897e8d87)

Click on the "Pipeline" tab, and click on the blue `DrawIndexedInstanced` entry in the list. At the bottom you'll see all the GPU stages.
* IA: Input Assembler - All the per-frame data that is being sent to the GPU
* VS: Vertex Shader - In our case it translates from absolute coordinates in pixels (top left corner is 0,0) to screen space coordinates that range from -1 to +1 in both the X and Y axis.
* PS: Pixel Shader - The thing that is probably failing right now. Texture 1 is the glyph atlas.

`CBV` are the Constant Buffer Values, i.e. the values that are constant across one entire shader invocation for all pixels. You won't be able to read the CBV unless you tell PIX its layout (I think this is a limitation due to the use of D3D11on12). To read it, double click on the CBV entry on the left and it'll pop up an Active Resource tab. There, you need to enter the struct definition which in case of the Pixel Shader is:
```
float4 backgroundColor;
float2 backgroundCellSize;
float2 backgroundCellCount;
float4 gammaRatios;
float enhancedContrast;
float underlineWidth;
```
Expand item `[0]` and it'll show you all relevant values. In my case:
![image](https://github.com/microsoft/terminal/assets/2256941/7928bc34-fce8-491e-880b-3a287629b67e)

**Comment by lhecker** [comment]
@tanc The PIX dump and your settings.json file helped me a lot! Quick workaround:
Update to the latest Windows Terminal (even non-Preview is fine) and remove the `passthrough.hlsl` shader from your settings.json (Ctrl+Shift+,). 🙂

I haven't 100% understood yet why it happens but I know what causes this effect. Once I open a PR, I'll comment there what caused this issue.

**Comment by tanc** [comment]
@lhecker ah of course! It was the `passthrough.hlsl` we added to debug #15199 
Removing that has fixed the issue. I'll close this issue as I don't think it'll affect anyone else.

**Comment by lhecker** [comment]
I'm glad it fixed it! For now I'd like to keep the issue open however, since this shouldn't happen if you use a shader and so I still got something to fix. 😅
(Please feel free to unsubscribe if you'd like!)
