### ISSUE TITLE
CLI apps don't start in Windows Terminal when started minimized

### ISSUE THREAD

**Issue by dapetcu21** [microsoft/terminal#15961]
# Description of the new feature/enhancement

I have Windows Terminal set as my Default terminal application and New instance behavior set to "Attach to the most recently used window". We have a tool that starts many console processes at the same time. It does so using `System.Diagnostics.Process.Start()`. We'd like for these processes to be started in the background as to not steal the focus from the foreground window. I noticed that if I start the processes with `ProcessStartInfo.WindowsStyle == ProcessWindowStyle.Minimized`, the console windows will start minimized, but they won't attach as a tab to Windows Terminal. They will just start as windows of their own. Can we have Windows Terminal handle this situation too?

**Comment by zadjii-msft** [comment]
You know, this was always by design. There's a bunch of heuristics built in to the Default Terminal handoff to try and ID a console app that "didn't wand a console window" - minimized is one of those things. 

Maybe now, in the post-1.18 world where we have tear-out, we can allow for minimized defterm windows. We could just always pop the minimized defterm connection into a new window that's minimized. If someone wants to re-attach it, they always could restore it then re-attach it later. 

xlinking a note from #13838
> This doesn't do the same for defterm-initiated connections. This is because we don't need to! Defterm very explicitly rejects handoff for minimized console apps. This is probably for the best! I put an attempt in 66f8b25ec before I forgot that it was filtered long before the Terminal. NOT doing this for /min saves us all sorts of "what happens if `start /min cmd` tries to glom?" or "what if someone does `start /min cmd && start /max cmd` and they glom together?".
