### ISSUE TITLE
Cannot drop file or folder path on cmd or powershell after install terminal 

### ISSUE THREAD

**Issue by OurIslam** [microsoft/terminal#15996]
### Windows Terminal version

1.17.11461

### Windows build number

10.0.22621

### Other Software

CMD
POWERSHELL
PREV AND full both can not drag and drop file or folder path after install windows terminal , but when i uninstall terminal then drag and drop works again

### Steps to reproduce

CMD
POWERSHELL
PREV AND full both can not drag and drop file or folder path after install windows terminal

### Actual Behavior

CMD
POWERSHELL
PREV AND full both can not drag and drop file or folder path after install windows terminal

**Comment by lhecker** [comment]
Do you launch Windows Terminal as admin?

**Comment by zadjii-msft** [comment]
Got it, so:

* Looks like you disabled UAC entirely, so Terminal is always running with admin permissions.
* That makes me think this is the thing we fixed in #14946. I don't _think_ we backported that to 1.17. Can you double check this with [Terminal Preview](https://aka.ms/terminal-preview) set as the default terminal application/?

**Comment by OurIslam** [comment]
yes SecHealthUI uninstalled , anyway this version of terminal dont damage cmd and powershell Microsoft.WindowsStore_22204.1400.4.0 
attached test 2 mp4  

https://github.com/microsoft/terminal/assets/3030547/f8a3bd98-07d7-4c10-8dc5-3c30602ecc6c

**Comment by OurIslam** [comment]
i have updated post . this version of terminal Microsoft.WindowsTerminal_3001.12.10983.0 dont damage drag drop of cmd and powershell

**Comment by zadjii-msft** [comment]
Terminal 1.**12**?? Yea you'll definitely want to update. That's a couple years old now 😅

**Comment by OurIslam** [comment]
Windows 10 ltsc 2021 21h2 19044.3448 tested the newer version of terminal , in this version of windows also did the same thing SecHealthUI uninstall and i am in administrator profile , 
here cmd and powershell works to drag and drop but as we see not working in win 11 , well should i check windows 11 with security apps ? may be it will works ?

**Comment by zadjii-msft** [comment]
This is basically unrelated to the OS version. The Terminal ships versions entirely separately from the OS. The code that checked if the Terminal was elevated or not didn't work exactly right before Terminal 1.18. I suspect if you install Terminal Preview (1.18), this will work for you.

**Comment by OurIslam** [comment]
now drag drop not works when i run as admin , 

https://github.com/microsoft/terminal/assets/3030547/81f367e8-6135-444d-a6dc-e7890b3f1f06

this windows is just installed nothing modification in security system , 
anyway the goal was drag drop file and folder path in admin cmd and powershell

**Comment by carlos-zamora** [comment]
Thanks for the feedback! Looks like this was fixed in #14946. So we'll mark this as a /dup of #13928.

Version 1.18 or higher should include a fix for this issue. You can download it from the [Releases page](https://github.com/microsoft/terminal/releases), microsoft store, or winget. Thanks again! :)
