### ISSUE TITLE
[1.19] Shell integration marks are totally in the wrong place

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#16034]
This was on 
Windows Terminal Canary
Version: 1.19.2643.0

![shell-integration-crazy-wrong](https://github.com/microsoft/terminal/assets/18356694/ad3c6d94-784c-4f9e-8f63-f28b60db776b)

Looks like the marks are like... off by one?

Possible culprits:
* #16006
* #15991 - 41f7ed73c - Nope, just reverting that didn't work.
* #15935 - 741633e - Nope, not this one either
* #15701 - 74748394c not this one

**Comment by zadjii-msft** [comment]
Looks like this is also busted in v1.19.2652.0

**Comment by zadjii-msft** [comment]
oh no, scrolling is really badly messed up 

![image](https://github.com/microsoft/terminal/assets/18356694/3b5ba58f-4323-4ec0-9e1a-8d94df7966b5)
![image](https://github.com/microsoft/terminal/assets/18356694/bcd689e1-1302-470b-8dfd-6635b642a44d)
![image](https://github.com/microsoft/terminal/assets/18356694/91d963fa-ebf2-4b2c-8c61-8b536a2e959c)

**Comment by zadjii-msft** [comment]
Bisecting. Starting by looking for a good commit around 

❔ ✅ ❌

* [x] ❌ 198c11f36 main 
* [ ] ...
* [x] ❔ c5e0908b9 Update cmd.exe FAQ (#15918)

**Comment by zadjii-msft** [comment]
4ddfc3eaf387b770530da8bb985bac9613063327 is the first bad commit
commit 4ddfc3eaf387b770530da8bb985bac9613063327

COOKED_READ_DATA: Fix scrolling under ConPTY (#15930)

**Comment by zadjii-msft** [comment]
Okay this is 100% due to:

https://github.com/microsoft/terminal/blob/cc2ba5350d115b6898ac8b92482d0af7b8c4d365/src/host/_stream.cpp#L79-L93

@lhecker how load bearing is that? I know that comment sounds super scary above it, but manually setting `needsConPTYWorkaround` to `false` definitely fixes the scrolling and marks issue.

**Comment by lhecker** [comment]
I'll fix #16044 and this issue in a single PR.
For #16044 I'll make it so that appending text only reprints the minimum amount of text that's necessary and for this issue I'll revert the above code entirely.

After all that, I'll reopen #15899 and leave it unfixed for the foreseeable future, because as much of a huge bug it is, I feel like fixing it is too difficult for the impact it has. To properly fix it, it always either required us to sacrifice on our Internationalization or to implement a pager, both of which are a pain to do (Unicode-)correctly. We have other issues that are much easier to fix and are hit much more often, right?

**Comment by zadjii-msft** [comment]
Totally cool with that. Tossing this one over to you then ☺️
