### ISSUE TITLE
[1.19] Serious regression in UIA notifications support (typed characters are sent as notifications)

### ISSUE THREAD

**Issue by codeofdusk** [microsoft/terminal#16044]
On Windows Terminal 1.19.2682.0 on Windows 11 22631.2338, a UIA notification for the current line is sent on every typed character. Since NVDA echos typed characters based on the user setting (each character/word/none at all), this is **extremely** disruptive.

The GitHub form didn't appear for me for some reason, happy to include any detail I've omitted. Please don't close this without further acknowledgement or engagement!

**Comment by DHowett** [comment]
Hey @codeofdusk! I am guessing that you're using Command Prompt? If so, @lhecker's recent input rewrite is almost certainly related. We redraw the entire command for each input. I thought that we had handling in Terminal to suppress those duplicate/overly long notifications...

**Comment by codeofdusk** [comment]
> Hey @codeofdusk! I am guessing that you're using Command Prompt?

No, `wt.exe`. `conhost` doesn't support UIA notifications at all as far as I understand.

**Comment by codeofdusk** [comment]
Oh, weird and weirder!

Since my default terminal is `wt`, I run `cmd` from the run dialog and the bug repros. But if I launch `wt` from run instead, the terminal that opens is fine, even if I start cmd from inside it (it defaults to PowerShell).

**Comment by lhecker** [comment]
I think your default terminal is probably Windows Terminal Preview, but your `wt` alias still points to the regular Windows Terminal.

Even in the old Windows Terminal it announce the entire prompt again and again if you were inserting text in the middle or beginning, right? 1.19 behaves as if this was always the case.

To fix this we'll simply reintroduce the same optimization we had before: When inserting at the end, we don't move the cursor and just write the new text out without reprinting the entire string. This will unfortunately also reintroduce certain edge cases, like the scrolling that happens when the prompt is longer than the viewport, but it'll fix this issue which is more serious.
