### ISSUE TITLE
PowerShell custom prompt bugs out last character on a "syntax error" line

### ISSUE THREAD

**Issue by azurenekowo** [microsoft/terminal#16210]
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.19045.0

### Steps to reproduce

My custom prompt is implemented via the following (added into `$profile`):
```powershell
function prompt {
     "$BASE[38;5;141m$env:username@$env:computername$BASE[38;5;228m: $BASE[38;5;250m$pwd $BASE[38;5;14m~#$RESET "
}
```

By default, it should show up as : `username@DESKTOP-xxxxxx: C:\Users\username ~#`

However, when I, say enter an invalid syntax (just typing `echo "`, not even executing it), it will bug out the last character (in this case, `#` with a red `m`). 

![image](https://github.com/microsoft/terminal/assets/67498765/19bb1170-48fc-4be4-a098-ea18747f9326)

It will persist until I press <kbd>Enter</kbd>, which executes the command and prompts again.
![image](https://github.com/microsoft/terminal/assets/67498765/3a0fee46-9e6a-4155-ba18-20bd8191de8e)

### Expected Behavior

It shouldn't bug out the last character of the prompt.

### Actual Behavior

It did bug out.  
![image](https://github.com/microsoft/terminal/assets/67498765/0394266b-140e-40b6-a235-fb1f5914e79d)

**Comment by j4james** [comment]
@azurenekowo As far I understand, this is a feature of PowerShell. When there is a syntax error in the command line, it redraws part of the prompt in red as a warning. However, in order for that to work correctly, it needs to know what your prompt looks like. You can control that with the `PromptText` option (see [Using the PromptText parameter](
https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.3#example-9-using-the-prompttext-parameter)).

I'm not sure why you're getting a red `m` though, since by default it should be a `>`. Is it possible that you've already set the `PromptText` option without realising it?

And if you don't want the prompt to change at all, you can probably just set the `PromptText` to a blank string.

**Comment by azurenekowo** [comment]
@j4james Hi, it worked. Thank you so much!

**Comment by 237dmitry** [comment]
I couldn't reproduce it either in Windows Terminal or in conhost.exe

![Screenshot 2023-10-22 173958](https://github.com/microsoft/terminal/assets/78153320/23eae13f-7cbc-40fb-a282-8ff9950646e6)
