### ISSUE TITLE
Windows PowerShell 5.1 not startable anymore

### ISSUE THREAD

**Issue by fubar-coder** [microsoft/terminal#16229]
### Windows Terminal version

1.138.2822.0

### Windows build number

10.0.22621.2428

### Other Software

Windows PowerShell 5.1

### Steps to reproduce

I installed the latest Windows Terminal and saw that I was unable to use the Windows Powershell.

![grafik](https://github.com/microsoft/terminal/assets/4739844/03f71c87-e0cd-4f7b-844d-c73725dc4a0a)

The error message basically means: "Internal Windows PowerShell error. Error 8009001d while loading the managed Windows PowerShell".

The reason for this bug is (probably) the new environment inheritance behavior.

### Expected Behavior

The Windows PowerShell should start without error

### Actual Behavior

The Windows PowerShell doesn't start anymore.

**Comment by lhecker** [comment]
We're tracking the issue over here: #16051
I'll thus be closing this issue in favor of the other one. /dup #16051

The issue occurs because you have null bytes in your environment variables in your registry. I wrote a script to find them: https://github.com/microsoft/terminal/issues/16051#issuecomment-1764546234
It'll tell you which registry keys are affected, which you could then fix by copying their contents into your clipboard and recreating them. Until we ship the bug fix you can also alternatively set the `"compatibility.reloadEnvironmentVariables": false` setting.

**Comment by fubar-coder** [comment]
@lhecker You were correct. I was able to find the broken environment variable using the script in https://gist.github.com/lhecker/393252fb1e95b3bc118d40ace802a505

It seems that the InnovaPhone installer is broken...
