### ISSUE TITLE
U+2594 doesn't render

### ISSUE THREAD

**Issue by Dan-Albrecht** [microsoft/terminal#16265]
### Windows Terminal version

1.19.2831.0

### Windows build number

10.0.22631.0

### Steps to reproduce

```pwsh
Write-Host "`n`n`u{2594}`n`n"
```

### Expected Behavior

On current mainline builds:
<img width="280" alt="image" src="https://github.com/microsoft/terminal/assets/7351388/a65bb296-8d1f-44db-8881-c588678fb68b">

### Actual Behavior

On preview+ builds:
<img width="291" alt="image" src="https://github.com/microsoft/terminal/assets/7351388/db7ba862-ad9a-41cc-ac5d-e2186d77ae79">

### Additional Information

This specific character was called out in #15489:

- At that time, turning off `Automatically adjust lightness of indistinguishable text` was suggested as a fix
  - I have this currently set to `Never`
- This is allegedly a font bug in _Cascadia Code_ as this character is outside its cell
  - Switching font to _Courier New_ fixes this, so might be the case this time. Not sure the render should be hacked to fix this vs. fixing the font.

**Comment by DHowett** [comment]
Thanks for filing! This is a specific case tracked in https://github.com/microsoft/terminal/issues/15359 -- with Cascadia, the entire glyph for U+2594 starts and ends outside of the bounding box. We cut off overhangs to avoid _specifically_ box-drawing and shade characters leaking outside of their cells. This of course doesn't work well with this design for U+2594 ☹️ 

/dup #15359 (since it tracks dealing with character overhangs better than we do currently)
