### ISSUE TITLE
In the Curl command it seems to lag or something else

### ISSUE THREAD

**Issue by skanda890** [microsoft/terminal#16309]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.2506

### Other Software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce

Type this in Administrator: Windows Power Shell

" curl github.com "

### Expected Behavior

It should at least be a response.

### Actual Behavior

Still no response.

**Comment by lhecker** [comment]
Your instructions don't involve telnet. Is there something missing?

**Comment by skanda890** [comment]
Can you check again?

**Comment by lhecker** [comment]
What should I check? Your issue description hasn't changed. It just says:
> Type this in Administrator: Windows Power Shell
>
> " curl github.com "

There's no mention of telnet. Did you mean curl?

**Comment by lhecker** [comment]
Ah I see you changed the title... In that case my next question would be:
* Does typing the command lag, or does it only lag after you press Enter?
* Does it lag less when you type `curl.exe github.com` (= with `.exe`)?

**Comment by skanda890** [comment]
It lags after I press Enter. It doesn't lag when I type .exe after curl. The response of curl github.com still didn't come.

**Comment by lhecker** [comment]
I'm confident to say that this also not a Windows Terminal issue, unfortunately.

A terminal is basically like a browser: We only do text rendering and the UI around the text, but we don't really have anything to do with application-specific issues like that. It's almost assuredly not us failing you to show a response, but rather `curl` not actually printing one in the first place. And we basically don't have any control over what `curl` does.

If I were you, I'd try to change my IP address and test my internet speed. I'd also never use `curl`, but only `curl.exe`, because as I said in the other issue, `curl` is an alias for `Invoke-WebRequest`, which is not the same as the true [curl](https://curl.se/). The true curl is vastly superior and much faster, so I'd always use that.

If you want to make sure that it's really not due to Windows Terminal, you can try this:
* Press Win+R
* Type `conhost powershell.exe` and press Enter
* Type `curl.exe github.com` and press Enter

If it also lags there then this is not a Windows Terminal issue. If it doesn't lag however, then please try it again in Windows Terminal. If it only lags in Windows Terminal and doesn't lag in "conhost", then please reopen this issue.

**Comment by skanda890** [comment]
Oh, okay.

**Comment by lhecker** [comment]
> The response of curl github.com still didn't come.

You know what, I think I just realized what you meant with "response didn't come"... You didn't mean that curl.exe hangs right? You just meant that there's no visible output?

Try typing this:
```
curl.exe -v github.com
```

`-v` stands for verbose (= detailed) mode. That way, curl will tell you exactly what it does under the hood. You'll then see:
```
*   Trying 140.82.121.3:80...
* Connected to github.com (140.82.121.3) port 80 (#0)
> GET / HTTP/1.1
> Host: github.com
> User-Agent: curl/8.0.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Location: https://github.com/
<
* Connection #0 to host github.com left intact
```

In other words, you're being redirected. There's two solutions to this:
* Use the proper, redirected URL: `curl.exe https://github.com/`
* Use `-L` which stands for "follow redirects" (The curl documentation is super helpful!)

I'd suggest doing the former in this case, because that way you only do 1 request instead of 2.

**Comment by skanda890** [comment]
> I'm confident to say that this also not a Windows Terminal issue, unfortunately.
> 
> A terminal is basically like a browser: We only do text rendering and the UI around the text, but we don't really have anything to do with application-specific issues like that. It's almost assuredly not us failing you to show a response, but rather `curl` not actually printing one in the first place. And we basically don't have any control over what `curl` does.
> 
> If I were you, I'd try to change my IP address and test my internet speed. I'd also never use `curl`, but only `curl.exe`, because as I said in the other issue, `curl` is an alias for `Invoke-WebRequest`, which is not the same as the true [curl](https://curl.se/). The true curl is vastly superior and much faster, so I'd always use that.
> 
> If you want to make sure that it's really not due to Windows Terminal, you can try this:
> 
> * Press Win+R
> * Type `conhost powershell.exe` and press Enter
> * Type `curl.exe github.com` and press Enter
> 
> If it also lags there then this is not a Windows Terminal issue. If it doesn't lag however, then please try it again in Windows Terminal. If it only lags in Windows Terminal and doesn't lag in "conhost", then please reopen this issue.

It lagged.

**Comment by skanda890** [comment]
> > The response of curl github.com still didn't come.
> 
> You know what, I think I just realized what you meant with "response didn't come"... You didn't mean that curl.exe hangs right? You just meant that there's no visible output?
> 
> Try typing this:
> 
> ```
> curl.exe -v github.com
> ```
> 
> `-v` stands for verbose (= detailed) mode. That way, curl will tell you exactly what it does under the hood. You'll then see:
> 
> ```
> *   Trying 140.82.121.3:80...
> * Connected to github.com (140.82.121.3) port 80 (#0)
> > GET / HTTP/1.1
> > Host: github.com
> > User-Agent: curl/8.0.1
> > Accept: */*
> >
> < HTTP/1.1 301 Moved Permanently
> < Content-Length: 0
> < Location: https://github.com/
> <
> * Connection #0 to host github.com left intact
> ```
> 
> In other words, you're being redirected and there's no other response from github (= no text). There's two solutions to this:
> 
> * Use the proper, redirected URL: `curl.exe https://github.com/`
> * Use `-L` which stands for "follow redirects" (The curl documentation is super helpful!)
> 
> I'd suggest doing the former in this case, because that way you only do 1 request instead of 2.

Can you tell me the final URL? Yes, I meant that, and the response which was shown above was correct.

**Comment by lhecker** [comment]
It's here
```
< Location: https://github.com/
```

So it's https://github.com/

**Comment by skanda890** [comment]
Huh, can you explain this?
