### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by demyte** [microsoft/terminal#1631]
# Summary of the new feature/enhancement

It would be great if the profiles.json would sync across users machines as other settings do in Windows using the users connected MSA and maybe a toggle for whether or not to sync.

**Comment by DHowett-MSFT** [comment]
We’re doing everything we can here apart from standing up our own server to do the syncing ... and we aren’t going to do that. I’ve seen my Terminal settings roam between my computers and it seems to work properly. There’s a couple issues caused by profile executables not existing on the machine to which they roam.

**Comment by demyte** [comment]
Thanks for the speedy reply @DHowett-MSFT 

Could I not be seeing this occur because I build from latest master source v's using the packaged preview?

I'll continue to monitor it and see if it starts to sync

**Comment by DHowett-MSFT** [comment]
Possibly! I’m not sure if “roaming” settings (which we’re using!) are supposed to roam here in 2019, but we can all figure that out together.
