### ISSUE TITLE
Error 0x80070002 faced during installation

### ISSUE THREAD

**Issue by Mr13Dan** [microsoft/terminal#16331]
### Windows build number

10.0.19045.0

### Steps to reproduce

run "winget install --id=Microsoft.WindowsTerminal -e" in the admin command line

### Expected Behavior

WT will install correctly.

### Actual Behavior

WTInstallFail
![image](https://github.com/microsoft/terminal/assets/26416516/b5cc30d8-06de-44f4-90e4-4a2608bee50e)
However, Microsoft.UI.Xaml 2.8 is installed on my system.
![image](https://github.com/microsoft/terminal/assets/26416516/6b04414a-f430-43e9-b872-fdae8a50f603)

**Comment by zadjii-msft** [comment]
(this may need to just go over to the winget repo)

What version of winget are you using/? I believe there was a package dependency resolution bug they just fixed in the latest version. 

Just looking at the output there, it's pretty clear you've got Microsoft.UI.Xaml v2.8.2208, and the Terminal requires >=2.8.2306

**Comment by Mr13Dan** [comment]
@zadjii-msft, I use v1.6.3133

**Comment by zadjii-msft** [comment]
Huh. Pretty sure https://github.com/microsoft/winget-cli/issues/163 was in 1.6+. 

This looks like a winget bug they're tracking: https://github.com/microsoft/winget-cli/issues/3166. I'd go add whatever logs you can over there. 

Thanks!
