### ISSUE TITLE
Does not handle ansi-bbs line drawing characters correctly

### ISSUE THREAD

**Issue by kalleswe** [microsoft/terminal#16346]
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19045.3693

### Steps to reproduce

Connect to any ansi bbs and you will see that line drawing characters/ansi is not properly displayed.

### Expected Behavior

Correct rendering of line drawing charachters/ansi

### Actual Behavior

blocky and round characheters and misalined gfx.

**Comment by lhecker** [comment]
Can you please enable "AtlasEngine" in the "Rendering" section of the settings and try it again?

**Comment by zadjii-msft** [comment]
Also, sharing the specific font you're using would be helpful too (if atlas engine doesn't fix it)

**Comment by j4james** [comment]
I suspect the issue is the character set. ANSI-BBS is typically going to expect you to be using code page 437 (or at least one of the other DOS code pages), and if you're connecting via a WSL telnet you're going to have UTF-8. That's the difference between something like this (using UTF-8):

![image](https://github.com/microsoft/terminal/assets/4181424/722018e3-c7c9-4325-a37d-1e86cdd84896)

and this (using code page 437):

![image](https://github.com/microsoft/terminal/assets/4181424/5f481f58-d37b-49b2-9830-50d222225260)

You may still encounter other issues, because the ANSI-BBS protocol is not fully compatible with VT terminals, but the character set will be the most obvious problem.

In terms of font choice, I find Consolas works better than Cascadia, and the new Atlas engine is better than the DX engine, but those differences aren't hugely significant.
