### ISSUE TITLE
Cyrillic messages on a en-us locale

### ISSUE THREAD

**Issue by VectorBCO** [microsoft/terminal#16395]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.0

### Steps to reproduce

I do not have exact steps to reproduce but:
I have Polish laptop with the en-us locale and after the last restart terminal started to be a russian language program
Everything and everywhere on my laptop use Polish local or English locale except terminal

![image](https://github.com/microsoft/terminal/assets/13451494/0f1d984c-a66b-4bd5-822d-b9f01409cfe3)
![image](https://github.com/microsoft/terminal/assets/13451494/0298821f-5d4b-41b4-8724-c9f5511f0aac)
![image](https://github.com/microsoft/terminal/assets/13451494/25beb10e-8dca-47c5-8848-7ee0e41e7144)
![image](https://github.com/microsoft/terminal/assets/13451494/ba87a768-f54b-4231-8adb-7ce8445419f0)

### Expected Behavior

I expect that Terminal as other my software will communicate with me in in English or at least in Polish
Searching information in russian is not what I`m dreaming about

### Actual Behavior

On a EN-US locale i have russian language terminal...

**Comment by j4james** [comment]
On the **Language** settings page, you need to scroll down a bit. In addition to the **Windows display language** there is a section labelled **Preferred languages**, which controls the translation of applications and websites. Make sure that you have **English (United States)** in that list (not just any other variant of English), and that it is higher up the list than Russian.

There is also a setting in Windows Terminal itself which can override the language. It's the first option in the **Appearance** section. And note that you'll need to restart Windows Terminal for the change to take affect.

![image](https://github.com/microsoft/terminal/assets/4181424/e5ab9546-d79b-4f28-82a1-7a0fb1325d2b)

**Comment by j4james** [comment]
Not all applications are available in every language, which is why the operating system lets you specify a list of language preferences. In the case of Windows Terminal, there isn't a Polish or Ukrainian translation yet, but there is a Russian translation. And by including Russian in the **Preferred languages** list, but not including English, you're telling the system that you prefer Russian over English.

Also note that there is an issue tracking requests for additional translations (#10667). Polish has already been requested, but if you'd also like to see a Ukrainian translation (or anything else), feel free add a comment on that issue.

**Comment by ViktorDronov** [comment]
as you can see there some other topics where unsufficient language selected by terminal and no one know why terminal select 2nd or 3rd language from the input lang list instead of system or app language...
