### ISSUE TITLE
`win+r > wt` dont work in 1.18.3181.0

### ISSUE THREAD

**Issue by ilcpm** [microsoft/terminal#16419]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.0

### Steps to reproduce

after update to 1.18.3181.0 from Microsoft store on win10, I could not start windows terminal by other programs use the command `wt`

I test for using `win+R` to run `wt`, then nothing will happen. by taskmanager I can see a wt thread open and immediately disappear.
![image](https://github.com/microsoft/terminal/assets/36830343/b3194e9e-fc66-45a9-951a-2b46717d1099)

but while I'm in the command line like powershell or wt, it can be open by the command `wt`
![image](https://github.com/microsoft/terminal/assets/36830343/340286e2-b84c-4588-bd36-e1fe93e8d1cc)
![image](https://github.com/microsoft/terminal/assets/36830343/e71841d5-750a-4c99-ad54-76fa33e0e88c)

### Actual Behavior

empty

**Comment by timadye** [comment]
I have the same issue. I can start Windows Terminal with the `wt` command from the Command Prompt, but can't start it from the Start Menu, either from the `Terminal` menu item, or with `Run` > `wt`.

As @ilcpm notes, it just gives me a "waiting" cursor for a second, but no window opens.

I see this with both the release (1.18.3181.0) and preview (1.19.3172.0) versions on two different Windows 10 22H2 systems.

**Comment by zadjii-msft** [comment]
I feel like we had another thread for this just recently, but I can't find it. The last one I can find has all sorts of notes about people disabling UAC, or otherwise attempting to mess with the permissions on WindowsApps 

### **NOTE**: Here's your reminder! NEVER mess with the permissions anywhere on `WindowsApps`! 
Doing that may irreversibly break your OS install. Like, literally no way to recover without reinstalling the OS. Don't ever do it.

**Comment by timadye** [comment]
Hi @zadjii-msft,

> I feel like we had another thread for this just recently, but I can't find it. The last one I can find has all sorts of notes about people disabling UAC, or otherwise attempting to mess with the permissions on WindowsApps
> NOTE: Here's your reminder! NEVER mess with the permissions anywhere on `WindowsApps`!

Thanks for the warning, but I don't think that could be what is happening, at least for me. This used to work a few weeks ago. I certainly haven't touched `WindowsApps` since then. Also, I get the same on a fresh install of Windows.

It may be correlated with the v1.18.3181.0 update. What's the best way to revert to the previous version to see if that helps?

**Comment by zadjii-msft** [comment]
Hmm, #13622 _might_ have been the latest report of this (though I still feel like there was a newer one than that). That thread was from like a year ago, and ultimately was root caused to the user disabling UAC (by setting EnableLUA=0). Turns out packaged apps really hate that. 

I think it's very curious that OP is also running elevated ("as admin"). Perhaps that has some interplay here. 

@timadye an idea might be to uninstall the Terminal, and go grab an earlier version off of https://github.com/microsoft/terminal/releases. 

~Or, another possibly dumb idea would be to install Terminal Preview (1.19), then go to the settings app for ["App Execution Aliases"](https://stackoverflow.com/questions/58296925/what-is-zero-byte-executable-files-in-windows/66539884#66539884) and switch `wt` to point at Terminal Preview instead. This would help rule out a bad MUX package install as a possible problem here.~ Derp I can't read, you already tried that

**Comment by ilcpm** [comment]
@zadjii-msft I have tried all UAC options, the result is the same

**Comment by lhecker** [comment]
> #### Works
> 5. Start Menu Run and type wt

This indicates that your issue is different from OP, right? Does this issue also happen without Open Shell? It's a fantastic extension, but I wonder if there might be a new incompatibility there... I'd say that it could be the search index too, but then I wouldn't understand why it happens with pinned taskbar items.

---

Maybe Windows Terminal is crashing during launch? You could follow this section and see if it results in a dump: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically

It's also possible that there might be relevant output visible when running [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview) simultaneously.

**Comment by timadye** [comment]
My tests with different versions of Windows Terminal, and the fact that this started in the last few weeks, indicate that this is probably something to do with updates to the Windows version, configuration, or other software.

I have Windows 10 Enterprise version 22H2, build 19045.3693. That's from KB5032189, installed on ‎18/‎11/‎2023, which *could* be when the problem appeared. Sorry, I don't remember exactly when it first started.

I see the issue on two different Dell laptops. The old one was initially installed in 2018. The new one was installed last week (29/11/2023). Both have similar software, though.

@zadjii-msft, your comment about UAC prompts me to note that we recently had [Admin By Request](https://www.adminbyrequest.com/) installed by our IT department. I *think* that was installed a bit earlier than when I started seeing the issue, but it's possible this is relevant.

**Comment by timadye** [comment]
> Does this issue also happen without Open Shell? It's a fantastic extension, but I wonder if there might be a new incompatibility there...

I can try uninstalling and see if it makes a difference, though I doubt it since I had the same version of Open Shell for a long time on my old laptop and this issue appeared recently.

Also, just to be clear: in my list above, I tried starting with both (2) the normal Windows Start Menu (shift-Start) and (4) the Open Shell menu (Start without shift).

**Comment by zadjii-msft** [comment]
Okay, so there are two separate things going on here. 

---

Problem the first: @ilcpm we think there might be an issue with app paths. If you just go toggle the app execution alias for `wt`, we think it might Just Work


----

Problem the second: @timadye we think there's probably a better dupe somewhere around here for what you're seeing, but we don't know off the top of our heads. Probably on in https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+label%3ACulprit-Centennial

**Comment by D-Maxwell** [comment]
> I feel like we had another thread for this just recently, but I can't find it. The last one I can find has all sorts of notes about people disabling UAC, or otherwise attempting to mess with the permissions on WindowsApps
> 
> ### **NOTE**: Here's your reminder! NEVER mess with the permissions anywhere on `WindowsApps`!
> Doing that may irreversibly break your OS install. Like, literally no way to recover without reinstalling the OS. Don't ever do it.

This has happened to me in the past, and after lots of fiddling around, resetting WindowsApps permissions to their defaults, and reinstalling affected packages, I can affirm it is in fact possible to recover from such a manipulation (on which I would like to know the internal reasons that make this a hassle in the first place ?)
