### ISSUE TITLE
make Windows Terminal available to v1809

### ISSUE THREAD

**Issue by fredless** [microsoft/terminal#1643]
# Summary of the new feature/enhancement

There are a significant quantity of corporate machines not able to run 1903 today for a variety of reasons (policy, compatibility, etc) and hence are locked out of terminal.  I wasn't able to find much discussion about the reasons that exist for 1903 to be a requisite.
![image](https://user-images.githubusercontent.com/16697069/60194952-211c6e00-97ef-11e9-9828-88cd61a9bdbe.png)

**Comment by JushBJJ** [comment]
In my guessing, there is probably a feature within the windows source code that is used in the new terminal which is why 1903 is required.

**Comment by ysc3839** [comment]
I guess it's because maintaining compatibility is a trouble. You CAN try to run on 1809 but without any support.

**Comment by DHowett-MSFT** [comment]
Sorry. Right now, there's two big blockers to adoption on 1809.

* XAML islands was a technology preview and didn't support high-DPI, DPI changes, or accessibility in 1809. We rely on them heavily.
* 1903 added support for side-by-side WinRT component activation, something deep in the COM stack that lets us find our DLLs when they're right next to our EXE.

We just can't go back to 1809.

**Comment by fredless** [comment]
> We just can't go back to 1809.

TY for the detail

**Comment by brunofin** [comment]
> We just can't go back to 1809.

Please Microsoft, fix the Surface Book 2 then! 😭

**Comment by NetMage** [comment]
It looks like WInUI 3.0 will backport full XAML Islands support to most versions of Windows 10 and is releasing this year - could you use WinUI 3.0 to add support for Windows Terminal on earlier versions of Windows 10?

**Comment by zadjii-msft** [comment]
That's certainly a possibility we'd have to investigate. If XAML Islands was detached from the platform, then I'm not sure how many of our own features are actually dependent upon 1903.

I guess Dustin mentioned the SxS winrt activation above - I'm not _positive_ that is still needed, but if it is, then that might be exceptionally hard for us to overcome. That would be one of the things to investigate when WinUI 3.0 is available.

**Comment by superm1** [comment]
> WinUI 3.0

It seems to me that there is now a preview available for it: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/

**Comment by zadjii-msft** [comment]
> XAML Islands is not supported in this release

That's the single most important part of the WinUI stack we need, so unfortunately, that's a non-starter for us. Don't worry, we work pretty closely with the WinUI team (in the same hallway in fact), so when WinUI 3 is ready for us to move to it, we'll work on it 😉

**Comment by sidietz** [comment]
WinUI 3.0 Preview 2 has been released some days ago. Anything new on LTSC support?

https://docs.microsoft.com/en-us/windows/apps/winui/winui3/

**Comment by DHowett** [comment]
I've gone ahead and marked up their list of limitations with ones that stop us from being able to use Preview 2:
![image](https://user-images.githubusercontent.com/189190/87824055-6a3fc580-c829-11ea-8ca7-8d18cc0e9ec3.png)

**Comment by zadjii-msft** [comment]
![image](https://user-images.githubusercontent.com/18356694/87823948-fe198d80-c839-11ea-818d-4b4cf5d7fecf.png)


As I've said before, we won't be able to start experimenting with WinUI 3.0 until there's support for XAML Islands.

**Comment by driver1998** [comment]
Can we migrate the whole app to WinUI on Desktop instead of a Win32 Window with XAML islands?

**Comment by zadjii-msft** [comment]
@driver1998 At some point sure. 

Last I checked (and this was a while ago), it would still be a while before WinUI3 supported custom content in the titlebar, and host backdrop acrylic. We fairly aggressively customize our own titlebar, and a lot of users really like acrylic and would be sad to see it go. 

Now, that was a while ago, and priorities might have changed since then. So those features might be supported in the official first WinUI 3 release. 

We've also got to balance the needs of our own engineering efforts. Moving to WinUI 3 would probably mean a whole month for a dev of just porting code and making sure nothing breaks. That's a month that we can't use on any of the other things that we've already committed to for Terminal v2. The WinUI 3 project layout is _far_ nicer and will probably be better in the long run, but right now the Terminal's `.sln` is a bit of a house of cards. It's got a bunch of carefully constructed hacks in it to make sure the Terminal builds _just right_. Making sure those hacks still work in WinUI 3 is what would take the majority of the time. 

WinUI 3 is probably one of the higher Terminal v3 priorities, it's just not in the cards for v2. We'd rather stick with the devil we know for now.

**Comment by sidietz** [comment]
After another three months having passed:
Is there any update on the WinUI3 transition?

**Comment by DHowett** [comment]
No, and it is neither in our roadmap nor committed or planned to ever happen. :smile:

**Comment by chucker** [comment]
If I'm not mistaken, this means a Windows Server 2019 machine can't run Windows Terminal at all — the current release for that is still 1809. (And you can't do an in-place upgrade to a newer release, because those are on a different channel.)

**Comment by DHowett** [comment]
You are not mistaken.
