### ISSUE TITLE
Error while running `chkdsk c: /f` command

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#16498]
### Windows Terminal version

1.18.3181.0

### Windows build number

Win 10 22H2 19045.3693

### Steps to reproduce

Open Terminal, type `chkdsk c: /f` command and press enter

---

I honestly don't know if it was a bug or not, I just wanted to report it here.

### Expected Behavior

It should show the following warning as the `Windows Command Prompt` says.

`Chkdsk cannot run because the volume is in use by another process. Would you like to schedule this volume to be checked the next time the system restarts? (Y/N)`

### Actual Behavior

Terminal shows the following warning saying access is denied.

```
Access Denied as you do not have sufficient privileges or the disk may be locked by another process.
You have to invoke this utility running in elevated mode and make sure the disk is unlocked.
```
![terminal-wcp](https://github.com/microsoft/terminal/assets/153795294/d2369c96-b598-4ddc-b1ba-1392f57aee95)

**Comment by o-sdn-o** [comment]
Have you tried running Windows Terminal as Administrator? 

You have Command Prompt running as Administrator, and the terminal as a regular user.

**Comment by zadjii-msft** [comment]
Yea, despite your screenshot labeling the Terminal window as "Administrator", it doesn't have any of the hallmark signs of actually being launched as admin - the titlebar doesn't have a shield, the tab title is missing "Administrator", and CMD started in your user profile directory, instead of system32. 

Does this work if you actually launch the Terminal as admin? Or moreover, how did you attempt to launch the Terminal as admin/?
