### ISSUE TITLE
Cannot input Hanja(한자) from Korean(한글) IME keyboard.

### ISSUE THREAD

**Issue by 3735943886** [microsoft/terminal#16537]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22631.2861

### Steps to reproduce

Simply type any completed korean character (at least one consonant + one vowel, ie ㄱ+ㅏ=가).
Press hanja(한자) key.
Select any hanja from pop up.

### Expected Behavior

The korean character should be changed to selected hanja chanracter.

### Actual Behavior

Nothing.

https://github.com/microsoft/terminal/assets/9522390/82fcf5b3-fe87-4083-9179-1b661705bcbf

**Comment by lhecker** [comment]
In #14349 I've come to the realization that we need to replace the IME implementation in Windows Terminal with the one from conhost. That one is much more robust and we expect it to fix issues like yours. While your issue and #14349 aren't exactly the same I'd still like to use #14349 to track this, since it's older and got more history. Your can subscribe to that issue to be notified of my progress on this. Thanks for giving me another test case with which I can test my changes though!
