### ISSUE TITLE
User default browser when opening file:/// URLs of HTML pages

### ISSUE THREAD

**Issue by Vampire** [microsoft/terminal#16548]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19045.3693

### Steps to reproduce

Ctrl+Click a file:/// URL that points to an HTML page

### Expected Behavior

file:/// URLs of HTML pages should be launched in the default browser, not some other

### Actual Behavior

If you have an http:// URL, the default browser is properly launched.
But if you have a file:/// URL, a different browser is launched.
If you for example run a Gradle build with failing tests, you get a file:/// URL pointing at the test report HTML.
Opening this starts not the default browser, but a different browser.

**Comment by DHowett** [comment]
Thanks for filing!

Terminal just tells the desktop shell to open the file. Because it points at a _file_, it will use the _file handler_ associated with `.html` files. It will _not_ use the default handler for `http` and `https` URLs, because it is not one of those.

You can configure the default handler for `.html` files in Settings. Search for "choose a default app for each type of file".

![image](https://github.com/microsoft/terminal/assets/189190/c3fdbc7c-56cc-43d8-8ba9-8fab7e19d713)

**Comment by Vampire** [comment]
Oh, thanks, you are fully right, sorry.
Unfortunately, the BrowserSelector App is not selectable there, but I guess its author needs to do something for that.
