### ISSUE TITLE
Hide 'Open in Terminal' context menu item when running Preview?

### ISSUE THREAD

**Issue by NebularNerd** [microsoft/terminal#16563]
# Description of the new feature/enhancement

I tend to run Terminal Preview not regular Terminal, can we have an option to hide `Open in Terminal` so we don't have two terminal context menu items? Potentially even remove `Preview` from the preview context item?

![image](https://github.com/microsoft/terminal/assets/8470449/9b52d478-b777-4528-be60-8488990438e3)

# Proposed technical implementation details (optional)
I've tried the following regedit below which is on various sites, but it removes both entries which is obviously not what we want.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked]
"{9F156763-7844-4DC4-B2B1-901F640F5155}"=""
```

**Comment by lhecker** [comment]
I'm not sure if hiding the non-Preview version when the Preview version is installed is something that I would want, personally speaking. After all, it's completely fine for you to uninstall the non-Preview version of Windows Terminal.

In other words: If you don't ever want to use the non-Preview version, you can just uninstall it.

The said, the UUID for Preview is `02db545a-3e20-46de-83a5-1329b1e88b6b`. If you didn't add that UUID into your registry, but both entries vanished from the context menu, you were simply encountering an Explorer bug. In fact, that bug happens quite often in my experience. For instance, when I reboot the first time I open the context menu none of my Windows Terminal entries will be there. The second time I open it, they'll be there. This has been happening to me ever since 2021 on various devices.
As such, I'll close this issue, as I believe that this is not a Windows Terminal bug (and the Explorer bug I described is known to them IIRC).
