### ISSUE TITLE
Bug Report - RunAs / CPAU  opens separate CMD window outside of Terminal

### ISSUE THREAD

**Issue by jricha34** [microsoft/terminal#1656]
# Environment

Windows build number: [10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
None

# Steps to reproduce
runas /user:someuser cmd 
enter password of someuser

# Expected behavior
Open another CMD within Terminal

# Actual behavior
Opens CMD outside of Terminal in CMD standalone window. 

In general I was trying to figure out how to open a terminal window from the command line in alternate creds and couldn't sort it out. I got access denied when trying to launch. 

Something I regularly do is use runas /netonly or cpau (www.joeware.net) to launch CMD with alternate creds which locally is whatever user I am logged into the PC with but remotely is the alternate credentials. For example I will open up CMD windows in creds from say 5-10 different disconnected AD Forests. Then as I need to manage the different forests I jump to the proper CMD window and run the commands I need to run.

As an aside, I am thrilled to see all of this work being done for command line access. There are quite a few of us who have been managing Windows and eventually AD from the command line since NT4 in the late 90s.

   joe (joe@joeware.net)

**Comment by DHowett-MSFT** [comment]
Thanks for the detailed report! I'm going to have to bounce you to the `sudo` megathread, #1032 
Right now, two things:

1. You're using a shell fixture to launch cmd.exe directly -- it cannot reintegrate back into Windows Terminal (#492) because it's using the traditional launch mechanism for all console applications.
2. Mixed-user scenarios are out of scope for terminal v1, and we've been fighting the uphill battle with the security folks for longer than this repository has existed :smile:
