### ISSUE TITLE
Ubuntu WSL2 is broken when opening from Run

### ISSUE THREAD

**Issue by garysassano** [microsoft/terminal#16584]
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.19044.3930

### Steps to reproduce

If I open Ubuntu from Terminal:

![image](https://github.com/microsoft/WSL/assets/10464497/bec4ceb9-4e88-45dc-9ffb-89a16061fb75)

![image](https://github.com/microsoft/WSL/assets/10464497/6a668933-4964-4e9c-9a1f-14c8bcf56e9b)

But if I open Ubuntu from Run command:

![image](https://github.com/microsoft/WSL/assets/10464497/b9f3114d-10a7-4e99-8c17-8b7bd2d9ad37)

![image](https://github.com/microsoft/WSL/assets/10464497/5db6abec-5ed9-49b1-a4d3-9b0422d85430)

### Expected Behavior

I expected no difference in opening Ubuntu WSL2 from a tab in Terminal or from a Run command.

### Actual Behavior

Terminal behaves differently based on how you start the Ubuntu WSL2 shell.

**Comment by carlos-zamora** [comment]
Thanks for filing! Looks like this is caused by the existence of two ubuntu profiles (one provided by us and one by Ubuntu). We're actually tracking that over in #12582. So we'll mark it as a \dup of #12582.

In the meantime, we recommend you move your font settings to the "defaults" section. That should be a nice workaround.
