### ISSUE TITLE
MINGW / Git Bash is not using Unicode / UTF8

### ISSUE THREAD

**Issue by yaohy2014** [microsoft/terminal#16596]
### Windows Terminal version

 1.19.3172.0

### Windows build number

10.0.22621.2428

#### open windows preview with git-bash
![image](https://github.com/microsoft/terminal/assets/118656244/ec6c7982-87b8-4712-80c3-ed665b3a9aaa)

#### write some Chinese words，like "你好"
![image](https://github.com/microsoft/terminal/assets/118656244/058b00bb-30e5-4670-bc08-dffef366f64d)

#### enter backspace button, delete all . The $ is deleted at the same time.
![image](https://github.com/microsoft/terminal/assets/118656244/7528bb8b-322e-4ea1-b818-af48a3168151)

### Expected Behavior

The $ will not be deleted

### Actual Behavior

The $ is deleted

**Comment by lhecker** [comment]
You need to use `bash.exe --login -i` to run mingw bash. Can you check your profile's commandline and ensure those two parameters are there?

**Comment by yaohy2014** [comment]
> You need to use `bash.exe --login -i` to run mingw bash. Can you check your profile's commandline and ensure those two parameters are there?
> 
> Edit: I've updated the title to make it easier to find it in the future.


It works. Thanks a lot. So why does it work when adding "--login -i"?

**Comment by lhecker** [comment]
I'm glad to hear that this resolved your issue!

`--login -i` is what "Git Bash" uses (the application in the start menu), so it's probably a good idea to use it no matter what since they use it.

That said, `--login` puts bash into a login mode which ensures that your bash profile is being read and `-i` puts it into the interactive mode which ensures that you get a proper interactive prompt (otherwise it's effectively just a script interpreter).

You can read more about it here:
* `--login`: https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
* `-i`: https://www.gnu.org/software/bash/manual/bash.html#Interactive-Shells
