### ISSUE TITLE
p10k prompt is not displayed correctly with AtlasEngine

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#16664]
### Windows Terminal version

1.19.10302.0

### Windows build number

22631.3085

### Other Software

WSL Ubuntu latest
ZSH
p10k (rainbow theme)
MesloLGS Nerd Font (from p10k repo)
9px font size

### Steps to reproduce

Setup `zsh`, `p10k`, set rainbow theme by using `p10k configure`
Select `MesloLGS NF` with a font size of 9px in the terminal settings with AtlasEngine enabled.

### Expected Behavior

Smooth borders of the prompt, like in this screenshot with AtlasEngine disabled
![image](https://github.com/microsoft/terminal/assets/35394377/9098e73d-ff97-401e-8b2d-ca633fd149be)

### Actual Behavior

Incorrect prompt rendering
![image](https://github.com/microsoft/terminal/assets/35394377/6b9d2921-1cf1-446d-96fd-2a7ce240ca61)

**Comment by lhecker** [comment]
Given your font size of 9pt (FYI: not px - our font sizes are in pt) and an apparent line height of 15 pixels, I'm assuming that you're using a display scale of 100%, right?

In that case, please delete your Meslo NF font and then download and install the latest version here: https://www.nerdfonts.com/font-downloads (At the time of writing the direct link is: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Meslo.zip)

This is because I found that the issue you've described does not occur on my PC in that case:
![image](https://github.com/microsoft/terminal/assets/2256941/247e7719-c026-480b-b49f-6cb93a1a88d4)

But you can see there that the "s" in ssh has the exact same pixel height as yours and the white box is also 15px tall. BTW this is super opinionated, but I personally definitely recommend enabling ClearType if you're using a 100% scale monitor. It'll add a somewhat ugly blue line in the rounded box, but it'll make the text a lot more legible in my opinion.

That aside, you can set fractional font sizes which allows you to solve this issue under most circumstances.

Lastly, I consider this an issue with the font itself, as we simply draw the glyphs exactly as they were designed. The only text renderer simply didn't have this issue because it cut off any overly large glyphs or distorted them if necessary. That has caused a ton of issues in the past and I personally don't wish to open that can of worms again. 😟 But this is a common issue with a lot of fonts (including our own Cascadia Code), and we intend to ship this workaround at some point: #5897

As such I'll close this issue for now and I'd suggest upvoting and following #5897 if you're interested in seeing this resolved properly in the future (we loosely use upvotes to see what features to implement in the future).

**Comment by Mystic8b** [comment]
> This is because I found that the issue you've described does not occur on my PC in that case:

Your example has the same problem. One pixel bottom part is missing
![image](https://github.com/microsoft/terminal/assets/35394377/20f5dfb5-eaa2-4109-a22f-858c4fef82ac)

**Comment by lhecker** [comment]
The bottom pixels are cut off because DirectWrite defaults to `DWRITE_RENDERING_MODE_DEFAULT` which seems to ignore the GASP table at small font sizes. If I explicitly use `DWRITE_RENDERING_MODE_NATURAL_SYMMETRIC` it works as expected:
![image](https://github.com/microsoft/terminal/assets/2256941/8a593aba-50a7-4fdb-8188-e763f1c5c5b5)

If other more people would be interested in making this configurable, we could consider adding it as a setting.
