### ISSUE TITLE
Can't start Windows Terminal after installation

### ISSUE THREAD

**Issue by saw-lau** [microsoft/terminal#16685]
### Windows Terminal version

1.19.10302.0

### Windows build number

10.0.19045.0

### Other Software

App Installer 1.21.3482.0.

### Steps to reproduce

1. Download Microsoft.WindowsTerminal_1.19.10302.0_8wekyb3d8bbwe.msixbundle from Releases.
2. Double click to install via App Installer.
3. After installation launch.

### Expected Behavior

Terminal launches.

### Actual Behavior

The following error is displayed:

C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10302.0_x64__8...\WindowsTerminal.exe

File system error (12175).

![image](https://github.com/microsoft/terminal/assets/1907363/1cba6f77-bd59-44e9-a22a-bb0a93cbaaab)

**Comment by saw-lau** [comment]
If I download the standalone [Microsoft.WindowsTerminal_1.19.10302.0_x64.zip](https://github.com/microsoft/terminal/releases/download/v1.19.10302.0/Microsoft.WindowsTerminal_1.19.10302.0_x64.zip), unzip this and run WindowsTerminal.exe from there it works.

**Comment by lhecker** [comment]
12175 is either one of these 2 failures:
* `ERROR_INTERNET_DECODING_FAILED`
  > WinINet failed to perform content decoding on the response. For more information, see the [Content Encoding](https://learn.microsoft.com/en-us/windows/win32/wininet/content-encoding) topic.
* `ERROR_WINHTTP_SECURE_FAILURE`
  > One or more errors were found in the Secure Sockets Layer (SSL) certificate sent by the server. To determine what type of error was encountered, check for a [WINHTTP_CALLBACK_STATUS_SECURE_FAILURE](https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nc-winhttp-winhttp_status_callback) notification in a status callback function. For more information, see [WINHTTP_STATUS_CALLBACK](https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nc-winhttp-winhttp_status_callback).

I'd say you've likely encountered a temporary outage in the app store's backend. Does the issue still occur?

**Comment by lhecker** [comment]
> I'm trying to install this on a corporate laptop which doesn't have access to the Windows Store and is behind a proxy - I wonder if that's the issue?

Yes that's an issue. The `.msixbundle` is effectively the same as installing from the app store and just like there, it requires internet access initially for "online activation". [^1]

Instead, you need to use an "offline" installation. Our documentation for that is here: https://learn.microsoft.com/en-us/windows/terminal/distributions
Please let me know if you have any issues with that! I'll be closing this issue in the meantime, since we unfortunately can't do anything about it.

[^1]: We're often asked why this is, but we can't answer that because we simply don't know either. This is solely in the hands of the folks who made .msix and the app store.
