### ISSUE TITLE
Wait before drawing the frame when receiving ESC[2J

### ISSUE THREAD

**Issue by a-usr** [microsoft/terminal#16723]
# Description of the new feature/enhancement
Wait before drawing ( or creating ) a frame when ESC[2J (Clear Screen) is received until either a set time (e.g. 2 ms)  has passed or additional data is received from stdout or stderr. This is to prevent flickering caused by applications (that do frame-based rendering, e.g TUI applications) that clear the screen before writing the next frame to it. If such a feature already exists, I propose making the timeout higher.

Worth noting is that the Flickering seems to be more intense on windows 11 vs on windows 10. Do the two platforms have different max framerates or is the framerate not capped at all and its caused by a hardware difference?

# Proposed technical implementation details (optional)

**Comment by a-usr** [comment]
For additional context, appaently the Flickering doesnt seem to be an issue with other terminals like WezTerm, but I havent tested this myself.

**Comment by lhecker** [comment]
In the current architecture it would be slightly difficult to implement this right now, but it would be generally possible long term. Your suggestion wouldn't work well over SSH though. Other terminals have since adopted iTerm2's synchronized update sequence (BSU = 2026) which does what you'd like but in a more robust manner. You can read about it here: https://gitlab.com/gnachman/iterm2/-/wikis/synchronized-updates-spec
Support for BSU is tracked in #8331. If that matches what you want, then I believe we should continue tracking this in #8331.

That said, and unrelated to the above, if you use the very latest Windows Terminal version and if you ensure to write your sequences in a single "packet" using the Windows APIs (= `WriteFile` on stdout) then it should not flicker.
C's `printf` for instance has an internal buffer size of 4KiB and any `printf` larger than that will chunk it up which causes flickering. WSL also does some buffering internally which causes the same thing. But if you use a native Windows function to write your output and buffer it properly then it should already work.

**Comment by a-usr** [comment]
Thanks for the explanation and the references! Also huge thanks to you for taking your time and taking a look at almost every single issue👍

**Comment by a-usr** [comment]
Also I was wondering, is there any functionality to see when Windows Terminal receives a packet and what its contents are?
