### ISSUE TITLE
Unable to open Windows Terminal any more

### ISSUE THREAD

**Issue by cmarkwick365** [microsoft/terminal#16747]
### Windows Terminal version

 1.19.10302.0

### Windows build number

10.0.22631.3155

### Steps to reproduce

I'm getting a similar issue as #16730 .  I don't have macType.  I just click on terminal from the start menu and nothing happens.  The dialog doesn't even flash up,  and nothing in the event log.

### Expected Behavior

Should open

### Actual Behavior

The odd thing is that if I open Powershell (x64) it will open.  But if I try to open a new tab, it crashes with this:

Faulting application name: WindowsTerminal.exe, version: 1.19.2401.30002, time stamp: 0x65b9ada4
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.3155, time stamp: 0xa0b6eeba
Exception code: 0xc000027b
Fault offset: 0x0000000000873530
Faulting process id: 0x0x71E8
Faulting application start time: 0x0x1DA65063E2CFEFC
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10302.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 49a8f447-eb8c-4473-94b1-5c94f3088e53
Faulting package full name: Microsoft.WindowsTerminal_1.19.10302.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by cmarkwick365** [comment]
Btw I already tried repairing and uninstalling/re-installing.

**Comment by carlos-zamora** [comment]
Thanks for filing. Could you capture a trace using Feedback Hub? This'll help us look into the issue further.

/feedback

**Comment by zadjii-msft** [comment]
\<bot hat>

Hi there!<br><br>Can you please send us feedback with the [Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) with this issue? Make sure to click the "Start recording" button, then reproduce the issue before submitting the feedback. Once it's submitted, paste the link here so we can more easily find your crash information on the back end?<br><br>Thanks!<br><br>![image](https://user-images.githubusercontent.com/18356694/140811502-a068f78b-89d2-4587-925a-73e19652b830.png)<br><br>![image](https://user-images.githubusercontent.com/18356694/140811557-cdc22a0f-fa6a-4f6a-953e-73b51f5548a3.png)<br><br>![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

**Comment by cmarkwick365** [comment]
Captured on Feedback Hub

**Comment by c0ony** [comment]
I am having the same issue on a fresh win 11. It was working on this computer with no issues before a bad GPU install wrecked everything and I was forced to do a full reinstall of win11. Now, the terminal won't open at all, even though I can open PowerShell and Command Prompt with no issues.

**Comment by carlos-zamora** [comment]
> Captured on Feedback Hub

Thanks! Would you mind sharing the link so we could look at it?

**Comment by Samary1999** [comment]
Reinstall Terminal, try to turn off Settings-Rendering-Use the new text renderer("AtlasEngine) may help.

**Comment by Samary1999** [comment]
Reinstall Terminal, try to turn off **Settings-Rendering-Use the new text renderer("AtlasEngine")** may help.

**Comment by cmarkwick365** [comment]
@Samary1999 I already had renderer("AtlasEngine")  set.

**Comment by cmarkwick365** [comment]
Waiting for feedback.  Still an issue.

**Comment by zadjii-msft** [comment]
@cmarkwick365 When you filed feedback, you need to click this button:
https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png

And paste the link it generates here. Otherwise, it's impossible for us to find the feedback you filed. Thanks!

**Comment by cmarkwick365** [comment]
@zadjii-msft Here is the feedback link
https://aka.ms/AApeuqb

**Comment by zadjii-msft** [comment]
```
{
 "version": 7,
 "providerName": "Microsoft.Windows.Terminal.App",
 "hresult": "2147942402",
 "fileName": "C:\\__w\\1\\s\\src\\cascadia\\TerminalApp\\AppActionHandlers.cpp",
 "lineNumber": "459",
 "module": "TerminalApp.dll",
 "failureType": "2",
 "message": "",
 "threadId": "11248",
 "callContext": "",
 "originatingContextId": "0",
 "originatingContextName": "",
 "originatingContextMessage": "",
 "currentContextId": "0",
 "currentContextName": "",
 "currentContextMessage": ""
},
{
 "version": 7,
 "providerName": "Microsoft.Windows.Terminal.App",
 "hresult": "2147942402",
 "fileName": "C:\\__w\\1\\s\\src\\cascadia\\TerminalApp\\TabManagement.cpp",
 "lineNumber": "92",
 "module": "TerminalApp.dll",
 "failureType": "1",
 "message": "winrt::hresult_error: The system cannot find the file specified.",
 "threadId": "11248",
 "callContext": "",
 "originatingContextId": "0",
 "originatingContextName": "",
 "originatingContextMessage": "",
 "currentContextId": "0",
 "currentContextName": "",
 "currentContextMessage": ""
},
```

at the bottom of `TerminalPage::_OpenNewTab`

https://github.com/microsoft/terminal/blob/563b7312b62fd68596ccb4a66af6217852f77ed9/src/cascadia/TerminalApp/TabManagement.cpp#L92


```
{
 "version": 7,
 "providerName": "Microsoft.Windows.Terminal.Connection",
 "hresult": "2147942402",
 "fileName": "C:\\__w\\1\\s\\src\\inc\\til\\env.h",
 "lineNumber": "132",
 "module": "TerminalConnection.dll",
 "failureType": "1",
 "message": "",
 "threadId": "11248",
 "callContext": "",
 "originatingContextId": "0",
 "originatingContextName": "",
 "originatingContextMessage": "",
 "currentContextId": "0",
 "currentContextName": "",
 "currentContextMessage": ""
},
{
 "version": 7,
 "providerName": "Microsoft.Windows.Terminal.Connection",
 "hresult": "2147942402",
 "fileName": "",
 "lineNumber": "0",
 "module": "TerminalConnection.dll",
 "failureType": "1",
 "message": "C:\\__w\\1\\s\\src\\inc\\til\\env.h(150)\\TerminalConnection.dll!00007FFD4FBF9160: (caller: 00007FFD4FBE7049) Exception(1) tid(2bf0) 80070002 The system cannot find the file specified.\r\n",
 "threadId": "11248",
 "callContext": "",
 "originatingContextId": "0",
 "originatingContextName": "",
 "originatingContextMessage": "",
 "currentContextId": "0",
 "currentContextName": "",
 "currentContextMessage": ""
}
```

https://github.com/microsoft/terminal/blob/9acb15b626571f145c551cca93407954592e40bd/src/inc/til/env.h#L150

interesting...

**Comment by zadjii-msft** [comment]
Wild. Pretty sure this is around

https://github.com/microsoft/terminal/blob/9acb15b626571f145c551cca93407954592e40bd/src/inc/til/env.h#L423-L428

can you run `conhost -- cmd` from the Run dialog, then run `set`, and copy-paste the output here[^1]? Looks like there's some env var somewhere in there that's blowing up our env var loader/?

Alternatively, testing if this repros the same in [1.20 preview](https://github.com/microsoft/terminal/releases/tag/v1.20.10572.0)

[^1]: this may have some amount of PII in it

**Comment by zadjii-msft** [comment]
Specifically the dumps reference [Terminal v1.18.3181.0](https://github.com/microsoft/terminal/releases/tag/v1.18.3181.0). There was one last 1.18 servicing release, [Terminal v1.18.10301.0](https://github.com/microsoft/terminal/releases/tag/v1.18.10301.0), which had a couple additional fixes in it, but nothing that immediately stands out.

**Comment by cmarkwick365** [comment]
![image](https://github.com/microsoft/terminal/assets/43414070/4438c0c4-2fd6-4c66-9ecc-c8acaa2781f6)

**Comment by zadjii-msft** [comment]
Weird, but okay 🤷 feedback hub is wack sometimes. The env vars might still be helpful.

**Comment by cmarkwick365** [comment]
Still waiting for a resolution.

**Comment by mhjartstrom** [comment]
> Reinstall Terminal, try to turn off **Settings-Rendering-Use the new text renderer("AtlasEngine")** may help.

Not quite sure I'm seeing the exact same issue, but turning off "AtlasEngine" seems to help me... My WindowsTerminal has crashed frequently the last week or so, sometimes e.g. when doing git log but also when rescaling the window, creating crash dumps and logs quite similar to the original poster's crash log above.

I can't tell when the "AtlasEngine" was enabled by default, but I'm running 1.19.10573.0 and according to [https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-20-release/] the "AtlasEngine" was enabled by default in the 1.20 preview release? Hence I should not have been affected by this, still I am (or at least was until now)...

I've not had a crash all day, since I disabled it. Before that, Windows Terminal had become useless and I had to run wsl.exe from the Command Prompt instead.

**Comment by cmarkwick365** [comment]
@mhjartstrom Thanks for the suggestion.  It did not make a difference.

**Comment by jmpecx** [comment]
> Reinstall Terminal, try to turn off **Settings-Rendering-Use the new text renderer("AtlasEngine")** may help.重新安装终端，尝试关闭设置-渲染-使用新的文本渲染器（“AtlasEngine”）可能会有所帮助。

you save me a lot

**Comment by zadjii-msft** [comment]
Another idea: 
* Does running `cmd` from the Run dialog open Command Prompt in the Terminal?
* Does `wt -w 0 new-tab --inheritEnvironment` work to open a new tab/?

**Comment by lhecker** [comment]
@mhjartstrom @jmpecx The option to disable AtlasEngine will go away in the future. Could you please assist me in figuring out why it crashes? To do so, please enable AtlasEngine again and send me a crash dump. You can find my email address in my GitHub profile. Here's how to enable crash dumps: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-automatically

**Comment by cmarkwick365** [comment]
@lhecker Email sent with dump file/

**Comment by mhjartstrom** [comment]
@lhecker Email sent with dump file.

**Comment by lhecker** [comment]
@mhjartstrom Thanks for the dump! Unfortunately I can't quite pinpoint the origin of the heap corruption. Would you be willing to help me further test this?

If so, one thing I'd like to test is whether Windows Terminal Canary crashes for you. You can install it here: https://aka.ms/terminal-canary-installer
After installing it, make sure it has imported all your settings from your regular Windows Terminal. (Otherwise open the settings file with Ctrl+Shift+, in both applications and copy it over.)

**Comment by mhjartstrom** [comment]
@lhecker OK, I've sent another crash dump for when using Windows Terminal Canary.

**Comment by cmarkwick365** [comment]
@lhecker resent dump file.  Canary had the same behavior.

**Comment by cmarkwick365** [comment]
@lhecker I take it that you noticed this in the dump I sent?
FAILURE_BUCKET_ID:  STOWED_EXCEPTION_XAML_TEXT_Class_not_registered_80040154_Microsoft.UI.Xaml.dll!winrt::hresult_error::hresult_error

**Comment by lhecker** [comment]
@cmarkwick365 For others it's crashing due to a heap corruption, but your terminal is crashing in an entirely different place. I believe your system may be corrupted, because I can see:
```
*** WARNING: Check Image - Checksum mismatch - Dump: 0x12261cd, File: 0x1226255 - C:\Symbols\sym\Windows.UI.Xaml.dll\E6498AA71226000\Windows.UI.Xaml.dll
```

I would suggest checking your system with `chkdsk`, `dism` and `sfc`. For instance:
```
chkdsk C: /f
dism /Online /Cleanup-image /Restorehealth
sfc /scannow
```

If it is a corruption of `Windows.UI.Xaml.dll`, it may be necessary to reinstall Windows. I'm not 100% sure if it's a corruption though - I certainly haven't seen this warning before.

---

@mer30hamid @mhjartstrom I'll address you both in this comment, because I've asked both of you for dumps and both of you have heap corruptions.

Coincidentally, you also both use 8+ year old Intel Graphics drivers. Can you check if there's a newer driver available for you? You can find instructions on how to find the latest drivers here: https://www.intel.com/content/www/us/en/support/articles/000005629/graphics/processor-graphics.html

In theory it should be one of these 2 drivers: https://www.intel.com/content/www/us/en/search.html#sort=relevancy&f:@tabfilter=[Downloads]&f:@stm_10385_en=[Graphics,Processor%20Graphics,Intel%C2%AE%20HD%20Graphics%20Family]&f:@operatingsystem_en=[Windows%2011%20Family*]
(I know I selected Windows 11 there, but I think this is fine. If you go to each of the driver's pages it'll say that it's compatible with Windows 10.)

**Comment by mer30hamid** [comment]
> @cmarkwick365 For others it's crashing due to a heap corruption, but your terminal is crashing in an entirely different place. I believe your system may be corrupted, because I can see:
> 
> ```
> *** WARNING: Check Image - Checksum mismatch - Dump: 0x12261cd, File: 0x1226255 - C:\Symbols\sym\Windows.UI.Xaml.dll\E6498AA71226000\Windows.UI.Xaml.dll
> ```
> 
> I would suggest checking your system with `chkdsk`, `dism` and `sfc`. For instance:
> 
> ```
> chkdsk C: /f
> dism /Online /Cleanup-image /Restorehealth
> sfc /scannow
> ```
> 
> If it is a corruption of `Windows.UI.Xaml.dll`, it may be necessary to reinstall Windows. I'm not 100% sure if it's a corruption though - I certainly haven't seen this warning before.
> 
> @mer30hamid @mhjartstrom I'll address you both in this comment, because I've asked both of you for dumps and both of you have heap corruptions.
> 
> Coincidentally, you also both use 8+ year old Intel Graphics drivers. Can you check if there's a newer driver available for you? You can find instructions on how to find the latest drivers here: https://www.intel.com/content/www/us/en/support/articles/000005629/graphics/processor-graphics.html
> 
> In theory it should be one of these 2 drivers: [https://www.intel.com/content/www/us/en/search.html#sort=relevancy&f:@tabfilter=[Downloads]&f:@stm_10385_en=[Graphics,Processor%20Graphics,Intel%C2%AE%20HD%20Graphics%20Family]&f:@operatingsystem_en=[Windows%2011%20Family*]](https://www.intel.com/content/www/us/en/search.html#sort=relevancy&f:@tabfilter=%5BDownloads%5D&f:@stm_10385_en=%5BGraphics,Processor%20Graphics,Intel%C2%AE%20HD%20Graphics%20Family%5D&f:@operatingsystem_en=%5BWindows%2011%20Family*%5D) (I know I selected Windows 11 there, but I think this is fine. If you go to each of the driver's pages it'll say that it's compatible with Windows 10.)

I tried to update my intel graphic driver but no update available for it, I have dual graphic processor and switched to NVIDIA and problem is gone!

![image](https://github.com/microsoft/terminal/assets/1561497/6ffe13fa-172b-4069-b361-f1db5ebb4b43)

**Comment by mhjartstrom** [comment]
@lhecker There is no newer Intel graphics card driver as far as I can tell. But it's working splendidly without the AtlasEngine, so I take it that this is caused by something that you do, not that Intel does?

**Comment by lhecker** [comment]
It's unfortunate to hear that the newer drivers don't work for you! I was hoping you two would be using a 6th gen Intel CPU or newer, because then you could use the 30.* series drivers that I've linked above.

> But it's working splendidly without the AtlasEngine, so I take it that this is caused by something that you do, not that Intel does?

Graphics drivers run in user-mode nowadays, within each process (within WindowsTerminal.exe). If the driver has a bug then this can cause the application to crash. Normally, I wouldn't assume that it's a driver bug, but given that @mer30hamid can resolve this issue by simply switching to his Nvidia GPU, it makes me very, very suspicious of your Intel GPU drivers. AtlasEngine has no vendor-specific code, so no matter whether you use your Intel or any other GPU, the exact same code with the exact same inputs should be running. If it's crashing with one GPU driver but not the other then this is somewhat suspicious.

The reason it works when AtlasEngine is disabled is because the older text renderer is based on Direct2D which uses older and simpler graphics APIs. However, AtlasEngine has an internal mode to use Direct2D as well, which is currently only activated when it runs on very old GPUs.

So my idea to resolve your issue is to simply add a setting to Windows Terminal that forces it to use Direct2D for rendering. @mhjartstrom If you want to help test my idea can you try running these commands?
```
d3dconfig apps --add WindowsTerminal.exe
d3dconfig device feature-level-limit=9_3
```
Afterwards, restart Windows Terminal. Does it still crash then?

When you're done with testing I would recommend running
```
d3dconfig --reset --confirm
```
and disabling AtlasEngine again.

**Comment by mer30hamid** [comment]
> can you try running these commands?
> ```
> d3dconfig apps --add WindowsTerminal.exe
> d3dconfig device feature-level-limit=9_3
> ```
Yes! 


> Afterwards, restart Windows Terminal. Does it still crash then?

No ! no crash anymore even I enabled the "AtlasEngine" option

After running this command: `d3dconfig --reset --confirm` windows terminal crashed again by resizing, so I disabled "AtlasEngine" again.

**Comment by mhjartstrom** [comment]
> ... @mhjartstrom If you want to help test my idea can you try running these commands?
> 
> ```
> d3dconfig apps --add WindowsTerminal.exe
> d3dconfig device feature-level-limit=9_3
> ```
> 
> Afterwards, restart Windows Terminal. Does it still crash then?
>
I would very much like to help out, as I'm eager to have this issue resolved, but now I'm on vacation two weeks starting today... I'll be sure to try this out as soon as I'm back - if you still want me to, or are you on a deadline for this?

**Comment by cmarkwick365** [comment]
Windows Terminal started working again for me again.  Whatever was in the latest release must have fixed it.

**Comment by zhangbaozhe** [comment]
> Reinstall Terminal, try to turn off **Settings-Rendering-Use the new text renderer("AtlasEngine")** may help.

This worked. I opened Windows Terminal in Admin mode and changed the settings. It worked. Thanks!

**Comment by cmarkwick365** [comment]
> > Reinstall Terminal, try to turn off **Settings-Rendering-Use the new text renderer("AtlasEngine")** may help.
> 
> This worked. I opened Windows Terminal in Admin mode and changed the settings. It worked. Thanks!

That wasn't the issue.  It resolved itself after an update.

**Comment by lhecker** [comment]
Many of you are probably using MacType which had a bug that made us crash (to be clear, it's not a bug in Windows Terminal). Since this comes up relatively often, we have recently added some code to detect the outdated MacType versions here: #17369

**Comment by MatthewBM** [comment]
The above fixes did not work for me on Win11. I found that my User Profile Environment had some Nvidia Cuda Paths that were incorrect. To test this I was able to run wt.exe fine with powershell: 

```
$env:CUDA_PATH = $null
$env:CUDA_PATH_V12_0 = $null
$originalPath = $env:PATH
$env:PATH = ($env:PATH -split ';' | Where-Object {$_ -notlike "*CUDA*" -and $_ -notlike "*NVIDIA*"}) -join ';'
wt.exe
```

The permanent fix was to go to Win + X → System → Advanced System Settings → Environment Variables and delete any System Variables with CUDA_* or NVIDIA_* and then restart computer
