### ISSUE TITLE
Taskbar icon creates new terminal when restoring from notification area

### ISSUE THREAD

**Issue by JVimes** [microsoft/terminal#16774]
### Windows Terminal version

1.20.10303.0

### Windows build number

10.0.19045.0

### Other Software

n/a

### Steps to reproduce

1. Pin WT to taskbar
2. Enable "Hide Terminal in the notification area when it is minimized"
3. Minimize
4. Click the WT taskbar icon

### Expected Behavior

Restore the window from notification area (no new terminal tab).

### Actual Behavior

Window is restored with a new terminal tab.

**Comment by carlos-zamora** [comment]
Thanks for filing. This is consistent with how other multi-instance apps are hidden in the tray. The taskbar does not know that Terminal is running, so it ends up launching a new instance.

Clicking the taskbar icon creates the new instance, whereas the notification area icon can be used to bring it back.

**Comment by JVimes** [comment]
Thank you @carlos-zamora, but that's not really true.

- Restoring a minimized window doesn't add a new tab to it. Restoring a hidden window shouldn't. It's the same case to the user.
- The taskbar behavior is fine because WT can end the superfluous instance. We know because the "attach to recent window" feature works.

I hope you'll consider reopening this issue.

**Comment by lhecker** [comment]
You're not restoring a minimized window though, because in your example the terminal is not minimized to the taskbar. Instead it's hidden (not minimized) in the notification area. This distinction is important, because "restoring" a window from the taskbar obviously only works if there's a window in the taskbar in the first place. But you don't have a window in the taskbar, you only have a pinned application.

You're right though that some application work differently. Steam for instance allows you to click its pinned symbol and restore the main window. But that's different from us, because unlike Steam, we're a tabbed, multi-window application and so there's no single window for us to restore. In fact, we can't even tell what your intention was (restore VS open a new tab), because clicking on a pinned application in the taskbar is identical to running it with Win+R or from the start menu.
