### ISSUE TITLE
Command prompt: cursor shape won't change from Insert/Overwrite mode

### ISSUE THREAD

**Issue by Hexaae** [microsoft/terminal#16785]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.3155

### Steps to reproduce

Open MS-DOS command prompt.
Change Insert/Overwrite mode from your physical keyboard.

### Expected Behavior

Cursor shape should change to let you notice you're in Insert or Overwrite cursor mode.

### Actual Behavior

Cursor shape stays always the same.

**Comment by j4james** [comment]
The blocking issue for this is #7382. We need to pass on the request for the overwrite-mode cursor via conpty, which requires an equivalent escape sequence for the half-height block cursor, but there isn't a standard way to achieve that.

It's also worth noting that this particular cursor change is achieved with an internal `SetCursorDBMode` call, which toggles the "double cursor" mode, independent of the actual cursor size - it's not using the public `SetConsoleCursorInfo` API. So that's something we need to bear in mind if we want to get this working in conpty.

**Comment by carlos-zamora** [comment]
Thanks for filing. We're going to mark this as a /dup of #7382
