### ISSUE TITLE
disable tracking

### ISSUE THREAD

**Issue by 3052** [microsoft/terminal#16806]
### Windows Terminal version

1.12.220314002

### Windows build number

 10.0.18363.0

### Steps to reproduce

not sure if its powershell or Windows Terminal, but running the shell I am getting several calls to

https://dc.services.visualstudio.com/v2/track

### Actual Behavior

I tried $env:POWERSHELL_TELEMETRY_OPTOUT=1 as well

**Comment by 3052** [comment]
note I also did: Office 365, we could go to File > Options > Trust Center > Trust Center Settings > Privacy Options > View Diagnostic Data > Disable View data viewing.

**Comment by zadjii-msft** [comment]
That doesn't look like something Terminal is requesting ourselves. A couple ideas:

* Does this repro for all shells? 
* Do you have the Visual Studio profiles enabled? 
  * If so, does this repro if you change the `icon` of those profiles?


Also, 1.12/? That version is like... two years old. Does this repro on an updated version? (I'd suspect that since this doesn't look like something we're doing, a newer version won't change this, but it's always easiest to debug as close to `main` as possible 😄)

**Comment by 3052** [comment]
> * Does this repro for all shells?

seems like just PowerShell

> * Do you have the Visual Studio profiles enabled?

I dont even know what that is. to my knowledge I do not have Visual Studio installed at all, just Microsoft 365

> Also, 1.12/? That version is like... two years old. Does this repro on an updated version?

yes, just tried with the current release as problem remains

**Comment by zadjii-msft** [comment]
> seems like just PowerShell

Great! That sounds like something you should bring up with them over at https://github.com/PowerShell/PowerShell/

Thanks!
