### ISSUE TITLE
Unexpected rendering behavior with U+1xxxx Unicode characters

### ISSUE THREAD

**Issue by sba923** [microsoft/terminal#16856]
### Windows Terminal version

 1.20.10572.0

### Windows build number

10.0.22621.0

### Other Software

PowerShell 7.4.1
PSReadLine 2.3.4

### Steps to reproduce

1. Define the PSReadLine chord handler at https://github.com/PowerShell/PSReadLine/issues/3578#issuecomment-1987149796
2. Enter

`'1f369` and hit `Alt+x`

### Expected Behavior

I would expect

![image](https://github.com/microsoft/terminal/assets/12860484/ee1c464b-6e86-443d-b12b-1dc36dbf23f2)

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/12860484/6e9690a8-679e-4f29-9879-22f4f3d39cbd)

The emoji is rendered only after typing a closing `'`

![image](https://github.com/microsoft/terminal/assets/12860484/70168555-196b-463f-9b37-1aca9866958a)

**Comment by elsaco** [comment]
Alacritty does it also:

![wt_16856_1](https://github.com/microsoft/terminal/assets/3933920/44828625-ef15-4ec5-a03a-6e6adc7305c8)

![wt_16856_2](https://github.com/microsoft/terminal/assets/3933920/59afc312-6019-41c1-841f-1c3cfd41399c)

**Comment by lhecker** [comment]
Unfortunately, PSReadLine doesn't support supplementary Unicode planes (= U+1xxxx) to begin with so this cannot be fixed in Windows Terminal. For instance, try pasting 🍩 and then backspace. You'll have to backspace twice, presumably because PowerShell internally sees it as the surrogate pair U+D83C U+DF69 and it doesn't know what a surrogate pair is. But just to be sure, I've debugged your repro test and sure enough, PowerShell sends us a literal "??" string.

It may be worth mentioning that Windows Terminal also has poor Unicode support. While it does support supplementary Unicode planes, it fails to support zero width joiners and marks, which means that emojis right now look like this:
![image](https://github.com/microsoft/terminal/assets/2256941/12ddf852-5dca-488f-b307-29c73acf327a)

The upcoming version 1.21 is planned to fix this and it'll then look like this:
![image](https://github.com/microsoft/terminal/assets/2256941/31b6e478-35f7-432a-afff-c659d1fb69d8)

**Comment by sba923** [comment]
Thanks for the clarification.

This was triggered by checking out https://github.com/StartAutomating/Emoji.

Probably doable to live with some limitations...
