### ISSUE TITLE
1.19.10573 version of the terminal will conflict with the Windows font rendering program MacType

### ISSUE THREAD

**Issue by iray1024** [microsoft/terminal#16866]
### Windows Terminal version

1.19.10573

### Windows build number

10.0.22635.0

### Other Software

MacType 2021.1-rc

### Steps to reproduce

After enabling rendering on MacType, starting the terminal through win+r will directly crash.

错误应用程序名称: WindowsTerminal.exe，版本: 1.19.2402.26003，时间戳: 0x65dce3ea
错误模块名称: MacType64.Core.dll，版本: 1.2021.507.1，时间戳: 0x6094e4a5
异常代码: 0xc0000005
错误偏移量: 0x0000000000005ea9
错误进程 ID: 0x0x644C
错误应用程序启动时间: 0x0x1DA744E54E4FC6E
错误应用程序路径: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
错误模块路径: E:\Tools\MacType\MacType64.Core.dll
报告 ID: 7447b2c3-83fb-4c40-b733-eeef06bde436
错误程序包全名: Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe
错误程序包相对应用程序 ID: App

### Expected Behavior

normal

### Actual Behavior

Terminal Flashback.

**Comment by zadjii-msft** [comment]
Yep, there's a known bug in MacType that can cause crashes in the Terminal. Fortunately, they have already fixed it - I'd go update MacType. 

* See also #15792, #16730 and upstream: https://github.com/snowie2000/mactype/issues/607
* /dup https://github.com/snowie2000/mactype/pull/938
* The fix is in https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31

**Comment by iray1024** [comment]
ok，thanks for your attention !
