### ISSUE TITLE
Any use of `FindFontWithLocalizedName` is broken and requires refactoring

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#16943]
From #16821

> Font features and axes have multiple blocking bugs right now anyway (I mean even without this PR), so I figured that we can do a follow-up refactoring later where we fix both issues: The existing bugs and the incompatibilities introduced by this one. I'm half done making the changes to fix this and they're highly related

**Comment by zadjii-msft** [comment]
@lhecker I was told this was blocking for 1.21 - are we fine shipping 1.21 with this?

**Comment by lhecker** [comment]
No. I'm currently working on this issue.

Technically this should be a trivial change but funneling this into XAML turns out is harder than writing the renderer lol. "Oh this doesn't have a ItemsSource you need to instantiate UI elements yourself. Oh this is only a getter, needs a manual injection. Oh you can't set Items in the Click handler or it gets unresponsive. Oh you can't have generic types in a DataTemplate, needs a custom wrapper. Oh you can't reference the VM from inside a DataTemplate. Oh…" Hilarious lol.
