### ISSUE TITLE
Bug Report - Can't type pipe "|" and quick edit mode doesn't work

### ISSUE THREAD

**Issue by TheMMcOfficial** [microsoft/terminal#1697]
# Environment

```none

Microsoft Windows [Version 10.0.18362.175]
terminal version 0.2.1715.0
```

# Steps to reproduce

I have a Canadian Multilingual keyboard ant to do a pipe symbol I have to use the right alt and the key before the 1 on a us layout I don't kown which one it is but on my keyboard is a slash (/). 

# Expected behavior

Able to write a "|" without pasting it and able to copy thing in the terminal window.

# Actual behavior

The other bug I found is that I can't copy paste something. Normally, with quick edit enable you do select the text + "enter" or right click on the window title copy. The paste works.

**Comment by miniksa** [comment]
Using AltGr for symbols is a dupe to #521.
Your copy/paste issues could be one of a multitude of things assigned to @carlos-zamora.

Please file one issue per bug that you find.
Please search for existing issues for your concerns before filing new ones.

Otherwise, thanks for your feedback. I'm closing this issue as it's duplicate data.
