### ISSUE TITLE
Georgian text overlaps

### ISSUE THREAD

**Issue by Joeeeeb5** [microsoft/terminal#16981]
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.19045.4239

### Steps to reproduce

Type text in Georgian

### Expected Behavior

Text shouldn't overlap

### Actual Behavior

Georgian text overlaps and isn't readable
![image](https://github.com/microsoft/terminal/assets/125207782/02b1a0cd-1830-41a7-9d8e-bf39009966c9)

**Comment by lhecker** [comment]
When it comes to Georgian I have very very bad news...
Unicode's [UAX #11: East Asian Width](https://unicode.org/reports/tr11/) specifies how many columns a given character is supposed to take up, even for characters that aren't used in East Asia.
"ლ" for instance is [U+10DA in Unicode](https://codepoints.net/U+10DA) and for whatever reason its width is explicitly specified as "Narrow". 🤦

_However_, the good news is that there's exactly 1 (one) modern font in the entire world which supports monospace Georgian: DejaVu Sans Mono.

On top of that, there are two more up to date clones/forks of that font:
* "Menlo" by Apple is a font you can't use because Apple's licensing terms only allow it to be used on their devices. Since I don't want you to violate those terms I urge you to definitely avoid visiting this page: https://github.com/ueaner/fonts
  It's recently been replaced by "SF Mono" which doesn't support Georgian.
* "Hack" is another clone, but it's open source and is the default font for KDE. You can find it here: https://sourcefoundry.org/hack

Out of all of these, I recommend using Hack since it's the most modern one. If you download Hack, I recommend against using their .exe installer. Just download the .zip instead, extract it, select all 4 files, right click and select to "Install for all users":
![image](https://github.com/microsoft/terminal/assets/2256941/1f2b55ce-68c6-4b51-93f7-d53f5ec789c6)

Installing fonts for only your own account has been broken for a long time on Windows.

There may be other monospace fonts, but I bet that if it's not a derivative of DejaVu Sans Mono, it won't support Georgian. The only exception is "GNU Unifont" but that's not a font you'll want to use. 😅
