### ISSUE TITLE
After Reboot custom fonts give error until settings window is opened/closed

### ISSUE THREAD

**Issue by YouveGotMeowxy** [microsoft/terminal#17042]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.19045.4291

### Other Software

I do have Ubuntu running in WSL, however, it happens in Ubuntu tabs as well as Powershell (I use Powershell 7)

### Steps to reproduce

- Reboot computer
- start Windows Terminal
- get error(s) (happens on both PowerShell and WSL (Ubuntu) tabs. Also, all special characters for addons like Oh My Zsh and Oh My Psh get screwed up.
- No mnatter how many times I close/reopen or open new tabs, I get the same error until.....
- I click the Settings cog and the settings window opens
- No changes need to be made; don't even need to click the save button. Just click the X to close the settings page.
- from there on (until next reboot) no more font errors, and the special character fonts for things like Omz/Omp show properly.

### Expected Behavior

No errors and my fonts show properly. :)

### Actual Behavior

Examples:

![image](https://github.com/microsoft/terminal/assets/39491297/dab51bc1-2a76-4512-a0df-34342e71ec4f)

![image](https://github.com/microsoft/terminal/assets/39491297/07fc3ed4-3e7c-4164-99cd-a23d26968b09)

**Comment by lhecker** [comment]
Windows caches font information between reboots in two places:
* `%LOCALAPPDATA%\Microsoft\FontCache`
* `C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache`

Additionally it also caches font information per process.

Now when you install a font, this causes Windows Terminal to not find it, because Terminal's internal (per process) font cache doesn't get invalidated when you install fonts. Once we address #17034 (an issue extremely similar to yours), that will be fixed, because we'll simply ask Windows "Hey, do you have new fonts installed?".

In your case on the other hand, the system font cache between reboots is broken. This can be due to two reasons: Either one of the two directories above is corrupted, or the "Font Cache" service is not running.

---

Can you please press Win+R and run `services.msc`. Then scroll down to "Windows Font Cache Service". It should be set to "Automatic" and should be running:
![image](https://github.com/microsoft/terminal/assets/2256941/7795f939-f0ad-4875-8000-1b17cde46ab5)

If yours wasn't running, please try that and let us know whether that fixed your issue.

---

The following may fix your issue. I have done it before and it fixed this exact issue for me, however it's very much unsafe. It may break your system. In fact, one time it did break my system and I had to restore the Font Cache service manually. This is because the Font Cache service is not particularly robust (which is also why it's broken for you and so many others).

If you know Windows, you know what the Font Cache service is and you trust yourself doing it, you could attempt it. If it breaks your system and you don't know how to restore it, **_no one may be able to help you_**.

So, to be absolutely clear: ⚠️ **Doing this is not recommended.** ⚠️

That said, the Font Cache uses the aforementioned directories for its databases:
* `%LOCALAPPDATA%\Microsoft\FontCache`
* `C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache`

Technically you need to delete both. 90% of the safety risk comes from deleting the 2nd database however. So obviously we'll first try to delete only the former and see if it fixes the issue.

To do so, you can do the following:
* Launch pwsh or powershell **as admin**
* Exit all applications, *including background applications*. This step is crucial or the next one won't work consistently and your system may break.
* `sc stop FontCache`
* `rm -Recurse -Force $env:LOCALAPPDATA\Microsoft\FontCache\*`
* `sc start FontCache`
* Reboot, etc., to test whether it works

If that didn't fix the issue, you may have a corrupted system font cache. Fixing that one is dangerous and somewhat difficult. It consists of multiple layers and we may have to delete all of them. This may leave your system in a broken state though. It can be recovered by restoring the files from another system. In any case, I recommend making backups of the files in that directory.

Most importantly though, **DO NOT USE EXPLORER TO GAIN ACCESS**. Do not modify the access rights of that directory in any way.

The per-user cache in the system font cache directory can be deleted by first stopping the FontCache service as before and then running something like this:
```
rm -Force "C:\Windows\ServiceProfiles\LocalService\AppData\Local\FontCache\*$((New-Object -ComObject Microsoft.DiskQuota).TranslateLogonNameToSID((Get-WmiObject -Class Win32_ComputerSystem).Username))*"
```

If that didn't work, you can still try to delete the entire `FontCache` directory contents (contents! not the directory itself, only the contents!). However, once again, that's even riskier. I'm not entirely sure if it restores the `Fonts\fontset-2017-04.json` file in that case. If it doesn't restore it you can get it [here](https://fs.microsoft.com/fs/windows/fontset-2017-04.json).

**Comment by DHowett** [comment]
@lhecker wow, that’s comprehensive. I was just gonna guess that they’d installed their font “per user” rather than “for all users” :)

**Comment by lhecker** [comment]
Oh, I thought that it broke the font until you reinstalled it after a reboot, and that it can't be fixed by clicking Save in the settings. But looking through related issues that indeed doesn't seem true. I've edited my large comment above accordingly.

**Comment by YouveGotMeowxy** [comment]
Got it! Thank you both for pointing me in the right direction.

I was going to pass on the scary font cache deletions, but it sent me off on a deep investigation into the fonts. I'm not sure why, but I could see those particular fonts in `c:\windows\fonts`, but the weren't being shown in the Fonts Control Panel. I don't know if that might mean as @DHowett was saying; that it was installed for the User only, and not system?

Either way, I copied out those fonts do another folder, deleted them from that Windows path, and then dropped them onto the Fonts Control Panel which installed them again. Now, after testing with a reboot, no more errors. wewt!

thank you guys, that was incredibly annoying!

**Comment by Tgentil** [comment]
@lhecker worked for me. Thank you so much.

**Comment by mgua** [comment]
I had the issue. windows 11, admin account. windows terminal not showing hack nerd font anymore. font available and usable in other applications. I closed every istance of windows terminal, opened file explorer, and went to c:\windows\font. found the "hack" fonts: 3 icons, and simply copied them to an empty folder: 12 .ttf files appeared there. Then i deleted the 3 icons from the font folder, and they did not go away. had to repeat. then opened windows terminal and the hack fonts were not available. closed terminal, went back to font folder, and just dragged back the 12 ttf files there. After this windows terminal was able to "see" the hack fonts again without issues. Thank you [YouveGotMeowxy](https://github.com/YouveGotMeowxy)
[Kacey](https://github.com/YouveGotMeowxy)

**Comment by arafatm** [comment]
I had to add to .bashrc

```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
```

**Comment by wertstahl** [comment]
You can also reboot into service mode, then  ( | = enter)   cmd to  
c:  | go to windows c: root
cd C:\WINDOWS\ServiceProfiles\LocalService\AppData\Local\FontCache | 
dir | << to make sure >>
del asterisk.asterisk | asterisk = the star thingy, cannot put it here for security reasons
y | (confirms deletion)
exit | (=reboot) 

and all will be gone and fine and rebuilt upon next boot. dont be scared.
! it will take quite some time to rebuild all the font caches next time you type something in like photoshop. just wait. no need to be scared !
