### ISSUE TITLE
Enable the user to set the location of settings.json

### ISSUE THREAD

**Issue by iwino** [microsoft/terminal#17060]
## Problem

Currently, the location of `settings.json` is fixed to be either one of the three locations only:

![image](https://github.com/microsoft/terminal/assets/128335079/0d1983a4-031b-4a79-8b0e-053a9f60caf5)

## Proposal

Give the user the ability to specify the location via an environment variable, so that the user doesn't have to create any garbage windows shortcut inside some weird folder that ends with some random nonsense like `8wekyb3d8bbwe`.

## Use case

By allowing the user to specify the location of `settings.json` cleanly (i.e. without resorting to creating a windows shortcut), it also enables the user to cleanly move it to a folder where the user might have config files for other applications all under one folder.

For example, I use a number of applications on Windows and they all either respect `XDG_CONFIG_HOME` and/or `XDG_DATA_HOME`, or provide their own custom environment variables that enable me to move config and data files to a folder of my choice (without having to create garbage shortcuts), making them very easy for me to find as the files are very neatly organized "under one roof".

**Comment by zadjii-msft** [comment]
FWIW, `8wekyb3d8bbwe` actually isn't just "randome nonsense" - it's actually part of the Terminal's unique identifier that we get from the Microsoft Store. `%localappdata%\packages\{{package family name}}\LocalState` is kinda the well-known path for a package to put their data. 

You may also be interested in [Portable Mode](https://learn.microsoft.com/en-us/windows/terminal/distributions#windows-terminal-portable), though, that lacks the benefit of auto-updating.

Otherwise, we've  also got the following threads:
* #6687
* #2933
