### ISSUE TITLE
Search highlights are gone if the window is resized 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#17073]
v1.20.11072.0 (bug bash on 4/16)

They shouldn't stick around after a resize

**Comment by lhecker** [comment]
I may be doing something wrong, but it seems to still occur.

**Comment by tusharsnx** [comment]
If you have already introduced the throttled func, you still need to clear the search at the time of resize otherwise they render relative to the old buffer 🤔

**Comment by lhecker** [comment]
OH.

**Comment by lhecker** [comment]
> [...] and we should absolutely not because that's going to be announced as results being cleared

BTW I've removed the event and replaced it with
* An "output is idle" event, which gets thrown whenever there wasn't any output for 100ms
* `ControlCore::Search()` returns a `SearchResults` struct

`TermControl` owns `ControlCore` and because of that IMHO the former should be in charge of deciding when to call into the latter. Whenever `ControlCore` raises this generic "output is idle" event, `TermControl` calls `_core.Search()` and handles updating the UI synchronously. That way no search update event is needed.

> So, when the renderer tries to read in between the pending call, it should get an empty list for the duration. Later, the throttled call would refresh the results and mark them as fresh again.

I may be misunderstanding you again, but you're suggesting to clear the search results after the reflow and then trigger a search update asynchronously, right? That's the same thing I had in mind. 🙂
