### ISSUE TITLE
Add keyboard shortcuts to increase and decrease font size (or zoom)

### ISSUE THREAD

**Issue by wizll** [microsoft/terminal#1708]
It would be nice to quickly increase the size of my font (similar to zooming in a web browser). (ctrl)+(+) and (ctrl)+(-)

**Comment by jefflomax** [comment]
CTRL Mouse Up/Down works and is consistent with existing shell

**Comment by dnagl** [comment]
@wizll I will take a attemt to solve this feature request

**Comment by dnagl** [comment]
I've done a implementation for this feature request.
Waiting for code-review and merge :)

**Comment by DHowett-MSFT** [comment]
Since you've put out a pull request for this, I'm going to mark it as triaged and accept it for v1.0 :smile:

**Comment by hwinkler** [comment]
The above PR seems to have died and never been accepted. Just want to register my interest in this feature. A key combination (as in VS Code and many other examples) Ctrl plus/minus is essential because the existing Ctrl+ scroll support is awkward on a touchpad. A terminal program ought not assume the presence of any pointing or scrolling device. It's a terminal.

I hope the team will complete this effort.

**Comment by awarmfastbear** [comment]
I am surprised that this hasn't been implemented yet, hopefully the CR can be revived / finalized.

**Comment by dsafa** [comment]
I'm interested in seeing this feature done. I can try and continue where the PR left off if thats ok.

**Comment by zadjii-msft** [comment]
@dsafa Go for it!
