### ISSUE TITLE
Stale output outside the window when switching from fullscreen to windowed mode

### ISSUE THREAD

**Issue by tusharsnx** [microsoft/terminal#17108]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.22631.0

### Steps to reproduce

1. Open Windows Terminal
2. Go into fullscreen mode with alt+enter
3. Do another alt+enter to go back to window mode.

### Expected Behavior

Everything looks fine, and we're in windowed mode.

### Actual Behavior

We're in windowed mode, but the screen still has terminal output stuck in place and that's also outside the app's window frame.

https://github.com/microsoft/terminal/assets/55626797/0b44c73c-065f-428e-b98b-c8c7d6af6019

**Comment by lhecker** [comment]
We've seen this issue reported to us before. For instance: #14865
I've also seen the issue with my Nvidia GPU. I think the corruption occurs because DWM (= compositor = blends all windowed applications together into a single image) doesn't get correctly informed about our swap chain resizing. On my Windows 11 26001 build with up to date Nvidia drivers I can't reproduce the issue anymore, but I know that last year it definitely still happened. I'm not sure whether a driver update or Windows fixed it at some point.

**Comment by tusharsnx** [comment]
Oh, thanks for pointing me to the original issue.

Could this also happen because we don't resize our swap chains when DWM expects us to do it (when receiving `WM_PAINT`)? I mean, this is how the terminal looks when we're done processing all the resize events (+ events resulted from that), but the render engine is yet to resize swap chain buffers (I added a breakpoint inside _handleSettingUpdate):

**Comment by tusharsnx** [comment]
I'll close this and continue in the original thread.
