### ISSUE TITLE
Underline color is being overwritten by foreground color

### ISSUE THREAD

**Issue by EpicBirb** [microsoft/terminal#17184]
### Windows Terminal version

1.19.10821.0

### Windows build number

10.0.19045.0

### Other Software

nvim v0.9.5

### Steps to reproduce

1. Create the following highlight group in neovim using this command `:lua vim.api.nvim_set_hl(0, "test", {underline=true, sp="#00FF00", fg="#FFFFFF"})`
2. Then run the command `:hi test`

### Expected Behavior

![image](https://github.com/microsoft/terminal/assets/68750348/c8d9ff06-ff3b-440d-9fe6-a41892c55bea)
Executed using nvim-qt

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/68750348/237f3fc3-c40f-4fbf-8b6e-6793dd8baddc)
Executed using Terminal

**Comment by PhMajerus** [comment]
Doesn't seem to be a problem in Terminal itself, I can have colored underlines and change the foreground color without it affecting the underline color:
![image](https://github.com/microsoft/terminal/assets/25664275/74741b51-5e65-4288-968b-d96a3eecc3f2)

**Comment by lhecker** [comment]
It's because neovim only enables extended and colored underlines if the terminfo database says so, as well as for certain specific terminals: https://github.com/neovim/neovim/blob/01e4a70d668d54a7cefa3ff53ec97e39df516265/src/nvim/tui/tui.c#L2365-L2375

While invisible-island.net does an absolutely fantastic job in maintaining the terminfo database overall, when it comes to Windows Terminal it's not quite perfect:
* Since we're still "catching up" with the other established terminals, the terminfo database is usually behind by a year or so of our development (currently: 1.16 from Jan 2023). 
* It has some remarks about our correctness that I personally find very surprising. Among others it says "italics sitm/ritm do not work in WSL2" even though that's `\e[3m` and `\e[23m` which for certain have worked since the very first 1.0 release. (Same for smxx/rmxx = cross out allegedly not working, etc.)

In any case, neovim seems to document ways to override the behavior here: https://neovim.io/doc/user/term.html
I'm not a (n)vim user so I can't say what the best approach is but setting `TERM` to `xterm-kitty` does definitely make colored underlines work in nvim.

**Comment by EpicBirb** [comment]
> It's because neovim only enables extended and colored underlines if the terminfo database says so, as well as for certain specific terminals: https://github.com/neovim/neovim/blob/01e4a70d668d54a7cefa3ff53ec97e39df516265/src/nvim/tui/tui.c#L2365-L2375
> 
> While invisible-island.net does an absolutely fantastic job in maintaining the terminfo database overall, when it comes to Windows Terminal it's not quite perfect:
> 
> * Since we're still "catching up" with the other established terminals, the terminfo database is usually behind by a year or so of our development (currently: 1.16 from Jan 2023).
> * It has some remarks about our correctness that I personally find very surprising. Among others it says "italics sitm/ritm do not work in WSL2" even though that's `\e[3m` and `\e[23m` which for certain have worked since the very first 1.0 release. (Same for smxx/rmxx = cross out allegedly not working, etc.)
> 
> In any case, neovim seems to document ways to override the behavior here: https://neovim.io/doc/user/term.html I'm not a (n)vim user so I can't say what the best approach is but setting `TERM` to `xterm-kitty` does definitely make colored underlines work in nvim.

I see. Thanks for helping!

**Comment by DHowett** [comment]
Thanks for closing! Terminfo is something we really should make sure we keep up to date -- it's on my endless todo list :laugh:
