### ISSUE TITLE
Open new Pane via Keyboard with currently active Profile

### ISSUE THREAD

**Issue by Maximizer02** [microsoft/terminal#17208]
# Description of the new feature/enhancement
I propose for there to be an option to create a direct keyboard shortcut for opening a new Pane (Split Vertically or Horrizontally), but instead of using the default profile, it uses the profile of the currently active tab. 
My research has concluded that opening a new pane with the currently active profile is currently only possible by either right-clicking the tab up top or by opening the new tab dropdown with ctrl+shift+space and then select the already opened profile and alt+enter it.
As this is rather cumbersome i propose for there to be an option for a shortcut to make this a bit easier.

# Proposed technical implementation details
There could maybe be an argument in the settings.json file for which Profile should be opend when performing a split. It could either be one of the existinng profiles or the currently active profile. That way the user can customize the behavior how he likes it best.

**Comment by zadjii-msft** [comment]
* there's been an arg to `splitPane` for years now that would make it duplicate the pane: ["splitMode": "duplicate" ](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#parameters-16)
* For 1.21 we merged #16951 which closes out /dup #7657. That'll change the default keybindings to duplicate instead of use the default.
