### ISSUE TITLE
Gaps between block elements when using Direct2D

### ISSUE THREAD

**Issue by o-sdn-o** [microsoft/terminal#17224]
### Windows Terminal version

Current main

### Windows build number

10.0.19045.4291

### Steps to reproduce

- System-wide scale and layout (display settings): 100%
- WT PowerShell profile settings:
  - Font face: "Cascadia Mono"
  - Font size: "12.2"
  - Line height: "1.2"
  - Font weight: "Normal"
  - Builtin Glyphs: "On"
  - ![image](https://github.com/microsoft/terminal/assets/11535558/c5d3dcab-d3f3-4928-bb64-b5106f9c4eec)
  - Graphics API: "Direct2D"
  - ![image](https://github.com/microsoft/terminal/assets/11535558/92c17826-e955-4155-8c98-57ecbd565c40)

- Type "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄" at the pwsh prompt
  ```pwsh
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄"
  ```

### Expected Behavior

[Block elements](https://unicode.org/charts/PDF/U2580.pdf) are fused into a solid bar.

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/11535558/41b56b19-9f19-4300-a76c-f1022d65926f)

**Comment by lhecker** [comment]
Right... I wrote that "This feature only works when GPU Acceleration is available." text before I added the Graphics API setting (at which time that statement was mostly true), but now that doesn't work anymore of course. The question is, which one is best?
* This feature is only available when the Direct3D Graphics API is used.
* This feature is unavailable when the Direct2D Graphics API is used.
* This feature is unavailable when Direct2D is used for text rendering.
* _something else?_

**Comment by o-sdn-o** [comment]
It seems to me that since the "Builtin Glyphs" option is completely dependent on the "Graphic API", it makes sense to make it a sub-option that only becomes available when "Direct3D 11" is selected.

I don't think the "Builtin Glyphs" option should necessarily be tied to a profile, as a global option it is quite appropriate for me.

**Comment by zadjii-msft** [comment]
Oof that's a tricky one. Cause I'd expect it on the appearance page, but the renderer option doesn't really need to be on the appearance page. That's definitely an advance option. 

Maybe when d2d is enabled, we could disable the builtin glyphs menu item, and add a message box with a deeplink to the advanced page... but that sounds overly complicated. 

I guess making it a sub-item of the renderer entry is probably the most elegant solution

**Comment by lhecker** [comment]
I suspect most people will keep it on the default option "Automatic", in which case Direct2D is only used if the system lacks a GPU (or it's a very old GPU, but that's fairly rare nowadays). This is commonly the case when using RDP to remote into a server or VM.

The reason I put the "Builtin Glyphs" option on the profile appearance page is because the font setting is per-profile and so I guess the builtin-glyph option (which overwrites glyphs in the font) should be per-profile too.

The problem is that the settings UI doesn't really have any idea about this "Automatic" API choice. It could be hooked up of course, but I think that's somewhat annoying to do (different DLLs, with different components, on different threads, and it may change at any given moment = needs event hooks). The upside on the other hand is potentially fairly small, because >95% of users are using the Direct3D renderer anyway.

Unless Dustin/Mike think about this differently, I think I'll only change the sub-text on the setting for now. If more people run into this issue (even just a few), I'll try to improve it by hooking up the render thread to the settings UI, or something similar.

**Comment by tusharsnx** [comment]
I'd love those specific feature toggles to get grayed-out when the feature is not available for any reason. We could give additional context as to why they're grayed out with a ⓘ button treatment to the grayed-out toggles.

![image](https://github.com/microsoft/terminal/assets/55626797/3a556b4a-ef4c-4deb-9ebf-a888161ca436)

**Comment by zadjii-msft** [comment]
Unanimous team consent: It's just easier to add builtin glyph support to d2d rather than finagle the SUI to support this
