### ISSUE TITLE
Mouse-Friendly UI in Quake Mode

### ISSUE THREAD

**Issue by polygonnedpotato** [microsoft/terminal#17242]
# Description of the new feature/enhancement

Currently, Quake windows only show the terminal, with no UI. One of the reasons this terminal is better than conhost.exe is because there is support for tabs, and a more user-friendly UI. However, these are not present in Quake mode, and the only way to use tabs are by keyboard shortcuts, which could be hard to remember. Redesigning the Quake UI could help the user's experience with Quake mode, as it would make it easier to use.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
For what it's worth, you may be more interested in just plain-old [`globalSummmon`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-summon), which you can use with any window (not just a quake one):

I have it bound like: 
```json
        {
            "command":
            {
                "action": "globalSummon",
                "monitor": "any"
            },
            "keys": "win+sc(41)"
        },
```

I think that's 1000% more useful than the \_quake window. You can also "Toggle focus mode" to turn the tabs back on in Quake mode

Otherwise, we're tracking "customizing the quake window" very broadly in /dup #9992
