### ISSUE TITLE
Accelerating Terminal rendering with D3D12 mesh shaders

### ISSUE THREAD

**Issue by Andarwinux** [microsoft/terminal#17248]
# Description of the new feature/enhancement
Accelerating Terminal rendering with D3D12 mesh shaders

# Proposed technical implementation details (optional)
https://gpuopen.com/learn/mesh_shaders/mesh_shaders-font_and_vector_art_rendering_with_mesh_shaders/

**Comment by lhecker** [comment]
I'm aware about this technique but my understanding is that it's significantly slower than using a glyph atlas. The reason games use mesh shaders (or the more venerable, but patented [Slug library](https://sluglibrary.com/)) is because games require text to be drawn in a size according to their distance to the camera. Do you disagree? Are mesh shaders actually faster for our use case?

**Comment by lhecker** [comment]
Wow yeah that demo is definitely _really_ cool, especially when using Alt+Mouse. The author does note though:
> This technique is harder on the GPU than atlas textures but avoids the need to use the CPU to render at runtime when a required glyph size is missing.

Since we mostly scroll text if anything, and don't really zoom or scale a lot, I think atlases may still have the best performance.

> Windows Terminal only achieves the same smoothness when scrolling vertically via trackpad.

Do you mean to say that zooming is slow/stuttery for you? If so, I'm assuming this is when you use the newer AtlasEngine text renderer, right?

**Comment by lhecker** [comment]
I'll be closing this issue for now. The good news is that I do have future improvements in mind when it comes to text rendering: In particular, I'm hoping to one day implement a "tiled deferred shading" renderer with a compute shader. The reason I didn't chose this approach for the current AtlasEngine is because this app needs to work reasonably well on some particularly bad hardware. Older Intel iGPUs don't have good support for compute shaders, but I'm worried that this is most of our users.

> Yes, I'm using it, and if I switch to Direct2D, the stuttering improves, but there is still a slight stutter.

Do you by any chance use an Intel GPU?

**Comment by lhecker** [comment]
Do you use G-SYNC? If so, what happens if you disable that?
