### ISSUE TITLE
Auto Reverting Font to Consolas

### ISSUE THREAD

**Issue by ezekielbaniaga** [microsoft/terminal#17276]
### Windows Terminal version

1.20.11271.0

### Windows build number

10.0.22631.0

### Other Software

Just opening plain terminal

### Steps to reproduce

1. Install JetBrainsMono Nerd Font
2. Open Terminal and set as default font
3. Dialog warning will show just click OK
4. Terminal will default to consolas.
5. Open terminal tab a few times and it will suddenly use JetBrainsMono Nerd Font

Here's a screenshot of a working scenario:
![image](https://github.com/microsoft/terminal/assets/8464038/433f68fc-1715-482f-98cd-28d1188e6d2f)

Here's a screenshot of non-working scenario:
![image](https://github.com/microsoft/terminal/assets/8464038/421ae128-416e-421b-b4a8-4c54be85ea2f)

### Expected Behavior

Clearly Windows Terminal can use the font. I'm expecting it to just use JetBrainsMono Nerd Font at the start without the hassle. I installed the font a few times even charmap verifies that font is installed. Also if font is not installed correctly then why:

1. JetBrainsMono Nerd Font is in the list of Font face selection at Windows Terminal Settings
2. Windows Terminal suddenly uses the font after a few tries

### Actual Behavior

Shows annoying "Warning Unable to find the selected font JetBrainsMono Nerd Font. "Consolas" has been selected instead. Please either install the missing font or choose another one."

**Comment by ezekielbaniaga** [comment]
> Did you install the font for all users/?

No. I just select set of fonts then "Install". I also tried dragging to Windows Fonts directory

**Comment by ezekielbaniaga** [comment]
Install for all users work. It's kinda hidden though. 

![image](https://github.com/microsoft/terminal/assets/8464038/527f9b6f-4511-4818-8d20-709298ffcc1a)

BTW, why not include a quick instructions at the warning dialog box? Or maybe some description in the warning dialog box that will tell the user that he needs to install for "all users" in order to render text properly.

**Comment by lhecker** [comment]
> Install for all users work. It's kinda hidden though.

FYI don't forget to remove the per-user font now, or otherwise you got it installed twice. If you then update the font in the future, some apps will use the old version and some the new version which will be confusing.

> BTW, why not include a quick instructions at the warning dialog box?

IMO that's a good idea. @zadjii-msft what do you think?

The reason you need to install it for all users is because per-user fonts have never been properly implemented in Windows. The font cache service simply "forgets" them after a reboot. So even outside of Windows Terminal, I would recommend always installing it for all users. We've internally reported the bug (MSFT:42103854), but work on it hasn't started yet. You can see the full history over at #3257.

**Comment by ezekielbaniaga** [comment]
> > Install for all users work. It's kinda hidden though.
> 
> FYI don't forget to remove the per-user font now, or otherwise you got it installed twice. If you then update the font in the future, some apps will use the old version and some the new version which will be confusing.

Thank you for reminding me
