### ISSUE TITLE
After outputting content from the owlshell terminal, clear the command line window. After adding a space to the cd, it will jump to the bottom

### ISSUE THREAD

**Issue by jiao6** [microsoft/terminal#17359]
### Steps to reproduce

Create a new Powershell terminal, enter the pip list, output information, and clear the terminal
Enter cd with a space and enter, the cd will be displayed at the bottom
![image](https://github.com/microsoft/terminal/assets/22795264/683577c1-5ddc-43f8-9857-0ea8051bbcce)
![image](https://github.com/microsoft/terminal/assets/22795264/c77d7435-d559-4684-9042-a6fa0818afce)
![image](https://github.com/microsoft/terminal/assets/22795264/9c8009fe-327e-4a94-8c79-1e294687a8fd)

### Expected Behavior

Display CD with space in its original position

### Actual Behavior

After adding spaces to cd, it will jump to the bottom

**Comment by zadjii-msft** [comment]
Two things: 
1. This looks just like #2432, which I believe was fixed with an updated version of PsReadline. 
2. However, it looks like you're using the VsCode terminal, not the Windows Terminal. This is the repo for the Windows Terminal, not the vscode one. 


If updating PsReadline doesn't help, then I'd file an issue over at https://github.com/microsoft/vscode
