### ISSUE TITLE
allow tabs on any side and allow users to change the sharpness

### ISSUE THREAD

**Issue by YeesterPlus** [microsoft/terminal#17456]
# Description of the new feature/enhancement

Allow tabs on any side
Allow users to change the sharpness of the tabs

**Comment by YeesterPlus** [comment]
I can't use konsole

**Comment by j4james** [comment]
@YeesterPlus  I'm not sure why you downvoted the bot's suggestion, because that sounds like exactly what you're requesting. If you're also wanting to have the tabs on the bottom of the window, that's tracked in issue #835 which the above mentioned issue was merged with.

As for "sharpness", I'm guessing you want sharp/rectangular corners on the tabs rather than the current rounded corners. If so, that's tracked in issue #7213.

If I've misunderstood you, could you please provide more details.

**Comment by PankajBhojwani** [comment]
Thank you! As j4james said, this is a duplicate /dup #835

**Comment by klunejko** [comment]
This isn't actually a duplicate of #835

**Comment by zadjii-msft** [comment]
@klunejko care to elaborate?

**Comment by klunejko** [comment]
@zadjii-msft #835 is only about tab placement, this issue also asked for an option to change the tab design itself (assuming sharpness refers to the radius/roundness)

**Comment by zadjii-msft** [comment]
Okay, fine, that's #7213. Still a dupe, just a different one.
