### ISSUE TITLE
conpty hangs in _ClosePseudoConsoleMembers

### ISSUE THREAD

**Issue by LemonBoy** [microsoft/terminal#17489]
### Windows build number

10.0.22631.0

### Other Software

vim 9.1

### Steps to reproduce

 - `git clone git@github.com:vim/vim.git`
 - `cd src`
 - `nmake -f .\Make_mvc.mak GUI=yes FEATURES=HUGE TERMINAL=yes DEBUG=yes`
- `.\gvimd.exe -U NONE -u NONE -c 'set go+=! | !dir'`

### Actual Behavior

The program hangs.

Attacching a debugger shows the main thread waiting in `_ClosePseudoConsoleMembers` for `conhost.exe` to die.
The pipes passed by Vim are all closed by the time it calls `ClosePseudoConsole`, I've read the remark in the docs regarding the possibility for the function to hang, but here I'm not sure it applies to this case.

**Comment by lhecker** [comment]
> The pipes passed by Vim are all closed by the time it calls `ClosePseudoConsole`, I've read the remark in the docs regarding the possibility for the function to hang, but here I'm not sure it applies to this case.

It does apply unfortunately. You must keep the output pipe open and read from it until after `ClosePseudoConsole` has returned.

Because this was difficult to use, we have modified `ClosePseudoConsole` in Windows 11 24H2 to never block. But that doesn't fix the issue on older Windows versions of course. It also contains a `ReleasePseudoConsole` API with which you can simply read the output pipe until it's closed on you. That way you don't need to monitor whether the spawned child has exited, which makes it even safer to use.
