### ISSUE TITLE
[Feature]Add option to always hide tab bar

### ISSUE THREAD

**Issue by zoumi** [microsoft/terminal#17498]
# Description of the new feature/enhancement
The terminal can't hide tab bar when there are more then one tab exists. But some people would like to switch tabs by hotkeys, then the tab bar will be useless.
 
# Proposed technical implementation details (optional)

![Snipaste_2024-07-01_22-28-55](https://github.com/microsoft/terminal/assets/5162901/9abc4056-47a4-429e-85ab-6b181e72d4ae)

**Comment by CoderParth** [comment]
Hi there, to hide your tab bar, 
please add `config.enable_tab_bar = false` to your .wezterm.lua file. 

Also, please ensure you have created .wezterm.lua file in your home directory. 
So, a full script to enable this feature would look like this. 

.wezterm.lua  file 
```
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This will hold the configuration.
local config = wezterm.config_builder()

config.enable_tab_bar = false

return config`
```




Hiding the tab bar will remove the launcher ('+' sign) from the tab bar as well. 
So, in order to launch the launcher through your key bindings, you can add somethingl ike this to your file

```
config.keys = {
	-- Bind Alt + L to show the launcher. Change it to your desired bindings.
	{ key = "l", mods = "ALT", action = wezterm.action.ShowLauncher },
}
```
