### ISSUE TITLE
Hyperlink/URL is not correctly recognized and opened

### ISSUE THREAD

**Issue by jiasli** [microsoft/terminal#17495]
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.22631.0

### Steps to reproduce

```
$ cat https://login.microsoftonline.com/.
cat: 'https://login.microsoftonline.com/.': No such file or directory

$ cat https://login.microsoftonline.com/:
cat: 'https://login.microsoftonline.com/:': No such file or directory
```

### Expected Behavior

`https://login.microsoftonline.com/` should be recognized and opened.

### Actual Behavior

![image](https://github.com/microsoft/terminal/assets/4003950/82e90429-3332-4c3f-9f71-1e40602a6bad)

![image](https://github.com/microsoft/terminal/assets/4003950/3a3296b7-9fa2-4dbc-800d-d359704ad8e8)

In the terminal windows, `https://login.microsoftonline.com/` is underlined, but in the pop-up tooltips,  `https://login.microsoftonline.com/.` and `https://login.microsoftonline.com/:` are shown.

After _Ctrl + Click_, `https://login.microsoftonline.com/:` is opened and results in an error:

![image](https://github.com/microsoft/terminal/assets/4003950/6bceef3e-de9f-4ed9-a232-8894b31f7697)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to https://github.com/microsoft/terminal/issues/17323 for more discussion.

/dup #17323

This was also fixed in [Windows Terminal v1.20.11781.0](https://github.com/microsoft/terminal/releases/tag/v1.20.11781.0)
