### ISSUE TITLE
Cannot install, and the .zip versions do nothing

### ISSUE THREAD

**Issue by gitcnd** [microsoft/terminal#17523]
### Windows Terminal version

terminal-1.20.11781.0

### Windows build number

Microsoft Windows [Version 10.0.17763.5936]

### Steps to reproduce

Use Windows 10N
Try to install or run

### Expected Behavior

Should have worked

### Actual Behavior

Installer says this:-

![pic_2024-07-08_09 49 33_744](https://github.com/microsoft/terminal/assets/4301826/a5345ad8-689b-4a16-ac45-d6de996006e7)

wt.exe etc from the .zip file all "do nothing" (no errors, not nothing - the commands just end silently)

Not all versions of windows come with the "Store App" you know.

![pic_2024-07-08_09 55 26_745](https://github.com/microsoft/terminal/assets/4301826/7824ff24-e13b-4a22-8371-de5baf868b8e)

**Comment by zadjii-msft** [comment]
You need Windows 10.0.19041 at a minimum to be able to run the Windows Terminal. We've never supported 17763, since it's missing a bunch of the core technology we depend on.

**Comment by gitcnd** [comment]
"core technology", for **telnet**?    You know this comes from 1969, right?

I love the way to deal with shafting old users - just exit() with no messages.  Sheesh.

**Comment by zadjii-msft** [comment]
...... what?

The Windows Terminal is not telnet. It's a whole windowed application, with UI elements, and the particular UI stack we're on[^1] didn't start working till 10.0.18362 at the very earliest. 

We haven't added specific error messages to 17763, because that's not a version we officially support. If you'd like to add an error message there, you're more than welcome to add one. 

[^1]: Xaml Islands, for XAML without an app container. We also need reg-free winrt, which was also added in that version of Windows
