### ISSUE TITLE
in git bash for command $ git init ->says fatal: unable to access 'C:\Users ame/.config/git/config': Invalid argument .here dir was C:\Users\name/.config/git/config

### ISSUE THREAD

**Issue by nafeu-khan** [microsoft/terminal#17522]
### Steps to reproduce

\n is going to be a newline here in git bash . c\users\name it should be valid path in git bash terminal

### Expected Behavior

should create .git folder

### Actual Behavior

in git bash for command $ git init ->says fatal: unable to access 'C:\Users ame/.config/git/config': Invalid argument .here dir was C:\Users\name/.config/git/config

**Comment by zadjii-msft** [comment]
What is your `HOME` environment variable set to? Have you made any other modifications to your git bash setup? 

If you've replaced your actual username with `name` in the above post, can you share the actual output? At least one post I read on this topic suggested that it might be due to an errant `'` in a username
