### ISSUE TITLE
[Bug Bash] Quick Fix button being rendered to wrong spot

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#17631]
### Windows Terminal version

1.22.2081.0 (bug bash on 7/30)

### Steps to reproduce

![{11B3EFDF-2243-429B-BA6F-0B028E93B984}](https://github.com/user-attachments/assets/39de1bb1-afa4-4e93-a8cd-37f7b6976b9e)

It's being placed in random positions. However, it'll snap to the cursor if you resize when in that state.

May be similar to this bug: 
Opening snippets pane causes prompt to disappear and QF button moved to where the prompt is supposed to be?

![{9AC1A666-F826-4E04-BCA2-0B923D80B915}](https://github.com/user-attachments/assets/9b168991-4706-4f6e-a6f2-2788f237c170)

Confirmed it's not related to snippets, so there's something weird going on with drawing the QF button.

### Actual Behavior

x

**Comment by carlos-zamora** [comment]
Oh no, I did a git bisect (a few, actually) and it led me to:
450eec48d A minor ConPTY refactoring: Goodbye VtEngine Edition (#17510)

**Comment by lhecker** [comment]
Flushing in the old VtEngine happened with a 16ms delay (unless the content scrolled) so it's not unlikely that we had a bug already but simply didn't notice due to the delayed output from cmd.

Looking at this image:
![{11B3EFDF-2243-429B-BA6F-0B028E93B984}](https://github.com/user-attachments/assets/39de1bb1-afa4-4e93-a8cd-37f7b6976b9e)

Doesn't cmd emit the command-not-found VT sequence when printing that exact message? In that case I think it's just natural that the quick-fix button is possibly on the same line. Without knowing the quick-fix code exactly, I suspect we're using a `resume_foreground` somewhere, lock the text buffer, ask for the cursor position and then show the bulb next to the cursor, right? That can't work reliably since it's timing sensitive and races with the concurrently running cmd output.

If we're fine with showing the bulb next to the cmd error message, the easiest fix for this may be to transmit the row number with the event that informs the control to show the bulb. Unfortunately, we don't yet have unique row IDs that would make it possible to figure out the vertical offset while the text buffer is possibly concurrently scrolling. In that case I think we should add them.
