### ISSUE TITLE
WT believes Noto Sans Mono CJK is not a Mono font

### ISSUE THREAD

**Issue by Andarwinux** [microsoft/terminal#17658]
### Windows Terminal version

1.22.2151.0

### Windows build number

26120.1330

### Other Software

https://github.com/notofonts/noto-cjk/blob/main/Sans/Variable/OTC/NotoSansMonoCJK-VF.otf.ttc

### Steps to reproduce

![image](https://github.com/user-attachments/assets/90b5e485-865a-40ed-a284-da7f830e8dd1)

### Actual Behavior

![image](https://github.com/user-attachments/assets/4a9c3a35-3b85-4339-98f7-3083fc717642)

**Comment by DHowett** [comment]
Thanks for filing!

Yes, this is true.

Windows DirectWrite does not consider this font to be monospaced because the PANOSE values specify that it is an "Any" proportion font for Text Display purposes.

The PANOSE bProportion value is 0 instead of 9.

In addition, the postscript table specifies `isFixedPitch` to be `0`.

In short, the font's built-in metadata says it is proportional.

It is probably because it contains multiple character widths. This is common (but not required) for CJK fonts.
