### ISSUE TITLE
Splitting a tab should offer profiles like it used to

### ISSUE THREAD

**Issue by inosik** [microsoft/terminal#17684]
# Description of the new feature/enhancement

The "Split pane" command used to have a submenu, where you could select the profile for the new pane:

![WindowsTerminal_2024-08-08_15-32-52](https://github.com/user-attachments/assets/46468969-0399-40b5-b723-1ae3d33dbbad)

Right now I have no idea how to create a new pane using a profile that is not the default one.

**Comment by carlos-zamora** [comment]
Oh no... This is another manifestation of #17294.

I'm guessing you added a plain `"command": "splitPane"` to your settings.json. We expose that as `Split pane` in the command palette.

In #16886, the key for the nested action got renamed from `Split Pane...` to `Split pane`. This accidentally caused a collision because now you have two actions with the same name! The settings model then prefers _your_ action over the one defined in defaults.json, thus completely hiding the nested version.

I'm marking this a /dup of #17294 and reverting the `...` changes in the names. That should make these come back 😊

**Comment by inosik** [comment]
> I'm guessing you added a plain "command": "splitPane" to your settings.json

You're right, there was an action that was bound to this command. I'm not aware of adding it though.

However, I removed it and the submenu is back, thanks!
