### ISSUE TITLE
Can't off feature "Auto recognize URLs"

### ISSUE THREAD

**Issue by Zeroes1** [microsoft/terminal#17727]
### Windows Terminal version

1.22.2281.0

### Windows build number

10.0.19045.3448

### Steps to reproduce

broken features:
"experimental.detectURLs": false,

work fine:
Microsoft.WindowsTerminal_1.17.11461.0_x64.zip
Microsoft.WindowsTerminal_1.18.2681.0_x64.zip

broken:
Microsoft.WindowsTerminal_1.19.10302.0_x64.zip
...
Microsoft.WindowsTerminal_1.20.11781.0_x64.zip

latest Canary terminal-1.22.2281.0 also broken

test URL:
https://aka.ms/terminal-documentation

### Expected Behavior

recognized URLs are not highlighted

### Actual Behavior

recognized URLs is highlighted
anyway

when 
"experimental.detectURLs": false,
or
"experimental.detectURLs": true,

**Comment by lhecker** [comment]
This regressed in cd80f3c76496c7664ed710907d7d473f634191bc because this line got removed from the branch:
https://github.com/microsoft/terminal/blob/5651f087702d97f8c5e48db6cd4199aed8a04479/src/cascadia/TerminalCore/Terminal.cpp#L1340-L1342

The fix is to add a `_detectURLs` check here:
https://github.com/microsoft/terminal/blob/1ef497970f8409def5ac03e26ba54439d0aad4e0/src/cascadia/TerminalCore/Terminal.cpp#L1422-L1452

**Comment by DHowett** [comment]
Eh, I figured I'd drive by and fix it
