### ISSUE TITLE
Build Windows Terminal using clang-cl instead of msvc

### ISSUE THREAD

**Issue by Andarwinux** [microsoft/terminal#17832]
# Description of the new feature/enhancement

Windows Terminal seem have had to disable PGO recently due to a bug in msvc. Maybe consider trying clang-cl, which is usually much faster than msvc.

# Proposed technical implementation details (optional)
https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170

**Comment by DHowett** [comment]
I actually do maintain a ClangCL pipeline for Terminal!

It does not necessarily perform better, and it introduces an extra AddRef/Release pair around every WinRT object interaction which results in additional virtual dispatches in many critical call sites.

See https://github.com/microsoft/cppwinrt/issues/1273 for more info on that.

I am not likely to push to productive the ClangCL build because it’s incompatible with the “UAP” platform build targets. I will, however, continue to maintain the branch because it keeps us honest and compliant.
