### ISSUE TITLE
Inconsistent settings across MsStore Terminal and github Terminal

### ISSUE THREAD

**Issue by domoar** [microsoft/terminal#17866]
### Steps to reproduce

Install the MsStore Terminal and the github Terminal

### Expected Behavior

Same settings options across both applications (Left: Terminal installed from MsStore, Right: Terminal installed from github)

### Actual Behavior

![Screenshot 2024-09-05 142534](https://github.com/user-attachments/assets/327e00e7-c39e-4ec5-bdf9-d10ab68e512c)

**Comment by zadjii-msft** [comment]
That's totally by design. The "unpackaged" terminal installed from a zip file from github can't be set as the Default Terminal, so that setting isn't available in the settings UI for the terminal when it's running like that. 

If you instead install the `.msix` off of our github releases, that will run as a package, and can still be set as the default.

**Comment by domoar** [comment]
Thank you for letting me know! That makes sense now. I assumed that this was by design, because the windows setting didnt recognize the unpacked terminal either. I appreciate your help!
