### ISSUE TITLE
how to disable `WT_SETTINGS_DIR` for nonportable Windows Terminal?

### ISSUE THREAD

**Issue by candrapersada** [microsoft/terminal#17957]
How to disable `WT_SETTINGS_DIR` for `Windows Terminal` installed from the Microsoft Store?
and enable `WT_SETTINGS_DIR` from `Environment Variables`

**Comment by DHowett** [comment]
Can you explain your use case a bit more? `WT_SETTINGS_DIR` is expected to point to the actual settings directory Terminal was started with; it cannot use and does not use the one you set. Did you add one to your environment block so that you could use it to refer to WT settings you stored somewhere _other than_ the settings directory?

**Comment by candrapersada** [comment]
> Did you add one to your environment block so that you could use it to refer to WT settings you stored somewhere _other than_ the settings directory?

yes to change the settings location with use `Environment Variables`

**Comment by DHowett** [comment]
Terminal does not read the location of its settings file from that variable. It never has. :)

**Comment by DHowett** [comment]
We are not planning on supporting a configurable settings location using an environment variable right now. Sorry!
