### ISSUE TITLE
Cascadia font family prevents Terminal from updating properly

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [microsoft/terminal#17991]
### Windows Terminal version

1.21.2701.0

### Windows build number

10.0.22631.0

### Steps to reproduce

Use winget update or winget upgrade to update Terminal to the latest version (case 1).
Otherwise, either use Microsoft Store update function to do the same (case 2) or download the MSIX package and install it (case 3).

### Expected Behavior

For case 1, the program should be updated.
For case 2, given a completely different, yet to be determined cause, I need to then manually register the newly downloaded folder after it fails the last step, then complete the task with Microsoft Store to update its app version database, after which the old version folders get erased.
For case 3, most likely for the same reason, I have to use add-appxpackage from a command line application instead of just double-clicking and installeng, after which the old version folders get erased.

### Actual Behavior

For this app in particular, case 1 returns an error and does nothing bt add an almost empty folder with a different version numbering scheme (same version as the new one, but preceded by a 300 and replacing the "x64" by a "neutral"), which does nothing except preventing case 2 from even noticing the app isn't up to date, while cases 2 and 3 leave a trail of old version folders.

Checking those leftover folders, the reason they can't be erased is that CascadiaMono.ttf and CascadiaMonoItalic.ttf claim to be in use by SYSTEM (something the Resource Monitor cannot confirm) for all versions at the same time. Sometimes (it has happened to me once, seemingly after an attempt to get rid of the folder with a remove-appxpackage), a bunch of dlls plus OpenConsole.exe, WindowsTeminal.exe and Microsoft.Terminal.Remoting.winmd get readded to the folder, but those can be erased no issue.

I find it weird that everyone has issues with Cascadia not being found while my issue is that my System is hogging every single Cascadia font file in existence.

**Comment by lhecker** [comment]
> I find it weird that everyone has issues with Cascadia not being found while my issue is that my System is hogging every single Cascadia font file in existence.

It's caused by the same issue though: The Windows font cache. It does not seem to be actively maintained and does not work well with features added since Windows 8, in particular packaged applications like ours. You're also not alone with this issue, because it happens to everyone. Most just don't notice that they have 10+ leftover WindowsTerminal directories in the WindowsApps folder. We've internally opened an issue for the font missing after a reboot and are waiting for it to be resolved. We could tack your issue onto it, but I suspect it'll also not be resolved anytime soon.
