### ISSUE TITLE
Feature Request - see the name of the server taken in ssh in the name tab 

### ISSUE THREAD

**Issue by TheMMcOfficial** [microsoft/terminal#1803]
# Summary of the new feature/enhancement

Can we get the name of the server in the tab name? For the moment it's written "OpenSSH SSH client". 

# Proposed technical implementation details (optional)

Get the name for the server in the tab name when we type "ssh user@SERVER" in the new terminal. Maybe we can also have a place to save ssh setting to have quick access to certain servers.

**Comment by DHowett-MSFT** [comment]
The shell on the other end is perfectly capable of reporting any information it wants to. The default configuration in Ubuntu, as an example, sets the title to `user@server:directory` -- all without the terminal having to do anything.

It's 1000x better to have the remote shell report this information, because if the local terminal has to do it it is _just a guess_ and _likely to be wrong._

If your remote shell is bash, [check this out](https://superuser.com/questions/84710/window-title-in-bash). If it's powershell, use `$Host.UI.RawUI.WindowTitle`

This is what it looks like for me:

![image](https://user-images.githubusercontent.com/14316954/60612850-8556a900-9d7e-11e9-90d6-8bdbe8920b8b.png)

**Comment by TheMMcOfficial** [comment]
Maybe I wasn't clear... But in Powershell or in CMD the tab name is "OpenSSH SSH client" 
![image](https://user-images.githubusercontent.com/34872211/60616050-99aa9e00-9d9e-11e9-9c07-7533c626c44f.png)

**Comment by DHowett-MSFT** [comment]
I may not have been clear either. *When you are using SSH,* you are likely running a shell on a remote machine. **That shell** can set the title to whatever it wants. There is a standard way for a shell to set a title. Your remote shells are _not_ doing that. This is a configuration issue on your remote shell on the receiving end of the SSH connection. :smile:

**Comment by Sky-Walkrr** [comment]
For those who comes after looking for setting title bar to ssh server name, here I provide a way (has tested on my remote server which runs a Cent OS 7 with bash shell):

1. Edit the `.bashrc` file on your remote server machine, add lines below:
```bash
function title {
   PROMPT_COMMAND="echo -ne \"\033]0;$1 \007\""
}
title "$USER@$HOSTNAME"
```

2. Save the changes and after next login, you should see the user@hostname on the Windows Terminal tab correctly.

Give it a try.
