### ISSUE TITLE
Show last command in tab & Windows taskbar

### ISSUE THREAD

**Issue by oSumAtrIX** [microsoft/terminal#18061]
# Description of the new feature/enhancement

Often, you have multiple windows of Terminal open:

![Image](https://github.com/user-attachments/assets/e3c0e296-b256-4eb6-af18-6bec01d1f850)

The same issue occurs in the tabs:

![Image](https://github.com/user-attachments/assets/5f97d929-c05b-4343-995d-88b144c73a4c)

This is troublesome as you forget which window is which. 

One can rename the tab, but this is often impractical for quick tasks:

![Image](https://github.com/user-attachments/assets/1d31b18f-9dea-47bd-ac81-6953ae43e966)

An option to show the last typed command (trimmed is fine) would easily solve this situation. You'd know which window or tab is which because of the last command:

![Image](https://github.com/user-attachments/assets/beaa5a6c-082b-4871-b299-e8606ce37bd9)

**Comment by coderzawad** [comment]
I quite like the concept, Maybe I will make a contribution related to this requested feature

**Comment by zadjii-msft** [comment]
This is something that's more a _shell_ (CMD, PowerShell, Bash) feature rather than a _terminal_ one. The Terminal doesn't really know what's running in it, or when a sub-command is started/ended. But the shell does know, and it can always set the title of the window/tab itself. 

In fact, CMD.exe already does this 😉 
![Image](https://github.com/user-attachments/assets/e1a732af-0ea7-423b-b890-f2eb03a7b179)
