### ISSUE TITLE
Certain key sequences change the output glyphs

### ISSUE THREAD

**Issue by ctolkien** [microsoft/terminal#1814]
# Environment

```none
Microsoft Windows [Version 10.0.18362.207]
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce
- Use MesloLGL Nerd Font ForPowerline font.
- Type `fi`

# Expected behavior
- Terminal displays `fi`

# Actual behavior
- Terminal rewrites `fi` to a phone icon.
- Video example: https://i.imgur.com/fUwPUvN.gif

**Comment by DHowett-MSFT** [comment]
So, this is a strange case. Yeah, it shouldn't be doing that. But everything I can find tells me that Meslo is authored or patched incorrectly.

Check this out.

There is a glyph dedicated to the `fi` ligature. Here's what it looks like in Meslo LGL NF:

![image](https://user-images.githubusercontent.com/14316954/60634472-d472fd00-9dc3-11e9-971c-fbcc0d9eb7a2.png)

Now, that shouldn't matter. The glyph doesn't have to be used.

Except, it is. It's the ligature for `f` `i`...

![image](https://user-images.githubusercontent.com/14316954/60634493-e8b6fa00-9dc3-11e9-9474-f763b19665ef.png)

Now, because that information is encoded in the font? Terminal is doing the right thing and ligating `f` `i` together into ![image](https://user-images.githubusercontent.com/14316954/60634507-f53b5280-9dc3-11e9-8140-a53936b9947d.png).

**Comment by ctolkien** [comment]
Confirming, you're bang on. When looking at the font in settings:

![image](https://user-images.githubusercontent.com/515955/60774535-8578ef00-a158-11e9-8f74-79e4e9f0942b.png)
