### ISSUE TITLE
Latest builds do not honor my system's accent color

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/terminal#1843]
# Environment

```none
Windows build number: 10.0.18362.207
Windows Terminal version (if applicable): Daily build from 7/4/2019

Any other software?
```

# Steps to reproduce

Just run WindowsTerminal and make sure it is the active window.  I also have the dark theme configured on my system with a Blue accent color.

# Expected behavior
The window title bar area not covered by tabs should reflect my configured accent color - Blue like this:

![image](https://user-images.githubusercontent.com/5177512/60738908-21b6b200-9f1d-11e9-9744-6a8435f777a4.png)

BTW the above is from the store version of WT so something has changed for the worse.  

# Actual behavior
The window title bar area not covered by tabs is black:

![image](https://user-images.githubusercontent.com/5177512/60739019-87a33980-9f1d-11e9-951a-400f6d3095ec.png)

Also, not a fan on the rounded corners.  Every other Window on my system uses my accent color (and **not** rounded corners) e.g.:

File Explorer:
![image](https://user-images.githubusercontent.com/5177512/60738975-617d9980-9f1d-11e9-95dc-4af9bb62332c.png)

Notepad:
![image](https://user-images.githubusercontent.com/5177512/60739067-b3262400-9f1d-11e9-92c3-78c0c756f4ee.png)

You get the idea.

**Comment by DHowett-MSFT** [comment]
You might be the only person who _liked_ how it was before with the weird keystone cut out of the accent-color window. That was always a stopgap until we could get full non-client area painting in.

I'm going to dupe this to #1375 to focus our efforts. Suffice it to say that "supporting various themes" is important, and following the system accent color is just another one of those themes.

Incidentally, the rounded corners are because the kernel (yeah, don't ask) hands back a window region that matches the Windows Vista Aero Basic shape :grin:.

**Comment by rkeithhill** [comment]
Sorry for the dupe. Didn't see 1375 until you pointed it out.  Yeah, I get it that it's far from done.  Just wanted to make sure my issue was captured.  FWIW I think there is a benefit to having the window chrome style look consistent with the rest of my windows.  At the very least, maybe we could have another option to use the system accent color?
