### ISSUE TITLE
Path environment variable with spaces cannot be passed into cmd/powershell terminal

### ISSUE THREAD

**Issue by peidaqi** [microsoft/terminal#1847]
# Environment
Windows 10 b1903 18932.1000
```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?
```

# Steps to reproduce

Add a path with spaces in System-Environment Variables at the end of existing ones, e.g.
PATH=C:\Windows;C:\Windows\System32;C:\Program Files\Microsoft VS Code Insiders\bin

# Expected behavior

New path working.

# Actual behavior

By typing "path" with a cmd terminal or "$env:path" with powershell, the path entry with spaces disappeared.

**Comment by DHowett-MSFT** [comment]
You will need to clarify _how you are adding this variable to `PATH`_.

**Comment by peidaqi** [comment]
Control Panel -> System Properties -> Environment Variables

![image](https://user-images.githubusercontent.com/18495787/60746456-d4523900-9f4c-11e9-985d-0a2302edfa29.png)

**Comment by DHowett-MSFT** [comment]
That doesn't answer the question. How did you set PATH? _WHEN_ did you set PATH? Have you relaunched Windows Terminal since you set PATH?

**Comment by peidaqi** [comment]
Yes I set the environment variables before starting both cmd and Windows Terminal so that they could inherit them. Also tried restarting the entire system, which doesn't help.

By the way, I get your point, but is it REALLY _NECESSARY_ to capitalize and italicize the words??

**Comment by DHowett-MSFT** [comment]
Er, sorry, I was only capitalizing PATH because that's its official name :smile:. As for "WHEN," it was probably not necessary. My worry was that we might be missing one of the system state change messages that lets us know that the system's environment has changed, but if you've rebooted then that's off the table.

**Comment by peidaqi** [comment]
That's all right. It's a very bizzare issue - I don't have anyone else with a Windows machine so not sure if it's re-producible though.

**Comment by zadjii-msft** [comment]
So the spaces are totally a red herring here, right? The first entry on your PATH has spaces: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath`

I'm also pretty sure it's not universal to the VS Code path, since that's working fine on my machine:
![image](https://user-images.githubusercontent.com/18356694/60815177-ab07f780-a15c-11e9-94bb-6af010b33900.png)

Maybe it's possible we're mangling PATHs with lots of entries. @peidaqi if you move the vs code PATH entry earlier in the PATH, does it appear in the right place, with the last entry not appearing?

**Comment by peidaqi** [comment]
Good observation... I just realzied it's because I have a duplicated entry in both User Environment Variables and System Environment Variables. Windows Terminal removed the duplicated one with User, while CMD kept both.
