### ISSUE TITLE
Unable to permanently set codepage to 65001 in `wt.exe`

### ISSUE THREAD

**Issue by rivy** [microsoft/terminal#1852]
# Environment

```none
C:\>ver
Microsoft Windows [Version 10.0.18362.175]

C:\>where wt.exe
C:\Users\Roy\AppData\Local\Microsoft\WindowsApps\wt.exe

C:\>echo %LocalAppData%
LOCALAPPDATA=C:\Users\Roy\AppData\Local
```

# Steps to reproduce

Setting "CodePage" within the registry doesn't result in the correct code page within the `wt` terminal window.

Neither this ...

```none
C:\>C:\Windows\System32\reg.exe add HKCU\Console\%LocalAppData^%_Microsoft_WindowsApps_wt.exe /v CodePage /t REG_DWORD /d 65001 /f
The operation completed successfully.
```

nor this ...

```none
C:\>C:\Windows\System32\reg.exe add HKCU\Console\C:_Users_Roy_AppData_Local_Microsoft_WindowsApps_wt.exe /v CodePage /t REG_DWORD /d 65001 /f
The operation completed successfully.
```
result in the correct codepage within the `wt` terminal window..

# Expected behavior

```none
C:>chcp
Active code page: 65001
```

# Actual behavior

```none
C:\>chcp
Active code page: 437
```

**Comment by rivy** [comment]
I can force the codepage to 65001 by enabling `BETA: Use Unicode UTF-8 for worldwide language support` in the "Control Panel \ Clock and Region \ Region \  Administrative \ Change system locale..." dialog box and rebooting.

But, I would expect a less global setting to be available.

**Comment by DHowett-MSFT** [comment]
This boils down to #1802. You’re unable to set the console codepage for WT using the Console registry keys because _wt is not a console application._ Those keys only apply to things that run INSIDE consoles, not things that ARE console hosts.

What we need is a way for WT to force its connected console hosts to be in codepage 65001. That’s the essence of 1802.
