### ISSUE TITLE
Bug Report - Powershell Get-Credential doesn't work

### ISSUE THREAD

**Issue by kevinteynor** [microsoft/terminal#1911]
## Environment

Windows build number: 10.0.18362.175
Windows Terminal: built from master af1a4dd068171c7cbbca42c69082fef3ba501efc

## Steps to reproduce

In a powershell window, execute the command ```Get-Credential```

## Expected behavior

The credential dialog should open and be interactive; I should be able to enter inputs and close the dialog.

## Actual behavior

The credential dialog appears and can be dragged around, but no buttons or input fields on it are responsive. It also blocks the rest of the terminal, requiring me to kill and restart the entire terminal.

This happens even when launching terminal as admin.

Other GUI dialogs (Show-Command) work as expected, but I haven't tried with any other blocking dialogs.

**Comment by oising** [comment]
powershell 5.x or pwsh (powershell core)?

**Comment by WSLUser** [comment]
Not sure if this counts but using the Store release, it works in Windows Powershell. I have pwsh installed on Pengwin so this may be where things differ. After launching Pengwin from Terminal, I entered pwsh and executed the same command. Since it was launched in Pengwin, I don't get a dialog box, instead, you enter the credentials inside the Terminal. This works.
