### ISSUE TITLE
Bug Report - Windows Terminal doesn't start with some characters

### ISSUE THREAD

**Issue by DY1TzJkqODtTqOI** [microsoft/terminal#1961]
# Environment

```none
Windows Terminal version: Microsoft Windows [Version 10.0.18362.239]
Linux subsystem in Windows <a href="https://www.microsoft.com/en-us/p/kali-linux/9pkr34tncv07?activetab=pivot:overviewtab" target="_blank">(you can download it from here!)</a><a href="https://www.kali.org/news/kali-linux-in-the-windows-app-store/" target="_blank">(and the docs here!)</a>
Dual boot with Linux
```

# Steps to reproduce
If i change the settings of the Windows Terminal, create a new profile and set it default with Linux (not powershell or cmd) , modify the property 'fontFace' from 'Consolas' to 'Rubik' (font on fonts.google.com). Close all windows and try to open Windows Terminal it won't open, if i change it back to 'Consolas' and try to open it this time it will start.

# Expected behavior

Change the font and work properly.

# Actual behavior

App doesn't start.

**Comment by gifuthornberkanan** [comment]
I'm getting the same issue but it seems inconsistent which fonts trigger this.

For me 'Droid Sans Mono for Powerline' does work but 'Droid Sans Mono Slashed for Powerline' and 'Droid Sans Mono Dotted for Powerline' both cause the app to crash.

Also in addition to the OP's description of the problem, I also noticed that if you have the profile.json open at the same time as the terminal app, and then change the font to a "bad" font and Save, the terminal crashes and closes right away.

**Comment by gifuthornberkanan** [comment]
Just did a little more quick testing and if you set the "fontFace"property to a non-existant font, the terminal does not crash.

I tried setting it to 'Draid Sans Mono for Powerline' (which is not a real or installed font on my system) and also 'Courier Old' (also not real) and the terminal didn't crash but the font size did change to what looked like a 1 point font.

So it seems like specific fonts are causing it to crash as opposed to not being set to a real/installed font.

**Comment by DY1TzJkqODtTqOI** [comment]
> 
> 
> Just did a little more quick testing and if you set the "fontFace"property to a non-existant font, the terminal does not crash.

If you try something that he doesn't like (false settings, non existing fonts, ecc,) the terminal strt with the default settings ("factory default").
that is normal (i think).
Anyway Good job with the Terminal, keep it up :-D

**Comment by gifuthornberkanan** [comment]
I did more testing and I'm not sure if I'm having the exact same issue as the OP.

I'm pretty sure that the cause of my crashing is when I try to save with a font whose name is 32 characters or more.

Evidence:
"fontFace" : "Roboto Mono Light for Powerline" (font name is 31 chars) --> saves and font changes on the terminal (expected behavior)
"fontFace" : "Roboto Mono Light for Powerlinex" (font name is 32 chars) --> terminal immediately crashes

"fontFace" : "Roboto Mono Thin for Powerline" (font name is 30 chars) --> saves and font changes on the terminal (expected behavior)
"fontFace" : "Roboto Mono Thin for Powerlinex" (font name is 31 chars) --> not a real font so font displayed on terminal becomes 1 point
"fontFace" : "Roboto Mono Thin for Powerlinexx" (font name is 32 chars) --> terminal immediately crashes

I'd be interested to see if the OP's font actually has a longer name then just "Rubik". If not, then my problem might be different and I'll start my own issue.

**Comment by DHowett-MSFT** [comment]
If you do, make sure you look at #602!

**Comment by gifuthornberkanan** [comment]
Yup! That's my issue. I did try to look through the backlog but I guess I didn't look hard enough.

**Comment by DY1TzJkqODtTqOI** [comment]
> 
> 
> I'd be interested to see if the OP's font actually has a longer name then just "Rubik". If not, then my problem might be different and I'll start my own issue.

As i said in the Original post you can go on https://fonts.google.com/ to 'test' fonts (Copy paste the names), if you want to see the font that i was talking about just go here ---> https://fonts.google.com/specimen/Rubik

**Comment by mdizzy** [comment]
Why is this closed? The OP said the bug wasn't due to font name length.

**Comment by DY1TzJkqODtTqOI** [comment]
@mdizzy i don't know

**Comment by zadjii-msft** [comment]
I think this is closed because it's a dupe of another issue that's known, but the actual issue wasn't linked here.

From playing around with the font myself, it looks like the bug is one of the following:
1. Specifying a font name that doesn't actually exist causes the terminal to crash
2. Rubik might not actually be a monospaced font. 
3. When I was playing with it, I say some artifacts similar to #610

![image](https://user-images.githubusercontent.com/18356694/62707238-ab431f00-b9b6-11e9-9580-6c6aa2102efe.png)


* "Rubik Regular" would not be found, and we'd fallback to Consolas
