### ISSUE TITLE
Make this available to versions older than 1903

### ISSUE THREAD

**Issue by pedro2555** [microsoft/terminal#2024]
This is probably the longest shot I've done with Microsoft.

Without wanting to get into discussion about the matter, the Windows update is broken, and version 1903 will only be available for my machine September 2020, company policy.

The fact that the windows terminal requires 1903 is a deal breaker.

Any chance to get compiled binaries from somewhere else than the App Store for <1903?

**Comment by zadjii-msft** [comment]
We've actually [discussed ](https://github.com/microsoft/terminal/issues/1643#issuecomment-505971691)[at](https://github.com/microsoft/terminal/issues/1909#issuecomment-510042323) [length ](https://github.com/microsoft/terminal/issues/841#issuecomment-492940388)[in this](https://github.com/microsoft/terminal/issues/498#issuecomment-490091740) [repo](https://github.com/microsoft/terminal/issues/1893#issuecomment-509728952) about how we're dependent upon OS features that are only available in 1903 or later. Because of them, we unfortunatelywon't be able to bring the terminal downlevel :/.

**Comment by pedro2555** [comment]
What a bummer. So no windows terminal after all. So much hype for nothing.

**Comment by pedro2555** [comment]
Anyway, thanks for the quick reply.
