### ISSUE TITLE
scroll in tmux does not get the same result as ubuntu terminal does

### ISSUE THREAD

**Issue by optlee** [microsoft/terminal#2056]
this is ubuntu terminal get when scroll up in terminal ( it is true history result of terminal)
![image](https://user-images.githubusercontent.com/1232296/61619918-5eff9b80-aca2-11e9-8704-a1a8c65e40cd.png)

this is terminal get
![image](https://user-images.githubusercontent.com/1232296/61619973-7e96c400-aca2-11e9-8d1b-12646da81b07.png)

**Comment by DHowett-MSFT** [comment]
Just to be certain: this is what happens when you use your mouse to scroll, and tmux scrolls off the bottom of the screen instead of staying in place and scrolling inside it?

**Comment by DHowett-MSFT** [comment]
(Note to self: i think this is probably related to not supporting alt buffer at the terminal level (outside of conpty))

**Comment by optlee** [comment]
what do you mean scroll inside it ?

**Comment by DHowett-MSFT** [comment]
Sorry, I was attempting to determine whether you were scrolling _the actual terminal history_ or whether your mouse events were going into tmux and tmux was implementing its own scrolling.

Judging by the tmux indicator in the top right of the "working" screenshot, this is caused by a lack of mouse support in Windows Terminal and ConPTY. #545 #376.
