### ISSUE TITLE
When a dialog is open, the titlebar is the wrong color

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#2100]
related to #1625.

![image](https://user-images.githubusercontent.com/18356694/61895322-04e81b80-aed8-11e9-8ecc-ce908f185e69.png)

This one's tricky - the Background of the TabRow doesn't actually change here, it's just being combined with the overlay of the ContentDialog. We'd have to compose that color ourselves in the NonClientWindow class.

**Comment by DHowett-MSFT** [comment]
Alternatively, we may want to disable the cutout when a dialog is up.

**Comment by greg904** [comment]
I have an idea. Would it be possible to replace the `SetWindowRgn` trickery by a completely transparent, invisible window that we put on top of the drag bar and that catches all of the mouse events. If this works then it means that the XAML can draw its own drag bar so this bug goes away and also it will allow for acrylic title bar.

I got this idea by using looking at the Settings UWP app's window using a tool called Spy++.
It looks like it does something similar to this (but not exactly this because the window's size is not exactly the same as the title bar's size) with a window called `ApplicationFrameInputSinkWindow` that only receive messages when I put my mouse on the drag bar:
![image](https://user-images.githubusercontent.com/56923875/74767398-15eae680-5287-11ea-9440-1e8725b86684.png)


I don't know if that would work but I might try to do it when I have free time.
