### ISSUE TITLE
Undeterministic glitches of text with colored background

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#2130]
# Environment

bd5cae13

# Steps to reproduce

Run program of this kind:
```
int main()
{
	cout << "\x1B[41m";
	cout << "X Red ";
	cout << "\x1B[42m";
	cout << "Green\n";
	cout << "\x1B[43m";
	cout << "Yellow ";
	cout << "\x1B[44m";
	cout << "Blue";
	cout << "\x1B[0m";
	return 0;
}
```

# Expected behavior
![image](https://user-images.githubusercontent.com/38111589/61995695-ff333700-b08b-11e9-92b6-86a1e8f60457.png)

# Actual behavior
![bug](https://user-images.githubusercontent.com/38111589/61995698-09edcc00-b08c-11e9-8d15-567a2e3110a2.png)

**Comment by j4james** [comment]
Unless you have set the VirtualTerminalLevel registry setting, those escape sequences shouldn't be interpreted at all, so your program really shouldn't be displaying any colors. Try running it from a conhost shell to see what I mean.

However, because the Windows Terminal is passing your output through at conpty pipe, I suspect it's accidentally interpreting those escape sequences on the other side of the pipe, and that's when things start to go wrong.

I believe this is a know bug - issue #1965 describes a similar situation.

**Comment by DHowett-MSFT** [comment]
Correct, this just looks like the same issue. If you use `SetConsoleMode` to turn on `ENABLE_VIRTUAL_TERMINAL_PROCESSING` explicitly, does it work fine?

**Comment by mcpiroman** [comment]
@DHowett-MSFT it does
