### ISSUE TITLE
Failed to load settings on startup

### ISSUE THREAD

**Issue by JeffMill** [microsoft/terminal#2182]
# Environment

Microsoft Windows [Version 10.0.18362.267]

# Steps to reproduce

Start terminal

# Expected behavior

No error

# Actual behavior

Failed to load settings
Settings could not be loaded from file - temporarily using the default settings.
Check for syntax errors, including trailing commas.

it's because I was missing "...\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json"
Maybe rather than using defaults, a default file should be written to that location if missing, a message indicating that a default file has been created should be shown once?

**Comment by DHowett-MSFT** [comment]
That's unusual, because this is the empty "first launch" state as well, and that definitely works. We load default settings and save them out to disk whenever we don't have a profile, and that's expected so it doesn't present a dialog. @zadjii-msft thoughts here?

**Comment by JeffMill** [comment]
I figured it out. I somehow had an empty file there which was parsing as invalid json.  Deleting the file created a new default file. Not sure if there's any great resolution for this case, so feel free to close.

**Comment by zadjii-msft** [comment]
Huh. That's certainly super weird. Maybe there was an exception while serializing, which caused us to write the file with _nothing_ in it. 

Unfortunately I don't think we can really do anything without some sort of repro steps for getting into the state with an empty `profiles.json` file.

**Comment by chuckuntulis** [comment]
The reference to "...\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\RoamingState\profiles.json" is only partially useful because a new user, I do not know where to start looking, FOr the cognizeti that may be useful, but where do I start looking for the the ... Much of the information does not give naïve users enough to dig into the problem.

**Comment by JHBonarius** [comment]
Here's my repro:
![afbeelding](https://user-images.githubusercontent.com/36847155/116414851-21e21900-a839-11eb-8989-15f141c1f371.png)
I think it started after an upgrade, but I'm not sure.

**Comment by zadjii-msft** [comment]
@JHBonarius This issue is nearly two years old now - the underlying root cause of OPs issue is almost certainly different than what you're seeing. Would you mind filing a new issue? Make sure to include your terminal version number, how you installed the terminal, and the contents of your settings.json would also be helpful for debugging.

**Comment by Karlheinzniebuhr** [comment]
Same issue, win10 19045.2364 latest Terminal Version on Microsoft Store 

![image](https://user-images.githubusercontent.com/5278928/209336674-ef8ab8e8-cff9-406f-9c91-dfbed38d8b5f.png)

**Comment by LzPhoton** [comment]
I was getting the same error. I fixed it by going to settings 
![image](https://github.com/microsoft/terminal/assets/69617690/f2568c84-2e55-4daa-a260-bce9ca3f60b1)
Command prompt > Delete profile
![image](https://github.com/microsoft/terminal/assets/69617690/94d21f3b-042c-49fb-83dd-397ecb10de5b)

**Comment by ntnghiaw** [comment]
@LzPhoton  Thank you very much. It works for me
