### ISSUE TITLE
Dragging Terminal window results in it turning white and unresponsive

### ISSUE THREAD

**Issue by tonysln** [microsoft/terminal#2217]
# Environment

```none
Windows build number: [Version 10.0.18362.267]
Windows Terminal version: v0.3.2142.0
```

# Steps to reproduce

1. Start up Windows Terminal.
2. Drag the window.

# Expected behavior

The terminal window should move as any other window.

# Actual behavior

The terminal turns white, all tabs and buttons become disabled. The terminal still can be dragged and resized. Maximizing the terminal window restores it back to normal.

![2019-08-03-1545-38](https://user-images.githubusercontent.com/20811603/62412249-319ee000-b608-11e9-8586-c54fc415de45.gif)

**Comment by zadjii-msft** [comment]
So curiously only the Xaml part of the window seems to hide itself. As you can see, the "drag handle" at the top of the window still paints itself correctly when the window turns white. That drag handle is done in Win32, while the rest of the window is all drawn with XAML Islands. If I had to guess, the XAML looks like it is still trying to render itself, because we don't paint the entirety of the win32 window, only the borders and drag area. 

I'm going to summon @ocalvo and @austin-lamb to see if they have any ideas why this might be happening, or if there's anything about the machine configuration that we could use to narrow this problem done. 

Also cc'ing @0warning0error who filed a dupe and might be able to get us more info.

**Comment by cparis** [comment]
Additional detail:
If you are able to send re-size commands to the window, it will start responding again.

For example, Win-Left or Win-Right.  Or if you drag with your mouse to the side of your monitor, or double click on the exposed/functioning title bar.

**Comment by toshkeen** [comment]
I would like to add another observation.

In my case, sending re-size commands does restore the window, but as demonstrated in my gif, the window will become unresponsive once dragged again. However, resizing the window (while it's still responsive) into an entirely different shape fixes this issue and it does not appear again until the terminal is resized back into the initial shape and size, but there's multiple of these shapes.

It seems that this bug happens only with selected shapes of the window, here's another one for example: 

![image](https://user-images.githubusercontent.com/20811603/63469772-b21c6800-c473-11e9-9036-9ac52a6e18e1.png)

If I would make this window a bit wider, the bug would not replicate no matter how much I dragged or resized.

**Comment by toshkeen** [comment]
Yet another addition. 

This bug appeared for me while using the font [Hack](https://sourcefoundry.org/hack/). After switching to something such as Consolas, the bug would not duplicate whatsoever.

**Comment by nc-x** [comment]
According to my limited amount of testing, this only occurs when both these conditions are true - 
```
(number of columns) in {117,118,119,120,121,122,123,124}
(number of rows) in {29,30,31}
```

**Comment by Tembocs** [comment]
Just installed Windows Terminal yesterday and faces the same issue.

**Comment by zadjii-msft** [comment]
@Tembocs & @tonysln - Are either of you still seeing this? This bug is from like, 18 months ago now, and a good amount of our code has changed since then. We also haven't gotten any other reports of this, so I'm thinking this might have just gone away from some other change?

**Comment by tonysln** [comment]
Can't replicate the bug anymore! Using version `1.6.10571.0`.

**Comment by zadjii-msft** [comment]
Fantastic! Glad we fixed it (sometime) 😄
