### ISSUE TITLE
Terminal process remains on background after exiting it

### ISSUE THREAD

**Issue by NDelt** [microsoft/terminal#2258]
# Environment

```none
Windows build number: [run "ver" at a command prompt] 10.0.18362.267
Windows Terminal version (if applicable): v0.3.2142.0

Any other software? No
```

# Steps to reproduce
## Error 1: CMD
1. Open Windows Terminal
2. Open CMD tab
3. Close Terminal

## Error 2: Ubuntu
1. Open Windows Terminal
2. Open Ubuntu tab
3. Input any command
4. Close Terminal

# Actual behavior
## Error 1: CMD
![pic1](https://user-images.githubusercontent.com/46282492/62481181-afbbdc00-b7ec-11e9-999b-c1748d4688f6.png)

## Error 2: Ubuntu
![pic3](https://user-images.githubusercontent.com/46282492/62481575-bc8cff80-b7ed-11e9-9a5f-b0c18d2ccd3a.PNG)

Terminal process remains on background and especially it occupies CPU resources excessively when after exiting terminal used as CMD.

When I use only PowerShell, terminal process disappears from background process list immediately after exiting terminal.

**Comment by dynalz** [comment]
Indeed this happens to me aswell. 
Some scripts I have on python have been running on background without my knowledge after closing out Windows Terminal. I saw them accidentally because logs were being written and I happen to notice.
Quite easy to test running any background process that opens up a port (node API or frontend web dev), in my case, after closing windows terminal http://localhost:8080/ keeps being accessible due to process never shutting down

**Comment by DHowett-MSFT** [comment]
This looks like another shade of #2232.
