### ISSUE TITLE
last line of terminal is not used

### ISSUE THREAD

**Issue by wolf99** [microsoft/terminal#2264]
# Environment

```none
Windows build number: [Version 10.0.18362.239]
Windows Terminal version (if applicable):  0.3.2142.0
```

# Steps to reproduce

1.  Open terminal
2. Run some command that produces output that extends past the bottom of the window (e.g. `dir` on a directory containing lots of files)

# Expected behavior

Output fills all lines of the terminal (such as in cmd)

# Actual behavior

Last line is always blank - acts as if there's some kind of invisible window chrome here

For example, in both the below images, the output extends past the bottom of the window (i.e. scrolling reveals more output below what is currently shown)
The first is in WSL terminal, and uses all lines within the window. The second is in Windows Terminal, the last line is blank; this occurs for all shells within this terminal. (Note that while it is not readily apparent from the screen shots, there are actually further files in the directory listing output than are shown so the last line should actually display the next file in the list)

![image](https://user-images.githubusercontent.com/281700/62485274-31434800-b7b4-11e9-8411-0b29b2384a4f.png)

![image](https://user-images.githubusercontent.com/281700/62485000-600cee80-b7b3-11e9-84a0-564448733030.png)

**Comment by zadjii-msft** [comment]
I bet this is because the last line in the terminal is _just shorter_ than an actual line. If you resize the terminal to be just slightly taller, does the line appear?

I'm _certain_ there's another issue out there tracking the fact that the `initialCols` setting is a little off right now. That's what's probably causing the window to not be the right size, resulting in this last line that's just barely not the right size.

**Comment by mcpiroman** [comment]
But maybe terminal could also render the last line (and last row) even if it doesn't fit entirely

**Comment by wolf99** [comment]
🤦‍♂ This does seem to resolve it!
Close in favour of #2061 then :)
