### ISSUE TITLE
Bug Report: PowerShell Core launched by Azure Cloud Shell bash has positioning issues

### ISSUE THREAD

**Issue by AlanMcBee** [microsoft/terminal#2267]
# Environment

```none
Windows build number: 1903 OS build 18362.239
Windows Terminal version (if applicable): 0.3.2142.0

Any other software? N/A
```

# Steps to reproduce

1. Launch Azure Cloud Shell profile tab and connect/login to Azure
1. Launch PowerShell Core with command: `pwsh`
1. Execute any PowerShell Core commands

# Expected behavior

Cursor position should continue to advance down the console as commands are entered and output is produced by cmdlets.

# Actual behavior

Keyboard-entered input (cursor) is initially repositioned at row 0, column 0 regardless of where the prompt positions the cursor.

![image](https://user-images.githubusercontent.com/37203424/62490064-4c469580-b77d-11e9-91b4-55b02b7fee78.png)

**Comment by DHowett-MSFT** [comment]
This bug is two-fold.

1. Windows Terminal usually had conhost sitting in between client processes and itself doing some basic VT translation for it. Powershell asks where the cursor is, and WT doesn't know to answer.
2. Powershell seems to have this _pathological need_ to know where the cursorm is at all times, which makes it very frustrating to use everywhere but windows.

**Comment by cconrado** [comment]
Yes this drives me crazy lol
