### ISSUE TITLE
Show Image or Video inside Terminal

### ISSUE THREAD

**Issue by jrahma** [microsoft/terminal#2288]
Hi,

Please add **show** command which will show image or video files inside the terminal, crazy idea?

Well, something like this:

`show myphoto.png`

or:

`show myvideo.mpeg`

It can also be shown when using dir so if the file is an image it will show the image in small thumbnail

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by CatTheHacker** [comment]
What real usage does that has?
How does that improves anything?

**Comment by JamesG269** [comment]
I think adding images to the console is a great idea, it allows you to inspect the content without having to switch to another program, so you can see what you are doing commands on. Make it optional of course, for those who don't need or want it. Something like "dir -thumbnails" that shows thumbnails of images or videos is desirable. In addition to utility, it would make the console look pretty cool.

**Comment by WSLUser** [comment]
This is related, a duplicate, or has dependency on https://github.com/microsoft/terminal/issues/448. Actionable for this issue could be usage of a `show` or similar command. This needs to keep in mind compatibility with other shells, especially if sshing into a network device such as those by Cisco where `show` is a primary CLI command.

**Comment by dhrdlicka** [comment]
I guess nothing prevents anyone from implementing this in a separate application or a PowerShell module, as long as the Terminal supports the appropriate VT sequences (#448). However, I see no real reason why should this specific functionality be integrated into the Terminal or the Command Prompt.

I can see some good use cases there, such as being able to inspect image/video files over a remote CLI connection (SSH/telnet), but as I said before, I don't feel like this ability belongs in a terminal nor a shell.

I especially don't hold my hopes high on the "thumbnails in `dir`" idea, since as far as I am aware the Command Prompt is not really actively maintained anymore, being included only for backward compatibility purposes and I am afraid that this would pretty much be a breaking change.

**Comment by JamesG269** [comment]
dir is an alias in powershell, didn't mean cmd.exe.

**Comment by oising** [comment]
Duplicate: https://github.com/microsoft/terminal/issues/448
