### ISSUE TITLE
newTab on current path

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#2315]
# Description of the new feature/enhancement

When opening a new tab AND OPTIONALLY if the current program in the active shell is not the shell program, use the current path of the active shell as the default path for the `newTab` action.

# Proposed technical implementation details (optional)

There should be an option for this.  `useCurrentPath` in `globals` which takes in a string of "never", "always", "whenNotShell"

**Comment by DHowett-MSFT** [comment]
This is one of those things that is impossible in the general case but _technically possible_. There's a lot of intricacies here, like:

```
cmd
powershell
cd d:\users
```

well, powershell isn't the first process we launched. we'd ignore the path `d:\users`

```
(in powershell)
cd d:\users
```

we'd ignore `d:\users` because powershell _doesn't actually set the current working directory_ (!!)

If your "shell" is `ssh dustin@example.com` (where we strictly define shell to be "the first process Terminal spawns on your behalf"), its working directory is always going to be `C:\windows\system32` regardless of what the remote working directory is.

I'd rather not provide the feature than provide the feature with so many caveats that they'd fill a documentation page. ☹️ sorry.

**Comment by DHowett-MSFT** [comment]
Thanks, nonetheless, for the suggestion. We'll keep thinking about this.

**Comment by trajano** [comment]
Hmm that's kind of odd. I would think it's just a matter of reading the process' current directory https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcurrentdirectory and calling https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw with the directory (then again I haven't traversed through the code base yet).

The part I don't know the API for would likely be trying to determine the process itself which I think should be possible because ProcExp shows the following tree

![image](https://user-images.githubusercontent.com/110627/62714196-16e3b700-b9cc-11e9-9f5f-7d7a79ca88ba.png)

But then even the example above if I used git bash it will be in the wrong folder if you're looking at the first process under `conhost.exe`
