### ISSUE TITLE
Create a Mac version

### ISSUE THREAD

**Issue by wess** [microsoft/terminal#2331]
Using this on my windows box has been awesome, and I appreciate all the hard work. When I travel Im on my MacBook Pro, and would love to see a version of this terminal come to Mac.

**Comment by egmontkob** [comment]
For macOS there's [iTerm2](https://iterm2.com/) which is probably the most feature rich terminal emulator out there.

Not serious comment:

iTerm2 has a feature request to get a [Linux port](https://gitlab.com/gnachman/iterm2/issues/7448), GNOME Terminal (or at least VTE) allegedly can be made to [work on Windows](https://bugzilla.gnome.org/show_bug.cgi?id=369310), so with these plus a macOS version of Windows Terminal the circle would close :D

(Disclaimer: I'm just a random guy commenting here, not affiliated with Microsoft.)

**Comment by DHowett-MSFT** [comment]
lol! @wess thanks for the excitement here. There are some really good terminals on OS X, including iTerm and Hyper. Since Windows Terminal requires a good number of windows-specific technologies _today_, I'm going to have to say we won't be supporting it on Mac or anywhere else any time soon.
Sorry!
