### ISSUE TITLE
Code health improvement: Use SAL annotations

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#2404]
# Description of the new feature/enhancement
To help reduce defects and provide better testing, SAL annotations should be applied to all applicable code in this project that utilizes C/C++. Guidance for this can be found at https://docs.microsoft.com/en-us/visualstudio/code-quality/using-sal-annotations-to-reduce-c-cpp-code-defects?view=vs-2019

> SAL is the Microsoft source code annotation language. By using source code annotations, you can make the intent behind your code explicit. These annotations also enable automated static analysis tools to analyze your code more accurately, with significantly fewer false positives and false negatives.

# A clear and concise description of what you want to happen.

For now, I'd just ensure it's applied to new PRs. Going back to the other code can be done as time permits.  A quick action that can be taken in reference to this issue is to update the [Contributor's Guide](https://github.com/microsoft/terminal/blob/master/doc/contributing.md)

This issue can be a placeholder to remain open until SAL annotations are applied across the entire code base (similar to the issues for adopting C++ iso standards).

**Comment by zadjii-msft** [comment]
Summoning @adiviness, @miniksa

**Comment by adiviness** [comment]
I was under the impression that sal was getting deprecated in favor of gsl.

**Comment by WSLUser** [comment]
C++ guidance still point to SAL. Taking a look at the GSL repo, they appear to be in a more beta stage right now. Better to use SAL now and change to GSL later when it has less issues.

**Comment by DHowett-MSFT** [comment]
We're roughly following the windows coding guidelines these days, where we use modern C++ constructs (with checked accessors) and GSL instead of SAL for all new code. We're not likely to go add SAL annotations to the vast majority of our code.

We're using the following "mappings":

* `_In_` -> `const type`
* `_Out_` -> `type&`
* `_Outptr_Maybenull_` -> `type*`
* `_In_reads_` -> STL container `const vector<T>&`, `const array<T>&`, and many others
* `_In_z_` -> probably not much, but preferring `wstring` or `wstring_view`

The list goes on, but we're not likely to introduce annotations for things that can be generally broadly enforced by the actual compiler.
