### ISSUE TITLE
Ctrl+W (search) when using nano closes Terminal

### ISSUE THREAD

**Issue by wpmjones** [microsoft/terminal#2407]
# Environment

```none
Windows build number: [Version 10.0.18362.267]
Windows Terminal version (if applicable): [Version 0.3.2171.0]

Any other software?
```

# Steps to reproduce

ssh into a Linux environment
nano filename.txt
Ctrl+W to search within nano

# Expected behavior

Ctrl+W is used for searching within the nano editor.  Ctrl+W should bring up a search field.

# Actual behavior

When pressing Ctrl+W anywhere within Windows Terminal, it closes the active tab.  This behavior effectively prevents the use of nano's search feature.

**Comment by DHowett-MSFT** [comment]
We changed the default key bindings quite a while ago to move closePane off of Ctrl+W. You should edit your settings to re-bind it to Ctrl+Shift+W.

**Comment by etomProductions** [comment]
Same issue here with both "Ctrl+W" or "Ctrl+Shift+W" in Windows 11 using GCP SSH

**Comment by DHowett** [comment]
You are welcome to change your default key bindings to remove <kbd>Ctrl+Shift+W</kbd>.

As I noted _five years ago,_ we removed the default binding for <kbd>Ctrl+W</kbd> _five years ago_ because of conflicts like this.

If you are still using a settings file from 2019, I am both impressed and horrified.
