### ISSUE TITLE
Copy and Paste Bug while using Ctrl + C and Ctrl + V shortcuts

### ISSUE THREAD

**Issue by nabanita-sarkar** [microsoft/terminal#2420]
# Environment

```none
Windows build number: 1903 for cmd
Windows Terminal version (if applicable): latest from the Microsoft store

Any other software? N/A
```

# Steps to reproduce

Copy any text using keyboard shortcut `ctrl + C` and try to paste it using `ctrl + V` shortcut.

# Expected behavior

This should paste the copied text in the command line.

# Actual behavior

After typing `Ctrl + V` only `^v` is showing.

**Comment by zadjii-msft** [comment]
Do you have keybindings for `copy` and `paste` set in your `profiles.json`?

**Comment by zadjii-msft** [comment]
Also, please refer to [the user documentation](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#adding-copy-and-paste-keybindings)

**Comment by dasMulli** [comment]
Has there been a discussion of changing the defaults to ctrl+c/ctrl+v by default similar to how the default conhost+cmd experience in windows is at the moment? (I assume there is a reason like making a lot of *nix programs hard to use?..)

**Comment by DHowett-MSFT** [comment]
We explicitly changed the defaults away from <kbd>Ctrl+C</kbd>/<kbd>Ctrl+V</kbd> _because_ of that reason -- it's hard to use your shell and your CLI applications when your terminal emulator gets in the way by eating common key combos. #2446 goes a long way to fixing this, because it lets you bind <kbd>Ctrl+C</kbd> over copy but still send `^C` to the connected application when there's no selection; there is, however, no reasonable heuristic we can use for <kbd>Ctrl+V</kbd>.

We're trying to make something approachable for Windows _and_ Linux folks, but in some cases the best we can do is choose one option and make it trivially easy to change for the people who disagree.

**Comment by nabanita-sarkar** [comment]
Okay

**Comment by onionhammer** [comment]
What was wrong w/ how it worked in the other command prompt?

If text is selected CTRL+C copies
if text is not selected CTRL+C sends signal

**Comment by zadjii-msft** [comment]
@onionhammer When that comment was authored, the Terminal had a bug where whatever keybinding you had for copy would always try to copy, even if there wasn't a selection. Now that that bug is fixed, we can think about maybe adding Ctrl+C as a default copy keybinding again.

**Comment by onionhammer** [comment]
@zadjii-msft afaict it works perfectly if I just add the key-binding in manually

**Comment by iliveforfun** [comment]
> Also, please refer to [the user documentation](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#adding-copy-and-paste-keybindings)

**already solve my problem**  but is there a strict format for the definition of such command? cuz when I type a command for copying, error always happens. Although my format looks like other comand
