### ISSUE TITLE
Git commit -m closes the terminal using zsh + oh my zsh

### ISSUE THREAD

**Issue by eullercdr** [microsoft/terminal#2518]
Dears,

I have a problem in terminal WSL, when i type git commit -m the terminal is closed!

Note: In the default terminal, this error does not happen. The error happens when I install zsh + plugin oh my zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

My windows build is Windows 10 Pro, 1903.

I have been installed Ubuntu 18.04 LTS.

Can you help me please?

**Comment by billpereira** [comment]
We have faced the same issues... but with some tests we noticed that the following plugin was causing it: zdharma/fast-syntax-highlighting

Do you also have it installed?

**Comment by zadjii-msft** [comment]
Does this repro in both the Windows Terminal and a conhost (cmd.exe, powershell.exe, wsl.exe) window?

Does this repro in both `bash` and `zsh`?

**Comment by jonatasbr** [comment]
In the WSL happens.
In the others not happens.

@zadjii-msft

**Comment by mufeez-amjad** [comment]
having the same issue, commenting to follow

**Comment by zadjii-msft** [comment]
For the record, this is a perfectly good button for following an issue without notifying everyone else on the thread already:
![image](https://user-images.githubusercontent.com/18356694/64713686-31e59300-d472-11e9-807d-ff6abad7aaad.png)

<hr>

@mufeez-amjad @jonatasbr @eullercdr If you're seeing this, could you follow the Feedback Hub instructions the bot posted? We need more information to be able to investigate this, since we can't repro this on our end.
