### ISSUE TITLE
Do not pad tabs from the top when maximized or fullscreen

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#2541]
# Description of the new feature/enhancement

Edge and most other programs that use tabs where a menu bar is not present keep the tabs flush to the top of the screen rather than padding it down.  

# Proposed technical implementation details (optional)

Make Terminal consistent with Edge Dev (ideally use the same code if possible) to render the tabs on top.

**Comment by imjasonmiller** [comment]
They are aware of it, as it has been mentioned in #1375, under “Things related to tabs”

**Comment by WSLUser** [comment]
> where a menu bar is not present

Edge (or Chrome for that matter) aren't responsible for it. Chromium is. Since Terminal isn't Chromium based, re-use can't happen. Incidentally, I (along with many others) would prefer a menu bar like IE in Edge. I actually opened a ticket for it on the Chromium bug tracker but will probably need more input on the bug tracker to get any type of action on it. Honestly a menu bar in Terminal would be great as well and I'm sure it will be addressed in #1375.

**Comment by vadimkantorov** [comment]
To not lose context: in 
https://github.com/microsoft/terminal/issues/4479#issuecomment-582535106 @DHowett-MSFT mentioned that the complain of https://github.com/microsoft/terminal/issues/4479 would be copied here, but it was somehow forgotten

**Comment by DHowett-MSFT** [comment]
Thanks!

**Comment by sjoshid** [comment]
Is there a reason why a padding must exists for a floating window?

**Comment by DHowett** [comment]
It's what every other commonly-used tabbed application has padding above the tabs for a drag/resize area, except for perhaps Firefox.

**Comment by sjoshid** [comment]
Im using Chrome Edge and even in floating window there is enough gap to drag the window no matter how many tabs you add. And yes Firefox does it best.
