### ISSUE TITLE
Windows Terminal Settings, open profile in Jason with Visual Studio

### ISSUE THREAD

**Issue by Johnabarreto** [microsoft/terminal#2599]
When entering the configuration parameters it automatically opens the profile in Json, I don't know if this only affects when they have Visual Studio installed.

**Comment by zadjii-msft** [comment]
That's by design - the settings are only available as a JSON file currently. When you install Visual Studio, VS will automatically configure itself as the default application for `.json` files. If you want it to open in another application, you can feel free to change the default editor for `.json` files.
