### ISSUE TITLE
Guidance - S mode support?

### ISSUE THREAD

**Issue by svgPhoenix** [microsoft/terminal#2624]
Hey I couldn't find anything about whether this is intended to work on devices in S mode. (My device is in S mode and crashes when I try to open it.) I will submit a bug report with Feedback Hub diagnostics if it's supposed to.

**Comment by DHowett-MSFT** [comment]
It’s not supposed to, sorry. CMD and PowerShell are restricted on S mode devices by policy, and we can’t countermand that policy.

**Comment by svgPhoenix** [comment]
Could you mention that in the readme please?

**Comment by bitcrazed** [comment]
@svgPhoenix Will do - thanks for the suggestion.

Also, when you say "it crashes when I try to open it", I assume you mean Terminal? If so, could you share what errors etc. you see here too? Sorry to bifurcate you across two feedback mechanisms, but it might shorten the path to a root cause by doing so in this case.

**Comment by svgPhoenix** [comment]
@bitcrazed Yeah, I meant Terminal Preview crashes - not windows itself lol. [Here's the link to my diagnostic data on Feedback Hub.](https://github.com/microsoft/terminal/issues/2624#issuecomment-528047633) Terminal doesn't give any errors or anything, just closes as soon as the frame renders.
