### ISSUE TITLE
"suppressApplicationTitle" doesn't work (or exist.)

### ISSUE THREAD

**Issue by aedm** [microsoft/terminal#2645]
# Environment

```
Windows 10.0.18362.0
Terminal: 0.4.2382.0
```

# Steps to reproduce

1. Add custom, permanent tab titles for some of the profiles:
```
  "tabTitle" : "gateway",
  "suppressApplicationTitle": true,
```
2. Start a new application in these tabs.

I took the syntax from the PR by @zadjii-msft: https://github.com/microsoft/terminal/pull/2373#issuecomment-520832247

# Expected behavior

Tab titles don't change, they keep the value specified in `tabTitle`, just like they used to in Terminal 0.3.x.

# Actual behavior

Tab titles change to reflect the currently running program.

Here I'm running three different applications using `npm start`. I've set up a different, useful `tabTitle` for all of these tabs, but all I see is this:

![image](https://user-images.githubusercontent.com/7765984/64156420-05f45d00-ce35-11e9-9d97-01cb2ff558de.png)

# Note

From #2373: _"d. We'll add suppressApplicationTitle when someone complains"_ <- Here I am. :)

**Comment by rkevingibson** [comment]
Strong upvote for this. This most recent update made my nice short tab titles into 80 character long beasts when using razzle, and they all contain useless information.

**Comment by DHowett-MSFT** [comment]
@rkevingibson you knwo you can use the `title` command (from CMD) to reset them, right? PowerShell also affords `$Host.UI.RawUI.Title`. A lot of these are better options than a strict override, unless the application has _absolutely no other way_ of fixing the title. It's a huge hammer.

**Comment by aedm** [comment]
@DHowett-MSFT It would be a very good solution, but it doesn't always work. Some apps like `npm` completely override `title`.

![2019-09-06_16-18-27](https://user-images.githubusercontent.com/7765984/64435188-52a09800-d0c2-11e9-8540-16371a911dc1.gif)

**Comment by encladeus** [comment]
@DHowett-MSFT  as mentioned by @aedm, I too have observed issues whereby **tabTitle** and the **title** command in the command prompt are overridden dynamically. Sometimes at the end of running a batch file to build code from the command line, after the title has changed dynamically in the tab, it may or may not revert back to the title set before the batch file was run.

For example, after setting title to x64, as also defined in tabTitle, the following happens while the batch file is running (for several minutes). 
![title2](https://user-images.githubusercontent.com/8571098/64436343-0f432b00-d0bc-11e9-8d95-4d62ccb6565b.png)

So in the case above the title eventually reverted back to **x64**, but this one didn't revert back to **x86** (shown in previous image) after completion of the batch file:
![title1](https://user-images.githubusercontent.com/8571098/64436555-84aefb80-d0bc-11e9-8f63-06943f416453.png)

I definitely prefer a method, perhaps by using `tabTitle `and `suppressApplicationTitle = true` so that once set it never changes. Meanwhile, it also looks like something is not working as expected.

**Comment by timespinner** [comment]
I would vote for a more dynamic solution if the title is not set - have optional tabMinWidth and tabMaxWidth properties, and shorten the width of all tabs, stopping at minWidth as width of the overall terminal decreases.  If the overall width increases, increase the width of all tabs until maxWidth is reached.  Scrollbars only appear if tabs can't be shortened any more and then disappear where there is enough room.  This will ensure that all tabs appear without having to scroll, and still gives you dynamic titles, which is quite critical.

**Comment by 4k3or3et** [comment]
Hi guys,

i just updated Windows Terminal to Version: 0.7.3291.0. I have implemented in the config:

            "commandline" : "%windir%/system32/openssh/ssh.exe root@192.168.1.2
            "name" : "My Linux box",
            "tabTitle" : "My Linux box",
            "suppressApplicationTitle" : true,

However when i start new tab with that profile, title still changes to 'OpenSSH SSH client'.

Am i doing something wrong guys?

Thanks for any clues...

**Comment by supermartzin** [comment]
Same issue here, the setting doesn't work for me either :(

**Comment by asmh1989** [comment]
@4k3or3et  i delete `tabTitle`,  it works

**Comment by 4k3or3et** [comment]
> @4k3or3et i delete `tabTitle`, it works

I just tried to delete `tabTitle`. Title still changes to 'OpenSSH SSH client'

Anything else i can try?

> Same issue here, the setting doesn't work for me either :(

Did you manage to resolve it on your config?
