### ISSUE TITLE
Preview 0.4 asset fails to install (hangs on 'Installing required frameworks 16%')

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/terminal#2647]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): 0.4.2382.0

Any other software? N/A
```

# Steps to reproduce

Download and run https://github.com/microsoft/terminal/releases/download/v0.4.2382.0/Microsoft.WindowsTerminal_0.4.2382.0_8wekyb3d8bbwe.msixbundle

# Expected behavior

Install should complete

# Actual behavior

Installer window appears but hangs at:

![image](https://user-images.githubusercontent.com/7724321/64169094-de0cf580-ce44-11e9-8138-4e6269f08ae8.png)

There is no commentary to say why it has hung.

The PC is behind a corporate proxy server.

Terminal v.0.3 previously installed successfully using Github asset in similar environment.

**Comment by rogenaro** [comment]
I had that same problem with preview 0.3, being behind a corporate proxy too.
I was able to get a few directions on the installation log when I tried to install the package on PowerShell with the command `Add-AppxPackage -Path <path-to-the-msixbundle-file>`
Back then, the problem was related with a dependency on the package VCLibs.140, that couldn't be downloaded from the store because of the proxy.
I ended up downloading the VCLibs.140 package in another PC and installed it using the `Add-AppxPackage` cmdlet on PowerShell.
After this I was able to install both Windows Terminal Preview 0.3 and 0.4 on using PowerShell.

**Comment by bitcrazed** [comment]
@DavidA2014 As @rogenaro points out, looks like you're struggling to download dependencies (probably the VCLibs.140 package which is required by all Centennial apps), likely due to your corporate proxy. Please try manually downloading and installing VCLibs.140 from the link provided part way down [this article](https://blogs.msdn.microsoft.com/appconsult/2016/10/20/desktop-bridge-how-to-handle-c-and-c-dependencies-with-the-desktop-app-converter/).

Closing for now, but please re-open if this does not solve your installation problems.

**Comment by DavidA2014** [comment]
@bitcrazed Thanks for your reply. I tried installing the VCLibs.140 package (from https://www.microsoft.com/en-us/download/details.aspx?id=53175) but the Terminal install still hangs at 16%.  So I would like to reopen this issue.  Is there an installation log that would help identify where it is hanging?

**Comment by bitcrazed** [comment]
Thanks @DavidA2014. Reopening. 

Did you restart your machine after installing VCLibs.140?

I've asked the app install team to take a look at this thread too - hopefully they can provide guidance / log collection instructions.

**Comment by DavidA2014** [comment]
@bitcrazed Sorry, I hadn't restarted the machine. I have now done so and the Terminal installer ran successfully. Thanks for your help.

I wonder if something could be added to the instructions at https://github.com/microsoft/terminal about the possible requirement to install the package manually if behind a proxy?

**Comment by bitcrazed** [comment]
Great suggestion. I’ll be revising readme next week and will incorporate.

Rich.

**Comment by zadjii-msft** [comment]
You know, I don't think we do this at all anymore. I'm gonna close this.
