### ISSUE TITLE
Add app execution alias for "cmd" or "bash"

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#2653]
# Description of the new feature/enhancement

Add additional app execution aliases in addition to `wt`

# Proposed technical implementation details (optional)

I am used to pressing Win-R then "cmd" to open up a command prompt, can you provide an option for adding `bash` and `cmd` as additional aliases (which are disabled by default).  Also detect that they are being used and start up the appropriate shell.

**Comment by DHowett-MSFT** [comment]
Thanks! Wow, this is a terrifying idea that just might work! However, we don't want to stomp `cmd` or `bash` or `wsl` for anybody who has Terminal installed, because those are used in _huge number_ during automation. This would break even running `cmd` from CMD.

We're going to tackle this more holistically at the OS level with #492.

/dup #492
