### ISSUE TITLE
Bug Report: Clicking console window pauses application

### ISSUE THREAD

**Issue by tamusjroyce** [microsoft/terminal#2678]
Per https://serverfault.com/questions/204150/sometimes-powershell-stops-sending-output-until-i-press-enter-why

Legacy console did not pause. However, the new console does pause (I thought randomly...but seems like user input is the cause) while executing long-running processes like npm install.

Could Quick **Edit Mode** and **Insert Mode** be deselected by default?

# Environment
Windows 10 Enterprise

# Steps to reproduce

Click on the window, the console pauses

After
1. **Edit Mode** and **Insert Mode** inside console properties is checked
2. Running a long-running process
3. Clicking the console window (text not scrolling)
4. Leaving for lunch
5. Return, unlock computer, make console active
6. Hit enter and progress continues

No progress was being made. This was not a production issue. However, without changing these settings, it could cause production issues.

# Expected behavior

Any process that is started continues running

# Actual behavior

Process pauses mid-run

**Comment by ngudbhav** [comment]
This happens with me on legacy console. Running, say node app.js and going into the select mode, the server stops sending response and the browser is stuck on 'waiting for localhost...'. It is only after I click to exit the select mode, the response is successfully received by browser.
This may have something to do with how CMD handles.

**Comment by DHowett-MSFT** [comment]
Hey @tamusjroyce! Sorry about the delay here. This is, unfortunately, one of those big polarizing features we can't change in the legacy console. There's a couple reasons:

1. User behavior. The people who love this feature _really love it_. They'll go to the mats over this feature.
1. Since console applications get fairly intimate control over the windows they're hosted in (which in hindsight was certainly the wrong decision), some applications actually use this to pause their own output. There's also an API for querying whether output is currently paused (I think.)

We're not going to turn off **Quick Edit** mode by default, either, as that was hailed as a huge advance in the usability of the console some four and a half years ago.

This one's just going to have to be "by design." Sorry!

**Comment by mathfirst** [comment]
My python program was paused accidentally. How can I resume my program?

**Comment by zadjii-msft** [comment]
Try hitting <kbd>esc</kbd>
