### ISSUE TITLE
Window does not react to PowerToys

### ISSUE THREAD

**Issue by Qingtian-Zou** [microsoft/terminal#2689]
# Environment

```
Windows build number:[Version 10.0.18362.295]
Windows Terminal version (if applicable): 0.4.2382.0

PowerToys: 0.11.0
```

# Steps to reproduce

Hold down the SHIFT key and drag the Windows Terminal window.

# Expected behavior

The FancyZone function in PowerToys should react and resize&put the window to where I want it to be, just like other windows like explorer.exe and firefox.exe.

# Actual behavior

The FancyZone does not react. It just seems to be that I am dragging the window without holding down SHIFT key.

**Comment by zadjii-msft** [comment]
@indierawk2k2 @jeffbog

**Comment by jokeyrhyme** [comment]
Apps that DO 😃 react as expected to SHIFT+drag with FancyZones:

- Command Prompt
- Discord
- Firefox
- Microsoft Store
- Twitch
- Visual Studio Code
- Windows Explorer
- Windows PowerShell

Apps that do NOT 😢 react at all:

- Battle.net
- Chrome
- Windows Terminal

It could be to do with apps that customise their window decorators a certain way? Or perhaps they bind SHIFT so that it can't be detected by FancyZones? 🤷‍♂

**Comment by jokeyrhyme** [comment]
Here's the issue over in the PowerToys project: https://github.com/microsoft/PowerToys/issues/209

**Comment by DHowett-MSFT** [comment]
Closing in favor of the upstream bug. Thanks!
