### ISSUE TITLE
Delay when loading backgroundImage between tabs

### ISSUE THREAD

**Issue by hoxha-saber** [microsoft/terminal#2696]
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version (if applicable): 0.4.2382.0
```

# Steps to reproduce

1) In your profiles.json, create two profiles (we will call them A and B)
2) Give A the space background image and B the tree background image (attached at the bottom)
3) Open windows terminal with A as the default profile
4) Open B in a new tab
# Expected behavior

There should ideally be no delay in loading the background images.
# Actual behavior

When we start with profile A, there will be no delay. However, when opening profile B we see the background is gray for small moment of time. Afterwards, the image loads normally. If we switch between tabs every 1.5 seconds(ish) when going from A to B the image has a delay loading. But if switch quickly there will be no delay. I will add a gif showing the result happening. I'll also add both of the background images I'm using.

![space](https://user-images.githubusercontent.com/26442377/64492305-a933e080-d240-11e9-880b-9299dd703447.jpg)
This is image for profile A.

![sshspace2](https://user-images.githubusercontent.com/26442377/64492317-bfda3780-d240-11e9-8d69-02d8b25ace3a.jpg)
This is image for profile B.

![School2019-09-0813-45-54](https://user-images.githubusercontent.com/26442377/64492400-66263d00-d241-11e9-832e-1ef6dcc31891.gif)
The issue in action.

**Comment by bitcrazed** [comment]
@hoxha-saber The images you shared are full 4k images which, beautiful though they are, take considerable CPU to scale down to fit within the bounds of your Terminal. We do not cache the scaled images in order to avoid caching/live-update issues in the Terminal.

If you scale those images down to a size more like the typical size of your Terminal, they should require much less scaling and take much less time to render. 

If you still see major perf issues, you may want to open an issue on the [Win-UI XAML](https://github.com/Microsoft/microsoft-ui-xaml) project who re responsible for the image rendering control we're using.

Closing this issue for now.

**Comment by hoxha-saber** [comment]
@bitcrazed So you're saying I can't have 8k images as the background and have amazing performance at the same time?????? 

I'm kidding, thanks for taking the time to respond.

**Comment by bitcrazed** [comment]
Pffft! 8K is soooo last year! [16K is the way of the future](https://en.wikipedia.org/wiki/16K_resolution) ;)
