### ISSUE TITLE
Possible to have Acrylic effect remain on window focus loss?

### ISSUE THREAD

**Issue by Kaito0597** [microsoft/terminal#2698]
I love the Acrylic effect in the new terminal. Really gives it a modern feel. But at the moment, whenever you focus on a different program, i.e click away from the terminal, it loses the Acrylic effect and goes to a solid color. I have two monitors so most of the time, I have my terminal visible on the second monitor while working in the first and most of the time the terminal is just a solid black color. Would it be possible to make it so that it keeps the Acrylic effect or is that a limitation of the UI toolkit?

**Comment by DHowett-MSFT** [comment]
Thanks for the request! It is, unfortunately, platform policy. 😦
/dup #2326 #1886 #1747 #1546 #1505 #1099 #593

**Comment by JCKodel** [comment]
> Thanks for the request! It is, unfortunately, platform policy. 😦
> /dup #2326 #1886 #1747 #1546 #1505 #1099 #593

User, who pay for the product "can I have this?"
Company, who need the user "no, we don't hear user's opinion".

Good thing there is a lot of software from companies who DO listen to its customers.

**Comment by zadjii-msft** [comment]
For the record, we _do_ hear this request constantly, and have been working with the XAML team to get this restriction relaxed. Things like this just take time. The place to really make sure your request is heard is over at https://github.com/microsoft/microsoft-ui-xaml

**Comment by RikuXan** [comment]
I have been looking through all the issue duplicates, but haven't found this suggestion anywhere:
Would it be possible to set `useAcrylic` to `false` within `unfocusedAppearance`, so that an unfocused terminal window would still be transparent, just without the Acrylic effect? 
As far as I understood it, the non-Acrylic transparency should still work, even for background windows (and trying it out by disabling Acrylic globally seems to confirm this), but at the moment there seems to be no way to combine the "best of both worlds".
