### ISSUE TITLE
RIS doesn't propagate through ConPTY to clear connected terminal

### ISSUE THREAD

**Issue by watzon** [microsoft/terminal#2715]
# Environment

```none
Windows build number: Win32NT 10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.4.2382.0
Ubuntu WSL version: 1804.2019.521.0
```

# Steps to reproduce

Enter `printf "\033c"` while using WSL in Windows Terminal

# Expected behavior

Console should be cleared, as when using any standard Linux terminal

# Actual behavior

Nothing changes.

Could be related to #140, but it seems like that has been fixed.

**Comment by zadjii-msft** [comment]
Is this maybe #2307, which was fixed in #2367?

cc @j4james

**Comment by j4james** [comment]
@zadjii-msft Yes and no. PR #2367 was just a conhost fix. So while it should improve the behaviour of RIS in the Windows Terminal (e.g. the screen should at least clear), it won't be perfect. Things like the backbuffer clearing would assumedly need special case handling through conpty. I don't know much about that side of things though.

**Comment by mixmastamyk** [comment]
This allowed  `CSI 3 J` but seems to have forgotten RIS?  It least RIS doesn't seem to work for me on the new build mentioned above.

**Comment by studoot** [comment]
And as far as I can tell, the original bug report (printf “\033c” not clearing scrollback in WSL bash) is still the case with the 0.9 build.

**Comment by Lemmingh** [comment]
@studoot , **Clearing scrollback** should be considered as *another* issue related to [ConPTY](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/), I think. Actually, *every* app running in Windows Terminal is experiencing the problem, whether it's PowerShell, WSL, Cmd, etc.

According to issue #1193, there is difficulty in clearing **ConPTY's own buffer**. Thus unfortunately, it's impossible to clear scrollback *entirely* for now.

**Comment by j4james** [comment]
@Lemmingh The problem of clearing the scrollback in PowerShell and Cmd is covered by another issue (#3126), because Windows applications don't use VT sequences like `RIS` and `CSI 3J`. In that case we need to intercept the Windows API calls that are used to clear the scrollback, and then convert them into equivalent VT escape sequences (that's really the whole point of conpty). In a perfect world, fixing those Windows apps would automatically make `RIS` work as well, but in practice it's probably not that simple.
