### ISSUE TITLE
colortool doesn't work when output is redirected to $null

### ISSUE THREAD

**Issue by GoldSubmarine** [microsoft/terminal#2726]
# Environment

```none
Platform     ServicePack    Version            VersionString
--------       -----------      -------              -------------
 Win32NT                         10.0.18362.0     Microsoft Windows NT 10.0.18362.0
```

# Steps to reproduce

if i run the command:  `colortool SolarizedDarkHigherContrast > $null` ,it does not work.

but  the command `colortool SolarizedDarkHigherContrast` works well,i dont want to print the theme information

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment]
ColorTool works, in its traditional mode, by looking at the Console on its output handle. By redirecting the “output” of colortool to `$null`, you’re making it hard for it to find that console to set the color table. Unless we do a lot of possibly fragile work to dig around and open the actual console you were launched from, this is by design.

In general, applications with a strict dependency on a console connection (as opposed to a text stream) are fragile in this way.

**Comment by DHowett-MSFT** [comment]
@zadjii-msft @miniksa should ColorTool explicitly open `CONOUT$`?

**Comment by miniksa** [comment]
> @zadjii-msft Mike Griese FTE @miniksa Michael Niksa FTE should ColorTool explicitly open `CONOUT$`?

It could, but we would have to separate which handle was used to emit the theme information from the one used to send the commands. If we use `CONOUT$` for everything, then the redirection to null won't do anything and the theme information will be emitted contrary to expectation.
