### ISSUE TITLE
utf-8 support in all place of cmd and powershell in UI showing and backing

### ISSUE THREAD

**Issue by lusics** [microsoft/terminal#2748]
this is issue and new feaute 
![image](https://user-images.githubusercontent.com/55165554/64862832-ba1d9100-d648-11e9-89d5-0ad85845130a.png)

**Comment by zadjii-msft** [comment]
@lusics could you be very specific with what's broken and how it should be fixed?

This looks to me like the _main_ problem here is that typing Arabic characters at the input line of Windows Powershell displays question marks instead of the actual characters.
* Does this repro if you `Remove-Module PSReadline`? If so, then this is probably a psreadline bug.
* Does this repro in [Powershell Core](https://aka.ms/pscore6)? If so then it should probably be reported on their repo 
* Does this repro in cmd.exe (within the Windows Terminal)? If so then it's probably a bug on us, but there's a decent chance we won't be able to fix it, for compatability reasons.

There's also a bunch of other things that _might_ be wrong here:
* characters too small: #610 
* We generally don't support RTL characters at all: #538

**Comment by lusics** [comment]
@zadjii-msft 
what you are saying Mr,
the problem is simple :: support utf-8 in powershell and cmd when typing this signs ` ??` has no means, and it is not seem good.

**Comment by j4james** [comment]
I think this may be a PowerShell-specific problem. I can reproduce something similar by pasting some unicode characters at the command prompt in a conhost window. For example, try pasting the command `echo ΩΔΘΣ` into a bash shell, a cmd shell, and a ps shell. This is what I see:

![image](https://user-images.githubusercontent.com/4181424/65373623-f029c900-dc77-11e9-9398-70fed4271b22.png)

And note that the result of the `echo` actually displays the characters correctly - it's only the command prompt itself that messes up. It looks to me like it's trying to convert those characters into approximate equivalents in the single-byte character set of the current locale, and in the worst case you get a `?`.

**Comment by j4james** [comment]
Oh and `Remove-Module PSReadline` definitely fixes the issue for me.

**Comment by lusics** [comment]
this problem comes from core of cmd and powershell not from terminal ...

**Comment by lusics** [comment]
s
