### ISSUE TITLE
Feature Request - Separate taskbar thumbnail for each tab

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/terminal#2887]
# Description of the new feature/enhancement

I think it would be helpful if each tab appeared in its own taskbar thumbnail.  Clicking on the thumbnail would activate the window with that tab open.  The way the app currently works, if you have multiple tabs open and the app is currently in the background you would need to click the taskbar button to switch to the app and then click the tab you want to work with if it's not the currently active one.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Just to be clear, this is different from #1871, right? You want one taskbar entry per tab?

That _must_ be possible, since IE supported it:
![image](https://user-images.githubusercontent.com/18356694/65601301-717aa780-df67-11e9-9858-7c8fab8c91b4.png)


Questions:
  * How is this possible
  * Should it be one entry per tab, or per _pane_?
  * We should definitely make this configurable, since not everyone (me included) might want this.

**Comment by fishnet37222** [comment]
Yes, I would like one entry per tab. You could make an option for one entry per pane, but that makes less sense to me. I also agree that it should be configurable.

**Comment by DHowett-MSFT** [comment]
This might need to be an ask on the Windows shell folks (@mdtauk: not the WinUI team, I know what you'd say) -- right now the DWM API that provides for tab previews only operates on `HWND`s, and we are _decidedly light on those_.

**Comment by DHowett-MSFT** [comment]
FWIW I think we have a dupe for this, I just can't find it right now.

**Comment by DHowett-MSFT** [comment]
I couldn't find a duplicate for this, and I decided that this was the master issue. Congrats, you're promoted to a full-fledged feature request tracker. :smile:

**Comment by greg904** [comment]
I found the duplicate! #687

**Comment by zadjii-msft** [comment]
Oh wow, look at that. Good investigative work @greg904! /dup #687
