### ISSUE TITLE
Terminal takes an unexpected dirt nap when backgroundImage contains environment variables

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#2922]
I literally can't believe we're not expanding environment variables.

**Comment by nzain** [comment]
@DHowett-MSFT I'm confused. #1468 (environment variables in icon) was fixed in version 0.3.x but the `backgroundImage` setting (and all other settings using a path) were not? I can't believe it :) 

Actually, I wanted to file a new issue because Version `0.6.2951.0` crashes when I use `"backgroundImage": "%userprofile%\\etc"`. Specifying the full path works fine. Now I found this issue, it has been closed only 5 days ago... I suppose, its not released, yet?

**Comment by zadjii-msft** [comment]
> this issue, it has been closed only 5 days ago... I suppose, its not released, yet?

That's correct - we should be releasing another update later this month that will contain this fix.
