### ISSUE TITLE
Feature Request: add 

### ISSUE THREAD

**Issue by aster94** [microsoft/terminal#2951]
# Description of the new feature/enhancement

Add ability to open new tabs that run one (or more) custom command before the opening

# Proposed technical implementation details (optional)

In the profile.json add add a new field, for example `commands`:

```
{
            "acrylicOpacity" : 0.5,
            "background" : "#012456",
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "powershell.exe",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "name" : "Conda",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : true,
            "commands": ["$env:Path += ";PathToConda""]
}
```
where `commands` are the commands that the terminal will execute before opening the new tab, in the example it will add the path to conda to the environmental path for the session

a dirty image of what i am talking about

![terminal](https://user-images.githubusercontent.com/21184718/65813366-a9d2ed80-e1d4-11e9-822f-1200adc100ed.png)

**Comment by fpqc** [comment]
I don't understand.  This is already possible using the commandline like this:
```
set "PATH=<PathToConda>;%PATH%" &  powershell.exe
```

**Comment by aabounegm** [comment]
@fpqc, might be for the simple example of setting and environment variable, but sometimes more complex commands are needed. For example, I want to have a profile for ROS where I run these commands once the tab opens:
```bash
source /opt/ros/melodic/setup.bash
export DISPLAY=:0
```
or even a script stored in the `startingDirectory` or anywhere else (because I don't want to run these commands for all Ubuntu shells, just ROS). I basically run ROS on WSL, so the `commandline` is just `wsl.exe -d Ubuntu-18.04`, and I couldn't find a way to run a command on WSL and keep it running.  This `commands` option would be really helpful.

**Comment by fpqc** [comment]
@aabounegm It can be done by setting it in your .bashrc or .zshrc if you need to set up something complicated. Bash and I think zsh support loading `--rcfile` which lets you load a different rcfile for a different environment.

**Comment by aabounegm** [comment]
@fpqc Thank you for the suggestion. I didn't think about running `bash` as the command passed to wsl 😅. It works well, except that I lost colors. I'll try to find out why.

**Comment by DHowett-MSFT** [comment]
Since Terminal can't really know--or hope to know--what shell you're using, we're not going to add an "initial commands" feature. It's far more extensible to do this in your shell profile (`~/.bashrc`, `Documents\PowerShell\profile.ps1`), and you gain the benefit of being able to check that into source control and use complicated logic in it. It's way, way better than "make the terminal pop some commands into the input stream on startup."

**Comment by aster94** [comment]
> I don't understand. Isn't this already possible using a commandline like this (ignoring the problems with escaping the quotation marks):
> 
> ```
> set "PATH=<PathToConda>;%PATH%" & powershell.exe
> ```

Not working:
`"commandline" : "set `"PATH=C:/Users/vincenzo/.platformio/penv/Scripts;%PATH%`" & powershell.exe",`

nor

`"commandline" : "set ""PATH=C:/Users/vincenzo/.platformio/penv/Scripts;%PATH%"" & powershell.exe",
`
nor

`"commandline" : "set \"PATH=C:/Users/vincenzo/.platformio/penv/Scripts;%PATH%\" & powershell.exe",`

**Comment by zadjii-msft** [comment]
maybe try 

```
            "commandline": "%comspec% /k cmd.exe /c \"set PATH=\"foo;%PATH%\" && powershell.exe\"",
```

which is going to get cmd to call cmd to process a commandline, and that commandline is going to set the `PATH` and launch powershell

**Comment by DHowett-MSFT** [comment]
Or, just have a powershell `profile.ps1` that sets up the way you'd like your shell to act?

**Comment by aster94** [comment]
@DHowett that would be indeed the best solution, but i need to have different path added and i would like to avoid to have all together.  I mean that sometimes i need a powershell windows that has the path to conda, other times one that has a path to a different command

I know i can do in `profile.ps1`

`$Env:Path += ";<path_1>;<path_2>"`

where `path_1` and `path_2` are the two target path but i would like to have them separated, and honestly i don't know how to load only one of these

**Comment by aster94** [comment]
I also found that this would works good:
`"commandline": "powershell.exe -noExit -Command \"& {$Env:Path += '\";C:/Users/vincenzo/Miniconda3/Scripts\"'}\"",`
