### ISSUE TITLE
Pasting multiple lines using "\" line break

### ISSUE THREAD

**Issue by andrp92** [microsoft/terminal#2962]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18990.1]
Windows Terminal version (if applicable): Version: 0.5.2681.0
```
# Steps to reproduce
Copy text with ```\``` line break. Example: 
```make build-essential checkinstall libssl-dev libbz2-dev libzip-dev \
libreadline-gplv2-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libffi-dev \
wget curl libldap2-dev zlib1g-dev lib32z1-dev uuid-dev
```

Paste it on powershell or wsl console. 

# Expected behavior
Terminal should recognize ```\``` as a line break and should execute the whole code as it does on powershell or wsl console directly. 
![image](https://user-images.githubusercontent.com/28060986/65827125-037efa80-e25d-11e9-9848-48ae9278e5a0.png)
![image](https://user-images.githubusercontent.com/28060986/65827130-0d086280-e25d-11e9-9ba7-ab47b79c36c7.png)

# Actual behavior
Terminal will not recognize ```\``` as a line break and will execute each line individually immediately causing a unexpected results. 
![image](https://user-images.githubusercontent.com/28060986/65827086-9cf9dc80-e25c-11e9-9b1c-fe77e99265a5.png)
![image](https://user-images.githubusercontent.com/28060986/65827097-bac74180-e25c-11e9-9340-bc858a4a2445.png)

**Comment by DHowett-MSFT** [comment]
Also, PowerShell doesn't use `\` for line continuations. You might need <kbd>`</kbd> when you're using powershell.

**Comment by andrp92** [comment]
Hi DHowett-MSFT, thanks for the comment. However I posted a picture showing that powershell does recognize the ‘’’\’’’ for line continuation. In the very first picture you can see it does. About the duplicate issue. Read the whole thing and couldn’t really get if that issue has anything to do with this behavior. I would like to point out that outside the terminal, the wsl console does what it should with these type of escenarios.

**Comment by DHowett-MSFT** [comment]
Curiously, this doesn't work for me even without Windows Terminal involved:

![image](https://user-images.githubusercontent.com/14316954/65932285-ec0d5200-e3c1-11e9-9619-29fa349dbea1.png)
(this applies to powershells 5.1, 6.2.2, and 7.0.0-preview)

I've called this a duplicate because in your WSL and powershell screenshots inside terminal, even when continuation is being engaged, it's being skipped because terminal is sending another (stray) line feed. You can see that by the presence of the hanging `>>`s (in bash, just `>`).
