### ISSUE TITLE
The bottoms of some lines are cut off for some unknown reason

### ISSUE THREAD

**Issue by verifix-repos** [microsoft/terminal#2968]
# Environment

```none
Windows build number: 10.0.18990.1
Windows Terminal version 0.5.2681.0
Windows Snip & Sketch
```

# Steps to reproduce

When I open a Terminal window, and start writing some commands, some lines doesn't show properly and are truncated. I think the problem might be my current Windows resolution, which I set on 125%

# Expected behavior

![image](https://user-images.githubusercontent.com/45128551/65830815-42d83600-e2b3-11e9-92d7-7a162d56deaa.png)
The most weird thing is that when taking a screenshot with the Windows Tool, everything appears normal on the screenshot like above.

# Actual behavior

Here's below what I really see on my screen (when taking a photo of it). For eg., first line is truncated.
![IMG_2013 232](https://user-images.githubusercontent.com/45128551/65831538-fb55a800-e2ba-11e9-94ab-53d6df5f4e1e.JPG)
*Sorry for the image Github doesn't want to turn it anyway but clicking on it shows the photo correctly :)*

**Comment by dschneiderch** [comment]
I also suffer from this and it's very annoying. this has been a persistent issue for me since testing the original release but i only now got around to reporting it (sorry!).  I think it mostly (only?) happens with WSL terminal. 
![image](https://user-images.githubusercontent.com/7461221/74670273-ab8a5700-515d-11ea-845e-64d263d0f2a8.png)
You can see that there is no prompt at the bottom and the scroll bar is all the way down. after reading this issue I realize now that I can ctrl+- to decrease the font size and then it shows up. but eventually you run out of usuable zoom out range.
in case it's important here are my windows display settings:
![image](https://user-images.githubusercontent.com/7461221/74670418-ff953b80-515d-11ea-9fdb-6c3247be5a37.png)

`clear` takes to back to the top of the screen. 

WT 0.9.433.0
Win10 Pro 1903

**Comment by verifix-repos** [comment]
Thanks for the tip. The issue doesn’t seems to be present on my system
anymore (since latest update I noticed), but I think it was because my
scale is at 125% and when at 100%, I hadn’t this problem on the Terminal.
But your problem seems a little bit different that mine, and more
embarrassing anyway (!)

**Comment by zadjii-msft** [comment]
Hey I must have missed this in my inbox 2 months ago. @verifix-repos Thanks for following-up that your problem went away! It's a shame that we don't know exactly when it was resolved, but there have been a _lot_ of renderer changes since 0.5 that have fixed a bunch of different bugs. This was probably just another artifact of one of the resolved ones.
