### ISSUE TITLE
Other applications open behind the Terminal window - (ConPTY window handle z-order shenanigans with `GetConsoleWindow`)

### ISSUE THREAD

**Issue by amithegde** [microsoft/terminal#2988]
# Description of the new feature/enhancement

When I open File explorer from terminal using command such as `start .` control should shift to explorer window but it remains in terminal.

# Proposed technical implementation details (optional)

when file explorer starts control should shift to explorer and any further keyboard interaction should be targeted to explorer window.
You can verify how `ConEmu` or `cmd` works to validate this.

**Comment by amithegde** [comment]
I noticed it does shift control some times. So I guess it's a bug? Some times control doesn't shift and some times it shifts?

**Comment by zadjii-msft** [comment]
This might not be possible. This repros for any conpty session. 

I (believe) that traditionally, `start` uses `GetConsoleWindow` to get the `HWND` of the console, to place explorer (or any application really) in the z-order above the conhost.exe window.

For something running in conpty however, the console doesn't actually have a window. The Terminal does, but the console doesn't. So there's no way for `start` to place something above the console window, since there _is no console window_.

**Comment by fpqc** [comment]
I can't imagine it would be hard for a motivated person to write a small Windows program that launches a program and then sets it at the top of the Z-order without comparing against the current window.

**Comment by amithegde** [comment]
> This might not be possible. This repros for any conpty session.
> 
> I (believe) that traditionally, `start` uses `GetConsoleWindow` to get the `HWND` of the console, to place explorer (or any application really) in the z-order above the conhost.exe window.
> 
> For something running in conpty however, the console doesn't actually have a window. The Terminal does, but the console doesn't. So there's no way for `start` to place something above the console window, since there _is no console window_.

I will be demotivated to use Terminal in that case since it doesn't behave consistently with existing tools like `cmd`😒

**Comment by dracan** [comment]
Not sure if this information is useful or not, but I had created a similar issue #3636 which got closed as a duplicate of this current issue. In my case, it was `git difftool` that was causing winmerge to not appear in the foreground. I've just discovered that whilst it happens when I do a normal `git difftool`, which triggers a `Launch 'winmerge' [Y/n]?` prompt - if instead I do `git difftool -y`, which suppresses that prompt - it works as expected.

**Comment by dracan** [comment]
Although, if more than one file has differences - the first launch of winmerge is in the foreground (when specifying the `-y` mentioned in my previous post), however any subsequent ones have the issue where the winmerge window is right at the back of all other windows.

I've also just noticed that the same issue happens from the vscode terminal. It doesn't happen when using the native Powershell terminal window though.

**Comment by zadjii-msft** [comment]
showerthought: what if we had a conpty api to set a HWND that the virtual console window should be on top of? Since conpty has to maintain a fake HWND to make the GetConsoleWindow API work correctly, but we think it's a bad idea to just use the terminal's HWND as that value, is there win32 trickery we could do to make that virtual HWND appear at the top of the z-order? It can't be hit tested or receive input, but maybe that would make the shell spawn new windows on top of the Terminal

**Comment by OMA2k** [comment]
Whatever the reason for Explorer windows not appearing on top, this should be fixed! I doesn't make sense having to hunt down a recently opened Window below several other windows, instead of having it open on top of everything as it's been the case for the past 25 years (since Windows 95!)

**Comment by OMA2k** [comment]
Please, take some minutes to look into this bug! This was reported back in September 2019, and now we're in 2021 still with this same really annoying bug. It drives me nuts!

**Comment by zadjii-msft** [comment]
@OMA2k This is not a bug that would take "a few minutes" to look into. The assumption here is that ShellExecute is using the console's HWND to find the z-order to place the new window. However, in conpty (which is what the Terminal uses), there is no HWND. And there's no good way to fake that value, without also just plumbing the Terminal's HWND all the way through to the conpty. However, if the conpty were running on another machine, all of a sudden the Terminal's HWND isn't a reliable value to use! So it's a complicated bug.

**Comment by cactusbash** [comment]
referencing #8679 (closed);

MFA authentication window, along with any Windows.MessageBox popup in the background. Has this been fixed or being worked on?

**Comment by campbellkerr** [comment]
Could the title of this issue be updated to be more "generic"? That way people like me might be able to find it easier instead of raising duplicate tickets?

**Comment by KalleOlaviNiemitalo** [comment]
> However, if the conpty were running on another machine, all of a sudden the Terminal's HWND isn't a reliable value to use! So it's a complicated bug.

What's the scenario in which the conpty is running on another machine but hosts GUI applications whose windows need to be correctly stacked?

I mean, you can have a conpty on another machine, if you run an SSH client in Windows Terminal and the SSH server on another machine then uses a conpty. But if you then start e.g. winver.exe over that connection, I wouldn't expect its window to be visible on either machine, so it hardly matters whether the window is active and where it is in the Z-order.

Well, I imagine you could have a visible window if you ran the SSH server interactively and not as a service. If that is an important scenario, the SSH server could create its own window and pass the HWND to the conpty. No need to send the HWND of Windows Terminal over the wire.

Did you have something else in mind?

**Comment by DHowett** [comment]
> there's no good way to fake that value, without also just plumbing the Terminal's HWND all the way through to the conpty

Oh boy, and Cygwin uses the _window handle of the console_ as a global identifier to disambiguate its fake `tty` devices. Without each console session being hosted in a unique window with a unique HWND, it will believe that all open windows are connected to the same `tty` device.

**Comment by DHowett** [comment]
OpenSSH (client) uses the window handle of the console to replace the title of the window, which won't work in multi-hosting scenarios like Terminal.

Vim for Windows uses the window handle to set/reset the icon, which ... well, will also not work properly in multi-hosting scenarios. It would also cause people to file bugs like "Terminal's icon changed to Vim when I ran Vim, and it sticks when I switch tabs" which _looks and smells and tastes_ like a Terminal bug but ... isn't.

The license we'd given app developers to futz with "our" window (while calling it "their" window) _really sucks._

**Comment by zadjii-msft** [comment]
> Cygwin uses the _window handle of the console_ as a global identifier to disambiguate its fake `tty` devices.

God I forgot about that bug. That one was just the worst, and agressively throws a wrench in the "just plumb WT's HWND through" solution.

I wonder if we could fake conpty's pseudo-HWND into being "always on top". That would give us the opposite problem. Instead of apps opening behind the Terminal sometimes, they'd open on top of all other apps _always_, but maybe that's not a bad idea?

**Comment by freMea** [comment]
For me, as explain in #10345, only cmdlet using GUI like `Show-Command Get-ChildItem` or `Get-ChildItem | Out-GridView` open behind the terminal. For now no issue while opening external app like `code $Profile` or `start .`

What apps are still causing problem if any ?

**Comment by arkrumbe** [comment]
Just want to +1 this. I'm hitting this with `Get-ChildItem | Out-GridView` and it's pretty disruptive to my workflow.

**Comment by zadjii-msft** [comment]
@arkrumbe If you'd like to "+1" this feature, the best way to do that is by hitting the 👍 button on this issue

![image](https://user-images.githubusercontent.com/18356694/96140789-ef3c8880-0ec5-11eb-82e0-30ce4977b9a7.png)

That way, you avoid unnecessarily pinging everyone following this thread. Thanks!

**Comment by zadjii-msft** [comment]
Guh. Neither passing `WS_EX_TOPMOST` to `CreateWindow` nor `SetWindowPos(... HWND_TOPMOST)` worked to hackily fix this. I wonder what exactly `Out-GridView` is doing to place the window. Maybe we can trick it _just right_...

**Comment by zadjii-msft** [comment]
Interesting. I tried the following, and even this didn't work:
* Open a terminal window.
* Grab it's HWND.
* Leave that terminal window open.
* Manually edit `GetConsoleWindowImpl` to return that HWND, and recompile the Terminal.
* Launch a dev build of the Terminal, and run `sleep 1 ; Get-ChildItem | Out-GridView`.
* quickly focus the original Terminal window, so it's at the top of the z-order.
* ❌ The window still appears _beneath_ the Terminal window!

This convoluted example is a proof-of-concept for just having `GetConsoleWindow` return the HWND of the hosting terminal. Even in that case, the spawned child process doesn't open above the Terminal. I'm a little shocked that the original scenario worked at all...

**Comment by IanMoroney** [comment]
@zadjii-msft , instead can the class name of window be grabbed and used to bring it to the foreground?
https://stackoverflow.com/questions/10898560/how-to-set-focus-to-another-window
(Pardon my ignorance in this area, i'm by no means experienced, just offering suggestions 👍 )

**Comment by KalleOlaviNiemitalo** [comment]
@IanMoroney, do you mean Windows Terminal should detect that a process opened a window, and bring that window to the foreground? The user can have e.g. cmd.exe running in WT and start powershell_ise.exe from there. WT could perhaps detect the new process via JOB_OBJECT_MSG_NEW_PROCESS, and detect the new window by hooking HSHELL_WINDOWCREATED or some WinEvent, but I don't know how WT could decide whether the new window belongs to the foreground or not. The "HwndWrapper" class names are not very useful for this, because those are generated ([source](https://github.com/dotnet/wpf/blob/v6.0.1/src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/HwndWrapper.cs#L94-L112)) by the Windows Presentation Foundation (WPF) library, which is not used by all applications.

@zadjii-msft, AllowSetForegroundWindow may be relevant to your July experiment.

**Comment by grossag** [comment]
This issue happens consistently for me if I am in Maximized mode. Unfortunately I do use Settings > Startup > Launch mode > Maximized so I regularly run into this issue. It reproduces in two ways:
1. Basic case: `start .` entered from terminal runs in the background (mentioned in earlier comments).
2. Other case (not mentioned in earlier comments):
   - Run: `echo https://www.google.com`
   - Click the hyperlink from that echo message.
   - My default browser (Google Chrome) launches in the background, when I would expect it to launch above the terminal app in the z-order.

This issue happens for me with both the GA version (1.11.3471.0) and the preview version (1.12.3472.0).

**Comment by zadjii-msft** [comment]
Internally, MSFT:37697992

**Comment by zadjii-msft** [comment]
Notes:
* we're the murderer in the `start` case. Technically, we own `cmd.exe`, and `start`, the `cmd` intrinsic, uses `GetConsoleWindow` to place the HWND. Ruh roh. That case seems like it'll be hard to fix, and likely that we'll definitely mess it up and have to revert the fix anyways.
* I should refer to `queue.cxx` and `xxxConsoleControl`, alongside `SetConsoleWindowOwner` in conhost. That hwnd _might_ be the one that the OS thinks is the owner for console applications, so we may be able to fudge the Terminal hwnd into that.

**Comment by zadjii-msft** [comment]
I have nowhere else for good notes, so sorry for the kinda random ping here folks:

As of b2575819b, this is starting to work a little better
![image](https://user-images.githubusercontent.com/18356694/154688034-602c4807-2f27-4ef6-9a11-6dd36ff18663.png)

Turns out there's piles of edge cases. Seemingly different things zorder in different ways, which is complicating this. Duping everything to this thread may not have been the most wise ;___;

**Comment by zadjii-msft** [comment]
Misc notes:

   
```c++
    gci.ProcessHandleList.ModifyConsoleProcessFocus(WI_IsFlagSet(gci.Flags, CONSOLE_HAS_FOCUS));

    ...

    // ModifyConsoleProcessFocus calls _ModifyProcessForegroundRights

    ...

void ConsoleProcessList::_ModifyProcessForegroundRights(const HANDLE hProcess, const bool fForeground) const
{
    LOG_IF_NTSTATUS_FAILED(ServiceLocator::LocateConsoleControl()->SetForeground(hProcess, fForeground));
}
```

> ### [FocusIn/FocusOut](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-FocusIn_FocusOut)
> FocusIn/FocusOut can be combined with any of the mouse events since it
> uses a different protocol.  When set, it causes xterm to send CSI I
> when the terminal gains focus, and CSI O  when it loses focus.




The easiest prototype may just be always passing `true`	here in conpty mode.

**Comment by zadjii-msft** [comment]
Alrighty. With #12515, #12526, #12799, #12899, #12900 all merged, I think this one's done. Everything I found linked to this thread seems to work in `main`. At this point, any new issues we discover in 1.14+ will be something else entirely, so we should give them new threads.

Thanks for the patience here folks!

**Comment by zaaj** [comment]
Terminal version 1.19 on Windows 11 here almost half way through 2024 and this is still a problem - Microsoft Graph login-prompt windows usually show up behind the Terminal window that launches them, I also have intermittent issues with Get-Credential in windows powershell 5.1 (pwsh 7 not having all the functionality I use on a day-to-day basis, I'm still feeling stuck on 5 - plus, writing my scripts for 5 makes them more sharable with my less-powershell-savvy colleagues, and is easier to run them on servers where we don't want to install any software not needed, including Pwsh 7).

From a technical programming standpoint, I can understand a ConPTY process not having a console window, but it is obviously being show IN a window, which DOES have a window handle.  With 5 PRs all trying to attempt to resolve this, it would appear to be a hard-to-fully-resolve issue.  I appreciate that work had been done towards resolving this issue, but it does not appear to be resolved yet.  Please keep working on this issue.
