### ISSUE TITLE
Nano doesn't recognize arrow keys

### ISSUE THREAD

**Issue by JCKodel** [microsoft/terminal#3000]
When using normal cmd.exe console, using https://github.com/bmatzelle/gow and then using `nano readme.txt`, all works normally.

In the new terminal, arrow keys displays `[ Unknown Command ]` (Backspace also not working sometimes and typing leave the cursor 1 letter behind, i.e.: typing teste gives me `test|e` (notice the cursor before the last `e`, not after, where it should be)

**Comment by DHowett-MSFT** [comment]
Whoa, this could actually be the same as #2397... I wonder if the gow runtime uses `ENABLE_VIRTUAL_TERMINAL_INPUT` or not?

**Comment by DHowett-MSFT** [comment]
Confirmed that this is a duplicate. Thanks!

**Comment by jeffrson** [comment]
Strange coincidence - I just wanted to file another bug with nano...

Well, I have a newer version of nano (4.3 from scoop.sh) that behaves a bit different in Windows Terminal. It seems like arrow keys, return and backspace do modify the internal cursor position in nano, because typing or deleting works - but the shown cursor position does only change when typing.
