### ISSUE TITLE
Drag and Drop of .Bat file to terminal

### ISSUE THREAD

**Issue by NikolaGrujic91** [microsoft/terminal#3014]
Drag and drop .bat file to Windows PowerShell/CMD and start execution of script. This will make running of .bat scripts much more convenient.

![DropScript](https://user-images.githubusercontent.com/17230877/65967191-8375b200-e461-11e9-8f21-68acaef84b98.gif)

**Comment by zadjii-msft** [comment]
This almost certainly won't be possible, since the Terminal doesn't really know anything about what application is running in it. If the application is cmd.exe, sure this is easy. Even powershell isn't that hard. But what about WSL? Or the Azure Cloud Shell Connector / ssh, which could be connected to _anything_, what do we do then?

Plus, with the auto-executing of these commands, that seems like it might be a bit of a security risk to me. `malicious-code.exe` could always just fake a drag-and-drop notification to Windows Terminal, and autorun its malicious batch file.

There's also #904 which will probably get you 90% of the way there.

**Comment by HBelusca** [comment]
Definitively #904 seems to be what is actually wanted there. This is also what happens in the regular console: dragging & dropping a file in a console/terminal just simulates keypresses corresponding to the letters of the full path to the file.

**Comment by JushBJJ** [comment]
Maybe instead of auto executing, a text editor like vim or notepad could be executed editing the file?

For instance in WSL:
-> User Drags file into terminal
-> Terminal receives file and checks what's the current selected **tab type**? (Example: Tab 3 [Selected] is currently running WSL).
-> Check's if any process is running that aren't background for example, matrix.sh is currently running
-> If it's a valid type and no processes are running, it will proceed to execute vim within the shell.

That's my brief idea on it. Though I can see multiple problems with it already so I'm pretty neutral.

**Comment by DHowett-MSFT** [comment]
This is a more dangerous way to suggest /dup #904 :smile:
Thanks!
