### ISSUE TITLE
Vertical joining of box drawing characters has gaps

### ISSUE THREAD

**Issue by tryptamic** [microsoft/terminal#3029]
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.356]
Windows Terminal version (if applicable): 0.5.2681.0

# Steps to reproduce

Run this litle command in the terminal using a cmd.exe tab to produce a little box:

```cmd
echo ┌┐ & echo └┘
```

# Expected behavior

The box should have perfectly joined lines on all sides. Living in a monospaced environment where the box drawing characters are used to draw trees, boxes and other stuf perfect line joining is expected

# Actual behavior

The lines of the box are not vertically joined

![image](https://user-images.githubusercontent.com/8502209/66046865-eaa96a00-e526-11e9-9bd9-90396b006770.png)

**Comment by zadjii-msft** [comment]
@tryptamic What font are you using?

What does this look like in conhost (launch cmd.exe directly) with the same font selected?

**Comment by egmontkob** [comment]
Some terminals, including VTE and Konsole draw the U+2500..257F (or even up to 259F) glyphs manually, rather than taking them from the font. This prevents such problems (and also avoids ugly looking antialiasing). I haven't seen any monospace font that would just look perfect on its own.

Interestingly, independently from each other, both VTE and Konsole came up with the idea of defining the look of most of these codepoints as a 5x5 matrix (where how the given 5x5 grid is stretched to the character cell is not necessarily the same for thick lines vs. double lines).

VTE [link1](https://gitlab.gnome.org/GNOME/vte/blob/0.58.0/src/box_drawing.txt), [link2](https://gitlab.gnome.org/GNOME/vte/blob/0.58.0/src/vtedraw.cc#L1180)

**Comment by DHowett-MSFT** [comment]
I like the idea of having Terminal draw these itself; we've chatted about that internally and thought it was pretty clever.

This is also related to #455.

**Comment by tryptamic** [comment]
> @tryptamic What font are you using?
> 
> What does this look like in conhost (launch cmd.exe directly) with the same font selected?

Consolas but with Cascadia Code it gets even worse because horizontal joining is then broken as well and vertical gaps got even larger as you can see in the screenshot

![image](https://user-images.githubusercontent.com/8502209/66063946-b8a70080-e544-11e9-924a-9deb4fc361f6.png)

**Comment by zadjii-msft** [comment]
@tryptamic The legacy console and the Terminal use different renderers to display text. The Terminal's renderer is far more performant, but there are still many edge cases we need to work out, and this is one of them. 

I think in general this falls under the umbrella of /dup #455 so I'm gonna close as a dupe.
