### ISSUE TITLE
Opening multiple tabs from a single profile on start, with the default terminal, and on individual profiles.

### ISSUE THREAD

**Issue by danielkeery** [microsoft/terminal#3037]
# Description of the new feature/enhancement

This FR would solve having to manually setup my workspace on every new launch. I always start with the same 3 tabs, it would be nice to launch these all in the default.

"globals": {
    "defaultProfile": ["GUID1", "GUID2", "MULTI-PROFILE-GUID1", ...]
}
...
"profiles": [
    {
        "guid": "multi-profile guid",
        "launchProfiles": ["other profile guid1", "other profile guid 2", ...] 
    }
]
# Proposed technical implementation details (optional)

Change existing launch code into a for loop and the defaultProfile backing as a array.
Either new profile type could be introduced or the detection of launchProfiles for each profile configuration would signal needing to launch other profiles. Recursive?
Support the launching of multiple profiles in any launch action. Should be self explanitory.

**Comment by zadjii-msft** [comment]
So I suppose this was discussed before in #1043, though there doesn't seem like there's a unique issue for it, so congratulations, this is now the thread :)

There are probably a bunch of things we'd want to consider as part of a comprehensive solution here.
* What if someone wants to open the terminal with multiple tabs (what you've already discussed above)
* What about with multiple panes, in various different split configurations? How would we set that?
* Perhaps the user wants to auto-launch multiple _windows_? In different locations, etc.
* Obviously, any solution for the above three should not preclude any of the others. Users would want to be able to specify multiple windows, each with their own tabs, and with tabs that might have any number of panes.
* Would we want this multi-launch behavior to only happen on _first_ launch, or _every_ Terminal launch?
* With the nesting behavior you have above, what if someone had a recursive loop, where one profile A specified launching profile B, and B specified launching A? That would theoretically cause an infinite loop - do we allow that?
* (I'm sure there's more I'm missing here)


This is certainly a problem that's feasible from an engineering standpoint, but due to the complexity of specifying these scenarios, I'd want a [spec](https://github.com/microsoft/terminal/blob/master/doc/specs/spec-template.md) written first to try and think through the edge cases before we start working on the code.

**Comment by DHowett-MSFT** [comment]
I'm actually gonna merge this one back into /dup #756, since I found the original "multiple tabs on startup (and more)" issue.
