### ISSUE TITLE
Don't round the tabs

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#3084]
I hate the rounded tab look. Doesn't mesh well with the Windows 10 UI.

**Comment by mdtauk** [comment]
The Windows 10 UI will be getting rounded controls and dialogs

**Comment by musm** [comment]
Source?

**Comment by mdtauk** [comment]
> Source?

The Win UI controls have been updated to have rounded corners, and this is under the guidance of the Fluent / Windows Design Team

**Comment by musm** [comment]
Interesting. Personally it clashes with thr square UI box the terminal is contained in. But the UI still has a lot of bugs.

**Comment by mdtauk** [comment]
Windows 10 20H1 is where any Shell changes to window shapes etc will come, if they come.

Then there is Windows 10X which has an entirely new shell, as will the new XBoxes

**Comment by musm** [comment]
thanks for the info

**Comment by DHowett-MSFT** [comment]
Seems addressed. Sorry, we're not changing the design of Windows.

**Comment by musm** [comment]
VS Code doesn't round the tab bars, and I am still not convinced this governed by updates to the Win UI control changes  since I haven't seen any other software UI with tabs that have them as rounded as they are in the new terminal

![image](https://user-images.githubusercontent.com/4319522/68319061-b415c080-008b-11ea-998e-37d6c2488074.png)

**Comment by zadjii-msft** [comment]
[microsoft/microsoft-ui-xaml/v2.2.190917002](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.2.190917002) and [https://github.com/microsoft/microsoft-ui-xaml/v2.3.191007001-prerelease](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.3.191007001-prerelease) (the later of which we're using) both include multiple patches to round the corners for various UI elements. The long-term roadmap for Windows XAML UI elements is a shift towards more rounded corners. Just because other software hasn't yet ingested the absolutely latest bits doesn't mean that it's not a change that's coming.

@mdtauk might be able to pull up a WinUI roadmap, though I don't know where that lives.

**Comment by musm** [comment]
Ok thank you very much. I suppose VS Code will incorporate some of these UI XAML elements in the future.

**Comment by mdtauk** [comment]
The new chromium Edge tabs are rounded, and the WinUI team is trying to converge on that design
