### ISSUE TITLE
Font Ligatures Can Connect With Current Path

### ISSUE THREAD

**Issue by chiefklondog** [microsoft/terminal#3224]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.356]  
Windows Terminal version (if applicable): Version: 0.5.2762.0
```

# Steps to reproduce

Switch to a font that contains ligatures that effect the '>' character. (In my case I used Fira Code)
Type a character such as '=' on a fresh line and it will combine in with the text that you are normally unable to edit
![image](https://user-images.githubusercontent.com/30984107/66928192-dca71f00-efe5-11e9-8c00-00313dc70580.png)

# Expected behavior
Not sure how impactful this really is but my expectation would be that the user would be unable to effect the current location text since they are unable to edit it as normal text

# Actual behavior
The user typed character is being combined into the location text modifying the normally un-editable text

**Comment by DHowett-MSFT** [comment]
/dup #757 but in the general case, since a terminal is just a grid of characters, we _can't know not to ligate two things_.

In general, user input _and_ shell output are actually both generated by the shell (powershell reads a key, prints it to the screen). Because of that, we can't actually ever know whether a given piece of data was user-generated or shell-generated.
