### ISSUE TITLE
Permissions needed to run Terminal

### ISSUE THREAD

**Issue by PayasR** [microsoft/terminal#3230]
The Terminal app installed via Microsoft Store currently needs the following permissions (ref: https://support.microsoft.com/en-us/help/10557/windows-10-app-permissions):

**Access all your files, peripheral devices, apps, programs, and registry:** The app has the ability to read or write to all your files (including documents, pictures, and music) and registry settings, which allows the app to make changes to your computer and settings. It can use any peripheral devices that are either attached or part of your device (such as cameras, microphones, or printers) without notifying you. It also has access to your location, and can use platform features, such as  location history, app diagnostics, and more, which are denied to most Store apps. You can't control most of the permissions for this app in Settings > Privacy. Note that while the app has the ability to access these resources, it might not actually do so. For more info about what the app collects or uses, review the privacy policy of the developer.

Could the developers please either add a privacy policy clarifying what data does the application collect or what peripheral devices does it use and when? If no such data is collected, shouldn't the application have fewer permissions?

**Comment by DHowett-MSFT** [comment]
Assigned @bitcrazed for followup. There's a story here, but we'll get to it after triage. :smile:
Thanks!

**Comment by bitcrazed** [comment]
Thanks for filing Payas - much easier to provide a detailed response here than on Twitter :)

There are several reasons why Terminal is classified as a "full-trust" app and thus, why its permissions described in the Store look so ... expansive:

## 1: Terminal needs the ability to run elevated

Tools and scripts that need to be elevated with admin rights need to be connected to a Terminal/Console instance running at the same Integrity Level (IL) - High-IL in the case of elevated processes.

Currently, modern UWP managed/packaged applications cannot run elevated. We are working with the app platform team to support this requirement in a future OS release.

## 2: Terminal needs the ability to launch arbitrary command-line binaries

In order for the Terminal to be useful, it needs to connect to and run arbitrary command-line binaries that _you_ want to run, like `Cmd.exe`, `PowerShell.exe`, `WSL.exe`, `ping.exe`, etc.

UWP apps are not allowed to launch and connect to arbitrary binaries. Again, we are working with the app platform team to support this requirement in a future OS release.

## 3: Terminal needs the ability to access files in arbitrary locations

Terminal needs to be able to access files stored in locations you specify on your machine, some of which are currently unreachable by managed UWP apps.

## So ...

Due to these issues, it's clear why we had to build Terminal as a Win32 app for now. And thus, because the Terminal is a full-trust Win32 app (which don't offer/support granular activity-based permissions like modern apps do), the Store's permissions description is correspondingly expansive.

Once the app platform can support our requirements, and allow us to declare our specific needs (e.g. "Run Elevated" or "Launch External Processes"), we'll be able to publish the Terminal as a more restricted, and explicit modern UWP app.

However, now that you can see the source code that implements both the Terminal, and the Console, you'll see that we do not access your camera, microphone, scan your files, etc.

Let me know if you have any further questions.

**Comment by PayasR** [comment]
This is great, thank you so much Rich! It's good to have all of this documented somewhere. :)
@DHowett-MSFT story time?

**Comment by DHowett-MSFT** [comment]
@PayasR Sure! I'll be brief, since it's late here, but here's the gist.

Our application is a full-trust application masquerading as a UWP, masquerading as a full-trust application. There's a bunch of different layers here -- we built the core components of the Terminal as though we were building a universal application to run inside the sandbox, but, as Rich alluded to, the sandbox isn't quite the right fit for something that needs the ability to spawn other applications...

We've been pushing a dependency on the team who owns the application infrastructure to make sure that we don't need this "full trust" moniker. It's been an interesting discussion to have here on the inside, because an application that can spawn other applications that can administer the system is only a single shade _away_ from being a full trust application. Further, it's been _fun_ (and by fun I mean, broadly speaking, frustrating) to dig through the windows application security model in search of a way to do what we need to do. :smile:
