### ISSUE TITLE
Terminal doesn't survive PC hibernation 

### ISSUE THREAD

**Issue by SimonWellborne** [microsoft/terminal#3276]
# Environment
Microsoft Windows [Version 10.0.18990.1]
Windows Terminal (Preview) 0.5.2762.0

# Steps to reproduce
1. Open Windows Terminal
2. Place PC into Hibernation
3. Awake PC from Hibernation

# Expected behavior
Expect Windows Terminal to remain open and maintain the state of the tabs in use prior to hibernation.

# Actual behavior
I utilise between 1-2 Windows Terminal windows, each containing multiple tabs through the course of a normal day.  I place the PC into hibernation, resuming either a few hours later or the next day and find all Windows Terminal windows closed.   

All other applications maintain their state across the hibernation process.

**Comment by HBelusca** [comment]
All these tabs are "connected" to console applications opened on the local computer? (i.e. no remote ssh sessions are running inside them?)

**Comment by SimonWellborne** [comment]
> All these tabs are "connected" to console applications opened on the local computer? (i.e. no remote ssh sessions are running inside them?)

Forgot to mention that I predominantly use WSL (Ubuntu) tabs.  When I open a new WSL tab its default directory is /mnt/c/Users/simon

I've tried leaving the WSL tab at either this directory, or in ~, but no difference.

**Comment by SimonWellborne** [comment]
> Hi there!
> 
> Can you please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end?
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/18221333/62478757-b69d0d00-b760-11e9-9626-1fa33c91e7c5.png) ![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

https://aka.ms/AA6e8dh

**Comment by Alonski** [comment]
Chiming in that I see similar behavior.
I use Pwsh in Terminal. After hibernation Terminal is closed.
However, any processes that were running in Powershell stay running although I can't view them.
I end up having to kill the processes with Task Manager and respawn them.

Is there any info that I can provide to help?

**Comment by zadjii-msft** [comment]
Hey it's been like, 3 years since this was filed - is this still happening? It's possible that the store just took this opportunity to update the Terminal (and also just closed it), but if it happens on _every_ hibernate, then that's not it. 

If it is still happening, can you try following the steps in [this post](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm) to set up automatic crash dumps? (For more info, see [this link](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)) If that works, then you should be able to automatically get a `.dmp` of the terminal when it crashes. Then, can you zip that dump up and send it to us, so we can investigate/? Thanks!
