### ISSUE TITLE
VSCode's integrated terminal can not support bold character while enabling ConPTY.

### ISSUE THREAD

**Issue by Suyun514** [microsoft/terminal#3297]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable):

Any other software? Viaual Studio Code 1.40.0-insider
```

# Steps to reproduce

0. Set `"terminal.integrated.windowsEnableConpty": true`.
1. Install Cygwin.
2. Set the default shell as bash.exe(for Cygwin) in Viaual Studio Code, and the args as `--login`.
3. Run `ls --color=auto`.

# Expected behavior

The executable files and the folders' names are displayed in bold. (You can check the bold character in MinTTY with the option `Show bold ad font`.)

# Actual behavior

There is nothing displayed in bold.

**Comment by Tyriar** [comment]
You should try repro with Windows Terminal and give the version if you haven't yet

**Comment by DHowett-MSFT** [comment]
![image](https://user-images.githubusercontent.com/14316954/67429870-e60c2a80-f595-11e9-9c13-7a7c3513d3e1.png)

This is in VS Code. I'm 99% sure this is a Cygwin issue, because **they have their own VT parser, and they probably don't think we can handle VT.**

More in https://github.com/microsoft/terminal/issues/2837#issuecomment-533830745.
