### ISSUE TITLE
Drag & Drop from File Explorer produces incorrect file paths with WSL

### ISSUE THREAD

**Issue by acesnik** [microsoft/terminal#331]
Dragging & dropping a file from Windows File Explorer into a Bash window produces the path formatted for Windows instead of Ubuntu.

Dragging the Desktop folder into a Bash window should produce the text /mnt/c/Users/acesnik/Desktop. Instead, it produces C:\Users\acesnik\Desktop.

Your Windows build number
Edition: Windows 10 Pro
Version: 1607
OS Build: 14393.576

See also https://github.com/Microsoft/WSL/issues/1501

**Comment by zadjii-msft** [comment]
There's not really a way for us as the console/terminal to be able to know what format the shell running attached to us wants the path in. I wouldn't even begin to know how to begin implementing this.

I've filed MSFT:19977636 to track this request, but I don't think it's going to go anywhere any time soon, especially without any plan for how it'd be possible.

**Comment by therealkenc** [comment]
> I wouldn't even begin to know how to begin implementing this.

Thanks Mike. Since I'm the one who rudely punted here, I should probably speak up. That wasn't the answer I expected, but I _understand_ the answer. WSL (on its end of the pty) has no business knowing what you are doing when a file is dropped onto your window. On your end of the pty, you are saying (point blank): hey I have no idea how WSL wants that path string to look. I don't even know it is WSL. 

Impasse.

The popular competing terminal emulator implements this by throwing out separation of concerns. The emulator knows the context of the thing that launched it (historically that meant Cygwin). You can do the same. So for `wsl.exe` context is the string might be "wsldistro=Ubuntu1804" and then way up in your drop handler you do a bunch of dirty work (which your terminal emulator really has no business knowing) to convert the path. For `poweshell.exe` the context string would be, well, nothing. The details of that dirty work doesn't matter for our purposes right now. You probably don't like that answer, but at least this is a _different_ answer than "there's not any way for us ...to know".

The other way to do this is inversion of control. You provide a hook, which `wsl.exe` (or `powershell.exe` or `cmd.exe`) can consume. How you'd provide that inter-process hook is up to you, but at least the signature is conceptually bog simple. Method OnPathDrop takes a string and returns a string. Framing the problem this way means you don't have to know the dirty details, ever. Not your problem. The scope of work is providing said hook.

Academic, I know. Beats empty proposition.

**Comment by HBelusca** [comment]
> There's not really a way for us as the console/terminal to be able to know what format the shell running attached to us wants the path in. I wouldn't even begin to know how to begin implementing this.

The problem is that the paste is seen by conhost, that will then emulate keypresses to be sent to the underlying console application. I would suppose that in the WSL it's either wsl.exe or bash.exe (??) and they would have to detect that the thing you are entering at this precise moment is a file path (rather than "random" keypresses), and then do a path conversion "à la Cygwin".

The problem here of course is that detection.

Unless, it is possible, from within conhost, to "detect" whether the console application that has the focus (is the main) in the given console, will expect *nix-type file paths instead of win32-type file paths.
If this was possible, then a win32 to *nix file path conversion would have to take place in conhost.exe.

An alternative way (that is inspired from Wolfram Mathematica when you paste file paths in a string), would be to recognize that the file path has a certain form, namely "driver_letter:\path\to\file" . If such recognition can be performed, then one can then convert this type of string to a *nix-formatted file path.
Since that solution would be handled by the console application itself, the console app could display some kind of "popup" character-window asking whether or not to perform the file-path conversion.

**Comment by stevemk14ebr** [comment]
Hi, can this please be implemented? It's pretty trivial as far as i can tell, the parent process for conhost is wsl.exe so all it needs to do is check the module name of it's parent process. This can be done a number of ways, the easiest of which is probably just enumerating the processing and checking pids. If one is found get the window name and check for 'wsl.exe': https://gist.github.com/mattn/253013/d47b90159cf8ffa4d92448614b748aa1d235ebe4 (additionally should probably verify the parent start time is before child start time).

![image](https://user-images.githubusercontent.com/6619205/85865491-f5cab700-b793-11ea-81fd-a185bd9d089e.png)

**Comment by zadjii-msft** [comment]
Ah but what if you're running `cmd.exe` within WSL 🤔 

>  the parent process for conhost is wsl.exe

Well, that's certainly not what I'd expect actually. That's curious that there's an extra console process hanging around when WSL is already attached to a console. In your screenshot, the console server for `wsl.exe` is actually OpenConsole.exe, presumably 18360.

**Comment by stevemk14ebr** [comment]
![image](https://user-images.githubusercontent.com/6619205/85869101-3c6ee000-b799-11ea-8e0b-f50bc3735127.png)

wslhost.exe is always the parent of conhost for wsl systems afaik. The wsl.exe is parent of cmd.exe when spawned from within a wsl2 environment. Grab process hacker2 and try for yourself

**Comment by Matsuyanagi** [comment]
Has no effect on WSL Ubuntu 22.04.1 LTS.

Ubuntu 22.04.1 LTS installed from the Microsoft Store is configured in this way, so it is not determined correctly.
```
	"source": "CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc"
```

`ManglePathsForWsl()` determines like this.
It has to be a more efficient way of judging or set manually.
/terminal/src/cascadia/TerminalControl/ControlInteractivity.cpp:676
```
    bool ControlInteractivity::ManglePathsForWsl()
    {
        return _core->Settings().ProfileSource() == L"Windows.Terminal.Wsl";
    }
```

**Comment by DHowett** [comment]
FWIW, This is an excellent example of why I always thought that pushing the _source_ down into the control layer to make the decision about drag/drop was the wrong thing to do. Hmm.

**Comment by NNois** [comment]
> There's not really a way for us as the console/terminal to be able to know what format the shell running attached to us wants the path in. I wouldn't even begin to know how to begin implementing this.
> 
> I've filed [MSFT:19977636](https://task.ms/19977636) to track this request, but I don't think it's going to go anywhere any time soon, especially without any plan for how it'd be possible.

that's not true git bash for windows does that correctly
