### ISSUE TITLE
`SCREEN_INFORMATION::LineChar` should maybe just be an enum

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3366]
Right now, in `SCREEN_INFORMATION`, we have an array of chars, that we fill with the appropriate line-drawing chars:

https://github.com/microsoft/terminal/blob/444de5b166d800b17c90510cde8664aefffcb236/src/host/screenInfo.hpp#L171-L177

and we fill that array _on construction of a `SCREEN_INFORMATION`_
https://github.com/microsoft/terminal/blob/444de5b166d800b17c90510cde8664aefffcb236/src/host/screenInfo.cpp#L64-L70

This could/should probably be replaced with just an `enum Foo : wchar_t` with each of the values in it. Unless there's a perf reason we're doing it this way, in which case, we should certainly leave a note.

**Comment by j4james** [comment]
Do you really even need the enum? As far as I can see, this is only used for drawing the borders of the popup window, and I don't see why you couldn't just use the existing unicode constants there directly.

For example, instead of this:

https://github.com/microsoft/terminal/blob/9b92986b49bed8cc41fde4d6ef080921c41e6d9e/src/host/popup.cpp#L95-L96

why not just do this?

```
// draw upper left corner
_screenInfo.Write(OutputCellIterator(UNICODE_BOX_DRAW_LIGHT_DOWN_AND_RIGHT, 1), WriteCoord);
```
Is that really any less readable?

**Comment by zadjii-msft** [comment]
Honestly it's not (less readable). I agree, the enum isn't even really necessary. That's what I get for trying to file an issue at 7am 😜
