### ISSUE TITLE
"Close all tabs?" dialog should highlight the "default" option

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3379]
refer to screenshot:

![image](https://user-images.githubusercontent.com/18356694/67896977-7238c780-fb2b-11e9-8899-f232d649e234.png)

Pressing enter here _closes the window_, because that's the focused/default button on this dialog. However, there's no way of knowing which is the selected button right now. We should either use the accent color with the button, or manually display the focus rect (is that even possible)?

Also for discussion: Should "close" be the default option here?

**Comment by DHowett-MSFT** [comment]
Gut feeling: cancel should be the default option.

**Comment by carlos-zamora** [comment]
Classic Edge:
![image](https://user-images.githubusercontent.com/11050425/68063455-5c173c80-fcce-11e9-9d1a-ba5c9e3c0d38.png)

Pressing Enter does trigger "Close all". Surprisingly, they don't make it clear that that's the default button here. We definitely should though.

On a separate note, consider adding that checkbox? (that should definitely be it's own issue though)

**Comment by mdtauk** [comment]
You could use the Accented Button style for the default option

**Comment by jantari** [comment]
My opinion is that you should use the focus rectangle.

When you only have two buttons and they are different colors it is still not clear which one is active.

**Comment by cinnamon-msft** [comment]
Along with this issue, the styling should be fixed as well to match the other dialog boxes.
Mockup proposal:
![image](https://user-images.githubusercontent.com/48369326/72943040-df728800-3d29-11ea-8f49-ad4bae3f105b.png)

In terms of what should be default, I'd argue if we have the checkbox for "don't show this again", it should be Cancel. Otherwise, Close All Tabs should be default.
