### ISSUE TITLE
Text font looks little bold in comparison to conhost

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#3388]
From @srv-code in #3386:

> Text font looks little bold (a difference noticed in comparison to cmd font even after keeping the same font properties).

@srv-code Could you maybe see some screenshots of the difference you're seeing? I'm sure there are going to be slight differences between GDI (the conhost renderer) and DX (the Terminal renderer), but they shouldn't be that significant.

Maybe this has to do with how we're antialiasing? #1298 has some discussion there.

**Comment by srv-code** [comment]
> From @srv-code in #3386:
> 
> > Text font looks little bold (a difference noticed in comparison to cmd font even after keeping the same font properties).
> 
> @srv-code Could you maybe see some screenshots of the difference you're seeing? I'm sure there are going to be slight differences between GDI (the conhost renderer) and DX (the Terminal renderer), but they shouldn't be that significant.
> 
> Maybe this has to do with how we're antialiasing? #1298 has some discussion there.

Yeah. I also think its because of the use of different renderers. The difference is not that significant though. Just that the text in conhost looked much lighter and therefore better if you ask me. Attached are the screenshots from my system (I don't know if you can see the differences in this picture).
![diff - fonts of conhost   wt](https://user-images.githubusercontent.com/32870803/68183332-228e4c00-ffc2-11e9-8c97-68074884084d.jpg)

**Comment by zadjii-msft** [comment]
Looking at that screenshot, it does look like the difference you're referring to does have to do with the way we're anti-aliasing the text. @miniksa can correct me if I'm wrong here. I know we had a lot of discussion about how we anti-alias fonts prior to announcement. I think once we add #1298, you should be able to configure the terminal to at least be closer.

Thanks!

/dup #1298

**Comment by miniksa** [comment]
Yes, this is just the visual difference between GDI text and DirectWrite text. We're planning on adding more knobs to configure it as @zadjii-msft said.
