### ISSUE TITLE
Tab switching by "ctl + arrows"

### ISSUE THREAD

**Issue by Malnasser** [microsoft/terminal#3392]
I would like to switch between tabs by keyboard shortcuts with "Ctrl + ➡" to switch to tabs in the right and "Ctrl + ⬅" to switch to tabs in the left.

I would like to develop it by myself if this is possible" 😁

**Comment by zadjii-msft** [comment]
I'm pretty sure this is already possible, if you add the following keybindings:

```json
        { "command": "nextTab", "keys": ["ctrl+right"] },
        { "command": "prevTab", "keys": ["ctrl+left"] },
```

**Comment by Malnasser** [comment]
@zadjii-msft can we have this by default with the right hand Ctrl key?

**Comment by zadjii-msft** [comment]
I'm not totally sure we can differentiate between the two, though @lhecker can correct me if I'm wrong.

Even if we can, I'd be inclined to _not_ add this as a default, simply because some shell applications (like powershell, cmd) already use <kbd>ctrl+arrow</kbd> as a "move-by-word" shortcut, and I'm fairly certain they _don't_ differentiate between left vs right control. Additionally, we already have <kbd>ctrl+tab</kbd>/<kbd>ctrl+shift+tab</kbd> bound to these actions.

**Comment by Malnasser** [comment]
I see! I didn't know about ctrl+tab/ctrl+shift+tab!
In this case, I would agree with you.

**Comment by lhecker** [comment]
@zadjii-msft We can differentiate between them. It's just that the code related to settings [doesn't support this yet](https://github.com/microsoft/terminal/blob/b726a3d05d35928becc8313f6ac5536c9f503645/src/cascadia/TerminalSettings/KeyChord.idl#L20).
