### ISSUE TITLE
support wdq colors in microsoft terminal

### ISSUE THREAD

**Issue by VladimirAlexiev** [microsoft/terminal#3432]
# Environment

Microsoft Windows Version 10.0.18362.418, whose `cmd` includes the new `Terminal` tab/options (eg see https://devblogs.microsoft.com/commandline/new-experimental-console-features/)

Any other software?
- Clink v0.4.9 [git:2fd2c2] Copyright (c) 2012-2016 Martin Ridgers                                                        
  http://mridgers.github.io/clink
- https://github.com/nichtich/wdq 0.4.4 (/cygdrive/c/Strawberry/perl/site/bin/wdq)
- perl v5.28.0
- cygwin

# Steps to reproduce

```
wdq help
```

# Expected behavior

Should show modestly colored output:

![image](https://user-images.githubusercontent.com/536250/68113597-d5947200-fefc-11e9-9c72-de143016d5df.png)

# Actual behavior

Shows escape sequences:

```
wdq [ [0;34mMODE[0m ] [ [0;34mOPTIONS[0m ] [ [0;34mREQUEST[0m | [0;34m< REQUEST_FILE[0m ]
[1;39mUsage:[0m
  Access Wikidata Query Service [0;33m<https://query.wikidata.org/>[0m via command                                      
  line to perform SPARQL queries ([0;32m"query"[0m mode), lookup entities ([0;32m"lookup"[0m),
  or search items and properties ([0;32m"search"[0m or [0;32m"psearch"[0m):                                                                                                                                                                     ...
  See the manual for details or get help via [0;32m"wdq help"[0m:                  
```

# Through file

If I save the output to a file (`-C` explicitly enables color mode) then `type` or `cat` the file to the microsoft terminal, the color shows ok:

```
wdq -C help > wdq-help.txt 
type wdq-help.txt 
cat wdq-help.txt 
```

The saved file: [wdq-help.txt](https://github.com/microsoft/terminal/files/3803499/wdq-help.txt)

So I thought the problem may be related to some startup magic? The file starts like this:

```
>head /cygdrive/c/Strawberry/perl/site/bin/wdq
#!/usr/bin/env perl
use v5.14;
```

Starting perl explicitly makes no difference:

```
perl -S wdq help
```

**Comment by zadjii-msft** [comment]
So admittedly, I don't know a ton about how exactly clink/cygwin works. What I can say is that in order for escape sequences to work in the Windows Console (conhost.exe, the vintage terminal on Windows), applications need to explicitly call [`SetConsoleMode`](https://docs.microsoft.com/en-us/windows/console/setconsolemode) with `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. So perhaps something in the stack here isn't calling that? @VladimirAlexiev Are there any other apps in your setup that _should_ be displaying colors but aren't?

For the record, installing `wdq` in WSL does correctly display the colors:
![image](https://user-images.githubusercontent.com/18356694/68127373-6195a200-fedb-11e9-8626-22ab39da1386.png)


This is because WSL itself is setting the console into the correct mode for all child processes it launches.

**Comment by VladimirAlexiev** [comment]
@zadjii-msft thanks for looking into that! What is WSL and how do I install wdq into it?

**Comment by zadjii-msft** [comment]
WSL is the Windows Subsystem for Linux.

You can find instructions on how to install it [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

Once you have your distro of choice, you can install `wdq` however you normally would on linux. IIRC [this was the script I used](https://github.com/nichtich/wdq#prebuild-packages):

```sh
wget https://github.com/nichtich/wdq/raw/master/script/wdq
chmod +x wdq
```
