### ISSUE TITLE
Feature Request - Background Flip

### ISSUE THREAD

**Issue by bobfrankly** [microsoft/terminal#3452]
# Description of the new feature/enhancement
Some animated gifs have motion on a specific side of the image. When the motion is focused to the right edge of the screen, this tends to work well, but when the motion is on the left side, it may be too much. An option to flip the background would add flexibility in such situations.
**Examples:**
- [Would Flip](http://giphygifs.s3.amazonaws.com/media/6Q2KA5ly49368/giphy.gif)
- [Wouldn't Flip](https://media.giphy.com/media/69qrEqqjd06TZZY89S/giphy.gif)

# Proposed technical implementation details (optional)
Add to the profiles.json spec: backgroundImageFlip with options for horizontal and vertical, and the functional code that would implement this feature.

# Obvious flattery
Loving the product so far! -Bob

**Comment by DHowett-MSFT** [comment]
> Flattery

thanks!

> (flip)

I'm concerned about the overhead of having the terminal (or the XAML image control, really) flip the image every time it's displayed when you could save your computer time and processing power by pre-flipping the gif you'd like to use :smile:

We had a discussion like this in #2370, but never reached a consensus.

**Comment by bobfrankly** [comment]
> > Flattery
> 
> thanks!
> 
> > (flip)
> 
> I'm concerned about the overhead of having the terminal (or the XAML image control, really) flip the image every time it's displayed when you could save your computer time and processing power by pre-flipping the gif you'd like to use 😄
> 
> We had a discussion like this in #2370, but never reached a consensus.

Now I'm just a powershell junkie, so I'm admittedly not familiar with the details, but would the overhead for a flip that considerable compared to the automatic scaling and alignment that's already included?

I get the mentality behind 'modify and save locally', but the idea of 'copy and paste these few lines and my config is over here now' is a strong contender as well 😄

**Comment by egmontkob** [comment]
The two cents of someone who doesn't even use this software (that is, me):

Adding such a feature opens up a can of worms for an endless number of similar tiny ones: rotating by 90° or arbitrary angle, applying arbitrary matrix transformation, blurring, various kinds of color corrections and so on and so forth.

The only consistent and non-arbitrary place to draw a line is to include only the ones absolutely necessary, the ones which cannot be done externally because depend on the current size of the terminal (that is: scaling, stretching or cropping, aligning, tiling).

**Comment by DHowett-MSFT** [comment]
I think that's a really good assessment. Thanks @egmontkob! I'm going to have to veto this one, but I'm still open to a discussion about the merits of various background image options. 😸
