### ISSUE TITLE
Maintain scrollbar position during resize

### ISSUE THREAD

**Issue by egmontkob** [microsoft/terminal#3494]
# Description of the new feature/enhancement

Currently, if you drag back the scrollbar and then resize the window, the viewport jumps back to the "regular" position (the end of the data buffer, and the bottom position of the scrollbar).

It would be better to (approximately) maintain the scrolled position, so that the user keeps seeing whichever data was previously shown.

In VTE we usually track the position at the bottom of the viewport and try to keep that at the bottom; except when fully scrolled back to the top. More details in [doc/rewrap.txt](https://gitlab.gnome.org/GNOME/vte/blob/master/doc/rewrap.txt).

**Comment by zadjii-msft** [comment]
Okay I implemented this just now and WOW what a quality of life improvement this makes. Thanks for the great tip 😉 I ended up using the top of the viewport instead of the bottom, but that was mostly due to the fact that I already had code that would quickly locate the top's position in the reflowed buffer. Fortunatley, this makes the "fully scrolled back to the top" case really easy ☺️
