### ISSUE TITLE
Clicking the current tab to raise the window should focus the text area

### ISSUE THREAD

**Issue by FaffeF** [microsoft/terminal#3609]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.6.2951.0

Any other software? Nope
```

# Steps to reproduce

1. Start Terminal
1. Focus another window
1. Re-focus Terminal by clicking on the active tab
1. Enter text using your keyboard

# Expected behavior

Raising the Terminal window should focus the text area no matter how you do it.

Works as expected if you click any other tab than the currently active.

# Actual behavior

Text input is ignored even though the Terminal window has focus. Text input is restored when clicking the text area or focusing another tab.

**Comment by egmontkob** [comment]
gnome-terminal used to suffer from this problem, too. It was super annoying.

**Comment by zadjii-msft** [comment]
Thanks for the report! This is actually something that's already being tracked in #1205 / #552, and is fortunately in PR in #3540. Hopefully should be fixed in the next release.

/dup #1205
/dup #552

**Comment by FaffeF** [comment]
Well, my searching skills are apparently not up to the task ¯\_(ツ)_/¯

And that should probably be /dup #522, not 552

**Comment by FaffeF** [comment]
This is not fixed in 0.7.3291.0

**Comment by zadjii-msft** [comment]
AH what happened?! This definitely was fixed in a previous commit of mine. Must have somehow regressed during the PR. I'll re-open and re-investigate.

**Comment by DJackman123** [comment]
Confirming that it doesn't work for me, either.  I'm on version 0.8.3651.0 of Terminal.  I played around with this a bit and found that it works fine when I use Alt-Tab to make Terminal the active window.  It also works when I click on the tab bar (but not a tab) of Terminal, or when I click on an inactive tab, or even the drop-down menu.  It also works when using Ctrl-Tab or clicking inactive tabs when Terminal is active.  
However, if I click on the active tab then focus is removed from the text area of the window.  This happens regardless of whether Terminal is the active window when clicking the tab.

**Comment by FaffeF** [comment]
A bit sad this is still not fixed in 0.10.781.0 😥

**Comment by gfody** [comment]
this bug is bah-ack

**Comment by gfody** [comment]
Some additional usability notes as of 1.0.1401.0:
Once the tab has focus it keeps it, even if you alt-tab away and back, or use the minimize/restore buttons - the only way to get the cursor back in the terminal is to tab until it lands there or click the main terminal area.

Ideally the tab wouldn't capture focus at all, but it would probably also suffice to just make it so that clicking the tab switched focus to the terminal area.

**Comment by DHowett** [comment]
> the only way

Like, even _clicking in the terminal region_ doesn't do it? Huh.

**Comment by gfody** [comment]
> 
> > the only way
> 
> Like, even _clicking in the terminal region_ doesn't do it? Huh.

clicking works as long as you don't click on the tab

**Comment by mle-ii** [comment]
This still repros in `1.1.2233.0`.

**Comment by zadjii-msft** [comment]
@mle-ii Yep, it sure will. That's why this issue is still open 😉

**Comment by FaffeF** [comment]
Really hard to fix, or just keeps getting left on the backlog?

**Comment by DHowett** [comment]
@FaffeF https://github.com/microsoft/terminal/pull/6290#issuecomment-674189421

**Comment by zadjii-msft** [comment]
Honestly a bit of both. Hard to come up with a good, comprehensive way to prevent this from regressing in the future, and also not be hard to maintain, and because of that, it just keeps getting left behind. 

IIRC one of the solutions I imagined required that every UI element we add to manually do some work to do the right thing, and that's not great. Like having the cmdpal toss the focus back to the focused control isn't wrong, but it doesn't handle the search/find box appropriately. So we could do a similar thing with the tabs, presuming we fix the search box focus issue. But then also the tab color picker needs to manually toss the focus back, and the tab context menu, and the tab renamer, and anything else we might add, so that doesn't seem the most scalable

**Comment by mle-ii** [comment]
Luckily this is not too hard to work around.  I tried a few things out, so besides clicking in the terminal window area one can hit tab 2 times or click a different tab and back to the tab you want.  But yeah, I've sent a few words off into the ether after clicking a tab.  LOL

I suppose some other possibilities until this can get fixed without breaking things is to show that the tab UI has focus (you can see focus shown if you hit left or right arrow key when the tab has focus) and/or flash when the tab UI has focus and you type.  Or perhaps when certain keys, like say alpha/numeric are hit the focus moves to the terminal and text gets sent there.  

What is odd is that Ctrl+Tab cycling around through the tabs or back again with Ctrl+Shift+Tab gives the window the proper focus when is back to that tab.

And I agree, getting focus right is very hard.  I spent several years of my working career at MS in my past working on testing UI controls.  :)

**Comment by vefatica** [comment]
Yup.  This behavior is very annoying.

**Comment by JFLarvoire** [comment]
This still happens in version 1.3.2651.0, and this is very annoying indeed:
Several times a day, I click on a tab, and type several words for nothing... until I notice they have not appeared in the terminal :-(
The strange thing is that the occurrence is unpredictable: Most of the times, it just works fine.

**Comment by FaffeF** [comment]
Halleluja!
