### ISSUE TITLE
Feature request: allow keyboard input while an app is running 

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#3694]
# Description of the new feature/enhancement

Sometimes, as a shell user, I just want some space before some app is about to log something interesting, as a kind of visual marker, so what's appear doesn't get lost in the noise. 

Unix folk often just bang enter to do this, but the console and Windows Terminal seem to take keyboard control away when an app is running

It would be useful to allow this as an option.

**Comment by zadjii-msft** [comment]
I don't really think this is a _terminal_ problem, this might just be more of a commandline client issue.

If I run `ping bing.com` in conhost or the Terminal, I can definitely still use enter to separate the lines of output easily. `ping.exe -t bing.com` however eats the keystrokes. 

Since this is something that each client seems to handle in their own way, I'm not sure there's a way for us to be able to solve that without breaking compatibility...

**Comment by mikemaccana** [comment]
@zadjii-msft You can? `bing.com` doesn't respond to ICMP for me, but more importantly, if I try a site that *does* respond, using enter does not separate the lines of output:

```
 ping google.com

Pinging google.com [172.217.169.46] with 32 bytes of data:
Reply from 172.217.169.46: bytes=32 time=6ms TTL=56
BANGS ENTER A LOT RIGHT HERE AND NOTHING HAPPENS
Reply from 172.217.169.46: bytes=32 time=6ms TTL=56
```

I actually asked about it on the Powershell slack, and they thought it was terminal / conhost thing. 😂

**Comment by zadjii-msft** [comment]
Okay so I may have tried with _another search engine_ that _did_ respond to `ping`, and then edited my post assuming `bing.com` would work 😆 

I may have also accidentally forgotten an important piece of info: __WSL__ `ping` works, but `ping.exe` does _not_:

WSL ping:
![image](https://user-images.githubusercontent.com/18356694/69566414-a95c9600-0f7c-11ea-91f7-8969f0d7e6ee.png)

You can see the spots where I hit enter a bunch in the middle of ping

`ping.exe`:
![image](https://user-images.githubusercontent.com/18356694/69566458-c1341a00-0f7c-11ea-9038-6f97c0faceb3.png)

Here you can see cmd.exe processing all the enters from while I was running `ping.exe` all at the end

**Comment by DHowett-MSFT** [comment]
The core of the issue here is that on the unix/linux tty subsystem, standard input is in echo mode by default. Even when an application isn't reading, the tty will echo back all of your input.

The console subsystem defaults to echo _off_, but the application is still receiving the events. For heaps of reasons, most of which are compatibility and user expectations around input, we're not going to be changing that. Sorry!

/resolution-answered
