### ISSUE TITLE
Trying to define color 256 causes temporary hang

### ISSUE THREAD

**Issue by egmontkob** [microsoft/terminal#3720]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.7.3291.0
```

# Steps to reproduce

Trying to redefine the exact RGB value for color index 256:

    echo -ne '\e]4;256;rgb:ab/cd/ef\e\\'

# Expected behavior

Nothing, because the index is out of range.

# Actual behavior

The next shell prompt and the command as I type it doesn't appear. It takes a newline or so to get out of this state.

Note: This issue only occurs with exactly 256. With bigger numbers there's no hang.

**Comment by j4james** [comment]
Note that this is not a conhost issue - it only fails in Windows Terminal. The exact source of the error is in the `Terminal::SetColorTableEntry` method:

https://github.com/microsoft/terminal/blob/99a833718525214aeb8846ec8a88b5551b80df21/src/cascadia/TerminalCore/TerminalApi.cpp#L401-L405

That test should be `>=`. It might even be safer to drop the test and rely on the `at` checking, but just make sure the exception is handled properly. Because even if we fix this particular test, it doesn't seem right that an exception would cause the parser to get into such a weird state.

**Comment by zadjii-msft** [comment]
Ooh, good catch. Thanks for finding that @j4james!
