### ISSUE TITLE
Sometimes panes won't expand and take up blanks

### ISSUE THREAD

**Issue by hez2010** [microsoft/terminal#3744]
# Environment

```none
Windows build number: 18363.476
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce
1. create lots of split panes and resize some panes.
2. run `exit` on some of panes to close some panes.
3. sometimes other panes won't take up the spaces of closed panes.

# Expected behavior
Other panes should take up the blank space of the window after I close some panes.

# Actual behavior
The blank spaces still leave blank.
![image](https://user-images.githubusercontent.com/14960345/69729004-8985c780-1160-11ea-8353-078e6ddd8119.png)
![image](https://user-images.githubusercontent.com/14960345/69728791-167c5100-1160-11ea-8343-85b329e86719.png)

However, if you resize the window, the panes will return to normal.

**Comment by zadjii-msft** [comment]
wowowow that looks really bad. Thanks for the report! This doesn't always repro, but it definitely does _sometimes_ repro. Good enough for us to be able to investigate.

**Comment by DHowett-MSFT** [comment]
Wait, this that _modern art_ I've been hearing so much about

**Comment by mcpiroman** [comment]
For the record, I've been seeing this for a long time, so that's not something recent. I must have forgotten to file an issue.

**Comment by mcpiroman** [comment]
I thing I've found the cause. But first, the simplest possible repro:

1. Split pane
2. Split the right pane
3. Close the left-most pane

This happens when neighbour of closed pane is a pane in 'parent' state. It won't get resized, because it's children's are sizes are specified by fixed pixel amount. By contrast, a 'leaf' pane does resize, because the terminal control inside is set to fill the grid. 
I don't quite understand the intent of https://github.com/microsoft/terminal/issues/3996#issuecomment-566676111, but that seems like the  ideal solution for this issue.

**Comment by zadjii-msft** [comment]
@mcpiroman Ooh, that's a really good catch. That comment probably will fix this. Thanks!
