### ISSUE TITLE
The copy/paste line wrapping bug is back

### ISSUE THREAD

**Issue by xgonc** [microsoft/terminal#3764]
# Environment

```none
Windows build number: 10.0.18362.10024
Windows Terminal version (if applicable): v0.7.3291.0
```

# Steps to reproduce

Copy some text from the terminal, with multiple lines
Paste that text inside a terminal editor (tested with `nano`)

# Expected behavior

Copy text in multiple lines, paste the same multiple lines

# Actual behavior

The pasted text will be concatenated in 1 line

**Comment by mkitzan** [comment]
From when I hexdump-ed a repro of this, it looks like on multi-line copy-pastes, instead of inserting a newline at the separation between lines it just adds spaces until the next line begins (as it appears on the screen). Kind of makes sense since the selection is highlighting spaces instead of jumping to the newline.

Here's the hexdump of text from the top of a new CMD terminal:
<img width="522" alt="cmd-prompt" src="https://user-images.githubusercontent.com/28279285/69933330-2f984100-1483-11ea-96d2-53c007ff2e56.PNG">
<img width="329" alt="hexdump" src="https://user-images.githubusercontent.com/28279285/69933218-cadce680-1482-11ea-8cf7-a8beebf7b6c5.PNG">

**Comment by DHowett-MSFT** [comment]
Say, are you copying with right-click or with the <kbd>ctrl+c</kbd> or <kbd>ctrl+shift+c</kbd>?

**Comment by mkitzan** [comment]
@DHowett-MSFT it behaves like that with `ctrl+c` or `ctrl+shift+c`, but it works fine with right click. What.

**Comment by AjawadMahmoud** [comment]
@mkitzan, thanks for the tip. I wrote small Python script with Terminal in order to generate some long, repetitive-kind of text, I faced the wrapping bug when I copied text with `ctrl+c`, but right click saved the day.

**Comment by AjawadMahmoud** [comment]
So new release `v0.7.3382.0` has fixed the problem for me, it's mentioned in the release notes:
https://github.com/microsoft/terminal/releases/tag/v0.7.3382.0

**Comment by DHowett-MSFT** [comment]
Thanks for confirming.
