### ISSUE TITLE
Crash when opening and closing a tab

### ISSUE THREAD

**Issue by timkoers** [microsoft/terminal#3776]
Environment
```
Windows 10 Home 18363.476
Windows Terminal (Preview) Store installation - v0.7.3291.0
```

When opening and closing a 3rd tab, when two tabs are already openend and a single tab is executing a command, the Terminal crashes completely.

I had a Windows PowerShell tab open as my first tab and a Ubuntu shell open as my second tab, opening and closing a new Windows PowerShell tab as the third one.

**Comment by mkitzan** [comment]
I found a very consistent way to crash WT when trying to replicate your issue. Have at least one tab open then in quick sequence use open your WSL terminal (using your keyboard shortcut) then enter the keyboard shortcut to close a tab. I have WSL mapped to Ctrl+Shift+1 and close tab on Ctrl+W. So by hitting Ctrl+Shift+1 then immediately Ctrl+W, WT crashes every time.

**Comment by mkitzan** [comment]
Did a check of other issues. This issues sounds like a duplicate/instance of #2248.

**Comment by DHowett-MSFT** [comment]
In addition, there's at least one instance of us keeping a reference to a predeceased terminal control or tab object during a title changed event. We need to do a pass to make our async event handlers take weak references!

**Comment by mkitzan** [comment]
@DHowett this crash instance is due to the `Tab` [passing itself a raw pointer](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/Tab.cpp#L299) to the title change event handler and being de-referenced past its lifetime (as you suspected). In order for `Tab` to support WinRT `weak_ref`, we'll have to turn it into a WinRT object so it can be a [valid template argument](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/weak-ref#template-parameters) when calling `get_weak` or `make_weak`. I'll work on figuring out how to do that.

**Comment by zadjii-msft** [comment]
@mkitzan it might be easier to change `Tab` to [`enable_shared_from_this`](https://en.cppreference.com/w/cpp/memory/enable_shared_from_this), and then get a weak pointer to itself. Making the `Tab` a proper WinRT type is something we'd definitely want to do in the future, but we might want to get this particular crash solved faster than that :P

**Comment by mkitzan** [comment]
Sounds like a good plan for the time being. I'll add a TODO in the source to eventually make a WinRT type.

**Comment by mkitzan** [comment]
@zadjii-msft currently the event handlers are bound to the `TermControl` and root `Pane` on construction of `Tab`. The lambdas can't correctly capture the `std::weak_ptr<Tab>` because they require the object spawning the `std::weak_ptr<Tab>` to be of type `std::shared_ptr<Tab>` (instead of plain `Tab`). So, to get this to work I'm thinking of adding a weird `Tab` function member to provide a `Tab` object with a `std::weak_ptr<Tab>` to itself before binding the events. Any thoughts on this, because it seems a little 🙃

**Comment by DHowett-MSFT** [comment]
If we make Tab inherit from `enable_shared_from_this<Tab>`, it'll gain a method `shared_from_this()` that will return a `std::shared_ptr<Tab>` that you can then weaken :smile:

**Comment by mkitzan** [comment]
Thanks @DHowett-MSFT, Got too focused on the `weak_ptr` side of things! Using `shared_from_this()` still requires a function member to initialize the event binding, because calling `shared_from_this()` inside the constructor throws `bad_weak_ptr` exception. Luckily, calling the binding function fits well in [`TerminalPage::_RegisterTerminalEvents`](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/TerminalPage.cpp#L756). This fixes the issue, no more crashes when rapidly opening-closing tabs!
