### ISSUE TITLE
suppressApplicationTitle hides the "Administrator" identifier on the tab

### ISSUE THREAD

**Issue by encladeus** [microsoft/terminal#3779]
# Environment

```none
Windows build number: [10.0.18362.476]
Windows Terminal version: [0.7.3291.0]

Any other software? No
```

# Steps to reproduce

1. Define a cmd profile with `"suppressApplicationTitle": true`
2. Define the same profile with a tabTitle, such as `"tabTitle": "cmd"`
3. Start Windows Terminal as an **Administrator** (_Run as Administrator_).
# Expected behavior

The tab appends the **Administrator** identifier to the tab:
![image](https://user-images.githubusercontent.com/8571098/69870400-a7aa0f80-12a7-11ea-91dc-2ff0b39898cd.png)

This issue may be related to #3743 but it is not clear that this is exactly the same issue.

# Actual behavior

The **Administrator** identifier is omitted from the tab:
![image](https://user-images.githubusercontent.com/8571098/69870446-c90afb80-12a7-11ea-8b69-63ebb2c01d0b.png)

If there were another way to identify a Windows Terminal session that is running as an administrator, I would probably prefer this behavior.  It would be better than repeating **Administrator** on each tab, using valuable space.

**Comment by DHowett-MSFT** [comment]
So, there's a couple things here. `suppressApplicationTitle` is working as-intended, because `Administrator:` is part of CMD's app-specified title. You're probably looking for /dup #1939, though, at the end of the day.

fwiw: if you do not want the application's title to be suppressed -- and this applies to all application titles, including those emitted by shells in WSL that include your username (like `root`) -- you may want to investigate setting good titles from your shell and not suppressing them :smile:
