### ISSUE TITLE
Closing vim changes colors for previous prompts

### ISSUE THREAD

**Issue by heaths** [microsoft/terminal#3794]
# Environment

```none

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable): N/A

Other Software:
vim 8.1
```

# Steps to reproduce

1. Use a colored prompt (like powerline) with colors about the normal 16 color palette. For example, for cmd something like: `PROMPT $e[38;5;231;48;5;55m$$$s$e[0m`
2. Open vim: `vim`
3. Close vim: `:q`

# Expected behavior

Previous colors stay the same.

# Actual behavior

Colors from previous prompts that were rendered seem to resort to the 16-color palette, e.g. the purple in the example above is now magenta. Light blue turns to blue, etc.

To note, this seems to happen with any conhost, but it doesnt reproduce if I run WSL in cmd/pwsh then open vim in wsl. However, if I open vim.exe in WSL, it launches okay but upon closing the previous history is completely erased.

Perhaps this is an error with Win32 vim, but perhaps the color palette shouldn't be allowed to be changed by any program that was written when conhost supported only 16 colors. Just a thought.

![PowerShellCore2019-12-0111-05-23](https://user-images.githubusercontent.com/1532486/69919013-6479a900-142d-11ea-892e-eeadd47f03cf.gif)

**Comment by j4james** [comment]
I suspect the problem here is not the palette, but the fact that vim saves the contents of the screen buffer using the `ReadConsoleOutput` API (see [here](https://github.com/vim/vim/blob/912bc4a51af0ad947cb39deba2a6fa4ee27af906/src/os_win32.c#L2346)), and that API only supports [4-bit colors](https://docs.microsoft.com/en-us/windows/console/char-info-str). As a result, the restored screen is only going to be an approximation of what was originally there.

**Comment by DHowett-MSFT** [comment]
Correct! Vim has had fifteen years to support the alternate screen buffer API :smile: I did some digging and it looks like this solution was _never_ required, as allocating and switching console buffers dates back to the earliest versions of Windows.

Now they could at least use the xterm alt buffer here!

@parkovski has been, if I recall correctly, looking into bringing Vim for Windows into the modern age?

**Comment by DHowett-MSFT** [comment]
Closing this one out since there really isn't anything we can do about poorly-behaved applications.

**Comment by heaths** [comment]
@DHowett-MSFT any idea which version of Windows introduced the alt buffer? I'd be interested in submitting a change to vim to stop doing that when unnecessary, but know they try to support some really old versions of Windows (for some reason). Or, when you said *never*, did you mean even in WFW 3.1 which, IIRC, is the oldest they still support?

@parkovski have you already been looking to change that (if not more)?

**Comment by DHowett-MSFT** [comment]
So, allocating alternate buffers with the API dates back to the earliest references I could find in Windows 95. I thought that WFW 3 didn’t _have_ a console API and instead offered unreal-mode access to a VGA text buffer, but I could be wrong.

Allocating alternate buffers with VT sequences is a Windows 10 10.0.10240 thing. Vim already has version and capability checks laying around, so it would not be unusual to introduce another.

**Comment by heaths** [comment]
I see there's already a bug (and workaround from @lzybkr) opened at vim/vim#5092.

**Comment by parkovski** [comment]
I haven't done much with vim itself, I use neovim regularly and I did patch [some missing keys in libuv](https://github.com/libuv/libuv/pull/2535). There's [another awful hack](https://github.com/parkovski/config/blob/ae16204ab3ccce8e427fa591e7f7be6c973923d5/.vimrc#L623) I use (this utility can be found [here](https://github.com/parkovski/conutils/tree/master/isvt.cpp)), but between these two things my neovim experience is pretty solid. Hoping to get around to adding conpty to neovim at some point as I ignore the embedded terminal and just use tmux for now.

Vim unfortunately is still glitchy for me and I'm probably not going to pursue it, but there are a couple vim contributors that work on the Windows compat stuff if they get good bug reports. It's important to clarify if the issue happens over a plain conhost, conpty (like WinTerm), or WSL interop PTY (tmux) because there are subtle differences.
