### ISSUE TITLE
docker-desktop-data not working crashes on open

### ISSUE THREAD

**Issue by 810** [microsoft/terminal#3795]
# Environment

```none
Windows build number: 19033.1
Windows Terminal version (if applicable): v0.7.3291.0

Any other software?
Latest docker installed, and setup correctly.
```

# Steps to reproduce

click on docker-desktop-data

# Expected behavior

open de wsl on the correct location.

# Actual behavior

tab crashed and close it.

**Comment by DHowett-MSFT** [comment]
The `docker-desktop` distributions are not meant to be used. They are created by Docker for Windows and are part of the Docker for Windows WSL2 integration.

**Comment by 810** [comment]
I would like have this feature on the terminal. 

Like for a docker container cli.

So maybe with a container option, example:

````
{
            "guid": "{d8afdc0e-a636-5b68-89dd-50a9d0b54349}",
            "hidden": false,
            "name": "docker-desktop-data",
            "container": "joomlanew_joomla_1",
            "source": "Windows.Terminal.Wsl"
        },
````

**Comment by DHowett-MSFT** [comment]
Since Docker containers can run so many different things-different distributions _and_ different operating systems-there would be no way for Terminal to know what shell to run inside the container. This is best left to the user to configure. You can set the `commandline` to `docker exec -ti container-name /bin/bash`, if you want, and change `/bin/bash` to a shell you know exists inside the container.
