### ISSUE TITLE
Enable sending input to the Terminal with a keybinding

### ISSUE THREAD

**Issue by compulim** [microsoft/terminal#3799]
# Description of the new feature/enhancement

On Windows, there are difference between <kbd>CTRL</kbd> + <kbd>C</kbd> and <kbd>CTRL</kbd> + <kbd>BREAK</kbd>, as mentioned in #1118.

Some keyboard layouts do not have the <kbd>BREAK</kbd> key. For example, on Surface keyboard, there are no <kbd>BREAK</kbd> key. In some situations, <kbd>CTRL</kbd> + <kbd>BREAK</kbd> is a crucial way to break some processes.

Will be great if Windows Terminal has a command to map <kbd>CTRL</kbd> + <kbd>BREAK</kbd> to some other keys, e.g. <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>BREAK</kbd>.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
I could have sworn that we had an issue that was "I want to be able to send input to the Terminal with a keybinding" but it doesn't seem like we do. Congratulations! This is now that issue ☺️ 

Previously mentioned (in #2046):
* [ ] We want to be able to send strings of characters
* [ ] We want to be able to send input with or without a trailing newline (so people can run a command like #2809)

**Comment by j4james** [comment]
In case this affects the implementation, note that there are a couple of VT escape sequences for reprogramming the keyboard which we may want to support one day (e.g. [`DECUDK`](https://vt100.net/docs/vt510-rm/DECUDK.html) and [`DECPFK`](https://vt100.net/docs/vt510-rm/DECPFK.html)).

Also I think issue #2005 is quite similar to this.

**Comment by compulim** [comment]
@zadjii-msft I can read your mind. 😏

**Comment by SeeminglyScience** [comment]
This would also enable a decent workaround for #530 (remap <kbd>SHIFT</kbd> + <kbd>ENTER</kbd> to some symbol that can be read instead).  That would be an excellent band-aid for PowerShell folks looking to migrate.

**Comment by damnskippy** [comment]
+1 request for this feature.

**Comment by damnskippy** [comment]
For those who desperately seek a solution/workaround to remap key bindings, [powertoys ](https://github.com/microsoft/PowerToys/tree/master/src/modules/keyboardmanager) has a module to do this.  Not the most perfect solution (since the mapping is global to the OS, not just the terminal) and I'm sure there are equivalents out there (AHK for instance), nor can you enter arbitrary input (only map to another shortcut), but this will at least tide one over until terminal can support this natively.

**Comment by damnskippy** [comment]
Just curious if there's any love for this issue and is tracked on some milestone?  Seems like a fairly popular request/demand based on the various dupes.  Thanks, and much gratitude to WT - my daily driver.

**Comment by DHowett** [comment]
Alas! We haven't been working on this one, but we're pretty keen on it. I'm moving it into the 2.0 milestone and out of the backlog.

I don't know if I believe that a spec is required beyond a paragraph explaining what `sendInput` would do.

**Comment by zadjii-msft** [comment]
No real commitments on this one quite yet. I especially want to do this for it's potential integration with the command palette (#5400). The hardest part of this is honestly just designing exactly how the setting should work. How will arrow keys be encoded in the settings file? Trailing newlines? etc. 

The implementation itself should be fairly trivial

**Comment by damnskippy** [comment]
Wonder if it's an option to specify a sequence/string of characters bound to a key shortcut.  User can input the escape sequence for the key they want to enter.  For example, left arrrow will be `"\x1b[D"`.  This would also allow for the other use case for this i.e. to be able to enter an arbitrary text (as opposed to mapping to another key).  Say `F12` is mapped to a character sequence `"text entered over and over again\n"`  (including the newline).  I believe Alacritty does something like this. 

Just a thought, not sure how useful.

**Comment by lhecker** [comment]
I'd like to implement this feature, if you don't mind. 🙂

I believe this feature is crucial, but realistically will probably only be used by a small fraction of all Windows Terminal users.
As such it'd be best in my opinion to keep the feature as straightforward and low level as possible. That way it's easy to implement and simultaneously very powerful.

### Config

I imagine a potential config setting to look like the following:
```json5
{
    "keybindings":
    [
        // Bind Ctrl+Shift+C to the Delete key
        { "keys": "ctrl+shift+c", "command": { "action": "sendInput", "input": "\x7f" } },

        // Send some text when pressing F12
        { "keys": "f12", "command": { "action": "sendInput", "input": "text entered over and over again\n" } },

        // Swap left/right arrow keys (lol)
        { "keys": "left", "command": { "action": "sendInput", "input": "\x1b[C" } },
        { "keys": "right", "command": { "action": "sendInput", "input": "\x1b[D" } },

        // Send a VK_PLAY (media play/pause button) key press to your shell
        { "keys": "f11", "command": { "action": "sendInput", "input": "\x1b[250;0;0;1;0;1_\x1b[250;0;0;0;0;1_" } },
    ]
}
```

Unfortunately I don't have a solution for <kbd>Ctrl</kbd><kbd>Break</kbd> as that's equivalent to calling `TerminateProcess` and AFAICS you may just as well close the offending tab, right? 🤔

### Implementation

* Extend [`IKeyBindings::TryKeyChord`](https://github.com/microsoft/terminal/blob/20a288020e26d48efab309b843e41498e7bc8684/src/cascadia/TerminalControl/IKeyBindings.idl#L11) to return a pair of `bool handled` and `string sendInputValue`.
  `sendInputValue` is dedicated exclusively to the `sendInput` action. It contains the value of the `command.input` field. `sendInputValue` is empty if the key chord wasn't handled, or the action isn't of the `sendInput` kind.
* If `handled` is `false` the key chord wasn't handled and nothing further needs to be done by `TermControl`.
* Otherwise the contents of `sendInputValue` - if any - are directly given to `TermControl::_SendInputToConnection`.

### Future extension

The above solution is very technical, but IMO sufficient for an initial implementation and can still be extended later on.
For instance the Win32 key sequences could also be represented with a JSON object instead.

**Comment by zadjii-msft** [comment]
Thoughts off the top of the dome:
* I think we'll need `\u001b` to be the encoding for escape (for json's sake). I don't love that, but I think json will explode on `\x1b`
* As far as implementation is concerned, I think it might be easier to just expose `TermControl::SendInput(hstring input)` as a method projected off of the `TermControl` class, rather than return a tuple from `TryKeyChord`. Then, just have `TerminalPage` actually send the string to the control, kinda like it handles paste or other actions with args:

```c++
    void TerminalPage::_HandleSendInput(const IInspectable& /*sender*/,
                                        const TerminalApp::ActionEventArgs& args)
    {
        if (const auto& realArgs = args.ActionArgs().try_as<TerminalApp::SendInputArgs>())
        {
            const auto termControl = _GetActiveControl();
            args.Handled(termControl.SendInput(realArgs.Input()));
        }
    }
```

The implementation of `SendInput` would be as easy as you suggest -  the contents of `realArgs.Input()` are directly given to `TermControl::_SendInputToConnection`.

I'm totally on board with this, thanks for the writeup! I'll throw you on the **Assigned To** line 😉

**Comment by lhecker** [comment]
Aww... I always thought WT uses JSON5, but it seems it's using JSONC. (JSON5 supports `\xNN` escape codes.) \*insert comment about using YAML here\* 😄

Thanks @zadjii-msft! I wasn't aware about `AppKeyBindings::SetDispatch` and how it integrates into `TerminalPage`.
I've edited my proposal above to use unicode escape codes and changed the implementation section.
