### ISSUE TITLE
Thread race condition on refreshing the screen and listening to keyboard signal?

### ISSUE THREAD

**Issue by were** [microsoft/terminal#3827]
I use WSL Ubuntu 18.04.
I wrote a program that dumps tons of logs to stdout and I want to use `<Ctrl-C>` to terminate this program.

Then it does not work, it seems the main thread is too busy (refreshing the screen logs) to listen to `<Ctrl-C>` signal.

**Comment by zadjii-msft** [comment]
@were could you confirm for me that what you're seeing is basically the same thing described in #3169? That issue is also basically "I try some input and there's a delay before the Terminal reacts to it".

What applications are you all using in your stack when this repros? `ssh`? `tmux`? `screen`? `less`? 

Are you still seeing this in 0.10?

**Comment by were** [comment]
I think it is good now. I no longer face this problem in the current version. I can close it. Thank you!

**Comment by zadjii-msft** [comment]
Glad to hear it! Thanks for following up ☺️
