### ISSUE TITLE
Prompt is slow to render

### ISSUE THREAD

**Issue by rschuetzler** [microsoft/terminal#3840]
# Environment

```none
Windows build number: 18363.476
Windows Terminal version (if applicable): 0.7.3291.0

Any other software?
```

# Steps to reproduce

1. Open a terminal
2. Type a command (e.g., `ls`)

# Expected behavior

Action happens and new prompt appears immediately

# Actual behavior

The prompt takes possibly more than a second to reappear. This happens only on the local system, and only within WSL. The Windows cmd shows up immediately. With WSL this happens on either the Windows Terminal or the Ubuntu terminal.

**Comment by rschuetzler** [comment]
I made a gif of it happening. Of course it's going faster now that I'm recording it.
![Untitled Project](https://user-images.githubusercontent.com/600775/70234005-4e1d6700-1725-11ea-8bf8-8efa9d718cf4.gif)

**Comment by zadjii-msft** [comment]
If this is something that's happening universally on both the vintage console (`conhost.exe`) and the new Windows Terminal, and it's only something you're experiencing on WSL (not cmd, powershell, etc.), then this sounds like it's probably a problem with WSL, not the Terminal 😉 

I'd file an issue at [microsoft/WSL](https://github.com/microsoft/WSL), since they'd be better equipped to be able to solve this perf issue. Doesn't really seem like it's something the console can fix here.

**Comment by rschuetzler** [comment]
Filed at WSL https://github.com/microsoft/WSL/issues/4734
