### ISSUE TITLE
Allow users to configure the tab size

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#3847]
# Description of the new feature/enhancement

Tab is often used inside files. It can traditionally be 8 characters, but eg Python commonly uses 4 and JS uses 2. it would be useful to allow the user to configure the tab size. or maybe this would be better handled in higher level tools? Just a thought.

![image](https://user-images.githubusercontent.com/172594/70250317-9d8b8380-1775-11ea-9741-7f884bb5ed17.png)

**Comment by DHowett-MSFT** [comment]
Nah, terminal tabs are always either 8 or whatever the client application set by using the “set horizontal tab stops” escape sequences. That sequence is already well-supported in conhost (and therefore, in Terminal).

**Comment by zadjii-msft** [comment]
There are commadline applications that are out there (@ emacs) which assume that tabs are 8 spaces, and others out there that change the width of a tab so that they can quickly navigate within the buffer. If we let people configure this default value, that would _undoubtably_ break the rendering of these applications. 

It'd probably be easier to get a `--tabWidth 4` param added to `cat`

**Comment by mikemaccana** [comment]
Yeah fair enough @zadjii-msft I suspected as much. 👍🏼

**Comment by cygnus2048** [comment]
So how do I configure the terminal to use 4-spaces for tabs?

**Comment by lhecker** [comment]
As explained above, tabs aren't really configurable in terminals in general. Unless I'm mistaken, other popular terminals do not allow this to be configured either. Your application or editor likely has a setting to change the width of tabs already. `vim` for instance uses the `tabstop` and `shiftwidth` settings for this.
