### ISSUE TITLE
Destruction of displayed string in ConhostV2

### ISSUE THREAD

**Issue by ntak** [microsoft/terminal#3868]
Is this behavior recognized as a problem?
Cmd.exe of Japanese build 19035.1 was captured.
If you move the cursor position, the character at the position that seems to be the route moved is destroyed.

![test](https://user-images.githubusercontent.com/44701315/70328332-1b39b700-187c-11ea-8fda-fa927362e70f.gif)

https://github.com/microsoft/terminal/issues/724

**Comment by zadjii-msft** [comment]
This does look like it's exactly the same issue as #724, unless I'm missing something, correct? @ntak is there something specific to this bug that makes it different than #724?

**Comment by ntak** [comment]
I pinged #724, but since there was no reaction for half a year, I raised it again to prove that it was not a problem with Vim.
Because of this problem, some percent of Japanese developers cannot be developed with Insider build. Loss of opportunity.

Same problem, please ignore it forever. Does Microsoft need a multi-byte culture?

**Comment by zadjii-msft** [comment]
@ntak We do have a _lot_ of issues on our plate, and unfortunately we get more bugs than we have the developer resources to be able to solve. We definitely want to be able to solve all the bugs in our software, but there's just not enough time to solve them all. If you're particularly motivated, the source for the Windows Console is open-source now too, and we'd welcome a external contribution to fix this. Otherwise, I've marked the original bug up to make sure that it gets fixed in the next Windows release.
