### ISSUE TITLE
Backspacing a tab character in conpty causes visual corruption

### ISSUE THREAD

**Issue by getkirill** [microsoft/terminal#3971]
# Environment

```none
Windows build number: 18362.476
Windows Terminal version (if applicable): 0.7.3451.0

Python 3.5>>> 3.8
```

# Steps to reproduce
Add to config file:
```none
{
            // Make changes here to the python.exe profile
            "guid": "{0cab0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "Python",
            "commandline": "C:\\Program Files\\Python35\\python.exe",
            "hidden": false,
	    "backgroundImage": "C:\\Users\\noncyrilicusername\\Documents\\DDLC\\extract\\src\\images.rpa\\images\\cg\\credits\\1.png",
            "backgroundImageOpacity": 0.5,
	    "icon": "C:\\Program Files\\Python35\\icon.png"
        }
```

Launch new tab, try to write text, press Enter, press Up Arrow, try to edit
# Expected behavior
Normal text

# Actual behavior
![image](https://user-images.githubusercontent.com/26975352/70862493-32e4ff80-1f4e-11ea-85c3-bfc7a41818e2.png)

**Comment by zadjii-msft** [comment]
@getkirill I'm not seeing this repro with python 3.7.5 - could you try updating python to see if that fixes it?
![image](https://user-images.githubusercontent.com/18356694/70911623-e0502580-1fd7-11ea-8cad-899745284f25.png)

If it doesn't, then I think I'm going to need some more specific steps to help repro this. Exactly what input is causing this to repro? Does it repro in a plain old conhost/Console window?

**Comment by getkirill** [comment]
@zadjii-msft I use config with python cmd, + i upgraded python to 3.8.

**Comment by zadjii-msft** [comment]
Okay so it's not dependent upon python version. Could I get some literal text that repros this bug for you? I can't get it to happen on my end by just entering commands and attempting to use the up arrow to navigate the history.

**Comment by strayge** [comment]
windows 10.0.19037.1
terminal 0.7.3451.0
python 3.7.4

Steps to reproduce:
1) open new "cmd" tab
2) run "python"
3) write text with tab identation, ex.: `<tab>123`
in terminal it now looks like: <pre>>>>     123</pre>
4) move cursor to `<tab>` character and delete it with `<Backspace>`/`<Del>`
5) terminal shows <pre>>>> 123 123</pre>

**Comment by zadjii-msft** [comment]
Okay, that's much more helpful. Thanks!

**Comment by j4james** [comment]
Note that this is a conhost bug, and as far as I can tell, it only occurs when VT mode is enabled (i.e. you've set the _VirtualTerminalLevel_ registry entry).

The issue is that the `WriteCharsLegacy` method handles tabs differently in VT mode, and doesn't update the number of spaces written. If you look at [the section of code where the tab is processed](https://github.com/microsoft/terminal/blob/6f667f48ae109d4291cda1f8d4e977315c0dae8a/src/host/_stream.cpp#L758-L774), you'll see that `TempNumSpaces` is only updated in the non-VT branch. As a result, the `_visibleCharCount` in the `COOKED_READ_DATA` class is not updated correctly, and the `DeleteCommandLine` method then doesn't fully clear the line when backspacing.

It's possible this could be fixed just by updating `TempNumSpaces` with the distance that the cursor is moved in VT mode, but I don't know what other implications that would have. Also, the fact that we've got legacy code receiving VT-specific behavior is probably going to cause all sorts of other problems, because the two tab types are really quite different. That's potentially a bigger issue.

Long term, I think it would be preferable if we could get rid of all of this VT-specific code in the `WriteCharsLegacy` method and just let the `AdaptDispatch` class have its own text writer that follows the VT rules (I'm hoping that's what #780 is going to achieve). Short term maybe we should be passing a flag to `WriteCharsLegacy` to say whether any VT behavior is allowed. In fact, the existing `WC_DELAY_EOL_WRAP` flag could possibly be repurposed for that.

**Comment by j4james** [comment]
> Note that this is a conhost bug, and as far as I can tell, it only occurs when VT mode is enabled (i.e. you've set the _VirtualTerminalLevel_ registry entry).

Actually this bit isn't quite true. If you're using the Windows Terminal, then you probably wouldn't need to set the registry entry to trigger the issue, because WT already sets the VT mode automatically (I think).

**Comment by getkirill** [comment]
Thanks everyone for your feedbacks! Bug isn't fixed yet, but anyway, THANKS!
_(may contain broken english)_

**Comment by zadjii-msft** [comment]
> The issue is that the `WriteCharsLegacy` method handles tabs differently in VT mode, and doesn't update the number of spaces written. If you look at [the section of code where the tab is processed](https://github.com/microsoft/terminal/blob/6f667f48ae109d4291cda1f8d4e977315c0dae8a/src/host/_stream.cpp#L758-L774), you'll see that `TempNumSpaces` is only updated in the non-VT branch. As a result, the `_visibleCharCount` in the `COOKED_READ_DATA` class is not updated correctly, and the `DeleteCommandLine` method then doesn't fully clear the line when backspacing.
> 

This might highly concern @miniksa
