### ISSUE TITLE
Change "Adminstrator" in tabs to "Admin"

### ISSUE THREAD

**Issue by diligamer** [microsoft/terminal#4265]
# Description of the new feature/enhancement
Change "Adminstrator" To "Admin" in tabs, as it takes up space and hides away the name of the shell

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! If I remember correctly, this is something the shell application (cmd.exe or powershell) does on its own, not something the Terminal controls. `cmd.exe` is parked indefinitely, so we can't change that codebase. Powershell could maybe change this, you'd have to suggest it over at https://github.com/powershell/powershell. I _doubt_ they would though, since the title of the window (including the "Administrator:" string) is something that's queryable by commandline applications, and I would expect that changing that string would break a bunch of existing applications and scenarios.

If all you want is wider tabs so that you can see the entire title of the tab, might I suggest adding:
```json
    "tabWidthMode": "titleLength"
```
to the globals part of your `profiles.json` file. That should make the tab's width match the width of the title string. For more info, see: [SettingsSchema.md](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)

**Comment by diligamer** [comment]
I Understand That a lot of users may not need this and that it may break many things. Thanks for your response.

- Diligamer (Keanu Reeves)
CEO Of Socialounge
