### ISSUE TITLE
Special cursorShape for non-insert mode

### ISSUE THREAD

**Issue by manu-st** [microsoft/terminal#4266]
# Description of the new feature/enhancement

In a traditional cmd.exe prompt or when using some others such as jpsoft tcc.exe the cursor is different whether you are in insert mode or not. Usually in insert mode the size of the cursor is about 25% of the height, while not in insert mode it is 50% (I would actually prefer if the default was 100%).

This would let users quickly see if they are in insert mode or not.

# Proposed technical implementation details (optional)

I would like to see a new setting where the shape of the cursor can be modified as explained above:
```
 "overrideCursorHeight": {
          "description": "Sets the percentage height of the cursor starting from the bottom when it is in override mode (i.e. opposite of insert mode). Only works when cursorShape is set to \"vintage\". Accepts values from 25-100. Default "100",
          "maximum": 100,
          "minimum": 25,
          "default": 100,
          "type": "integer"
        },
```

**Comment by DHowett-MSFT** [comment]
Hey there! Thanks for the feature request.

Terminal is on the far side of a communication channel, and it doesn't actually know that the cursor "height" is changing (because that's not something that can be represented over the traditional terminal communication channel, "VT"). There isn't too much we can do about this today. Sorry.
