### ISSUE TITLE
Danish keyboard layout Ctrl+Alt+7

### ISSUE THREAD

**Issue by Agazoth** [microsoft/terminal#4279]
# Environment

```none
Windows 10, PowerShell 7.0 rc2, PowerShell Core, Windows Powershell
Danish keyboard settings
```

# Steps to reproduce

Ctrl+Alt+7

# Expected behavior

I would expect to get
{
in the console 

# Actual behavior

PowerShellCore and Windows PowerShell:
^_

PowerShell 7.0 rc1 and rc2
_

**Comment by DHowett-MSFT** [comment]
This may be helped by open PR #4192, actually. @lhecker any idea?

**Comment by lhecker** [comment]
Generally the issue here is - as far as I can see - that Ctrl+Alt is not the same as AltGr.
#4192 should fix this I suppose. I just need some free time to finally fix the failing unit tests. 😄

**Comment by lhecker** [comment]
#4192 woudln't fix this issue... yet. Until now I planned to retain the current behavior as much as possible, which includes [the AltGr handling](https://github.com/microsoft/terminal/blob/f0e6037570f637cf77d7f36b0fb3e399326d4857/src/terminal/input/terminalInput.cpp#L392-L396). --> Using Ctrl+Alt in place of AltGr is currently not supported.

But I've checked [ECMA-48](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-048.pdf) again and it clearly states that the second character of a C1 escape sequence must be in the range `[0x40, 0x5F]`. The [current code](https://github.com/microsoft/terminal/blob/f0e6037570f637cf77d7f36b0fb3e399326d4857/src/terminal/input/terminalInput.cpp#L413) supports pressing Ctrl during the creation of an escape sequnce though which is in violation of this spec.
If we drop this invalid behavior we can just trait AltGr the same as Ctrl+Alt - like Windows itself - and fix this issue as well.
Since I had to rewrite `TerminalInput::HandleKey` anyways I'll take the liberty to fix this issue within that single PR. 🙈
