### ISSUE TITLE
Potential Random console input overflow?

### ISSUE THREAD

**Issue by DSLM82** [microsoft/terminal#4298]
Consider the following Bash command line:

while [ loop != done]; do cat /dev/random; done

This will dump an endless string of random characters to the console forever.

After a few moments, this reliably results in the title bar in the terminal app changing and, shortly thereafter, the terminal hanging.

I wonder if this could be the basis for a buffer overflow, which if run against a terminal in  privileged mode might potentially open an attack vector.

I've reproduced this in Kali and Ubuntu, as well as with a friend who tested it with a clean install of Terminal/Ubuntu.

**Comment by j4james** [comment]
The title changing is to be expected. That's just the result of the random characters generating an OSC 2 escape sequence (which is used to set the title). The hanging is likely a duplicate of #4145 which was recently fixed by PR #4150. I can reproduce the hanging in a preview build (v0.8.10091.0), but it's no longer happening in the master build.

**Comment by DHowett-MSFT** [comment]
Indeed. I think this is likely to have been fixed as /dup #4145. Thanks @j4james for trying to repro.
