### ISSUE TITLE
Mouse Scrolling is not working

### ISSUE THREAD

**Issue by TimilsinaBimal** [microsoft/terminal#4315]
# Environment

```none
Windows build number:Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version (if applicable): Windows Terminal Preview v0.8.10091.0
```

# Actual behavior

Works Fine with CMD.exe but when I use CMD in Terminal vertical Scrolling automatically disabled and works only if I use the Scrolling bar in Terminal but that is only for sometime. Then again it stops scrolling. I even cannot see the contents after one page is full.

**Comment by zadjii-msft** [comment]
I'm not totally sure I understand what the problem is here - this could be any number of things:
* #545 Mouse-mode input doesn't work for commandline-line apps in the Terminal 
* #979 Some trackpads don't work for scrolling the Windows Terminal
* #4120 exceeding `historySize` variable set in `profiles.json` stops scrolling from happening

Do any of those sound like what you're seeing?

**Comment by TimilsinaBimal** [comment]
The Problem was, I wasn't able to scroll  neither with two finger gesture nor mouse wheel. 
But after reading  #979 , I found that the problem was due to the software ```X-Mouse Control```. And after disabling ```Scroll Window under Cursor```. It is working fine now.
Sorry for the duplication. And, Thanks for your help.
