### ISSUE TITLE
Incorrect space sanitization for shell creation

### ISSUE THREAD

**Issue by sqlrob** [microsoft/terminal#4322]
# Environment

```none
> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```
Terminal version 0.8.10091.0

# Steps to reproduce

1. Create a file `C:\Program`, contents irrelevant; this applies to en-us, other languages will have different names.
2. Open a powershell tab (other shells may have the issue, didn't check)

# Expected behavior

Tab opens with a usable Powershell

# Actual behavior

Window opens with the message
```none
[error 0x800700c1 when launching `powershell.exe']
```

**Comment by DHowett-MSFT** [comment]
(For the shell,)
This is, and always will be, how CreateProcess with search path expansion works. Sorry.

* We're relying on the system to do `PATH` resolution
* If we implement our own heuristics here, we have to expand `PATH` _and_ `PATHEXT` to properly populate the first arg to `CreateProcess`.
* Even if we fix this, other applications will fail in the same way.
* You need to be an admin to make a file there; there are far easier ways to break Terminal

(For the console host,)
This was fixed by #4172, which will be in the next servicing update... which may make this a /dup of #4061

**Comment by sqlrob** [comment]
Shells are in well defined locations. Why is PATH even being used?

**Comment by DHowett-MSFT** [comment]
I'm not sure I agree that shells are in well-defined locations- A user's entitled to reorganize `PATH` such that their preferred instance of `pwsh.exe` comes first, or so that they can set version priorities for OpenSSH. Shells are wherever the user wants to put them!

**Comment by eryksun** [comment]
>     * If we implement our own heuristics here, we have to expand `PATH` _and_ `PATHEXT` to properly populate the first arg to `CreateProcess`.

`CreateProcessW` doesn't use `PATHEXT`. It calls `SearchPathW` with an optional ".EXE" extension.

**Comment by DHowett-MSFT** [comment]
Fair enough.
