### ISSUE TITLE
It is not possible to scroll tabs list without touch screen

### ISSUE THREAD

**Issue by matthew4850** [microsoft/terminal#444]
* Your Windows build number:  10.0.18890.1000

* What you're doing and what's happening: If you open enough tabs you are unable to see all tabs at once. The only way to solve this is to either close this or use a touch screen to scroll horizontally.

* What's wrong / what should be happening instead: It should be possible to scroll tabs without a touch screen or the tabs should automatically resize so they all fit at once.

**Comment by kumarharsh** [comment]
I think the tabs should resize to *a particular min-width*, and then start scrolling. Basically, the tab behaviour should be like Firefox and not Chrome.

**Comment by zadjii-msft** [comment]
So there's a LOT of different opinions about how tabs should be sized. I'm not even going to open that can of worms here.

What I can say is that mouse scrolling of the tabs _should_work. Unfortunately, we're using a pretty early build of the TabControl, so when you try scrolling it with the mouse, the parts of the tabs that weren't visible before don't actually render for some reason. If you manually resize the window, then the tabs will figure themselves out.

**Comment by krzys-h** [comment]
I can confirm that scrolling the tab list with does not seem to work at all for me either. I don't have a touch screen to test.

Windows build 10.0.18362.86

**Comment by pavlkara1** [comment]
Scrolling works with a mouse but not as intended. When I open many terminal tabs as can be seen in the screenshot below, it doesn't show the complete tab and when I open more tabs, they don't even appear in the bar. (the maximum number of tabs are 4)
Also scrolling works with a mouse but not with Windows Precision trackpad.

**Comment by matthew4850** [comment]
Ah, I was using my surfaces trackpad

**Comment by Californ1a** [comment]
[**@kumarharsh**](https://github.com/kumarharsh) commented on [May 6, 2019, 11:53 PM EDT](https://github.com/microsoft/Terminal/issues/444#issuecomment-489897429 "2019-05-07T03:53:27Z - Replied by Github Reply Comments"):
> I think the tabs should resize to _a particular min-width_, and then start scrolling. Basically, the tab behaviour should be like Firefox and not Chrome.

[**@zadjii-msft**](https://github.com/zadjii-msft) commented on [May 7, 2019, 12:56 PM EDT](https://github.com/microsoft/Terminal/issues/444#issuecomment-490162811 "2019-05-07T16:56:10Z - Replied by Github Reply Comments"):
> So there's a LOT of different opinions about how tabs should be sized. I'm not even going to open that can of worms here.

Might be better suited as a separate issue, but since it came up in here, what about a setting for minimum tab width instead of forcing either "scrolling after min-width" or "no min-width, no scroll" tabs:
![](https://i.imgur.com/UYtiZE3.png)
If disabled, it would be chrome-like with tabs getting ever smaller, and if enabled, then you can define the min-width you want before it starts scrolling.

**Comment by matthew4850** [comment]
@Californ1a yeah, that sounds like a good solution.

**Comment by zadjii-msft** [comment]
@Californ1a Let's open a separate issue for discussion of tab sizing. I'd rather each issue discussed an atomic topic, in this case, scrolling the tabs without a touchscreen.

**Comment by pavlkara1** [comment]
> Ah, I was using my surfaces trackpad

I rebuilt it and deployed it again and it works 😉
