### ISSUE TITLE
Settings menu doesn't open anything

### ISSUE THREAD

**Issue by correcthorsebatterystaple** [microsoft/terminal#4486]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

1. Install Windows Terminal (Preview) from Microsoft store
2. Open Terminal
3. Click the down caret on the top bar
4. Click on settings
# Expected behavior

A settings menu pops up
# Actual behavior

The cursor goes into loading for a while and then returns to normal with no menu or GUI opening or anything else to change the settings.

**Comment by j4james** [comment]
There isn't a UI for the settings yet - that's issue #1564. However, the settings menu should open the _profiles.json_ file (which contains the settings) in whatever editor you have associated with json files. If it's not doing anything, you'll probably need to reset that file type in your Windows settings.

**Comment by zadjii-msft** [comment]
For the record, when you _don't_ have a `.json` editor set by default, the system is doing _something_. It's trying to figure out what your `.json` editor is. Once it _eventually_ determines that there isn't one, it'll pop this dialog
![image](https://user-images.githubusercontent.com/18356694/74043084-5fd1f380-498e-11ea-87ae-336248ab2c4a.png)

The real problem here is that there's a pretty substantial delay between clicking the settings button and that dialog opening. I'm not sure how much we can really do about this. The easy workaround is just to make sure to set some application as the default editor for `.json` files, until #1564 lands.

This is also some combination of #1422 #1586 #2599 #2895 #2036 #1928 #1786 #1704 #1460 #1664 #3592 #3244 #3240 #2969
