### ISSUE TITLE
cmd.exe "START" cannot find file since upgrade to 1903

### ISSUE THREAD

**Issue by LRiba** [microsoft/terminal#4488]
I just upgraded my Windows 10 Pro system to 1903 (build 18362.356) and began experiencing a similar problem to [#271](https://github.com/microsoft/terminal/issues/271), which was reported in 1809.
_(The description of duplicate issue [#345](https://github.com/microsoft/terminal/issues/345) is closer to what I'm seeing)._

I have a batch file containing multiple commands executed as
`START "" /MIN /I /D ...`
Since the upgrade, they all now return
> The system cannot find the file ...

Removing the `/MIN` does **not** resolve the problem.

#271 was fixed in KB4501371 for 1809; is there an update for 1903 with a similar fix?

# Environment
Microsoft Windows [Version 10.0.18362.356]
### Previous Environment
1803 (build 17134.1246)

**Comment by DHowett-MSFT** [comment]
Sorry for the delay. Are you seeing the problem in _1809_ with KB4501371? I'd like to figure out if we broke this between the code we serviced to 1809 and 1903.

**Comment by LRiba** [comment]
This system never had 1809, corporate updates went directly from 1803 to 1903.
System has since updated from build 18362.356 to 18362,657, and is still expieriencing this problem.
Could/should I try installing KB4501371 anyway?

**Comment by DHowett-MSFT** [comment]
KB4501371 will not help, unfortunately. We'll take up the investigation on our side.

**Comment by zadjii-msft** [comment]
Sorry to be that guy, but @LRiba - is this still happening for you? I'm mot sure we ever made any code changes on our side to address this, but there also shouldn't be any `cmd.exe` changes at all, so it's a little troubling that this regressed in the first place. 

It's been a few months, so it's entirely possible this has been fixed in the meantime. If this is still happening, we'll take another look. 

Thanks!
