### ISSUE TITLE
Settings doesn't open reliably when there's no notepad.exe

### ISSUE THREAD

**Issue by bernstein82** [microsoft/terminal#4502]
Hi

I know there have been similar issues reported, like #1460 with solution #1841.

But i would like to raise this again, as it seems that :
- when there is no notepad.exe (can be removed officially in next windows release) 
- and no editor associated with .json files

open settings seems totally broken, with absolutely no clue what's wrong.

I for one falsely assumed for months, that the settings functionality just hasn't been implemented yet (as it's still a preview)...

thanks

# Environment
Microsoft Windows [Version 10.0.18363.592]

# Steps to reproduce
- remove notepad.exe
- disassociate any editor from .json files
- open settings in windows terminal

# Expected behavior
settings are shown, or until #1564 is resolved, a simple popup with a path to the settings.json

# Actual behavior
absolutely fantastically nothing

**Comment by zadjii-msft** [comment]
For the record, when you _don't_ have a `.json` editor set by default, the system is doing _something_. It's trying to figure out what your `.json` editor is. Once it _eventually_ determines that there isn't one, it'll pop this dialog
![image](https://user-images.githubusercontent.com/18356694/74043084-5fd1f380-498e-11ea-87ae-336248ab2c4a.png)

The real problem here is that there's a pretty substantial delay between clicking the settings button and that dialog opening. I'm not sure how much we can really do about this. The easy workaround is just to make sure to set some application as the default editor for `.json` files, until #1564 lands.

This is also /dup #4486

**Comment by bernstein82** [comment]
> For the record, when you _don't_ have a `.json` editor set by default, the system is doing _something_. It's trying to figure out what your `.json` editor is. Once it _eventually_ determines that there isn't one, it'll pop this dialog
> ![image](https://user-images.githubusercontent.com/18356694/74043084-5fd1f380-498e-11ea-87ae-336248ab2c4a.png)
how nice of you for not reading my issue and  dismiss it by claiming false information. 
**i filed this issue _exactly_ to point out that, that menu you so nicely screenshot'ed does not appear.**
and no it doesn't appear late, even after 5 minutes...

also very nice to say to close this a duplicate of #4486 and then closing that one too.
