### ISSUE TITLE
Add function to get a console file handle from a ConPTY handle.

### ISSUE THREAD

**Issue by grubba** [microsoft/terminal#4622]
# Description of the new feature/enhancement

Currently the only way to get to the client side of a ConPTY is to spawn off a new process.
Adding a way to get a client side file handle would have uses like:

* Simplifying testing of pty handling code by not having to have a separate process for the simulated client.
* Used to inhibit a ConPTY terminating early (ie before all process intended to use it have been started).
* Used to probe whether a ConPTY is still alive.
* Use as a second ConPTY for stderr for a subprocess when stdin and stdout are on another ConPTY.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
I'm going to leave this one on the triage queue until I can chat with my engineers about it. On the face of it, I'm not sure if those use cases are enough to justify the work, and I'd be concerned about allowing a pty host to _also be a client_ because it would allow that host to do an end run around the PTY API and read the console output buffer and generally do things we're actively trying to get people to _not do_.

Using a separate pty for stderr is interesting, though.

For the rest, I'd much prefer better APIs around pseudoconsole management (and perhaps actually fixing the client termination bug.)
