### ISSUE TITLE
Detatched command input line

### ISSUE THREAD

**Issue by undeadfish** [microsoft/terminal#4634]
# Description of the new feature/enhancement
A way to have a detatched input line that can either float freely or be docked to the window. 

Input from this window will not be sent to the command window until the return/enter key is pressed. Multiple lines can be queued in this command line by either using shift+enter or ctrl+enter (whichever is the preferred standard).

This would be useful for those few of us that still use raw telnet to connect to MUD/MUX/MOO games. In addition I can imagine scenarios for certain applications where being able to have a more robust window to preview your command before sending it to the actual command window could be beneficial.

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment]
@undeadfish as a fellow MUD player, I totally appreciate the feature request! Thanks!

Unfortunately, I don't think it's tenable for Terminal to implement since we couldn't do it well enough to do justice to every CLI application. At the end of the day, we're just exchanging streams of text with another application--we can't know when the application is requesting user input, and we can't really know when that application wants to take user input and do something fun like syntax highlighting or automatic text insertion or even tab completion.

The windows console host made a huge mistake 30-odd years ago by offering something very similar to this (at least, architecturally). The console host stores the input line and dispatches it to an application when the application asks. Because an app needs to bend over backwards to get the data out of our buffer before we send it, we've been fighting that legacy for as long as my team has existed. :smile:

I'd rather not do it than do it poorly, y'know?

**Comment by undeadfish** [comment]
Makes sense. It was worth a shot.

Love the new terminal otherwise. Keep up the good work!
