### ISSUE TITLE
Add C# and F# Interactive Profile Generators

### ISSUE THREAD

**Issue by deoradh** [microsoft/terminal#4667]
# Description of the new feature/enhancement

Related to #3821, also add support for the C# and F# interactive prompts which are shipped with VS.

# Proposed technical implementation details (optional)

I use something similar to this for my profiles:

{
            "commandline": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\Bin\\Roslyn\\csi.exe",
            "name": "C#",
            "tabTitle": "C#"
}, {
            "commandline": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsi.exe",
            "name": "F#",
            "tabTitle": "F#"
}

**Comment by DHowett-MSFT** [comment]
Thanks for the request! I've been redirecting requests for additional dynamic shells to /dup #2303, because that'll allow _those applications_ to register their shells too. Terminal's only going to autodetect a scant few of them, and I'd like to keep that list small to avoid making users upset that we keep running roughshod over their profiles list :smile:
