### ISSUE TITLE
Is there an installation package you can download?

### ISSUE THREAD

**Issue by 516025** [microsoft/Terminal#468]
I just want to use it, but I can't build it, so can I download the installation package?

**Comment by DimitriLambrou** [comment]
There is no installation package, you need to set everything up yourself https://github.com/microsoft/Terminal#building-the-code

**Comment by Tlaster** [comment]
I've built a release package and it's only x64 version
NOTE: it's a UWP application so make sure your system version is above 1809 (I'm using 1903)
https://1drv.ms/u/s!Aj53J0r2UND0kf1rweVP1nIbgERsqw

**Comment by Larsklopstra** [comment]
@Tlaster Hmmm, I added the certificate and tried to launch the installer but got a message saying:

> Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)

**Comment by 516025** [comment]
@Tlaster thanks
> I've built a release package and it's only x64 version
> NOTE: it's a UWP application so make sure your system version is above 1809 (I'm using 1903)
> https://1drv.ms/u/s!Aj53J0r2UND0kf1rweVP1nIbgERsqw

**Comment by ictw** [comment]
> I've built a release package and it's only x64 version
> NOTE: it's a UWP application so make sure your system version is above 1809 (I'm using 1903)
> https://1drv.ms/u/s!Aj53J0r2UND0kf1rweVP1nIbgERsqw

I use your package,but it arised an error:"**App installation failed, error message: Windows cannot install the package because it is Microsoft.WindowsTerminal_1.0.0.0_x64__8wekyb3d8bbwe incompatible with the device. The package requires the Windows.Universal device family to run operating system versions 10, 0, 18362, 0, or later. The operating system version of the device is currently running 10, 0, 17763, 475. (0x80073cfd)**" and my windows version is the lastest **1809**(OS 17763.475 ), how should I do?

**Comment by YantCaccia** [comment]
> I've built a release package and it's only x64 version
> NOTE: it's a UWP application so make sure your system version is above 1809 (I'm using 1903)
> https://1drv.ms/u/s!Aj53J0r2UND0kf1rweVP1nIbgERsqw
> 
> I use your package,but it arised an error:"App installation failed, error message: Windows cannot install the package because it is Microsoft.WindowsTerminal_1.0.0.0_x64__8wekyb3d8bbwe incompatible with the device. The package requires the Windows.Universal device family to run operating system versions 10, 0, 18362, 0, or later. The operating system version of the device is currently running 10, 0, 17763, 475. (0x80073cfd)" and my windows version is the lastest 1809(OS 17763.475 ), how should I do?

You should opt-in in Windows Insider, download and install the update 18362.30 (for me it took about 1 hour) and eventually try again installing this package, it should work then.

**Comment by DHowett-MSFT** [comment]
Hi @Tlaster,
Thanks for being so excited to jump in. Please don't use this issue tracker for distributing binaries. :smile:

**Comment by zadjii-msft** [comment]
I'm gonna use this as the catch-all issue for this topic.

### There are no binaries to download quite yet. 

The Windows Terminal is in the _very early_ alpha stage, and not ready for the general public quite yet. If you want to jump in early, you can try building it yourself from source. 

Otherwise, you'll need to wait until Mid-June for an official preview build to drop.

**Comment by bertyhell** [comment]
There is a package now:
https://github.com/microsoft/terminal/releases

When you look under the assets of each release:
![image](https://user-images.githubusercontent.com/1710840/62629472-7b036e00-b92d-11e9-97ef-d86e17774e21.png)
