### ISSUE TITLE
Customizable/Shortened cwd path in prompt for windows shells

### ISSUE THREAD

**Issue by cbrit** [microsoft/terminal#4687]
# Description of the new feature/enhancement
I expect this is either implemented or requested already, but I can't find it so here goes.

Basically it would be nice to alter the appearance of the current working directory in my prompt to be shorter. For example `~\src>`, or even just `src>` (current folder only) instead of `C:\Users\Name\src>`. I am usually working in a project directory that is 5-6 directories deep which means the prompt takes up half of my pane if I'm doing split screen. 

I am aware that the original cmd.exe has some options for changing the prompt but it is no where near as flexible as bash-style prompt alterations.

# Proposed technical implementation details (optional)

I don't know the technical requirements for this kind of change for Windows but I wanted to at least suggest it.

Apologies if this is already something that has been posted about.

**Comment by DHowett-MSFT** [comment]
So! First- we're not going to change CMD, so I'm sorry about that.

Second, however: PowerShell can absolutely do this, and I highly recommend looking into it. You can customize your prompt by overriding the `Prompt` function, and you can make it do whatever you want.

Since this is more of a question, I'm gonna close it as answered.
Sorry about that!
