### ISSUE TITLE
Transparent window or Upcoming windows versions

### ISSUE THREAD

**Issue by bhanukaranaweera** [microsoft/terminal#4742]
**Problem**: when we are working with PC or Laptop (only primary screen and

 no other screens). Its very hard to work with two windows in same time simultaneously , Even if we have open some tabs in side by side ( cascade windows )
<Opening cascade windows reduce the efficiency of work and it does not display full interface of application>

Example :
if I work with Microsoft word. Then I want to refer some pdf. I have few option.
1. Minimize current working window and open required software ( pdf reader ) .
2. Use cascade windows. ( if we use this technique, The efficiency becomes less and since the
screen size is limited all area cannot be achieved )

**Solution**: to overcome this problem I suggest transparent windows . ( Windows Service or Feature )
**How Its works**

When we want that feature, We can activate through windows notification center. Then that feature will be activated. 
After that by pressing a special key ( as example alt key ) long time the window that has in maximize mode is starts to transparent ( Like a glass, We can see through it the minimized windows ). Then we can work on that window ( The newly opened minimized window or application interface ). 

All minimized windows are displayed   as small icon some corner of display. if we want to select some particular window  we can use special key with number  ( alt key + number ).

When we want to come back to the current working window by pressing the special key ( Short pressing ) it comes automatically.

The concept has uploaded as pdf file here
[Transparent window or Upcoming windows versions.pdf](https://github.com/microsoft/terminal/files/4267947/Transparent.window.or.Upcoming.windows.versions.pdf)

**Comment by zadjii-msft** [comment]
1. This is primarily the repo for just the Windows Terminal application, not all of Windows. I'm actually not sure where the best place to put Windows feature requests is - probably the Feedback Hub? Actually this might fit in over in the [microsoft/powertoys](https://github.com/microsoft/powertoys) repo
2. (Even though this thread is off topic for this repo) - I'm not sure why this is needed as an alternative to just <kbd>Alt+Tab</kbd>'ing between active windows. That's been the traditional Windows workflow for this kind of scenario (multi-tasking between two full-screen apps) since _I've been born_.

**Comment by bhanukaranaweera** [comment]
here i have mentioned its a transparent. Then we can see through the current working window.
here the same problem i have experienced,
 If we code something by looking at some reference code as i mentioned in the issue, its very hard . 
So i think if we have something like this would helps to everyone.
