### ISSUE TITLE
Investigate Acrylic in titlebar / not using a `HRGN` for the titlebar

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#4744]
# Description of the new feature/enhancement

The title says it all.
This is another really good thing that Windows Terminal could borrow from [felixse/FluentTerminal](https://github.com/felixse/FluentTerminal).
This would basically expand the current terminal's background (including all the modifications done to it, for example a custom background image or opacity level) over to the titlebar (including the minimize, maximize and close icons). 
This would make it consistent with other Windows apps following Fluent Design (think of the Settings app and its titlebar), apart from making it look really cool.
Attached here is a screenshot of Fluent Terminal (with acrylic blur and without any background image):

![Screenshot (145)](https://user-images.githubusercontent.com/46838874/75578659-3aff0680-5a8a-11ea-9c5a-3b8a612321ba.png)

# Proposed technical implementation details (optional)

While digging for similar requests (I couldn't find an issue that addressed this specifically), I read somewhere that such a thing isn't possible given the architecture. Well, if that's the case, too bad. But I'm still opening the issue so that this remains documented somewhere separately.

**Comment by zadjii-msft** [comment]
This is actually something that's already discussed in #1375, the megathread that probably mentioned
>  The title bar isn't acrylic, sorry, that one probably can't happen given our architecture

We'd _love_ to make the titlebar acrylic like this, but give the platform limitations, this unfortunately won't be possible.

There's also #3327, which as a part of that thread is tracking changing the titlebar background to match the terminal control. This includes issues #3774, #702, which are both pretty similar.

I'm going to mark this as 
/dup #702, #3774, #3327

Thanks!

**Comment by greg904** [comment]
@zadjii-msft I think I found a way to make the title bar acrylic and still allow the window to be moved with the drag bar. I posted it here: https://github.com/microsoft/terminal/issues/2100#issuecomment-587641240:
> replace the SetWindowRgn trickery by a completely transparent, invisible window that we put on top of the drag bar and that catches all of the mouse events

I didn't try applying that solution to the terminal yet but I tried prototyping a solution on a repo on my GitHub and it seems to work: https://github.com/greg904/LearnXamlIslands (if ever you look at it, ignore the `_top_border_window` and the big space at the top of the window, it's because I'm also using that repo to prototype other things).

GIF of a prototype with the idea above implemented (again, ignore the big space at the top):
![test](https://user-images.githubusercontent.com/56923875/75585707-fd42b380-5a72-11ea-83b9-d7678c18eda4.gif)


So I think it is possible to do it.

**Comment by rashil2000** [comment]
Hey @zadjii-msft, would you mind reopening this to take @greg904's work into consideration?

**Comment by zadjii-msft** [comment]
Woah okay that's incredible. I've been a little MIA for the last month so I missed that comment. I'd love to see if that would work! I'm trying to remember a far off, long ago conversation we had with someone on the input team that said this might not work in all scenarios. Something about the "move-size" loop was said. 

If you can get that working without the standard titlebar / working in the Terminal, I'd certainly be stoked. I guess I'll use this issue to track that investigation. If that pans out, we could probably just close #2100. If this doesn't work out, then we'll still need a solution to #2100 before we ship 1.0.

**Comment by DHowett-MSFT** [comment]
@greg904 I am in love with this idea. Sorry I didn't say that on your other titlebar PR. :smile:
