### ISSUE TITLE
After pasting, Ctrl+z deletes character by character instead of undoing the whole string

### ISSUE THREAD

**Issue by alexhinz** [microsoft/terminal#4745]
# Environment
Windows build number: 10.0.19569.1000
Windows Terminal version: 0.9.433.0

# Steps to reproduce

1. Copy some text to clipboard from any source (Terminal, Notepad, browser, etc.), e.g. "hello world"
2. Open a Windows PowerShell tab or PowerShell Core tab in Terminal.
3. Paste the text by any usual means: right click, Ctrl+Shift+v, Ctrl+v (if configured in settings json).
3. Press Ctrl+z. Observe, repeat.

# Expected behavior

With a single Ctrl+z press, the whole "hello world" string should be deleted. This behavior matches PowerShell when not running inside Terminal.

# Actual behavior

Each press of Ctrl+z deletes a single letter/character, as if by pressing Backspace.

In contrast, I see that if I use the up/down arrows to insert strings of text, Ctrl+z correctly deletes the whole string, which matches the behavior of PowerShell outside of Terminal.

My PSReadline version is 2.0.0, according to `Get-Module PSReadline`.

**Comment by DHowett-MSFT** [comment]
Unfortunately, this is because PSReadline is handling `^V` itself in the traditional console case. When Terminal handles it, it inputs the pasted string a single character at a time like all other terminals.

This will be fixed when we have bracketed paste mode[1] and PSReadline supports asking for it.

/dup #395

[1]: "Bracketed paste" is a terminal feature whereby a terminal can say "I am beginning/ending a paste" so that a remote shell can do the right thing with user-pasted content that it received char-by-char.
