### ISSUE TITLE
 Platform='ARM64' build failed.

### ISSUE THREAD

**Issue by CanoeFZH** [microsoft/Terminal#477]
Build FAILED.

"D:\Terminal\OpenConsole.sln" (default target) (1) ->
"D:\Terminal\src\host\exe\Host.EXE.vcxproj.metaproj" (default target) (2) ->
"D:\Terminal\src\buffer\out\lib\bufferout.vcxproj" (default target) (3) ->
(InvalidPlatformError target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.InvalidPlatform.Targets(22,7): error MSB8007: The Platform for project 'bufferout.vcxproj' is invalid.  Platform='ARM64'. You may be
 seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [D:\Terminal\src\buffer\out\lib\bufferout.vcxproj]

**Comment by aar0nz** [comment]
This works for me:
msbuild openconsole.sln /p:Platform=x64

**Comment by CanoeFZH** [comment]
> This works for me:
> msbuild openconsole.sln /p:Platform=x64

Great! It works:)

**Comment by csy19960309** [comment]
> This works for me:
> msbuild openconsole.sln /p:Platform=x64

nice work homie

**Comment by audac1ty** [comment]
Compiling for me now, would it be worth documenting this to make building a little easier?

**Comment by aar0nz** [comment]
[https://github.com/microsoft/Terminal/tree/master/tools](url)

I'm building it with the bcz tools now, please check the README file in /tools

**Comment by bleedingpixels** [comment]
not sure why arm64 is the default

**Comment by bef178** [comment]
> not sure why arm64 is the default

It is Visual Studio. The default platform is selected by alphabet order. Add an .suo will fix that. However, .suo file should not be committed into repo.

**Comment by dwjorgeb** [comment]
I'm having this error now: 

The OutputPath property is not set for project 'TerminalConnection.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [(...)\Terminal\src\cascadia\Termi
nalConnection\TerminalConnection.vcxproj]

**Comment by zadjii-msft** [comment]
@dwjorgeb I'd refer you to #489 for issues building.

Since this thread is about building for ARM64, and that's been answered, I'm going to close this issue

**Comment by NetherGranite** [comment]
> This works for me:
> msbuild openconsole.sln /p:Platform=x64

How did you actually run it once you built it?
