### ISSUE TITLE
Visual artefacts in splitted window

### ISSUE THREAD

**Issue by e-Dark** [microsoft/terminal#4771]
# Environment
Windows build number: Microsoft Windows [Version 10.0.18363.657]
Windows Terminal version (if applicable): 0.9.433.0

# Steps to reproduce

1. Open Windows Terminal with any config CMD/Powershell/Ubuntu
2. Fill all visible window with some longline text - ex:. ls, dir, cat smth
![image](https://user-images.githubusercontent.com/61321141/75669207-b2e84f00-5c8b-11ea-9a41-00d3d7e4f330.png)
3. Split horizontal
![image](https://user-images.githubusercontent.com/61321141/75669267-d14e4a80-5c8b-11ea-9169-f818143c21ba.png)
4. Focus to the first pane.
5. Output smth short - ex.: ps
![image](https://user-images.githubusercontent.com/61321141/75669358-f9d64480-5c8b-11ea-8940-4ec0cbf5e6e6.png)
6. View artefacts!

**Comment by zadjii-msft** [comment]
This is _similar_ to the bug in #2432, but it's definitely not the same. #2432 is caused by PsReadline acting weirdly, but this has more to do with us not saving the viewport position correctly. It's actually probably the same root cause as #3490, which is in PR in #4741. I could have sworn there was an actual specific dupe for this bug, but there isn't anything in #4200 so I doubt it.

I'm going to leave this open to make sure that #4741 actually fixes this bug as well. Thanks!

**Comment by zadjii-msft** [comment]
Just checked this out in `dev/migrie/f/reflow-buffer-on-resize`, my branch for #4741, and that PR definitely also fixes this bug.
