### ISSUE TITLE
Add support for fcntl and ioctl

### ISSUE THREAD

**Issue by SR-Lut3t1um** [microsoft/terminal#4801]
# Description of the new feature/enhancement

As Linux terminals support those features I think it would add a lot to the terminal, if these features would be implemented

**Comment by DHowett-MSFT** [comment]
Sorry, because `ioctl` and `fcntl` are API multiplexing APIs (that take action codes and do things with them) what you’re asking for pretty much amounts to “add some APIs for terminals.” We’ve already got a whole bunch of APIs.

If you’d be willing to describe the specific things you’re looking for, I’d be happy to listen.
