### ISSUE TITLE
Launch WSL terminals directly in Windows Terminal

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#4876]
# Description of the new feature/enhancement

After installing a distro, install a terminal such as Konsole, xterm, xfce4-terminal, etc.  and configuring/installing an X server such as VcxSrv, when launching the terminal it does not appear in Windows terminal. By launching a new tab in WT if launched from WT, we can provide a unified experience. Git bash can be used in WT so getting Linux terminals used in WT is the next step.

# Proposed technical implementation details (optional)

I want to launch a Linux terminal from WSL and have it open in WT as a new tab. Furthermore, it should appear as a drop-down in the menu similar to Pengwin creating entries in the Windows start menu for Linux applications.

**Comment by DHowett-MSFT** [comment]
I think there's a terrible misunderstanding going on here -- we're _not_ going to make it so that if you launch _another entire terminal_ (Konsole, xterm, xfce4-terminal, etc.) that Windows Terminal takes over your wishes. Can you imagine? That'd be like VSCode taking over Notepad invocations.

Any application that can launch `konsole` can launch `wt.exe`. This will, or should, work today.

If you want it to appear in a new tab in the same window, you want to follow #4472.

**Comment by WSLUser** [comment]
Basically when I'm in my distro and launch a terminal app, I want it to appear in a new tab.  I'm not sure that issue will be able to address it (at least not in the context of the OP) but the general idea matches.

**Comment by DHowett-MSFT** [comment]
It absolutely will, because on the WSL side you can set your _terminal application_ to be "wt.exe whatever launch in a new tab". It's up to you and the configuration of your WSL distribution as to _how exactly_ it launches a terminal, but when you **explicitly** say "konsole" or "gnome-terminal" you are **explicitly** saying that you want to use Konsole or gnome-terminal, not WT.
