### ISSUE TITLE
Windows Terminal to have folder management to manage sessions please

### ISSUE THREAD

**Issue by iamgavin** [microsoft/terminal#4880]
# Description of the new feature/enhancement

Would like to see Windows Terminal to have folder management feature. I have lots of sessions that folder management is necessary for me to organize them.

Thank you.

**Comment by zadjii-msft** [comment]
I'm sorry, could you elaborate more? I'm not exactly sure what you're asking for. 

Maybe you're thinking of something like what's described in this: https://github.com/microsoft/terminal/issues/1571#issuecomment-519504048 ?

**Comment by maubertin** [comment]
Hello team,

First of all, let me congratulate you for this amazing product. 

I face the same issue, so may i can explain.

Currently, we can store remote ssh session using profil customisation. 
For exemple:
...
   ],
    "SSH": [
      {
        "name": "SSH Jenkins Scaleway",
        "commandline": "ssh -L 44400:localhost:44400 maubertin@jenkins.XXXX.io",
        "hidden": false,
        "backgroundImage": "ms-appdata:///roaming/fond_term3.gif",
        "backgroundImageOpacity": 0.8,
        "backgroundImageStrechMode": "fill"
      }
    ],
...

However, because of number of session we could face, it isrequired to organize it using sub-menu of sub-folder. 

This new fetaure would be great.

Best regards,

**Comment by DHowett-MSFT** [comment]
Good find! Thanks for following up 😄 

/dup #1571
