### ISSUE TITLE
Rename To "Terminal"

### ISSUE THREAD

**Issue by diligamer** [microsoft/terminal#4881]
# Description of the new feature/enhancement
"Renaming The "Windows Terminal" To "Terminal"

# Why?
All The Apps In The Store By Microsoft Have No "Microsoft" or "Windows" Prefix. Terminal Should Follow that.

**Comment by diligamer** [comment]
@microsoft/terminal, Why The Inactivity?

**Comment by zadjii-msft** [comment]
> Why The Inactivity?

Because our team is located in the US, and this issue was posted in the middle of the night for us. Even now, it's only 6am for 86% of the team 😆 

> "Renaming The "Windows Terminal" To "Terminal"

We actually had a bunch of meetings with the marketing and branding teams to help us decide on a name for the application. Since there's already Terminal.app onOSX, which is pretty universally just known as "Terminal", we couldn't use that. So "Windows Terminal" was the unanimous choice of everyone in the room.
