### ISSUE TITLE
Shouldn't help ( -h or --help) print to the console? 

### ISSUE THREAD

**Issue by MonkeyNinja** [microsoft/terminal#4887]
Not open a dialog...seems strange

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment]
Oh it absolutely _should_, but shockingly, that's impossibly -.-

For reference, I'll refer you to [this section](https://github.com/microsoft/terminal/blob/master/doc/specs/%23607%20-%20Commandline%20Arguments%20for%20the%20Windows%20Terminal.md#subsystemwindows-or-subsystemconsole) in the spec for commandline arguments. 

the **TL;DR** is that there are two types of executables on Windows: Windowed apps, and Console apps. 
1. A console app _always_ needs a console, so if you were to launch `wt` from any context _without_ a console (explorer, start menu, run dialog), then a console window will always be created for it.
2. A Windows app can request a console is made for it, and can request to attache to it's parent console, but shells like `cmd` and `powershell` will have already continued running, because they don't wait for Windowed apps to complete before they return to the prompts.

Option 1 is bad, because we don't want _another_ vintage console window appearing every time the Terminal is launched.

Option 2 is bad, because we can't print to the console before powershell or cmd has started printing again. Our output would get all mixed up with theirs.

So we opted for Option 3, which is to display a message box. This is at least an established pattern on Windows. In the meantime, we'll also be pushing on our side to try and make this better, because obviously this situation is not great.
