### ISSUE TITLE
Open Docker terminal from Terminal

### ISSUE THREAD

**Issue by jmsnavarro** [microsoft/terminal#4892]
# Open a Docker-hosted terminal directly using Windows Terminal
- Possibility to add a terminal profile hosted in Docker as part of the Windows Terminal profiles.
- This allows the user to instantly launch a terminal session hosted by Docker (provided that there is an already active container)

# Proposed technical implementation details
```
"profiles":
    [
        {
            "guid": "{5743275e-4f2q-5b06-ad1e-a6969a402336}",
            "hidden": false,
            "name": "Ubuntu 18.04 LTS over Docker",
            "source": "Docker.Container.Ubuntu.trusted-twister",
            "fontFace" : "Cascadia Code",
            "fontSize" : 10,
            "acrylicOpacity" : 1,
            "useAcrylic" : false	
        },
```

**Comment by DHowett-MSFT** [comment]
You’d be better served by just adding a new profile whose commandline is “docker exec -t -i container /process". Even if terminal randomly guessed what shell you wanted inside a random container, it wouldn’t be very reliable and people would hate the autogenerating profiles for each one :smile:

You know your containers a lot better than we ever could!

**Comment by DHowett-MSFT** [comment]
Thanks, however, for the request!

**Comment by jnovick** [comment]
@jmsnavarro I have a script in my Ubuntu WSL distro for generating these profiles. I created it as an experiment. I am not sure what the practical purpose of wanting these profiles is, but you could copy and edit this t accomplish what you want. If you do not have `jq` installed, you can install it via `sudo apt-get install -y jq`. This also relies on the fact that there are no comments in the `settings.json` since `jq` cannot handle them.

``` bash
VALUE=$(docker ps --format '{{ json . }}' | jq '{"name": ("Docker " + .Names + " " + .Image), "guid": ("{0974efce-f787-4a0a-8468-"+.ID+"}"), "hidden": false, "commandline": ("docker exec -it " + .Names + " /bin/bash")}' | jq -s .)
cat /mnt/c/Users/Joshua/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json \
  | jq '.profiles.list=([.profiles.list[] | select(.name | contains("Docker") | not)] + '$VALUE')' \
  > /mnt/c/Users/Joshua/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json
```

Once <https://github.com/microsoft/terminal/pull/7584>/<https://github.com/microsoft/terminal/pull/7632> is done, you could leave comments in place and just direct the first line into a file instead of a variable.
