### ISSUE TITLE
Crash in Windows Terminal TerminalControl!TextBuffer::Reflow

### ISSUE THREAD

**Issue by Treit** [microsoft/terminal#4907]
While running a stress test on Windows Terminal version 0.10.721.0, I was able to cause a crash in TerminalControl!TextBuffer::Reflow.

I was running https://github.com/Treit/TerminalStress, the application I wrote some time back to reproduce a different bug (that was since fixed.)

I was running something like 5 instances in parallel in different panes on the same tab, then rapidly pressing Alt+Enter to switch from full screen to normal and back.

[WindowsTerminal11.txt](https://github.com/microsoft/terminal/files/4331632/WindowsTerminal11.txt)

I have attached some additional output from the debugger that might be helpful.

**Comment by DHowett-MSFT** [comment]
Finger-in-the-air guess is P3: if this only reproduces when you're murdering your terminal by resizing it multiple times a second while printing megabytes of output, I'm going to cay it won't strike too many people too often.

It's still worth fixing.

**Comment by DHowett-MSFT** [comment]
I can't repro this on v0.11.1212, even resizing like mad with five open panes printing our 6MB test file simultaneously.

I'm gonna call this one no-repro. @Treit please let me know if you can still repro!

**Comment by Treit** [comment]
> I can't repro this on v0.11.1212, even resizing like mad with five open panes printing our 6MB test file simultaneously.
> 
> I'm gonna call this one no-repro. @Treit please let me know if you can still repro!

@DHowett-MSFT  Yes I can still reproduce it on 0.11.1212.0

**Comment by Treit** [comment]
@DHowett-MSFT here is a brief video I just made demonstrating how I reproduced the issue on 0.11.1212.0:
https://1drv.ms/v/s!Alav93a0o3vchOwF91dG-jJ5He1g0w?e=2Lm59k

**Comment by DHowett-MSFT** [comment]
Perfect. Thank you.

**Comment by DHowett-MSFT** [comment]
The problem is, as always, double-width characters. Somehow, the source buffer (during the reflow operation) is getting a hanging DBCS Trailing character that we dutifully try to reflect into the new buffer.

**Comment by kasper93** [comment]
> Would you share some of the glyphs that are in your powerlevel10k theme?
> 
> I'll mark this as a /dup of #4907 in the meantime -- same call stack, same symptoms, same repro (go wild on resizing with garb in the buffer)

@DHowett-MSFT Since the other issue has been closed I replying here. 

For me the problems started with https://github.com/microsoft/terminal/commit/7ae34336da0be8428738df5e13dfc4c5f1df6f75 probably because ✔ has been wide. 

To summarize my problems:
1. tmux drawing is broken. I needed to select pane to redraw vertical separator. Tick mark draw over separator. Also when resizing it glitches visually. https://streamable.com/xwrs5z
2. WT crashes https://streamable.com/xwrs5z It is very easy to reproduce in tmux, I did reproduce it also without, but it is harder. (watch after 27s, before I tried not to crash it, also I cut video before window closed, but it crashed in the end, you can see it is not responding anymore) 
3. Changing this tick mark to wide (or smth else) made it mess up really bad when resizing. After 7ae34336da0be8428738df5e13dfc4c5f1df6f75: https://streamable.com/2wanng and before 7ae34336da0be8428738df5e13dfc4c5f1df6f75: https://streamable.com/rd2a8v

I initially though that crashes and other issues are related, but while they are introduced by the same commit for me, it looks like they are separate problems. We might reopen my issue for drawing problems and discuss crash in this one.

**Comment by DHowett** [comment]
So @kasper93, we fixed the width of ✔ at least! This bug'll remain to track the resizing issue :smile:

**Comment by o-sdn-o** [comment]
This issue can be instantly reproduced as follows:
1. `ssh vtm@netxs.online` (using any profile, PowerShell or WSL)
2. Resize the terminal window quickly and intensively

My environment:
```
Microsoft Windows [Version 10.0.19042.844]
Windows Terminal version: compiled from `main`
```

![image](https://user-images.githubusercontent.com/11535558/112718464-0079ce80-8f15-11eb-9f34-1f050e76d099.png)

**Comment by DHowett** [comment]
Fixing as part of MSFT-17364373, which is a conhost crash that hits moderately often (~500 hits in the past 14 days!)
