### ISSUE TITLE
Need a way to run a startup script

### ISSUE THREAD

**Issue by randomascii** [microsoft/terminal#4916]
All shells have some way to run a startup script in order to configure the environment. I don't recall how it works on Linux but the Windows command prompt has /k

The new terminal cannot be taken seriously without this feature. Many other features (setting the starting directory) become unnecessary once you have this feature.

All that is needed is an entry in the settings .json file to specify a startup script.

**Comment by DHowett-MSFT** [comment]
Thanks for the request!

The new terminal doesn’t control what you launch inside it; you can set the commandline of any profile to `cmd /k script.cmd`, `powershell -noexit -c whatever.ps1`, or anything else that will launch your preferred shell with your preferred arguments. 

Since Terminal doesn’t _replace_ CMD hut rather supplements it, and it’s the shell’s job to mediate what happens after you launch it, I’m going to close this one out as Question/Answered.
