### ISSUE TITLE
Please add support closePaneRight/Left/Up/Down

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/terminal#4941]
# Description of the new feature/enhancement
I want to look for a way to close eg right pane and bind it to a hot key.
Currently, to close eg right pane, I need move focus to right pane first. Then close it.

# Proposed technical implementation details (optional)

Please add support closePaneRight/Left/Up/Down.
Then people can bind it to a hot key

Thanks.

**Comment by zadjii-msft** [comment]
Okay I like the idea, but what happens when someone's got something like the following:
```
[ A | B | C ]
```

What happens when they `closeRight` from pane A? Or the even more complicated `[ A | B | C | D ]`? What happens when the nesting gets ridiculous like
![image](https://user-images.githubusercontent.com/18356694/76797567-d509c300-679b-11ea-91e2-abe49b577995.png)

**Comment by 9527KGG** [comment]
If "multi command binding" is supported, that would be even better.

**Comment by zadjii-msft** [comment]
Ah okay. What you _really_ want is tracked over here, in #3992. Thanks for helping clarify!

/dup #3992
