### ISSUE TITLE
Add support for pseudo graphics apps with mouse support

### ISSUE THREAD

**Issue by SiarheiKuchukBelitsoft** [microsoft/terminal#4983]
1. Install Far Manager
2. Change config of Windows Terminal as following
`        {
          "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b1}",
          "hidden": false,
          "name": "Far Manager",
          "commandline": "c:\\Program Files\\Far Manager\\Far.exe"
        }
`
3. Run Far Manager

Observe
1. Inconsistent sizes of vertical sized border elements
![image](https://user-images.githubusercontent.com/60220228/76946978-f8587d80-6915-11ea-9a87-a93cdda3df8b.png)

2. Now click and drag mouse by Window 
Observe text selection happens instead of passing data of mouse to app
![image](https://user-images.githubusercontent.com/60220228/76947100-2c33a300-6916-11ea-8350-67bac154b256.png)

Consider fixing font chars for those vertical borders and disabling mouse intervention for Far app.

Thanks!

**Comment by zadjii-msft** [comment]
Please avoid filing issues with multiple bug reports in them - this makes it incredibly hard for us to track and triage all issues atomically. 

This issue is a combo of two other issues already on our repos:
* Line-drawing characters not filling the entire cell is a whole bucket: #455,  #1790, #3498, and a whole host of issues linked to #455
* Mouse not working for Win32 apps: #376

/dup #376
/dup #455

**Comment by SiarheiKuchukBelitsoft** [comment]
@zadjii-msft Thanks. I wasn't aware of them.
