### ISSUE TITLE
Alt+ Enter rendering error 

### ISSUE THREAD

**Issue by Po-wei** [microsoft/terminal#5029]
# Environment

```none
Windows build number: [[Version 10.0.18363.720]]
Windows Terminal version (if applicable):  0.10.761.0

Any other software?
```

# Steps to reproduce
There are two bugs of Alt+Enter behavior.
 Text Disappear && Prompt Duplicate
a.  open terminal with WSL
b. type: ls -la or do whatever will print content over a page
c. **mouse scroll up** to the top
d. type Alt+Enter to Fullscreen
e. text outside orignal windows do not render.
d. scroll down to the bottom: type Alt+Enter several times
f. prompt duplicate several times.

I used zsh with the right side Prompt
![image](https://user-images.githubusercontent.com/17596021/77134780-bae31580-6a25-11ea-998d-0e3f965bf54e.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/17596021/77134938-92a7e680-6a26-11ea-9421-7db56a3d9914.png)

![image](https://user-images.githubusercontent.com/17596021/77134715-76577a00-6a25-11ea-99d7-26255428b82d.png)

# Expected behavior
We need to scroll the terminal  to force a re-rendering.
![image](https://user-images.githubusercontent.com/17596021/77134701-617ae680-6a25-11ea-9754-4dd0c2195a22.png)

**Comment by zadjii-msft** [comment]
@Po-wei could you share your `profiles.json`? 

The second screenshot you've shared is certainly very peculiar. It almost looks like the behavior I'd expect from 0.9, but not 0.10. Like the conpty didn't resize to the newly fullscreen'd size. Especially considering the green from the `.tooling` line doesn't extend to take the full width of the buffer. I'd bet the buffer didn't actually increase in size.


Oh wow actually I just repro'd that immediately. It's almost as if we don't invalidate the screen or something on a resize.

WE almost certainly don't, because we were repainting the entire screen before on a resize, so this wasn't a problem. Yea okay I know what the fix is.

**Comment by Po-wei** [comment]
@zadjii-msft
My profile.json of terminal
https://gist.github.com/Po-wei/5512e0a85ea53ad6075a292c2e9bc77f
It is a pretty normal profile.

**Comment by zadjii-msft** [comment]
@Po-wei Thanks for sharing that. I originally thought you might be hitting the "a really large history size causes weird behavior on a maximize", but I was able to actually figure this out already. The fix is already in PR :)
