### ISSUE TITLE
conhost VK_F4 regression

### ISSUE THREAD

**Issue by tamlin-mike** [microsoft/terminal#5033]
# Environment

```
Windows 10.0.18363.592 (bug also present in some earlier build(s))
```

# Steps to reproduce

- cmd.exe
- `C:\>aaa bbb ccc ddd`
- Home, Ctrl-Right. Cursor should now be before the first 'b'.
- F4, Space. 'bbb' gets deleted.

# Expected behavior

Visual cursor position remains (i.e. now just before ' ccc').

# Actual behavior

1. Visual cursor position moves to EOL.
2. To make it worse, the insertion-point still is where the caret _was_, If you now type 'x' command line goes from 'aaa  ccc ddd' to 'aaa x ccc ddd', while the cursor remains at EOL!

**Comment by zadjii-msft** [comment]
Yikes yep that's annoying. I bet that this regressed in one of our earlier `COOKED_READ` refactors, though it's hard to know when exactly.

**Comment by DHowett-MSFT** [comment]
Regressed in 19H1 (10.0.18362)

**Comment by DHowett-MSFT** [comment]
(Verified using [CHOP](https://github.com/microsoft/terminal/commit/f840a7c7b5a04231ec9437c62d823cae3c1059b4))

**Comment by zadjii-msft** [comment]
note to self: still reproing in 10.0.22518.1000

**Comment by zadjii-msft** [comment]
Sharing notes because it's too close to 5pm:

Important to remember that the cmdline functions that open a popup do _not_ get handled in `CommandLine::ProcessCommandLine`. It has to wait for more input, so it gets processed later. So somewhere inside of `CopyFromCharPopup::Process` is where I need to be doing the final call back to `AdjustCursorPosition`, not at the bottom of `CommandLine::ProcessCommandLine`

**Comment by tamlin-mike** [comment]
Back when you announced with fanfare "Console will get TLC!" I had hopes you would do something good. **We** had hopes.

It saddens us, but unfortunately doesn't surprise me, to finally accept that was, like almost everything Microsoft nowadays, just lies. You have completely abandoned the console, seemingly care more about implementing _slow_ and maddeningly resource hungry rendering of translucent unicode turds than working on what matters to your customers, like _reducing_ resource usage, _speed up_ rendering, and most certainly reverting or fixing stuff you break, and now it's too late. You will NEVER fix this, since Microsoft itself has abandoned Windows 10 (the last and only Windows there will ever be, right).

Your use of `#fuckitshipit` clearly displays your arrogance, and it shows in the product. We have used Windows since back in the 3.11 days. This was the straw. Our next operating system will be a unix derivative. With any luck it will also become a punishable offence to even _suggest_ Microsoft products in the future. No need to thank us, you deserve it.

**Comment by lhecker** [comment]
FYI I'm currently working towards rewriting the command line implementation from scratch, because the original code was hard to maintain and the rewrite that brought this issue is even worse (and incorrect on top of it). Thanks for pinging this issue - now I know to remember to test it.
Contrary to what you said, you will be able to use it on Windows 10, even in conhost, and I'd be happy to show you how.

Also, while I understand your anger,  don't write comments like that please.
