### ISSUE TITLE
SCP friendly integration

### ISSUE THREAD

**Issue by z1lV3r** [microsoft/terminal#5059]
# Description of the new feature/enhancement
A user-friendly tool to share files between local machine and remote servers over SCP. 

# Proposed technical implementation details
Windows terminal could bring a feature to `drag and drop` a file into a terminal **to transfer a file** into the actual folder of the remote server and to get a file it could be using `right click` into selected file name from the remote server with an option `download` in right-click menu which will open a `save as` dialog to select a folder.

As an extra could be great a `configuration` to get a `default path` to download a file from the server with an option for "ask every time".

**Comment by DHowett-MSFT** [comment]
Thanks for the request! Unfortunately, this is somewhat out of scope for a _terminal_, and is more of a feature of a general-purpose remote file manager. I'm gonna close this one out, since it's not likely we'll implement or accept the contribution of any SCP-specific features. If we accept SCP, we'll have to accept SFTP, then FTP, and DAV, and eventually we'll become a _file manager_ and not a terminal. :smile:

**Comment by zadjii-msft** [comment]
@CatCatCatDog That's already being tracked by #4000, don't worry 😉
