### ISSUE TITLE
Highlight certain text in Windows Terminal with the mouse and perform actions

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5069]
# Description of the new feature/enhancement
Highlight the specified selected text in Windows Terminal with the mouse and perform actions such as deleting and inserting characters.

# Proposed technical implementation details (optional)
![Anmerkung 2020-03-22 060539](https://user-images.githubusercontent.com/47790579/77242837-30f0a380-6c03-11ea-84f3-a12e9f167e8b.png)

**Comment by DHowett-MSFT** [comment]
Thanks for the request!

This will not work in general. What if I select this text and choose "Delete"?

![image](https://user-images.githubusercontent.com/14316954/77242890-b56e0280-6bc0-11ea-92ae-11b922836ca2.png)

Terminal can't "collude" very well with the shell because it needs to remain generic.

**Comment by DHowett-MSFT** [comment]
Because terminal cannot reliably do this, I'm going to close this feature request. Please, keep them coming! Thank you!

**Comment by DHowett-MSFT** [comment]
Oh! Powershell can do this if you hold down Shift and use the Arrow keys. That’s a good shell feature!
