### ISSUE TITLE
newTabProfile shortcut hinting

### ISSUE THREAD

**Issue by baruchiro** [microsoft/terminal#5083]
# Description of the new feature/enhancement

We want to use more and more shortcuts instead of using the mouse, but for doing that we need to remember all the Windows Terminal shortcuts.

I thought about something like if you hold the `Ctrl + Shift` you will see the profiles list:
![image](https://user-images.githubusercontent.com/17686879/77303516-c5d6c800-6cfb-11ea-8962-c659fec04f0e.png)

And then you just need to add a number to your holds to open the relevant profile.

# Proposed technical implementation details (optional)

1. You want to open a new profile but you don't remember the profile number.
2. You start with the shared shortcut: `Ctrl + Shift`
3. The popup with the profiles numbers opened.
4. You add the relevant number to the `Ctrl + Shift` holding,

You can expand this Feature Request to all shortcuts (related to https://github.com/microsoft/terminal/issues/4695)

**Comment by zadjii-msft** [comment]
I'm not sure that this is something that would really be possible - since users can override the keybindings arbitrarily, there's no way to know for sure if the `newTab` keybindings shared a common prefix (like <kbd>ctrl+shift</kbd>).

There's also the `openNewTabDropdown` action, bound to <kbd>ctrl+shift+space</kbd> by default, which might work for the scenario you're describing.

**Comment by baruchiro** [comment]
You're right. the ctrl+shift+space (how do you mark it as a keys combination in markdown?) is almost what I suggested.

Closing

**Comment by zadjii-msft** [comment]
@baruchiro Thanks for following up! 

As far as the markdown, you're looking for `<kbd>ctrl+shift+space</kbd>` 😄
