### ISSUE TITLE
Screen content does not update in tmux

### ISSUE THREAD

**Issue by kasper93** [microsoft/terminal#5104]
# Environment

Windows 10.0.18363.0
tmux over ssh in cygwin

# Steps to reproduce

1. Attach to tmux session
2. Fill the screen for example with `echo test` multiple times
3. Keep printing `test`, you should alternate with some different text to see if console is scrolled properly.

# Expected behavior

Whole screen buffer is redrawn

# Actual behavior

Only first line in terminal is redrawn, the rest of the screen space is static and doesn't update while it should. If the output is one line (i.e without new line). If I do `echo 'test\n'` whole screen is properly redrawn. 

## Bisect result

This is regression from this commit https://github.com/microsoft/terminal/commit/ca33d895a359664c337c6482b853489823c216d3 before that everything was working fine. 

// CC @miniksa

**Comment by miniksa** [comment]
OK I've managed to reproduce this. I think it's a bug that's been there a while and was just hidden by the fact that the previous invalidation-mechanism would coalesce both invalid regions into repainting the entire display. I need to figure out how to dispatch the appropriate content scrolling from the PTY to the Terminal because the entire point of the `til::bitmap` change was to not re-emit massive amounts of data that are already on the other side of the fence.

**Comment by skyline75489** [comment]
I've encountered a similar issue when using Vim in WSL. The majority of content is not being invalidated while scrolling up and down using keyboard.

![图片](https://user-images.githubusercontent.com/4710575/77597359-98775d80-6f39-11ea-82a7-dc4a42fafa3a.png)

The actual content should be line 80 - line 107. But only the first and last line is correctly displayed.

**Comment by DHowett-MSFT** [comment]
@skyline75489 while you've got a local build, would you mind trying out https://github.com/microsoft/terminal/pull/5122? It's the speculative fix :smile:

**Comment by skyline75489** [comment]
@DHowett-MSFT It's working! Vim is back to normal with the help of #5122.

**Comment by kasper93** [comment]
I can also confirm, working fine with the fix.
