### ISSUE TITLE
Terminal cannot process keystroke combinations with specific Win10 keyboard languages

### ISSUE THREAD

**Issue by mtjon** [microsoft/terminal#5168]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable):  0.10.781.0

wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Running         2
```

# Steps to reproduce

Set Windows 10 keyboard language to something that binds `ctrl + alt + l`, e.g.: English (United States International), which binds it to 'ø'.

# Expected behavior

I expect the terminal to pick up the keystrokes as input, in my case it would be used as keybinding in my tmux configuration.

I would understand if this is classified as expected behaviour, but I'd much prefer Terminal to handle the keystrokes 'directly'. 

# Actual behavior

Windows sends the 'ø' to the Terminal, which does not know how to handle it, and displays it as `<ffffffff>`. My font (`Fira Code`) possibly doesn't contain the glyph.

**Comment by zadjii-msft** [comment]
Could you share a screenshot? When the _Terminal_ doesn't understand a character, it usually displays it as `\uFFFD`, the "unicode replacement character". If you're seeing `<ffffffff>` in the Terminal, that's probably due to some other application failing to interpret the character. What application are you trying to type into? `bash`, `zsh`, `vim`, `emacs`, etc? 

Could you try running `showkey -a` in WSL, press <kbd>ctrl+alt+l</kbd> for me, and paste the output here?
