### ISSUE TITLE
Option to disable ConPty wrapping/reflow functionality

### ISSUE THREAD

**Issue by kchibisov** [microsoft/terminal#5192]
From what I've seen in some alacritty bug reports [e.g](https://github.com/alacritty/alacritty/issues/3361#issuecomment-606531771), it seems like ConPty is doing wrapping/reflow by itself, which is pretty annoying if your terminal can handle all of that. So it also interferes with our logic from time to time and breaks some of our features. Ideally it'll be nice to have an option to prevent ConPty of doing so(ideally I want ConPty to be 'just a pipe', which forwards things to us directly without any black magic under the hood, but meh).

The main problem that this feature would solve is that it'll help other terminals out there who is capable of handling content reflow by themselves have their reflow/wrap related features working, since ConPty can't handle use cases like: split across line selection with double clicks aka select a word, triple click on a line, which should select the entire wrapped line, URL clicking and launching, reflow of multiple cursors(alacritty has a keyboard driven mode to select text and a special cursor for it), selections, etc, etc.

**Comment by j4james** [comment]
I think what you probably want is the passthough mode discussed in #1173. I don't see how wrapping could be disabled without that, unless I've misunderstood your request.

**Comment by j4james** [comment]
That said, it looks like PR #4415 might help with this issue. I'm not sure if that's been released in a version that you can test yet, but you could always build it yourself to check if it makes any difference.

**Comment by kchibisov** [comment]
>That said, it looks like PR #4415 might help with this issue. I'm not sure if that's been released in a version that you can test yet, but you could always build it yourself to check if it makes any difference

It really seems like the thing we want tbh, thank you for linking this, I don't have any windows machine to test this myself, however I'll link it on our tracker, so folks, who are running windows can test it, and check if it works for them.

I'll close this issue for now.

**Comment by mintty** [comment]
This issue should be reopened, still unhandled after 4 years. See my renewed attempt to raise awareness of the problem in microsoft/WSL#12143.

**Comment by DHowett** [comment]
Preview 1.22 doesn't reflow via ConPTY any longer. There would be no value in reopening this issue.

**Comment by mintty** [comment]
> Preview 1.22

Please give some details: Preview of what? (Windows 11/Windows Terminal/...)
Does it also pass input/output sequences unfiltered?
Are sources of wsl.exe available?

**Comment by DHowett** [comment]
Windows Terminal

Yes

No

**Comment by mintty** [comment]
You seem to mean that replaceming conhost with OpenConsole changes wsl.exe behaviour.
Unfortunately, unlike previous versions, that does not work in Windows 10.

**Comment by DHowett** [comment]
`wsl.exe` is a Windows Console subsystem application and therefore needs to be hosted in a console.

ConPTY is the API we offer for hosting Windows Console subsystem applications.

The version of ConPTY present in Windows Terminal--which will eventually be released as part of Windows and as a separate package for _people who want to host console applications_[^1]--passes through the VT output from hosted console applications unmodified.

It, nearly by definition, changes `wsl.exe`'s behavior when `wsl.exe` is hosted inside it... which is the way you are expected to host `wsl.exe`[^2]. It does not change how `wsl.exe` behaves when `wsl.exe` is not hosted using it. This is the very nature of console application hosting.

This fact is observable! If you _do_ replace conhost.exe with OpenConsole[^3] _even on Windows 10[^4]_, applications that use ConPTY to host `wsl.exe` get different output from `wsl.exe`.

[^1]: this is not the place to readjudicate our delivery mechanisms
[^2]: [somebody](https://github.com/o-sdn-o) reimplemented the server side of console hosting based on our IOCTL API. it still has to handle the Win32 API components of the console API, but you might find what you need there. it is not conhost. you still need to actually _use it to host an application_
[^3]: no warranty, either express or implied
[^4]: we know this because we do it, routinely

**Comment by mintty** [comment]
> OpenConsole ... does not work in Windows 10.

Sorry, that was a misscarried test case. It does work. Thanks for dropping the reflow.

**Comment by DHowett** [comment]
Woot!

@lhecker and I have been discussing a couple other options for getting conpty fixes back to Windows 10. We'll keep the repo updated if we move forward on any of 'em...
