### ISSUE TITLE
Debugger creates processes every second

### ISSUE THREAD

**Issue by crazyyzarc** [microsoft/terminal#5267]
# Environment

```none
Windows build number: W10 RB1903 18362.752
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
```

# Steps to reproduce

**1.** open `regedit.exe`
**2.** add new key `cmd.exe` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\`
**3.** add new `Debugger` string with value to windows terminal `"C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.10.781.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe" `
**4.** run `cmd.exe`
**5.** enjoy how windows terminal is opened thousands of times ;)

https://framapic.org/FXcZwQgGbBPZ/bYYEfDIIPOXj.png

# Expected behavior

open once only

# Actual behavior

see step **5.**

**Comment by zadjii-msft** [comment]
_y tho_

Is this really a bug, or expected behavior? I bet your default profile for the Terminal is a `cmd.exe` profile. Whenever you launch cmd.exe, Windows is going to open a new WT instance, which is going to start `cmd.exe` as your default profile, which is going to cause Windows to open a new WT instance, ...

This is very much by-design. Do you have some other design or use case in mind?

**Comment by DHowett-MSFT** [comment]
I think what they want is #492

**Comment by crazyyzarc** [comment]
> 
> 
> I think what they want is #492

Yes, when I use the command cmd.exe, I want to open a WT instance instead of system32\cmd.exe
