### ISSUE TITLE
Add X11 forwarding 

### ISSUE THREAD

**Issue by TomaszGrzmilas** [microsoft/terminal#5351]
Description of the new feature/enhancement:

I would like to be able to run the ssh -X (-Y) <servername> command on a terminal and use the functionality available in PuTTY -> X11 Forwarding.

I got installed XLaunch and when I connect using PUTTY ssh, I can run GUI applications on remote linux server.

I was thinking if that can be done by windows terminal, without necessary to use PuTTY  or even XLaunch ?

Thanx !

**Comment by DHowett-MSFT** [comment]
If you can run `ssh -X` outside of Terminal you can certainly run it inside terminal. This sounds like a request for the Win32-OpenSSH team.

**Comment by hensz** [comment]
Hi there!
While it's technically possible to use X11 forwarding with Windows Terminal I have one case where it doesn't work.
When I open a WSL terminal and manually run ssh -X myhost I get a connection and can also open X11 programs. But when I use a custom profile with Command line "wsl.exe ssh -X user@myhost" I get a connection, too, but I cannot open X11 programs. Instead I get the usual error message:
xterm: Xt error: Can't open display:
xterm: DISPLAY is not set

So obviously there's a difference wrt. X11 forwarding between the "regular" WSL terminal (wsl.exe -d Ubuntu) and my custom profile. Is this a configuration error on my side, or is this a bug in Windows Terminal?

btw, I'm using the latest Preview version 1.10

**Comment by DHowett** [comment]
It's likely that running `wsl ssh` skips parts of your profile initialization, or does not propagate the `DISPLAY` environment variable.

**Comment by DHowett** [comment]
(This is by design)

**Comment by hensz** [comment]
Any idea how to do this differently, where to look for further information or whom to ask? Searching for wsl ssh x-forwarding didn't help much :-(

**Comment by hensz** [comment]
Hi @DHowett,
this issue is closed and my question is only partly related to the original question, so I wanted to post it somewhere else - but I don't have a clue where would be the best place to do so. Can you give me a hint? Is the behavior I reported "caused" by Windows Terminal, wsl or OpenSSH? And what is the correct reporting channel for the respective component?
Thanks in advance,
Torsten

**Comment by ciaochiaociao** [comment]
@TomaszGrzmilas I also ran into this issue. Like the other said, it should not be Windows Terminal's issue. But I understand why you post here, since using PuTTY with *Port Forwarding* enabled simply works while Windows Terminal does not. I think PuTTY does many things under the hood in fact. To use other terminals than PuTTY, you can follow the note I wrote below.

# Settings for SSH Clients Used On X11 Server (Workstation)

## Option 1: Use PuTTY with *Port Forwarding* enabled

## Option 2: Use ANY terminal with following steps

1. export `DISPLAY` environment variable in X11 Client's (remote) shell runcom file: `*rc`

   ```bash
   # in ~/.bashrc or ~/.zshrc ...
   export DISPLAY=<x11_server_name_or_ip>:<display_num>.<win_num>
   # e.g.
   export DISPLAY=myhome.com:0.0
   # or just
   export DISPLAY=myhome.com:0
   ```

2. allow ports 6000-6063 in Firewall setting

   ref: https://forums.anandtech.com/threads/what-port-does-x11-traffic-use.618859/

3. Start X11 Server with access control disabled, e.g., start VcXsrv with option: *Disable Access Control* (Don't forget this. Otherwise, it will show *authentification error*.)

All three steps need to be done, otherwise, it won't work.

FYI

**Comment by zxleong** [comment]
> 1. export `DISPLAY` environment variable in X11 Client's (remote) shell runcom file: `*rc`
>    ```shell
>    # in ~/.bashrc or ~/.zshrc ...
>    export DISPLAY=<x11_server_name_or_ip>:<display_num>.<win_num>
>    # e.g.
>    export DISPLAY=myhome.com:0.0
>    # or just
>    export DISPLAY=myhome.com:0
>    ```


How do I find my x11 server name and display num?

**Comment by sisrfeng** [comment]
1. `export DISPLAY=localhost:11.0` in .zshrc. 
2. start **xming**
done

**Comment by sisrfeng** [comment]
update:
X11 forwarding  success only if I keep mobaxterm ssh to the same remote machine with the same  `localhost:11.0`   (Using mobaxterm, DISPLAY will be set by mobaxterm, not forced to `localhost:11.0` by zshrc

my zshrc
![image](https://user-images.githubusercontent.com/53520949/154062025-e3ed2ff0-15bd-4a3a-8caf-3548666ccfcf.png)

Same code as above, but with my notes:
![image](https://user-images.githubusercontent.com/53520949/154062122-b880b256-24e3-45f9-8791-a8a6675a780a.png)

.zshlogin:
(excuted after .zshrc)

![image](https://user-images.githubusercontent.com/53520949/154062714-8013a0c3-d033-4531-a8f9-f1cf0b439d99.png)

**Comment by Zhaoyilunnn** [comment]
> update: X11 forwarding success only if I keep mobaxterm ssh-ing to the same remote machine with the same `localhost:11.0` (Using mobaxterm, DISPLAY will be set by mobaxterm, not forced to `localhost:11.0` by zsh' s config ) This implies that it is the X-server integrated in mobaxterm, instead of Xming, that makes x11 forward success in the situation of my reply above. but I want to uninstall mobaxterm!
> 
> How to make Xming/VcXxvr works for windows terminal ?
> 
> my zshrc ![image](https://user-images.githubusercontent.com/53520949/154062025-e3ed2ff0-15bd-4a3a-8caf-3548666ccfcf.png)
> 
> Same code as above, but with my notes: ![image](https://user-images.githubusercontent.com/53520949/154062122-b880b256-24e3-45f9-8791-a8a6675a780a.png)
> 
> .zshlogin: (excuted after .zshrc)
> 
> ![image](https://user-images.githubusercontent.com/53520949/154062714-8013a0c3-d033-4531-a8f9-f1cf0b439d99.png)
> 
> Allowed by firewall ![image](https://user-images.githubusercontent.com/53520949/155316094-f534b42f-82ee-461f-90b0-9dc644ade503.png)

Exactly the same problem with you

**Comment by Zhaoyilunnn** [comment]
> How to make Xming/VcXxvr works for windows terminal ?

https://superuser.com/questions/1610181/connecting-to-x11-using-windows-10-openssh-and-vcxsrv

This works for me.
