### ISSUE TITLE
Mouse input ignored for new instances

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#5367]
# Environment

```none
Windows build number: 10.0.19608.0
Windows Terminal version (if applicable): 0.11.1043.0

```

# Steps to reproduce

1. run `wt`
2. use the mouse to do anything

# Expected behavior

mouse input should go through to the XAML controls (including TermControl).

# Actual behavior

No mouse input is accepted.

**Comment by carlos-zamora** [comment]
Actually, all new instances are busted. Investigating now. Especially since there's no repro for @zadjii-msft .

**Comment by DHowett-MSFT** [comment]
Did you get a repro?

**Comment by carlos-zamora** [comment]
Unfortunately no :(. Reported to the input team and they closed the internal bug as no repro. So, it might be an OS issue? Though this _only_ happened with Terminal. And it only happened when it was on the main monitor. Worked perfectly fine on the secondary monitor.

**Comment by DHowett-MSFT** [comment]
Res no repro, thanks!

**Comment by oplik0** [comment]
I can reproduce it consistently on my machine. Mouse input broken only on main monitor. [Video evidence](https://imgur.com/LQlX0dr) (the weird shaking and the dropdown not showing seem to be artifacts from build-in windows recorder. It was made for games after all, but I didn't want to download something else to do it)

However, I think I also found the culprit - PowerToys. Closing this app solves the issue, though relaunching it doesn't start causing it again (perhaps after restart? Will test further soon, but it's too too late in Poland and I prefer sleep to looking for issues with Windows Terminal :). I'd expect that the issue is caused by either FancyZones or Shortcut Guide, as both present some kind of overlay.

**Comment by DHowett-MSFT** [comment]
Interesting. I think we have an issue on our repo for that one already -- #3325 perhaps?

**Comment by carlos-zamora** [comment]
For the record, I also had PowerToys running but I did not think about closing it.

**Comment by EricBrownz** [comment]
The same issue when I run `tmux`.
It seems mouse input works incorrectly after updated to 0.11.
