### ISSUE TITLE
Terminal doesn't respond to SIGINT (CTRL+C KeyboardInterrupt) when running as administrator

### ISSUE THREAD

**Issue by 403-Fruit** [microsoft/terminal#5460]
# Environment

```none
Windows build number: Windows NT 10.0.19041.0
Windows Terminal version: Version: 0.10.781.0
```

# Steps to reproduce
* Start one terminal as administrator, and one normally 
* Using PowerShell or cmd (didn't test other shells), start some continuous process, e.g  ```ping -t localhost```
* Try to interrupt process with ctrl+c on each terminal.
* Observe that it only works on the unelevated terminal. 

# Expected behavior
SIGINT causes console process to exit, regardless of elevation

# Actual behavior
Process does not respond to SIGINT, and requires manual termination from taskmgr or another shell

**Comment by DHowett-MSFT** [comment]
Can't repro this, as admin.

![image](https://user-images.githubusercontent.com/14316954/79946405-c494da00-8424-11ea-9831-03d743008a66.png)

**Comment by 403-Fruit** [comment]
I think it's the way I'm launching it, as it's a bit improper. I have a shortcut on my taskbar with the target

```C:\Windows\System32\cmd.exe /c start /b wt```

that is set to run as administrator, just so that it defaults to admin. I just tried and it works as expected if I `Right click -> Run as Administrator`.  

I can't remember why I used the above target, but setting the it to `wt.exe` appears to produce the desired behavior, and CTRL+C works fine.

**Comment by DHowett-MSFT** [comment]
Ah, thanks for following up. That’s really quite strange. I’m not sure there’s anything we can do about that; perhaps there is something strange about app activation in this context... ☹️ 

For now, I’ll resolve this one as External. Please let me know if you have any other ideas or any other leads.

**Comment by eryksun** [comment]
> I think it's the way I'm launching it, as it's a bit improper. I have a shortcut on my taskbar with the target
> 
> `C:\Windows\System32\cmd.exe /c start /b wt`

Why doesn't the shortcut simply run wt.exe?

The `/b` option of CMD's `start` command calls `CreateProcessW` with the creation flag `CREATE_NEW_PROCESS_GROUP` and without the flag `CREATE_NEW_CONSOLE`, so it sort of acts like running a background process in the current console session, especially if combined with redirecting the process standard input to NUL. 

A process that's created in a new console process group initially has Ctrl+C disabled (i.e. the `ConsoleFlags` in the PEB process parameters has the first bit set). I guess it's because only 'foreground' processes should see Ctrl+C. This setting gets inherited by child processes. 

Interestingly, this flag remains set in the process parameters and inheritable even if we run a non-console application such as Windows Terminal. I suggest that Windows Terminal should clear this flag to enable Ctrl+C on startup via `SetConsoleCtrlHandler(NULL, False)`.

**Comment by DHowett-MSFT** [comment]
Good catch, @eryksun. Thanks!

**Comment by 403-Fruit** [comment]
> Why doesn't the shortcut simply run wt.exe?

@eryksun That's a mistake on my part. I don't quite remember why I ended up with that, and it seems completely unnecessary in hindsight. Thanks for the insight.

**Comment by 403-Fruit** [comment]
By the way, you guys are doing an awesome job with the Terminal. It's a home run IMO, and I'm genuinely excited to see what comes next 👍

**Comment by ribbles** [comment]
Still seeing this intermittently in `v1.6.10571.0`.

**Comment by vladsol** [comment]
Windows terminal 1.11.3471.0

I can reproduce this problem.

Windows terminal stopped responding on Ctrl + C after executing and just trying to log-in by ssh on any host.

**Comment by jacobrastad** [comment]
I can confirm @vladsol observation as well.

1. Login with SSH on any remote host. Then exit that
2. Run `ping 8.8.8.8 -t`
3. Try to exit with `ctrl+c`

**Comment by jacobrastad** [comment]
Created a new issue for this at https://github.com/microsoft/terminal/issues/13503

**Comment by mikizdr** [comment]
ctrl + c doesn't work

**Comment by DHowett** [comment]
If you are experiencing this issue, file a new bug and fill out the template. This one is four years old and has been closed for the majority of that time.
