### ISSUE TITLE
Feature Request: Plugin support

### ISSUE THREAD

**Issue by Domain** [microsoft/terminal#555]
Please support plugin, so that we can add our own feature.

**Comment by hapylestat** [comment]
Check the MSFT short video presentation of the terminal. There was me mention about supporting plugins....

**Comment by fredrikaverpil** [comment]
I am sure users are going to request a plethora of features of the new terminal. Would it be beneficial for you (Microsoft) to add resource-demanding features as separate extensions and possibly provide (and even recommend using vscode-like popups) groups of extensions on top of an otherwise barebones and speedy experience, like with the [wsl terminal](https://github.com/microsoft/Terminal/issues/327)?
I personally live and breathe inside vscode and love the way extensions can be searched/browsed/recommended and also how they can be enabled/enabled.

I am thinking about http link colorization/clickability (such in the [reveal video](https://www.youtube.com/watch?v=8gw0rXPMMPE)), arrangable tmux-like panes support, CPU/mem stats bar, text exporters and other extensions which may possibly slow down the overall experience of the terminal.

Maybe for some commands you are about to run, you might actually disable all (or a selection) of extensions prior to executing, just to make the terminal speedier.

**Comment by bitcrazed** [comment]
Thanks for your thoughts here @fredrikaverpil. We're keen to add extensibility to the Terminal, but we have a bunch of features we need to solidify before we can turn our attention to such features.

One of the things I am currently working on is planning our roadmap which I'd like to share with the community within the next couple of weeks. This roadmap will give you some visibility into when key features are likely to land, how we're aiming to ship v1.0, and where we're going afterwards.

Please bear with us while we figure-out some of the details.

**Comment by kfarmer-msft** [comment]
@bitcrazed -- Any progress on the roadmap you mentioned?

**Comment by zadjii-msft** [comment]
Hey like 2 years ago I moved this to #4000 and never closed out the original thread. Oops.

# -> Go to #4000 <-
