### ISSUE TITLE
QOL: Paint terminal win32 host background so it looks like the launch profile?

### ISSUE THREAD

**Issue by letmaik** [microsoft/terminal#5572]
# Environment

```none
Windows build number: 10.0.18363.778
Windows Terminal version (if applicable): 0.11.1121.0
```

# Steps to reproduce

Start Terminal and observe the short gray-to-default-profile-background-color flicker before the shell is loaded. Close Terminal and observe the same in reverse.

# Expected behavior

There should be no flickering. When starting, the background of the "empty" shell area should be the same color as the default profile. When closing, the shell area should use the background color of the currently active profile/shell.

# Actual behavior

The "empty" shell area is always gray, which means it transitions very quickly from gray to (typically) black when the default profile shell is displayed. Similarly when closing Terminal.

**Comment by WSLUser** [comment]
Probably related to this: https://github.com/microsoft/terminal/pull/5277

**Comment by letmaik** [comment]
Really? Why do you think so?

**Comment by zadjii-msft** [comment]
Yea that merged literally 3 days ago, it hasn't actually been shipped to anyone yet

**Comment by zadjii-msft** [comment]
@letmaik do you mean a gray window like this?
![image](https://user-images.githubusercontent.com/18356694/80398046-adb71300-887c-11ea-96a4-bd6836803fbf.png)

**Comment by letmaik** [comment]
This is what the moment looks like when it starts/exits:
![grafik](https://user-images.githubusercontent.com/530988/80401208-df979c00-88b3-11ea-8e52-bddde92631e6.png)

**Comment by WSLUser** [comment]
Oh, I thought it was part of the .11 release. So much for being obvious.

**Comment by dreadnaut** [comment]
This happens for me as well, in the most recent release but also in previous ones. The terminal window appears with the default system background colour:
![image](https://user-images.githubusercontent.com/584584/80997799-c2c21200-8e39-11ea-8fc6-c52d9d1673e2.png)
then the correct theme background is applied. Both with standard decorations, or with tabs in the titlebar. The same when closing the window.

Switching the system's "default app mode" to dark _does not_ change the flash colour: it's still white.

**Comment by DHowett** [comment]
Thanks for writing this all up!

I think it would be a nice quality of life improvement if we were to paint the window in a color closer to the one it'll eventually be filled with.

@dreadnaut your issue seems different, somehow... that titlebar doesn't look familiar to me (the standard Windows one is narrower, and the custom one we draw has different caption buttons ...)

**Comment by DHowett** [comment]
(name changed to encompass what I think would be best)

**Comment by dreadnaut** [comment]
> @dreadnaut your issue seems different, somehow... that titlebar doesn't look familiar to me (the standard Windows one is narrower, and the custom one we draw has different caption buttons ...)

I use Terminal with acrylic disabled, and
```
    "alwaysShowTabs" : false,
    "showTabsInTitlebar" : false,
```
which means I only see the standard Windows titlebar until I open a second tab. If I switch to tabs-in-titlebar, the flash has the same colour. I'd say it's the same issue 🙂

**Comment by Mystic8b** [comment]
Titlebar looks frankly bad. It’s so bad that I’m ready to use alternative terminals where the mouse doesn’t work in mc, etc., but it’s not painful for my eyes to look at them.

And if you turn on the acrylic - it gets even worse. Titlebar doesn't mix with absolutely anything! It should have the same color (and transparency if enabled) as the main menu.

**Comment by zadjii-msft** [comment]
I'm gonna also x-ref #11561 here. With the transparency changes in 1.12, the backgound starts as totally transparent, instead of gray/white. 

There's also now the possibility that the Terminal is launching:
* with some profile other than the default profile
* with _multiple_ tabs & panes, which might complicate this. 

So this isn't necessarily straighforward "use the default profile's BG to paint the window".

**Comment by mentalisttraceur** [comment]
In case this changes priority at all: getting flashbanged in the eyes like this is the \#1 thing I know of that makes dark themes unhelpful for some people - if your eyes are sensitive in the right way, light theme is bad and unpleasant but still better than to let your eyes get used to dark only to get sliced across the eyes with a momentary flash.

**Comment by mentalisttraceur** [comment]
For anyone looking for a slightly better experience, I noticed that if I install WSL Debian, set my default terminal application to Windows Terminal instead of Windows Console Host, and then run Debian, I only get the flash on close rather than on open.

(I presume you'd get the same improvement with any command-line program which indirectly launches Windows Terminal instead of directly, but I haven't checked.)

**Comment by mentalisttraceur** [comment]
Actually I take that last statement back.

Upon further testing it seems that it's only sometimes fast enough to not do the white-ish flash on launch in those cases, but other times I still get the flash.

Also an interesting effect is that the initial color on start and final color on close are different. The open color seems dimmer, like a gray, while the close color seems closer to a white.

**Comment by zadjii-msft** [comment]
You know what, like 8 months ago we started having the HWND be entirely hidden until the window is ready to render. That basically makes this issue moot 😄

**Comment by mentalisttraceur** [comment]
Now that you mention it, I don't remember being bothered by this problem lately.

(I moved to Emacs through gWSL as my daily driver terminal emulator about a year ago, so in those 8 months I've only opened the terminal a handful of times.)

Checking now, I can confirm that this issue seems to no longer happen, on both open *and close*. Big thanks.
