### ISSUE TITLE
Not respond to mouse selection in Tmux (WT:  v0.11.1121)

### ISSUE THREAD

**Issue by Jarvis73** [microsoft/terminal#5608]
# Environment

```none
Windows build number: 

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable): 0.11.1121.0

Linux server:
 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

Tmux: 2.6
```

# Steps to reproduce

Open WT -> login linux server

```bash
tmux new -s main
ls
```
Then select a word or something.

# Expected behavior

The word/something is selected.

# Actual behavior

Nothing is selected.

I think the latest release v0.11.1121.0 made some changes about mouse events and caused the issue because everything was well a few days ago.

**Comment by DHowett-MSFT** [comment]
> login linux server

It’s very important how you’re doing this.

Are you using the version of SSH that comes with Windows? If so, that is version 7.7 and it doesn’t support transmitting mouse events.

**Comment by thochra** [comment]
Hi, @DHowett-MSFT 
I do have the same issue after last update.
I can ssh my VM and select text, but I can't in tmux anymore.

I'm using the Windows' ssh version.

----

As a workaround, you go back to previous version:
 - release page => https://github.com/microsoft/terminal/releases/tag/v0.10.761.0
 - download the msixbundle from the assets and reinstall
 - don't forget to open settings to identify the settings folder and rename or copy/paste the content of `settings.json` into the `profiles.json` as the file was renamed to `settings.json` after this version

FYI my settings folder was : C:\Users\[MY_USER_NAME]\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState

**Comment by DHowett-MSFT** [comment]
Oh, I see what you're reporting. Okay.

This is because tmux asks for terminal to enable "mouse mode":

* SSH sits in the middle, and passes on the request.
* Terminal now reliably enables mouse mode.
* Terminal sends mouse input to SSH
* SSH ignores it.

You'll need to configure tmux to not request mouse mode, or upgrade SSH.

Alternatively, you can hold down Shift to interact with the Terminal's selection model.

**Comment by thochra** [comment]
Hi 👋 

I didn't know that there is another ssh client available and more up to date than the Windows's additional functionnality one.

----

For those who falled into the same issue as me:

I picked the information from this post: https://blog.frankfu.com.au/2019/03/21/moving-from-windows-1809s-openssh-to-openssh-portable/

Since I installed the Win32 OpenSSH version from chocolatey I found back the behavior I'm used to with tmux.

The only drawback is that I had to disable mouse support (which isn't working atm) in tmux in order to be able to perform double click selects and single click de-selects.
NOTE: do the same with vim if it bother you.

.tmux.conf => `set -g mouse off`
.vimrc => `set mouse=`

**Comment by Jarvis73** [comment]
> Oh, I see what you're reporting. Okay.
> 
> This is because tmux asks for terminal to enable "mouse mode":
> 
> * SSH sits in the middle, and passes on the request.
> * Terminal now reliably enables mouse mode.
> * Terminal sends mouse input to SSH
> * SSH ignores it.
> 
> You'll need to configure tmux to not request mouse mode, or upgrade SSH.
> 
> Alternatively, you can hold down Shift to interact with the Terminal's selection model.

Thanks! I upgraded SSH to OpenSSH_for_Windows_8.1p1 and the problem was solved.
* Copy/Paste inside tmux: select by mouse, and paste by `C-b + ]`
* Copy to/Paste from system clipboard: hold down Shift, select by mouse and right-click to copy; hold down shift, right-click to paste
