### ISSUE TITLE
Multiple keybidings 

### ISSUE THREAD

**Issue by xgonc** [microsoft/terminal#5614]
# Environment

```none
Windows build number: Version 10.0.18363.778
Windows Terminal version (if applicable): 0.11.11.21.0

Any other software?
```

# Steps to reproduce
Create a keybinding with multiple shortcuts. Example:

```
       {
            "command": "paste",
            "keys": [
                "ctrl+shift+v",
                "shift+insert"
            ]
        }
```

# Expected behavior
No errors/warnings

# Actual behavior
An error message saying that there are multiple keys defined, which is not allowed. However both keybindings seem to work. Workaround:

```
        {
            "command": "paste",
            "keys": [
                "ctrl+shift+v"
            ]
        },
        {
            "command": "paste",
            "keys": [
                "shift+insert"
            ]
        }
```

**Comment by zadjii-msft** [comment]
I mean, that's exactly expected behavior. Defining multiple keys for a keybinding in a single array _doesn't_ work. The example you've given above might just happen to work, because `ctrl+shift+v` and `shift+insert` are already bound to `paste` in `defaults.json`:

https://github.com/microsoft/terminal/blob/d6cae40d26d2f4ba249d3960e8478c04681c8e1e/src/cascadia/TerminalApp/defaults.json#L323-L324

**Comment by xgonc** [comment]
My point is, since the keys object is an array, I'd assume that multiple keybindings could be setup for the same command. In my mind this is more obvious than creating multiple objects for the same command. Unless the usage of an array for keys is wrong (this bit was migrated from the configuration file of version v0.10.781.0).

**Comment by DHowett-MSFT** [comment]
Unfortunately, keys being an array was a "we're gonna need it" feature for key "chording" (like in screen/tmux). Since we didn't land that in time for v1, we simplified the settings model a little bit and downgraded all our default settings to avoid the array syntax so as to not confuse folks. Unfortunately, legacy settings live on :smile:
