### ISSUE TITLE
How about make microsoft terminal can be used on mac osx or  linux

### ISSUE THREAD

**Issue by netroby** [microsoft/Terminal#563]
How about make microsoft terminal can be used on mac osx or  linux. 

I am using both windows and linux . 

the new microsoft terminal looks good. 

can it be ship to mac osx and linux ?

**Comment by DHowett-MSFT** [comment]
Hi! Thanks for the interest. Since we depend on some parts of the Windows platform, that’s not an option for us. Sorry!

**Comment by DHowett-MSFT** [comment]
#504 dupe

**Comment by dinfyru** [comment]
t_t

**Comment by zinking** [comment]
with windows having 2 kernels now, I'd suggest seriously consider support other platforms.   I might moving back to windows because of this.

**Comment by Biswa96** [comment]
> with windows having 2 kernels now

Any OS can have any number of kernels by virtualization.

**Comment by miguelusque** [comment]
Hi all,

First of all, thank you for this great product. I ❤️ it.

About the following comment:

> Since we depend on some parts of the Windows platform, that’s not an option for us. Sorry!

I understand that you make use of some parts of the Windows platform, but I was wondering if there is no equivalent to that functionality in other Operating Systems, like MacOS or Linux.

Is it so tight the integration with Windows OS which makes so hard to port to other OSs?

Thanks! And congrats again for the great work you are all doing!

Regards,
Miguel

**Comment by zadjii-msft** [comment]
@miguelusque See https://github.com/microsoft/terminal/issues/6074#issuecomment-632028446:



> From https://github.com/microsoft/terminal/issues/4235#issuecomment-574748858
> 
> > We're dependent upon C++/WinRT and XAML Islands (UWP XAML) for our UI. We're also using DX/DWrite for the text renderer. Unless those are ported to linux sometime, then I'd say there's very little chance we ever support linux.
> 
> s/linux/macOS/

**Comment by miguelusque** [comment]
Hi @zadjii-msft ,

I understand the current status, thank you for your swift reply.

Nevertheless, Microsoft has proven to be able to develop software which runs on multiple platforms, i.e.: Microsoft Visual Studio Code, Microsoft Teams, Microsoft Office...

Therefore, I am keen to think that it is not because of technical issues why a MacOS/Linux version is not available yet, but a matter of other priorities and/or project planning.

Once again, congratulations for the great work done.

Regards,
Miguel

**Comment by zadjii-msft** [comment]
Visual Studio Code and Teams are [Electron](https://www.electronjs.org/) applications which are fundamentally web apps, so they're trivial to make cross platform. However, they do come with the burden of the entire Electron runtime, and that's something that we weren't comfortable with on the Terminal team. We wanted to make sure to build a native application so that _in the long run_, the Terminal would have a smaller memory commit and be far more performant than we could ever get with Electron.

Office on the other hand has been around for decades and has an enormous team of engineers. I'm not sure what tech stack they're using, but I'm sure that once they got the apps running cross-platform, it was easier to maintain that. Plus, with their larger teams, it's probably easier for them to maintain two different UI stacks (one for Windows and one for OSX). They likely have a team of engineers for the Windows version and a separate team for the Mac version. With the _4_ of us on the Terminal, I'm not sure it's really feasible for us to try and support an entirely separate UI stack. 

If WinUI, DirectX, and WinRT were available on OSX, then it would be _trivial_ for us to port the Terminal to MacOS. Those are all critical components in how the Terminal is built. Replacing any one of them with a cross-platform solution would be an enormous undertaking, if it's possible at all. 

So you're probably not wrong. There might be replacements for each of those components. We could use (whatever the UI stack on OSX is), OpenGL, and (something?) to replace them. But it absolutely is not a priority for us when we'd rather work on improving the developer experience here on Windows first and foremost. We'd rather be working on hyperlinks in the Terminal (#574 #204), or adding support for a default Terminal application (#492), or tab tearout (#5000), or application theming (#3327), or Mark Mode(#5804), or Quake Mode (#653), or any of the other 1000 open issues on this repo. Adding support for OSX would mean pushing a bunch of those features back by at least a year. 

So that's where I'm coming from.

**Comment by tracker1** [comment]
@miguelusque you might want to take a look at [hyper](https://hyper.is/) It's not quite the same, but offers some similar features and is cross platform.  It's what I tend to use in Linux.  On mac I use iTerm2 and on Windows I'm using Windows Terminal.

**Comment by danielktdoranie** [comment]
> How about make microsoft terminal can be used on mac osx or linux.
> 
> I am using both windows and linux .
> 
> the new microsoft terminal looks good.
> 
> can it be ship to mac osx and linux ?

LOL no thanks ha ha ha

**Comment by DHowett** [comment]
@danielktdoranie was it necessary for you to let everybody subscribed to this repository that you don't particularly care for somebody's _rejected feature request_? No? Well.
