### ISSUE TITLE
Auto Hide Menu Bar

### ISSUE THREAD

**Issue by AmericanY** [microsoft/terminal#5631]
How can i `auto` hide the Menu Bar ?

Also that's will be great if there's option for Menu Bar size, such as `slim` or `classic`
![image](https://user-images.githubusercontent.com/27644047/80550759-68502e00-89c1-11ea-8caa-b859bd89de7e.png)

**Comment by zadjii-msft** [comment]
At the moment, no, since there's really no way to drag the window without it 😆 

You might be interested in #2238 for a borderless mode, or #3327 for "the ability to change the size of UI elements".

There's always of course fullscreen-mode, if you don't really care about being windowed. In fullscreen mode, we'll hide the titlebar as well.
