### ISSUE TITLE
Windows PowerShell is always the default profile even if not existed in settings.json

### ISSUE THREAD

**Issue by wbpluto** [microsoft/terminal#5640]
Windows Terminal (Microsoft Store, upgraded automatically by the Store)
Version: 0.11.1121.0

Windows PowerShell is opened by default every time when start Windows Terminal:
![image](https://user-images.githubusercontent.com/5191513/80578764-93776380-8a3b-11ea-8899-cfd13ea19cd0.png)

**Comment by Varstahl** [comment]
This is a (weird) regression, and this also ignores the `defaultProfile` specified in settings.json.

**Comment by Varstahl** [comment]
@wbpluto this looks like the same issue I had, until I read #3600. Globals are no longer valid in the config, so you must extract everything from it. Amongst the settings that were available in there was `defaultProfile` which selected the default profile to start with.

But it's still weird that without `defaultProfile` defined it just starts a random powershell instead of the first profile available.

**Comment by zadjii-msft** [comment]
@Varstahl you're correct, largely, this is /dup #5458.

It's actually not the `profiles.list` change - in defaults.json we specify that the [default profile](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json#L3) should be [powershell.exe](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json#L30)
