### ISSUE TITLE
Sad to read that terminal isnt actually a new terminal

### ISSUE THREAD

**Issue by 4A47** [microsoft/terminal#5669]
"if terminal is nothing more than a UI wrapper for cmd/powershell, then it'll do little to win over developers and sys admins.... The will stick with far better terminals on other systems."

I was under the impression that this was eventually going to be a replacement for cmd in windows, that was the impression the marketing gave me, but to see that not even simple tab complete functionality is being implemented is very sad.

What on earth are you guys even working on, what is this going to achieve? the only thing it does better than cmder is start quicker, its worse at everything else. What a waste of your time.

**Comment by zadjii-msft** [comment]
I'd like to remind you real quick that when you're contributing to this repository, please make sure you're following our [code of conduct](https://opensource.microsoft.com/codeofconduct/). Thanks!

I think you might have a misunderstanding between the difference between what a terminal is and what a shell is.

* A _terminal_ is (typically) a graphical application that's responsible for displaying the output of commandline applications, and sending input to those applications. Examples include `gnome-terminal`, `xterm`, `mintty`, `putty`, `conhost`, and yes, the Windows Terminal.
* A _shell_ is a commandline application that processes user input and writes output. These are the applications responsible for handling the prompt, executing child processes, etc. Examples include `cmd`, `powershell`&`pwsh`, `bash`, `zsh`, `fish`, etc.

The official company stance is that PowerShell Core is the shell that developers should be using, not `cmd`. [Powershell](https://github.com/powershell/powershell) is receiving constant updates. 

Both `cmd` and `powershell` have tab-complete functionality - I'll admit that `cmd`'s isn't great, but powershell's is pretty good, and highly configurable.

What _we're_ trying to build here is a better _terminal_ application. By building a better terminal, we can make improvements to the the user experience of developers using _any_ commandline application, regardless of which shell they prefer.

**Comment by oising** [comment]
Need to pin this... to the forehead of anyone who conflates shells and terminals.

**Comment by zadjii-msft** [comment]
I think you still don't understand the difference here. 

The "linux terminal" is a collection of technologies - depending on your distro, it's probably something like `gnome-terminal`, running `bash` or `zsh`, with a collection of utilities like `ls`, `grep`, `ps` and others.

With the Windows Terminal, we're just trying to replace the `gnome-terminal` part of that equation. If you don't like powershell, you can still run the linux shells you're used to with WSL:
![image](https://user-images.githubusercontent.com/18356694/80728339-70e15b00-8acc-11ea-9768-82761a28da6f.png)

**Comment by 4A47** [comment]
So im misusing the word terminal, but you know what im talking about when I say the linux terminal, everyone does, nuances of the definition of terminal aside.

Im sure yous will build a really solid and good looking "terminal", but effectively you are building a shiny box to put your old junk in. Most similar programs probably only exist because cmd is so bad, instead of fixing the problem you are adding another solution where many already exist. Not very ambitious for a company like microsoft. Welcome to the future.

**Comment by zadjii-msft** [comment]
> you are building a shiny box to put your old junk in

I mean, WSL is a pretty shiny new toy, if you haven't used it yet I'd recommend it. I'd say it's pretty ambitious - _run all your linux applications directly on windows without needing to recompile them_. That's pretty neat if you ask me. 

Simply put, there's already a team at Microsoft that's working on a commandline shell - that's the powershell team. It doesn't make sense for us as a company to invest in two shells and have them compete with each other. 

> Most similar programs probably only exist because cmd is so bad

> instead of fixing the problem you are adding another solution where many already exist

Here you go confusing the two again. The first clause suggests that there are other programs that exist to replace `cmd`, and those programs would be shells. Then, in the second clause, you're talking about how we're adding another _terminal_ to the ecosystem of terminals. This is why the nuance in the difference between the terms _matters_.

Sure there are problems with `cmd`, but the existence of other _terminal_ applications doesn't mean that they solve `cmd`s problems, and the Windows Terminal isn't supposed to be a solution to those problems. 

Conhost was also bad, yea. It was written 30 years ago, it's hard to maintain, and it's fully of crazy legacy UI behavior that we can't change without breaking some back-compat story. That's why we're building the Terminal to replace the user interface of conhost. Terminal is an improvement over `conhost`, but it's never meant to do anything about `cmd`.

**Comment by 4A47** [comment]
The other terminal apps allow us to use other shells to cover cmds shortfalls - is maybe a better way of putting it. They wouldnt be necessary or anywhere near as widely used if cmd was as good as out of the box linux terminal experience. 

I tried WSL but uninstalled it pretty quickly, I dualboot so I dont really need it.

> Simply put, there's already a team at Microsoft that's working on a commandline shell - that's the powershell team. It doesn't make sense for us as a company to invest in two shells and have them compete with each other.

That makes sense, I wont be using powershell so means windows "shells" are effectively dead to me.
