### ISSUE TITLE
C# code Console.CurorTop and Console.WindowTop don't work

### ISSUE THREAD

**Issue by Thraka** [microsoft/terminal#5695]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1153.0

Any other software? .NET Core 3.1 app
```

# Steps to reproduce

```csharp
Console.WriteLine($"{Console.CursorTop} | {Console.WindowTop}");
Console.WriteLine("Line");
Console.WriteLine("Line");
Console.WriteLine("Line");
Console.WriteLine("Line");
Console.WriteLine("Line");
Console.WriteLine("Line");
Console.WriteLine("Line");
Console.WriteLine("Line");
Console.WriteLine($"{Console.CursorTop} | {Console.WindowTop}");
```

# Expected behavior

Behave the same as **cmd.exe** when the code is run. each value increasing appropriately as the session scrolls.

# Actual behavior

`Console.WindowTop` is always 0. When the session scrolls down past the screen (running a few times) the `Console.CursorTop` always remains the same.

**Comment by DHowett-MSFT** [comment]
The terminal operates like a console whose buffer size is the same as the window size. It was a _mistake_ to allow applications to address characters off the top or bottom of the screen, and fixing it is, unfortunately (for a narrow class of applications), by design.

Sorry!

Happy to go into more detail :smile:

**Comment by Thraka** [comment]
Sounds good! What would I do as a developer on .NET Core/5 platform that wants to be compatible with classic windows cmd prompts, and the newer terminal (that I also assume is more linux friendly too, or behaves the same/similar to other OS terminals)?

**Comment by Crossbow78** [comment]
I don't see why this is good. This was a very useful feature of the classic console, which allowed great text-based visualizations even when they were too large to fit within the window height - the window simply scrolled up and down. Windows Terminal has become useless for this purpose.

I could understand that `Console.WindowTop` is always 0 if that's where the window buffer starts, but then `Console.CursorTop` should also follow that logic and always return the row _relative to the window buffer_ - and also allow to position the cursor on an off-screen row within that buffer.

```
for (int i = 0; i < 100; i++)
{
    Console.WriteLine($"This is row {i}");
}

Console.SetCursorPosition(0, 0);
// On classic console this is row 1
// On Windows Terminal this depends on how far the window has scrolled

Console.WriteLine("Overwriting the top row");
```

**Comment by DHowett** [comment]
> Windows Terminal has become useless for this purpose. … Could you elaborate […]

It was always possible for the *standard Windows Console* to run in a mode where there was no scrollback and no portion of the buffer was off the top of the screen. Applications that were not prepared for that have, unfortunately, been broken for longer than Terminal has existed. 🙂

**Comment by Crossbow78** [comment]
As long as `Console.WindowTop` and `Console.CursorTop` behave consistently I wouldn't call it broken. But does the fact that you could configure the standard console to a mode without scrollback justify Windows Terminal from not supporting off-screen cursor positioning at all?

**Comment by lhecker** [comment]
Architecturally speaking, Windows Terminal aims to become a modern UNIX-style terminal. Those generally do not support what you want. Applications are expected to implement the pagination themselves (which is not too difficult to achieve).

It is possible that this may make a return in the future if we move over to a new ConPTY implementation that supports this. But right now, it is not a priority to make it work, because the focus is on making it work well with WSL, OpenSSH, and others. This is squarely a "eat the cake and have it too" kind of situation if we tried to make both things work (i.e. very difficult).
