### ISSUE TITLE
Activate the function "Do not save commands"

### ISSUE THREAD

**Issue by Aylexx** [microsoft/terminal#5719]
# Description of the new feature/enhancement
This function should delete the executed commands or overwrite them after a restart or with another text.

# Proposed technical implementation details (optional)

**1. Terminals sends typed char
2. PowerShell receive typed char
3. Terminal displays chars**
![grafik](https://user-images.githubusercontent.com/64732227/80913440-ec4d4180-8d44-11ea-98e2-5ebe798283bc.png)

**Comment by DHowett-MSFT** [comment]
You have read the issue from which you copied this text. There is no reason for you to file a second one.

**Comment by Aylexx** [comment]
Which issue do you mean?
@DHowett-MSFT

**Comment by DHowett-MSFT** [comment]
Sorry, there's a lively discussion in #5378 -- people are asserting that it is _possible_, but nobody can tell me how. :smile:

The user who filed that issue has a lot of _friends_ coming over to this repository to keep filing the same requests, and it looked like some of the text in this issue was copied from there, so I thought that it was a clone. It turns out that it isn't (sorry!), but the issue is still a /dupe of #5378.

More information on why it may not be possible in this comment: https://github.com/microsoft/terminal/issues/5378#issuecomment-616883348
