### ISSUE TITLE
Missing icon in taskbar

### ISSUE THREAD

**Issue by kulaeff** [microsoft/terminal#5735]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.11.1191.0
```

# Steps to reproduce
—

# Expected behavior

The icon should be rendered in a taskbar.

# Actual behavior

No item is rendered.
![image](https://user-images.githubusercontent.com/12672487/80977366-4b868100-8e2d-11ea-9653-05c616b2a1b4.png)

**Comment by DHowett-MSFT** [comment]
This is, unfortunately, an issue that appears with the taskbar from time to time. Unfortunately, there isn't anything Terminal can do about it 😦

**Comment by woss** [comment]
my question goes : `So why other apps are never affected but the Terminal is?`

**Comment by elialgranti** [comment]
This issue is still happening and this is one of the top search results for it so here's a solution that has worked for me:

The problem seems to indeed not be related to Terminal but rather to the windows store, and affects other windows store installed apps (e.g. for Outlook also had it's icon missing). To solve the issue:

Reset the windows store by running `WSReset.exe` from an elevated command window, and then restart your PC (restarting Windows Explorer from the task manager may also work, did not check).

Usual disclaimer: This is based on my experience only, there may be other bugs which cause the same symptoms.
