### ISSUE TITLE
Keybindings in new tab dropdown menu are not updated

### ISSUE THREAD

**Issue by DVDAndroid** [microsoft/terminal#5737]
# Environment

```none
Windows build number: Microsoft Windows [Versione 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1191.0

Any other software? No
```

# Steps to reproduce

1. Change keybinding settings
2. Open new tab dropdown menu

# Expected behavior

Updated keybindings for "new tab" and "open settings" actions

# Actual behavior

Old, not updated, keybindings for "new tab" and "open settings" actions

![image](https://user-images.githubusercontent.com/6277172/80994631-3a457080-8e3d-11ea-8726-1207ef3b2845.png)

**Comment by DHowett-MSFT** [comment]
So, this is because the original key bindings are actually still bound. They're all set up in the "default" settings file.

If you replace them by unbinding them, the menu will update.

@zadjii-msft Maybe I'll throw this one on the settings model changes. "Know where a setting came from so we can display what the user expects?"

**Comment by zadjii-msft** [comment]
We absolutely have a dupe for this already, I'm trying to find it in the backlog...
