### ISSUE TITLE
Settings should open with app associated with `.json`

### ISSUE THREAD

**Issue by darcyparker** [microsoft/terminal#5777]
# Environment

```
Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

Open settings and observe `settings.json` opens in `notepad.exe`.

# Expected behavior

I expect `settings.json` to open in the app I have associated with `.json` files.

In `cmd.exe`, I used `assoc` and `ftype` to view my configuration:
```cmd.exe
c:\>assoc .json
.json=sourcecode
c:\>ftype sourcecode
sourcecode="C:\Program Files\gvim\gvim.exe" "%1"
```
And in case you don't lookup `.json` assoc, I tried `txtfile` too
```cmd.exe
c:\>ftype txtfile
txtfile="C:\Program Files\gvim\gvim.exe" "%1"
```
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ftype

# Actual behavior

The settings open in `notepad.exe`.  I expect `assoc` and `ftype` settings to be consulted to open the `settings.json` file.

**Comment by DHowett-MSFT** [comment]
So, the logic that launches Settings uses `ShellExecute()`, just like what happens when you double-click on a JSON file in Explorer.
It only launches notepad if that association _fails_ for some reason.

I'm surprised that that association would work anywhere, because it uses `%C:\Program Files%` instead of `%ProgramFiles%`. . .

**Comment by darcyparker** [comment]
It was a typo. sorry.
