### ISSUE TITLE
The CursorTop position within 2 of the BufferHeight limit is incorrect

### ISSUE THREAD

**Issue by rmaclean** [microsoft/terminal#5815]
# Environment

```none
Windows build number: 10.0.18363.778
Windows Terminal version (if applicable): 0.11.1251.0

Any other software? Reproducible in a variety of shells within Windows Terminal. Tested with: Fish Shell, cmd and Powershell. Can also test with VT 100 commands
```

# Steps to reproduce

Set the cursor top to within 2 lines of the BufferHeight. For example, if the BufferHeight is 30, you could use `echo -e "\e[29;0fHello"`

Another option is with C#, this should print `Hey` on the same line each time:
```csharp
Console.Clear();
Console.WriteLine($"BufferHeight: {Console.BufferHeight}");
var y = Console.BufferHeight - 1;
for (int i = 0; i < 10; i++)
{
  Console.SetCursorPosition(i, y);
  Console.WriteLine($"Hey {i} - {Console.CursorTop} / {Console.BufferHeight}");
  Thread.Sleep(200);
}
```

# Expected behaviour

It should print to the specified row. In the VT 100 example, it should be printed without moving the screen and with the C# example, it should print `Hey` on each line, producing this at the end of the code `HHHHHHHHHHey 9 - 27 / 30`.

 This is the behaviour in Command Prompt as well in Terminal on OSX.  

# Actual behaviour

Moves the content up one and writes to the screen, as if we were exceeding the height of the BufferHeight.

For the C# you will get an output like this:
```none
Hey 0 - 29 / 30
 Hey 1 - 29 / 30
  Hey 2 - 29 / 30
   Hey 3 - 29 / 30
    Hey 4 - 29 / 30
     Hey 5 - 29 / 30
      Hey 6 - 29 / 30
       Hey 7 - 29 / 30
        Hey 8 - 29 / 30
         Hey 9 - 29 / 30
```

# Workaround

Best I have found in my own code is to assume the BufferHeight is 2 shorter than it is and readjust the cursor position that way but it does break other CLI code which does not take this into account.

**Comment by DHowett-MSFT** [comment]
Doesn’t `WriteLine` append a newline, thus pushing the contents of the screen up? That seems critically important to _avoid_ if you care about having the buffer stay in the same place...

**Comment by DHowett-MSFT** [comment]
So, it looks like this reproduces on a conhost instance (without Terminal) where the buffer size is the same as the window size. If you _fix_ the C# reproducer to not include the extra newline (which pushes the entire buffer up, unequivocally, as that's what it's supposed to do) it works fine.

Incidentally, if I take the C# repro and run it on Linux inside xterm (our reference implementation for how terminals should work), I get...

![image](https://user-images.githubusercontent.com/14316954/81443187-cf8c8180-9129-11ea-9c02-d22bd9ac31b9.png)

I'm very close to calling this one "By Design"

**Comment by rmaclean** [comment]
Thanks, that is definitely my misunderstanding then. Thank you
