### ISSUE TITLE
Profile Manager - Like iTerm2 or SecureCRT - There is any plugin?

### ISSUE THREAD

**Issue by fischerdouglas** [microsoft/terminal#5880]
I'm migrating from Mac to Windows.

I use terminal essentialy to ssh/telnet remote access to manager network devices and servers.

I'm used to the profile manager of iTerm2, or even the SecureCRT, to store the informations about the host to connect.

I got really excited with Windows Terminal, but I can't see a way to implement the solutions that iTerm2 or SecureCRT used to provide-me, like:
- Manage Several profiles, and present it with some order and tags(iTerm2, or even folders (secureCRT).
- Integrate passwords based on triggers calling the passwords stored on Keyring(iTerm2), ou passwords stored on the session profile(SecureCRT, not secure method. I know.)

Any Suggestion for that?

**Comment by DHowett-MSFT** [comment]
Unfortunately, we don't have a feature like this right now. We're tracking related work in /dup #1280, but because we're not a dedicated SSH/telnet client we're not going to be doing password storage, keyring integration, etc.

This is something that'll be helped by us having an extension model (#4000), but not something that's in our near-term plan.
