### ISSUE TITLE
clone ssh session support

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/terminal#5978]
# Description of the new feature/enhancement

*first of all, I know Windows Terminal is not a pure SSH connection client, so is this really a reasonable good idea I'm not really sure.*
please consider supporting "clone session", it's really useful for man who has to connect via “springboard machine / machine fortress” and through 2-factor(even 3-factor sometimes) verification/authentication.
application like SecureCRT has this function called "Clone Session". putty has similar "Duplication Session" but useless because that new connection is totally a raw flesh.
# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Thank you for the request! It's possible to _duplicate an open profile_ right now, but it's not possible for us to duplicate anything more than that. Here's why:

The important things about an SSH session are:
* Username
* Server
* Password or Authentication Context

Since the username and the server can be encoded in the commandline, <kbd>ctrl+shift+d</kbd> can easily duplicate them. However, the _password_ (or the authentication information) **cannot** be copied because Terminal is not going to get into the password business. It would increase the security risk of our project, and it's not a good feature for a generic terminal.

We have some requests for SSH session management, however. This might be a /dupe of #1280.

**Comment by jaydu666** [comment]
I need "Duplication Session"  too. using duplicate exist socket, not remember password.
like "openssh controlmaster", but windows not support unix socket.
