### ISSUE TITLE
"Azure Cloud Shell" and "Windows PowerShell" cannot be removed from list of profiles

### ISSUE THREAD

**Issue by davkean** [microsoft/terminal#6016]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.836]
Windows Terminal version: 1.0.1401.0
```

# Steps to reproduce

1. Open Settings
2. Delete Windows Power Shelll and Azure Cloud Shell from the list of profiles and save
3. Go back to Terminal

# Expected behavior

No Windows Power Shell or Azure Cloud Shell in the profiles

# Actual behavior

Both are still listed. If I open up settings again, Azure Cloud Shell has been added back:

```
,
      {
          "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
          "hidden": false,
          "name": "Azure Cloud Shell",
          "source": "Windows.Terminal.Azure"
      }
```

Powershell isn't listed, but still exists in the profile list.

**Comment by DHowett** [comment]
So, we have a bit of documentation on this;

https://docs.microsoft.com/en-us/windows/terminal/dynamic-profiles#prevent-a-profile-from-being-generated

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#hide-a-profile-from-the-dropdown

Right now, the Windows PowerShell profile is being _inherited_ from the default settings file. Your settings apply as overrides to the defaults. We’ll try to make this clearer in the documentation.

**Comment by davkean** [comment]
Is this supposed to cause the PowerShell terminal to be hidden?

```
"disabledProfileSources": [ "Windows.Terminal.Wsl", "Windows.Terminal.Azure", "Windows.Terminal.PowershellCore" ],
```

Because while it works for the Azure one, the PowerShell one continues to show.

(By the way, do you own own search for the Terminal docs? It returns zero results regardless of search term)

**Comment by davkean** [comment]
Filed https://github.com/MicrosoftDocs/terminal/issues/19 for the doc issue.

**Comment by DHowett** [comment]
I believe that’s because they only recently went up. If not, I’ll have to take it up with the docs team... we don’t own that bit of infrastructure :/

Right now, the Windows PowerShell profile is being inherited from the default settings file. Your settings apply as overrides to the defaults. You’ll need to add a block that sets `hidden` to `true` for that profile; we originally tried to explain that by slapping down a comment that said “TO HIDE THIS PROFILE SET THE FOLLOWING BOOLEAN TO TRUE”, but we realized that people weren’t reading it.

**Comment by davkean** [comment]
I suppose what's confusing me at this point, was that the Azure Cloud one keeps getting added back to my personal settings. The PowerShell shell one isn't, So at this point its very unobvious how to hide the PowerShell without getting Terminal to recreate the settings.

**Comment by davkean** [comment]
To resolve this situation for those that hit this:

- Held down ALT and Click Settings. This opens the default settings file.
- Copied the PowerShell entry from it and into my personal settings
- Marked it as hidden.

The Azure Cloud Shell just kept getting recreated in my personal settings so that was as easy as marking it has hidden.

**Comment by DHowett** [comment]
That's fair feedback.

Add this:

```json
{                                                     
    /* Windows PowerShell - hidden */                 
    "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", 
    "hidden": true                                    
},                                                    
```

We're tracking making this a dynamic (and therefore detectable and supressable) generator in #5482.

I've got it on my personal backlog to make Terminal _remember which ones it generated_ so if you actively delete one it just won't come back. We were a bit averse to doing this before we had a settings UI because it would've been totally undiscoverable, but ... a blob getting written back into your json every time is ironically _less_ discoverable.

**Comment by DHowett** [comment]
Whoops, you beat me to it. Sorry.
