### ISSUE TITLE
Unable to remove bottom padding 

### ISSUE THREAD

**Issue by metaltermite** [microsoft/terminal#6021]
There is too much bottom padding, which is fine by default, but setting the bottom padding to 0 doesn't reduce the bottom padding to the bottom window margin as you'd expect, there's still a fair amount of padding.

![Annotation 2020-05-20 021735](https://user-images.githubusercontent.com/10378599/82412177-2efb6300-9a41-11ea-8960-3464742f4cb3.png)

(Also Setting bottom padding to -1, doesn't reduce it; setting bottom padding to -2, reduces the padding but the bottom margin gets clipped.)

# Environment

```none
Windows build number:  10.0.18363.836
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

Run any app, such as byobu, that draws a horizontal bar at the bottom of the terminal to gauge the size of the padding. Set bottom padding to 0, "padding": "0, 0, 0, 0"

# Expected behavior

The bottom margin should be flush with the bottom of the terminal window

# Actual behavior

There's still a fair amount of bottom padding.

**Comment by zadjii-msft** [comment]
This is unfortunately by-design. That space that's there on the bottom of the window isn't big enough for an entire row of text, so we just fill it with blank space. That's generally preferable to a row of characters that's only partially visible. Otherwise, the only solution would be to prevent the window from filling the entire screen while maximized, which I'm sure that no one really wants.

Thanks!

**Comment by bkkm78** [comment]
The kitty terminal, for example, has a [`placement_strategy`](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.placement_strategy) property that can be used to configure the placement of the terminal area with respect to the window (and therefore where the paddings are placed). When set to `center`, you get two smaller paddings at the top and the bottom instead of one fat padding at the bottom only, partially mitigating the problem. I guess many would also prefer the `bottom` strategy that moves the padding to the top, as programs like tmux and vim have status bars at the bottom by default.

**Comment by ite-ela** [comment]
Workaround: Set font size and line height. On my resolution (1080p) the font size 12 with 1.5 line height works, or 13 with 1.2 line height. 12pt = 16px. `1080%(16*1.5)=0`

**Comment by tiokr** [comment]
Workaround: Set font size (and line height). Example: my resolution is 1080p. 
I can set either font size 13 and line height 1.2, or font size 12 and line height 1.5. 
12pt = 16px, `1080 % (16 * 1.5) == 0`

**Comment by wakaranakattari** [comment]
I don't know if this issue is still relevant, but "padding": "0, -7, -2, -3" and "scrollbarState": "hidden" helped me. The bottom padding disappears completely, it overlaps the top panel a little, but it doesn't really matter to me, it's very convenient.
