### ISSUE TITLE
Question - generic text rendering?

### ISSUE THREAD

**Issue by dakom** [microsoft/terminal#6036]
I'd imagine a big part of Terminal is solving the general problem of text rendering on the GPU.

Would it be possible to split that into its own open-source repo such that it could be used by other projects?

Ideally it could be somewhat backend-agnostic, something that could serve as a layer that could work with not just DirectX but also Vulkan, OpenGL, WebGPU, Metal, etc.

Just curious :)

**Comment by DHowett** [comment]
Thanks! So, right now, our "generic" text renderer is just called "use DWrite".. Unfortunately, most of the magic is inside there. That makes it a lot easier to run Terminal on Windows and _a lot harder_ to separate it out into a separate project.

I wish we could! Unfortunately, I've gotta close this one out because we can't.

Now, I 100% think our "text buffer" implementation should usable standalone at some point... but maybe that's meaningless...
