### ISSUE TITLE
Please add git branch highlighting like Cmder

### ISSUE THREAD

**Issue by JohnDuncanScott** [microsoft/terminal#6050]
# Description of the new feature/enhancement
Currently to get git branch highlighting working I need to enable Git Bash. However this isn't particularly user friendly. I currently use Cmder as my console of choice. It seems to be able to show branch information when going into any folder with an "ANSI Execution" option, in this case: "cmd -cur_console:R /cGitShowBranch.cmd" (at least that's how I think the feature activates)

It would be really nice to have something like this in terminal. Otherwise I'm not sure why I'd use Terminal over Cmder.

**Comment by DHowett** [comment]
As evidenced by the "GitShowBranch.cmd", this is a shell feature that can be applied to a great many terminals! Cmder is just a wrapper around "Clink", which you can use inside Windows Terminal to get all of the cool weird features you want in CMD.

I'm gonna close this one because it's not really actionable for us. Sorry.

**Comment by JohnDuncanScott** [comment]
Awesome, thanks :)
