### ISSUE TITLE
Feature Request: Bash-style enhancement/replacement for cmd (not WSL or git-bash)

### ISSUE THREAD

**Issue by cloudrootab** [microsoft/terminal#6055]
# Description of the new feature/enhancement
Have an option to switch to more bash-style CMD would be a god send. Basically because CMD is so limited, not just in functionality but there are so many quality of life issues that bash (or similar unix-style ones) do so much better. The Tab-behaviour is just pure gold in a Linux terminal. But it's hampered in CMD. And I was hoping that WT would actually improve things like this.

**Comment by WSLUser** [comment]
That's why Powershell was created....

**Comment by cloudrootab** [comment]
> That's why Powershell was created....

With that reasoning you're saying that Powershell is better than a sh shell? I really didn't expect someone going by the name WSLUser to say that... Interesting. And also, kudos for being constructive dude.

**Comment by WSLUser** [comment]
No but for Windows, Powershell is a far superior shell to cmd and is much more powerful and customizable. I can like bash and powershell. You can even install powershell on Linux. I don't see much of an actionable here for Windows Terminal. They can't mess with cmd because of legacy compatibility. They've already added "won't fix" to plenty of cmd bugs due to that legacy compatibility. Powershell was created to address the limitations of cmd. Terminal addresses issues that Powershell can not as it's a shell, not a terminal.

**Comment by WSLUser** [comment]
If you want bash style, then use bash. WSL is great for that. Powershell can be useful to use for both Linux and Windows. Bash is only good for Linux. Keep that in mind.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #3121 for more discussion.

/dup #3121

[This doc might also be of interest](https://github.com/microsoft/terminal/blob/master/doc/Niksa.md#cmd).
