### ISSUE TITLE
Change Font Opacity 

### ISSUE THREAD

**Issue by DaveMiddleton** [microsoft/terminal#6065]
# Description of the new feature/enhancement
Ability to change the font opacity. In Windows Terminal version 1,  the window opacity e.g. "acrylicOpacity": "0.9" option will set the opacity for the  whole Terminal window, including the fonts. Against a white background, the fonts do not stand out enough and become harder to read. 

# Proposed technical implementation details (optional)
Add an option e.g. "fontOpacity" to set an opacity level other than the one one of the Terminal window.

**Comment by zadjii-msft** [comment]
I mean, the text is already 100% opaque, regardless of the acrylic opacity...

![image](https://user-images.githubusercontent.com/18356694/82677499-bdbcdb00-9c0d-11ea-9847-3993d43e9c70.png)
![image](https://user-images.githubusercontent.com/18356694/82677514-c44b5280-9c0d-11ea-9da4-791c90d4a363.png)

In both the above screenshots, all the text is 100% opaque, even the white text. It's just hard to read in the second because my acrylic opacity is like 0% in that screenshot. You could absolutely change the color of the white or foreground colors to make them stand out more though ☺️
