### ISSUE TITLE
Copying text from CLI

### ISSUE THREAD

**Issue by nistre** [microsoft/terminal#6068]
# Description of the new feature/enhancement
In the standard cmd and PowerShell there is the ability after highlighting (marking) text in the window then by pressing <Enter> one could copy text from the CLI.  In the new Terminal, not saying it has to be the same process as before but also <Right-Clicking> or Ctrl+C after marking does not allow the user to copy text and there should be some way to accomplish this.  If there is a way to copy text I am not aware of it.

**Comment by DHowett** [comment]
Terminal allows you to select text with the mouse and copy it to the clipboard using the mouse or the keyboard. You can then paste it with the mouse or the keyboard.

If you're using OpenSSH 7.7 with vim or tmux, that software is suppressing text selection in the Terminal and not giving you any of the benefits commensurate with it doing so.

**Comment by DHowett** [comment]
(If that's the case, try holding down <kbd>Shift</kbd> while clicking and dragging.)

**Comment by nistre** [comment]
@DHowett can you specify how to use the mouse and keyboard to do this?  I am able to highlight (mark) like I said in the initial post.  While text is highlighted I have tried the following things to copy the text:

1. Pressing the Enter key, this results in running the current command or adding a new line to the CLI and does not copy the text that was highlighted.
2. Pressing Ctrl+C, the exact same result as when pressing Enter
3. Pressing Right-Click, removes the highlight without copying the text and without a context menu to select copy text

**Comment by DHowett** [comment]
Sure. Some of this depends on the settings you are using.

Select text.

To copy with the mouse: Right-click.
We don't have a context menu today, but there's a workitem tracking implementing one.

To copy with the keyboard:
**By default**: <kbd>Ctrl+Shift+C</kbd> and <kbd>Ctrl+C</kbd> are both bound t copy. This only applies if you're using a settings file generated after version 0.11.
If you are using a settings file generated before 0.11(*) (you'll know because there's no version stamp in the file), the default is <kbd>Ctrl+Shift+C</kbd> alone.

You can configure what exact keyboard keys affect copy; check out [the keybinding docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings) for more.

(*): We changed the default, but didn't want to force it on our existing users during the preview.

**Comment by nistre** [comment]
Thank you.  I had to completely remove my older version and reinstall to get the new settings file.  I expected the settings file to get updated through the update process I guess.

**Comment by DHowett** [comment]
Sorry about that. We decided at some point (0.5!) that user settings were _held dear_ and that we wouldn't rewrite them until we had our first after-v1 settings changes that required migration.
