### ISSUE TITLE
Feature request: suppress VT title and prefer profile name (or something else)

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#608]
"Is it also possible to shown a short title instead of the whole path?"

_Originally posted by @wahid in https://github.com/microsoft/Terminal/issues/491#issuecomment-490712361_

**Comment by zadjii-msft** [comment]
We do have a setting (`"showTerminalTitleInTitlebar":bool`) that suppresses the title changing. Now we just need a setting for what to display instead of just "Windows Terminal"

**Comment by DHowett-MSFT** [comment]
That’s for the app, though, not the profile and the tab!

________________________________

**Comment by ObsidianPhoenix** [comment]
I agree, this seems like a good shout, the profile `name` property should be used in the tab title instead of the `commandline` property.

**Comment by timheuer** [comment]
I'm looking at this (it's annoying to me a bit right now).  

I'm struggling to find where the instance of TerminalControl is changing as that's what is happening here: https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/Tab.cpp#L34 and no matter what I've tried to force the TabViewItem.Header to the profile name, it keeps getting reset.

**Comment by ObsidianPhoenix** [comment]
Yeah I was taking a look too. I _think_ the initial title is taken from the console itself as it starts up. And the way Terminal initialises the consoles means that it’s just the exe path by default. 

You can see how it’s hooked up by changing the title from within the console itself - the events hooked up capture this change from within the console itself and updates the tab element in the UI. 

I think we’d need to be careful changing it so that a title change within the console itself continues to allow direct changes from the console. 

Unfortunately I’ve still not figured out a way to set the initial value while preserving the events either. It may just need a manual action as part of the tab creation process, but that would hide something a user puts into their powershell profile script.

**Comment by oising** [comment]
@timeheuer -- it's likely sync'ing with VT sequence OSC 0/1/2 (all are treated equivalently in the terminal although strictly they shouldn't be). Fire up a pwsh instance and try ```"`e]0;new title`a"``` and you'll see the tab header changes as well as the root window's. The reason it's getting overridden every time is that with every repaint of the buffer, it's emitting the OSC sequence to reset the title. So, in order to change the tab header, you'll need to change state in the VT engine itself; ergo you'll need to emit the right code, at the right time. This may or may not be trivial to do. I'm not that familiar with the codebase.

**Comment by oising** [comment]
I'm guessing whenever @miniksa gets proper region invalidation working, the title won't be emitted every frame. Right now the entire buffer is repainted with every keystroke.

**Comment by timheuer** [comment]
> it's likely sync'ing with VT sequence OSC 0/1/2 (all are treated equivalently in the terminal although strictly they shouldn't be). Fire up a pwsh instance and try `` "`e]0;new title`a" `` and you'll see the tab header changes as well as the root window's. 

Interesting!  Thanks for that explanation. 

> You can see how it’s hooked up by changing the title from within the console itself - the events hooked up capture this change from within the console itself and updates the tab element in the UI.
Yeah I see that immediately the TitleChanged event is firing pretty reliably after tab creation (I changed to some hard-coded values as my debugger is not working with breakpoints to follow the code flow :-()
 
> Unfortunately I’ve still not figured out a way to set the initial value while preserving the events either. It may just need a manual action as part of the tab creation process, but that would hide something a user puts into their powershell profile script.
I suppose this warrants actually a PM decision here.  I think the nature of profiles for me is that the 'name' I give it is what I want in the tab header (I don't care really about the Window title as I imagine that is going to go away once the team fixes the XAML non-client area situation to make it draggable while hiding the window title).  This is how I have things configured in ConEmu with my tabs being the names I've provided for the tasks/shell...makes it easier for me to find them.  Path is useless.

**Comment by DHowett-MSFT** [comment]
> Path is useless

For some. For others, the title contains useful information -- the machine they're connected to, how many hops, and what "environment" they're in!

This'll be a profile-level feature, and it might require some of the `Tab` changes that are going on in #825. They probably clear up ownership of a few of the Control/Tab/App areas.

**Comment by timheuer** [comment]
Fair enough -- beauty in the eye of the beholder and all :-D.  In a heavily multi-tabbed UI experience though, this information gets long and truncated (or should) so that the usefulness fades a bit.  Take a look at any heavy user of tabs in a browser.  Also please don't assume massive monitors for users and this won't happen -- I'm not a multi-mon user and my screen space is valuable to me.

Either way, having a PM call here @cinnamon-msft may be the right path to clarify desired behavior before proceeding.

**Comment by mdtauk** [comment]
The teaser concept video shows a status bar at the bottom of the app.  Some of that information could be placed there maybe @timheuer

**Comment by cinnamon-msft** [comment]
I was just having a conversation about this today.

Ideally, the title of tabs will be configurable by the user, either with the path, shell name, name of their pet, etc. all configurable within the profiles.json file.

Additionally, the status bar shown in the video adds another option of where you could display the path if that's something important to you. This feature hasn't been designed yet, so that'll be a little ways out.

**Comment by zadjii-msft** [comment]
See, I'm thinking it should be either 2 or three states:
1. Use title from terminal (this is what we have today)
2. Use a custom string. This could default to the profile name (if we had settings UI), or the user could customize it to whatever.
3. Use profile name. This one feels like a special case of 2.


If we went with just 2 modes, we could do it in the two possible ways:
1. Add an optional 'titleText:string' string to the profile. If that's set, then we'll display that string instead of the terminal's title. 
  - this has the downside of not defaulting to the profile name. The user would manually need to set that string.
  - if the profile name changes, then the user would have to manually change this as well.
  - it might not be abundantly clear that `titleText` means we'll be using that instead of the terminal's title, but ideally the settings UI will explain this better, and the actual key doesn't matter so much.
2. Add a `useTerminalTitle:bool` and optional `titleText:string` to the profile. If `useTerminalTitle` is set, then we'll use `titleText`, if it's set. If `titleText` isn't set, then we'll default to the profile name.
  - this has the upside of defaulting to the profile name. 
  - this has the downside of having two settings the user needs to maintain, as opposed to one.
  - could people be confused that having `titleText` set to something, but `useTerminalTitle:false` does _nothing_?

Thoughts? 

<hr>
PS:

> I don't care really about the Window title as I imagine that is going to go away 

The window title will still be used, even with non-client tabs, for the alt-tab view and other shell things:

![image](https://user-images.githubusercontent.com/18356694/57864745-115a4480-77c2-11e9-9b29-81cd842635ff.png)

**Comment by timheuer** [comment]
I wouldn't personally create a new property.  profile:name exists and so early on that you could *state* this is what it is and where it will be used (frankly the only place it seems to be used now is the menu).  Having name and titleText in the profile seems redundant to me and has issues with what you point out (someone may/may not change both).  Feels to me:

- add ```useProfileNameAsTitle``` and default to false (looking at conemu as an example here they use the exe)
- keep ```name``` and make that the displayed value if above is set to ```true```
- if the full shell exe is used, truncate it at least.  IMO the full path in the tab can get long and occupies space (open 5 powershell tabs on a laptop).  Again, conemu inspiration here just shows me 'powershell.exe' unless i rename it
- OPTIONAL: support rename from the tab (if i right-click on the tab 'Rename' -> then that sets/resets profile ```name``` + sets the ```useProfileNameAsTitle``` to true

Also, ack on the alt+tab view showing window title.  Thanks for the reminder.  Personally I think that should be displaying "Windows Terminal - <profilenameoption>"

**Comment by mdtauk** [comment]
Tabs at the top, means no Window Title, but Tabs at the bottom would be different.

![image](https://user-images.githubusercontent.com/7389110/57870781-b9423300-77ff-11e9-8e8f-7b610a7545de.png)

Then there is the Status Bar which could display various bits of information.  Tabs at the top could mean a status bar below the console view, or it could be part of the console view itself, and thus customisable and monospaced.

![image](https://user-images.githubusercontent.com/7389110/57871663-c19b6d80-7801-11e9-939a-d808667c0fe3.png)

But then you could have each tab appear in Alt+Tab and the Taskbar Icon hover.  So perhaps.

**Windows Terminal** - App Name / Window Title
**Ubuntu 18.04** - Profile Name / Tab Text
**Windows Terminal - Ubuntu 18.04** - Alt+Tab preview text

**Comment by zadjii-msft** [comment]
@timheuer I was trying to design for the fact that some people might want to set the title to something other than the profile name. I don't really know _why_ you'd want that, but as @cinnamon-msft said:

>  the title of tabs will be configurable by the user, either with the path, shell name, name of their pet, etc. 

So someone could have the profile be named "Foo" and the tab text still say "Bar". Or even have the name be Powershell and the title text be `pwsh.exe`.

**Comment by timheuer** [comment]
Yeah, we should really define what profile name means...because you kind of already have an internal identifier, so if it isn't the public identifier, than what is it...so I think it really needs to be clarified what ```name``` is going to be used for.  As you said I don't know why you would want name "foo" but display "bar"

**Comment by gaohongkui** [comment]
> Tabs at the top, means no Window Title, but Tabs at the bottom would be different.
> 
> ![image](https://user-images.githubusercontent.com/7389110/57870781-b9423300-77ff-11e9-8e8f-7b610a7545de.png)
> 
> Then there is the Status Bar which could display various bits of information. Tabs at the top could mean a status bar below the console view, or it could be part of the console view itself, and thus customisable and monospaced.
> 
> ![image](https://user-images.githubusercontent.com/7389110/57871663-c19b6d80-7801-11e9-939a-d808667c0fe3.png)
> 
> But then you could have each tab appear in Alt+Tab and the Taskbar Icon hover. So perhaps.
> 
> **Windows Terminal** - App Name / Window Title
> **Ubuntu 18.04** - Profile Name / Tab Text
> **Windows Terminal - Ubuntu 18.04** - Alt+Tab preview text

Your interface looks cool. Can you share your profile with us? My interface looks ugly, even without icons.
![image](https://user-images.githubusercontent.com/38203359/57897277-a9216680-7886-11e9-96b2-7dd6681722dd.png)

**Comment by mdtauk** [comment]
Those are just design mock ups I made to try to illustrate ideas as I contribute on here

**Comment by phuclv90** [comment]
by default PowerShell starts with the "Windows PowerShell" title, so terminal should also use that

**Comment by DHowett-MSFT** [comment]
By default, terminal uses _whatever title the shell sets_, so if you’re seeing a path instead of the words “Windows PowerShell,” I’ve got some bad news for you: that’s what powershell is doing _by default._

**Comment by phuclv90** [comment]
@DHowett-MSFT but why do I see "Windows PowerShell" when I start PowerShell separately instead of its path by default?

**Comment by DHowett-MSFT** [comment]
Ah, I see! When you launch Windows PowerShell the title is inherited from the shortcut. Since the Terminal can't launch powershell from its shortcut, it can't find that name. Interesting.

**Comment by DeChrist** [comment]
@zadjii-msft About:
> < snip >
> Use a custom string. This could default to the profile name (if we had settings UI), or the user could customize it to whatever.
> < snip >
> Add an optional titleText:string string to the profile. If that's set, then we'll display that string instead of the terminal's title.
> 
> this has the downside of not defaulting to the profile name. The user would manually need to set that string.
> < snip >
> **Thoughts**?

If a customizable setting like `titleText:string` is made available in the profile, it would be nice to support "expressions", so that the title can be fixed in part, but have a controlled variable part allowing to distinguish multiple instances easily, **according to the user's preference**.
As a concrete example (not for syntax itself!): the [ARM Template Syntax](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#syntax). 

For instance (using [C# string Interpolation syntax](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) here):

- "{tabIndex} - {profileName}" would become
  - "1 - Console"
  - "2 - Windows PowerShell"

**Comment by DJackman123** [comment]
I really like this idea with the ability to insert pre-defined strings into the tab title like tabIndex, profileName, and also the title coming from the shell.  For the shell title, I'd also like to be able to run that title through a regular expression replacement so I can extract the most important part for display in the tab.  That way I can see more tabs at once and they can all tell me what I need to know.

**Comment by DeChrist** [comment]
Hi @zadjii-msft 
I support the logic of your decision.
Should the request for "templated variables" be kept in a separate Feature Request?

**Comment by DHowett-MSFT** [comment]
From @carlos-zamora, @cinnamon-msft,
For v1 we'll tackle:
* Setting the title to a string specified in profile.json
  * Consideration: If we want the title to be the same as the profile name, do we introduce a trinary state, or do we expect the user to set `{"name":"Powershell", "title":"Powershell"}`?
* Not setting the title, letting the connected console application control it.

For v>=1.x, we shall split out custom string interpolation for the title into a new deliverable.

**Comment by DJackman123** [comment]
My opinion is that if in the future there will be a way to customize the title with string interpolation then it would be wise to not add any additional complexity now to support inheriting the name as the title (like a trinary state) that would need to be supported in future versions.  So, just keep it simple and have the user set the same value for both name and title if that's what they want.  
I'm happy to contribute here if that's acceptable.

**Comment by shanselman** [comment]
Why not just default to the NAME which already exists in the Profile?

**Comment by DHowett-MSFT** [comment]
Right, yes, but again: if it costs nearly zero additional work to make it customizable, we should. That requires us to answer the question in [this comment](https://github.com/microsoft/terminal/issues/608#issuecomment-501927732).

**Comment by mdtauk** [comment]
When creating a profile via the Settings UI, the internal name for the profile, should come from a user set "Profile Name" property, and that string would appear in the Tab Title, New Tab menu, or Profile picking UI within Settings.

**Comment by DHowett-MSFT** [comment]
Okay, let me break this down.

1. Some users want the title in the tab to match _the title set by the application_
![image](https://user-images.githubusercontent.com/14316954/59708046-d54b4280-91b8-11e9-8cb6-3cffbfe40a7e.png)
2. Some users want the title in the tab to match _the title of the profile_
![image](https://user-images.githubusercontent.com/14316954/59708076-e4ca8b80-91b8-11e9-87a9-157905b74f8c.png)
3. Some users want the title to be specified separately from the profile _or_ the application.
![image](https://user-images.githubusercontent.com/14316954/59708111-f6139800-91b8-11e9-9ac0-f4ed050ea1c8.png)

The question is not "how do we store the profile name." (re @mdtauk)

The question is:

If we are designing a robust system that allows a user to specify _one of three options_ (`use app title`, `use profile title`, `use *THIS* title`), **what is most reasonable?**

### A
The easiest way to support all of them is to introduce a nullable _string_ setting, `title`. The downside to `title` is that the user must repeat themselves if they want number 2. Here's what it looks like.

1. `"name": "CMD", "title": null`
![image](https://user-images.githubusercontent.com/14316954/59708046-d54b4280-91b8-11e9-8cb6-3cffbfe40a7e.png)
1. `"name": "CMD", "title": "CMD"`
![image](https://user-images.githubusercontent.com/14316954/59708076-e4ca8b80-91b8-11e9-87a9-157905b74f8c.png)
1. `"name": "CMD", "title": "Whatever, I don't care"`
![image](https://user-images.githubusercontent.com/14316954/59708111-f6139800-91b8-11e9-9ac0-f4ed050ea1c8.png)

### B
The slightly more annoying way to support all of them is to introduce _two settings_, _boolean_ `useAppTitle` and _string_ `title`. This requires two settings. It's more annoying. It also introduces a fourth state that doesn't matter.

1. `"name": "CMD", "useAppTitle": true`
![image](https://user-images.githubusercontent.com/14316954/59708046-d54b4280-91b8-11e9-8cb6-3cffbfe40a7e.png)
1. `"name": "CMD", "useAppTitle": true, "title": "This is ignored"`
![image](https://user-images.githubusercontent.com/14316954/59708046-d54b4280-91b8-11e9-8cb6-3cffbfe40a7e.png)
1. `"name": "CMD", "useAppTitle": false, "title": null`
![image](https://user-images.githubusercontent.com/14316954/59708076-e4ca8b80-91b8-11e9-87a9-157905b74f8c.png)
1. `"name": "CMD", "useAppTitle": false, "title": "Whatever, I don't care"`
![image](https://user-images.githubusercontent.com/14316954/59708111-f6139800-91b8-11e9-9ac0-f4ed050ea1c8.png)

**Comment by mdtauk** [comment]
@DHowett-MSFT  Would providing just a simple CheckBox saying:
> [X] Use profile name in tabs
And then requiring a Name for each Profile, solve this issue?

If the option is unchecked, it displays the system provided text?

**Comment by DHowett-MSFT** [comment]
Since the settings UI is not looming on the horizon, and its implementation hasn't even started, I am forced to care about _what that checkbox does to the settings file_ :smile:

Also, that still doesn't allow for case 3.

**Comment by DHowett-MSFT** [comment]
Also, just in general: the settings file is the property of the user, and we have to be good stewards of it. Even if we have a nice fancy settings UI, there will be people who want to edit `profiles.json` themselves in their own text editors and their own tools. We can't just use it as a dumping ground for poorly-thought-out blobs of json. We _have_ to consider the schema when we're designing settings, even if we're approaching it UI first.

**Comment by mdtauk** [comment]
> Since the settings UI is not looming on the horizon, and its implementation hasn't even started, I am forced to care about _what that checkbox does to the settings file_ 😄
> 
> Also, that still doesn't allow for case 3.

Sure case 3 is not covered - but do all three scenarios need to be supported?  And of course, you could enforce the JSON to make Profile Names a requirement for a valid profiles.json file.  The CheckBox for overriding the tab text could also be added as a boolean

**Comment by zadjii-msft** [comment]
@DHowett-MSFT great work breaking that down, esp with screenshots.

Considering that case B.4 is useless, I'd lean towards implementing **A**.

At some point, we're going to need to just commit one way or another. In this case, there's pros and cons for both implementations, and I don't think there's a _clear_ winner. As long as the pros and cons are included in the spec doc, I'm fine just picking one, so long as we can come to a consensus.

**Comment by ObsidianPhoenix** [comment]
I think there’s an additional case to consider: runtime modification of the title. I may want my initial title to be “powershell” by default, but to have the ability to change it within the tab itself whilst performing a specific action.

It’s possible that you could handle this by forcing the tab title before handing it over to the users control, and simply allowing modifications like we do at the moment. However I think some applications (e.g. telnet maybe?) which change the window title when executed - that could be contrary to what a user wishes, but supporting the ability might have to just accept this as a side-effect.

I’m not necessarily averse to the decision that we simply don’t allow this to happen when title is specified, but I think we need to explicitly call it out as a decision point.

**Comment by DJackman123** [comment]
I think this falls into the string interpolation flexibility, which is planned for post v1.0.  Because of this, I would prefer implementing plan A given above.  If we want to implement any more complexity than that, then we should take the time to design what the end goal looks like for string interpolation and runtime title modification then decide which portion of that goal we want to implement now.  I don't want to see us implement something now that winds up making the end goal harder to achieve.
Is there another issue open for discussing the post-v1 plan?

**Comment by dhavalhirdhav** [comment]
Can we make it as simple as this:

"title":"{Profile}"
"title":""
"title":"Hardcoded title"

if title is blank, we use the title provided by the application. If title is {Profile} we use title provided by the profile, and if title has string without {} it takes the title specified as is.

With introduction of { } syntax we can open up lots of possibilities.

**Comment by zadjii-msft** [comment]
For the record, I'm moving discussion of _dynamic_ strings in the title to #1320. For this task (and v1.0), we're gonna just focus on getting a static string to override the terminal's title text.

**Comment by Jaykul** [comment]
I think whatever you do here, you **should not** (especially in _this_ Terminal app) choose a default which results in ignoring the title sent by VT ... 

I've been using consoles and terminals a lot for a long time -- and I _set_ the title in my prompt (and in terminals where I have a status bar, I set that too). In the PowerShell world, my `PowerLine` prompt module sets the title automatically, and allows you to override the title with calculated values (don't use this one, it's really long, and is an example only):
![image](https://user-images.githubusercontent.com/192942/59959063-36f00300-947e-11e9-8179-f5036371acb2.png)

I won't fight against the including of a settable `"forceTitleTo" : "Text"` type of property -- but it needs to be a separate property that's _not_ set by default. It should definitely not just default to using the profile name. And frankly, _every time someone asks for the feature_ we should tell them they can set it with `ESC ] 2 ; <title>` in their profile, before we tell them about the feature to override it.

**Comment by fredless** [comment]
until this gets addressed, I'm just:
```
"commandline" : "cmd.exe /k \"title cmd\"",
"commandline" : "powershell.exe -NoExit -Command \"& {$host.ui.RawUI.WindowTitle = 'ps'}\"",
"commandline" : "python.exe -i -c \\\"import ctypes; ctypes.windll.kernel32.SetConsoleTitleW('py')\\\""
```

(and yeah I know there are multiple clever ways to do this)

**Comment by MCKLMT** [comment]
What about WSL? 🤔

**Comment by fredless** [comment]
> What about WSL? 🤔

More tricky but also way more flexible.  bash in many distributions (re)sets the window title at every prompt via escape codes on PS1.  For example, WSL Ubuntu 18.04 ships with this default in your user's .bashrc:
```shell
case "$TERM" in
  xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
  *)
    ;;
esac
```

Pay attention to what appears between `\e]0` (literal "ESC"+"]"+"0") and `\a` (bell or alarm).  
Changing this to:
```shell
 PS1="\[\e]0;ubuntu\a\]$PS1"
```
..yields something that suits my needs:
![image](https://user-images.githubusercontent.com/16697069/60307348-12ba7900-98f9-11e9-9a80-cc3322f1dfbf.png)

**Comment by fredless** [comment]
thanks for that tabTitle patch - haven't built this yet, but looking forward to removing my workarounds
