### ISSUE TITLE
Windows PowerShell opens ADAL forms page in background

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoft/terminal#6084]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software? Yes - MSOnline/AzureAD/ExchangeOnlineManagement Windows PowerShell modules.
```

# Steps to reproduce

When executing Connect-MsolService, Connect-AzureAD, Connect-ExchangeOnline, or any cmdlet that will invoke a Modern Authentication, the webpage/authentication form window opens behind the Windows Terminal window.  This doesn't happen in Windows PowerShell when not using it in Windows Terminal.

# Expected behavior

The webpage/authentication form window should open in the foreground so that you know it's there, and can enter your credentials.

# Actual behavior

 Currently, you have to notice that a Windows PowerShell taskbar icon has spawned, and switch to it manually.

**Comment by DHowett** [comment]
Hey, really sorry about that. This is a known limitation with how window handling is done in Terminal. There's a bad old console API that let a text-mode app get a window handle to present on top of. SSH, VSCode, Terminal, etc. do not work with it because they may not have a single window (or may not have a window at all.)

More details in /dup #2988

**Comment by JeremyTBradshaw** [comment]
Thanks. I couldn't find the original issue when searching, so I'm happy to know there is one already.
