### ISSUE TITLE
winget install -  There’s a problem with Windows Terminal. Contact your system administrator about repairing or reinstalling it.

### ISSUE THREAD

**Issue by felickz** [microsoft/terminal#6115]
# Environment

> PS\> [Environment]::OSVersion
> 
> Platform ServicePack Version      VersionString
> -------- ----------- -------      -------------
>  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

# Steps to reproduce

> PS\>winget install terminal
> Found Windows Terminal [Microsoft.WindowsTerminal]
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://github.com/microsoft/terminal/releases/download/v1.0.1401.0/Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle
>   ██████████████████████████████  18.1 MB / 18.1 MB
> Successfully verified installer hash
> Starting package install...
>   ██████████████████████████████  100%
> Successfully installed.

# Expected behavior
App launches

# Actual behavior

There’s a problem with Windows Terminal. Contact your system administrator about repairing or reinstalling it.

**Comment by felickz** [comment]
downloading msix has same behavior - any better way to get logs?

**Comment by DHowett** [comment]
Does it tell you an error code number when you try to install the msix yourself?

**Comment by chrismartain** [comment]
Hi everyone, Is there any solution to this issue yet?  I am currently dealing with the same situation after installing windows Terminal on windows server using winget.

**Comment by jamespack** [comment]
AppX Deployment operation failed for package Microsoft.WindowsTerminal_3001.18.3181.0_neutral_~_8wekyb3d8bbwe with error 0x80073D19. The specific error text for this failure is: error 0x80070002: While processing the request, the system failed to register the windows.sharedFonts extension due to the following error: The system cannot find the file specified. Im seeing this error in connection with this issue. There are others but they are way less specific and seem like symptoms rather than causes to me.

**Comment by jamespack** [comment]
Uninstall/Reinstall seems to fix it. At least in my case.
