### ISSUE TITLE
Install failure: Invalid value for registry

### ISSUE THREAD

**Issue by hholst80** [microsoft/terminal#6127]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.264]
```

# Steps to reproduce

Download and try and install Microsoft Terminal from Github releases.

# Expected behavior

Microsoft Terminal should install.

# Actual behavior

![bild](https://user-images.githubusercontent.com/6200749/82647945-3a07ec00-9c17-11ea-9dcf-6b130e63bd07.png)

**Comment by DHowett** [comment]
It sounds like your app installer application is damaged; are you able to install other APPX or MSIX applications?

(This looks like an issue that is outside of Terminal's control, so I'm going to close it. Please let me know if it works for other apps.)

**Comment by hholst80** [comment]
Rhetorical question: Should we blame the operating system (outside the control of the app) for any out of memory issue occurring in case of a memory leak?

It certainly looks like its your app that is stating the issue? Certainly we should try and figure out what registry key and value that cannot be set and then determine what the root cause is. 

I have already validated that the same download works with another user on the same machine. I will try and validate that an instance of that esoteric installer type work on my system with the same user. I have never run across them before so I will have to search for an app first. Unless you can hint me of another app which uses the same format?

**Comment by alexander-miglis** [comment]
I faced the exact same issue, it was fixed by resetting the app installer. You find it under “Apps & Features“ find the app called “App installer”, click on it and select Advanced), then press reset.

This app installer seems to be running in an appcontainer so that would probably explain why it would work for other users on the same machine.

**Comment by Harlloh** [comment]
Resetting the App installer worked for me too, thank you @alexander-miglis

**Comment by TheMR-777** [comment]
> I faced the exact same issue, it was fixed by resetting the app installer. You find it under “Apps & Features“ find the app called “App installer”, click on it and select Advanced), then press reset.
> 
> This app installer seems to be running in an appcontainer so that would probably explain why it would work for other users on the same machine.

There was no "App Installer" in my case, however I previously had that, and always kept it updated.
To resolve that, 
- I first downloaded the installer package from here https://aka.ms/getwinget
- Since there was no installer to install the installer, I ran the PowerShell command to install the installer, like this:
```bash
Add-AppxPackage -Path "PathToTheInstaller.msixbundle"
```
- Everything is good since then :)
