### ISSUE TITLE
Terminal Graphics Corruption

### ISSUE THREAD

**Issue by tomspilman** [microsoft/terminal#6142]
# Environment

```
Windows build number:  Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable):  1.0.1401.0

Been running various graphics tools, half dozen copies of VS, dozens of Chrome tabs, etc.
```

# Steps to reproduce

I unfortunately don't have clear steps...  it just started happening out of the blue.

I opened terminal and had three tabs open for around 12 hours.  In that time i did several commands in each tab and went back and forth between them and other tasks.

Some time after about 12 hours i looked up and various graphical elements were corrupted.

# Expected behavior
Not having the UI corrupted.

# Actual behavior
The window frames, tabs, dropdowns, dialogs are corrupted across the terminal:

![image](https://user-images.githubusercontent.com/103522/82685169-61f84f00-9c19-11ea-9c2a-780f081f83b9.png)

![image](https://user-images.githubusercontent.com/103522/82685202-6f153e00-9c19-11ea-8a8d-785a00e701b6.png)

![image](https://user-images.githubusercontent.com/103522/82685120-4ee57f00-9c19-11ea-86b1-1472332fbfcf.png)

But note that the actual content of the terminal windows are not corrupted:

![image](https://user-images.githubusercontent.com/103522/82685420-c9160380-9c19-11ea-8400-3dda6b5a450a.png)

Note closing and reopening the terminal application didn't fix the corruption.

No other applications were affected.  Visual Studio, Chrome, Skype, Calc, Discord, etc all looked normal and fine.

**Comment by zadjii-msft** [comment]
Huh, something's real messed up with the corner radius on all those XAML elements. I don't know enough about XAML to know what might have caused that. Maybe @stmoy, @michael-hawker, or @mdtauk might know more?

**Comment by stmoy** [comment]
cc: @ranjeshj @chingucoding @chigy - this is very mysterious!

**Comment by chingucoding** [comment]
This seems like an issue with the rendering of the corner radius as @zadjii-msft pointed out. Maybe this is an issue solely caused by XAML islands? 

What surprises me a bit is the fact that restarting the app also doesn't work. @tomspilman is there anything you might have done in that time that could be remotely related to this?

Also if it's not too much for you, could you check if other apps that use WinUI and use corner radius exhibit the same behavior? A good example to check if the [XAML Controls Gallery](https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt?activetab=pivot:overviewtab) also has rendering issues.

Thank you for help!

**Comment by tomspilman** [comment]
@chingucoding 

> is there anything you might have done in that time that could be remotely related to this?

The only other thing i can think of is that i did launch Terminal with "run as Administrator".

> A good example to check if the XAML Controls Gallery also has rendering

Yes it does in places:

![image](https://user-images.githubusercontent.com/103522/82759128-d6192b00-9db0-11ea-8d2f-297989e49d9f.png)

So it seems this is system wide somehow?

**Comment by chingucoding** [comment]
Okay, it seems that the UWP/WinUI rendering stack has an issue with rounded corners on your machine, since other UWP apps are affected too.

So maybe this issue can be moved over to WinUI @ranjeshj @stmoy @zadjii-msft as it doesn't seem to be limited to terminal.

This is probably a long shot, but could you check in the event viewer if there is an event in the timeframe where this issue occurred? Also did you install an update recently that could cause this, though I highly doubt that.

**Comment by tomspilman** [comment]
> So maybe this issue can be moved over to WinUI 

Do you need me to do that @chingucoding ?

> This is probably a long shot, but could you check in the event viewer if there is an event in the timeframe where this issue occurred?

Lots of random info and errors but nothing that seems related to this.


> Also did you install an update recently that could cause this, though I highly doubt that.

Not that i am aware of.

**Comment by chingucoding** [comment]
> Do you need me to do that @chingucoding ?

You can create an issue over at the [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml) or we can wait for a Microsoft member to move it over. Hopefully they have more ideas on how to solve this issue or what the next steps are.

**Comment by zadjii-msft** [comment]
Thanks for investigating @chingucoding! I've moved this to https://github.com/microsoft/microsoft-ui-xaml/issues/2550
