### ISSUE TITLE
UI: align design with other UWP apps

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#615]
It seems the design isn't following other Windows/UWP apps/components. The `+` button to add a tab seems very big and bold (it's even bigger than close/minimize window buttons).

Here is a comparison with Edge:

![image](https://user-images.githubusercontent.com/199648/57436474-093d5a80-7240-11e9-91f0-f3a23b1a9398.png)

Also, it's positionned at the right edge of the window instead of being next to the last tab like in Edge.

**Comment by zadjii-msft** [comment]
Yea, the design of the tab row right now is under pretty active updating. There are actual UX designs/mockups that are being worked on by the design team currently, but until they're finalized, we don't want to waste time futzing with the styling if it's just going to change.

I'm also on board with the plus button being at the end of the tabs, instead of at the end of the tab row, but some people actually really like it where it is. I think this is something we're inevitably going to have a setting to control :)

**Comment by warpdesign** [comment]
I see: it's not needed to waste time until the design is ready indeed. I also have my preferences, but above all I like consistency across every app: I hope all teams will share the same UI/Design/components :)
