### ISSUE TITLE
Use PSHOME in settings.json

### ISSUE THREAD

**Issue by Neur1n** [microsoft/terminal#6168]
# Description of the new feature/enhancement
When I'm trying add Powershell Core to Windows Terminal and specifying the `icon` option, I have to input the full path of the icon say `E:\\ProgramFiles\\PowerShell\\7\\assets\\Powershell_av_colors.ico`. This is inconvenient when I clone the settings.json file to another computer in which Powershell Core is not installed in the same path. Hence it will be great if one can do something like

```json
"icon": "$PSHOME\\assets\\Powershell_av_colors.ico"
``` 

I've done some search and haven't found a solution nor a related issued yet. Any help is much appreciated.

**Comment by DHowett** [comment]
Unfortunately, PSHOME is a powershell variable that is generated by powershell when it starts up, and is only visible to the powershell session. Terminal can’t know it because it isn’t exposed to anybody but powershell.

You can set any environment variable you would like, however, and use it with the traditional windows environment variable syntax.
