### ISSUE TITLE
The Ime composition string is overlapped with background text.

### ISSUE THREAD

**Issue by heroboy** [microsoft/terminal#6192]
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18362.836]
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce

1. type some text like "abcde"
2. move the cursor to the beginning
3. switch ime to Microsoft Pinyin
4. type some text like "xxx"
5. see the screenshot

# Expected behavior

Like cmd.exe or other input control, draw a background for the composition text.

# Actual behavior

![图片](https://user-images.githubusercontent.com/54468/82853192-9fb9e800-9f37-11ea-9e7b-a655306ede6c.png)

**Comment by Hamayama** [comment]
Same problem occurs with MS-IME Japanese.

Microsoft Windows [Version 10.0.18363.1139]
Windows Terminal version (if applicable): 1.3.2651.0

![3001_winterm_issue_6192_ime](https://user-images.githubusercontent.com/4497079/97947584-0c7fbb00-1dd1-11eb-8004-acdd92df62a2.png)

**Comment by furuki328** [comment]
I have same problem in Japanese IME. And this problem is reported in some Japanse Blogs at the same time of this issue starts.
Please change background color of IME converting string from transparent to opaque. It is Console Host's solution.
![image](https://user-images.githubusercontent.com/28430794/147824086-d8c4dd7c-0206-457a-b393-c2bb206834a8.png)
"すこし" is inserting IME converting string with opaque background at Cosole Host(vim.exe).

**Comment by lhecker** [comment]
We just published a major update to our IME implementation in the nightly Canary branch. It was rewritten from the ground up and has tons of improvements! If you're interested in trying it out, you can get it here: https://aka.ms/terminal-canary-installer
If you already have the Canary build installed, you can use this link to force an update.

If you encounter any issues or have any suggestions, or if you simply like/dislike the changes, please let us know! Thank you for bearing with us. 😊
