### ISSUE TITLE
When a non-default profile is launched the settings of the default profile are used.

### ISSUE THREAD

**Issue by astitvapandey** [microsoft/terminal#6202]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

Set default profile of Windows Terminal to Ubuntu (for example).
Open cmd and run the command 'wt cmd' to run Windows Terminal in cmd mode (for example)

# Expected behavior

Windows Terminal launched in cmd mode with profile settings of cmd profile.

# Actual behavior

Windows Terminal launches in cmd mode but with the profile settings of Ubuntu (default) profile.

![image](https://user-images.githubusercontent.com/64017433/82901274-57241e00-9f7b-11ea-998c-2370ca6d77e8.png)

**Comment by zadjii-msft** [comment]
If you'll want to use the profile settings of your "cmd" profile, you'll need to use `wt -p cmd`. Otherwise, `wt cmd` simply runs your _default_ profile with the commandline `cmd`.

This does seem like a valuable docs gap on https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows though, so I'll move this issue there.
