### ISSUE TITLE
Keep external CLIs in Windows Terminal interface

### ISSUE THREAD

**Issue by windingtheropes** [microsoft/terminal#6271]
Keep external CLIs, like DiskPart inside the Windows Terminal interface rather than opening up the diskpart interface resembling command prompt.

This would make using Windows Terminal a more oragnized and consistant experience, because you could access all types of CLIs in a single app, Windows Terminal, like DiskPart. 

By opening separate external CLIs (like DiskPart) in Windows Terminal, they should stay contained inside the tab that the CLI was opened in, similar to how in C# you use UseShellExecute = false to execute the process in the same console Window.

**Comment by zadjii-msft** [comment]
Looks like the only reason that `diskpart` runs in an external console window is because it self-elevates. If you simply run `diskpart` from an already elevated Terminal instance, it'll run in the existing window:

![image](https://user-images.githubusercontent.com/18356694/83408760-d0d36600-a3d8-11ea-973d-622e9582ab0b.png)


See also #1032
