### ISSUE TITLE
wsl --unregister doesn't cause Linux distribution to disappear from New Tab drop-down list

### ISSUE THREAD

**Issue by matkaz** [microsoft/terminal#6274]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 1.0.1401.0

WSL enabled
Ubuntu 18.04 LTS
Ubuntu 20.04 LTS
```

# Steps to reproduce

In power shell type:
`wsl --unregister Ubuntu-18.04`

# Expected behavior

Ubuntu 18.04 disappears from the New Tab drop-down list (preferably: immidiately, could be: after restarting Windows Terminal).

# Actual behavior

Even after restarting Windows Terminal Ubuntu 18.04 is still there:
![obraz](https://user-images.githubusercontent.com/12645105/83333280-06c0ff00-a2a0-11ea-8419-155873d81b59.png)
After selecting it process exits with code 4294967295:
![obraz](https://user-images.githubusercontent.com/12645105/83333302-2526fa80-a2a0-11ea-8cad-c571d2cd8851.png)

**Comment by DHowett** [comment]
If the Ubuntu entry was created by Terminal, it will be removed on the next launch.

If you’re not seeing that behavior, can you share the output of `wsl -l` after removing a distribution?

**Comment by matkaz** [comment]
Every entry was created when I've installed Ubuntu from Microsoft Store.
The output of `wsl -l` after removing the distribution was as expected:
```
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
```

**Comment by zadjii-msft** [comment]
Wait to be clear - when you relaunch the terminal, does the uninstalled distro get removed from the list of profiles?

**Comment by matkaz** [comment]
No, it didn't. I tried restarting terminal as well as Windows. Eventually, it got removed when I removed the entry on my own in settings.json.

**Comment by zadjii-msft** [comment]
Well, that's certainly unexpected then.

**Comment by DHowett** [comment]
Hey @matkaz, would you mind sharing your settings file?

**Comment by matkaz** [comment]
@DHowett sure: [settings.json.txt](https://github.com/microsoft/terminal/files/4754162/settings.json.txt).

Please, keep in mind that I've already removed the faulty entry. One thing that I noticed while removing the entry was that it had much more fields than Ubuntu 20.04 entry. It resembled Azure or PowerShell entries.


(Also: I've renamed settings.json to setting.json.txt as GitHub complains about attaching a file with `.json` extension...)

**Comment by DHowett** [comment]
> much more fields than Ubuntu 20.04

So, yeah, this is what I was wondering about. There's a narrow band of settings files that predated version 0.5 (yours looks like one of them!) that still had WSL autodetection applied to them. To preserve user data/user customization, those settings files aren't migrated or replaced.

Unfortunately, they didn't include enough information for Terminal to use to automatically hide WSL distributions that were removed after the settings block for them was generated. Terminal errs on the side of caution here and keeps the profile around.

At the end of the day, those old profiles are indistinguishable from profiles you have added yourself. We wouldn't want to delete one of those :smile:

It looks like you came in after 0.2 or 0.3 (since your default key bindings are on <kbd>ctrl+shift</kbd> instead of just <kbd>ctrl</kbd>), so migrating will be a lot less painful. If you're interested, Scott Hanselman put together a [blog post about the new settings](https://www.hanselman.com/blog/NowIsTheTimeToMakeAFreshNewWindowsTerminalProfilesjson.aspx) and how you can migrate. If you're comfortable doing so, I'd recommend it.

**Comment by DHowett** [comment]
(The new settings file format leaves out 90% of the information in the old one, and gives you more pointers about where to apply customizations.)

I'm gonna close this one out as "old settings file; an abundance of caution stopped us from deleting a profile we thought was yours". In the future, all autodetected profiles (profiles with a `source`) will be handled correctly.
