### ISSUE TITLE
Add shortcut like "Shift+Alt+T" in Ubuntu to open a Windows Terminal

### ISSUE THREAD

**Issue by AlphaKennyBudy** [microsoft/terminal#6301]
# Add shortcut like <kbd>Shift+Alt+T</kbd> in Ubuntu to open a Windows Terminal
I'm just bored of pressing <kbd>Win+R</kbd> and typing ```wt```. Is there a better solution?

I'm sorry, if there was such a feature request. I've searched, but there are tons of issues about shortcuts, so I just lost.

**Comment by skyline75489** [comment]
You can in fact pin the WT to your task bar and use Win+#x to open it. See #5909.

**Comment by skyline75489** [comment]
For clarification, it's highly unlikely that there will be a system-wide shortcut like in Ubuntu, since WT is a standalone app and will continue to be so as far as I can see.

**Comment by zadjii-msft** [comment]
I personally really like the <kbd>Win+1</kbd> solution @skyline75489 suggested above.

Once #492 lands, then the <kbd>Win+x</kbd>, <kbd>c</kbd> shortcut used to launch `cmd` will open directly in conhost instead. 

Otherwise there's #653/#2809 for "global hotkey", which is probably what you're looking for.

Thanks!

/dup #653 #2809 #5000
