### ISSUE TITLE
Bottom padding in full-screen and maximized is not affected by settings.json

### ISSUE THREAD

**Issue by Almoullim** [microsoft/terminal#6302]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): Version: 1.0.1401.0
```

# Steps to reproduce
Set the padding to "0,0,0,0" and open the terminal in full screen

# Expected behavior
The terminal has 0 paddings all around in fullscreen or otherwise 

# Actual behavior
The terminal has extra padding at the bottom, plus a tiny bit on the right if you look closely as seen on the second screenshot

When not maximized or not in fullscreen, the `padding` settings are respected
![0](https://user-images.githubusercontent.com/8402210/83491602-b376c880-a4ba-11ea-896c-c44823177aab.PNG)

However, when in fullscreen or maximized, it is not
![1](https://user-images.githubusercontent.com/8402210/83491677-d2755a80-a4ba-11ea-8d0f-59bc4801c4d0.PNG)

**Comment by zadjii-msft** [comment]
This is unfortunately by-design. That space that's there on the bottom of the window isn't big enough for an entire row of text, so we just fill it with blank space. That's generally preferable to a row of characters that's only partially visible. Otherwise, the only solution would be to prevent the window from filling the entire screen while maximized, which I'm sure that no one really wants.

Thanks!

/dup #6021

**Comment by Mukul-daroch** [comment]
![Screenshot (34)](https://github.com/microsoft/terminal/assets/68000748/955e8556-9e2d-4e68-9c6c-44a819a39f83)
Just turn off following settings
![Screenshot 2024-06-18 103912](https://github.com/microsoft/terminal/assets/68000748/45df2b6e-3e7f-4188-aa39-071adfb9df80)
after that you can use full screen with no padding 
![Screenshot (35)](https://github.com/microsoft/terminal/assets/68000748/5dbfbd93-bb4f-43c3-80ee-bfe2bea9f06b)
without full screen
![Screenshot (36)](https://github.com/microsoft/terminal/assets/68000748/3daf4642-97ef-4514-8130-6649023ee5fd)
