### ISSUE TITLE
Theme only work in profile Deafults.

### ISSUE THREAD

**Issue by IveGotRoot** [microsoft/terminal#6317]
Hey, I have set my color scheme to a theme called Atom.
{ "name": "Atom", "black": "#000000", "red": "#fd5ff1", "green": "#87c38a", "yellow": "#ffd7b1", "blue": "#85befd", "purple": "#b9b6fc", "cyan": "#85befd", "white": "#e0e0e0", "brightBlack": "#000000", "brightRed": "#fd5ff1", "brightGreen": "#94fa36", "brightYellow": "#f5ffa8", "brightBlue": "#96cbfe", "brightPurple": "#b9b6fc", "brightCyan": "#85befd", "brightWhite": "#e0e0e0", "background": "#161719", "foreground": "#c72a2a"//"#c5c8c6" }
I Have verified it works, but only in the profile defaults. I can't set them in the profiles section per profile.

**Comment by DHowett** [comment]
As requested in the other thread, can you share a [gist](https://gist.github.com) of your full settings file? Thanks!

**Comment by Blocktrician** [comment]
https://gist.github.com/Blocktrician/2a978cb14c35428f12a0f554a5f29239

**Comment by DHowett** [comment]
I mean, you have two profiles that _explicitly_ set the `colorScheme` to `Campbell`. Are those the ones that aren't working?

**Comment by IveGotRoot** [comment]
All of them aren't working

**Comment by IveGotRoot** [comment]
I have them set as an experiment, I was just trying to set the theme to atom. Both of them were replaced correctly for the atom theme. I could only get it if I set the theme in default.

**Comment by zadjii-msft** [comment]
Ah okay, I see it. The first profile in your list of profiles is... odd. It's got a `source`, but no `guid`, so it's not actually being correlated to _any_ profile. If you wanted to change the properties of the "Windows Powershell" profile, you'd want the following:

```json
            {
                "guid" : "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name" : "Powershell",
                "acrylicOpacity" : 0.7,
                "fontFace" : "Cascadia Code PL",
                "colorScheme" : "Atom"
            },
```

**Comment by IveGotRoot** [comment]
Thanks, It had no guid by default. Is that intentional?

**Comment by zadjii-msft** [comment]
Definitely not - the ones that have the `"source"` property are [_dynamically generated_](https://docs.microsoft.com/en-us/windows/terminal/dynamic-profiles) and need the GUID to help the dynamic generator figure out which profile it is. 

The "Windows Powershell" profile _isn't_ dynamically generated, since it's always available on every version of Windows. It's defined in [`defaults.json`](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json), and also requires a GUID so the terminal can know that you're trying to change it's settings.
