### ISSUE TITLE
Display colors don't work as aspected

### ISSUE THREAD

**Issue by trodix** [microsoft/terminal#6345]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.18363.836]
Windows Terminal version (if applicable): 1.0.1401.0
```

# Steps to reproduce

execute the command `symfony serve` in a symfony project

# Expected behavior

Colors should be rendered like this: (WSL 1 ubuntu used in legacy terminal window)

![image](https://user-images.githubusercontent.com/34584317/83726041-3dea3400-a643-11ea-92db-56e1f16bfc50.png)

# Actual behavior
(Windows Terminal 1.0.1401.0)
Escape chars are not interpreted

![image](https://user-images.githubusercontent.com/34584317/83725617-82290480-a642-11ea-8c51-5a07238b77f3.png)

**Comment by zadjii-msft** [comment]
Where are you getting `symfony` from? Are you maybe using a cygwin/msys/git bash version of it? Since this doesn't repro in WSL, I'm assuming that this is because this version of `symfony` isn't enabling VT processing with [`ENABLE_VIRTUAL_TERMINAL_PROCESSING`](https://docs.microsoft.com/en-us/windows/console/setconsolemode)

**Comment by trodix** [comment]
I Keep in mind the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag, I coudn't make it working but It seems to be the solution of my issue. 

To be continued

**Comment by trodix** [comment]
It works on WSL with the Windows Terminal 1.0, so... issue solved
