### ISSUE TITLE
File association for .BAT and .CMD

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#6429]
Hello,
Please add below feature:
- File association for .BAT and .CMD

![Desktop](https://user-images.githubusercontent.com/23485114/84151379-87d67e00-aa78-11ea-961a-f07c96931514.gif)

```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\cmdfile\shell\open\command]
@="\"C:\\Users\\Muhammad\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe\" new-tab -p \"Command Prompt\" \"%1\" %*"

[HKEY_CLASSES_ROOT\batfile\shell\open\command]
@="\"C:\\Users\\Muhammad\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe\" new-tab -p \"Command Prompt\" \"%1\" %*"
```

Thanks

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! I think the way we plan on solving this is by letting the user broadly set another application as the _default_ terminal app, instead of the vintage console host. That way, double-clicking on a `.bat` or `.cmd` file would automatically open `cmd` inside _whatever_ the default terminal application is. 

That work is being tracked over in /dup #492
