### ISSUE TITLE
SSH then running a reset caused blank space 

### ISSUE THREAD

**Issue by NathanR1225** [microsoft/terminal#6545]
# Environment

Win 10
Windows Terminal Version: 1.0.1401.0

Any other software?
SSH? 

# Steps to reproduce

1. SSH into Linux using power shell or Ubuntu terminal 
2. run some commands (to full console ) 
3. run reset to clear console
Show example in images 

# Expected behavior
When running reset the console should clear like it does but put the next line at the top of the screen. 

# Actual behavior
Used SSH to log into a piece of hardware running linux. When I ran the reset command it clears the screen but adds a blank new line above the terminal line. resizing the terminal from full screen to partial screen then back to full screen does remove some new lines. Seen in Power shell and Ubuntu terminal.  
![image](https://user-images.githubusercontent.com/63110047/84912193-2a00f200-b087-11ea-963f-41caa5c7a138.png)
![image](https://user-images.githubusercontent.com/63110047/84912224-36854a80-b087-11ea-8fbd-41b1351f7024.png)

**Comment by DHowett** [comment]
Would you mind sharing the output of...

```bash
infocmp | grep "rs[123]"
```

in a session where `reset` is acting up?

**Comment by NathanR1225** [comment]
Command was run in Ubuntu terminal 

rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,

**Comment by j4james** [comment]
This is because `AdaptDispatch::EraseInDisplay` returns false in conpty mode, which prevents the remaining steps of the `AdaptDispatch::HardReset` method being executed. That include the cursor position not being reset to 1,1 so the conhost cursor ends up out of sync with the conpty client.

I can't help thinking this passthrough approach is wrong - I mean idea of "failing" in conpty mode as a way to trigger a passthrough. I'm also not convinced that we should be aborting command sequences (like `HardReset`) on the first failure. I'd much rather we just continued executing everything, and accumulated the failure status.

So instead of:

```cpp
if (success)
{
    success = _EraseScrollback();
}
```

we could just have:

```cpp
success = _EraseScrollback() && success;
```
    
That at least should fix this particular problem.

**Comment by DHowett** [comment]
I also find the failure=passthrough behavior somewhat suspect. :smile:

**Comment by DHowett** [comment]
Thanks for digging into this!
