### ISSUE TITLE
WSL emjoy is ？？？

### ISSUE THREAD

**Issue by LiodAir** [microsoft/terminal#656]
# I jumped to kaili in the wsl system (ubuntu) of windwos10, I got emjoy expression turned into? ?
![image](https://user-images.githubusercontent.com/26197815/57510589-cd86bb80-7339-11e9-9617-10b72b4b171f.png)
At the same time, any of my input will be invalid.
![image](https://user-images.githubusercontent.com/26197815/57510706-0a52b280-733a-11e9-93dc-8b08cee755d3.png)

**Comment by zadjii-msft** [comment]
Why are you launching ubuntu via `powershell`?

If I had to guess, something's happening where the encoding of the text is getting mixed up piping the output of one wsl instance through powershell then back to wsl before going to the terminal.

@miniksa might have other ideas.

**Comment by DHowett-MSFT** [comment]
This is a curious case that we can't do anything about.

The version of conhost that ships along with Windows Terminal has been updated to support sending emoji (and other high unicode characters) from the connected command-line application to the terminal. When you run a Windows `.exe` from WSL, you're using _the inbox conhost.exe_ as the console translator, and that version of conhost _doesn't_ support high unicode.

The fix for this will naturally roll out as part of Windows, and it may already be available in Insider Fast builds.
