### ISSUE TITLE
Alt+Numpad not working

### ISSUE THREAD

**Issue by tkmikan** [microsoft/terminal#657]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18362.86
* What you're doing and what's happening:
Using ALT+numpad to input some characters by their code. For example I'm typing ALT+97 to enter `a`
  - in cmd in terminal: `9` and `7` appear when hitted, and `a` appears when releasing ALT
  - in powershell in terminal: digit-argument is triggered, so `a` is duplicated 97 times when releasing ALT
* What's wrong / what should be happening instead:
  should have same behavior as outside the terminal

Perhap it is similar to #637

**Comment by zadjii-msft** [comment]
Adding support for this is in PR currently, #623.

**Comment by tkmikan** [comment]
Actually I mean all inputs should be blocked when holding ALT. This issue does not have much to do with #623

**Comment by zadjii-msft** [comment]
Ah okay, I see what you mean now. Yea, #623 probably even makes this worse. I'll change this to a bug.

**Comment by encladeus** [comment]
The behavior of this bug seems to have slightly changed with 0.3, but is still not working correctly in cmd, powershell or ubuntu. Here are a couple of screen shots from Ubuntu running on WSL.

While holding down the Alt key and entering 148 (**Alt + 148**):
![ubuntu-alt](https://user-images.githubusercontent.com/8571098/62423123-1b9b2900-b6b5-11e9-832b-24e6e8254605.jpg)

Then when the Alt key is released, it clears the argument line above and replaces the command line with 148 **ö** chars.
![ubuntu-release](https://user-images.githubusercontent.com/8571098/62423138-4f764e80-b6b5-11e9-995d-942e8bfbecaa.jpg)

Similarly, if I enter **Alt + 141** there are 141 **ì** chars output on the command line.

**Comment by miniksa** [comment]
/dup #1401 

I know this is the older one, but that one has a bit more code info in it and seems to be similar enough.
