### ISSUE TITLE
(Minor) Default profile given by name is currently recognized to be a mismatch in preview v1.1.1671.0

### ISSUE THREAD

**Issue by Gravifer** [microsoft/terminal#6584]
According to the schema file, only a valid guid is now accepted for the "defaultProfile"; when a profile name is given, the mismatch is detected. This feature is still working and appealing though. 

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
Yeah, this is ... unfortunate. It's because we only have one schema link :smile:

For your preview settings, can you change your `$schema` to `https://raw.githubusercontent.com/microsoft/terminal/master/doc/cascadia/profiles.schema.json`? That will make sure that you're always using the most up to date schema (instead of the one from 1.0)

We'll be better about this in the future.
