### ISSUE TITLE
wt split-pane (multiple copies) seems to have occasional focus issues

### ISSUE THREAD

**Issue by mfeemster** [microsoft/terminal#6586]
# Environment

```none
Windows build number:  10.0.18363.0
Windows Terminal version (if applicable): 1.1.1671.0

Any other software? No
```

# Steps to reproduce

Run a command line which opens multiple tabs, and some split panes. Supply a name for each tab using `--title`.

Example command line:

`wt.exe -p "Command Prompt" -d . --title Cmd1 ; split-pane -H -p Cmd -d . ; new-tab -p "Windows PowerShell" -d . --title Posh1 ; new-tab -p "Windows PowerShell" -d . --title Posh2 ; split-pane -H -p "Windows PowerShell" -d . ; split-pane -H -p "Windows PowerShell" -d . ; new-tab -p "Windows PowerShell" -d . --title Posh3 ; split-pane -V -p "Windows PowerShell" -d .`

# Expected behavior

Each tab gets the name you assigned it.

# Actual behavior

Tabs sometimes get the names you supplied, and sometimes not. Since this problem is intermittent, I suspect it's a threading bug. I would guess you are using the same string variable to parse parts of the command line successively and passing each to a thread. The variable is getting clobbered.

Also of note, this is likely the same problem that is causing #6340, because they also describe it happening intermittently.

Thanks.

**Comment by DHowett** [comment]
What titles _are_ you getting?

**Comment by mfeemster** [comment]
Since the tabs I specified are either powershell or cmd, the cmd tab is randomly either Command Prompt or Cmd1, which I specified on the command line.

For the powershell tabs, I've specified Posh1, Posh2 and Posh3. Each of those is randomly the text I specified for it, or Windows PowerShell, which is the default in the settings.json file.

The randomness of it leads me to believe it's a threading bug. Run the command line I posted above several times and you'll start to see different results.

**Comment by DHowett** [comment]
So, as far as I can tell, this is wrong for a different reason than "titles aren't working". Here's why.

I've decomposed your command into the wtscript that it runs, then annotated it.

```
wt.exe 
 new-tab -p "Command Prompt" -d . --title Cmd1       [1]
 split-pane -H -p Cmd -d .                           [2]
 new-tab -p "Windows PowerShell" -d . --title Posh1  [3] 
 new-tab -p "Windows PowerShell" -d . --title Posh2  [4]
 split-pane -H -p "Windows PowerShell" -d .          [5]
 split-pane -H -p "Windows PowerShell" -d .          [6]
 new-tab -p "Windows PowerShell" -d . --title Posh3  [7]
 split-pane -V -p "Windows PowerShell" -d .          [8]
```

1. Open a new tab, running a terminal whose title is "`Cmd1`"
2. Split that terminal, running a new terminal _with the default title_
3. Open a new tab, title "`Posh1`"
4. Open a new tab, title "`Posh2`"
5. Split that terminal, running a new terminal _with the default title_
6. Split that terminal again, running a new terminal _with the default title_
7. Open a new tab, title "`Posh3`"
8. Split that terminal, running a new terminal _with the default title_

Titles are actually attached to Terminals, not to tabs. The title shown in the tab is that of the active, focused terminal in that tab.

The issue here is that _focus isn't ending up where we expect it._ When you switch focus to the original split in the split pane, the title comes back.

**Comment by mfeemster** [comment]
Ah ok, that is very interesting. Thank you!

This now seems also bit more like user error on my part. Every *pane* needs a title, not just every *tab*. I will handle my setup by naming each pane, no problem.

Maybe clarify the documentation to state this clearly?
