### ISSUE TITLE
Terminal window has white border

### ISSUE THREAD

**Issue by michalhudecek** [microsoft/terminal#6620]
This issue has been reported several times but incorrectly marked as duplicate or just closed with no explanation.

The terminal window should have **under no circumstances a white border**. Not just in dark mode but NEVER. It is completely inconsistent with all other Windows apps including those from Microsoft. 

### Terminal border
![image](https://user-images.githubusercontent.com/1215304/85220577-f71f6c80-b3ac-11ea-91b8-7fb57b38f400.png)

### Any other Windows app

![image](https://user-images.githubusercontent.com/1215304/85220555-aad42c80-b3ac-11ea-9680-60e78b7b229b.png)

![image](https://user-images.githubusercontent.com/1215304/85220558-b58ec180-b3ac-11ea-866f-11dabb02ea91.png)

![image](https://user-images.githubusercontent.com/1215304/85220561-c2131a00-b3ac-11ea-8a2f-521b6e910897.png)

![image](https://user-images.githubusercontent.com/1215304/85220562-c8a19180-b3ac-11ea-87e5-1078455f7803.png)

![image](https://user-images.githubusercontent.com/1215304/85220565-cf300900-b3ac-11ea-9b55-3674ccd01e99.png)

Issues that were incorrectly closed: 
- https://github.com/microsoft/terminal/issues/4980 
- https://github.com/microsoft/terminal/issues/4837

**Comment by michalhudecek** [comment]
Btw ... aren't there any Microsoft design guidelines? I assume this issue shouldn't be discussed at all per application.

**Comment by j4james** [comment]
The border color is affected by a number of settings. Typically it uses the accent color, in which case it could be white (or at least a light gray) if that's the accent color you chose. But I suspect in this case you've probably just turned off _Title bars and window borders_ option, and that's what's responsible for the white border in the _Light_ mode.

I think that might be a bug, but it's different from the original white border issue.

**Comment by michalhudecek** [comment]
Here is my setting:

![image](https://user-images.githubusercontent.com/1215304/85223290-43c17280-b3c2-11ea-93e6-631fc3c0eb36.png)

**Comment by greg904** [comment]
True. I did a PR (#3394) to add "standard" window borders a long time ago where I assumed that the "standard" window borders behavior was the one of the Win32 windows, where they _do_ have a white border:
![image](https://user-images.githubusercontent.com/56923875/85224589-a9662c80-b3cb-11ea-960d-d4b29e9aa430.png)
![image](https://user-images.githubusercontent.com/56923875/85224590-ab2ff000-b3cb-11ea-81cc-d60e0c111fe2.png)
But now, looking back, I was probably wrong because UWP apps seem to be the future for MS so if they put black borders on UWP apps, then MS probably wants to put black borders on new apps as well.

**Comment by j4james** [comment]
I don't think it's meant to be black exactly. I suspect it might be version specific, but the border colors I'm seeing on most UWP apps is different on the top and sides, and it's actually a level of transparency, so what you see will depend on the background. I'm talking specifically about the _Light_ mode, with the _Title bars and window borders_ option disabled.

I'm on version 10.0.18362.836. The OP didn't fill in the bug template, so I don't know what version he is using, but his screenshots look different to what I'm seeing.

**Comment by michalhudecek** [comment]
I am using Terminal 1.0.1401.0 (stable) and 1.1.1671.0 (preview). The issue is the same in both.

Here is my Windows version:
![image](https://user-images.githubusercontent.com/1215304/85225420-69a24380-b3d1-11ea-9da6-98eff219216d.png)

**Comment by greg904** [comment]
Yes sorry I meant "dark" instead of "black".

j4james, I don't know if you're talking about this when you say that the top and side colors are not the same, but if you are, I think it's a bug because it disappears after a restart:
![image](https://user-images.githubusercontent.com/56923875/85225458-c1d94580-b3d1-11ea-8f49-4c0ef131ef0a.png)
(see how the top border is dark but other borders are light)

I am on 10.0.18362.900.

**Comment by j4james** [comment]
> j4james, I don't know if you're talking about this when you say that the top and side colors are not the same, but if you are, I think it's a bug because it disappears after a restart:

That makes sense. That's exactly what I'm seeing. I thought it might be a bug.

**Comment by greg904** [comment]
This is unrelated to the OP but I reported this bug in the Feedback Hub: https://aka.ms/AA6pqh3. (I put this here so that we can upvote it).

**Comment by DHowett** [comment]
Unfortunately, there isn’t a standard here. If somebody wants to remove the theme check around “TrySetDarkMode” in “NonClientIslandWindow.cpp”, I would absolutely accept that pull request.
Thanks for digging up all these counterexamples, @michalhudecek!

**Comment by DHowett** [comment]
(When I say “there isn’t a standard here,” I mean “terminal even has to use a _private API_ to get its window borders to look like other UWP applications.” It drives me crazy!)

**Comment by michalhudecek** [comment]
There is no standard even "on paper"? I mean something like a codified design system: https://atlassian.design/guidelines/product/overview or https://material.io/components

**Comment by michalhudecek** [comment]
That was quick! Good job :)

**Comment by harristom** [comment]
This problem is back in v1.17, I guess due to the recent changes around theming. The grey border is there to start with until you switch to another window and back (presumably it's part of the dark theme and doesn't get repainted until switching). Once you switch back it is white and will stay so even after closing/re-opening.

Steps to reproduce:
* Delete settings.json and state.json
* Open Terminal and switch to light theme
* Border is grey
* Alt tab to another window then back again
* Border is now forever white

**Comment by kaecy** [comment]
I don't want a border around my terminal. I'm very sensitive to colour.
