### ISSUE TITLE
Pressing CTRL+SHIFT, ENTER in Windows Run Dialog should run as admin

### ISSUE THREAD

**Issue by aplocher** [microsoft/terminal#6625]
# Description of the new feature/enhancement

Would like to be able to open the Windows "Run" dialog (WINKEY+R) and type "wt", then press CTRL+SHIFT+ENTER to open as an Administrator, like I do with "cmd.exe" (or any other app).

I'm not sure if this should be filed as a feature or a bug...

# Proposed technical implementation details (optional)

Thanks!

**Comment by KalleOlaviNiemitalo** [comment]
These work, though:
- Press only the Windows key (not Windows+R), type "wt", and press Ctrl+Shift+Enter.
- Open `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` in File Explorer, right-click `wt.exe`, and choose Run as Administrator.

I don't understand why it does not work for `wt` in the "Run" dialog, even though it works for e.g. `skype`, which likewise has a Microsoft Store signature. Is that caused by something in the AppX manifest?

**Comment by DHowett** [comment]
So, we heard back from the AppX team about this. It's a bug in the platform :smile: which I am certain is everyone's favorite thing to hear!

**Comment by DHowett** [comment]
It turns out that when an application's _alias name_ doesn't match its _filename_ (as in our case, `wt.exe` is an alias for `WindowsTerminal.exe `), it fails out during elevated launch.

We can fix this by renaming our executable or providing a local shim.

I'm interested in the shim option, as it might solve another issue we've been hitting ...
