### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by dakom** [microsoft/terminal#6630]
I installed through the Microsoft Store which according to the documentation is the recommended approach.

However, as of today the Releases page here says the latest version is `1.1.1671.0` and when I go to the `About` page via terminal (installed via store a while back) it says `1.0.1401.0`

I've hit "Get Updates" in the Microsoft Store App but it had no effect.

Would be great to have documentation on how exactly to update terminal to the latest and greatest, using the recommended approach - or perhaps a note about what the release schedule looks like vis-a-vis the store. Thanks!

**Comment by zadjii-msft** [comment]
Ah, this is because you've probably installed the _stable_ release version, which you can find [here](https://aka.ms/terminal), while the latest version has only been pushed to the preview channel, which you can [install here](https://aka.ms/terminal-preview).

Maybe you're looking for something like the [roadmap](https://github.com/microsoft/terminal/blob/master/doc/terminal-v2-roadmap.md)?

> The Windows Terminal project is engineered and delivered as a set of 4-week milestones. New features will go into Windows Terminal Preview first, then a month after they've been in Preview, those features will move into Windows Terminal.

**Comment by dakom** [comment]
perfect, thanks!
