### ISSUE TITLE
CTRL+w should close the current tab

### ISSUE THREAD

**Issue by JamesEarle** [microsoft/terminal#6636]
Just like in the new Chromium based Edge, `CTRL+w` should close the current tab.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues.

/dup #6449 #6490


The `closePane` command (which can be used for closing tabs as well) is bound to <kbd>ctrl+shift+w</kbd> [by default](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/defaults.json#L311). This is because there are other commandline applications, like `nano`, that use <kbd>ctrl+w</kbd> as a keybinding themselves.

If you'd like to bind it to <kbd>ctrl+w</kbd> instead, add the following to your settings:
```json
{ "command": "closePane", "keys": "ctrl+w" },
```
