### ISSUE TITLE
on Vim, <C-_> cannot interpret as c-/

### ISSUE THREAD

**Issue by w93163red** [microsoft/terminal#6643]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Any other software?
ssh + tmux + neovim

```

# Steps to reproduce

```
nmap <C-_>   <Plug>NERDCommenterToggle
vmap <C-_>   <Plug>NERDCommenterToggle<CR>gv
```

then press c-/.

# Expected behavior

Should interpret as c-/

# Actual behavior

Nothing happens.

**Comment by DHowett** [comment]
Which version of SSH are you using?

**Comment by DHowett** [comment]
Win32-OpenSSH 7.7 has its own input generator, and it does not support <kbd>Ctrl+/</kbd>. Win32-OpenSSH 8.x is using the Windows Console input generator, which DOES support it.

### 8.2
![image](https://user-images.githubusercontent.com/189190/85436208-80fe3f80-b53d-11ea-8ab0-baa46bf2d607.png)

### 7.7
![image](https://user-images.githubusercontent.com/189190/85436221-86f42080-b53d-11ea-84ff-cd6b0d4a58bd.png)

It's silly, because it's an image of _nothing_

**Comment by w93163red** [comment]
> Win32-OpenSSH 7.7 has its own input generator, and it does not support Ctrl+/. Win32-OpenSSH 8.x is using the Windows Console input generator, which DOES support it.
> 
> ### 8.2
> ![image](https://user-images.githubusercontent.com/189190/85436208-80fe3f80-b53d-11ea-8ab0-baa46bf2d607.png)
> 
> ### 7.7
> ![image](https://user-images.githubusercontent.com/189190/85436221-86f42080-b53d-11ea-84ff-cd6b0d4a58bd.png)
> 
> It's silly, because it's an image of _nothing_

@DHowett May I know how I can check the version?

**Comment by w93163red** [comment]
@DHowett May I know how I can check the version?

**Comment by DHowett** [comment]
Please run `ssh -V`.

**Comment by w93163red** [comment]
> Please run `ssh -V`.

Thanks. It is 7.7.
