### ISSUE TITLE
A solution to the "acrylic-focus" problem, which isn't GPU intensive

### ISSUE THREAD

**Issue by Adriiii** [microsoft/terminal#6690]
A solution to the "acrylic-focus" problem, without being GPU intensive

(before everything, sorry if my English is a little bit approximate, I'm French)
A lot of people are complaining about the acrylic background not be working when the terminal isn't in focus.
But instead of displaying a uniform (ugly) background when the window loses focus, it could be possible to "save" the current state of the acrylic background and display it until the window is back in focus.

(I didn't understand the question...)
Ps : Thanks for your work, this new Terminal is extraordinary

**Comment by JasonWei512** [comment]
In fact this should be done by DWM...

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! You know what, I'm just caving on this issue and suggesting that someone port the brush from Notepads, which supports unfocused acrylic, to the Terminal. We're going to make it an opt-in setting, so users can chose this behavior if they want, but that's going to be the cleanest solution to this problem IMO. This work is going to be tracked over in #7158

**Comment by harounhajem** [comment]
@Adriiii I understand the problem but It's not a good solution and it will impact the perceived quauility of the terminal, since it may look like a bug. Because the proposal is not following the expected behavior of acrylic glass. 

I would advice just using a transparent background or a solid background on a low-end machine.
