### ISSUE TITLE
Render artifacts in existing pane upon opening new split pane

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [microsoft/terminal#6699]
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

- While running __command/process__ in a `Powershell`, outputting progress __log__.
- And you try to open new __pane__ using `SHIFT+ALT+ '+'` or what ever command you have set.
- Following are the results

# Expected behavior

- Both __panes__ should render outputs normally.

# Actual behavior

- The __tab/window__ flashes(like reloading), feels like rerendering the both panes again
- Causes some render artifacts, see the screenshot

![bug](https://user-images.githubusercontent.com/46624268/85920160-cfd40e00-b88a-11ea-9b32-a35571e1e3ae.png)

**Comment by muhammad-usman-anwar** [comment]
This could also be result of __scaling__ issue, as the process trues to make space for new __pane__. Ends up rendering it to new line and when I increased the __width__ of window, resulted in artifact. This requires further testing.

**Comment by DHowett** [comment]
Unfortunately, terminals _everywhere_ cause problems for applications that draw progress bars when they're resized. Because the available space is changing, the application needs to make a decision about how to draw the  bar once the space changes.

I believe there's nothing we can do about that. ☹️
