### ISSUE TITLE
Show "Windows Terminal" in Search when typing "wt"

### ISSUE THREAD

**Issue by skyanchor** [microsoft/terminal#6748]
# Description of the new feature/enhancement
When typing "cmd" in Windows Search, there comes "Command Prompt". On the other hand, when typing "wt" in Search, it shows a common icon with "Run Command". I'm wondering if it could show the app's icon and name.
![image](https://user-images.githubusercontent.com/52092252/86258185-1c05b200-bbed-11ea-890f-174518d35af5.png)
![image](https://user-images.githubusercontent.com/52092252/86258212-23c55680-bbed-11ea-85ba-72dc54c078bd.png)

# Proposed technical implementation details (optional)

**Comment by KalleOlaviNiemitalo** [comment]
On Windows 10 version 2004 (OS Build 19041.329), if I create the following Registry value, then the Start Menu shows the Windows Terminal icon when I search for `wt`, regardless of whether the `wt.exe` app execution alias is enabled:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe]
@="C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.0.1811.0_x64__8wekyb3d8bbwe\\WindowsTerminal.exe"
```

Unfortunately, this Registry value also prevents Windows Terminal from starting when I click "Open" in the Start Menu after searching for `wt`, even if the `wt.exe` app execution alias is enabled. Process Monitor shows that it RuntimeBroker.exe tries to open "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1811.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe" for execute access, gets an ACCESS DENIED error, tries "%LOCALAPPDATA%\Microsoft\WindowsApps\WindowsTerminal.exe", and gets a NAME NOT FOUND error because the app execution alias is `wt.exe` rather than `WindowsTerminal.exe`.

If I instead search for `skype.exe` and click "Open", then RuntimeBroker.exe tries to open "C:\Program Files\WindowsApps\Microsoft.SkypeApp_15.61.100.0_x86__kzf8qxf38zg5c\Skype\Skype.exe" for execute access, get an ACCESS DENIED error, tries "%LOCALAPPDATA%\Microsoft\WindowsApps\Skype.exe", and succeeds.

So, I think implementing this enhancement on Windows 10 version 2004 would require two things:

- Add `wt.exe` to the directory of Windows Terminal, as planned in <https://github.com/microsoft/terminal/issues/6625#issuecomment-647816383>.
- Add the Registry value under `App Paths`. Is this even possible from within an MSIX package?

Ultimately, it would be better if this were implemented in Windows itself, so that the feature would apply to all apps that have app execution aliases.

**Comment by zadjii-msft** [comment]
@DHowett Do we know which team owns execution aliases, and if they'd be willing to pick this up for the next release?

**Comment by KalleOlaviNiemitalo** [comment]
This issue has been sort-of fixed in Windows Terminal Preview. Now that the package contains `wt.exe`, AppXSvc creates `wt.exe` Registry keys under App Paths, and the Start menu shows the proper icon if I type `wt`. There is the <https://github.com/microsoft/terminal/issues/7188> side effect, though.

**Comment by DHowett** [comment]
Marking tracking-external with MSFT:28186919. Feature request has been made to the appropriate folks.

**Comment by zadjii-msft** [comment]
Alrighty so chatted a bit with the search folks - this is gonna be the final form of this (at least for the long foreseeable future). Search will show the icon of the app the execution alias, but ultimately the important piece of data to surface is the execution alias itself. 

Thanks!
