### ISSUE TITLE
Shitf+Tab don't work through ssh

### ISSUE THREAD

**Issue by musicwei** [microsoft/terminal#6769]
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Any other software?
shell:zsh
software:nvim+spacevim
```

# Steps to reproduce

edit with spacevim ,shift+tab don't work
"SHIFT + TAB"seems to be used by powershell,Is there a way to change it?

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
Are you using the version of ssh that comes with windows? If so, this is because they do not support shift-tab. Win32-OpenSSH 8.1+ will fix this.

**Comment by musicwei** [comment]
@DHowett Thanks this helpful

**Comment by DHowett** [comment]
Happy to help. Sorry that there's an issue :smile:

The problem is that Windows SSH has its own input generator. It reads the keyboard keys on its own, and converts them into the right format. It doesn't know what to do when it gets a "shift" and a "tab" at the same time.

For now, you can either update to the new version (at https://github.com/powershell/win32-openssh/releases) or use SSH through WSL.
