### ISSUE TITLE
Display tabs in the alt-tab switcher

### ISSUE THREAD

**Issue by electronic-dk** [microsoft/terminal#6783]
One of the features in the latest windows insider build (20161) is the ability to display Edge's tabs alongside the open apps in the alt-tab switcher. I think that it may be pretty convenient (I loved this feature back in Android 5-6 times). Do you think it's something that can be brought over to MS Terminal as an optional feature (or an extension perhaps)?

**Comment by zadjii-msft** [comment]
I don't know how this works in Edgium, but I'd imagine it's similar to the code that we'll need for #687 (also see #2887 and #3247 which helped lead me to that one).

I'm inclined to leave this open alongside #687, since that one seems to be specific to "tabs in the taskbar", and this one is "tabs in the alt-tab" switcher. If someone could point me at the specific APIs that would suggest these are in fact the same APIs, we can close this one. I'm thinking that they're definitely different though, since the old IE had tabs in the taskbar, but not alt-tab.

**Comment by electronic-dk** [comment]
@zadjii-msft I'd say those should be different apis, since AFAIK the tabs in the alt-tab switcher in Edgium canary are only available in the Windows Insider build (20161) and not in stable Windows versions.

**Comment by DHowett** [comment]
This is not currently possible via public API. I'm going to close this for now, but bring it back when there's an SDK that would allow for us to accomplish it.

**Comment by hougaard** [comment]
Soo... The terminal is a second-class citizen in Windows compared to Edge?

Or is this actually a request for Windows and not Terminal?

**Comment by zadjii-msft** [comment]
It's more of a request on the OS to make whatever API they're using publicly available. The Terminal is an open-source project, so we can only call APIs that are publicly available. Edgium is _not_ open source, so they don't have the same restrictions.

**Comment by oxygen-dioxide** [comment]
> It's more of a request on the OS to make whatever API they're using publicly available. The Terminal is an open-source project, so we can only call APIs that are publicly available. Edgium is _not_ open source, so they don't have the same restrictions.

Microsoft can provide a closed-source enhanced version of windows terminal("windows terminal plus") with this feature.

**Comment by DHowett** [comment]
We strive to be utterly committed to open-source and openness. I wouldn’t want to break that commitment to bring folks a feature that is, at the best of times, somewhat annoying. :smile:

**Comment by zadjii-msft** [comment]
@shmuelie That's actually slightly different, and tracked in #687. Seems like that would be a sensible place for apps to publicly be able to add "tabs" to alt-tab, but alas, we don't control that API's existence 😉

**Comment by valinet** [comment]
It's funny how they now allow uninstalling Edge in the EU, so the relevant setting in Settings now reads "Open windows and 5 most recent tabs in _apps_", implying that other apps should be able to tap into that OS offered functionality - yet, no SDK/API to do so, or is it? Will Microsoft ever publish anything about this? The feature is useless for me personally, but do we really need a government body to watch our every step in order to get anything right these days? This OS is dying the most painful death ever...

**Comment by valinet** [comment]
@DHowett And what would that place be? 4 full years and there's still no API for this, I could only speculate becuase of "business reasons", and when asked about it someone from Microsoft comes and basically says "fuck off". Really great attitude, truly!

Since we're on the topic, how can apps differentiate their sub-processes in Task Manager on Windows 11 like Microsoft Edge does? Is there an API for that at least? As far as I know, there is not, but maybe I am wrong...

Such a far cry compared to the superbar in Windows 7 and how we could tap into any of its new features, like thumbnails for documents, thumbnail commands, jump lists, overlay icons, progress bars and so on.

**Comment by zadjii-msft** [comment]
If only there was a repo for discussing the Windows SDK. Somewhere people could request new APIs for Windows Apps. Like, a Windows App SDK repo. Something like that. That would be a better place than here. 

<br>
<br>
<br>

oh wait oh wait oh wait that totally exists: https://github.com/microsoft/windowsappsdk. 


----

dripping sarcasm aside: this repo is pretty specifically for Terminal & Console issues. We can't begin to service all feedback for all of Windows. We like to keep things very tightly on topic here.

**Comment by valinet** [comment]
I mean, when I see you enjoy way more wasting time with "dripping sarcasm", no wonder things are where they are nowadays... Specifically about this stuff, not only have there been 4 years, but the public API should have been there from the get go. The operating system's job is to offer a level "playing field" for applications to "act on", not to discriminate the others in order to prioritize some in house offering. Really, there's [windowsappsdk](https://github.com/microsoft/windowsappsdk)? Unbelievable, wouldn't have guessed so. Probably no one knows about it, that's why things like this, or proper dark theme support on Win32, and many more, are still open issues after all these years... /s
