### ISSUE TITLE
Feature request: Add a unique launch argument for Windows Terminal Preview

### ISSUE THREAD

**Issue by yaichenbaum** [microsoft/terminal#6788]
# Description of the new feature/enhancement

Right now, both the release version and preview version of Terminal use the same launch arguments `wt` and the dev version uses `wtd`. While it's possible to set `wt` to point to the preview instead of the release version, there are times when I want to be able to launch either of them using launch arguments. An example where this would be useful is the navigation textbox in Files Explorer where I can type in `cmd`, `wt` and other similar commands.

# Proposed technical implementation details (optional)

A solution would be to add a unique launch argument for the preview version such as `wtp` so that I can continue using `wt` for the release version and `wtd` for the dev version.

**Comment by zadjii-msft** [comment]
I'm not _horribly_ opposed to this idea. That being said, I'd love to better understand why you might want to be running both at the same time. I'd think that if you are the kind of person to want the preview version and release cadence, then you'd probably _always_ want to use the preview one, right?

**Comment by yaichenbaum** [comment]
@zadjii-msft I personally use both as I like to keep up to date with the latest features, but I like having the release version as a backup in case there is an issue with the preview version.

**Comment by duke7553** [comment]
@zadjii-msft If both apps have a different release cadence, then why have the same executable name? 😃

**Comment by Jaiganeshkumaran** [comment]
> @zadjii-msft If both apps have a different release cadence, then why have the same executable name? 😃

The can't keep changing the name of the executable.

**Comment by DHowett** [comment]
So, I'm going to reject this request. Sorry.

Preview and Stable are only intended to be installed side-by-side and switched between when you're worried about the stability of Preview. We're not intending both channels to be in active simultaneous use. If you're encountering an issue that means you make to switch between them _more than once in a single session_ I'd rather we just fix the issue instead of bandaging it with another app execution alias. If you are, please do let us know what those issues are.

Fortunately, you _can_ work around this yourself! If you link `%LOCALAPPDATA%\Microsoft\WindowsApps\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\wt.exe` somewhere in your path as _wtp_ (or create a batch file called wtp.cmd, or any number of other tricks), you can explicitly launch it as wtp whenever you want. You can bind a shortcut to that specific path and it'll be durable for the life of the application.
