### ISSUE TITLE
CTRL+C does not kill windows terminal and stuck! 

### ISSUE THREAD

**Issue by thisVioletHydra** [microsoft/terminal#6790]
# Environment

 
 
```code
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal     1.0.1811.0
```
 
I am running a local server on nuxtjs
I can’t complete stop the process, I press ctrl + c and the terminal freezes to turn it off, I need to close it with a cross
![image](https://user-images.githubusercontent.com/11839238/86539922-2e436100-bf09-11ea-89f1-0b97332f8fee.png)

**Comment by KalleOlaviNiemitalo** [comment]
3221225786 = 0xC000013A = STATUS_CONTROL_C_EXIT

It looks like the process has exited, but because the exit code is not zero, Windows Terminal has left the tab open so you can see what happened. See [How the profile closes when exiting](https://docs.microsoft.com/windows/terminal/customize-settings/profile-settings#how-the-profile-closes-when-exiting) and <https://github.com/microsoft/terminal/issues/5214> for how to configure this.

**Comment by DHowett** [comment]
Yes, this is operating as designed. Your process was terminated _at your request_ and it has exited with a code indicating that it "failed." Failing codes, by default, cause the tab to remain open. /dup #5214

**Comment by thisVioletHydra** [comment]
Set: `"closeOnExit": "always"` helped me thx
