### ISSUE TITLE
Bug Report - Error Message while opening preferrences  -- Windows Terminal Version: 1.0.1811.0

### ISSUE THREAD

**Issue by drpacket** [microsoft/terminal#6848]
Error Message ="Adobe Acrobat cannot open 'settings.json' ... filetype not supported or damaged

Windows Terminal
Version: 1.0.1811.0

> **Error Message happend when trying to open preferrences** of "Windows Terminal" App 
> Window (clicking on the register of the window).

First thing most people do when they open a terminal app for the first time/new computer/os, is go to preferrences
to change the size/look of fonts, colors, or window size and such ...

Screenshot of original (german language version) error message:

![screenshot_WinTerminal1](https://user-images.githubusercontent.com/16911419/87001088-ef3a3780-c1b6-11ea-8d57-64e198853bc4.png)

**Comment by zadjii-msft** [comment]
The Terminal just tries to open whatever application is set as the default editor for `.json` files. Apparently, on you machine, that's been set to Adobe Acrobat. If you change that to notepad, or any other text editor, does that fix the issue for you?

**Comment by JoshuaKGoldberg** [comment]
This happened for me as well when I switched the default editor for `.json` files to VS Code. Pressing <kbd>Ctrl</kbd>+<kbd>,</kbd> made the Windows error bloop sound and showed this error popup for a fraction of a second _(I could only get a screenshot using a still from screen recording)_:

![Screenshot of a Visual Studio Code popup with black content instead of text](https://user-images.githubusercontent.com/3335181/87228611-61a24780-c370-11ea-84f5-490c6cfcbb12.png)

Switching back to Notepad++ allows settings to open fine.

**Comment by drpacket** [comment]
Yes, for some reason I do not know .json was set to open with adobe acrobat. Changed it to my text editor and it was fine.
   Guess I was just also expecting a GUI Window. That's why I found it so strange. Works now. Thanks

**Comment by zadjii-msft** [comment]
Thanks for following up!

**Comment by JoshuaKGoldberg** [comment]
@zadjii-msft I think this issue is not resolved. It's reasonable to want VS Code as a default editor for JSON files. It's normally able to open them when prompted by other programs. Would you think this is an issue in Terminal or VS Code?

**Comment by zadjii-msft** [comment]
@JoshuaKGoldberg I'm mainly resolving this since OP's original issue was resolved. I'm not sure why vscode isn't working for you as the default json editor, but I doubt it's Terminal specific. We're simply calling `ShellExecute` on the settings file, and hoping the system can figure it out:
https://github.com/microsoft/terminal/blob/592c63457781c9d753ae6648f03c96d998a0080e/src/cascadia/TerminalApp/TerminalPage.cpp#L1683-L1697

Does double-clicking a `json` file in Explorer work to launch VsCode?

**Comment by JoshuaKGoldberg** [comment]
It does work in Explorer, yes :+1:. Both when VS Code isn't yet launched (to start a new window) and when it already is (to open the file in an existing window).

**Comment by zadjii-msft** [comment]
That's very bizarre. I'd file an issue on the VsCode repo honestly, because they'll be far more equipped to be able to figure out why this isn't working for you than we are 😕

**Comment by JoshuaKGoldberg** [comment]
Ok, thanks for the pointers - I appreciate the GitHub issue debugging! ❤️
