### ISSUE TITLE
Arrow (➜) character in prompt is rendered small

### ISSUE THREAD

**Issue by arish** [microsoft/terminal#6864]
# Environment

```none
Windows build number: [Version 10.0.19041.329]
Windows Terminal 1.0.1811.0
Microsoft Visual Studio Code 1.47.0
```

# Steps to reproduce
- Open Windows Terminal
- Open `oh-my-zsh` with `robbyrussell` theme (or any theme that has an arrow character)
- Open Visual Studio Code
- Open its integrated terminal

# Expected behavior

- They should look identical

# Actual behavior

- The size of the arrow (➜) character in prompt is rendered smaller in Windows Terminal than Visual Studio Code's integrated terminal

Arrow character is smaller in Windows Terminal:

![image](https://user-images.githubusercontent.com/55414364/87183035-f5d5c580-c302-11ea-8dfe-2417d807f1d6.png)

However, it looks accurate on Visual Studio Code:

![image](https://user-images.githubusercontent.com/55414364/87183251-65e44b80-c303-11ea-9358-1f949e258949.png)

**Comment by devcrev** [comment]
Also look at the checkmark size and **colors**.

Terminal...
![image](https://user-images.githubusercontent.com/44066444/87236484-4e1acf00-c3b8-11ea-8806-091f2d829013.png)

VS Code...
![image](https://user-images.githubusercontent.com/44066444/87236497-7e626d80-c3b8-11ea-853b-9ac3c19dec08.png)

**Comment by zadjii-msft** [comment]
@miniksa do we have an active megathread for ongoing character sizing issues?

**Comment by miniksa** [comment]
> @miniksa do we have an active megathread for ongoing character sizing issues? See also #6738

I don't think so. We keep flopping on this because I think these Emoji are ones that were retroactively converted to two-columns. We'll have to dig yet again.

However, submitters (@arish, @DevCrev), it will immensely help the future investigator if you redirect the output from your prompts/commands to a file and attach it here. Then we can have access to the exact character stream that is causing you issues even if it takes us a while to get around to this.

**Comment by DHowett** [comment]
This is because other terminals allow the arrow glyph to spill outside of its cell. It's "single-width", but rendered double-width. iTerm2 does this with the narrow emoji, as well. The character under the right half of the two-cell glyph draws on top of the right side of it. It's ugly, but effective, and people can use spaces to give the arrow/emoji room to grow.

**Comment by DHowett** [comment]
I'll look for the duplicate.

**Comment by devcrev** [comment]
Sure!
Output from the Windows Terminal program is in **terminal.txt**. Output from the VScode program is in **vs_code.txt**.

[terminal.txt](https://github.com/microsoft/terminal/files/4933132/terminal.txt)
[vs_code.txt](https://github.com/microsoft/terminal/files/4933133/vs_code.txt)

It was a little tricky to generate these files since the command `./node_modules/.bin/eslint --init` walks the user through a series of questions. I snapshotted the captures at the moment the screens would look like they do in the screenshots I posted earlier (less the command that generated the output).

You will find the two files to be the same, i.e., binary equivalents.

**Comment by arish** [comment]
Here are the outputs from **Windows Terminal** and **Visual Studio Code**'s integrated terminal:

[wt.txt](https://github.com/microsoft/terminal/files/4937062/wt.txt)
[vscode.txt](https://github.com/microsoft/terminal/files/4937063/vscode.txt)

**Comment by Izolentiy** [comment]
Has anyone found a solution? Because I like Windows terminal, but these little arrows are literally an eyesore
Windows Terminal:
![image](https://user-images.githubusercontent.com/42691978/156526116-9611b949-ac6f-45f4-af6f-ed9f46dd0603.png)
VS Code:
![image](https://user-images.githubusercontent.com/42691978/156526614-1ff4f205-24f6-43b8-a368-6c4110a652a9.png)

**Comment by Izolentiy** [comment]
Hello there again! If someone is facing the same problem, I recommend to use another characters:
windows logo: "\ue70f", arrow: "\uf554"
You'll get this in VS Code
![image](https://user-images.githubusercontent.com/42691978/156790111-ddda070e-2c74-4f1c-9e03-06282f8620d3.png)
in Windows Terminal
![image](https://user-images.githubusercontent.com/42691978/156790137-57ee4e50-26b6-4735-8c0b-771407f39449.png)
Hope it helped someone to solve their problem.

**Comment by Cotarhls** [comment]
> Hello there again! If someone is facing the same problem, I recommend to use another characters: windows logo: "\ue70f", arrow: "\uf554" You'll get this in VS Code ![image](https://user-images.githubusercontent.com/42691978/156790111-ddda070e-2c74-4f1c-9e03-06282f8620d3.png) in Windows Terminal ![image](https://user-images.githubusercontent.com/42691978/156790137-57ee4e50-26b6-4735-8c0b-771407f39449.png) Hope it helped someone to solve their problem.

You terminal is awesome! Could you please tell me how to show the branch icon before text "branch" and the clock icon before time "23:15"?

**Comment by Cotarhls** [comment]
> Hello there again! If someone is facing the same problem, I recommend to use another characters: windows logo: "\ue70f", arrow: "\uf554" You'll get this in VS Code ![image](https://user-images.githubusercontent.com/42691978/156790111-ddda070e-2c74-4f1c-9e03-06282f8620d3.png) in Windows Terminal ![image](https://user-images.githubusercontent.com/42691978/156790137-57ee4e50-26b6-4735-8c0b-771407f39449.png) Hope it helped someone to solve their problem.

You terminal is awesome! Could you please tell me how to show the branch icon before text "master" and the clock icon before time "23:15"?

**Comment by Izolentiy** [comment]
> You terminal is awesome! Could you please tell me how to show the branch icon before text "master" and the clock icon before time "23:15"?

Sure! branch icon: "\ue0a0", clock icon: "\uf017".
If you want to have exactly the same theme as me. You can copy it from here and maybe modify it as you want on your local machine: https://github.com/Izolentiy/ThemesForApps/tree/master/WindowsTerminal
I uploaded my theme there. I think that exists better way to share my theme, but for faster result I did this.

**Comment by felipecrs** [comment]
Another example:

![image](https://user-images.githubusercontent.com/29582865/173688125-36216c61-b7e4-40bf-9478-902d87092697.png)

PS: Thanks @DHowett for [pointing out this issue](https://github.com/microsoft/terminal/issues/5897#issuecomment-1155777442).

**Comment by Cotarhls** [comment]
> > You terminal is awesome! Could you please tell me how to show the branch icon before text "master" and the clock icon before time "23:15"?
> 
> Sure! branch icon: "\ue0a0", clock icon: "\uf017". If you want to have exactly the same theme as me. You can copy it from here and maybe modify it as you want on your local machine: https://github.com/Izolentiy/ThemesForApps/tree/master/WindowsTerminal I uploaded my theme there. I think that exists better way to share my theme, but for faster result I did this.

I‘m sorry to reply so late. But thanks! Your answer helps me a lot. Now I know they are just preset-icons of some theme.

**Comment by lhecker** [comment]
@237dmitry you wrote "The default console looks much better." showing
![Screenshot 2022-09-14 110951](https://user-images.githubusercontent.com/78153320/190100665-5b63b00c-2a47-4d6a-81e8-139f25322596.png)

And you're right. It does look better. This is because the default console uses the font's information to determine how many cells a glyph like that takes up. But as you can imagine that is quite problematic for terminal applications, since those can't actually "see" what's on the screen. As such people have decided that all glyphs that aren't listed in the [Unicode Standard Annex #11](https://www.unicode.org/reports/tr11/) have a width of 1 column. That way terminal applications can blindly trust the terminal where it puts text on the screen again. (See #2066 for more information.)

But why do emojis and Nerd Font icons still work correctly in other terminals? Because they use [Unicode Standard Annex #11](https://www.unicode.org/reports/tr11/) only to determine how the cursor moves, while the text itself is still drawn according to the font's information. So for instance the Nerd Font icon U+F07B (similar to 🗀) is supposed to take up 1 column, but other terminals draw it in the original 2 column wide size, _overdrawing_ the text that follows it (in this case the whitespace after the icon). In other words, if you take other terminals and write ``"`u{f07b}xyz"`` it'll actually draw something like "🗀yz".

Now, normally this would be easy to fix: We just check the width of Nerd Font icons, right? Unfortunately, for some reason and quite annoyingly so, the "_advance width_" (aka how much the font file wants the cursor to move after drawing the glyph) of those icons isn't 2 but actually 1. The Nerd Font font files simply draw half the glyph outside the 1 column wide bounding box.
So the only way to consistently get that actual width of both Emojis and Nerd Font icons, etc., is by measuring the glyph which is fairly expensive.

A thorough fix is difficult and depends on us rendering the buffer contents off of a text buffer snapshot without console lock so that we can run the expensive measurements without blocking the entire application. A immediate, partial fix is to run those measurements inside the lock anyways, but only for Nerd Font icons since those hopefully don't occur that often. I'll have to think about this some more... but I am planning to solve it this year.

**Comment by ismailhkose** [comment]
I'd like to report same issue for different Unicode character.

Same issue for long arrow, "⟶", character ( U+27F6). It's rendered extremely small.

![image](https://user-images.githubusercontent.com/353824/192957084-19a997aa-5be0-4ff6-9d7f-bc6a6037a305.png)

I changed font to "UbuntuMono Nerd Font" in Notepad, and pasted the character, "⟶", everything is fine with notepad.
![image](https://user-images.githubusercontent.com/353824/192957514-05713846-3644-4961-ae87-15ad26cd25d0.png)


I'd like to use long arrow in VIM to replace 'I^' character for tab indentation.

![image](https://user-images.githubusercontent.com/353824/192957694-76c55b53-be62-40a5-b067-b49fb9841fc8.png)

**Comment by NoBurpees** [comment]
In 1.15.3465 (with activated new renderer) double width glyphs are displayed "correctly".
