### ISSUE TITLE
Translation error when current process ends

### ISSUE THREAD

**Issue by warpdesign** [microsoft/terminal#6870]
# Environment

```none
Windows build number: Microsoft Windows [version 10.0.19041.329]
Windows Terminal version (if applicable): 1.0.1811.0

Any other software?
```

# Steps to reproduce
- open a WSL terminal
- from another terminal, shutdown the WSL instance

When current Terminal process ends, a message with the exit code is shown. This is what appears in French:

> [processus terminée avec le code 1]

There's a little typo, this should be;

> [processus terminé avec le code 1]

How is handled localization in Windows Terminal? Maybe I could make a PR myself?

![image](https://user-images.githubusercontent.com/199648/87218479-58ef4880-c353-11ea-8171-068850f8e852.png)

**Comment by DHowett** [comment]
Thank you! Right now, our localization is handled by the microsoft translation services team (for the 10 languages we ship.) I'm considering how we would add support for other languages and get help from the community. Because French is one of the MS-translated ones, that wouldn't help!

I've reached out to the localization team to let them know about this.

**Comment by DHowett** [comment]
Thanks again for the report. I just pulled the latest localization data, and I've confirmed that this has been fixed. It'll be out in the next release. :smile:
