### ISSUE TITLE
Duplicate terminal session

### ISSUE THREAD

**Issue by maifeeulasad** [microsoft/terminal#6871]
# Description of the new feature/enhancement

Duplicate a session

# Proposed technical implementation details (optional)

There should be options to open at least the same directory in new tab. Like GNOME in Linux has `CTRL + SHIFT + T`, `CTRL + SHIFT + N`.

But when we are discussing about session, it should be more than opening in a specific directory.

Image we are working on CMD and a system variable is added, will the CMD knows about it? No.
If I have added a path. And I ask for that path in that CMD, will CMD be able to provide me with that. Now if I open up a new CMD, I will be able to access that path. So if we want to implement session, like we have a new key-set `CTRL + SHIFT + D`, we have to create another layer, where the CLI will be held. The top layer will just be view.

**Comment by j4james** [comment]
Opening a new tab in the same directory is #3158.

If you're expecting the new tab to also inherit environment variables from the current tab, I suspect that's not possible. Do you know of a Linux terminal that can do that?

**Comment by maifeeulasad** [comment]
@j4james I don't if any thing exists like this till now.
But maybe this this is possible.
I'll try to implement it on a small scale, and get back here as soon as possible.
Thanks.

**Comment by zadjii-msft** [comment]
So I know that "restore session" is _technically_ different, but it's got a lot of the same requirements as "duplicate session". I've discussed this more over in https://github.com/microsoft/terminal/issues/960#issuecomment-495355057 and linked threads. While restoring we might be able to get away with by hanging on to old sessions, duplicating the sessions would be generally impossible.

Let's also link up other relevant discussions:
* Feature Request - Restore closed tab #960
* Restore previously closed session's state #961

I'm going to close this because I believe that it's not possible in the general sense, and that #3158 is going to cover the 99% use case (if that's even possible for us)
