### ISSUE TITLE
Ctrl+Break being treated as Ctrl+C

### ISSUE THREAD

**Issue by wsy** [microsoft/terminal#6874]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1811.0

Any other software? I tried Windows Powershell, Powershell Core 7.0.1, Cmd.exe
```

# Steps to reproduce

Open Windows Terminal, use "ping" command to ping some address.
Example: 
``` Powershell
ping -t 192.168.1.1
```
Then press Ctrl+Break on your keyboard. (I'm using Microsoft Surface Keyboard with FingerprintID, but I assume any full-size keyboard will have the "Pause/Break" key)

# Expected behavior

Ping command will receive the Ctrl+Break signal and display statistic info while continuing to send ICMP packages.

# Actual behavior

Inside Windows Terminal, "ping" command received Ctrl+C signal instead of Ctrl+Break signal.
I tried this in Powershell Core 7.0.1, Windows Powershell and cmd.exe with legacy conhost.exe, they all handle Ctrl+Break correctly.

![image](https://user-images.githubusercontent.com/2684991/87226890-6b0bce00-c3c9-11ea-9178-b4885277a9b9.png)

**Comment by zadjii-msft** [comment]
Thanks for the report! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22Ctrl%2BBreak+as+Ctrl%2BC%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #1119 for more discussion.

/dup #1119

This was fixed as a part of #4999, and should be fixed in Terminal Preview 1.1
