### ISSUE TITLE
Can't reorder tabs when running as Administrator

### ISSUE THREAD

**Issue by Jacquers** [microsoft/terminal#6893]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Run Windows Terminal as Administrator

# Expected behavior

You should be able to reorder the tabs.

# Actual behavior

The tabs cannot be reordered.

**Comment by zadjii-msft** [comment]
Huh, I'm not sure we really have an open issue tracking the status of this, but this is something that we can't support right now due to some platform limitations. Turns out, even if we tried to support reordering tabs while elevated, the application would actually just crash 😨. See #4874, #5564 and others for more details. 

This might be made better by _not needing to run the Terminal elevated_, which we're hoping to land as a part of #5000, though, no promises.

**Comment by nclemons78** [comment]
If #5000 isn't going to be able to include the elevation fixes as it currently indicates, is there any progress towards this specific issue? It's rather a pain, since working with Vagrant + Hyper-V requires me to use elevation.

**Comment by vibonacci** [comment]
What kind of 'platform' limitations are we talking about?

It feels very odd that running as admin or not has effect on reordering tabs. They don't seem related at all, but what do I know.

**Comment by yaira2** [comment]
@zadjii-msft we're seeing this same issue in [Files](https://github.com/files-community/Files) in WinAppSdk.

**Comment by swinder0161** [comment]
Very much needed functionality. Any workaround available with some key shortcuts maybe?

**Comment by avraam-inside** [comment]
@zadjii-msft Hi!

The year is 2023. All requests for this functionality are closed - while the functionality itself is still missing.

Please open and still add.

I need a terminal in administrator mode and with the ability to move tabs normally, except in the application code there can be no problems

Please reopen the request and still make the functionality normal.

**Comment by zadjii-msft** [comment]
@avraam-inside Thanks for the feedback! As we discussed in #3581, dragging & dropping XAML elements in elevated applications is something that's strictly not supported by the platform currently. We've got ongoing threads with them internally, but there's nothing else we can do ourselves to support this. There's some discussion of the topic here: https://github.com/microsoft/WindowsAppSDK/discussions/373, but I'm not sure there's a dedicated WinAppSDK thread to that request. I'd recommend filing one there! That's the best place to request & show support for that feature request.

**Comment by avraam-inside** [comment]
@zadjii-msft thanks for fast answer! 

Done: https://github.com/microsoft/WindowsAppSDK/discussions/373

**Comment by rlwakefield** [comment]
I truly hope this can be solved soon because I have to run Terminal as an administrator all of the time at work due to what I need to execute with it. So I really could use the ability to re-organize the tabs through drag 'n drop.

If there isn't an option to do drag 'n drop for a while, can we get something like a workaround where you can right-click on a tab and tell it to "Move tab to the left", "Move tab to the right", "Move tab to the beginning" or "Move tab to the end"? At least this would allow us to move them around. Might not be efficient, but it would work.

Thanks.

**Comment by zadjii-msft** [comment]
FWIW there are `moveTab` action in the command palette, under "Move Tab forward" / "backward". Those can be bound to keys in the settings

**Comment by rlwakefield** [comment]
Thanks @zadjii-msft . I completely missed that. Now, if only they would add it to the right-click menu of the tabs. And maybe add another option to "Move Tab to Beginning" and "Move Tab to End". Just my thoughts/2 cents of course.

Thanks!

**Comment by swinder0161** [comment]
You can add shortcut also in json

{
            "command":
            {
                "action": "moveTab",
                "direction": "forward"
            },
            "keys": "shift+right"
        },
{
            "command":
            {
                "action": "moveTab",
                "direction": "backward"
            },
            "keys": "shift+left"
        }

**Comment by vibonacci** [comment]
@swinder0161 
That is pretty nifty and works.

However, this is still not the proper solution.

The Windows platform should be adjusted so that something completely arbitrary and logically unrelated, like administrator rights, should not affect an UI feature to perform a drag and drop operation.
VSCode can do it in Electron...

**Comment by avraam-inside** [comment]
Guys, what are you really doing!

It's not IT without dancing with a tambourine! Without inventing bicycles, workarounds and crutches!

@swinder0161 Thanks for the shortcut!
