### ISSUE TITLE
Progress bar on window resize

### ISSUE THREAD

**Issue by MalteRei** [microsoft/terminal#6932]
# Environment

Windows build number:  Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1811.0

# Steps to reproduce

1. run `npm install` (or something that shows a progress bar)
2. While the progress bar is loading resize the window

# Expected behavior

The progress bar animation should continue on one line.

![image](https://user-images.githubusercontent.com/37665562/87558453-6a20b800-c6b9-11ea-8bb2-2f76af38ec88.png)

# Actual behavior

The progress bar is spread across many lines and the window needs to start scrolling to keep up with the lines produced by the progress bar.

![image](https://user-images.githubusercontent.com/37665562/87558590-91778500-c6b9-11ea-9005-414abd20e5d2.png)

**Comment by zadjii-msft** [comment]
If you do the same thing in a vintage console window (i.e. by running `powershell.exe` directly), does the same behavior occur?

**Comment by MalteRei** [comment]
You are right. This is likely not specific to Windows Terminal. Even though it is not as extreme in PowerShell. There are no blank spaces and the text does appear in an order and does not jump back to previous lines.

![image](https://user-images.githubusercontent.com/37665562/87580493-e6c28f00-c6d7-11ea-9aa5-634ae4bcdd68.png)

Out of curiosity: can you explain how these animations are implemented by applications?

Otherwise this can probably be closed. I have seen there are already other issues regarding the problem that text in general appears in random lines.

**Comment by DHowett** [comment]
So, this is one of those weird unavoidable terminal problems.

Most non-Windows applications draw progress bars in one of two ways.

1. "Spinners" - the application sends a `-` or `|` or `/` or whatever and then quickly sends a backspace and another symbol. It'll keep doing this as long as it's processing.
2. "Bars" - the application sends a `[xxxxxxxxxxxxx-------]` coupled with a VT sequence that moves the cursor back to the beginning of the line.
   * This sequence is one of "go back to column 0", "go to row X column 0" or "go to the left 9999 times"

Now, on Windows, you've got all those options plus one more:

3. Do either of the above, but use the Win32 console API (one way or another) to reposition the cursor.

This is where things start to get dicey. Resizing the window can trigger all sorts of buffer changes, from text wrapping/unwrapping to cutting off the right edge of the screen. An application that thinks it knows where the cursor _was_ will almost certainly get it wrong when the window size changes. When it does that, it'll print somewhere unexpected. Sometimes, that'll be at the end of the last progress bar... and sometimes it'll be over top of other important text.

This is, regrettably, "by design" insofar as there's little we can do to prevent it.

:smile:
