### ISSUE TITLE
How do I set a SSH key to my profile?

### ISSUE THREAD

**Issue by FrozenBeard** [microsoft/terminal#6947]
First time setting up Windows Terminal, I found random docs that explain how to make a profile, but none of them explain how on earth to set the path of your SSH key to login to the SSH server.

**Comment by DHowett** [comment]
I quickly did an internet search for "windows set up ssh key" and found the following pages:

* https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement
* https://phoenixnap.com/kb/generate-ssh-key-windows-10#htoc-step-3-use-openssh-to-generate-an-ssh-key-pair

**Comment by FrozenBeard** [comment]
But I already have a key, I just need a way to set it in the terminal configs, not create another one, why is this not an option? mobaxterm just allows you to select a key.

**Comment by viktak** [comment]
@FrozenBeard I agree.

I already have the generated, it works fine from Putty, but I can't figure it out how to use it with Terminal. At best I get this error message:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:y6xUJD+U4QV0/D9Ze1ILf28wjnDoVJaMw+ojaOm/8o4.
Please contact your system administrator.
Add correct host key in C:\\Users\\Viktor/.ssh/known_hosts to get rid of this message.
Offending RSA key in C:\\Users\\Viktor/.ssh/known_hosts:2
RSA host key for 107.180.5.6 has changed and you have requested strict checking.
Host key verification failed.

[process exited with code 255]
```
Is there any info anywhere what key in what format to put in `known_hosts`?

**Comment by DHowett** [comment]
@viktak that error message is talking about the _identification of the remote host_, not your local key.
If your remote hosts are changing identification, especially unexpectedly, that is something you should be extremely worried about.

@FrozenBeard 

Windows started shipping OpenSSH a couple major releases ago -- all of it! A server as well (optionally). It's quite neat.

Terminal doesn't need to do any ssh agent or ssh key management responsibilities because there are already well-tested, robust system-level solutions for it. If Terminal were your SSH agent (and implemented Pageant functionality), it suddenly becomes the sole arbiter of your identity. Do you really want your Terminal to know about that stuff?

It's easy to set your SSH identity _in terminal's config_ in a way that puts OpenSSH in charge with a profile whose commandline specifies `ssh.exe -oIdentityFile=C:\path\to\my\key`.

Mobaxterm offers this _because it is an SSH client_. Terminal simply leverages your existing SSH client. :smile:

**Comment by viktak** [comment]
@DHowett I don't think this is the case. The server in question, where I am trying to SSH in is a GoDaddy host. With Putty (using the same key) I can SSH in with no issue.

At this stage I understand (thanks to your comment!) it is not a Terminal issue as Terminal uses ssh built into Windows. So, naturally, I went to a good old fashioned command prompt and tried to connect using this command:

`ssh ul8c4oapmt2v@x.x.x.x`

The result is the same error message.

Finally, again, using your suggestion, I tried this:

`ssh.exe -i C:\Users\Viktor\.ssh\proba1 ul8c4oapmt2v@x.x.x.x`

... and it worked!! yay! Both in command line and in Terminal.

Huge thank you for putting me in the right direction!
