### ISSUE TITLE
Properly handle and test "end of buffer" in UiaTextRange

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#6986]
When moving by unit, UiaTextRange keeps track of the last character to be the "end of the buffer". This provides significant performance improvements in our accessibility model for word navigation in particular.

However, it is still possible to create a UiaTextRange outside of that optimized buffer size. This has lead to a few bugs like #6402 and ##5243 across Terminal and ConHost.

This issue tracks taking the time to properly test this and polish this architectural change. Especially considering that this breaks a significant number of tests that already exist.

**Comment by codeofdusk** [comment]
This issue was added to a terminal milestone, not Windows. Does this mean it won't make it into 21H1?

**Comment by DHowett** [comment]
@codeofdusk nope, those milestones are just our rough buckets for "when things should land by". Because Terminal 1.3 is an earlier milestone than 21H1, even though they have different shipping vehicles, this fix will ship in Windows around when Terminal 1.3 ships (if not slightly before)

**Comment by codeofdusk** [comment]
> this fix will ship in Windows around when Terminal 1.3 ships (if not slightly before)

Does this then mean that all the UIA work (#4018 etc) could ship *before* 21H1? nvaccess/nvda#10964 might need to be adjusted in that case.

**Comment by DHowett** [comment]
> before 21H1

To the insider program. I can't comment on the official Windows ship cycle from here, though. :smile:

**Comment by DHowett** [comment]
In general, though, my "21H1" or "21H2" milestones _very roughly_ track the Windows release. Since I can't comment on or commit to these dates on behalf of my organization, they're as good as advisory for my team and our partners. It's some amalgamation of "the last day we could possibly get features in" and "the day the bugfix bar drops", which is long before we sign off on a final build and ship the release to the general public.
