### ISSUE TITLE
Could i change to Enligsh base command line?

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#7004]
{
                "guid": "{ffff0fff-3ffe-5ff6-ffff-afce00bbccdd}",
                "name": "cmd",
                "commandline": "%comspec% /k \"chcp 437\" 1> nul",
                "hidden": false
                 }
My windows 10 is not English, if i run Windows terminal, I want to see English.
I Think, This solution is not good, Has anyone good idea for command line language change to English?

**Comment by driver1998** [comment]
A lot of builtin Windows command line tools uses current character set as a clue to what language to display their messages in, not just CMD.EXE.

(This is why it is forced to use English when using CP65001, because using anything else is not going to work for everybody)

So before this limitation is sorted out (unlikely), I guess you'll have to do something like this.
Although I'll suggest you to use CP65001 instead of CP437, that way at least you can use Chinese (albeit in UTF-8 instead of GBK).

**Comment by DHowett** [comment]
So, unfortunately, we can't control the language that CMD starts up in. Because it is tied to the legacy Windows localization system, it is going to follow the "operating system language" setting. I believe there are third-party products that will allow you to run multiple languages side-by-side and specify the language on a per-process basis. This isn't something Windows Terminal or the Console can help.

Sorry. ☹️
