### ISSUE TITLE
[Preview] Keep the Command Palette around after executing a command

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#7011]
# Description of the new feature/enhancement
I tested using the Command Palette after finding how to bind it in the PR (perhaps adding an entry bound to null in defaults.json would be in order). First I enabled the AlwaysonTop Mode. Then I wanted to do another command from the Command Palette. But as soon as I enabled the AlwaysonTop Mode, the Command Palette exited. If I open it and then press ESC, it will close the Command Palette. So we have a way to exit without executing a command. Therefore from a usability point of view, please don't close it unless the user explicitly closes it using ESC (or any other bound key used for exiting). This would help someone open and close multiple tabs/panes quickly as well as enabling/disabling different visual modes quickly. 

# Proposed technical implementation details (optional)
Alter the method used for closing the Command Palette to require a user explicitly do so. We can add a setting to change this behavior (which I guess could also be toggable, inception anyone?) to always close after executing a command but I think not many users will want that behavior.

**Comment by zadjii-msft** [comment]
So the command palette was inspired heavily by the ones in VsCode and Sublime, both of which dismiss by default after executing a command. I'm open to the idea of making this a setting, but keeping the current behavior as the default.

**Comment by DHowett** [comment]
If we can find good examples of other applications that _don't_ dismiss, I'd be glad to see them.

Most of our actions change the terminal in some way that is immediately attention-switching for the user. Not dismissing the command list would get in the user's way.

**Comment by WSLUser** [comment]
I would still prefer having an option to keep it around and closing it myself when I'm done with it. This is basically an alternative to constantly typing out wt arguments or enabling certain settings in the json file (such as retro and alwaysontop). It's not easy remembering all the argument syntax and I can't always have the page in front of me that tells me how to do it. So this provides a useful alternative to getting things how I want without messing with typing out an argument. I'd also argue it's a much faster way too for some usersl.

**Comment by DHowett** [comment]
So, okay, I've thought about this over the weekend.

I'd rather reduce the need to run back-to-back commands instead of making running back-to-back commands easier.

The right way to run multiple commands back to back to get the terminal into a known state is going to be through #5970. If a user has multiple things they need to do to a specific terminal before it's _usable_, and they're all things that are exposed via commands or config options, that's what a **profile** is for.

In the future, when we have 5970, "enter fullscreen and toggle retro mode" can be a single command so you don't need to run them back-to-back.

Please feel free to continue the discussion, but for now I'm gonna mark this one rejected.
