### ISSUE TITLE
UI Suggestion: Visually link tab to console view

### ISSUE THREAD

**Issue by mdtauk** [microsoft/terminal#702]
When work begins on polishing the user interface, it could be nice to make the tab and the console view feel connected, in a similar way to the teaser/trailer video shown at build tries to portray.

![image](https://user-images.githubusercontent.com/7389110/57567803-9fa38480-73d6-11e9-827a-549de5d65a62.png)

![image](https://user-images.githubusercontent.com/7389110/57567807-a500cf00-73d6-11e9-806f-39cc316e916b.png)

The window frame respects the app mode so Light or Dark.  But each profile's tab, will match the customised settings.

**Comment by Ghosty141** [comment]
So I'm currently hacking around with this but I found one issue that most likely makes this kinda hard to implement: The tab bar is not using the acrylic effect (yet). This makes the opacity of the tab (thus the color) not match the rest of the window. But there is hope! They seem to have this on the radar, I found this comment:

https://github.com/microsoft/Terminal/blob/6088134832b851c553af791ee17a9b5c0d808385/src/cascadia/TerminalApp/App.cpp#L643-L644

Here is how I did it (acrylic needs to be off else it looks bad): https://github.com/Ghosty141/Terminal/commit/16fc0af6c9f561f731288f6b6c37377871aac08a

**Comment by mdtauk** [comment]
I believe it's using a XAML Island, but there are other surfaces that can use Acrylic, and I'm sure as WinRT's presentation platform becomes open source in WinUI 3.0 - this will become more possible.

But thinking about where the app is heading now, will hopefully drive things forward.

**Comment by Ghosty141** [comment]
@mdtauk What I'm saying is that changing the tab color "can" only be done once the tab bar is using the acrylic effect, and I'm not sure how difficult this is to implement. I'll see what I can do and find.

**Comment by mdtauk** [comment]
Yea I get that, but the window itself is a Win32 window, so XAML acrylic brushes are a bit difficult.

But yes, matching tab colour to the console is a start, and removing the tab background colour

**Comment by DHowett-MSFT** [comment]
Funny enough, the code @ghosty141 changed ("how to set a brush maybe?") is code I wrote when testing this exact feature.

If you get the _actual brush_ from the background of the terminal control, you can copy the acrylic effect directly into the tab. Use the same acrylic setup as is in `TerminalControl` -- create a `HostBackdropAcrylicBrush`, give it a tint and opacity, and set that as the background brush.

Ideally, we'd be using a `.xaml` file and xaml "theme resources" instead of pushing brushes directly into controls at runtime. :smile:

**Comment by mdtauk** [comment]
ThemeResources would automatically refresh upon the user setting the theme.  Until Win32 gets official support, you'll have to redraw and detect the change

**Comment by zadjii-msft** [comment]
I think this would be a really cool setting.

If someone wanted to to go ahead an implement this, they'd probably need to:
* add a `GetBackgroundBrush` method to `TermControl`, in the `.idl`, `.h` and `.cpp` files. 
* Then when the control is focused (when the tab changes), you'd need to change the background of the tab to control's brush. When it's unfocused, you'd need to remove this brush (somehow).
* Then, I'd add a setting to enable this feature, since not everyone's going to want their terminal to look this way. I'd make it a global setting, so see `GlobalAppSettings`. I'm okay defaulting this behavior to on, but if people have problems with that, we can discuss it on the PR :)

**Comment by Ghosty141** [comment]
@zadjii-msft Thanks for the help! I'm currently working on it and trying to get the changing of the background to work.

**Comment by miniksa** [comment]
This is another department where @cinnamon-msft might want to weigh in on what this should look like relative to the design mockups we've already prepared.

**Comment by jamers99** [comment]
Daaaanng i like that mockup.

**Comment by Stanzilla** [comment]
My only problem with the released version is that tabs do not support opacity or acrylic. Which makes it impossible to match the colors perfectly if your Terminal background does.

**Comment by zadjii-msft** [comment]
It's already in PR! #13935

**Comment by bendem** [comment]
> Handy links:
> 
> * [Release Notes](https://github.com/microsoft/terminal/releases/tag/v1.16.252)

That's a dead link.
