### ISSUE TITLE
Cannot select 'wt' selection in Start -> Run

### ISSUE THREAD

**Issue by mdreinders** [microsoft/terminal#7025]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal version (if applicable): 1.1.2021.0

Any other software?
```

# Steps to reproduce

 Click Start, type 'wt'. A selection for 'wt  --  Run Command' comes up. If I click it, or the Open link, nothing happens. I need to click Run As Administrator for it to open correctly.

# Expected behavior

 It should launch Windows Terminal when I select it, press Enter, or click Open.

# Actual behavior

 Windows Terminal does not open as expected.

**Comment by DHowett** [comment]
Does this also happen if you run "Windows Terminal" from Start (not wt) or run "wt" from the traditional Run dialog?

**Comment by mdreinders** [comment]
Running Windows Terminal from Start Menu works fine. When I type 'wt' in the traditional Run dialog, I get:

![image](https://user-images.githubusercontent.com/52163666/88245748-f30d9580-cc5d-11ea-91f1-9d27067ff738.png)

**Comment by DHowett** [comment]
So, it looks like you're using 1.2 instead of 1.1 -- that's important info, because we changed how `wt.exe` is invoked in that version.

Can you go to the Settings > "Manage App Execution Aliases" page? It should be accessible in your start menu by searching for "app exec"

1. Can you share a screenshot of the Windows Terminal entries?
2. If you turn them all off, and then turn the "Windows Terminal Preview" one back on ... does it suddenly fix this issue?

**Comment by DHowett** [comment]
FWIW: Mine look like this-

![image](https://user-images.githubusercontent.com/189190/88245892-ac17a400-cc4d-11ea-9a50-4a2a7981672b.png)

**Comment by mdreinders** [comment]
This is how mine looks now. I upgraded today to WT 1.1 and WT Preview 1.2.
![image](https://user-images.githubusercontent.com/52163666/88246088-066d3080-cc5f-11ea-8d24-996f5acc43df.png)

Yes, I turned them both off, turned on 'Preview' and then I was able to click 'wt' which launched 1.2 Preview.

Thanks! I totally wish the Windows 10 Insider Program used Github. I couldn't imagine if we would be able to have this 'direct' contact with MS engineers with issues in Windows 10. This is night and day better than the Feedback Hub. Nothing personal to the various teams and obviously using GitHub for W10 would be monumental of an endeavor.

Still, this is very cool. Thanks again for the help!

- Michael

**Comment by mdreinders** [comment]
Oh, and, could you please send me a download link or repository link to 'Windows Terminal Dev'? ;) ;) ;)

- Michael

**Comment by DHowett** [comment]
So! Thanks for getting back to me. I'm gonna close this bug out and take up app execution alias migration with the internal team that owns it :smile:

I too wish that the feedback hub was a big github repo ... but at the same time, they've got so many millions of users, and it might be very hard to moderate it! Much harder than the Terminal's issue tracker!

Windows Terminal Dev is what you get when you build directly from source code in this repository. If you have Visual Studio 2019 (Community edition is okay), you should be able to do it. Note that it might not work right, since it's the absolute latest code.
