### ISSUE TITLE
Make new tab appear instantaneously

### ISSUE THREAD

**Issue by corvusblack** [microsoft/terminal#7054]
# Description of the new feature/enhancement

When I open a new tab, there is a noticeable 1-second delay before the tab is rendered and a weird animation when the text is drawn. See following gif.

![new-tab](https://user-images.githubusercontent.com/2031121/88359270-e2752200-cd26-11ea-8085-5dc88d61073c.gif)

This is somewhat distracting to me because for a split second it appears a new tab failed to open. I would like the tab to be  rendered immediately. I assume that fetching the tab text and icon is an expensive operation which is why it takes so long to render. In this case, could there be some kind of caching involved so the tab could be rendered instantaneously?

If caching isn't possible for some reason, I would at least like the tab background to be rendered immediately. Surely there is no reason for the tab background to take so long to appear. The text and icon can be added after it is fetched. Also, could the animation be disabled?

**Comment by zadjii-msft** [comment]
Hey so this is actually an issue with the WinUI TabView itself. It's actually being tracked over in https://github.com/microsoft/microsoft-ui-xaml/issues/1999. I'm gonna forward this discussion to that thread, since there are more details there. Thanks!

/dup https://github.com/microsoft/microsoft-ui-xaml/issues/1999
