### ISSUE TITLE
[Feature NEED] Tab color switching via JSON in config file.

### ISSUE THREAD

**Issue by zacknorman** [microsoft/terminal#7152]
Hi everyone,

sort-of a duplicate of [THIS](https://github.com/microsoft/terminal/issues/702) and [THIS](https://github.com/microsoft/terminal/issues/3310)... but damn, is this implemented yet? and if not... why?

I am trying to theme my windows terminal (Switching from Linux...)! Is there a property where I can set the terminal _tab_ colour for a specific profile? Like, if my profile uses background colour #2f2833, I'd want the tab colour to match. Basically, I don't want it to look like _THIS_ (cringe)

![image](https://user-images.githubusercontent.com/16888605/89133662-ba867b00-d4eb-11ea-8d95-3d2810140270.png)

I'd want it to look like _THIS_ as soon as I open a new terminal instance:

![image](https://user-images.githubusercontent.com/16888605/89133641-8317ce80-d4eb-11ea-8118-aa5e96edb7e3.png)

Sorry for the big screenshots (also sorry if this has already been answered, it's just a major pet peeve when I know this is possible!)

Thanks,
Zack

**Comment by skyline75489** [comment]
I'm positive that this is possible in terms of implementation. I'd suggest using the preview version of Windows Terminal to get the latest feature as soon as you can. I think #3327 is where we are heading

**Comment by zadjii-msft** [comment]
This definitely _is_ possible, but we were trying to make sure that we addressed this as a part of larger problem - theming (see #3327, #5772). We've also seen this request [a bunch of times](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aclosed+%22tab+color%22) in the last month since #3789 hit stable. I'm trying to pull _specifically this feature_ out from the larger spec in #5772 into it's own feature, which you can see in #7134. 


/dup #702 
/dup #1337

Thanks!
