### ISSUE TITLE
Terminal closes after wakeup

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/terminal#7183]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 10.0.20180.1000
Windows Terminal version (if applicable): v1.2.2022.0

Any other software? Microsoft PowerToys, etc.
```

# Steps to reproduce

1. Leave Terminal running.
2. After your computer (mine: Surface Book 2) goes to sleep, wake it up.

# Expected behavior

My Terminal window should remain open after the computer goes to sleep.

# Actual behavior

Windows Terminal closes, and I lose everything I was working on inside it.

**Comment by DHowett** [comment]
Yeah, this definitely shouldn’t happen.  

/feedback

**Comment by DHowett** [comment]
What’s up? Did this issue go away?

**Comment by nitishvijai** [comment]
@DHowett For some reason, it doesn't close anymore.

**Comment by DHowett** [comment]
So, if you file a feedback item we may be able to get information on the crash you _did_ see. It's not great if our application crashes out in the background :smile:

**Comment by nitishvijai** [comment]
Sounds good, here's the link: https://aka.ms/AA97gjr

Thanks for your time!

**Comment by DHowett** [comment]
Alas, I wasn't able to find any Terminal crashes in your feedback report. However, it did indicate that you might have had a bugcheck/bluescreen recently? I wonder if these things are related ...

**Comment by nitishvijai** [comment]
@DHowett That's interesting... last time I had a BSOD was 1-2 weeks back and I'm not sure if that was caused by the Terminal.

**Comment by Zelnes** [comment]
Hello, I've had the same problem, very annoying...
Actually it was not quite the same, because I've been able to interact with my terminals for one minute, then I changed the current window, and the terminal app crashed.
I just come back from the weekend, where I left my computer go to sleep.
One more thing, when I openned the terminal app, it asked me if I wanted to close all tabs, like if I had closed myself the window.
Hope it helps

**Comment by Eryx5502** [comment]
I don't know if Zelnes' is the same problem as the original one, but I do have exactly the same problem. It should be related with Microsoft Store, since the same happens to me for every other app I use from the store. They are all closed every time my laptop sleeps for some time (say 5 to 10min at least). I don't know how to hunt this issue, but it is really annoying.
