### ISSUE TITLE
ConPTY(?) inserts broken control codes into tmux sessions.

### ISSUE THREAD

**Issue by Efreak** [microsoft/terminal#7185]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable): N/A.

Any other software?
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
tmux 2.6
```

# Steps to reproduce

Open an ssh (other?) session with a running tmux session with default configuration.

# Expected behavior

tmux session opens as you've left it.

# Actual behavior

tmux opens with `1;0c` appended to whatever was at the prompt/cursor previously. Applications that consume control characters attempt to do something with them. (I haven't run into any issues with that yet, but it's possible; mostly I'm just in nano, which only complains about `Unknown sequence`).

----------

## Fix

Add a line to `tmux.conf`: `set -s escape-time 10`. Do this on every remote server you log into.

I should note that this is not actually an issue with *WT* per say--it also affects cmd.exe (which is what I primarily use for quick, single-command sessions). However, the fix I found was located 
[here](https://github.com/microsoft/WSL/issues/1638), which links to here as the correct place to file an issue.

## Screenshots

<details>

<summary>Screenshots</summary>

Connecting to my laptop running Ubuntu 18.04.3 via WSL
[![Running on my laptop in WSL](https://files.catbox.moe/y7p274.png)](https://files.catbox.moe/y7p274.png)

Running on a remote VPS with Ubuntu 18.04.3:
[![Running on a remote actual-linux server](https://files.catbox.moe/e247a9.png)](https://files.catbox.moe/e247a9.png)

If nano is running, I get a ding and an `Unknown sequence` message:
[![Opening a session that has nano running](https://files.catbox.moe/e4xb52.png)](https://files.catbox.moe/e4xb52.png)
This one with a running editor has gotten me several times before, as I tend to leave files open, sometimes with modifications to finish later.
</details>

**Comment by DHowett** [comment]
Would you mind trying this with SSH 8.1 from the [Win32-OpenSSH releases page](https://github.com/PowerShell/Win32-OpenSSH/releases)? This seems very similar to the issue where Vim starts in replace mode because Win32-OpenSSH 7.7 won’t pass the escape sequence through unmodified and WT/conhost is replying to a DSR

**Comment by zb140** [comment]
Not the OP, but I just came across this issue by searching because I'm seeing the same issue.  I tried it with SSH 8.1 and I can confirm it does indeed fix the problem. And the good news is, the SSH issue tracker says v8.1 is expected to ship in the next version of WIndows (https://github.com/PowerShell/Win32-OpenSSH/issues/1646) so I can be lazy about updating all my computers if I'm willing to live with it another couple months :wink:

Thanks!

**Comment by idl0r** [comment]
Sorry but is there any chance to get an official openssh client bump that's been installed through the feature list / window?

**Comment by DHowett** [comment]
I’m sorry, we don’t own that component. The best place to ask would be on their repository :smile:

**Comment by idl0r** [comment]
Is https://github.com/PowerShell/Win32-OpenSSH the official repo for this? is that's the one that's being installed through the features setup? I just thought that you know someone there by chance, since this is an official Microsoft one as well?

**Comment by jyn514** [comment]
> Would you mind trying this with SSH 8.1 from the [Win32-OpenSSH releases page](https://github.com/PowerShell/Win32-OpenSSH/releases)? This seems very similar to the issue where Vim starts in replace mode because Win32-OpenSSH 7.7 won’t pass the escape sequence through unmodified and WT/conhost is replying to a DSR

i am still seeing this happen with `OpenSSH_for_Windows_9.5p1`.
