### ISSUE TITLE
Under remote (ssh) GNU screen and tmux sessions large output causes horrible performance

### ISSUE THREAD

**Issue by jblaine** [microsoft/terminal#7191]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable): 1.1.2021.0

Windows 10 native ssh client
Remote Linux host running either tmux or GNU screen, multiple versions all work to reproduce issue
```

# Steps to reproduce

ssh to a host
run `screen` or `tmux` or attach to an existing session of either
run `cat` on a large text file, such as one with 3000+ lines

# Expected behavior

Terminal should display a somewhat consistent stream of text, like PuTTY, Powershell on its own, CMD.EXE on its own, and other tools do.

# Actual behavior

Terminal displays a little, pauses for several seconds, displays some more, pauses, etc

**Comment by zadjii-msft** [comment]
Correct me if I'm wrong, but how is this different from #7019? It might be best to merge this discussion with that thread.

* Does this repro **without** `tmux`/`screen` running on the remote host?
* Does this repro with the `ssh` from a WSL distro?
* More insane - if you run `wsl.exe ssh.exe <args to ssh...>` inside a legacy powershell/cmd window, does the same issue repro? This will cause wsl to create a conpty to host `ssh.exe`, which could help identify if the issue is conpty vs something else.

I'm also thinking this might be related to conpty buffering the frames to at least 1/60th of a second, maybe something weird in this situation is causing that delay to seem much larger

**Comment by jblaine** [comment]
Sure, I'm fine merging my comments over there. The info in #7019 seemed a little different to me at the time I created this.

I'll close this in favor of #7019
