### ISSUE TITLE
HTML terminal mode

### ISSUE THREAD

**Issue by wm2015email** [microsoft/Terminal#720]
I was watching your build 2019 presentation..

I'll tell you the feature i've always wanted for terminal windows: ** HTML terminal mode**... why not make a "VT" terminal code that can switch into HTML mode so that a program can directly dump HTML to the terminal window?  HTML is much better suited at advanced formatting than anything VT-terminal codes can do...  then, when the program is finished, the VT code to switch back to non html mode is issued.   Like you switch to "HTML terminal mode", which causes a chromium browser window to be embedded into the terminal window after the terminal prompt, and all the HTML issued from your command to appear there...  like javascript graphics... maybe you need to make a subset of HTML that's compatable with terminal mode?  like obviously no need for HTML header tags and all the formalities of HTML... just everything inside of the body tags to render in the terminal embedded chromium window with x,y set to be the starting point after the prompt.

**Comment by oising** [comment]
Don't you already have one of those things, a web browser, isn't that what they're called? :) To be honest, I get where you're coming from, but funnily enough, Microsoft tried something along these lines about 15 years ago in the form of HTA (html applications) and it rode the wave of html-all-the-things for a while, but ultimately it was just another form of Windows lock-in that has long since gone out of vogue. Doing something like this would tie just fork the browser landscape out even more. But really, VT codes aren't that bad and they are far more efficient over the wire than using a complex technology like HTML. And it doesn't just stop at HTML - what about CSS? And then people want JS, etc etc. 

Thanks for contributing your idea, but I think it's safe to close this one.

**Comment by wm2015email** [comment]
OK... i'll wait for linux support first... ;-)

**Comment by wm2015email** [comment]
<esc>[xtml;<resource file="snoopy.jpg" encode='base64'>sgksdkjfhskjdghalkdjfsglkjdfgsljkdfhglksjdfhglskjdfhlkgsjdfhlgksjdfhlkgsjdfhgslkjdfhlgksjdgfhskljdgslkjdfhglksjdglksjdflgskdjglskdjflksgjdfsklgjdgksljdfhksljgdfhl</resource><img src="snoopy.jpg"/><esc>[;0

**Comment by wm2015email** [comment]
application program:

printf("\<esc\>[html;<resource file='snoopy.jpg' encode='base64]>4523hkj34h52k3j4h52kj34h52k3j45g2j3kh4g52k3j4hg52j3h4g52kj34hg52kj3h4g52kj3hg452jk3hfg452kj3hg45k2j3hg45k2j3fg745k2j3hg452kj3hf4g52hk3g452kjh3f4g52kj34hg52kj34g52kj3f4g52kj3h4g52kj34g52kj354\</resource\>\<img src="snoopy.jpg"/\>\<esc\>[0;");

**Comment by wm2015email** [comment]
C:\> adventureland.exe
resuming where you left off...
as you approach you see a pirate with an empty bottle of rum leaning against an empty treasure chest mumbling incoheriently...
\<insert picture of drunk pirate lending against an empty treasure chest\>

 What do you want to do? hit pirate with empty bottle

**Comment by wm2015email** [comment]
C:\\> price_of_rice.exe --country china
![China___121212](https://user-images.githubusercontent.com/17484682/57586652-d5279b00-74c6-11e9-904e-e5d58908d3d5.jpg)
