### ISSUE TITLE
Quick Command as same as [XShell - Quick Command]

### ISSUE THREAD

**Issue by shinestmt** [microsoft/terminal#7207]
# Description of the new feature/enhancement
![image](https://user-images.githubusercontent.com/2135380/89599189-73a0d880-d891-11ea-9033-03a2ac440ee6.png)

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This sounds a lot like #5273 to me, just, as a toolbar rather than a side panel.

I think there's also #2934 which is kinda similar, but with profiles exclusively. I bet that however that would be implemented wouldn't be as just a bunch of profile buttons, but as a bunch of _action_ buttons. Combining that with #3799, you could probably get the functionality you're looking for.

/dup #5273
