### ISSUE TITLE
F7 tunneling broken

### ISSUE THREAD

**Issue by luzhkovvv** [microsoft/terminal#7297]
F7 tunneling introduced by #4807 seem to be broken in 1.2.2234.0 preview, but still works in 1.1.2233.0 release

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable): Version: 1.2.2234.0
```

# Steps to reproduce

Press F7

# Expected behavior

F7 key is passed to application

# Actual behavior

Nothing happens

**Comment by DHowett** [comment]
Thanks. It looks like it worked in 1.2.2022 as well.

**Comment by DHowett** [comment]
Good money says this regressed with #7145.

**Comment by luzhkovvv** [comment]
WOW! That's a lightning-fast fix! 👍

**Comment by KillyMXI** [comment]
Weird. I'm on 1.4.3243.0 and F7 doesn't work.

**Comment by DHowett** [comment]
@killymxi with what shell? Are you getting a “caret browsing” pop-up when you use it? Gotta share a bit more info than “it doesn’t work” 😄

**Comment by KillyMXI** [comment]
@DHowett Good question. It didn't occur to me to check it outside of WT.
Now I checked:

- PowerShell 5.1.19041.546 and 7.1.0;
- Bare, inside WT and inside ConsoleZ.

And in all 2x3 cases there were no observable reaction to F7 key (no pop-up, nothing at all). And in all of those cases F8 key did it's thing (autocompletion from history).

So it's not WT after all, but now I'm even more puzzled how to trace my issue. This was the only relevant thing I've found.
I even checked whether F7 is working on my keyboard now, and the key itself is functional.

**Comment by DHowett** [comment]
Ah! So, PowerShell doesn’t do anything with F7 by default since the advent of PSReadline. It’s a line editing library that handles history, syntax highlighting, history search, etc. Life is way better with it enabled, but if you want to test a few things without it you can always `Remove-Module PSReadline`! (It’s only temporary)

**Comment by DHowett** [comment]
(PSReadline is far more featureful than our old line editor, which is also the one that provides the F7 pop-up.)

**Comment by KillyMXI** [comment]
Ah, I see now. I could've realized that during my search. Sorry about that.

I rather should get familiar with the "new" default, so I'll go and read about PSReadline.

I was trying to refresh all the ways to work with history in PS, and since this one is being phased out, there is no point for me to resurrect it.
