### ISSUE TITLE
ugly border while background is white

### ISSUE THREAD

**Issue by xmokay** [microsoft/terminal#7310]
after change background white, a black border present as follow.
![2020-08-17_101331](https://user-images.githubusercontent.com/9464343/90351502-018b7900-e073-11ea-9ba0-c1d94782ca93.png)

remove the border as cmd.exe will looks better.
![2020-08-17_102041](https://user-images.githubusercontent.com/9464343/90351665-79f23a00-e073-11ea-9ab3-21b1811dee50.png)

**Comment by DHowett** [comment]
The `color` command can only change the background color of the _terminal cells_. Because there is padding and a hover scrollbar, the color behind them is not part of the terminal. The `color` command cannot change those colors, and it will never be able to. Sorry. :smile:

**Comment by vefatica** [comment]
If the padding is separate from the terminal cells, what about user-specified colors (active/inactive pane) for the padding itself?  That would certainly make it easier to spot the active pane (given Windows 10's 2-pixel borders).

**Comment by DHowett** [comment]
The `background` is the user-specified padding color.

**Comment by vefatica** [comment]
I missed the reference to CMD's COLOR command.  I imagine that's done with SetConsoleTextAttribute().  If so, after COLOR is issued shouldn't the control sequence \e[0m (et al.) respect the new default colors?  I don't think it does.

**Comment by DHowett** [comment]
It doesn’t because it _can’t_. There is a bit of an illusion here: there is no such thing as the default colors in a win32 console application. There’s only the active colors and the _starting colors_. Those are not a property accessible to or controllable by any API that a win32 console application can use. There is no way for the `COLOR` command, therefore, to change them. All it can do is repaint the entire buffer with a new attribute and pretend that no other application can change it.

In general, there is a mismatch between the VT and Win32 APIs in their capability and breadth. Mixing them isn’t highly recommended, and this _would_ be an instance of mixing them.

**Comment by vefatica** [comment]
It's no big deal to me.  Before today I hadn't used the COLOR command since the days of MSDOS.
