### ISSUE TITLE
Preprocess and convert C1 controls to their 7 bit equivalent

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#7317]
# Description of the new feature/enhancement

This is from a discussion in #6328:

> @j4james: I was actually wondering whether this was something we could handle as a sort of preprocessing step that converts all of the C1 controls into their two character 7-bit equivalent. That way we can drop all the extra code that's checking for 90 and 9B introducers, and 9C terminators, because those conditions would now be handled as regular 7-bit escapes.

**Comment by jdebp** [comment]
Surely the other way around is better?  Technically, per ECMA-48, it's those actual C1 characters that delimit command strings and control strings, and that begin control sequences.  `ESC Fe` sequences are just ways to represent them for 7-bit transports.  It has been almost 4 decades since the world went largely 8-bit clean.

**Comment by j4james** [comment]
> Surely the other way around is better?

Semantically does it make any difference? The only reason I was suggesting converting from the C1 controls to the 7-bit escapes was because I thought that would be easier to handle the way our parser is setup.

> It has been almost 4 decades since the world went largely 8-bit clean.

That may be so, but in practice most people are using UTF-8 nowdays, so those C1 controls don't really gain you anything and are very rarely supported (at least in my experience).

**Comment by skyline75489** [comment]
If I'm not mistaken, converting `ESC Fe` to C1 characters would require looking ahead one character beyond `ESC`. That would also be troublesome. I'd prefer the other way around which is techinically the same.

**Comment by jdebp** [comment]
You're looking to the next character _anyway_, otherwise you simply aren't doing escape sequences right.  And of course converting to the C1 characters means that scanning for (say) ST at the end of a command string or control string is just a single character test.

**Comment by skyline75489** [comment]
Well that’s not wrong but we are somewhat stuck with the current implementation that’s prioritizing 7bit instead of 8bit. And you can check out my PR #7340 if you’re interested.
