### ISSUE TITLE
Why can't I specify the desired initial size and position for each profile?

### ISSUE THREAD

**Issue by reb061342** [microsoft/terminal#7338]
I can't even set the desired initial size for each profile because "initialCols" and "initialRows"
only work as 'Global'--they don't work in profile settings.

And 'size' and 'move' which are available when using the context menu on the row of tab names
doesn't stick--those settings disappear when Windows Terminal is closed.

This is a major problem that should have been fixed a year ago.

**Comment by zadjii-msft** [comment]
`initialRows` and `initialCols` are global settings because they only apply to the initial launch of the Terminal window. Do you want opening a new tab with another profile (with a hypothetically different `initialRows` and `initialCols` value) to resize the current Terminal window? What about opening a new pane with that profile? What would happen then?

Persisting the window size and position across reboots is already tracked by #766.
