### ISSUE TITLE
Cannot drag and drop into ELEVATED Terminal to get the path of a file

### ISSUE THREAD

**Issue by su-hy** [microsoft/terminal#7343]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable):  1.1.2233.0 and preview  1.1.2233.0

Any other software?
```

# Steps to reproduce

I drag a file from Windows Explorer onto Terminal window and it does nothing. In CMD or Powershell windows it gives me a path to file. 

# Expected behavior

I expect to get a path to the file. I looked around and see that this is what should be happening, but it is not for me. 

# Actual behavior

See the GIF below:
![windows_terminal](https://user-images.githubusercontent.com/29263008/90618200-eefa7680-e20f-11ea-914c-d85a36a584dd.gif)

**Comment by zadjii-msft** [comment]
Huh, good find! As it turns out, drag/dropping onto an elevated window isn't supported _at all_. This is a platform security feature. You can notice the same behavior by trying to drag/drop a file onto an elevated `conhost.exe` (the vintage console). I'd also expect that there's no way for us to get around that, because the drag/drop service runs unelevated, so I don't think it's _possible_ for it to be able to send messages to elevated windows at all. 

Thanks for the investigation!

**Comment by su-hy** [comment]
Interesting. I tried it on another account and indeed, it works fine when I open Terminal in a regular way, and it does not work if I "Open as Administrator". 
The problem I had was that the first account I used opened Terminal as Administrator by default. Both those accounts are domain admins, but I guess there must be some difference between them. 
Thanks.

**Comment by dpmaycry** [comment]
Windows 10 2004 19041.572
Windows Terminal v1.3.2651.0
I am administrator and while my powershell and cmd works fine with drag file path, windows terminal still got the same problem.
