### ISSUE TITLE
Terminal app silently crashes

### ISSUE THREAD

**Issue by dbaines** [microsoft/terminal#7350]
# Environment

```none
Windows build number:  Microsoft Windows [Version 10.0.19042.450]
Windows Terminal version (if applicable): 1.1.2233.0

Any other software?
VS Code
MS Teams
Steam
Spotify
Chrome
```

# Steps to reproduce

Not entirely sure what happened as it was a silent crash.
The system has been up for at least two days.
Terminal was running a java app via maven and a gulp watch in separate tabs

# Expected behavior

If crashing, show an error with a possible message why

# Actual behavior

Terminal app silently crashes showing no error

# Event log

It did throw an event log which I can attach in full. I'm not sure if there's any security issues in doing so, I don't think it's a memory dump but I'm happy to forward to the secure email address if you like.
I think these parts from the event might be helpful:

Event log:

```
The program WindowsTerminal.exe version 1.1.2007.20001 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 ...
 Faulting package full name: Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe
 Faulting package-relative application ID: App
 Hang type: Quiesce
```

Problem history:

```
Description
A problem caused this program to stop interacting with Windows.
Faulting Application Path:	C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

Problem signature
Problem Event Name:	MoAppHang
Package Full Name:	Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe
Application Name:	praid:App
Application Version:	1.1.2007.20001
```

# Other

Might possibly be related to #7345 - but I didn't check if existing processes were still running, sorry. This crash occurred yesterday around 10am ACST.
Interestingly, the version reported in the event log doesn't match the version presented when opening Terminal's "about" screen - could it be related to a forced update closing terminal while still in use?

**Comment by DHowett** [comment]
Huh, this is unusual. This isn't what it looks like when the updater kills Terminal, but it looks like the updater did capitalize on the opportunity to install an update nonetheless (after Terminal died of other mysterious causes).

Would you mind filing feedback? That's an easier way to get us information than the secure e-mail address :)

/feedback

**Comment by dbaines** [comment]
Thanks @DHowett 

I have submitted feedback:
https://aka.ms/AA9bfet

**Comment by DHowett** [comment]
Okay, I'm going to have to swallow my own words here.

I had a colleague help me look at the "hang" dump (or crash dump) that we found when we investigated your feedback, and it looks like it's part of a group of hangs that happen when the "do you want to close all tabs?" dialog is open.

We've seen an uptick in these issues very recently--about 7 days since we released the last update. I'm starting to become convinced that this _is_ because of the update (and not the other way around.)

Here's my theory:

1. The store decides there's been an update available for long enough
2. It asks Terminal to exit nicely
3. Terminal resists, and says "i've got tabs open -- at least let the user confirm it"
4. _With or without an answer_, this looks like Terminal is another intransigent application that needs to be put down, and so it gets terminated and _blamed_ for "hanging".

This is a place where the platform treats us like a "store-managed" application, where we're really not.

I'm tentatively closing this as a /duplicate of #6726. Thanks for following up :smile:
