### ISSUE TITLE
'Windows Terminal' feature to color tab labels doesn't work in a reasonable way.

### ISSUE THREAD

**Issue by reb061342** [microsoft/terminal#7357]
Currently after setting a color for a tab label, that color appears only when the cursor is on the row of tab labels.  This rather defeats the purpose of coloring the label.  Wouldn't it be much better for the color of the label to remain in effect even if the cursor was not on the row of tab labels?
(If there is anyone who prefers the current behavior, how about at least giving users the option of choosing between these two different behaviors.)

Also a question:  Where are the tab color settings saved?  Not in 'Settings.json'...but where?

**Comment by WSLUser** [comment]
You can view all settings [here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings). You can also use the Command Palette if you're on Preview (you removed the template so no idea).

**Comment by zadjii-msft** [comment]
What are you talking about? The tab colors do persist as part of the tab's color even when the mouse isn't over them:

As far as setting the colors goes, there's two factors that control the tab color:
1. runtime tab color
2. (in master, and being released in 1.3): a profile's `tabColor` property.

If you use the color picker, you set the "runtime color". Otherwise, we'll try and use the `tabColor`. The runtime color isn't persisted anywhere, it's simply for this current session.

For more details, I'd read [this doc](https://github.com/microsoft/terminal/blob/master/doc/specs/%231337%20-%20Per-Profile%20Tab%20Colors/%231337%20-%20Per-Profile%20Tab%20Colors.md).

**Comment by reb061342** [comment]
Since the runtime color doesn't persist, it's of marginal value anyway.  I'll hope that 'tabcolor' in the json file will be more satisfactory when it is released.
