### ISSUE TITLE
cat command on a particular file changes the character encoding

### ISSUE THREAD

**Issue by shreyasmete** [microsoft/terminal#7358]
After running the cat command on file included in file.zip messes the character encoding.

[file.zip](https://github.com/microsoft/terminal/files/5105090/file.zip)

![Screenshot (2)](https://user-images.githubusercontent.com/36543806/90816338-bced2f80-e349-11ea-8c4b-189789c616d3.png)
![Screenshot (1)](https://user-images.githubusercontent.com/36543806/90816334-bb236c00-e349-11ea-8620-14ab7c8debde.png)

**Comment by DHowett** [comment]
YES! We've finally reached parity with other terminals.

This exists in many different places, in many different ways. At the heart of the issue: you've printed a binary file to the screen. It contained a sequence of bytes that indicated a "character set" switch.

Because the terminal can't detect--**no** terminal can, actually--when you're just haphazardly spewing binary data at it, it dutifully responds to the "character set" command.

To fix it, use `reset` from WSL or print the sequence `\e(B` (set character set to default/US-ASCII/ISO-8859-1)

**Comment by DHowett** [comment]
If you want to reproduce this on demand,

![image](https://user-images.githubusercontent.com/189190/90820374-220f3980-e2e6-11ea-9e4a-4d10ec13960d.png)

See the Designating Character Sets section of [the VT420 manual](https://vt100.net/docs/vt420-uu/chapter9.html#S9.5).
