### ISSUE TITLE
Keybindings, splitpane, commandline ... does it work?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7375]
I have these:

{ "command": { "action": "splitPane", "split": "auto", "profile": "Ubuntu"}, "keys": "ctrl+shift+u" },
{ "command": { "action": "splitPane", "split": "auto", "commandLine": "c:\\windows\\system32\\wsl.exe"}, "keys": "ctrl+shift+b" },

The first works nicely.  The second gives a split pane with the default profile in it (regardless of the EXE I specified by commandLine).

If commandLine works, what am I doing wrong?

I ask because I noticed that when I run WSL in a console I get one instance of the "init" process.  When I run "Ubuntu" in Terminal (as above) I get two instances of the "init" process.  Is that expected behavior?

 - Vince

**Comment by DHowett** [comment]
The settings file is case-sensitive; you should use `commandline` instead of `commandLine`. If you use a text editor that has Schema support like VSCode it will tell you if there are any issues with your settings file like that. Once you fix that, you will have an escaping problem. You will want to use `\\` because `\` has a special meaning in JSON.

I would not pay too much attention to the specific number of `init` processes, because they are used for multiple different things by WSL.

**Comment by vefatica** [comment]
Indeed, "commandline" works better.  But "commandLine" (not "commandline") is shown in this document:

**https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings**

  - Vince

**Comment by DHowett** [comment]
Thanks. We should fix that
