### ISSUE TITLE
Background color changes by itself sometimes

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#7398]
Compare:
Tab 1:
![image](https://user-images.githubusercontent.com/1041752/91201021-3ac18a00-e700-11ea-9d9b-b04b84248049.png)
Tab 2:
![image](https://user-images.githubusercontent.com/1041752/91201042-43b25b80-e700-11ea-9ff7-1ac8d838f14d.png)

I didn't do anything to change bg color of the first tab, it happened by itself.

**Comment by zadjii-msft** [comment]
That looks to me like acrylic turned itself off. Sometimes that just happens, by OS policy. I think there are some dupes for that floating around...

**Comment by vadimkantorov** [comment]
It looks super-weird :( especially given that this does not apply uniformly to all tabs

**Comment by zadjii-msft** [comment]
@vadimkantorov What OS version are you on? This might be #7047

(#1414 is also a related discussion)

**Comment by vadimkantorov** [comment]
Windows 10 version 2004, build 19041

**Comment by zadjii-msft** [comment]
Yep, that'll do it. I'm pretty confident you're seeing the affects of #7047. I _believe_ that's a bug they're gonna service, but I'm not totally sure about its status. I'd follow #7047 for updates.

/dup #7047

**Comment by vadimkantorov** [comment]
Is it that "transparency" does not work? Or is it that "transparency" gets enabled by itself?

**Comment by zadjii-msft** [comment]
Basically, the OS incorrectly decides that your system can't support acrylic (when it really can), so it disables it. It's not consistent though, which is why it seems like sometimes it doesn't work.

**Comment by vadimkantorov** [comment]
Maybe it's again related to CPU/RAM resources. But it looks supper weird. I'd prefer whole terminal downgraded or an option to always start it without Acrylic, rather than downgrading just one tab out of many

**Comment by zadjii-msft** [comment]
It's actually caused by a bug in DWM. It incorrectly doesn't re-populate the properties for the monitor or something - I don't really understand the bug. I do know that the bug is fixed already internally, so it won't be too long before it rolls out to Insiders.

The Terminal unfortunately doesn't really have any way to know if acrylic will or not work when we ask for it. That's not really something that XAML exposes to us, and I'm not really sure it's worth our effort to add some mitigation code on our side for a bug that's _already fixed_.

**Comment by vadimkantorov** [comment]
When I remove focus from Terminal, light-black turns back into dark-black. So yeah, probably DWM fix is the right place for the fix
