### ISSUE TITLE
[discussion] Disable/pause automatic scroll down

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#7406]
A usecase: a long-running build process that prints occasionally noteworthy things to terminal. I scroll up and want to read them or copy them. However when new output from build appears on screen, the terminal automatically scrolls down (even if I'm still dragging scrollbar by mouse).

In this usecase we would like to disable automatic scroll down and let the user inspect the previous output. Some options to support this usecase: disable this altogether (the user should scroll down themselves to resume auto-scroll-down); provide some keyboard/UI shortcut to enable this.

I think Gnome Terminal doesn't do this, but I don't remember for sure.

**Comment by DHowett** [comment]
Thanks! So, there’s a couple issues at play here.

We recently (1.2) implemented scroll locking when you are scrolled up or have an active selection. That part is automatic and unconfigurable. Scrolling will snap back when you press ~Print Screen~ a key that sends input (😉).

We had (fixed in #7247) a bug where we would let the buffer roll underneath the locked scroll region. The fix is about to come out with 1.2.2381.0.

We also have a critical lack of support for infinite scrollback, so you have between 9001 and 32k lines, depending on how you configured Terminal, to print out before the locked scroll region will age out. I can’t pull that issue up in quicksearch on my phone.

With those two things noted, do we need further discussion? 😄

**Comment by vadimkantorov** [comment]
No, I think we're good :) It would be fantastic to have this scenario to added on your functional testing usecase list or something like that :)

**Comment by zadjii-msft** [comment]
Oh don't worry, we've already [got the test covered](https://github.com/microsoft/terminal/blob/master/src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp#L155).

Thanks for following up!
