### ISSUE TITLE
Windows terminal hangs under stress after resizing vertical pane to the minimum width

### ISSUE THREAD

**Issue by Treit** [microsoft/terminal#7416]
# Environment

```none
Windows build number: 10.0.20197.0
Windows Terminal version: 1.2.2381.0
```
# Steps to reproduce
1. Open Windows Terminal
2. Press alt+shift+= to open a second vertical pane
3. Build and run this [TerminalStress](https://github.com/Treit/TerminalStress) application in the left-hand pane.
4. While the stress test is running, press `alt+shift+left arrow key` to reduce the size of the pane. Repeat until the pane is reduced to the smallest possible width.

# Expected behavior
The terminal does not hang.

# Actual behavior
The terminal becomes unresponsive and hangs.

**Comment by michalnpl** [comment]
I can reproduce this very easily. At the time of writing this is caused by deadlocks due to numerous race conditions in [ticket_lock.h](https://github.com/microsoft/terminal/blob/06526cac0c8a7e1a63fd187ce495e3b88522adff/src/inc/til/ticket_lock.h).

**Comment by lhecker** [comment]
> You can reproduce the deadlock without resizing terminals (let them be equally wide) but instead very quickly resizing the entire host window horizontally (I acknowledge this will resize terminals, though) by grabbing and dragging the right border of the host window).

Can you reproduce the issue without resizing the window to a width of 1 column? If you do, I'd be super interested in this, because I cannot reproduce such an issue myself. If you could get a minidump of Windows Terminal when this happens, this would be extremely helpful! The screenshot above however seems to show the deadlock that occurs when you resize the window down to 1 column and is not caused by any race conditions. It occurs because of the issue described above (i.e. an infinite loop in `AdaptDispatch::_WriteBuffer`).

> All the threads share the same instance of  recursive_ticket_lock and get deadlocked since checks like [...] are not thread safe and prone to race conditions, (only **_owner.load(std::memory_order_relaxed)** part of the **if** is atomic, the **!=** operator is not, which leads to race conditions.

You didn't mean the actual comparison there right? Since a `!=` on a `std::atomic<T>::load` return value is thread safe in on itself (`load` returns a copy of the integer after all). You meant that the underlying value may change while the current thread performs the comparison, right? In this case, yes, that's actually fine.

That code is a generic approach to turn any non-recursive lock into a recursive one. The assumptions are that `GetCurrentThreadId()` never returns 0, because that's the initial value for `_owner` (this is true for `GetCurrentThreadId()` as it contractually never returns 0). Furthermore, it's return value is unique for every thread and a single thread can only run a single strand of instructions at a time, which means that within a thread there's no need for synchronization.

With the above in mind, the only possible way that this if condition is ever skipped:
https://github.com/microsoft/terminal/blob/06526cac0c8a7e1a63fd187ce495e3b88522adff/src/inc/til/ticket_lock.h#L102

is when the current thread has already acquired the lock. If the current thread has not acquired the lock, the `_owner` value must be some undetermined other value. It's not really important what that value is, but it's definitely not the same as `id`, because only the current thread can have that value.

But back to the race between threads you brought up: As mentioned above, it is possible for two or more threads to enter this if condition simultaneously. Let's say 2 threads enter the if condition simultaneously. Thread A loads and compares with `_owner` and then acquires the non-recursive actual lock (`_lock.lock();`). It'll then write their own ID into `_owner`. Thread B has already loaded `_owner` in the meantime, but hasn't compared it (the race condition you brought up). The underlying value of `_owner` has changed and thread B is looking at stale data, however the result of the comparison hasn't changed anyways: The value of `_owner` is still not identical to thread B's `id`. Only the current thread can set a value that would make the `!=` comparison fail.

**Comment by michalnpl** [comment]
**Disclaimer: For now, I'll assume my theory is wrong not to confuse or lead anybody on a stray path, and I'll revisit it when I get back on my dev machine.**

> Can you reproduce the issue without resizing the window to a width of 1 column? If you do, I'd be super interested in this, because I cannot reproduce such an issue myself. If you could get a minidump of Windows Terminal when this happens, this would be extremely helpful!

Sure! I'll get the dump in the next few days; I'm not on my dev machine right now.

Implementation detail: **unlock** sets the **_ower** back to **0**:
https://github.com/microsoft/terminal/blob/06526cac0c8a7e1a63fd187ce495e3b88522adff/src/inc/til/ticket_lock.h#L115

> You didn't mean the actual comparison there right?

I did. Here is another, more in-depth description of my reasoing about how the race condition leading to deadlock happens on the following code:
```
      void lock() noexcept
      {
          const auto id = GetCurrentThreadId();

          if (_owner.load(std::memory_order_relaxed) != id)
          {
              _lock.lock();
              _owner.store(id, std::memory_order_relaxed);
          }

          _recursion++;
      }
```

After a number of locks and unlocks, the _owner is 0 due to mentioned implementation detail.
THREAD A: executes **_owner.load(std::memory_order_relaxed)** and gets 0.
CONTEXT SWITCH
THREAD B: executes **_owner.load(std::memory_order_relaxed)** and gets 0.
CONTEXT SWITCH
THREAD A: EXECUTES 0 != id (always true)
CONTEXT SWITCH
THREAD B: EXECUTES  0 != id (always true)
CONTEXT SWITCH
THREAD A: goes inside the if statement
CONTEXT SWITCH
THREAD B: goes inside the if statement
BOTH THREAD A AND B ARE INSIDE IF STATEMENT

From there on, both will attempt to try to call **_lock.lock** and upon possible return, set themselves as the _owner (corrupting the _owner value). In this case, I believe this exact scenario happens with 3 threads.

However, if **_lock.lock()** will prevent concurring threads that already entered the **if** from acquiring the lock and possibly corrupting value of **_owner** by each setting it to themselves - then I need to take a closer look at how the implementation of the **_lock.lock()** behaves in this scenario and if there are any more guards there.

**Disclaimer: For now, I'll assume my theory is wrong not to confuse or lead anybody on a stray path, and I'll revisit it when I get back on my dev machine.**

**Comment by michalnpl** [comment]
@lhecker I deleted my latest response not to confuse anybody. I see how I completely misunderstood the intent here and that the **if** block is actually designed for potentially many threads to enter it and block except the one with an active lock, in which case it will not enter the **if** and simply increase the recursive counter. The race condition I brought up is irrelevant due to the blocking nature of **_lock.lock()**. I apologize for the confusion, thank you for the detailed response, and I will follow up with Minidump when I can repro non-one width terminal width hang.

**Comment by lhecker** [comment]
I think the bug for freezes in general is #11903. Our leading theory is that it happens because we acquire a mutex on the main, while the rendering thread is holding it. If the rendering thread however waits on the main thread already (which can happen depending on the graphics driver implementation) you get a deadlock. #14959 would improve on this situation because it doesn't call any graphics APIs while holding the mutex anymore. Solving the issue fundamentally will have to wait a little longer though unfortunately (it requires being able to snapshot the text buffer).

**Comment by michalnpl** [comment]
@lhecker, regarding the hang, I think you might be right because as I resize the host window, the left terminal can get close to 1 width, so I reckon you are right about inserting a 2-column wide glyph into a 1-column theory. Just to be sure, I attach the window when it hangs:

![TerminalHang](https://user-images.githubusercontent.com/25628581/231889230-fd9fe34c-c11d-41de-9626-3678e186d451.png)

The parallel stacks:
![HangStacks](https://user-images.githubusercontent.com/25628581/231889273-a299a963-1567-4ebe-8bb1-1bf55ff847be.png)

And the minidump:
[WindowsTerminal_NoHeap.zip](https://github.com/microsoft/terminal/files/11226707/WindowsTerminal_NoHeap.zip)
