### ISSUE TITLE
Make Windows Terminal in-built app into Windows 10

### ISSUE THREAD

**Issue by ShaunakSawant** [microsoft/terminal#7425]
# This new feature will make the two different command-line interface apps, Command Prompt and Windows Powershell replaced by the Windows Terminal which will come built-in with Windows 10 with robust new features and updates the Windows Terminal app gives making a new Command-line interface for Windows 10.
I had suggested it on the Feedback Hub app and it got many upvotes:
[https://aka.ms/AA93zee](url)

**Comment by zadjii-msft** [comment]
You know, I'm _sure_ there's a dupe for this, but considering discussion we were having this week, I'm going to leave this open. 

@cinnamon-msft do we have an internal deliverable/scenario we can link to this one externally? Or do we have another issue that's already tracking this?

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/issues/492> perhaps?

**Comment by zadjii-msft** [comment]
So #492 is slightly different. #492 is tracking changing Windows to allow the user to specify another application as the default terminal application that's launched when running a commandline client, instead of conhost.exe.

This one's more specific to "ship Windows Terminal in-box". The two _together_ make a really compelling story, where the Windows Terminal is the default terminal on Windows, and it comes with Windows by default, and if people don't like the Terminal, they're free to change to any other emulator.

**Comment by cjwijtmans** [comment]
That would be cool. Launch the console with win+r instead of runbox then move runbox to win+shift+r or something.

**Comment by zadjii-msft** [comment]
Oh hey, look:
https://blogs.windows.com/windows-insider/2021/03/17/announcing-windows-10-insider-preview-build-21337/
