### ISSUE TITLE
NewTab won't leave the Command Palette

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#7441]
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version : 1.3.2382.0
```

# Steps to reproduce
Add the following to your settings.json:
```
{ "name": null, "command": { "action": "newTab", "commandline": "wsl.exe" }, "keys": "f2" }
```

# Expected behavior

This entry does not appear in the Command Palette.

# Actual behavior

It appears in the Command Palette after explicitly setting "name" to null.

**Comment by DHowett** [comment]
_oh no_, this is another instance where we need to know the difference between `null` and `""`!

Except not in JSON. In Command.cpp:33-66

**Comment by Hegunumo** [comment]
Hi. I've tried to resolve this, and I think it can't be since code is acting the way it is.
`{ "name": null, "command": { "action": "newTab", "commandline": "wsl.exe" }, "keys": "f2" }` and 
` {"command": {"action": "splitPane", "commandline": "wsl.exe" },"keys": "f2" }` are pretty much treated as exactly same(meaning they are both `null`) so no matter I use something like `name.isNull()`, `name ==Json::Value::nullSingleton`, and `name == NULL` `"name": null` would pass `if (const auto name{ json[JsonKey(NameKey)] })` in Command.cpp line 63 and `_nameFromJson() `returns `L""`. All I am saying is that if there are way to differentiate
`{ "name": null, "command": { "action": "newTab", "commandline": "wsl.exe" }, "keys": "f2" }` and 
` {"command": {"action": "splitPane", "commandline": "wsl.exe" },"keys": "f2" }`
this issue can be resolved. Sorry if I'm wrong.

**Comment by Don-Vito** [comment]
@zadjii-msft, @DHowett - so this one is broken for 4 months.. and actually I am not sure when it really worked last time for commands that have action args :blush: Right now I don't see any evidence it ever worked 🤔 

So.. I am not sure if it is acceptable.. but cannot we simply replace this mechanism with something more explicit and parse-able. Like adding a dedicated field (aka "hideFromPalette")? Since I am not sure we can call it breaking compatibility

**Comment by zadjii-msft** [comment]
FYI future readers: #8402 has more investigation in it too.

Yea, I think the `"name": null` idea for hiding came about long before auto-generated names did, so now hiding with a null name seems weird.

I'm almost wondering how important **hiding default commands** is in the first place. It doesn't really seem like we've gotten requests for it. It's not like having default keybindings, where their presence might impact other apps. 

That would certainly make the design easier. If we didn't need to worry about hiding defaults, we could focus on just hiding commands defined by the user.

**Comment by atimholt** [comment]
For what it's worth, I'm always for as much customizability as possible. The presence of commands that one has long decided they're never going to use creates a measure of noise and, worse, can often hinder "fluent" use by necessitating more keystrokes for the fuzzy-find search.
