### ISSUE TITLE
CMD History Pop-up Color Settings

### ISSUE THREAD

**Issue by atrenton** [microsoft/terminal#7449]
# Description of the new feature/enhancement
Add foreground / background color settings for the F7 CMD History pop-up window.

Allow popup windows colors to be configured equivalent to old Command Prompt properties.
# Proposed technical implementation details (optional)

Add pop-up window color configuration settings to cmd.exe profile.

**Comment by DHowett** [comment]
Thanks for the request! This one we're probably not going to do. The popup code that CMD is using (which is unfortunately shared between cmd, python, powershell-without-psreadline, cdb, and every other traditional console application) is not something we're willing to change right now.

It's possible to set the colors using the SetConsoleScreenInformation API, however. A small application could be put together that allows for this customization, but it's going to have to come from somebody else.

Part of the issue is that it will never be able to support the rich color sequences that terminals written after 2005 tend to support. It's a legacy fixture, and we're going to have to treat it like one.
