### ISSUE TITLE
Copying doesn't work in mcedit on WSL

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#7470]
# Environment

```none
Windows build number: 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 1.3.2382.0
MC version: 4.8.24
```

# Steps to reproduce

Open a file in mcedit and try to copy the contents from it

# Expected behavior

Text is copied

# Actual behavior

Text isn't copied

**Comment by DHowett** [comment]
_mcedit_ has taken control over the mouse, and has implemented its own selection method. You will want to file a bug on them to report the clipboard content change, or turn off mouse mode in mcedit.

You can also hold down <kbd>Shift</kbd> while dragging your mouse to give Terminal control over the selection instead of mcedit.
