### ISSUE TITLE
Integrated PowerShell not working properly

### ISSUE THREAD

**Issue by anshdhinhgra47** [microsoft/terminal#7485]
# Environment

```none
Windows build number: [run OS Version: Windows_NT x64 10.0.18362 for powershell]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Stop the server using Ctrl +C

# Expected behavior

On entering n/N as input, the server should not stop running.

# Actual behavior
The integrated PowerShell stops the server even after accepting n/N as an input. An image for reference is attached below.

![windows_powershell_error](https://user-images.githubusercontent.com/56676059/91756221-04957600-ebea-11ea-9f1c-ae27351944dc.png)

**Comment by WSLUser** [comment]
Did you file also with VSCode (which you didn't mention but is clearly shown in the screenshot)?

**Comment by anshdhinhgra47** [comment]
Yes, but they closed the issue and asked me to file here.

**Comment by WSLUser** [comment]
Ok, then try using Windows Terminal. It comes with a newer conhost known as OpenConsole. If this works, you can either 
1) Continue to use Windows Terminal (recommended)
or
2) Disclaimer: Completely unsupported, not endorsed, here be dragons :
Locate OpenConsole.exe, copy it to system32, rename to conhost.exe (backup the original first). now you'll be running a newer console by default for the OS. If new problems occur, you'll be on your own.

**Comment by WSLUser** [comment]
Please also note you can configure VS Code to launch Windows Terminal as an external terminal in Settings for VS Code. Also would suggest a backport of the particular fix (once a bisect between conhost and openconsole is done) for this issue.

**Comment by anshdhinhgra47** [comment]
Alright.

**Comment by KalleOlaviNiemitalo** [comment]
AFAIK, the "Terminate batch job (Y/N)?" question comes from cmd.exe, rather than PowerShell. For example, if you have an `progs.bat` file that contains two lines

```
prog1.exe
prog2.exe
```

and you run `progs.bat` and press Ctrl+C while `prog1.exe` is running, then `prog1.exe` is first terminated; after that, `cmd.exe` asks whether you want to terminate `progs.bat` as a whole or proceed to run `prog2.exe`. 

So, I suspect that:

* Your `npm start` command runs some `npm.bat` or `npm.cmd` file, which then runs npm from its installation directory.
* Your Ctrl+C has already terminated npm before the "Terminate batch job (Y/N)?" question appears.
* The behavior would be the same even if VSCode, PowerShell, and Windows Terminal had not been installed.

**Comment by DHowett** [comment]
@KalleOlaviNiemitalo is correct.

@WSLUser’s suggestion will not change this reality, and he should not be suggesting it to people who are not having _console problems_ 😄
