### ISSUE TITLE
Pane divider?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7501]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.18363.1016 (1909)

Windows Terminal Preview 1.3.2382.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Split a tab vertically

# Expected behavior
Unknown

# Actual behavior
See below

Here are magnified pics of the split ... first, when the right pane is active

![image](https://user-images.githubusercontent.com/61856645/91928124-3c172780-eca9-11ea-8622-c90e34ab6faa.png)

... second, when the left pane is active

![image](https://user-images.githubusercontent.com/61856645/91928167-5d781380-eca9-11ea-9ac8-c179a9bb183f.png)

In the second case (left pane active) there's an extra vertical bar.  ???

In both cases there's a blue thingy (window border?).

**Comment by DHowett** [comment]
You may need to share a larger screenshot so that we can understand the context in which you're reporting this bug.

Here's what's up/what should normally happen:

![image](https://user-images.githubusercontent.com/189190/92012481-5aa90d00-ed01-11ea-8f30-97f8841c5d13.png)

The pane divider is split into two parts: "active" (matches your system accent color) and "inactive" (matches the system default chrome color). The "active" color surrounds the pane you are currently focused on, and the inactive color surrounds all other panes.

This is most evident when you have multiple panes visible:

![image](https://user-images.githubusercontent.com/189190/92012648-8fb55f80-ed01-11ea-9cf2-b792627e3ea9.png)

We've never seen reports of this gray bar you've indicated on the righthand edge of your left pane, but I can't help diagnose without a screenshot that includes the rest of the pane layout ;P

**Comment by vefatica** [comment]
Here's the whole thing, sitting on the desktop, left pane active.

![image](https://user-images.githubusercontent.com/61856645/92013879-5dfdc200-ed1c-11ea-9f4e-bc8d31e47195.png)

**Comment by DHowett** [comment]
K, that's a scrollbar. This is by design as explained above.

**Comment by vefatica** [comment]
I know there's a scroll bar. What's the thin vertical grey stripe next to it ... the inactive part of the pane divider?  That's not entirely obvious and (at least for me) it doesn't provide much of a visual signal (of anything).

In your pic there are some very thin scroll bars (yes/no?).  How do you get them?

**Comment by DHowett** [comment]
Yes, the thin gray strip is the inactive part of the pane divider. It's more evident when you have more than one split pane.

I'm using this setting:

![image](https://user-images.githubusercontent.com/189190/92017336-7663e180-ed08-11ea-84a5-4381c86edd81.png)

**Comment by vefatica** [comment]
I should have known.  I tried that when Windows 10 was new and didn't like it.

Why is there no scrollHome/scrollEnd

**Comment by DHowett** [comment]
Because nobody's implemented it yet.

**Comment by vefatica** [comment]
Does it need to be suggested/requested?

**Comment by DHowett** [comment]
Is it meaningful to go to the top of a 9001-line buffer and see the lines that are about to scroll off the top of the screen while output is actively being processed? scrollToEnd is covered by input snapping (press a key, it jumps to the prompt line) already...

When in doubt, search for related issues! :smile:

**Comment by vefatica** [comment]
With 9001 lines available, it's likely that the beginning of a session is available.  If you wanted to get there ...

Can't the input snapping be turned off?
