### ISSUE TITLE
Num Lock inverse behavior.

### ISSUE THREAD

**Issue by furameister** [microsoft/terminal#7510]
So when I enter my root password which has numbers in it, I use the numeric keypad. The bug is that when the num lock is activated the numbers do not work and when it is deactivated it does work. I have tried to open the Windows Terminal with the num lock off and activate it when it is running but it still has this bug.

**Comment by furameister** [comment]
I forgot to mention that this bug only happens entring root passoword.

**Comment by jdebp** [comment]
You really need to tell people what the thing is that is running using Windows Terminal for its I/O here.  Is it WSL?  If so, what application program is running on WSL?  `sudo`?  `login`?  `cat`?

**Comment by furameister** [comment]
The bug only happens when entring root password.

**Comment by DHowett** [comment]
Terminal can't know that you're entering a password--especially not specifically your root password--at that point.

Is it possible that your root password was set with numlock in the reverse state, and now it appears as though you have to turn numlock _off_ to make it work?

If you reset the password with `passwd` to a version where you make sure numlock is _on_... does it then work?

**Comment by furameister** [comment]
Still not working.

**Comment by DHowett** [comment]
Thanks for the info.

I'm going to ask you to reproduce the issue with the the debug window enabled.
**This will expose your password, so I suggest that you change your root password to one that can reproduce this bug but is not your actual password.**

If you are willing to do that, follow the steps below.

<details>
<summary>How to capture debugging information</summary>

1. Edit your settings to add `"debugFeatures": true,` at the top (under the first `{`)
2. Open Terminal
3. Open the new tab dropdown
4. Hold down <kbd>Left Alt</kbd> and <kbd>Right Alt</kbd> at the same time
5. Launch the profile that you're having trouble with
6. Release <kbd>Alt</kbd>s
7. You should see a new tab with two windows, one of which contains the raw output from the profile
8. Reproduce the issue. Make sure you have focused the pane running WSL, not the debug pane. You should see characters you type printed in red, like this: `␛[16;42;0;0;0;1_` 
9. Reproduce the issue
   * Make sure you capture a working transaction and a broken one
10. Send me the transcript of the debugging information (select, copy, paste into a .txt file or something)

This document will contain everything that came out of _and went into_ the application. Since you changed your password (as suggested above), this shouldn't be an issue. If you'd be more comfortable, you can send it to me at the `@microsoft.com` address on my GitHub profile.

</details>
