### ISSUE TITLE
"Disable Scroll-Forward" doesn't account for page-up/page-down keys

### ISSUE THREAD

**Issue by carlreinke** [microsoft/terminal#7514]
# Environment

Windows build number: 10.0.19041.0

# Steps to reproduce

1. Start PowerShell in conhost.
1. Enable "Disable Scroll-Forward".
1. Run a command that produces multiple screens of output.
1. Use the page-up key to scroll to the top of the output.
1. Use the page-down key to scroll past the output.

# Expected behavior

Scrolling it limited to the output and the scrollbar lets you scroll the output.

# Actual behavior

After running command, scrollbar is as expected:
![image](https://user-images.githubusercontent.com/11667451/92039310-1aae4e00-ed32-11ea-81d2-0893d2d913ed.png)

After page-up key once, scrollbar is indeterminate:
![image](https://user-images.githubusercontent.com/11667451/92039360-2c8ff100-ed32-11ea-9507-92a3cd5103b2.png)

After page-up key again, scrollbar indicates that you see all the output (but you don't):
![image](https://user-images.githubusercontent.com/11667451/92039398-39144980-ed32-11ea-8289-39689beb257d.png)

After page-down key, you have scrolled past the end of the output:
![image](https://user-images.githubusercontent.com/11667451/92039443-4c271980-ed32-11ea-9d06-4e268c9d8717.png)

**Comment by DHowett** [comment]
So I've got some unfortunate news!

PowerShell (specifically PSReadline) has implemented its own handling for <kbd>PgUp</kbd>/<kbd>PgDown</kbd>:

In these handlers (code [here](https://github.com/PowerShell/PSReadLine/blob/a88c22fd60a69f41d1b727b7c51b5cbf8f9b5f68/PSReadLine/Render.cs#L1263-L1288)), they're directly manipulating the console screen buffer.

Because they're setting the actual active viewport using these APIs, there's nothing we can really do but listen to them. If they want to scroll the viewport into the unpopulated region below the virtual bottom, they're fully allowed to do so.

Resolution on this one is, regrettable, "by design" -- we have to support these APIs forever, even if they coincide with our experimental features in an unfortunate way.
