### ISSUE TITLE
Dragging or tabbing to a file with full-width chars in its filename causes caret be pushed way out of sync

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/terminal#7546]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable): Tried on both 1.2.2381.0 and 1.3.2382.0

Any other software?
```

# Steps to reproduce
 
1. Name a file using full-width characters in its filename
2. Attempt to either drag the file into the window or tab to the file while in the correct folder for auto-complete
3. Notice that the caret gets pushed way off to the right, and stays that way for everything after the full-width chars

Not sure if its related to the full-width issue or not, but tabbing to the file also incorrectly escaped [ ] chars that were in the filename as well, adding a doublequote in front of each square bracket

# Expected behavior

No cursor desync to occur, and correct handling of full-width chars

# Actual behavior

Caret desync and improper special char escaping

**Comment by DHowett** [comment]
_What shell are you using inside Terminal_? The shell makes a huge difference here.

**Comment by Masamune3210** [comment]
Sorry, didn't even think about that. It's PowerShell

**Comment by DHowett** [comment]
This is interesting!

It appears to be an issue in older versions of PSreadline, the line editing library in PowerShell.

![image](https://user-images.githubusercontent.com/189190/92540314-00c0af80-f1f9-11ea-99c2-8bb9ddb3c59d.png)

![image](https://user-images.githubusercontent.com/189190/92540328-0e763500-f1f9-11ea-82db-6d8a3255ce90.png)

It works fine with the version of PSReadline that comes with PowerShell 7, and it works fine without PSReadline.

The extra quote character comes from overzealous (but not incorrect!) escaping, and it should be fine.

It appears as though PSReadline does some codepage translation when it believes that the console cannot display fullwidth characters.

Here, I have changed the codepage to one that supports FW.

![image](https://user-images.githubusercontent.com/189190/92540416-5c8b3880-f1f9-11ea-9098-97863798452f.png)

It now works.

Gonna close this one as external but fixed, since it is not a problem in newer versions of PowerShell.

Thanks!

/dup https://github.com/PowerShell/PSReadLine/issues/289

**Comment by Masamune3210** [comment]
Is powershell updated externally? Always assumed it was updated as part of the OS? This issue occurs on latest stable of Win10

**Comment by DHowett** [comment]
PowerShell 5.1, the version that comes with Windows, will not be updated any longer.

They have moved all of their effort to their new (well, it is years old by this point) open-source version that you can install from https://github.com/powershell/powershell.

**Comment by DHowett** [comment]
More info here: https://microsoft.com/PowerShell

**Comment by Masamune3210** [comment]
Ok, thanks! Was unaware that the built-in version had been shuttled
