### ISSUE TITLE
[DISCUSSION] Allow more URI schemes

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/terminal#7562]
# Description of the new feature/enhancement
We recently added support for hyperlinks (but only certain schemes so far). We should add support for more URI schemes. 

Discussion points:
- Which schemes should we support?
- Which schemes can be easily allowed without much security risks and which would require more thought?
- Is it on us to deal with the security concerns with regards to clicking links or is that on the user?

**Comment by dodexahedron** [comment]
What about a more generic implementation of URI parsing to match anything that fits the RFC, and leave handling actually opening it to Windows? Artificially implementing schemes, explicitly, on a one-off basis, seems limiting and more complex.

**Comment by PankajBhojwani** [comment]
You are completely correct that this way is more complex/limiting. However there are security concerns with regards to allowing any scheme to be opened (see the discussion in #7526 for example). 

That being said, I have marked this issue as a generic place to discuss adding support for more URI schemes, and further concerns regarding security/viability/etc can be talked about here. 

@j4james, would love to hear your input on this!

**Comment by dodexahedron** [comment]
Well taken.

I tend to be of a mind aligning with the third bullet point above, for a few reasons:

- This particular feature *is* just a convenience to the user, and isn’t likely to be a primary means of interacting with it.
- A user who has downloaded, installed, and is using Terminal is significantly less likely to be a novice user who doesn’t understand the repercussions of clicking random links.
- The text, as displayed, *is* the link, is it not? In other words, it’s not like an HTML page, where the displayed text may not match the actual target of the hyperlink.
- I *highly* doubt a malicious actor would go through the effort of having someone open up Terminal in order to carry out their dirty deeds, when there are *far* simpler ways of getting someone to click a nasty link.

A question/thought, though: If clicked hyperlinks are launched in such a way that UAC will be invoked, regardless of the permissions Terminal was launched with, would that not also be a fairly decent safeguard, leaving all responsibility then up to the user to confirm they want to do something potentially dangerous? Is that behavior possible?

**Comment by j4james** [comment]
I think by default most protocols should warn the user before opening, similar to the way browsers do, with a dialog telling them exactly which application is going to be opened, and the url that triggered the event. We can whitelist a few protocols by default (http being an obvious candidate), but I think that list should be really short. Users can always choose to whitelist individual protocols, but I wouldn't make that too easy for them, otherwise they'll just blindly whitelist everything.

When it comes to the file protocol in particular, we need to be even more careful. I don't think it's good enough to have a blanket whitelist for all file urls. One possibility would be to whitelist particular file extensions in the same way we would whitelist the protocols. So we default to popping up a warning - again letting the user know exactly which application is going to be opened - and then they can always have an option to whitelist trusted file extensions if they really want to.

Another thought I had was to `ShellExecute` the file urls using an `edit` verb. So for example if you clicked on a file url for a Python script, ideally we want to allow that to open in an editor, but never allow it to execute. I don't know how feasible that is in practice, though. Does `edit` guarantee that nothing will every be executed? And are there any file extensions that we would want to support that couldn't be opened that way? That needs to be investigated.

Finally, I should point out that I'm not a security expert, but in my experience security people tend to be way more paranoid than me about stuff like this, and I'm terrified of this functionality. If I were you, I wouldn't want to implement anything that hasn't been signed off by someone senior in Microsoft's security team, especially if we're planning to add hyperlink support to conhost as well, or if Windows Terminals is going to be become the default Windows console one day.

**Comment by KalleOlaviNiemitalo** [comment]
I looked for ways to avoid having a list of safe URI schemes in Windows Terminal, but didn't find any.

* [IAttachmentExecute](https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nn-shobjidl_core-iattachmentexecute): Requires a file name.
* [ASSOCDATA_EDITFLAGS](https://docs.microsoft.com/windows/win32/api/shlwapi/ne-shlwapi-assocdata) (FTA_OpenIsSafe, FTA_AlwaysUnsafe) or [AssocIsDangerous](https://docs.microsoft.com/windows/win32/api/shlwapi/nf-shlwapi-associsdangerous): Most ProgID keys that have a "URL Protocol" value do not have any "EditFlags" value. Some have FTA_Show = 0x00000002 or FTA_SafeForElevation = 0x00200000.
* [Bind Context String Keys](https://docs.microsoft.com/windows/win32/shell/str-constants) (perhaps an IBindCtx could be provided via [SEE_MASK_FLAG_HINST_IS_SITE](https://docs.microsoft.com/windows/win32/api/shellapi/ns-shellapi-shellexecuteinfow#see_mask_flag_hinst_is_site-0x08000000)): Nothing suitable.
* [STARTF_UNTRUSTEDSOURCE](https://docs.microsoft.com/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa#STARTF_UNTRUSTEDSOURCE): Could be added via [ICreateProcessInputs::AddStartupFlags](https://docs.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-icreateprocessinputs-addstartupflags), but ShellExecuteEx might not create a process, and the URL handler application might not support the flag.

[ASSOCSTR_FRIENDLYAPPNAME](https://docs.microsoft.com/windows/win32/api/shlwapi/ne-shlwapi-assocstr) and [IHandlerActivationHost](https://docs.microsoft.com/windows/win32/api/shobjidl_core/nn-shobjidl_core-ihandleractivationhost) seem to be ways to get the name of the URL handler application, if Windows Terminal wants to display that in the warning.

**Comment by DHowett** [comment]
So, in general I agree with the arguments made on behalf of security here. However, there's one issue that tips me in the other direction:

Given the basic premise that a remote application can't generate meaningful file URIs (it lacks knowledge of the layout of the remote system and any ability to drop files in known places), the concern about an application printing a link to an executable or executable document applies only to _local_ applications.

But then... any would such a local application that can produce a path to a malicious executable not itself simply _do the bad thing_? It's running with the user's integrity level and identity already. It can do far, far worse things than trick the user into clicking a link to another EXE file. It _is_, or can just directly spawn, an EXE file.

The same holds for URIs handled by applications that act immediately (like a hypothetical `ms-settings:reset_system?confirmed=yes&confirm_token=aaaaaa` (which doesn't exist, but illustrates the point). Those applications are already potential vectors for attack _regardless_ of who's calling them.

So I guess my question is ... what's the attack, and how does Terminal launching file URIs amplify it?

**Comment by DHowett** [comment]
If we were talking about terminal automatically fetching (or launching!) URLs as directed by an application, I'd be more concerned . . .

**Comment by miniksa** [comment]
I've located an internal contact related to URI handling and reputation. We'll reach out to the experts at Microsoft who have already handled this for other products and get some advice.

**Comment by j4james** [comment]
> Given the basic premise that a remote application can't generate meaningful file URIs (it lacks knowledge of the layout of the remote system and any ability to drop files in known places),

If it knows you're on a Windows box, it can reasonably assume it'll be able to find a bunch of executables under c:\Windows, or /mnt/c/Windows. It doesn't have to be right 100% of the time.

Also, note that most exploits are a combination of vulnerabilities. You may be thinking this isn't a problem because an attacker can only execute files that are already on the system, but can't drop files there. But there is likely also a developer somewhere thinking they don't have a problem because their vulnerability only allows the attacker to drop files on the system, but not execute them. Combine the two and the user is screwed.

I should also mention that the original proposed hyperlink code would already have allowed a file url to run remote executables using a UNC path to a public SMB share. In my tests, the OS did at least seem to detect that as a remote executable and provide a warning, but I wouldn't want to rely on that being an insurmountable defence. Anything that lets an attacker get closer to an exploit is a bad thing, even if it doesn't seem to go all the way.

**Comment by TheXenocide** [comment]
I found this while trying to use vscode://file/[path to file]:[line] URIs using ANSI Hyperlinks. IT would be very helpful to use already registered system handlers. I don't see why it needs to be any more secure than a browser (e.g. Are you sure, Choose Application, etc.) but if it was necessary maybe the configuration file can whitelist allowed schemes?

It would also be super handy to have a URI that could enter text as input on the current terminal as I'd love to make my powershell scripts more interactive with less text on the screen. Seems like this could go really well with VCS tooling, powerlines, directory listings (e.g. a hyperlink that change directory to a specific parent) and such. 

One of the first things that came to mind to test this with was adding a little config gear to my powerline and making it a hyperlink to `vscode://file/$PROFILE` or to edit a json config file similarly.

**Comment by mkanet** [comment]
I would love to be able to create **mailto:** and **msteams://** clickable links similar to how we open https:// hyperlinks in MS Terminal.  I can't tell from the above discussion if we will see this capability or not.  Hopefully, there will at least be _some_ way to achieve this through a work-around or official feature.

**Comment by zadjii-msft** [comment]
_note to self: ```Write-Output "`e]8;;msteams://foo`e\This is a link to teams?`e]8;;`e\"``` doesn't work, cause we manually block that._ 

I don't think we ever came to a decision one way or the other. We need to find someone who's an actual expert in this area to give us a bit more feedback. I don't think we're opposed to the idea, but we just don't want to go into this blindly 😄

**Comment by Araxeus** [comment]
Would love to see support for `::{CLSID}` and `shell:` schemes

For example, I have an interactive directory explorer (https://github.com/Araxeus/ls-interactive) and I'm trying to make everything a link
The problem is linking to `My Computer` - there isn't any valid path to it, only one of the schemes mentioned above
```
shell:MyComputerFolder
```
```
::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
```

> here's one convenient source for those: https://docs.rainmeter.net/tips/launching-windows-special-folders/

**Comment by WasabiFan** [comment]
Big 👍 here.

If there's uncertainty over which schemes are "safe" to automatically allow, it seems to me a configuration option to enter a list of schemes (or a URL regex) would be an effective stopgap. I have scripts which output `vscode://` and similar URLs as mentioned in a comment above and it's ineffective in Terminal.

**Comment by mkanet** [comment]
Maybe some URI's that aren't a security concern can get added first?  Who actually decides what can get added and what can't?

**Comment by zadjii-msft** [comment]
I mean, ultimately we as the maintainers decide what can and what can't, though, with feedback from the community. I kinda come down to two trains of thought:

* What schemes are safe for us to enable always? `https`, sure, but the rest I honestly don't know enough about the threat space here to make any sort of decision. That's where I'd love input from someone who _is_ an expert, and that we haven't had the cycles to dig up.
* How can we conditionally add support for additional schemes? Even if we don't allow all of them by default (and I'm sure we never will), what's the best way of enabling users to pick and choose which _are_ enabled? Is this just a list of well-known URI schemes that we let folks opt in to? Or maybe more broadly a whole list of regexes? How do these layer (i.e. profile-specific settings on top of `profiles.defaults` ones)? Another question I certainly haven't had the cycles for recently.

**Comment by Seldaek** [comment]
@zadjii-msft IMO enabling people to add schemes at least (much simpler than allowing complete URI regexes, and I don't really see the benefit as the URI regex should match all of them anyway) would already be a good 80-90% solution. 

I'd add `phpstorm` or `vscode` to an array of allowed schemes in my config (augmenting the defaults of `https`, `http`, `file`) and would become able to click those links. By doing this I'm also taking the responsibility for possibly adding threat vectors, but I doubt there are many ways URIs can be abused, as links are so prevalent online.

Given the utility this brings for developers opening files directly in editors from CLI output, I think it's well worth the addition and the minimal risk this carries.

I fully understand you don't want to spend too much time on a 100% solution here, but it seems like adding the config option for schemes and supporting it in https://github.com/microsoft/terminal/blob/143127d6c4810488df851ae99abe5789fec11e10/src/cascadia/TerminalApp/TerminalPage.cpp#L2461 and wherever the highlighting-on-hover/parsing happens (I could not find this, grepping for `http` or `file` is a nightmare 😄) is reasonably low effort and would resolve the issue for most I'm sure.

**Comment by zadjii-msft** [comment]
You know, there's a good point that I think has maybe been lost in the last two years. I think we long ago conflated "autodetected URIs" with "manually emitted" ones. 

I think there's a lot more minutia that would go into adding more URIs to auto-detect, and how that plays with some other regex asks. 

But I think I've lost the part of the discussion where we only allowed OSC8 links to `https:`, `http:` and `file:`. I'll need to dig for why that was. Seems like from the other discussion notes there's no reason to filter out the other URI schemes, we just only ever supported those to start with...
