### ISSUE TITLE
Is "ctrl+shift+z" available for binding?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7568]
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.18363.1016 (1909)
Windows Terminal Preview
Version: 1.3.2382.0
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Try to bind some command to "ctrl+shift+z".

# Expected behavior
It works.

# Actual behavior
It doesn't work.

I couldn't find any mention of "ctrl+shift+z" being special.  Using "unbound" first doesn't help.

**Comment by DHowett** [comment]
It appears to work here.

```json
        {"command":"tabSearch", "keys":"ctrl+shift+z"}
```

![ctrl_shift_z](https://user-images.githubusercontent.com/189190/92507336-a9501e80-f1bb-11ea-906e-57b13eff7e6f.gif)

It may be worth checking that you do not have another application listening for C-S-z as a global hotkey.

**Comment by vefatica** [comment]
That's what it was ... an obscure minimize to the tray feature of my shell.

**Comment by wthrower** [comment]
> That's what it was ... an obscure minimize to the tray feature of my shell.

To be specific, I believe the shell in question was TCC by JP Software. I say that because I encountered a similar issue. In my case I was trying to "redo" in an application that uses Ctrl+Shift+Z as the keyboard shortcut for "redo", and Windows Terminal kept restoring/minimizing. I found myself here, and I saw the comment I quoted, but couldn't tell if it was pertinent to my situation, so I moved on. I ended up tracking it down using spyxx. Hopefully, by naming the specific shell here, I can save the next person some time. As a bonus, I'll also explain how I solved it.

As far as I can tell, you can't disable the hotkey, but you can change the binding. I chose backslash.

Edit tcmd.ini. Running `notepad "%_inifile"` from TCC will open the right file, but you'll (probably) need to be running the shell as admin. In the `[4NT]` section, add `TrayHotKey=\` (or whatever key you choose). So, something like this:

```
[4NT]
TrayHotKey=\
```

**Comment by DHowett** [comment]
> Hopefully, by naming the specific shell here, I can save the next person some time. As a bonus, I'll also explain how I solved it.

Thank you so much for adding this info! Great investigation 🙂

**Comment by wthrower** [comment]
> `%_ININAME` refers to the INI file currently in use; not `%_INIFILE`.

Thank you for catching that. I have corrected it in my comment.
