### ISSUE TITLE
An empty OSC8 followed by an SGR 0 fails to terminate hyperlink over ConPTY at the bottom of the screen (!)

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#7597]
Behavior:

![image](https://user-images.githubusercontent.com/189190/92791945-f837b880-f361-11ea-85d7-51a0212dbbed.png)

There might be something in conpty that should be calling the new `SetDefaultMeta...` method.

**Comment by DHowett** [comment]
```
printf '\e[01;32m\e]8;;file://dhowett-sl/mnt/c/Users/duhowett/_viminfo\a_viminfo\e]8;;\a\e[0m'
```

**Comment by PankajBhojwani** [comment]
This is _interesting_ - the SGR0 is not necessary to repro this, it happens because of _both_ the '\e[01;32m' at the beginning and the '\n' at the end:

`printf '\e[01;32m\e]8;;http://example.com\aayylmaoo\e]8;;\a\n'`

will repro this whereas

`printf '\e]8;;http://example.com\aayylmaoo\e]8;;\a'` or
`printf '\e[01;32m\e]8;;http://example.com\aayylmaoo\e]8;;\a'`

will _not_

**Comment by PankajBhojwani** [comment]
Found the issue (in PR now) - though I suspect similar things will pop up _eventually_ because of old code where SGR reset was no different from resetting only the default meta attributes
