### ISSUE TITLE
Context Menu Integration

### ISSUE THREAD

**Issue by MisterJ936** [microsoft/terminal#7606]
# Description of the new feature/enhancement
The feature that I would like and I think most programmers want is the ability to open the terminal in a specified directory. In that said the feature is when a client/user right click on a folder he/she will be given an option to open the terminal in the specified directory.

this will is a good way to open terminal in a directory easily. 

# Proposed technical implementation details (optional)
You see, I was trying to create this feature by myself so that I can actually open the terminal in the directory. the problem is that it seems I cant able to work. Please check the images bellow.

this is the bat files the I created to easily add and removes in the registry.
![1](https://user-images.githubusercontent.com/31676163/92946064-bce3d980-f488-11ea-88ba-10177b2a55ea.png)

if you run the install.bat, you will be able to get this options when right clicking to a folder or inside a folder.
![2](https://user-images.githubusercontent.com/31676163/92946070-be150680-f488-11ea-9f0f-2cfa234f956d.png)
![3](https://user-images.githubusercontent.com/31676163/92946073-bead9d00-f488-11ea-98f1-e1594af88f65.png)

the problem was when I tried to click Open Winders Terminal here. The terminal shows this error.
![4](https://user-images.githubusercontent.com/31676163/92946077-bf463380-f488-11ea-8dc1-628714352787.png)

the source code is in my repo.
# [MyRepo](https://github.com/MisterJ936/Explorer-Context-Menu-Integration-for-windows-terminal)

**Comment by DHowett** [comment]
I'm sorry--we can't look at that code. It doesn't have an open-source license (or any license at all), and it is therefore proprietary software.

Based on your error message, you are using `new` instead of `new-tab` and you are not passing the `-d` option.

You may want to look at the output of `wt new-tab --help` to validate how the starting directory should be passed. :)

(Our built-in shell extension doesn't support directory/desktop backgrounds because of a Windows bug ☹️ #6414)
