### ISSUE TITLE
Ctrl + T does nothing

### ISSUE THREAD

**Issue by marcel-piehler** [microsoft/Terminal#763]
* My Windows Build Number:
10.0.17763.437

* What I'm doing and what's happening: 
When I press Ctrl + T nothing happens
![image](https://user-images.githubusercontent.com/47207871/57679976-e12d6d00-762c-11e9-9452-f83a50333b48.png)

* What's wrong / what should be happening instead:
Open a new tab and show settings gear

**Comment by CagatayUlubay** [comment]
Have you read the "Getting Started" Section (https://github.com/microsoft/Terminal#getting-started) and the small section above it (I tried running WindowsTerminal.exe and it crashes!)?

Seeing your Build Number, you are already failing the first requirement: "You must be running Windows 1903 (build >= 10.0.18362.0) or above in order to run Windows Terminal"

**Comment by marcel-piehler** [comment]
Oopsie. Thank you!
