### ISSUE TITLE
Preview 1.4 - select profile from right click of pinned icon crashes explorer.exe

### ISSUE THREAD

**Issue by dsolodow** [microsoft/terminal#7702]
# Environment

```none
Windows build number: 10.0.20215.0
Windows Terminal version (if applicable): 1.4.2652.0

Any other software?
```

# Steps to reproduce

Pin Windows Terminal Preview to taskbar
Right click pinned taskbar icon
Select any profile
# Expected behavior

Windows Terminal launches selected profile

# Actual behavior

Brief pop-up about target moved and explorer.exe restarts.
Event log shows explorer.exe crash referencing kernel32.dll
![image](https://user-images.githubusercontent.com/7574074/93963330-e4f5f700-fd2a-11ea-859f-acde4a882894.png)

**Comment by KalleOlaviNiemitalo** [comment]
A Web search for 0x0eedfade suggests this exception code is used by Delphi. Perhaps a shell extension written in Delphi has been loaded to the explorer.exe process and is throwing this exception.

If I understand correctly, selecting a profile from the jump list does not run any Windows Terminal specific code in the explorer.exe process; instead, Windows Terminal has previously registered a shell link that points to `wt.exe` with arguments, and Explorer then starts that via ShellExecuteEx. Perhaps the Delphi shell extension has somehow hooked this operation and attempts to examine the `wt.exe` file but fails because `wt.exe` is an app alias reparse point rather than a real executable, and that then causes the 0x0eedfade exception.

If you can get a stack trace of the exception, e.g. by attaching a debugger to explorer.exe and then triggering the crash, I think the faulty shell extension will be easy to identify from that.

**Comment by DHowett** [comment]
Filing a diagnostic with the feedback hub may help us determine why Explorer is crashing -- or at least find a specific extension to blame.

Thanks for the digging @KalleOlaviNiemitalo!

**Comment by dsolodow** [comment]
https://aka.ms/AA9qlzd

**Comment by dsolodow** [comment]
I had a chance to do a bit more testing today, including against my work PC which is on 20H2 rather than Dev ring.
Same issue, and it looks like only one shell extension in common between the two PCs.
Disabling/removing that extension solved the crash, and I've reached out to the vendor of the app in question (PowerArchiver 2019).
Their beta/RC version of the extensions doesn't seem to have the issue.

**Comment by DHowett** [comment]
Yep! It looks like those crashes are in `pashlext64.dll`. Thanks for engaging with them :smile:

I'm gonna close this one out as external.
