### ISSUE TITLE
cursor doesn't move and typing is overlapped before right arrow or enter

### ISSUE THREAD

**Issue by hongwj12** [microsoft/terminal#7761]
Yeah/

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or ubuntu]
Windows Terminal version (if applicable):

window terminal : powershell or ubuntu

Any other software?
```

# Steps to reproduce

cursor doesn't move and typing is overlapped before right arrow or enter

# Expected behavior

cursor moves in proper way

# Actual behavior

cursor doesn't move and typing is overlapped before right arrow or enter

you can see this error in the video below
https://www.youtube.com/watch?v=cxeePuQvI4o&feature=youtu.be

**Comment by DHowett** [comment]
This is because you are using an IME/"Input Method". /dup #6192

**Comment by bradkim06** [comment]
I use Korean IME and had the same problem. In my case this problem was solved by deleting the Hangle & Computer IME (Hancom Input Method Editor). I don't know other Korean IME is also a problem, but I only use Microsoft Korean IME, the problem does not occur anymore. Check it out and hope it's resolved.

**Comment by hongwj12** [comment]
Yeah, I solved the problem through the way you mentioned!
