### ISSUE TITLE
Question - how to disable the tabs list when I use CTRL + Tab to switch between tabs

### ISSUE THREAD

**Issue by Tsimopak** [microsoft/terminal#7779]
I started to notice in the new update that once I press CTRL + Tab, a new window popup is being shown and showing which tab will be chosen, the thing is I don't like it and I want to change to the previous state, could it be done via the settings?

**Comment by DHowett** [comment]
Yes. Set `useTabSwitcher: false`.

Just so we know: What's your problem with it? We'd love to see if we can make it better. :smile:

**Comment by Tsimopak** [comment]
@DHowett thanks for fast response!

It's a nice feature, it's very much looks and feel "windows" feature, which is not bad.
But there's a chunk of people ( myself including ) that use the new terminal to mimic somehow unix environment, in that case the tab switcher is something redundant.

On the other hand I'd like to see more "unix" features, for example middle mouse click for paste, or once new tab is being opened it will be on the same pwd as the previous one.

But overall you are guys doing fantastic job! It's just my own opinion to prefer not using it. :)

**Comment by DHowett** [comment]
Thanks :smile: I really appreciate it.

**Comment by DHowett** [comment]
(We're planning a feature we've called "pointer bindings" which would let folks re-bind how the mouse works -- including middle click)

**Comment by Tsimopak** [comment]
That's sweet! :) I'll stay tuned for the upcoming releases for sure.

**Comment by G-Rath** [comment]
@DHowett the reason I'm going to turn it off is because it's not fast for me - I could see its use if I had lots of tabs open in the one window, all with their own names, but I use tmux + prefer to have multiple windows since theres no way to detach (i.e they're not chrome tabs yet) so I can't re-organise them based on context.

As such, when I do have tabs it's because I'm heavily into a thing and so have two or three - the tab switcher is nice but in this situation really slows me down since I have to unpress all the keys; with it disabled, I can just ctrl and then do tab & shift + tab to quick jump between my two or three tabs for rapid terminal hacking :)

(this is one of the reasons I'm looking forward to improvements around tabs being more chrome-taby, for lack of better descriptor - ideally I'd like a sort of beefed up tmux crossed with IntelliJ/vscode that lets you split screens & tabs, detach and attach as you like, etc)

**Comment by aaron-613** [comment]
This was my problem with the new tab switcher:

![image](https://user-images.githubusercontent.com/7603332/95418516-50b2a380-096a-11eb-832e-ae5bd5b365f0.png)

They all look the same!  I'd rather just cycle through the actual windows because I'll recognize what I see.  And (I guess?) I'm used to Chrome's ctrl-tab  behaviour.

Thanks!
