### ISSUE TITLE
Title erase when starting Linux terminal from command line

### ISSUE THREAD

**Issue by yaute74** [microsoft/terminal#7795]
# Environment

```none
Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal Version : 1.3.2651.0

OpenSUSE Leap 15.2
fish, version 2.7.1
```

# Steps to reproduce

Launch WT from command line:
```none
wt -p "openSUSE-Leap-15.2" --title test 
```
# Expected behavior
To have 'test' in the tab title

# Actual behavior
I have: "fish /mnt/...." in the tab title

If I modify the title tab name manully after the start of WT it's ok.

**Comment by zadjii-msft** [comment]
This is by design - the `--title` param only sets the initial title for the window, and I'd bet that you have `fish` configured to set the title. If you don't want `fish` overriding the terminal, you'll probably want to change your `fish` config.


I guess the other potential solution here is having some way of passing in the runtime tab title override to the `new-tab` command. I'm not sure how we'd expose that clearly, but I guess that's not totally a terrible idea

**Comment by yaute74** [comment]
You are right, I do a test with bash and it's ok.
I will ask to the fish team if it's possible
Thanks
