### ISSUE TITLE
How to resolve console application exited with code 9009

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/terminal#7836]
Im try to run a c# console application in build process by using below command

   ```
 <Target Name="AfterBuild" AfterTargets="AfterBuild">
        <Exec Command="$(ProjectDir)$(OutputPath)$(AssemblyName).$(OutputType)" />
      </Target>
```

Error when Build : error exited with code 9009

Note : This error occurs due to my project have space in  parent folders

this same scenario working fine when parent folder name does not have space

How to resolve this issue?

**Comment by jdebp** [comment]
**This is _nothing at all_ to do with Windows Terminal, note.**

The command line syntax of, and quoting rules that you should be using in, [an `Exec` task in MSBuild](https://docs.microsoft.com/en-gb/visualstudio/msbuild/exec-task) are the same as you would use passing a command line to the `cmd` command interpreter, because that is of course what it runs.

**Comment by zadjii-msft** [comment]
Yea, this doesn't have anything to do with the Terminal, so I'm gonna close this thread. The link @jdebp provided should be able to help you.
