### ISSUE TITLE
Support Hindi Glyphs in the Terminal

### ISSUE THREAD

**Issue by raj6996** [microsoft/terminal#7846]
When I type or paste  नमस्ते, it doesn't shows correctly.
How to fix it?
Powershell and cmd
![hindifont_terminal error](https://user-images.githubusercontent.com/16426916/95319443-83e72b00-08b5-11eb-8288-8197fce66035.jpg)
Here is more: "कम्पाउन्डर" "हॉस्पिटल" "नुकसान"
![hindifont_terminal error](https://user-images.githubusercontent.com/16426916/95320330-f86e9980-08b6-11eb-970d-d5a01bd9db7e.jpg)

**Comment by zadjii-msft** [comment]
I bet this is due to us scaling the glyphs to fit neatly in the grid spaces, which is causing the glyphs to be misaligned like that. I know we have another issue open that's tracking those scaling issues, but I can't find it off the top of my head.

 I don't think we officially support Hindi at this point, so I'm just going to turn this into the "Support Hindi Glyphs" issue. Thanks!

**Comment by DHowett** [comment]
This is a specific instance of #1472; should we keep it around?

**Comment by o-sdn-o** [comment]
To support scripts such as Devanagari (Devanagari is the script for Hindi) in the terminal, a monospace font is required, since scaling the glyphs irreparably shifts the [shirorekha](https://www.quora.com/Is-shirorekha-the-name-of-the-line-that-is-used-on-top-to-link-all-the-letters-of-a-word-in-the-Devanagari-script-If-not-what-is-the-name-of-it), as in the screenshots above.

The unit of writing in Devanagari is a syllable (Devanagari is [abugida](https://en.wikipedia.org/wiki/Abugida)), so the font _must_ support ligatures for syllables.

Two cells wide (M:N = 6:2) Devanagari syllable `र​्ल​्क​ि -> र्ल्कि`
![indic_syllable](https://user-images.githubusercontent.com/11535558/95545502-7b0e6a80-0a17-11eb-9fbf-8e6f7090c6b9.png)

The big problem is that the final width of a syllable ligature can be up to 5 cells, this is determined by a cascade of font rules, therefore the terminal cannot display the ligatures correctly without interacting with the font. Also, the terminal must be able to work with such ligatures as with indivisible characters.

I am making [such a font](https://github.com/monotty/fonts) for use in terminals, it is not finished at the moment, but suitable for experimentation in the terminal.

**Comment by zadjii-msft** [comment]
You know, let's just track this with #1472 after all. Thanks all!

/dup #1472
