### ISSUE TITLE
Transparency not passing through when using git

### ISSUE THREAD

**Issue by musm** [microsoft/terminal#7847]
I'm having a hard time localizing if this is a git or windows terminal or neovim issue. But alas, here's the problem. Perhaps `git` for windows is setting something that it shouldn't.

- `nvim --version`:
```
> nvim --version
NVIM v0.5.0-709-g4f8d98e58
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
 - Operating system/version: Windows 10, Version 20H2 (Build 19042.546)
- Terminal name/version: Windows Terminal v1.3.2651.0
 
 

### Actual behavior
** Note the black background which should be transparent ** when using normal git operations 

![image](https://user-images.githubusercontent.com/4319522/95352984-c2b6ba00-0890-11eb-8f0b-2706ebf6baf2.png)

Note the black background surrounded by the transparent border (which should be the actual background) 

### Expected behavior

Normally using `nvim` (no issues w.r.t background transparency) 

![image](https://user-images.githubusercontent.com/4319522/95353161-f560b280-0890-11eb-8fbb-3bd547fda019.png)

**Comment by DHowett** [comment]
This is another instance of the [color banding issue](https://docs.microsoft.com/en-us/windows/terminal/troubleshooting#my-colors-look-strange-there-are-black-bars-on-my-screen) described here. Specifically, it looks like Vim for Windows is explicitly requesting a black background.

**Comment by desmap** [comment]
@DHowett just checked the troubleshooting docs and that color banding and I'm not sure if it's really related. Whatever, I couldn't get it to work with my use case:

I am using neovim/nvim and face a similar issue. Windows Terminal seems to respect a set bgcolor and treat it as opaque instead of setting all defined backgrounds as transparant.

So is this intended by design? If yes, what would be the motivation behind that. Should be open a new issue or what are the next steps?

For other driving by, I could fix this by just turning off the set bg color and redefine on Windows Terminal level but this is just a very hacky work around no one should aim for.

Here the issue: https://github.com/neovim/neovim/issues/13065#issuecomment-753789430
