### ISSUE TITLE
Why the Windows Store?

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/terminal#7898]
I am perhaps looking from high-up, sorry if this was explained elsewhere. It is not clear why the involvement of the Windows Store? It this a UWP app? Is this a pure WIN32 App?

**Comment by mdtauk** [comment]
Its a hybrid app (in advance of WinUI 3.0) and the Windows Store can provide more than just UWP apps

**Comment by DBJDBJ** [comment]
Thank's @mdtauk ... Although the question remains unanswered: Why the Windows Store?
And suddenly there are two more questions. 

1. Why the Windows Store?
2. Why the Hybrid App?
3. Why WinUI 3.0?

Three clear and simple questions in total :wink: 

And now one "why" into my direction: Why am I asking this? Simply because I was under the impression this (Windows Terminal) will replace Terminal host, cmd.exe and PowerShell, etc in Windows 10 with this one superior product?

**Comment by PhMajerus** [comment]
Windows Terminal will never replace cmd.exe and PowerShell because these are completely different things.
cmd.exe and PowerShell are text-based apps (aka CUI) that use text streams as their inputs and outputs instead of pixels and events, conhost and Terminal are apps that lets you interact with such apps by providing a graphical interface for them that produces the pixels and handle inputs acting as the frontend for CUI apps.

Terminal will probably replace conhost for new CUI apps, but conhost will remain for legacy support as they are not completely interchangeable for some cases.

**Comment by zadjii-msft** [comment]
1. We're using the Windows Store because it's an effective means of deploying and distributing our application to users without the team having to do much work ourselves. It also makes delivering updates easier. We're also deploying releases on [our github page](https://github.com/microsoft/terminal/releases).
2. We're one of the first of a new class of applications. These "hybrid" apps aren't really Win32 apps, and they're not really UWP apps. In the near future, developers for Windows should stop treating the two as separate targets. In our case, we wanted to use UWP XAML to have a modern UI experience, but we needed some classing win32 APIs for connecting to commandline client applications. So building the terminal as a "hybrid" win32 application using XAML Islands was the only way to make this possible.
3. [WinUI](https://github.com/microsoft/microsoft-ui-xaml/) 3.0 is just the next iteration on the concept of these hybrid applications. We're actually not using WinUI 3 yet (because it's still only in preview), but we are using WinUI 2.(something)

The Terminal is here to replace `conhost.exe`, the "window" for applications like `cmd.exe` and `powershell`. The Terminal can be used to run lots of different commandline applications, including linux shells with [WSL](https://github.com/microsoft/WSL/).

**Comment by DBJDBJ** [comment]
@zadjii-msft Many thanks Mike. Is there any info somewhere how can we make Visual Studio projects that will target The Terminal instead of cmd.exe? I assume this is one of those too obvious to see. Thanks ...

**Comment by zadjii-msft** [comment]
Not currently. The long-term plan is to allow users to set a "default terminal" application on Windows, so that all console applications will spawn the specified terminal, rather than `conhost.exe` (the vintage console window). That work's being tracked over in #492
