### ISSUE TITLE
WSL word wrapping issue in small windows

### ISSUE THREAD

**Issue by tomyummmm** [microsoft/terminal#7904]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.508]
Windows Terminal version (if applicable): 1.3.2651.0

Any other software? WSL Ubuntu-18.04
```

# Steps to reproduce

1. Open WSL and cd to a folder with a long path
2. Resize window / split pane with duplicate until current path has word wrap on 3rd line.
3. Do anything / enter / clear and see that word wrapping has glitched, causing multiple prints of the prompt.

# Expected behavior
Only show 1 print of the prompt like CMD and Powershell

![image](https://user-images.githubusercontent.com/65211592/95833766-ad4cfe80-0d6e-11eb-8d4c-1f2fe2931043.png)

# Actual behavior
Word wrapping past 2 lines in WSL causes the prompt to print and overlap twice. Should behave like CMD and PS

![image](https://user-images.githubusercontent.com/65211592/95833707-99a19800-0d6e-11eb-9a45-d24c891c62d4.png)
CMD on the left, PS in the middle, WSL on the right.

![image](https://user-images.githubusercontent.com/65211592/95833800-bb9b1a80-0d6e-11eb-94ea-17863edb5adb.png)
Word wrap 2 lines vs 3 lines

![image](https://user-images.githubusercontent.com/65211592/95834981-3e70a500-0d70-11eb-89ed-a47dab0cffad.png)
After typing and deleting command due to typo, the previous text remains on screen (cp_). Command still runs fine.

**Comment by jdebp** [comment]
Note that line editing libraries, like the GNU Readline that is linked into the Bourne Again shell, introduce complexities to what you are testing, as they attempt to redraw the edited line and sometimes the prompt when a terminal size change is signalled.  Also note that [it is possible to banjanx the Bourne Again shell's idea of what has been printed](https://unix.stackexchange.com/a/317743/5132).

I suggest:
* reproducing this without _any_ control sequences _at all_ in your `PS1`, neither colour changes nor stuff to set the window title, _only_ a long directory name;
* reproducing this with the Korn, Z, or even Almquist shells, all of which have _different_ line editors and thus will demonstrate how much of this is peculiar to GNU Readline; and
* showing what happens when the prompt _is not_ the one for the current command line that is being input, i.e. what happens to a prompt that _is not_ actively rewritten by your shell on size changes.

**Comment by tomyummmm** [comment]
> 
> 
> Note that line editing libraries, like the GNU Readline that is linked into the Bourne Again shell, introduce complexities to what you are testing, as they attempt to redraw the edited line and sometimes the prompt when a terminal size change is signalled. Also note that [it is possible to banjanx the Bourne Again shell's idea of what has been printed](https://unix.stackexchange.com/a/317743/5132).
> 
> I suggest:
> 
>     * reproducing this without _any_ control sequences _at all_ in your `PS1`, neither colour changes nor stuff to set the window title, _only_ a long directory name;
> 
>     * reproducing this with the Korn, Z, or even Almquist shells, all of which have _different_ line editors and thus will demonstrate how much of this is peculiar to GNU Readline; and
> 
>     * showing what happens when the prompt _is not_ the one for the current command line that is being input, i.e. what happens to a prompt that _is not_ actively rewritten by your shell on size changes.

Sorry but I am not an advanced user of linux nor Terminal, so I have no clue what you are talking about at all. Just came across this issue and thought to report it.

**Comment by zadjii-msft** [comment]
For the record, this is actually already tracked over in #3088, or at least that's the issue I've been duping these issues to.

Thanks!

/dup #3088
