### ISSUE TITLE
Daily or Weekly Preview Releases?

### ISSUE THREAD

**Issue by axcadsd** [microsoft/terminal#7925]
Hello,
  
I use Terminal Preview, however its release schedule is too slow for a preview IMO. 
  
Can you please consider releasing previews in a daily (like firefox fenix on android) or weekly schedule?
  
Or, maybe add another Terminal Nightly that has faster releases..

**Comment by zadjii-msft** [comment]
I'm not sure what the benefit of a faster release cadence would be for the Terminal, to be honest. We're not moving _that much_ code on a day-to-day basis that would make a nightly build valuable IMO. I think the team's preference here is that a longer release cadence (monthly instead of weekly) allows for us a little more wiggle room in getting bugs sorted out and features polished before pushing them to the general public. If we were to release weekly, we'd inevitably have to deal with the community reporting known issues that we're planning on fixing, lowering overall satisfaction with the app. For a team of our size, it's just not that feasible IMO.

**Comment by axcadsd** [comment]
Well, my thinking was that the terminal is pretty stable, but has plenty of big and small feature requests, which get implemented every now and then. Also, the major bugs with the terminal are already known and reported. So, a faster release schedule would allow people to use these newly implemented features without waiting a month.
In any case, you are the maintainers of the project, so you should decide whether this is worth it or is it more trouble.

**Comment by DHowett** [comment]
/dup #774

I'm not averse to this, we just haven't had engineering time to stand it up and evaluate the cost of throwing it in a storage bucket somewhere :smile:
