### ISSUE TITLE
Menu shade changed after latest W10 update

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/terminal#7933]
After the 20-10-15 W10 update, something changed in the menu. It was previously a solid color, now is an awful shaded color.

![image](https://user-images.githubusercontent.com/1824187/96144079-c5895e80-0ed1-11eb-902e-159507aaecfe.png)

**Comment by alannt777** [comment]
You mean version 20H2?

**Comment by mwpowellhtx** [comment]
Nope.

![image](https://user-images.githubusercontent.com/1824187/96152067-1d2bc800-0eda-11eb-976a-f43848a6eaae.png)

**Comment by alannt777** [comment]
Ok. An internal team member will have to deal with this.

**Comment by zadjii-msft** [comment]
Huh, you're the second person to report this recently, though we're really not sure what's causing it. The thread we're using to track this is over at /dup #7532. From my experience with this bug, it went away after a reboot, and hasn't come back since, so it's terribly difficult to investigate. You might also be able to mitigate this by rebooting.

**Comment by alannt777** [comment]
I thought that I was the master of finding duplicate issues. 😭

**Comment by mwpowellhtx** [comment]
@zadjii-msft I will try to "mitigate" when I reboot. But to be honest, why is it occurring in the first place?

**Comment by zadjii-msft** [comment]
@mwpowellhtx Honestly, I've got no idea. I'm thinking it's an OS bug where `ThemeShadow`s get composited in the wrong z-order. In this case, the shadow from the `MenuFlyout` is appearing _above_ the `MenuFlyout`. From what I recall, it was affecting _all_ shadows cast by `MenuFlyout`s in apps across the OS, including ones in the Xaml Controls Gallery. I wasn't ever able to drive it to a root cause with the composition team, and since it went away for me, I assumed it was just a transient bug that popped up in the middle of a OS release cycle. Apparently, the bug wasn't just transient, and made its way out to users 😢
