### ISSUE TITLE
Add GH Action: Cache

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#7964]
# Description of the new feature/enhancement

Use GH Action Cache to speed up builds by caching the Nuget dependencies. 
# Proposed technical implementation details (optional)
Add a yaml config for testing this. https://github.com/actions/cache/blob/main/examples.md#c---nuget was the guidance I received to add it for this project.

**Comment by zadjii-msft** [comment]
Sure, though I doubt this will really result in a noticeable build time improvement, since like 45 seconds is spent restoring packages, and 30 minutes is spent building the code and running the tests

**Comment by WSLUser** [comment]
Right now I'm trying to figure out how to make the linter happy. It doesn't like the fact the Action doesn't end with a colon and if I do use a colon, it wants me to specify a parameter. But if I do that, the whole thing errors out. Going to need to add a linter file for yaml like you did for markdown once I figure out how to make it ignore the colon if this ends up being added.

So it should download the deps to the repo wherever we tell it. The test will be when I submit the PR as I don't have Azure Pipeline setup for my fork. If build speeds don't go down by much we can ignore it.

**Comment by DHowett** [comment]
Thanks for the suggestion! We evaluated build caching[1] and found it to not amount to a reasonable time savings. Turns out that _downloading and extracting the cache archive_ takes just as long on our build agents as _downloading and extracting the original packages_. This is no surprise: they're just static files.

If we were caching the output of some slow process (`npm` comes to mind) or something that is compiled, it would be more worth our while.

Right now, it's not.

[1] _Additionally_: Using a github caching action in our _azure devops pipeline_ will almost certainly help nothing. What we tested was actual caching in the azure devops pipeline.
