### ISSUE TITLE
0xc0000022 error was occured while opening wt.exe after v1.2.2381.0

### ISSUE THREAD

**Issue by EddieIvan01** [microsoft/terminal#7974]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version: After Windows Terminal v1.2.2381.0
```

# Steps to reproduce

Start wt.exe from Run(Win+R)

# Expected behavior

Windows Terminal runs

# Actual behavior

0xc0000022 error was occured, it's similar to #7081 

# What's more

## 1

I have tested all the versions in release tab, versions after  `v1.2.2381.0` couldn't be started from `Win+R` properly:

+ Windows Terminal v1.2.2381.0
+ Windows Terminal Preview v1.3.2382.0
+ Windows Terminal v1.3.2651.0
+ Windows Terminal Preview v1.4.2652.0

Versions before `Preview v1.2.2234.0` works properly

## 2

Start wt.exe from `C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.4.2652.0_x64__8wekyb3d8bbwe\wt.exe`, 0xc0000022 error was occured

Start wt.exe from `C:\Users\USER\AppData\Local\Microsoft\WindowsApps\wt.exe`, it's ok

Observe `C:\Users\USER\AppData\Local\Microsoft\WindowsApps\wt.exe` via WindowsMonitor, it loads `C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.4.2652.0_x64__8wekyb3d8bbwe\wt.exe`

**Comment by DHowett** [comment]
You are not supposed to be running `wt` directly from the `Program Files` location. If that location is visible to you, and additionally on your `PATH`, you will want to reset the permissions on the `WindowsApps` directory, as they have assuredly changed since you installed Windows.

**Comment by EddieIvan01** [comment]
Well, how could I reset the permissions on the `Program Files\WindowsApps` directory? I haven't change its permissions manually, and the error was occured after a Windows update

**Comment by nascar3000** [comment]
Got same issue with Start\Run\wt.exe returns error; Application popup: wt.exe - Application Error : The application was unable to start correctly (0xc0000022). Click OK to close the application.

took Procmon and it shows ;
Process : Wt.exe
Class: File System
Operation: CreateFile
Result: ACCESS DENIED
Path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\vcruntime140.dll

Seems NTFS permission are weird for vcruntime140.dll because there is conditional access defined for this file. Don't know if this intentional or accident.

**Comment by blakepell** [comment]
I'm having the same issue as of the last windows update.  However, I did change permissions on those folders a month ago in order to delete almost 20 gigs of Candy Crush and whatever Disney apps Windows keeps downloading (I was running out of space on my laptop and I couldn't find anyway to delete those apps through the Windows Store as I've never actually installed them, but I digress).

I believe the issue is because the Run dialog is finding "wt" in the path and trying to execute that executable (which is the same behavior UWP apps present when you find them and explorer and try to run them).  Why it only started after the last Windows Update I don't know (perhaps the path changed).

**Comment by llkdsa** [comment]
我也遇到了这个问题，不过已经解决了，步骤如下：
1. 以管理员身份运行Windows Powershell
2.运行还原权限命令 `icacls "C:\Program Files\WindowsApps" /reset /t /c /q`
![image](https://user-images.githubusercontent.com/20829574/96675664-f9ff8d80-139d-11eb-9bed-357d6c592c6a.png)
3.win+ r 运行wt已经恢复正常了

**Comment by nascar3000** [comment]
Just taking ownership and granting read/execute permission to "Users"  for single file "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\vcruntime140.dll" fixed issue for me.  No need to mess with whole WindowsApps folder permissions

**Comment by DHowett** [comment]
/dup #7188 for now -- I don't have any more good information ☹️

**Comment by dexeonify** [comment]
> Just taking ownership and granting read/execute permission to "Users" for single file "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.3.2651.0_x64__8wekyb3d8bbwe\vcruntime140.dll" fixed issue for me. No need to mess with whole WindowsApps folder permissions

Thanks! That worked.

**Comment by Whatisone** [comment]
Just create file wte.bat (or other filename.bat), write in it
`@echo off
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps\wt.exe`
write a path your file in variable the PATH and open terminal from "run" with command wte (or other filename). ( Sorry for my English, I'm just starting to learn it XD )
