### ISSUE TITLE
Command prompt goes black after awaking from sleep

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#798]
Ported out from customer feedback bug MSFT:21308307.

I haven't managed to reproduce or investigate this at all yet.

> I have 2 open command prompts (regular, and admin powershell). I locked my computer last night, and it went to sleep automatically. After waking from sleep this morning, both terminals were showing black screens instead of the text that should be on them. Scrolling the window seems to cause a repaint and fixes the issue.
> 
> This also seems to affect 3rd party terminal apps as well (e.g. Terminus).

**Comment by iKlsR** [comment]
Roughly the same, mine crashes if my PC goes to sleep, the display turns off or I lock it.

**Comment by YoungElPaso** [comment]
Similar, twice now WT has crashed on sleep - everything else resumes.  I should note, I assumed it was WSL2 that crashed, but I think it's just the sessions in WT (using Ubuntu 18.04).  The reason I suspect that is because other processes such as Docker are still up and running, which I didn't expect to see.

**Comment by zadjii-msft** [comment]
Hey so we ported this out of the OS issue tracker like, 3 years ago. It was specifically referencing the vintage console window, not the Terminal window. That being said, we haven't gotten more reports of this for the _console_ since then. There also wasn't more info in the original issue (internally) which we could really use to investigate. 

I'm inclined to close this out. Niksa can veto if he wants.
