### ISSUE TITLE
Always on Top setting does not persist

### ISSUE THREAD

**Issue by mikepianka** [microsoft/terminal#7996]
# Environment

```none
Windows build number: [Version 10.0.18363.1082]
Windows Terminal 1.3.2651.0
```

# Steps to reproduce
Open Terminal and cover it with another window.

In `settings.json` set `"alwaysOnTop": true,`. Terminal will now be on top.

Open a second Terminal window and it will not exhibit this Always On Top behavior. Other windows can be placed over it.

# Expected behavior

Terminal should always remain as the top window.

# Actual behavior

Setting `"alwaysOnTop": true` only modifies the behavior for Terminal windows that are currently open. Any new Terminal windows that are opened after that setting has been saved do not have the Always On Top behavior.

**Comment by DHowett** [comment]
Ugh. Good catch.
/cc @zadjii-msft it looks like we're doing something strange on first load?

**Comment by zadjii-msft** [comment]
I haven't got the faintest clue. Must be though, since it seems to work just fine from the action, but it is weird on first launch.

**Comment by Don-Vito** [comment]
@DHowett , @zadjii-msft  - the root cause is obvious:

- The AppHost ctor reads the value of _logic.AlwaysOnTop(), which invokes AlwaysOnTop of the root TerminalPage.
- However at this stage neither AppLogic nor TerminalPage are properly initialized (this will happen only during the AppHost::Initialze, when the AppLogic::Create will be called, invoking TerminalPage::Create). 
- There is an additional issue, that TerminalPage::Create never initializes _isAlwaysOnTop field

I am checking how this can be worked around.
