### ISSUE TITLE
Ligatures do not render under cursor column in Vim

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#800]
Ported from internal customer feedback bug MSFT:21185824

> In Vim with `cursorcolumn` enabled, any ligature that falls under the cursor column does not get rendered. The ligature is correctly rendered either when there is nothing overlapping it, when the cursor is over it, or when under the cursor line (with `cursorline` enabled).
> Screenshots attached of all four cases mentioned above.
> 
> Tested in Vim 8.1.1-744 in WSL Ubuntu 16.04.

Note, I can't find the screenshots. Needs repro again.

**Comment by DHowett-MSFT** [comment]
This was @nathpete-msft.

**Comment by nathpete-msft** [comment]
Here are screenshots of the four cases mentioned above:
1. Ligature under cursor column
![image](https://user-images.githubusercontent.com/26779897/57738479-81eb4f00-7664-11e9-9261-8a68804875b1.png)
2. Ligature under cursor line
![image](https://user-images.githubusercontent.com/26779897/57738504-a5ae9500-7664-11e9-8809-412ee9a71460.png)
3. Ligature under cursor
![image](https://user-images.githubusercontent.com/26779897/57738523-b19a5700-7664-11e9-9d55-cfde5d98ccd5.png)
4. Ligature under nothing
![image](https://user-images.githubusercontent.com/26779897/57738528-bbbc5580-7664-11e9-80b9-6ec0eb471fdd.png)

**Comment by lhecker** [comment]
The new `AtlasEngine` renderer does not have this issue. You can optionally enable it in Windows Terminal in the Rendering settings, or otherwise use Windows Terminal Preview where it's enabled by default. The upcoming version 1.18 will further improve the quality of ligature rendering and should release later this month. Let me know if you need a preview build ahead of time!
