### ISSUE TITLE
missing feature

### ISSUE THREAD

**Issue by jfish007** [microsoft/terminal#8002]
Please add a context menu like right-clicking on the Powershell. The RunAs Admin would be helpful too.

**Comment by zadjii-msft** [comment]
Thanks for the request! Since there's not all that many details in your post, I've got to try and read between the lines a little bit. I'm thinking what you're sking for is probably one of two things:
* If you want to be able to right click a folder in explorer.exe and open it up in the Terminal, that's being tracked over in /dup #1060. This is something that we added support for in #6100
* If you want to be able to right click on the terminal itself and open up a context menu, that's being tracked over in #1553 

If you're looking for something else, please let me know and we can reopen this. Thanks!
