### ISSUE TITLE
Feedback on the Tab switcher UI

### ISSUE THREAD

**Issue by ondras** [microsoft/terminal#8006]
> We'd love feedback on why the new tab switcher didn't work for you!

Enabling the tab switcher makes switching tabs slower, because they are only switched when the `Ctrl` key is depressed.

Without the tab switcher, hitting the `Tab` key (`Ctrl` being held down) switches the tab. This allows peeking through multiple tabs while holding down `Ctrl` and just hitting `Tab`. The new UI prevents this kind of navigation.

**Comment by zadjii-msft** [comment]
Good news! This is actually already fixed in the main branch, and should be heading out to users soon<sup>tm</tm>.

This was originally being tracked over in /dup #7409

This was fixed in PR #7796. 

If you subscribe to either of those threads, you'll be notified by the bot wheen an update is pushed to the store that contains that change. Thanks!

**Comment by ondras** [comment]
Great, thanks @zadjii-msft !
