### ISSUE TITLE
Change current terminal behavior for "nextTab" and "prevTab" commands

### ISSUE THREAD

**Issue by storopchanin** [microsoft/terminal#8011]
# Description of the new feature/enhancement
Currently when you press hotkeys associated with "nextTab" and "prevTab" commands the following carousel appears in Windows Terminal:
![image](https://user-images.githubusercontent.com/25746391/96904518-82ae2480-1497-11eb-847d-05c53e468b1a.png)
The carousel above doesn't provide any useful information about what is happening in your tabs. 

# Proposed technical implementation details
Please implement standard "nextTab" and "prevTab" behavior: when you press associated hotkeys and program immediately switches to next / previous tab, e.g. Google Chrome (open multiple tabs and use hotkeys Ctrl + PgUp / Ctrl + PgDn)

**Comment by DHowett** [comment]
You can disable the new tab switching experience by setting `useTabSwitcher` to `false` in your settings file.

**Comment by zadjii-msft** [comment]
Also, this is actually already fixed in the main branch, and should be heading out to users soon<sup>tm</sup>.

This was originally being tracked over in /dup #7409

This was fixed in PR #7796. 

If you subscribe to either of those threads, you'll be notified by the bot when an update is pushed to the store that contains that change. Thanks!
