### ISSUE TITLE
Some parts of One Half Light and Solarized Light color scheme are barely visible

### ISSUE THREAD

**Issue by vincentmathis** [microsoft/terminal#8033]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

In settings set `colorScheme: "One Half Light"` and enter any command with a dot or select any text:

![One Half Light](https://user-images.githubusercontent.com/33002126/97093665-6ea42780-163d-11eb-9cb9-ae323ef4981a.png)

How it looks in One Half Dark:

![One Half Dark](https://user-images.githubusercontent.com/33002126/97093666-71068180-163d-11eb-8f9d-f1d7d9cedcb2.png)

# Expected Behavior

Text and text selection should be easily visible.

# Notes

The background color is #FAFAFA while the bright text color is #FCFCFC according to colorpicker.

The same problem is visible in Solarized Light.

Setting a custom colorscheme where `brightWhite` is set to something dark turns the `.Milliseconds` part dark.

**Comment by DHowett** [comment]
This is, unfortunately, by design. The shell (in this case PowerShell as configured through `Set-PSReadlineOption`) and the color scheme have to _cooperate_, and right now PowerShell is explicitly asking for "bright white" (97m).

```
MemberColor                            : "`e[97m"
```

Unfortunately, color schemes are not immediately fungible. You'll need to do some configuring to make the color-emitting application more suitable for your needs. :smile:

**Comment by SiqingYu** [comment]
Any workaround? Text selection and find results (Ctrl+F) are barely visible in light themes.

**Comment by SiqingYu** [comment]
I found this works well for lightbackground themes:
```
"selectionBackground": "#000000"
```

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes
