### ISSUE TITLE
Open terminal from the right click context menu

### ISSUE THREAD

**Issue by mikson60** [microsoft/terminal#8093]
# Description of the new feature/enhancement

Add the ability to open the terminal by right clicking inside a folder and selecting terminal as the app to open.
This would mean the terminal is navigated to the directory in which this was opened in.

From the design perspective this would work exactly like opening git bash or powershell from the right click context menu.

It would allow quick navigation to the directory you are interested in.

**Comment by zadjii-msft** [comment]
This is something that's already supported today, however, due to an OS bug, it only works when you right click on an actual folder. You can't just right click in the "background" of a folder that's already open in explorer

![image](https://user-images.githubusercontent.com/18356694/97550101-3a16cf80-199f-11eb-90bd-559f757e9adb.png)

See also:
* [This query](https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+label%3AArea-ShellExtension) for all open bugs/tasks with the context menu item
* /dup #1060 - the original issue, and its PR #6100

**Comment by mikson60** [comment]
Thank you!
