### ISSUE TITLE
Ho to start Git Bash profile in Windows Terminal from bat file and pass in an executable command to run

### ISSUE THREAD

**Issue by johnsoncherian** [microsoft/terminal#8163]
0

I am trying to start 2 applications (client and server of a MERN stack app) in Git Bash using command-line arguments for Windows Terminal. Below given is my command:
`wt -M; new-tab -p "Git Bash" -d D:\ws\user-management\server cmd /k "npm run dev" ; split-pane -p "Git Bash" -H -d D:\ws\user-management\client cmd /k "npm run dev"`
But this starts the application in windows cmd rather than in bash as I have given `cmd /k`. If I change the above command to `wt -M; new-tab -p "Git Bash" -d D:\ws\user-management\server npm run dev` it throws this error

> [error 0x80070002 when launching `npm run dev']

How do I run my npm run dev from git bash itself rather than cmd

**Comment by DHowett** [comment]
you can use `bash -c` provided that you supply the path to git's bash.exe.

**Comment by johnson-byjus** [comment]
did u mean like this 
`wt -M; new-tab -p "Git Bash" -d D:\ws\user-management\server bash -c "npm run dev"`
Which I tried and not working. Isnt `-p "Git Bash"` suppose to open a git bash terminal without supplying the path to bash.exe

**Comment by DHowett** [comment]
Nope. `-p "Git Bash"` means "use the settings from the profile named Git Bash" -- the colors, the keyboard settings, etc. Then you specify a commandline which _overrides the commandline in `Git Bash`_ (which is on purpose).

**Comment by johnson-byjus** [comment]
Yes got it. But how do I run `npm run dev` without overriding the command line in `Git Bash` (which is BTW bash.exe).? Sorry If am getting confused here.

**Comment by zadjii-msft** [comment]
@johnson-byjus Sorry for the miscommunication - there's not a good way of doing that currently, unfortunately. You can _either_ use the `commandline` from the profile, _or_ the one provided on the commandline, but there's not a way of appending arguments to the profile's `commandline` currently. That's work that's being tracked over in #5528. Right now, you'll manually need to copy the entire "Git Bash" profile's commandline into the WT command to achieve what you want - e.g. 

```
wt -M; new-tab -p "Git Bash" -d -d D:\ws\user-management\server -- "C:\Program Files\Git\bin\bash.exe" -li -c "npm run dev"
```

(though, I of course have no idea what you're actual Git Bash commandline is, so that's a guess)
