### ISSUE TITLE
Allow tabs to always entirely fill the available space 

### ISSUE THREAD

**Issue by Gliptal** [microsoft/terminal#8181]
This already (partially) happens when maximised, although a margin is annoyingly present to the first tab's left (this margin is missing in other MS software, like Edge Chrome):

![WindowsTerminal_agYpYZgo6r](https://user-images.githubusercontent.com/3907646/98397432-a2c91080-205f-11eb-9f38-13232b18a071.png)

This is not an option in windowed mode, where the tab vertically shrinks slightly:

![WindowsTerminal_1MQyM1sDkC](https://user-images.githubusercontent.com/3907646/98397444-a52b6a80-205f-11eb-85c3-1f1e3fe5bfab.png)

Is it feasible at all?

**Comment by Don-Vito** [comment]
@Gliptal - this space above the tab exists in the windowed mode to allow resizing of the window:
![DragTop](https://user-images.githubusercontent.com/4639110/98449771-4b9a6d00-213f-11eb-8841-7a3eb7c196d8.gif)

It is eliminated in the maximized mode, since resizing is not allowed.

By the way my edge looks the same:
![image](https://user-images.githubusercontent.com/4639110/98449779-6836a500-213f-11eb-8fad-709560fe389f.png)

**Comment by DHowett** [comment]
Thanks for the requests! We're following the current Windows UI guidelines here, unfortunately, so we're not going to be changing too much. Even when maximized, it looks like Edge reserves a small number of pixels in the top left that it doesn't put tabs inside.
