### ISSUE TITLE
Invoke aliased commands from a command window.

### ISSUE THREAD

**Issue by inputfalken** [microsoft/terminal#8222]
# Description of the new feature/enhancement

A command window that could execute aliased commands. Similar to VSCode's [`Ctrl-P`](https://code.visualstudio.com/docs/editor/editingevolved#_quick-file-navigation).

This would be useful for features in the terminal that you have trouble finding comfortable bindings for or features that you might not use so often.

For instance 
```
{ "command": { "action": "splitPane", "split": "vertical", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
```

Could look something like this.

```
{ "command": { "action": "splitPane", "split": "vertical", "splitMode": "duplicate" }, "keys": "alt+shift+d", "alias": "vsplit" }
```

And `vsplit` would be listed as a possible command to execute.

**Comment by zadjii-msft** [comment]
Thanks for the request! As it turns out, this is something we added a couple releases ago, the "Command Palette"

![cmdpal-nested-command-polish](https://user-images.githubusercontent.com/18356694/98809223-cf27b880-23e2-11eb-8bbb-cf9a0c131b04.gif)


It'll auto-generate commands for each of the actions you already have bound, but you can also give them specific names. You were so close to guessing it correctly, that parameter is `name`, not `alias`.

Check out all the other command palette threads in #5400

/dup #2046

**Comment by inputfalken** [comment]
Wow, thanks for the response. Cool that it already exists 😅

I tried to find if already existed but I searched mainly for the term 'command window'. 🙈

**Comment by zadjii-msft** [comment]
Don't sweat it, GitHub issue search is pretty bad in my experience 😄
