### ISSUE TITLE
lazygit 

### ISSUE THREAD

**Issue by xaotag** [microsoft/terminal#8236]
terminal 
![image](https://user-images.githubusercontent.com/40427877/98924822-38f1b080-2510-11eb-988e-c05d7c2ee82d.png)
powershell
![image](https://user-images.githubusercontent.com/40427877/98924944-6179aa80-2510-11eb-8812-fa6d2177be47.png)

**Comment by j4james** [comment]
I think this is a known issue in lazygit, which doesn't fully support full-width characters (see https://github.com/jesseduffield/lazygit/issues/24). Apparently the problem was partially fixed in [PR 231](https://github.com/jesseduffield/lazygit/pull/231), so upgrading lazygit may help if you're using an old version.

In your PowerShell screenshot there aren't any Chinese characters visible, which is probably why you aren't seeing the issue there. It would be useful for comparison purposes if you could show the exact same diff in both Windows Terminal and PowerShell.

It would also be useful if you said which version of Windows Terminal you're using as well as the version of lazygit that you're using.

**Comment by xaotag** [comment]
> 如果你使用旧版本，升
look
![image](https://user-images.githubusercontent.com/40427877/98944420-f9d15880-252b-11eb-9f17-0a3e1d603165.png)

**Comment by zadjii-msft** [comment]
Alright so this sounds like it's an external issue with lazygit, thanks for digging up the upstream issue @j4james!

**Comment by xaotag** [comment]
in the cmd 
![image](https://user-images.githubusercontent.com/40427877/99150530-3c339a80-26d0-11eb-972f-8dcceac06e4c.png)
