### ISSUE TITLE
conhost SHIFT+INSERT

### ISSUE THREAD

**Issue by gavenkoa** [microsoft/terminal#8268]
Once upon a time was IBM CUA: https://en.wikipedia.org/wiki/IBM_Common_User_Access

And we were granted:

> The Cut command is ⇧ `Shift+Del`; Copy is `Ctrl+Ins`; Paste is ⇧ `Shift+Ins`

As with character streams (which TTY/PTY are) there is no selection and so editing capabilities (Readline-like app level abstraction is here usually), so Cut / Copy are our of the scope.

I used mouse selection even in Xterm / Mintty so no blame here.

But I enjoy SHIFT+INS very much. Popular virtual terminals send selection buffer to terminal stream input.

When I work with WSL I enabled "Use Ctrl+Shift+C/V as Copy / Paste" and again only the paste is able to work in WSL as selection meaningless without mouse (use you use `tmux` / `screen` magic).

But it is crazy key combination. Can we have Shift+Insert too for conhost.exe?

I don't even need new `wt` as a replacement for conhost + Shift+Ins for paste makes conhost equivalent to XTerm/Mintty! Though I have to admit that Shift+Ins works in Windows Terminal.

This article:

https://docs.microsoft.com/en-us/previous-versions/orphan-topics/ws.11/mt427362(v=ws.11)

describes that some capabilities are disabled if app set/doesn't set appropriate `SetConsoleMode()`. I'd like to have Shift+Ins working all the time, not only when I launch `cmd.exe`.

**Comment by gavenkoa** [comment]
So https://docs.microsoft.com/en-us/previous-versions/orphan-topics/ws.11/mt427362(v=ws.11) explains why many capabilities are lost if oyu are not in processed input mode:

> If a conflict occurs, you can typically control the behavior of the application's use of line input, processed input, and echo input modes with the SetConsoleMode() API. If you run in **processed input mode, the shortcuts below apply, but in other modes, your application must handle them**.

But still Right Mouse Click  and Ctrl+Shift+V can be enabled. I'd expect Shift+Ins be enabled too.

**Comment by zadjii-msft** [comment]
For my own notes: this is specifically a conhost discussion. Obviously, this problem is a lot easier to solve in the Windows Terminal, just add `{ "command": "paste", "keys": "shift+insert" }` to your actions/keybindings.

The <kbd>Ctrl+shift+v</kbd> setting is a little different than the other keyboard shortcuts. That one we only recently introduced, in maybe 2018? So we added it as an explicit opt-in checkbox, meaning "I want ctrl+shift+v to _always_ paste, regardless of mode". That was desirable especially because WSL was a raw input application, that couldn't be pasted into, because it was expected to be processing the keys on it's own.

If I'm reading this correctly, what you want is basically the same checkbox, but for <kbd>shift+insert</kbd>. Unfortunately, the `conhost` UX is very much in maintenance-only mode, and we're not about to make any changes to that. The best solution here would be just to use the Windows Terminal - it's keybindings are far more powerful than conhost ever was, and you can even configure it to look like the vintage console by disabling tabs in the titlebar (if you want).

**Comment by gavenkoa** [comment]
Tnx for comments! I understand that conhost is in a maintenance mode. I only asked because there might be some unclear trick to make it works.

Shift+Ins was added as default to new WinTerm (there was an issue regarding this).

The problem that I start apps:

* by Win+R and descriptive name: cmd / debian / alpine
* by Win + search for cmd / powershell + Ctrl+Shift+Enter - for elevated shell

either way conhost is used and there is no way to configure alternative terminal:

* https://github.com/microsoft/terminal/issues/492
* https://github.com/microsoft/terminal/issues/1817 - unsupported with replacement of conhost by OpenConsole

As it was stated in #492 such integration would be no earlier than 2021Q1. Let's wait a year.

**Comment by zadjii-msft** [comment]
Hey I know it's three months later, but I thought I'd add: I usually launch the terminal with <kbd>Win+R</kbd> then `wt`. If you wanted to specify the program too, you could always do `wt cmd`, `wt powershell`, etc. That works today, a little sooner than defterm 😉

**Comment by gavenkoa** [comment]
Yeah, `wt debian` works!

I learned recently that you can pass args to app when hit Win and type in the Start menu search. That means I can run `wt powershell` elevated with `Ctrl+Shift+Enter`!

> Hey I know it's three months later

I developed muscle memory for `Ctrl+Shift+C` for this 3 months )) Still the experience is not pleasant when switch between WSL shells and Cygwin mintty...

Tnx for tip!
