### ISSUE TITLE
Define default zoom level

### ISSUE THREAD

**Issue by OlivierDupre** [microsoft/terminal#8288]
# Description of the new feature/enhancement

I love very small typos/icons in my screen. Meaning pretty large zoom out for barely everything.
Some prefer larger printings on their screens.

It would be nice to be able to set this at the global (or tab?) level.

And it could be a nice turnaround for #766 and #1056  

# Proposed technical implementation details (optional)

Exactly like for `initial[Position|Rows|Cols]` add and entry in the `settings.json` file with `initialZoom` going from 100 (meaning 100%, the default) to... well, you know better than me the current limits ;)

**Comment by zadjii-msft** [comment]
So this might be a bit of a misunderstanding. The Terminal doesn't actually have a "zoom level" like browsers do. When you "zoom in" on the Terminal, what you're actually doing is _increasing the font size_. Since everything in the Terminal is just text, increasing the font size does the same thing that zooming in would.

If you want to set an `initialZoom`, then the easiest way would be to just change the `fontSize` 😄

**Comment by OlivierDupre** [comment]
That is definitively a misunderstanding! Thanks for your answer.

And have a great day.

**Comment by RodricBr** [comment]
Currently, at windows 11, there's no such option in the .json file.
Every time I start the Windows Terminal, the zoom that I applied earlier with CTRL -/+ gets reseted.

**Comment by DHowett** [comment]
> Currently, at windows 11, there's no such option in the .json file.
> Every time I start the Windows Terminal, the zoom that I applied earlier with CTRL -/+ gets reseted.

If you are relying on this feature to preserve the larger font, you may also want to just set a larger font size in Settings. :)
