### ISSUE TITLE
Multiple tabs in the same view

### ISSUE THREAD

**Issue by DoctorSclero** [microsoft/terminal#8318]
# Description of the new feature/enhancement
I'd like to have the possibility to have two terminals in the same window like visual studio code with 2 files, witch one is opened on the side. To increase productivity by visualizing multiple consoles in the same place

**Comment by zadjii-msft** [comment]
Do you mean something like [panes](https://docs.microsoft.com/en-us/windows/terminal/panes)? (see also #1000)

**Comment by DoctorSclero** [comment]
Yes, finally I found it

**Comment by DHowett** [comment]
Thanks for pointing this out!

We have surfaced it in a couple places:

* [Getting Started: open a new pane](https://docs.microsoft.com/en-us/windows/terminal/get-started#open-a-new-pane)
* Here in a tooltip ![image](https://user-images.githubusercontent.com/189190/99605186-0a665080-29bc-11eb-9d42-1bcb8a7f4cf9.png)
* Here in a tooltip ![image](https://user-images.githubusercontent.com/189190/99605215-1b16c680-29bc-11eb-8107-441d961a5c80.png)
* Here in the command palette ![image](https://user-images.githubusercontent.com/189190/99605230-236f0180-29bc-11eb-9c81-c4ece442ba27.png)


Is there another more obvious place that we could put it? :smile:

**Comment by Don-Vito** [comment]
@DHowett - I am using the panes since day one with shortcuts, and it was today that I learnt about the Alt+Click capability (probably since I never leave a full screen mode on a 3rd monitor).

However, sincerely speaking, the feature is quite hidden:
* Tooltips are hidden (who is patient enough to wait for them)
* Command palette is hidden itself

This is how my search for Tooltip Practices looks like:
![image](https://user-images.githubusercontent.com/4639110/99629340-84d8b400-2a40-11eb-9adb-065c42026120.png)

I am not sure how much screen estate can be sacrificed for this, but probably the feature is vital enough to allocate some.
For instance we could:
* Educate, e.g., add a label to the top of the menu rather than a tooltip 
* Provide more interactive ways to invoke the functionality, e.g.,

![image](https://user-images.githubusercontent.com/4639110/99632465-eb140580-2a45-11eb-9f93-606646512d90.png)

**Comment by zadjii-msft** [comment]
> add split pane to a tab context menu

That's my favorite of all these solutions IMO. I don't want to clutter the new tab menu all that much more, especially with something like #1571 being possible. But nested `Split Pane... > [Horizontal, Vertical] > [Profiles...]` entries seem like they would work well.

(we'd run abreast of #8238, but I think the idea's still good)

**Comment by Don-Vito** [comment]
@zadjii-msft - can we stop the bot from closing it? :blush:

**Comment by DoctorSclero** [comment]
@zadjii-msft I think it could be something like visual studio code that you can drag the window around the screen to split the current screen or open new windows with the already opened tabs. I don't know if this is already proposed, it can be more intuitive to the people that are approaching this stuff for the first time.

**Comment by zadjii-msft** [comment]
Okay, yea what you're looking for is already covered in #4587, #7075, and a little bit of #4998. Since this is pretty well covered by other threads, @DoctorSclero is it okay if we close this one as a duplicate?

**Comment by DoctorSclero** [comment]
@zadjii-msft Yes, of course, it's ok😀 , by the way, I think this is the best terminal you invented, a very good job. Congrats
