### ISSUE TITLE
"Open in Terminal" button in explorer right-click menu

### ISSUE THREAD

**Issue by trylaarsdam** [microsoft/terminal#8328]
# Description of the new feature/enhancement

I'd really like it if there was some sort of "Open folder in terminal" button in the right click menu 
![image](https://user-images.githubusercontent.com/50586094/99620491-3c42db80-29eb-11eb-8214-08bed69ff2c0.png)
Something like the "Open with Code" button, just opens that folder in powershell within the new Terminal. I know quite a few linux desktops and OSX have this, and I find it quite convenient on those platforms.

If possible, maybe there could be a configuration option on whether to open the terminal in a tab of powershell/cmd/WSL2 from the button in the context menu for extra customizability.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22explorer+right-click%22+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo.

* It was originally filed in #1060
* It was originally implemented in #6100
* It's got [a bunch of open bugs and feature requests](https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+label%3AArea-ShellExtension)
  - including specifically one bug where the entry won't show up if you right click on the _background_ of a directory, instead of on a folder  - see #6414

/dup #1060
