### ISSUE TITLE
Add What's New popup on launching the terminal after an update

### ISSUE THREAD

**Issue by rluvaton** [microsoft/terminal#8353]
# Description of the new feature/enhancement
The problem is that I update the terminal and most of the time I don't know what changes have been made so a popup with the release notes summary would help to see what is new.

I know that you press the _About_ button but it has 2 problems:
1. It opens the browser which I would like to see in the app without the need for internet access.
2. It redirects you to GitHub Releases which is not the release notes for **your** release

I think that the release notes popup should from the previous version to the newly updated version

# Proposed technical implementation details (optional)

## Options:
1. **Ship the program with the release notes**
You can save the release notes in the program and after an update get the release notes from that file.

2. **PostUpdate script (if there is such a thing)
Fetch from GitHub the relevant release notes**

**Comment by DHowett** [comment]
Thanks for the request! We're tracking this with /dup #5513.

Option 1 would require us to write the release notes before building and validating the final build, which makes it pretty annoying given the team's bandwidth. I'm also not keen on shipping any UI in our app that _is an embedded web browser_.

The best I'm willing to do is to redirect to a release-specific page so that I can address issue (2) :smile:
