### ISSUE TITLE
!== Ligature issue

### ISSUE THREAD

**Issue by arnabanimesh** [microsoft/terminal#8354]
# Environment

```none
Windows build number: 10.0.18363.1198
Windows Terminal version (if applicable): 1.4.3243.0

Any other software? No
```

# Steps to reproduce

Use font `FiraCode NF` and type `!==`

# Expected behavior

It should show up like this:
![image](https://user-images.githubusercontent.com/6032584/99885018-0fdfc700-2c58-11eb-801d-80c0ae009960.png)

# Actual behavior

It shows up like this:
![image](https://user-images.githubusercontent.com/6032584/99885001-f8a0d980-2c57-11eb-973f-ae7f57e3f0d7.png)

**Comment by DHowett** [comment]
You may have observed that the ligature components are printed in two different colors. This _necessarily_ breaks up the ligature!
We cannot print a single ligature (one big glyph) in multiple colors. PowerShell has requested that they be displayed as individual units by changing the color.

**Comment by arnabanimesh** [comment]
Why are they different colors even if there are no spaces in between? What does `!=` signify?

**Comment by DHowett** [comment]
`!=` is a PowerShell inequality operator (i think)! The PowerShell parsing rules are difficult to know, because sometimes it does not require a space between certain things.

The ligature works properly if you enclose it in quotes, because PowerShell will parse the entire thing as a string and format it all in the same color.
