### ISSUE TITLE
Tab close icon is too big

### ISSUE THREAD

**Issue by EOussama** [microsoft/terminal#8419]
# Environment

```none
Windows build number: 10.0.19042.630
Windows Terminal version (if applicable): 1.4.3243.0

Any other software? No
```

# Steps to reproduce

Right-click on an open tab, notice the close option

# Expected behavior

The tab close icon should be the same size as the other icons

# Actual behavior

The tab close icon is too large and distracting almost.

![image](https://user-images.githubusercontent.com/22644543/100432334-c0572c00-3099-11eb-9aa0-d0670b0fa207.png)

**Comment by zadjii-msft** [comment]
I guess it does feel a bit bigger, even if it is the same size. 

/cc @cinnamon-msft who might have some opinions on the matter

**Comment by mdtauk** [comment]
I think that icon is designed for a fontsize of 12 rather than 16

**Comment by j4james** [comment]
I think the size discrepancy may be because that _close_ icon is not typically used in this context, since it's a "chrome" icon. The _cancel_ icon might be a better choice (\xE711), although that's possibly not semantically correct.

And on a similar note, I would have expected the "Rename Tab" menu item to be using the standard _rename_ icon (\xE8AC). Was there a reason for choosing the current icon? It also looks a little out of place to me.

**Comment by j4james** [comment]
Also, as a point of comparison, have a look at the icon used on the _Exit_ menu in this example from the Windows UI docs.

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml/images/keyboard-accelerators.png

That's more in line with what I would have expected for our _Close Tab_ menu.

**Comment by zadjii-msft** [comment]
> I would have expected the "Rename Tab" menu item to be using the standard _rename_ icon (\xE8AC). Was there a reason for choosing the current icon? It also looks a little out of place to me.

oh my god there's a rename icon

Yea it should be that one 🤦‍♂️ 



>  The _cancel_ icon might be a better choice (\xE711),

Yea that does look like what we should be using. @Hegunumo wanna try that icon instead?

**Comment by cinnamon-msft** [comment]
Yeah I agree, that close icon is definitely too large. I am curious how the _cancel_ icon will look, and I agree that the _rename_ icon should be used.

**Comment by j4james** [comment]
Here's what it looks like with the _rename_ icon updated, as well as the _cancel_ icon for the close menu.

![image](https://user-images.githubusercontent.com/4181424/100789686-b5402b00-340e-11eb-9eab-d8ee767249e2.png)

And while we're discussing this code, it's also worth mentioning that many of these standard icons can be set using a `SymbolIcon` rather than a `FontIcon`. It's a little easier and more readable that way I think. For example:

```cpp
Controls::SymbolIcon renameTabSymbol;
renameTabSymbol.Symbol(Controls::Symbol::Rename);
```
instead of 

```cpp
Controls::FontIcon renameTabSymbol;
renameTabSymbol.FontFamily(Media::FontFamily{ L"Segoe MDL2 Assets" });
renameTabSymbol.Glyph(L"\xE932"); // Label
```

**Comment by gabrielconl** [comment]
The Settings context menu still uses the old icon. 
![closeicon2](https://user-images.githubusercontent.com/78622729/109518910-63fa1300-7ab3-11eb-9379-58d761410ff2.png)
Wouldn't it be better to have a single menu for all tabs?

**Comment by zadjii-msft** [comment]
@gabrielconl good catch - surprised this was only fixed for Terminal tabs and not the TabBase
