### ISSUE TITLE
Escape sequences displayed on running 'groovy -h'

### ISSUE THREAD

**Issue by ElSamhaa** [microsoft/terminal#8425]
# Environment

```none
Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal Version: 1.4.3243.0
groovy 3.0.4 windows binaries
Cygwin
```

# Steps to reproduce

run `groovy -h`

# Expected behavior

escape sequence characters should be interpreted correctly, like on Cygwin terminal:

![image](https://user-images.githubusercontent.com/34912861/100463910-447ad500-30d5-11eb-88c7-8fa8b87ae518.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/34912861/100462214-99691c00-30d2-11eb-8f46-410272e7abfe.png)

**Comment by DHowett** [comment]
Groovy, or the runtime it uses, is explicitly disabling escape character handling _when it is talking to the Windows console_.

**Comment by ElSamhaa** [comment]
@DHowett  I'm not sure if this adds anything useful, but the colors show correctly under windows console

this is in windows console; cmd

![image](https://user-images.githubusercontent.com/34912861/100486248-d1d91c00-310b-11eb-9bd1-8c9561b4b9a7.png)

**Comment by ElSamhaa** [comment]
Besides, windows console and Cygwin terminal behaving correctly suggests that this is an issue with windows terminal!

**Comment by DHowett** [comment]
How about when you run it from Cygwin _in the Windows Console_? That's closer to the scenario you're testing out in Terminal.

The whole thing of it is that behind every pane or tab in Terminal _is a copy of the Windows Console_. It's just named `OpenConsole.exe` instead of `conhost.exe`.

You've tested two scenarios out of four possible so far.

x|console host|mintty
-|-|-
launched from cmd|✔️ works fine|_untested_
launched from cygwin bash|:x: doesn't work properly| ✔️ works fine

If you launch Cygwin Bash in conhost the same way you launch it in Terminal (that is, by running "bash.exe -l -i" directly and not using the mintty shortcut), what happens?
If you launch Groovy _from CMD_ inside Terminal, what happens?

Further, what version of the Cygwin runtime are you using?
What is the content of the `$TERM` environment variable in the broken scenario?

**Comment by DHowett** [comment]
(I have a suspicion that two things are happening here. This could be backed up with some console host tracing.

1. Cygwin is disabling VT mode before spawning Groovy
   * cmd doesn't do this.
2. Groovy, or Java, or whatever took a dependency on VT mode being enabled, but they _didn't explicitly enable it_, which makes them a poor citizen on Windows.

)

**Comment by ElSamhaa** [comment]
you are right, I've tested it under in windows console under bash like you've suggested, same weird behavior.

same for when run under cmd in mintty.

x | console host | mintty
-- | -- | --
launched from cmd | ✔️ works fine | ❌ doesn't work properly
launched from cygwin bash | ❌ doesn't work properly | ✔️ works fine

**Comment by DHowett** [comment]
> Still, I'd expect Windows Terminal to behave the same way as mintty when running Cygwin bash. maybe this needs some fixing?!

unfortunately, we don't have control over that. Cygwin has a special contract with mintty because they are not using the windows console APIs. This is unfixable from our perspective: since they are (in mintty's case) not using the windows console APIs and (in conhost's case) using the Windows console APIs in a way that contravenes reality, we _cannot_ help them.

Trust me: we've tried! Terminal explicitly enables VT parsing mode for all applications by default! Groovy, or Cygwin, **still* explicitly turns it off and then expects it to work. There's nothing we can do about that.
