### ISSUE TITLE
Ignore case when sorting command palette

### ISSUE THREAD

**Issue by Don-Vito** [microsoft/terminal#8430]
# Description of the new feature/enhancement
I took me a while to understand why custom commands I add appear at the bottom.
The reason is that when sorting commands in command palette we do it not lexicographically and as a result consider a case.

IMHO the case should not matter in the palette (or at least case-insensitive sorting should be optionally available).

# Proposed technical implementation details (optional)
Upon comparing the filtered commands, try to set both command names to lower case and then compare lexicographically.

**Comment by Don-Vito** [comment]
@DHowett - actually I am not sure what to do 🤔 

As @j4james mentioned correctly [here](https://github.com/microsoft/terminal/pull/8432#issuecomment-735304273), case is just a subset of a larger problem and will not solve accented chars, etc.

And the larger problem is described here: https://github.com/microsoft/terminal/issues/6953 - we need to use correct locale for comparison.

When I last talked to @zadjii-msft we decided that probably we should not invest in it, since in any case we want to implement https://github.com/microsoft/terminal/issues/7039 - that says not to localize the palette at all..

So now I am on the crossroads of:
1. Do nothing (hate this one)
2. Work on  https://github.com/microsoft/terminal/issues/7039 (though I am not sure how to advance there - are the US_English resources packed by default in addition to other languages?)
3. Work on https://github.com/microsoft/terminal/issues/6953 - try to read the user locale and use it
4. Simply compare the strings in lowercase (will probably help only for ascii characters)

WDYT?

**Comment by j4james** [comment]
Wow. I had no idea this issue was so complicated. But my understanding from reading #7039, is that VS is not just leaving the palette in English - it's listing both the native language as well as English, and allowing the search to match both of them. In that case, it still makes sense to sort with the user's native locale I would think.

If the plan is to not show the native language at all, then I guess a hardcoded US-EN locale may be best (assuming that is always available). But worst case I'd think the user's native locale would probably still be reasonable for sorting, even on English text - at least it can't be worse than ASCII ordering and seems neater than lowercasing everything (which can produce inconsistent results).

**Comment by zadjii-msft** [comment]
For the record, this seems fine to me, we'll loop back around on the "always display the EN-US command name" thing later, let's just start with this since it's a good low-hanging fix
