### ISSUE TITLE
Animations are buggy

### ISSUE THREAD

**Issue by ivan-prodanov** [microsoft/terminal#8435]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.4.3243.0

Any other software?
```

# Steps to reproduce

![winterminalbugs](https://user-images.githubusercontent.com/6418243/100524316-ccd5a480-31bf-11eb-9055-78d2af480c0d.gif)

# Expected behavior

Chrome has good animations. Use it as a reference - the animations are fast and don't confuse the user where he/she should click after the animation completes.

# Actual behavior

TLDR 2 bugs:
Bug 1) Some weird repaint when opening a tab, can't see the other tabs. I just installed the terminal for the first time to try it out. It feels like I installed a Chrome canary build.

Bug 2) Notice after closing a tab that the tab disappears immediately, however the rest of tabs are resized **after a while**. This is confusing when trying to close multiple tabs.

**Comment by DHowett** [comment]
Thanks for the report! Unfortunately, we're just using the TabView as shipped by the Xaml controls team. I found a couple issues on their tracker that we're already subscribed to :smile: so we should get fixes for them when they're available.

* Opening animation, repaint: https://github.com/microsoft/microsoft-ui-xaml/issues/1999
* Closing snap/animation (which is partially by-design: the tab strip doesn't resize while you're hovering because it doesn't want to put an unexpected control under your cursor): https://github.com/microsoft/microsoft-ui-xaml/issues/2588

For now, I'm gonna mark this one as External.

**Comment by DHowett** [comment]
Ah, and lastly: https://github.com/microsoft/microsoft-ui-xaml/issues/1511. Forgot that one!
