### ISSUE TITLE
The title shows the path, not the name or command

### ISSUE THREAD

**Issue by whwnow** [microsoft/terminal#8448]
# Description of the new feature/enhancement
![image](https://user-images.githubusercontent.com/1713701/100694778-b0f21e80-33ca-11eb-9183-ecec9af1d8e2.png)
This makes it easy to find the tab when opening multiple tabs.

**Comment by skyline75489** [comment]
This is actually caused by npm according to https://github.com/microsoft/terminal/issues/2645#issuecomment-528874323 .

You're free to set the title to whatever you want using OSC 2. For example in WSL:

```plaintext
printf "\e]2;test\e\\"
```

Then the tab title will change accoridingly:

![image](https://user-images.githubusercontent.com/4710575/100699857-07655a00-33d7-11eb-827f-7b76ea8d7967.png)

**Comment by zadjii-msft** [comment]
Yep, the title is something that's set by the client application (in this case, `npm`). You should probably file a feature request on npm(?) or whoever is running that tool to change the title of the terminal to the running tool, not just "npm".
