### ISSUE TITLE
Phrasing Q

### ISSUE THREAD

**Issue by DamieFC** [microsoft/terminal#8506]
I know there's 1,000+ other issues that are more important, but by "the original Windows console host," do you mean cmd.exe, or something else? Again, this isn't important, it's a least priority issue.

Thank you!

**Comment by DHowett** [comment]
Sure! So, the black window that opens when you run cmd (and the blue one for Windows Powershell) or any other text-based application is actually provided by one program: “conhost”. It is the Windows CONsole HOST, and it actually makes all the console APIs work. It gives those applications a screen, and lets the user actually interact with them. 

This repository contains that application in addition to Terminal (because they share code), and the version of it you can build (“OpenConsole”) is nearly identical to the one that comes with Windows (`conhost.exe`) (but much, much more up to date!)

Hope that helps! Feel free to ask any followups 😄

**Comment by DamieFC** [comment]
Ok! Thank you 😄!

**Comment by DHowett** [comment]
(I'll close this one as an Answered Question, but don't let that stop you from bumping it if you want!)

**Comment by alannt777** [comment]
@DHowett (This is off-topic but this is the perfect place to ask another question without creating a new issue)

Recently I believe clickable links were added to con host

But when I unzipped the latest preview msix and took out OpenConsole.exe, clickable links doesn't seem to work!

**Comment by DHowett** [comment]
Clickable links were actually _not_ added to conhost; the infrastructure for supporting both OSC8 and autodetected links was, because (for OSC8) conpty needs to be able to communicate them to Terminal/VSCode/wezterm/... and (for autodetection) the code for the text buffer is shared between conhost and terminal!

**Comment by DHowett** [comment]
The “interactivity” layer in conhost was not hooked up for OSC8 links, and neither was the GDI renderer. The patten detector was not hooked up for autodetected links 😄
