### ISSUE TITLE
Inherit icon from executable specified in "commandline" for default

### ISSUE THREAD

**Issue by ddarfantasy** [microsoft/terminal#8544]
# Description of the new feature/enhancement
Use icon of the executable specified in "commandline" for default.

# Proposed technical implementation details (optional)
For example:
If I have this in my config:
![图片](https://user-images.githubusercontent.com/75518399/101810369-aca8cc80-3b53-11eb-86b5-989107bab9c1.png)
I want to see the icon of python.exe at here by default:
![图片](https://user-images.githubusercontent.com/75518399/101810482-ce09b880-3b53-11eb-8844-e5d510dedb9a.png)

(I hope it isn't a dup. :) )

**Comment by Don-Vito** [comment]
@ddarfantasy - I believe this is very similar to https://github.com/microsoft/terminal/issues/1504, but more complex (as now you need to resolve what is the relevant "python.exe" - logic that is usually down by `CreateProcess` itself).

**Comment by DHowett** [comment]
This is a good request, but it is also very difficult because as @Don-Vito points out we'd need to effectively run `CreateProcess` (or crib all of its resolution logic) to figure out _what application you're pointing at_... and even so, it could be wrong and of course expensive to do for every profile. I'd rather support it as part of /dup #1504 :smile:
