### ISSUE TITLE
Error loading Settings

### ISSUE THREAD

**Issue by montyjain20** [microsoft/terminal#8556]
Hello

I see that when I launch Terminal app I get error 
Failed to load settings
Line 114 column 4 
missing "}"or object member name

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment]
Okay, did you delete the } from the end of the file? Can you share your settings file? The error message suggests that there is something wrong on line 114.

**Comment by montyjain20** [comment]
Attaching the settings json file as zip. deleting also didnt help

[settings.zip](https://github.com/microsoft/terminal/files/5681954/settings.zip)

**Comment by Don-Vito** [comment]
@montyjain20 - what version of terminal are you using? I loaded the settings you sent to 1.4, 1.5 and latest development branch, and none of them returned an error (though a purple background in CMD was somewhat I was unprepared for).

**Comment by montyjain20** [comment]
1.5.3242.0 is the version i am using. even for non-preview released version i see same error. this started happening after latest update otherwise it was working fine. let me know anything else is needed

**Comment by Don-Vito** [comment]
Well.. that's weird. It works for me on the same version. So I guess it is somehow related to the system.
Probably the team has better idea, but it can help to know:
* What OS version are you running?
* What languages are enabled?
* Can you please attach the screenshot of the error

It could also help if you could help pinpointing the problem is by slicing the file content prior to line 114.
If possible, I would start with:
* Removing the emojis from profiles (just wondering if there can be some weird unicode issue, though I see your file has BOM prepended)
* If the issue still exists to remove profiles from the list one by one

**Comment by DHowett** [comment]
Can you also generate a trace log of the crash following the steps in this comment? https://github.com/microsoft/terminal/issues/8358#issuecomment-731670909
