### ISSUE TITLE
let vs2019 execute new terminal 

### ISSUE THREAD

**Issue by fyc132** [microsoft/terminal#8597]
![world](https://user-images.githubusercontent.com/16433238/102338514-e6a02580-3fce-11eb-9558-681b7220e62e.gif)
![image](https://user-images.githubusercontent.com/16433238/102338646-194a1e00-3fcf-11eb-8cb4-b963ea856738.png)
![image](https://user-images.githubusercontent.com/16433238/102338669-1fd89580-3fcf-11eb-9255-3f6fde9c3c63.png)

1.
find Microsoft.VisualStudio.ProjectSystem.VS.Implementation.ni.dll
use winhex .
replace "cmd.exe" to "wt.exe " 
"%s /c \"\"%s\" %s & pause\"" to "      \"\"%s\" %s        \""
![image](https://user-images.githubusercontent.com/16433238/102338736-354dbf80-3fcf-11eb-93cf-9a40f94f5501.png)

2.
find your wt.exe path
![image](https://user-images.githubusercontent.com/16433238/102338995-852c8680-3fcf-11eb-9bbc-8146c9458687.png)

use mklink
![image](https://user-images.githubusercontent.com/16433238/102339136-b4db8e80-3fcf-11eb-83e2-74bff682a59f.png)

3.
ok.ctrl+f5 build and run console

**Comment by zadjii-msft** [comment]
I'm sorry, is there a question here? 

It's definitely clever to do this hack to get VS to open in Windows Terminal instead of conhost (the vintage console).

I think as a broader solution, we're working on #492, which will allow users to set a "default terminal emulator" on windows, and have the OS automatically open new commandline applications in Windows Terminal.

There doesn't really seem like anything actionable here, so I'm gonna close this issue. Thanks!
