### ISSUE TITLE
I get a warning that makes no sense on a desktop PC

### ISSUE THREAD

**Issue by mdcclxv** [microsoft/terminal#8692]
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.4.3243.0

# Steps to reproduce
Disable the "Touch Keyboard and Handwriting Panel" service.

# Expected behavior
No warning if I don't have a touchscreen device.

# Actual behavior
Every time I start the terminal I get the following warning when running on a desktop machine, with no touchscreen:

![image](https://user-images.githubusercontent.com/33668915/103467212-6232fe00-4d55-11eb-8e1f-d2a008702c6b.png)

# A simple solution
If testing for a touchscreen device is too complicated code-wise then at least provide a setting to disable this warning for good.

**Comment by skyline75489** [comment]
Well it’s actually more complicated than you think. See #8228 and #8524. Is there a particular reason why you wanna disable the service?

**Comment by mdcclxv** [comment]
Browsed the two tickets you just indicated, and I still think that an option in the settings json file to disable the warning would do just good and no harm. People who don't have the input issue will use that option, people who have it won't.
If that InfoBar has to be dismissed manually then it's not any better than a popup. Is still annoying.

**Comment by zadjii-msft** [comment]
/cc @ebadger as an fyi

I would really recommend not just disabling random services, just because you _think_ they don't do anything relevant. It may seem like disabling it does nothing at first, but clearly, disabling this service has the unintended side-effect of breaking keyboard input to the Terminal. Plus, who knows if other functionality will be added in future OS updates that depend on services that you've disabled. 

In my opinion, this service's name might be slightly misleading. I think it should be more correctly the "Touch<strong>,</strong> Keyboard<strong>,</strong> and Handwriting Panel Service". Even if you're on a desktop PC, this service helps control keyboard input to UWP (and XAML Islands) applications. 

We've already discussed this to death in the aformentioned thread, so I'll close this one as a dupe, and we can continue the discussion in that thread. Thanks!

/dup #8228
