### ISSUE TITLE
Fetaure: allow customizing colors in 16-color palette

### ISSUE THREAD

**Issue by Leffe108** [microsoft/terminal#8714]
# Description of the new feature/enhancement
Allow user to customize the RGB code of the 16 terminal colors.

Reason: Humans have variations in color receptors - eg. how good they see different colors. 

I for example cannot see the deep blue color on black which `ls` use for directories. So I need a way to make it brighter so I can read that text. Other users may have trouble with other colors and need to make their own customization to fit their eyes.

# Proposed technical implementation details (optional)

Putty SSH client has this feature which can be used as inspiration. Basically have a visual list of the 16 colors and when you click on one of them, it is focused and you can edit the RGB code.

**Comment by zadjii-msft** [comment]
You can already do this, in both conhost and Terminal. The advice varies depending on which you're using. Are you using the Windows Terminal or the vintage console host?

**Comment by zadjii-msft** [comment]
I'm guessing from 
> the deep blue color on black which `ls` use for directories

That you're using the vintage console host. For conhost, you can use the property sheet to change the colors. To open it, right click on the titlebar and select "Properties"
![image](https://user-images.githubusercontent.com/18356694/103796088-69376600-500c-11eb-978c-c24729500767.png)

In the "colors" tab, you should see a list of the 16 colors. Clicking on the boxes will let you change the values for that color.
![image](https://user-images.githubusercontent.com/18356694/103796150-7bb19f80-500c-11eb-831c-121f5880f997.png)


(Make sure to click on black/white again before you exit the dialog - otherwise it'll change the default foreground/background color to something else).

It's not a particularly friendly dialog, but heck that code is older than me so it gets the job done. 

For a more user-friendly approach, we've got [`ColorTool`](https://github.com/microsoft/terminal/tree/main/src/tools/ColorTool), which is a commandline utility you can use to set the entire color palette at once. 
![image](https://user-images.githubusercontent.com/18356694/103796667-20cc7800-500d-11eb-8a84-40d21ef1be70.png)

**Comment by DHowett** [comment]
If you are using Windows Terminal, you can follow our customization documentation on [color schemes](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes). :smile:

**Comment by Leffe108** [comment]
Thank you for the answer. I was using WSL2 which appear to use the classic terminal when I start eg. Debian or Ubuntu from start menu. But It seems that it is possible to launch a WSL2 terminal in the modern terminal so that is one solution to the color question too.

Also thanks for instructions on how to use the old color change dialog. I was there, but it seemed to only change background color but I did apparently not dig deep enough into its possibilities.
