### ISSUE TITLE
Add option to add Windows Terminal to File Explorer

### ISSUE THREAD

**Issue by AraHaan** [microsoft/terminal#8733]
# Description of the new feature/enhancement
I would like all of the places where the user can open powershell (from shift right click on File Explorer), and on the File Tab on file explorer to be replaced or add options to those 2 places in File Explorer on Windows 10 (even on the Windows Store terminals).
Or at least a button that says ``open [insert program here] here inside Windows Terminal``. Where it does what it would normally do but make it inside of the current Windows Terminal instance (or make a new one if there is no current instance of Windows Terminal).

# Proposed technical implementation details (optional)
I would like this because currently it only lists the powershell built into windows in File Explorer, but what if I want to use tabs instead from Windows Terminal to only worry about 1 process only that holds then all of the consoles I want to be running.

**Comment by KalleOlaviNiemitalo** [comment]
> I want to use tabs instead from Windows Terminal to only worry about 1 process only

Running PowerShell in Windows Terminal needs _more_ processes than running it in the default conhost. It needs a powershell.exe or pwsh.exe process as usual, then a OpenConsole.exe process instead of conhost.exe, and an extra WindowsTerminal.exe process. <https://github.com/microsoft/terminal/pull/7240> even describes a plan to add a "content process" for each session.

**Comment by DHowett** [comment]
Also, /dup #5591. :smile:
