### ISSUE TITLE
Polish Settings UI: Color Scheme page

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#8765]
- [x] Edit a color scheme -> Hit 'apply' -> the selected color scheme resets to the first color scheme in the list (instead of the one just edited) 
- [x] The buttons turn gray on rollover covering up what color I'm looking at (I have dark mode) 
- [ ] Activate scheme renamer… then commit with enter key or dismiss with esc key and it will do the needful then go highlight the Discard Changes button at the bottom. That's a bit weird. 
- [x] Rename/add new buttons are misaligned with combobox
  - ![misaligned buttons](https://user-images.githubusercontent.com/11050425/104356356-b5791f00-54c0-11eb-948d-747b513e1ae3.png)
- [ ] **Reorganize Color Scheme Entries**
  - There should be 3 tables: non-bright colors, bright colors, and miscellaneous.
  - Currently, everything is bound to one color table. It would be nice to find a way to fix that.
- [ ] **Redesign color buttons**
  - remove text for each color button (to prevent cropping when text is localized)
  - instead, add a tooltip (and automation property) that includes the label
- [ ] "add new" button may be cropped when localized (needs verification after #8777)

**Comment by zadjii-msft** [comment]
#### What have we learned? (Jan 13)

* When you navigate to a new item in the NavigationView, _we ctor a new version of that `Page`_. That explains why adding the schemes to the list each time just worked - each navigation is starting fresh.
* Same deal happens when we save the settings. We end up re-navigating, which causes the page to get reconstructed, which makes it impossible to store state _in the page_ across navigations. 

Let's try sticking that state in `ColorSchemesPageNavigationState`, and _not_ `make` a new one every time we Navigate. If the MainPage just hangs onto a single copy of `ColorSchemesPageNavigationState`, then we can stick some data in there to be able to reconstruct the state. I'm assuming that's what it's for.
