### ISSUE TITLE
[Settings] Polish UI and adhere to design guidelines

### ISSUE THREAD

**Issue by niels9001** [microsoft/terminal#8816]
Let me start off to say that I love the work being done with the Settings UI :)!

There are however some issues with the way pages are laid out: margins and font-sizes are sometimes off, and are not inline with design guidelines: e.g. https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/forms. This results in a UI that looks a lot like the native Windows Settings app, but just slightly... off :).

We had the same issue with PowerToys, but put in some effort to clean up the styles and adhere to the same paddings, font sizes and other UI elements.

The ask basically is: can we put in (minimal) effort to tweak the XAML it looks truly like a native Windows Settings page :)?

I'd be happy to pick this up!

**Comment by zadjii-msft** [comment]
@carlos-zamora & @cinnamon-msft thoughts?

**Comment by mdtauk** [comment]
I think it may be worth looking towards the Win 10X Settings app, rather than the older design of the Win 10 Settings app.

Mostly changes in font sizes, and control shapes/styles.

![image](https://user-images.githubusercontent.com/7389110/105056458-20e86100-5a6c-11eb-8bb4-5fd82c2a5075.png)
![image](https://user-images.githubusercontent.com/7389110/105056483-2776d880-5a6c-11eb-91ba-41ec652a2cde.png)
