### ISSUE TITLE
ENABLE_VIRTUAL_TERMINAL_PROCESSING skips null characters

### ISSUE THREAD

**Issue by alabuzhev** [microsoft/terminal#8866]
# Environment

```none
Windows build number: 10.0.19041.746
Windows Terminal version (if applicable): No

Any other software? No
```

# Steps to reproduce
Historically null characters in console output have been replaced with spaces by the host.
Now, when `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is set, these characters are completely removed from the output instead.
It breaks screen output logic if the application relies on the previous behavior.

Compile and run the following code:
```C++
#include <windows.h>

int main()
{
	const wchar_t Str[] = L"ABC\0XYZ\n";

	const auto Out = GetStdHandle(STD_OUTPUT_HANDLE);

	const auto print = [&]
	{
		DWORD n;
		WriteConsole(Out, Str, ARRAYSIZE(Str) - 1, &n, {});
	};

	print();

	DWORD Mode;
	GetConsoleMode(Out, &Mode);
	SetConsoleMode(Out, Mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);

	print();
}
```
# Expected behavior

```
ABC XYZ
ABC XYZ
```

# Actual behavior

```
ABC XYZ
ABCXYZ
```

**Comment by skyline75489** [comment]
Related: #6265 , #8680

**Comment by zadjii-msft** [comment]
Yea this is totally by design. `ENABLE_VIRTUAL_TERMINAL_PROCESSING` changes a whole bunch of other things about the way the console behaves too, this is just one part of it. If you want the console to act like a terminal, then you'll need to output text like you're connected to a terminal 😉 

There's also #1825, #3015, #4171 all relevant in this space.
