### ISSUE TITLE
Gradle commands in git bash sometimes output control characters

### ISSUE THREAD

**Issue by sharpau** [microsoft/terminal#8908]
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.21292.1010]
Windows Terminal version (if applicable): 1.4.3243.0

Any other software? git bash
```

# Steps to reproduce

Run a command that changes text in place, such as a gradle build.

# Expected behavior

Text changes in place: progress bars fill, percentages go up, etc...previous output is replaced with new output. This is what a plain git bash terminal does for me.

# Actual behavior

Certain invocations of Gradle (not all, and I haven't figured out the pattern yet) will print out control characters and lose colors and replacing. For instance, I'll see something like this at the end of a gradle build:
```←[32;1mBUILD SUCCESSFUL←[0;39m in 18s
33 actionable tasks: 1 executed, 32 up-to-date
←[0K
←[0K
←[0K
←[0K
←[0K
←[0K
←[0K
←[0K
←[8A←[1m<←[0;1m-------------> 0% WAITING←[m←[26D←[1B> IDLE←[6D←[1B> IDLE←[6D←[1B> IDLE←[6D←[1B> IDLE←[6D←[1B> IDLE←[6D←[1B> IDLE←[6D←[1B> IDLE←[6D←[1B←[8A←[2K←[1B←[2K←[1B←[2K←[1B←[2K←[1B←[2K←[1B←[2K←[1B←[2K←[1B←[2K←[7A
```

This is frustrating because I recently switched from ConEmu+git bash to Windows Terminal+git bash, and in every other respect it's better. But half my Gradle commands output as an unreadable mess.

The problem does not reproduce using cmd instead of git bash.

**Comment by DHowett** [comment]
So, unfortunately, this is another instance of "client application is not using `ENABLE_VIRTUAL_TERMINAL_PROCESSING`". The terminal goes to _great_ lengths to make sure that it's always enabled, but Gradle or the Java runtime or msys/cygwin is **explicitly** disabling it. There's nothing we can do when the application requests that it VT sequence processing be disabled (because it might be doing so for compatibility reasons.)

/dup https://github.com/gradle/gradle/issues/13279
