### ISSUE TITLE
A very long title causes only half of the progress ring to be visible

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#8910]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 19042
Windows Terminal version (if applicable): 1.6 preview

Any other software?
```

# Steps to reproduce

I was trying the `bcz.cmd` and found only half of the progress ring is shown.

Here's my profile:

```json
            {
                "name" : "Developer Command Prompt for VS 2019",
                "commandline" : "cmd.exe /k \"C:/\"Program Files (x86)\"/\"Microsoft Visual Studio\"/2019/Enterprise/Common7/Tools/VsDevCmd.bat\"",
                "startingDirectory" : "%USERPROFILE%",
                "colorScheme": "Chalk"
            }
```

# Expected behavior

The ring. The whole ring. The HALO.

# Actual behavior

![image](https://user-images.githubusercontent.com/4710575/105975152-9803a200-60c9-11eb-97d2-9e08b534aa84.png)

<hr>

I'm only seeing this in the VS cmd profile. All other profiles work fine:

![image](https://user-images.githubusercontent.com/4710575/105976002-9ab2c700-60ca-11eb-9846-e330db7dd872.png)

**Comment by zadjii-msft** [comment]
Okay, I'm testing this out. It doesn't look like it's the fallback icon that causes this. I think it's the title length. If you set the tab title to something really long, like `Developer Command Prompt A really really really long title`, then it seems to push the spinner halfway into oblivion.

That's real bizarre, because there's definitely space for it, but the tab view is still cropping it. Weird.
