### ISSUE TITLE
De-underline hyperlink on hover-out, even if not focused

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/terminal#8925]
Testing WT Preview 1.6.10272.0.

Ok, now that we got the underline hyperlink on hover, even when not focused (#8475, #8615)... can we have them always de-underline on mouseout as well? You know, for consistency? 😉

Right now, the underline gets removed only when another hyperlink gets underlined, not when the mouse moves away from it.

**Comment by zadjii-msft** [comment]
YUP we should do that, good catch.

**Comment by Don-Vito** [comment]
@zadjii-msft - I am wondering why we chose to implement #8475 rather than #6459. Won't it make the behavior more consistent and prevent issues like this one?

**Comment by DHowett** [comment]
@don-vito curious though -- would implementing focus-follows-mouse fix the issue where hyperlinks get underlined and never get un-underlined _when the whole window is out of focus?_

FFM is very controversial. I don't think it's the solution to any problems except the problem some users perceive where we do not have FFM. :smile:

**Comment by Don-Vito** [comment]
> @don-vito curious though -- would implementing focus-follows-mouse fix the issue where hyperlinks get underlined and never get un-underlined _when the whole window is out of focus?_
> 
> FFM is very controversial. I don't think it's the solution to any problems except the problem some users perceive where we do not have FFM. :smile:

@DHowett - what you mention regarding the entire window losing focus is another aspect that requires a fix, but it is not related directly to this report. The problem here is due to a gap in the implementation of mouse hover over unfocused pane. And the fix here will be different from the fix that will be required for window losing focus.

My suggestion for FFM is replacing the code that introduced this gap. I was not aware though that FFM is so controversial :blush:

**Comment by Don-Vito** [comment]
I am handing this separately from FFM.
