### ISSUE TITLE
Experimental HLSL shaders - cbuffer Time not bound

### ISSUE THREAD

**Issue by softmonkey** [microsoft/terminal#8935]
# Environment
Platform | ServicePack | Version | VersionString
--- | --- | --- | ---
 Win32NT |  |10.0.19042.0 | Microsoft Windows NT 10.0.19042.0

# Steps to reproduce

1. Write a simple HLSL shader that uses Time such as:  
```
  // The original retro pixel shader
  Texture2D shaderTexture;
  SamplerState samplerState;
  
  cbuffer PixelShaderSettings {
    float  Time;
    float  Scale;
    float2 Resolution;
    float4 Background;
  };
  
  float4 main(float4 pos : SV_POSITION, float2 tex : TEXCOORD) : SV_TARGET
  {
    // Read the color value at the current texture coordinate (tex)
    //  float4 is tuple of 4 floats, rgba
    float4 color = shaderTexture.Sample(samplerState, tex);
    
    // Vertical scroll
    tex.y+= Time;
    color.rg = tex * 0.5f;
    
    // Return the final color
    return color;
  }
```
2, Add it to your profile config

# Expected behavior
I am expecting the example shader to scroll vertically. Time is useful for a number of effects.

# Actual behavior
Shader is compiling fine, so suspect an error in the binding.
See TODO terminal/blob/main/src/renderer/dx/DxRenderer.cpp, DxEngine::_ComputePixelShaderSettings()

**Comment by zadjii-msft** [comment]
Oh yea, yikes. That TODO definitely _should_ be tracked somewhere, thanks! We probably should have made sure to do that before we shipped the shader out, clearly I forgot 😅

**Comment by Nacimota** [comment]
This feature got me excited enough to actually learn HLSL and have a go at doing some fancy shader effects for the terminal but I was quite disappointed to see the time input wasn't working because it's essential to basically any passive animated effect.

C++ is almost greek to me, but I had a go at fixing it myself and it seems like passing the time in `_ComputePixelShaderSettings()` where that TODO is doesn't entirely solve the problem because the screen only seems to update when the text changes:

https://user-images.githubusercontent.com/651955/106405266-5c7a2680-6481-11eb-821e-8c4ec19b452c.mp4

I can't figure out if it's that `_ComputePixelShaderSettings()` needs to be called somewhere else, or if the renderer just doesn't bother redrawing the frame when no updates have been made, or something else entirely, but oh boy is it pretty! I can't wait to see this fixed (by someone that knows what they're doing).

**Comment by zadjii-msft** [comment]
Let me just start with a WOW 👀! When we first added these shaders, this is exactly the kind of cool thing I was expecting people to be able to do with them. That looks awesome!

You're right in finding that our renderer only paints a frame when the contents of the window have changed. So yea, right now you need to be constantly emitting text or blinking the cursor or whatever to have the effect be "smooth". This is something we did a long time ago to try and save CPU cycles. Obviously though, that optimization doesn't make any sense if we want to let people make smooth graphical effects. 

If you make the PR to bind `Time` to something, then we can on our side hook up the `DxEngine` to the `RenderThread` to tell it to manually paint a frame every 1/60th of a second (when the pixel shader effects are enabled). Sound like a plan?

/cc @miniksa (our renderer expert)

**Comment by Nacimota** [comment]
That sounds good to me. As I said, I'm not really a C++ guy so I'm not sure I'm getting/setting the time in the most sensible way, but if you folks are willing to entertain my lack of experience with some constructive review I'll happily take a stab at it.

**Comment by zadjii-msft** [comment]
I'm always happy to help! I'm not sure anyone can confidently call themselves a C++ guy, no matter how much experience they have with the language 😜

**Comment by miniksa** [comment]
> If you make the PR to bind `Time` to something, then we can on our side hook up the `DxEngine` to the `RenderThread` to tell it to manually paint a frame every 1/60th of a second (when the pixel shader effects are enabled). Sound like a plan?
> 
> /cc @miniksa (our renderer expert)

Yeah no problem. I can do that after the `Time` is piped through... force the ticks to happen anyway when shaders are enabled.

Do note that this will only make the performance characteristics of this even heavier (more CPU, more battery/power, etc.) but I think we're well past caring about that point when using shaders anyway especially given that shaders enabled right now already forces full-screen repaint instead of differential drawing.
