### ISSUE TITLE
Copying text is tricky

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#894]
Copying text went tricky, what drag is to copy, Even just clicking on the terminal cmd, powershell, ..... etc copies the text whatever it is clicked (even it is blank)
So, coping the text on the terminal makes somewhat tricky on clipboard.. (When I get some sort of code and want to paste on terminal, it gets very tricky for users like me.)

What I think it is needed is like cmd and powershell before, right click to copy the text.

**Comment by natephysics** [comment]
It isn't even behaving like a traditional terminal in this regard. If you click without selecting anything in the terminal it tries to copy text. If you want to paste anything into the terminal you have to be very careful not to click inside the terminal window before attempting to paste otherwise you overwrite your clipboard. Can't tell you how many times I've lost my clipboard because I've selected the terminal window by clicking instead of tabbing.

**Comment by zadjii-msft** [comment]
Frankly this just kinda sounds like a different wording of #670 which will be fixed by #856.
