### ISSUE TITLE
Crash on tab context menu after a few mouse right-clicks

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/terminal#8944]
# Environment

```none
PS C:\Users\Ich> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal Preview
Version: 1.6.10272.0
```

# Steps to reproduce

1. Start terminal
2. Mouse right-click on a tab
3. A few mouse right-clicks on a different context menu entries

# Expected behavior

Don't crash (silent)

# Actual behavior

unlimited of this:
![2021-01-29 13_58_02-Solution1 (Debugging) - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/17874713/106278354-e3898d80-623a-11eb-8751-a751f8af1e93.png)

When you tell me how can I get a better debug about this crash, I want to given you a better error report

**Comment by zadjii-msft** [comment]
Shit. This is the context menu crash from over in #8238. @DHowett we held the nested menu back from 1.5 because of this crash, but it looks like we didn't hold it back from 1.6 too. This is the second report since we shipped - I bet we're gonna see a few more of these too. 

I'm gonna re-purpose this to make sure we push a hotfix to revert than ASAP.

**Comment by DHowett** [comment]
I'm only holding this back from 1.5 -- it's "stable" afterall.

**Comment by DHowett** [comment]
Ugh, okay, I'll cherry-pick it to 1.6.
