### ISSUE TITLE
Settings.json is not re-generated *when deleted* on 1.6 preview

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#8955]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 19041
Windows Terminal version (if applicable): 1.6 Preview

Any other software?
```

# Steps to reproduce

1. Have Windows Terminal open
2. Delete the existing settings.json.
3. Open a new instance of Windows Terminal.
4. Open Settings from the drop-down. It will offer to create one but will be blanked out.

# Expected behavior

I expect all the default settings to be regenerated.

# Actual behavior

~While 1.5 correctly regenerates the settings.json, 1.6 does not.~ Verified by @carlos-zamora that it occurs on 1.5 too

I suspect it has something to do with the way it's tied to the Settings UI.

**Comment by carlos-zamora** [comment]
Ok, did some digging. A few things:
- To repro, there was a step missing (updated the description). WT has to be open _before_ you delete the existing settings.json. If WT is not open, WT generates a new settings.json on launch.
- Verified that this occurs on v1.5.3142.0 too.

The root cause of this is in TerminalPage.cpp's `_LaunchSettings`:
https://github.com/microsoft/terminal/blob/40ebe5ab546dbfae65a57505954b062edbcd06f6/src/cascadia/TerminalApp/TerminalPage.cpp#L2148-L2154

When we attempt to open the settings.json, we just call a `ShellExecute` on the filepath. Apparently, if the file doesn't exist, notepad opens up and gives you this prompt:
![notepad prompt](https://user-images.githubusercontent.com/11050425/106537505-50a55900-64af-11eb-90c3-e414e935d4fc.png)

As for how to get around this, I guess we could check if the file is here first, then populate it there and then?

@DHowett @zadjii-msft Thoughts? Should this even be scheduled for v1.7 since it's always been around? The workaround is pretty straight-forward: re-launch WT.

**Comment by zadjii-msft** [comment]
Yea I'm cool with this being a 1.7 fix.

**Comment by WSLUser** [comment]
Sorry for missing a step. I guess 1.5 preview and 1.5 stable are different enough as I was not able to reproduce on 1.5 preview.

**Comment by DHowett** [comment]
If you don't want the settings file deleted, don't delete it. I dunno. We could add the deletion event to our filesystem change notifier, but _why_?

**Comment by WSLUser** [comment]
It should continue to be regenerated if deleted. In my case, I had deleted it in hopes of getting a properly formatted settings.json back that hasn't been touched by the Settings UI. This obviously didn't work. Anytime someone wants/needs to start from scratch with it again should be able to do so easily.
