### ISSUE TITLE
SettingsUI removes "disabledProfileSources"

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#9032]
Using the SettingsUI removes my "disabledProfileSources" customization.  I wish it didn't do that.  Perhaps it clobbers other customizations too.

**Comment by zadjii-msft** [comment]
Huh. That's no good.

**Comment by WSLUser** [comment]
> Perhaps it clobbers other customizations too

It absolutely does. It's all part of https://github.com/microsoft/terminal/issues/8991. It might be easier to prevent removals than to have parity though.

**Comment by zadjii-msft** [comment]
Woah now - removes a setting != reformats the file. In general, the file will be reformatted, yes. It should NOT, in any circumstances, be removing settings that are otherwise set. Unless the user modifies a setting, it should remain untouched (or in the case of floats, equivalent).

If the setting is getting lost, then there's a good chance that it's being bound incorrectly. That's my theory at least.

**Comment by vefatica** [comment]
I read #8991 when it was new but didn't appreciate what @WSLUser was saying until this issue arose.  The new format is shocking at first but completely rational and consistent across the whole file.  I'll have no problem getting used to it.  I miss the comments that gave hints about the use of the file's major sections; "keybindings" is the only section that still has such/any comments.  Hopefully, someday soon, I won't have to look at the file at all.
