### ISSUE TITLE
Great tool! The tool should able to save workspace when it is closed.

### ISSUE THREAD

**Issue by dinhanhvo** [microsoft/terminal#9046]
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by skyline75489** [comment]
See #766

**Comment by zadjii-msft** [comment]
Yea, this _sounds_ like a dupe of #766, though it's impossible to say for sure with a blank issue like this. 

/dup #766

**Comment by Poopooracoocoo** [comment]
By workspace, I think you mean virtual desktop. Funnily enough, Microsoft has a service called Virtual Desktop. I don't agree that it should only open on one virtual desktop. It should open on the desktop it was opened from. Microsoft Office used to have a _bug_ where it would switch desktops because it would open the last instance of an app. It _still_ opens the last instance of an app, but doesn't switch desktops anymore.
