### ISSUE TITLE
ui:add a title in "focus" mode to display the current shell title.

### ISSUE THREAD

**Issue by oqoehbeaopgc** [microsoft/terminal#9083]
ui:add a title in "focus" mode to display the current shell title.

yes:
![image](https://user-images.githubusercontent.com/73050941/107351650-d192cf00-6b05-11eb-8041-521adffccafb.png)

no: 
![image](https://user-images.githubusercontent.com/73050941/107351826-0d2d9900-6b06-11eb-9382-4cd4cddc8ded.png)

**Comment by zadjii-msft** [comment]
FYI you don't need to file a new issue. You could have just updated the existing issue (#9067) with more details.

It looks to me like what you want is the [`"showTabsInTitlebar": false`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/appearance#hide-the-title-bar) setting, combined with `"alwaysShowTabs": false`. This will just use a standard window titlebar when there's only one tab. It's not exactly the same as focus mode, but it's the most minimal UI you'll get with a titlebar present for now.

Otherwise, I'd follow issues #4717 & #4998. They're tracking adding titlebars to _panes_ themselves. Theoretically, those titlebars would be visible even in focus mode.

Thanks!

/dup #9067 
/dup #4717
