### ISSUE TITLE
The terminal can't input full width Chinese characters(in win10, Windows Termial with powershell or cmd)

### ISSUE THREAD

**Issue by LingYiLing** [microsoft/terminal#9084]

**Comment by LingYiLing** [comment]
The terminal can input Chinese words, but can't input  full width Chinese characters while using powershell.exe or command prompt.exe

**Comment by zadjii-msft** [comment]
@LingYiLing you still have to give us more info than that.

* What version of Windows are you using? 
* Are you using the Windows Terminal, or the vintage console? 
* If you're using the Terminal, what version of the Terminal are you using?
* What version of PowerShell? What version of PSReadline (if enabled)?
* Which IME are you using to input characters?
* What happens when you try inputing chinese characters? A screenshot would be helpful here. Protip: you can just paste images in this textbox on GitHub and it will upload and link the image for you ☺️

**Comment by LingYiLing** [comment]
I'm using Windows Terminal, version: 1.5.10271.0  
* The versions and problem is below  
![issue_01 2021-02-12 181635](https://user-images.githubusercontent.com/50640825/107757419-7dcff200-6d60-11eb-933e-154257390371.png)
![issue_02 2021-02-12 182549](https://user-images.githubusercontent.com/50640825/107757502-9d671a80-6d60-11eb-85b8-dc3b405f4c46.png)
![version 2021-02-12 181805](https://user-images.githubusercontent.com/50640825/107757678-d1dad680-6d60-11eb-9740-85fe9556ce39.png)
* IME I using is 微软拼音
![IME01 2021-02-12 182739](https://user-images.githubusercontent.com/50640825/107757835-08185600-6d61-11eb-9c74-0581a8cec655.png)

**Comment by zadjii-msft** [comment]
Ah, gotcha. So the issue is that the full-width  characters aren't working _wile you're using `ssh`_. That sounds like an issue with `ssh.exe`, you should probably report this on their repo. Their issue tracker can be found here: https://github.com/PowerShell/Win32-OpenSSH/issues
