### ISSUE TITLE
Min/Max/Close buttons should be 32px

### ISSUE THREAD

**Issue by TyJOrtiz** [microsoft/terminal#9093]
I see the minimize, maximize and close buttons (https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalApp/MinMaxCloseControl.xaml) are 36 px in height, the standard window title bar height is 32 px. This creates an inconstancy![image](https://user-images.githubusercontent.com/25320332/107457355-c42a1480-6b06-11eb-988f-c4739d83fee7.png)

**Comment by zadjii-msft** [comment]
I mean:

![image](https://user-images.githubusercontent.com/18356694/107505070-cb324080-6b61-11eb-886f-cb32b67a33e5.png)

Once you get to customizing the content in the titlebar, it's up to each developer to do whatever they'd like. Our tabs create 36px of space at the top of the window. It's actually _weirder_ if the caption buttons were only 32 px tall, because there'd be this 4px dead space beneath them.
