### ISSUE TITLE
Settings UI: Renaming default color scheme applies to each profile instead of defaults section

### ISSUE THREAD

**Issue by mbudnek** [microsoft/terminal#9094]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.6.10272.0
```

# Steps to reproduce

1. Create a custom color scheme named 'foo'
2. In the "Base Layer" settings page, select 'foo' as the color scheme
3. Rename the color scheme 'foo' to 'bar'

# Expected behavior

The color scheme in the "Base Layer" settings should be updated to be 'bar' and changing it should affect all profiles.

# Actual behavior

The color scheme in the "Base Layer" settings changes to "Campbell" and changing it has no effect on other profiles.  Looking at the settings file you will see that each profile has had the `colorScheme` attribute added with the new name, and the `colorScheme` attribute in the `defaults` section still has the old name.

**Comment by DHowett** [comment]
@carlos-zamora

**Comment by carlos-zamora** [comment]
Oh man. I know exactly what the problem is:
https://github.com/microsoft/terminal/blob/47f4b4197d82f3e4cdb3886148a25f9ff30322c4/src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp#L875

We should also update `ProfileDefaults` (aka "base layer") in this function.

**Comment by DHowett** [comment]
Oof, you know what? I bet the loop here is **forcing** every profile to _override_ the setting, too.

https://github.com/microsoft/terminal/blob/47f4b4197d82f3e4cdb3886148a25f9ff30322c4/src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp#L879-L884

If you set BaseLayer's color scheme first, that check won't force an override ........ but that feels like "works because of circumstances", not "works because of good design"

**Comment by carlos-zamora** [comment]
Good call. We need a `HasColorSchemeName()` check inside the loop too. Make sure that we're only redirecting any explicitly set references.

**Comment by DHowett** [comment]
Thanks again for the report!
