### ISSUE TITLE
fontWeightBold setting

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#9179]
# Description of the new feature/enhancement

When https://github.com/microsoft/terminal/issues/109 gets implemented, we should also add a setting

```
"fontWeightBold": "bold",
```

# Proposed technical implementation details (optional)

The default may be `bold` but allow users to change.

**Comment by DHowett** [comment]
We're going to tackle this with /dup #1790

**Comment by DHowett** [comment]
I am resistant to adding a bunch of `fontxxxBold`, because when we have support for more font things (right now `size`, `weight`, `face`, `stylisticSets`, `variantAxes`, etc etc etc) we'll have to multiply that out by the number of styles we support (`bold`, `italic`, maybe even `underline` or `applicationStyle53` (SGRs for selecting fonts do exist ...)) and end up with a combinatorial explosion of options.

I'd rather, before we add more individual font options, come to an agreement on how we should represent a _single font with all its configuration fields_. Then we can stamp out a bunch of those, one per style.
