### ISSUE TITLE
print to windows terminal as slow as conhost, git-bash.exe 10x faster

### ISSUE THREAD

**Issue by ta946** [microsoft/terminal#9187]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable): 1.5.10411.0 & Preview 1.6.10412.0

Any other software?
git-bash (mintty 3.4.1 xterm)
```

# Steps to reproduce

    python -c "from timeit import default_timer as default_timer; thisTimer = default_timer(); list(print(i) for i in range(100000)); print('thisTimer', round(default_timer()-thisTimer,2))"

# Expected behavior

Windows terminal mentions GPU accelerated text rendering so I was expecting a significant speed performance over conhost.

# Actual behavior

running the above python script to print 100k lines takes 7s on conhost with no speed difference using windows terminal (powershell or cmd)
Running the same script with git-bash takes 0.7s but it seems to render the screen in segments as opposed to wt and conhost clearly showing each line bring printed.

Is there a setting or option to let windows terminal print to console faster even at the cost of readability as a common use case i have is executing a long running code with a large text dump per second but running it in conhost ends up slowing down my script

**Comment by zadjii-msft** [comment]
I believe we're using #3075 to track the latest iteration of "Terminal not speed enough" (previously, #1064). The Terminal is actually a bit faster than conhost, but at the end of the day, there's actually still a conhost sitting between the Terminal and whatever the client application is. So that still slows things down a bit. 

/dup #3075
