### ISSUE TITLE
on-screen lines randomly disappear after scrolling or missing from the beginning

### ISSUE THREAD

**Issue by shivtorov** [microsoft/terminal#9200]
# Environment

```none
Windows build number:

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal 
Version: 1.5.10411.0

```

# Steps to reproduce

I don't know how to reproduce bug.
Just run powershell code, switch between apps, scroll terminal window

# Expected behavior

do not lose on-screen lines 

# Actual behavior

Every day once or twice a day I see lines disappear from Windows Powershell windows.
(I don't use other shells so don't know if the bug is specific to powershell tabs)

examples:
1) sometimes one line of the output is missing from the beginning.
I usually notice it when the 1st (header) line is missing in powershell output produced by "format-table". 
If I re-run the PowerShell command, it outputs header line correctly

2) sometimes initial output of a command is fine,  but after scrolling up and down, I notice a line might disappear.
The screenshot below shows such a case - missing line in the output.
It is very clear that one line is gone here - because it was the only row in this table.
Just to clarify - the line was there on the screen earlier. It is disappeared after scrolling up and down

![line-disappeared-after-scrolling](https://user-images.githubusercontent.com/31003608/108339453-8e361000-722b-11eb-8aae-51b85a0f4b34.PNG)

**Comment by DHowett** [comment]
This happens because PowerShell's line editing library (PSReadline) manually implemented display scrolling by telling the terminal to "shift the contents of the screen up by one, deleting any lines above". This worked with the Windows Console (because of how it was implemented), but does not work properly with Terminal. They have fixed it. If you update the PSReadline module, you will not see this bug any more.
