### ISSUE TITLE
"New Console" mode gives blank screen

### ISSUE THREAD

**Issue by neobis001** [microsoft/terminal#9214]
# Environment

```none
Windows build number: 10.0.18363.1379
```

# Steps to reproduce
1. Turn on legacy mode. Re-launch cmd.
![w-legacy](https://user-images.githubusercontent.com/10540174/108446167-903fa500-7212-11eb-99be-89773a1af9f4.jpg)

2. Disable legacy mode. Re-launch cmd.
![w-new](https://user-images.githubusercontent.com/10540174/108446347-d1d05000-7212-11eb-9651-0ab30dc51b27.jpg)

# Expected behavior
Just a normal console. I think I was in "new console" mode before trying this out. Because Ctrl+C/Ctrl+V functionality was working before. I was just trying "legacy mode" because I thought it would fix this weird thing happening to MASM Assembler.

# Actual behavior
As shown in the 2nd image, I get a blank console. I found one other person who had the same problem here:

https://answers.microsoft.com/en-us/windows/forum/all/command-prompt-gives-a-blank-black-screen-unless-i/2726f725-0793-435e-976b-da061aade847

He/she said it was just some weird settings, but didn't say what. So I don't know how to fix this myself.

**Comment by DHowett** [comment]
So, this is a well known old bug that has since been fixed. 18362 introduced “Terminal” settings, which let an application have access to more colors and cursors.

Due to an oversight, turning on the “legacy console” setting corrupts the terminal colors, turning them on but setting them both to black. You end up with the foreground and background both being black.

You should be able to recover by going to the Terminal settings tab and turning off the color options and resetting the cursor to “Vintage” or “default”.

There’s an old issue in our repo for this, but I can’t find it (on my phone.)

Let me know if that works!

**Comment by neobis001** [comment]
Thanks, disabling "color options" worked. Where's the "vintage" cursor option? I can't find it in the Terminal tab. Just curious.


![cmd-terminal-tab](https://user-images.githubusercontent.com/10540174/108456063-4b246e80-7224-11eb-8ca5-655d1228d055.jpg)

**Comment by DHowett** [comment]
Whoops- bad memory. I meant the “legacy” option :)

Glad it worked!
