### ISSUE TITLE
Add configuration for tab character width

### ISSUE THREAD

**Issue by powercode** [microsoft/terminal#9219]
# Add configuration for tab char width

When looking at xml-files, or some other hierarchical text context that uses tabs, having each tab rendered as 8 spaces quickly becomes unwieldy.

When looking at source code or diffs that align code with tabs, 8 is very rarely used as the size of tabs. 

It would be nice to be able to have a configuration for how Windows Terminal renders tabs.

**Comment by skyline75489** [comment]
Don't mean to be rude, but doesn't Vim has this?

**Comment by powercode** [comment]
Most (all?) unix terminals has this with the `tabs` command.

**Comment by skyline75489** [comment]
I’m a bit confused. Are you sure “tabs” is provided by the terminal instead of shells?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Staffan Gustafsson <notifications@github.com>
发送时间: Friday, February 19, 2021 7:10:16 PM
收件人: microsoft/terminal <terminal@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [microsoft/terminal] Add configuration for tab character width (#9219)


Most (all?) unix terminals has this with the tabs command.

―

**Comment by zadjii-msft** [comment]
Yea I mean, [`tabs`](https://linux.die.net/man/1/tabs) should already work in the Terminal. It sounds like it's using escape sequences that we've supported for a while now, `TBC` and `HTS`. That just sets the tab stops to new positions. Does `tabs` (in WSL) not already work for you?

**Comment by skyline75489** [comment]
I’ve tried this in WSL and it works as expected.

This is educational. I didn’t know about the existence of “tabs” before.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Mike Griese <notifications@github.com>
发送时间: Friday, February 19, 2021 8:22:36 PM
收件人: microsoft/terminal <terminal@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [microsoft/terminal] Add configuration for tab character width (#9219)


Yea I mean, tabs<https://linux.die.net/man/1/tabs> should already work in the Terminal. It sounds like it's using escape sequences that we've supported for a while now, TBC and HTS. That just sets the tab stops to new positions. Does tabs (in WSL) not already work for you?

―

**Comment by powercode** [comment]
It works in WSL.
How can it be configured for cmd and pwsh on windows then?

**Comment by zadjii-msft** [comment]
That really depends on what application you're seeing the tabs in. Where are you seeing the tabs that you want to configure the width of? Like, which application/scenario specifically? I'm not sure that `cmd.exe` itself actually uses tabs for anything. PowerShell might - I'm not as familiar with PS.

**Comment by powercode** [comment]
I am not talking about the WT tabs for running different shells. 
I'm talking about how `\t` is rendered. 
For example,
is the output of an application containing a tab character, like:
```text
"Label:\tText"
```
rendered as (tab size: 4)
```text
Label:    Text
```
or as (tab size: 8)
```text
Label:        Text
```

Basically, how do we set the tab stops?

**Comment by powercode** [comment]
Maybe we should use the terminology `tab stops` since the use of Tab is overloaded in this context.

And `tab stops` don't necessarily need to be set at even intervals.

**Comment by zadjii-msft** [comment]
Sure okay, my point still remains. Who's displaying text that's making use of the tab stops? Like, are you just `type`-ing a file to the console/terminal? Are you using `vim.exe`? Are you like, entering a multiline command in powershell? (again, not super familiar with PS so that might not make sense). The scenario definitely matters here.

I'm not sure that there's a built-in command that will set the tabstops to different positions (like `tabs` would). You could theoretically write one, but if you called it from `cmd.exe`, `cmd` would toggle VT processing back off, resetting the stops to the vintage console positions.  They were _always_ 8 characters apart for the vintage console, so that's not really configurable for vintage apps. It's only VT-aware apps that can actually make use of changing the positions of the tab stops.

If you're the author of the thing that's emitting the text with the tab characters, then you could certainly just emit the HTS sequences yourself at startup to change the positions of the tab stops.

**Comment by powercode** [comment]
The case I ran into today was looking at diffs with git, running from pwsh.

The source code was formatted for a certain tab width, lining up source code using tabs.
With the default of `8`, it was really hard to read, as the coder had used a tab width of 4 to make the alignment.

**Comment by zadjii-msft** [comment]
Not to start a holy war, but _this is why people should use spaces_ 😄 \</holy-war>

Looks a bit like you're hitting this: https://stackoverflow.com/a/10584237 ?

I'm not sure if there's a good way of configuring the output of a `git diff` that doesn't use the pager. 

<rant>
This is one of those times where the vintage console behavior is simply unpleasant, without a good solution. I'd _love_ to not have `cmd.exe` toggle VT off after each child process, but we _really really_ can't change `cmd.exe`, and we know for a fact that we can't do specifically that. Last time we tried that ~an oil rig exploded~ I think it caused all Windows builds to by 10% longer (which is measurable in hours).
\</rant>

**Comment by vefatica** [comment]
> ... cmd would toggle VT processing back off, resetting the stops to the vintage console positions.

Wasn't that behavior changed a while back ... so that toggling VT output processing no longer resets tab stops?  Here, CMD is quite happy with tab stops at 1, 5, 9, ...

**Comment by j4james** [comment]
> The case I ran into today was looking at diffs with git, running from pwsh.

Git diff won't use the terminals tab stop settings when displaying tab characters in a file, so it would be pointless trying to change them. But you should be able to configure the tab stop width in git config. See https://stackoverflow.com/questions/10581093/setting-tabwidth-to-4-in-git-show-git-diff

**Comment by j4james** [comment]
However, if you're just outputting a file with `type`, it looks like the terminal tab stop widths are actually used. So if you really want to change them, you can do so from the cmd prompt with commands like this:

    rem Clear all existing tab stops
    echo ^[[3g

    rem Set a tab stop in column 25
    echo ^[[25G^[H

Note that `^[` is <kbd>Ctrl</kbd>+<kbd>[</kbd>.

The equivalent commands in PowerShell are:

    echo `e[3g

    echo `e[25G`eH

**Comment by zadjii-msft** [comment]
> Wasn't that behavior changed a while back ... so that toggling VT output processing no longer resets tab stops? Here, CMD is quite happy with tab stops at 1, 5, 9, ...

You know, I could be wrong about that. I'm definitely wrong about that:

![image](https://user-images.githubusercontent.com/18356694/108708829-9023fb80-74d7-11eb-9786-c143c37e5bae.png)

Y'all are just fixing bugs faster than I can keep up with 😅 

I _think_ this discussion has run it's course, so I'm gonna close this. Thanks everyone!
