### ISSUE TITLE
How can one deploy Windows Terminal from command line?

### ISSUE THREAD

**Issue by Tembocs** [microsoft/terminal#926]
I've built successful from command line using the following command.
`msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 OpenConsole.sln`
I'm trying to find a possible solution for deploying from the command line. Is adding `/p:DeployOnBuild=true` enough? What other things need be done if necessary? Any guidance on what Deploy does, e.g. copying files to where, writing some environmental variables?

**Comment by timheuer** [comment]
No this is not enough as the deploy is actually deploying a UWP app, which isn't from MSBuild.  Using things like the WinAppDeployCmd SDK tool might be an option here, but I think also a powershell script is probably the easiest...I haven't looked to see if anyone started one or not.

**Comment by timheuer** [comment]
https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps#examples

**Comment by oising** [comment]
I've got a work item assigned to me for this. It's possible to deploy it as a "dev build" with `Add-AppXPackage` and using the AppManifest.xml as a path target with the `-Register` switch, but this install lacks taskbar and start menu icons (it's just a black square.) Additionally, I've had intermittent problems with launching the app like this - occasionally it opens with a blank white window and hangs. 

The long-winded way to install it is to create a self-signed certificate, add it as a local trusted root, and run the generated `Add-AppDevPackage.ps1` that sits in the Cascadia output folder. Additionally, you have to run a Release build (use `bzc rel`) as the Debug build won't generate an AppXBundle by default as it's a lengthy process.

**Comment by Tembocs** [comment]
@oising I can't locate the AppManifest.xml file in the project. Does one need to create it manually? If yes what exactly should be in it?

**Comment by zadjii-msft** [comment]
AppManifest.xml is auto-generated by visual studio when building the package. It's possible that msbuild would build it too, but I'm not 100% positive on that. I know it's generated from `package.appxmanifest`, as well as some other metadata the project knows about it's dependencies.

**Comment by WSLUser** [comment]
So I think self-signed is fine for dev builds but for official released builds, a proper certificate i needed. To put in simple terms, it's easier to grab the appx bundle from Artifacts from latest commit and install it (either double-click or PS script) than to have to grab Visual Studio and build the solution. Right now attempting to grab an appx from Artifacts and installing it will fail unless you have Developer-Mode on as there is no cert or it's considered untrusted by Windows. Unfortunately Developer Mode breaks Win32-OpenSSH, which I and a bunch of other people use (It can be more convenient than opening a WSL session just to remote into another host).

**Comment by zadjii-msft** [comment]
I mean, both building it from source and trying to run it from the build artifacts are both harder than just installing it from either the store or github, both of which have been available for some time now...

**Comment by DHowett-MSFT** [comment]
> Developer Mode breaks Win32-OpenSSH

???
We all use Win32-OpenSSH with developer mode turned on all the time. This is the first I’m hearing of this.

**Comment by WSLUser** [comment]
There's a known bug for it but appears to only affect some hosts. I believe having to install some software on an isolated network tends to make installations a bit more difficult (can't grab Dev Mode packages, SmartScreen prevents some app installs since it can't verify trustworthiness) and in Terminal's case, installation outside of Store and Chocolately, even with proper dependencies installed result in Terminal being unable to run with Windows thinking there's a network connection error (not sure why it's looking for a network connection to start with).

**Comment by WSLUser** [comment]
Also idea of self-signing the dev builds is basically to add the equivalent of the ConEmu feature where you get to choose between stable, beta, and alpha (which is essentially in most cases master branch). The process would need to be manual for now but since the software needs to be physically moved to a different network (via USB or portable HDD/SSD) , it's a manual process regardless.

**Comment by awakecoding** [comment]
I am trying to build and run Windows Terminal from the command-line. I did manage to build it using the [PowerShell module](https://github.com/Microsoft/Terminal#building-in-powershell), but I am unable to launch either WindowsTerminal.exe or wt.exe. There's a mention that one cannot launch it outside of Visual Studio, but why is that? Is code signing mandatory in order to launch Windows Terminal? I have successfully copied the files from an existing MSIX installation into a temporary directory and launched it from there, so what's different from trying to launch one that was just built from source?

**Comment by zadjii-msft** [comment]
Note to self: After the changes to unpackaged, portable, etc in 1.18, there might be better ways of doing this from the commandline in the near future. 

Refer to #15133 - that was one of the tip PRs for calling `makepri` manually. We may be able to find a way to modify that to just rebuild the package resources without needing to do the whole commandline deploy. 

Now, if only we could get the FastUpToDate check
