### ISSUE TITLE
Paste in PowerShell drops certain characters like "【】｜"

### ISSUE THREAD

**Issue by czphoenix** [microsoft/terminal#9263]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable):1.5.10411.0
PowerShell 7.1.2
Windows PowerShell
```

# Steps to reproduce

1. Open a tab of PowerShell 7.1.2 or Windows PowerShell
2. Copy any line of the following text
```none
【1】【2】【3】[4][5][6]
【】【】【】
【【【【【【
】】】】】】
｜｜｜｜｜｜
1｜2｜3｜4|5|6|
```
3. Paste it

# Expected behavior

Pasted text should be the same as copied

# Actual behavior

Ended up with the following
```none
【123[4][5][6]
【
【
】
｜
1234|5|6|
```
Works fine in Terminal 1.4.3243.0
Works fine in Command Prompt and Ubuntu
Works fine in standalone Windows PowerShell and PowerShell 7

**Comment by skyline75489** [comment]
Holy cow this is real. Happens in 1.5, 1.6 & 1.7.

**Comment by WSLUser** [comment]
If the previous release of Cascadia Code is used for the font, does this issue still happen? That would be the only major change that could cause this since I don't think the bracketing paste mode and paste filtering was applied to 1.5. Otherwise I would look to that as the culprit.

**Comment by DHowett** [comment]
This is due to neither the font nor the bracketed paste filtering.

**Comment by skyline75489** [comment]
The filtering does not seem to matter. Feels like a PSReadline problem while I was debugging, cuz it only happens with PowerShell. But I’m not sure.

All those characters are Chinese characters by the way. And conhost can not correctly display them either.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dustin L. Howett <notifications@github.com>
发送时间: Thursday, February 25, 2021 12:43:38 AM
收件人: microsoft/terminal <terminal@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [microsoft/terminal] Paste in PowerShell drops certain characters like "【】｜" (#9263)


This is due to neither the font nor the bracketed paste filtering.

―

**Comment by zadjii-msft** [comment]
I'm shocked by the assertion that this would work in 1.4.xxx. I _really_ don't think there's anything that would have changed in that timeframe. 

![image](https://user-images.githubusercontent.com/18356694/109159142-e6907480-7739-11eb-96fe-703263b76a35.png)


Yea this is definitely a PSReadline issue. Please file this upstream at https://github.com/powershell/psreadline

**Comment by czphoenix** [comment]
[PSReadLine](https://github.com/PowerShell/PSReadLine/issues/2249#issuecomment-791852947)
Removing PSReadLine do fix the issue, but it does not explain why it is fine in standalone PowerShell Core Console, PowerShell Console, Cmder etc..

**Comment by skyline75489** [comment]
That's probably because Windows Terminal handles pasting differently than conhost & cmder.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by skyline75489** [comment]
@czphoenix Despite the similar functionally, Windows Terminal & conhost (the terminal that PowerShell Core Console, PowerShell Console and Cmder are using) actually have very different input stack, and totally different code path for paste handling.
