### ISSUE TITLE
Appearance settings in a pane aren't updating on reload

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#9280]
I had a background image in a profile and then tried to update it in the settings UI while the profile was open in a pane, and the image didn't update. Same thing happened when I tried to update my color scheme while the profile was open in a pane. (I had two panes open at the time.)

Looks like this also happens when you try to enable `focusFollowMouse` using the settings UI. The setting is just ignored.

# Environment

```none
Windows build number: 10.0.21318.0
Windows Terminal version (if applicable): 1.7.543.0

Any other software?
```

# Steps to reproduce

Open two panes and change the background image or color scheme in the settings UI.

# Expected behavior

The pane updates its appearance to the new settings.

# Actual behavior

The newly saved settings are being ignored and the pane looks the same.

**Comment by carlos-zamora** [comment]
Repros on v1.6.10272.0 as well.

**Comment by DHowett** [comment]
In 1.7, I could get it to reliably reproduce _even with the JSON file_.

In 1.6, I could not.

@PankajBhojwani - We're seeing an issue where settings are only applied to the *first* pane. I tried the following:

1. Launch
2. Split
3. My background is `#203`
   * ![image](https://user-images.githubusercontent.com/189190/109183166-83efa680-7742-11eb-9bd2-4fa16959852d.png)
4. Update background to `#225033`
   * ![image](https://user-images.githubusercontent.com/189190/109183228-936eef80-7742-11eb-910f-85277d78b6cb.png)
5. Split
   * ![image](https://user-images.githubusercontent.com/189190/109183276-9ec21b00-7742-11eb-8615-deefdcd4fcb4.png)
6. Update background to `#228033`
   * ![image](https://user-images.githubusercontent.com/189190/109183313-a97cb000-7742-11eb-83e8-0536169d2fd6.png)


Since you've been working in TerminalSettings propagation and pane stuff, would you mind taking a look?
This also, weirdly, impacts focus-follows-mouse. I guess we made it a `TerminalSettings` setting instead of leaving it in the app layer (😬)
