### ISSUE TITLE
unused terminals

### ISSUE THREAD

**Issue by bckelley** [microsoft/terminal#9347]
# Description of the new feature/enhancement
I find it annoying that I can't delete Azure Cloud or WSL terminal or cmd prompt from settings files. I don't even use these programs and I am tired of them clogging up the settings file. Is there some workaround I'm missing, or can there be an update to add this feature?

# Proposed technical implementation details (optional)

**Comment by WSLUser** [comment]
Use the `disabledProfileSources` option or `hidden` in Settings. These are also in the Settings UI.

**Comment by bckelley** [comment]
> I don't even use these programs and I am tired of them clogging up the settings file.

I'm not sure if you actually read this but I clearly state that I DON"T want it clogging up the settings json file

**Comment by Johbii** [comment]
> 
> 
> > I don't even use these programs and I am tired of them clogging up the settings file.
> 
> I'm not sure if you actually read this but I clearly state that I DON"T want it clogging up the settings json file

Isn't this a very niche point? What is the functional difference in changing this?

**Comment by skyline75489** [comment]
Well for better or worse, we're moving to use the Settings UI as the default experience. You won't see any JSON if you only use Settings UI 😄

**Comment by zadjii-msft** [comment]
Alright so there are a variety of solutions here:
* For the cloud shell and WSL, you can stop them from being autogenerated with `"disabledProfileSources": ["Windows.Terminal.Wsl", "Windows.Terminal.Azure"]`. Then you could go ahead and delete the stubs from your settings file.
* `"hidden": true` will also work on these profiles, though you specifically don't want them in your json file. We unfortunately need to leave the stubs in there so that we know if a user has seen them or not. Without the stub in your settings file, the WSL auto-detector presumes that this is a distro that you've newly installed.  
* When App state (#8771 and follow-ups) land, it'll be easier to hide/disable these profiles from the settings UI, without cluttering your settings file.
* For cmd.exe - that's a "built-in" profile, which is in the `defaults.json` file. If you want to hide that from the new tab dropdown, you'll need to rely on `"hidden": true`. Sorry about that. I don't think that 
```json
{
    "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
 	"hidden": true
}
```
  is too much clutter.

**Comment by bckelley** [comment]
thank you @zadjii-msft most helpful! I've looked at the default json  file and have noticed powershell is a built-in profile as well, will App state fix it as well?

**Comment by zadjii-msft** [comment]
No, app state isn't planning on addressing the built-in profiles. If you want Command Prompt **and** Windows PowerShell hidden, then you'll have to live with the 8 lines in your json file 😄
