### ISSUE TITLE
Title name

### ISSUE THREAD

**Issue by tonycody** [microsoft/terminal#9355]
Use Windows terminal open the window,Use Ubuntu，but when system login,the Window title name change the system account name?why not keep Ubuntu?

**Comment by zadjii-msft** [comment]
Because your shell (`bash` or `zsh` or whatever) has explicitly told the Terminal "please set the window title to {whatever}". In `bash`, it does this in the `PS1` variable in your `.bashrc`. You'll note that this is the same way that a linux terminal behaves.

If you don't want the application to be able to set the title, you can set [`"suppressApplicationTitle": true`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#suppress-title-changes) in your settings.

**Comment by tonycody** [comment]
> Because your shell (`bash` or `zsh` or whatever) has explicitly told the Terminal "please set the window title to {whatever}". In `bash`, it does this in the `PS1` variable in your `.bashrc`. You'll note that this is the same way that a linux terminal behaves.
> 
> If you don't want the application to be able to set the title, you can set [`"suppressApplicationTitle": true`](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#suppress-title-changes) in your settings.

![image](https://user-images.githubusercontent.com/6773121/110560561-2b2bff00-8181-11eb-9154-314b533334a9.png)
Each one has to be set independently, which is too much trouble. Can you provide a global setting?

**Comment by DHowett** [comment]
![image](https://user-images.githubusercontent.com/189190/110563151-7a861700-8110-11eb-9868-f63622231b32.png)

...
