### ISSUE TITLE
Paste adding extra new lines

### ISSUE THREAD

**Issue by justmobilize** [microsoft/terminal#9378]
# Environment

```none
Windows build number: `Microsoft Windows [Version 10.0.19042.804]`
Windows Terminal version (if applicable): `1.6.10571.0`

Any other software?
```

# Steps to reproduce

I am constantly ssh-ing to a box, starting up iPython, pasting a block of code (with methods), and then running selected methods. Currently I've been using `putty` and this works great.

Switching to `Windows Terminal` I tried this, and it pastes one line at a time, and thus errors out.

I can do awkward things like `%cpaste` in iPython or `:set paste` in Vim, but that makes things more complicated

For example pasting:
```
def add(a, b):
  # add method

  val = a + b

  return val

print(add(1,2))
```

# Expected behavior

I should get this, everything pasted together:
![image](https://user-images.githubusercontent.com/1547881/110021261-5e811080-7cdf-11eb-8f71-c73a92527627.png)

# Actual behavior

I get this:
![image](https://user-images.githubusercontent.com/1547881/110021127-385b7080-7cdf-11eb-9131-17dbbda41d4d.png)

Which obviously will cause errors

**Comment by zadjii-msft** [comment]
This _sounds_ like something that bracketed paste (#395) might just fix. Can you try installing Windows Terminal Preview, and see if that fixes it? Preview added support for bracketed paste in 1.7.

**Comment by justmobilize** [comment]
@zadjii-msft thanks, but sadly no. Got the same results.

Installed v1.7.572.0

**Comment by skyline75489** [comment]
Like Dustin said in https://github.com/microsoft/terminal/issues/9364#issuecomment-789992943  you may need to use a newer version of Win32-OpenSSH in order to make the bracketed paste work over SSH.

**Comment by justmobilize** [comment]
Huzzah! That works.

Will the newer version of both of these be released soon?

**Comment by skyline75489** [comment]
The 1.7 preview will become 1.7 stable about the end of the month, I think? You know the preview is actually good enough for most people I think. The preview version is released after being tested inside Microsoft. I've been using preview like forever. 

I actually do not know about the release schedule of Win32-OpenSSH. I was also wondering this.  That's probably what @DHowett  can answer.

**Comment by WSLUser** [comment]
> I do not know about the release schedule of Win32-OpenSSH

Well there's been no movement on it for over a year and they're quite a few releases behind the mainstream ssh. By now we should be at 8.6 but 8.1 is the last release. The Powershell team is supposed to be responsible for it but seems like it's just not a priority for them. I almost consider it abandonware for that reason.

**Comment by gousaiyang** [comment]
@trevor-pope I'm having a similar issue with IPython recently and found a way to solve it. I guess you might be having the same problem and I want to share my findings:

I'm using IPython in Windows Terminal. The profile is `"commandline": "ipython.exe"`, so this is just running the IPython in Windows, not an IPython in WSL, and not through SSH, just on my local machine. I observed incorrect indentation when pasting multiline code into IPython. It was working correctly for a long time but started to break recently. I was originally suspecting this to be a Windows Terminal problem, but it turned out to be [a bug in `prompt-toolkit`](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1519) (a dependency of IPython) since version 3.0.20.

On Windows, IPython does not emit `\x1b[?2004h` to inform terminal of bracketed paste support. Instead, it utilizes the following two mechanisms to achieve bracketed paste:

1. By utilizing `prompt-toolkit` to [recognize multiline paste as bracketed paste](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/df8246cf03deec681a521c03a12a68d712158e24/prompt_toolkit/input/win32.py#L266).
2. Additionally, by [registering a handler for Ctrl-V key event](https://github.com/ipython/ipython/commit/589822493192889f8d6902f3461ae63e0040ff5f) to improve the paste behavior.

When using Windows Terminal, the second mechanism (handler for Ctrl-V key event) will not work because Ctrl-V is already handled by Windows Terminal (as in the default `settings.json`) and not passed to the application. The application received pasted text instead of the Ctrl-V key event. When the first mechanism (`prompt-toolkit`) is buggy, IPython will fail to correctly handle multiline paste.

When using the traditional conhost, the incorrect indentation does not happen even when `prompt-toolkit` is buggy because the second mechanism (handler for Ctrl-V key event) is working there. If you paste content by "Right clicking conhost window title -> Edit -> Paste", the incorrect indentation will show up.
