### ISSUE TITLE
Pasting tab characters into the Terminal replaces these characters with the name of the first file in the working directory

### ISSUE THREAD

**Issue by TautvydasZilys** [microsoft/terminal#9380]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable): 1.6.10571.0

Any other software? Terminal configured to use cmd.exe
```

# Steps to reproduce

Copy paste this into the terminal: 

```
	hello
```

# Expected behavior

"hello" gets pasted into the terminal

# Actual behavior

"hello" gets prepended with the first file in the directory: ".bash_historyhello"

I reproduced it on all machines I tried it on. It doesn't reproduce when using cmd.exe through the default windows conhost.exe. This issue is especially annoying when copy pasting stuff from websites as they like to contain "invisible" tabs.

**Comment by KalleOlaviNiemitalo** [comment]
Consider setting the `no_empty_cmd_completion` option in Bash.

**Comment by KalleOlaviNiemitalo** [comment]
bq. It doesn't reproduce when using cmd.exe through the default windows conhost.exe.

It does for me, if I uncheck the "Filter clipboard contents on paste" option.

**Comment by KalleOlaviNiemitalo** [comment]
For conhost, removal of pasted TAB characters is implemented here: <https://github.com/microsoft/terminal/blob/507a84664e6d5449bc31746510128d3136ecc719/src/interactivity/win32/Clipboard.cpp#L338-L343>

I don't see similar filtering in TermControl::_SendPastedTextToConnection.

**Comment by j4james** [comment]
Paste filtering was only recently added, but we don't currently filter the tab character:
https://github.com/microsoft/terminal/blob/2c603ef953752b315f3c1e1c4b49368c76390cf3/src/types/utils.cpp#L456-L457

I didn't think it was necessary, since most *nix terminals don't, but obviously they're not dealing with a cmd shell. I think XTerm replaces the tab character with space, so maybe that's an option we could go with.

cc @skyline75489

**Comment by DHowett** [comment]
This one is likely going to bruise a few people. Pasting tabs is important for things that aren't cmd, but it's unpleasant for things that are. :|

**Comment by skyline75489** [comment]
So if I'm understanding this correctly, cmd.exe actually filters tab to prevent "inadvertant tab expansion", while most *nix terminals does not do this, but somehow also does not suffer from the tab expansion issue? Forgive me for being an ignorant man, I don't quite get it why cmd.exe is so special.

**Comment by j4james** [comment]
Typing TAB in a cmd shell autocompletes with the first file in the current directory, while typing TAB in a *nix shell will only have an effect if you've already typed something else on the command line (at least as far as I know - I'm not an expert). So technically pasting a TAB could still do something weird in a *nix shell, but I think it's less likely. And even then the problem could be avoided by enabling bracketed paste, which is not an option in a cmd shell.

**Comment by skyline75489** [comment]
Well, guess I *really* don't know cmd or Windows that well. 

Like Dustin said, I don't feel quite comfortable just striping Tabs since some folks might actually want to paste a lot of Tabs. Why would XTerm just replacing Tabs with space? Does that frustrates people who just want tabs? Or is there an option for it.

**Comment by j4james** [comment]
XTerm has options for just about everything, so it wouldn't surprise me if this was an option too. And it's not just TAB - there are a few other control characters that they replace with space which some terminals just filter out.

**Comment by skyline75489** [comment]
OK now I honestly have no idea how we should do about it. I’ll just trust Dustin’s decision on this one.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: James Holderness <notifications@github.com>
发送时间: Friday, March 5, 2021 9:47:44 AM
收件人: microsoft/terminal <terminal@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [microsoft/terminal] Pasting tab characters into the Terminal replaces these characters with the name of the first file in the working directory (#9380)


XTerm has options for just about everything, so it wouldn't surprise me if this was an option too. And it's not just TAB - there are a few other control characters that they replace with space which some terminals just filter out.

―

**Comment by TautvydasZilys** [comment]
Is this issue still being triaged? I'm facing it every day and it's very, very annoying.

**Comment by zadjii-msft** [comment]
Well, I dunno how this fell off the triage queue. 

This one's tricky - 
* We probably don't want to filter all tabs, because as mentioned, there's probably someone out there actually pasting tabs in `bash` for something.
* Seemingly, this is a special conhost feature, not a `COOKED_READ` one, because it doesn't work "for free" in `cmd` in Terminal
* We probably don't want to just add it to `COOKED_READ` if it's not something that's already in there, because that'll inevitably break someone else.
* I wonder if this has to do with QuickEdit mode in conhost, which there's no good analog for in the Terminal.
