### ISSUE TITLE
Pressing 'Enter' to execute a command first moves cursor to end of line

### ISSUE THREAD

**Issue by rectified95** [microsoft/terminal#9440]
# Environment

```none
Windows build number: Win32NT             10.0.21322.0 Microsoft Windows NT 10.0.21322.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce

1. Type any command, eg. `git status` and move the cursor to the middle of the string.
2. Press `Enter` to run the command.

# Expected behavior

Command should execute immediately.
# Actual behavior

Seeing a short flicker due to the cursor moving to the end of the line before the command gets executed.

**Comment by zadjii-msft** [comment]
What shell are you using? cmd? PowerShell? Some linux shell (possibly via ssh or WSL)? Something else? And what version of that shell?

**Comment by rectified95** [comment]
It defaults to Powershell for me.

**Comment by jdebp** [comment]
Actually, executing immediately from the cursor in the middle of the input line is _not_ the expected behaviour.  The expected behaviour, from pretty much all shells and command interpreters, is to have the cursor on the start of the following line and _then_ execute the command.  Sometimes this involves finalization of the input area in some form.  (The Z shell erases any active completion menu, for example. A command-line interpreter could have things like deferred syntax colouring, un-highlighting of pasted text, or other stuff to do at finalization.)

[PSReadLine's finalization apparently involves moving the input point to the end of the line](https://github.com/PowerShell/PSReadLine/blob/0de63689c40135825d84002e6c394d8033f22ee0/PSReadLine/BasicEditing.cs#L303).  This is _nothing to do with Windows Terminal_, which just displays what programs tell it to.

**Comment by zadjii-msft** [comment]
Yep, that sure does sound like it's caused by PSReadline. Note that if you `Remove-Module PSReadline`, the behavior goes away 😉 If you want, you could try filing a bug upstream at https://github.com/powershell/PSReadline, but this might be by-design.
