### ISSUE TITLE
Option to confirm before closing a tab

### ISSUE THREAD

**Issue by ercius** [microsoft/terminal#9470]
# Description of the new feature/enhancement

I accidentally clicked the x on a running Ubuntu terminal (instead of activating that tab) and closed an important ssh session losing all work. There was no confirmation to close the running session. 

Can an option to confirm on exit for a single tab be added? There is already an option to confirm when closing many tabs, but not for a single tab.

BTW: Windows Terminal is awesome. Where has this been all my life?

**Comment by Nacimota** [comment]
This seems pretty reasonable to me as an optional feature, disabled by default. Perhaps we could even have it as a per-profile setting? So for instance if you have a profile you mostly use for SSH or something important you don't want to accidentally close you could set `warnOnClose` (or whatever) to `true`.

**Comment by Don-Vito** [comment]
@Nacimota - great idea.

@ercius  - consider using read-only panes for important stuff (https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#mark-a-pane-as-read-only-preview).

In addition, there is https://github.com/microsoft/terminal/issues/3335, suggesting to hide the "x" button to prevent such faulty clicks.

**Comment by ercius** [comment]
`warnOnClose` is a great option to have per tab.

Ill also check out the read-only panes in Preview and see how they work. Thanks!

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #6549 for more discussion.

/dup #6549

**Comment by nullbio** [comment]
Was this actually implemented? Was marked as completed, but I don't see this in the actual program.

**Comment by addison-rio** [comment]
Yeah, they suck at maintaining any of the discussion. Took me a bit to get it, but look - this is even better - just get rid of the stupid button:

In WindowsTerminal's `settings.json`:

```json
{
    ...,
    "theme": "Dark Without Close Buttons",
    "themes": [
        {
            "name": "Dark Without Close Buttons",

            "window": {
                // THIS IS THE THEME YOU WANT TO OVERRIDE! I didn't want to lose dark mode, so I put `dark` here.
                "applicationTheme": "dark"
            },

            "tab": {
                "showCloseButton": "never"
            }
        }
    ],
    ...
}
```

Note - this may require you to actually _get good_ and hit `ctrl + d` to kill your terminal with an EOF, or type `exit`. That's because this also disables `ctrl + w` and middle-click closing tabs. AKA - you basically cannot kill a tab - you have to kill the process.

Failing that, you can still right-click on the tab, and painstakingly click `close tab` to get the old functionality, should you need it.
