### ISSUE TITLE
不是bug，关于用户体验的优化

### ISSUE THREAD

**Issue by wjliuh007** [microsoft/terminal#9486]
如果可以复制标签页，带session的复制，用户体验会更好，比如我ssh登录了堡垒机，如果我想再打开一个堡垒机的控制台，需要重新输入密码，这样用户体验就不好，如果可以直接右键复制选项卡，打开的新选项卡就是前一个的堡垒机那岂不是更好。

补充一点，就是类似 xshell的【copy ssh channel】

**Comment by skyline75489** [comment]
Translation:

Not a bug, but suggestions of how to improve the user experience.

When you duplicate a tab, it would be great if you can duplicate the *session* in it.  For example if I ssh into a jump server using one tab, duplicating this tab would require me to re-enter the password. Being able to duplicate the session in it would be great, because it saves the re-entering of password.

Another feature request: "copy ssh channel" as in XShell.

**Comment by skyline75489** [comment]
首先我真的不清楚有哪个 terminal 支持带 SSH session 的复制功能，也不知道是不是有通用的实现方法。

OK first I don't really know a terminal that supports this "duplicate SSH session" feature, nor do I know if there's a general way to implement it.

其次 Windows Terminal 的目标和 XShell 之类的专用 SSH 软件并不完全相同，后者在 SSH 方面的专业程度明显更高，而 Windows Terminal 则是更通用的 terminal 软件。

Second, the goal of Windows Terminal is not exactly the same as professional SSH client like XShell. While the latter clearly experts at SSH-related feature, Windows Terminal is meant to be a general terminal.

**Comment by pan3793** [comment]
You can leverage ssh `ControlMaster` to simulate `copy ssh channel`(I don't know how `xshell` implement it), but AFAIK, it doesn't work in Windows, but works in WSL.

**Comment by DHowett** [comment]
`ControlMaster` will handle this for you. @skyline75489 is correct -- Terminal is not a professional SSH client; it is a terminal. Thank you!
