### ISSUE TITLE
When will legacy console be deprecated?

### ISSUE THREAD

**Issue by moon6969** [microsoft/terminal#9493]
# Description of the new feature/enhancement
Unfortunately our tooling is incompatible with the new terminal (particularly the forced line wrapping).
So for now we will enable "use legacy console".

I would like to know please how long the legacy console is likely to be supported?

Thanks.

**Comment by DHowett** [comment]
Application developers have had 6 years to adjust to the new non-legacy console. I highly recommend that you do so, because I am going to end support for the legacy console the very moment it becomes too burdensome to continue supporting it.

**Comment by DHowett** [comment]
(Line wrapping is not forced in conhostv2; it is a user preference. Your application can change the screen buffer size to make sure that its text fits at all times without wrapping. This is possible with the SetConsoleScreenBufferInfoEx function.)

**Comment by matsmcp** [comment]
The Legacy console is currently (as far as I know atleast) the only way to have a console working remotely under WinPE (2004). 
For some that doesn't matter at all. For others that have 1000Km to the box booting WinPE - it's rather important. Even more so adding Corona Restrictions.

I know that both MS Dart and Uvnc fails to produce a CMD window with Console V2 but if you force it to use legacy with  "HKCU\Console\ForceV2","0","REG_DWORD" it works. 

So please, make sure that this is resolved before removing the legacy console.

**Comment by DHowett** [comment]
Huh? We use the "modern" console under WinPE _all the time!_

I don't know what "MS Dart" or "Uvnc" are, but it seems like they are doing something strange if it's not possible to activate a v2 console window.

**Comment by matsmcp** [comment]
Dart is Diagnostics and Recovery Toolset a part of Microsoft Desktop Optimization Pack. They provide a "RDP server" for WinPE
Ultra VNC is a third party VNC client/server 

It's even more strange than that. After doing some digging/testing and bing/googling
Building WinPE from ADK 1903 with "modern" console works. 
Building WinPE from ADK 2004 with "modern" console fails.
Building WinPE from ADK 2004 with "legacy" console works.

Definition of works is that you can se the CMD window through a remote connection (dart/RDP or Uvnc)
Just wanted to let you know since it's something that is very usable (even more so with Corona restrictions)
