### ISSUE TITLE
font changed after I used less or vim command

### ISSUE THREAD

**Issue by zhouzhendiao** [microsoft/terminal#9512]
# Environment

```none
Windows build number: [Version 10.0.17763.1397]

```

# Steps to reproduce

font changed after I used less or vim command in WSL1

# Expected behavior
When I open WSL, the font like this:
![image](https://user-images.githubusercontent.com/12294679/111242436-21e7da00-863a-11eb-8e6c-6654419be2fe.png)

# Actual behavior
But after I used Vim or Less:
the font would change like this:
![image](https://user-images.githubusercontent.com/12294679/111242469-3330e680-863a-11eb-80ac-34294303773e.png)

Can Someone tell me the reason?

**Comment by skyline75489** [comment]
what is the terminal you are using? Is it cmd.exe? Is it Windows Terminal? You need to give us more.

**Comment by j4james** [comment]
I suspect this might be related to issue #221, although that seems to be triggered by codepage changes, which I wouldn't have thought likely in a WSL shell. But if that is the case, then this is assumedly the GDI renderer and thus conhost. If it turns out he's using Windows Terminal then I have no idea.

**Comment by DHowett** [comment]
Version 10.0.17763 ... looks like it _might_ be before WSL used ConPTY for hosting Windows applications. If you end up running the Windows version of vim or less (`vim.exe` or `less.exe`), it absolutely may change your codepage. Unavoidable.

**Comment by zhouzhendiao** [comment]
> what is the terminal you are using? Is it cmd.exe? Is it Windows Terminal? You need to give us more.

Just WSL1: ubuntu18.04

**Comment by zhouzhendiao** [comment]
> I suspect this might be related to issue #221, although that seems to be triggered by codepage changes, which I wouldn't have thought likely in a WSL shell. But if that is the case, then this is assumedly the GDI renderer and thus conhost. If it turns out he's using Windows Terminal then I have no idea.

Thanks for replying, I just use WSL1

**Comment by zadjii-msft** [comment]
* Can you use the console property sheet to show us what the selected fonts are before and after opening vim?
  ![image](https://user-images.githubusercontent.com/18356694/112008515-8bad2b80-8af3-11eb-9200-3b02ee4e8700.png) -> ![image](https://user-images.githubusercontent.com/18356694/112008573-9b2c7480-8af3-11eb-87e8-cc319cedacb6.png)

* Does the font change when you enter vim, then return to the original when you exit?

I'm thinking this is probably the same root cause as #415.

**Comment by zhouzhendiao** [comment]
> * Can you use the console property sheet to show us what the selected fonts are before and after opening vim?
>   ![image](https://user-images.githubusercontent.com/18356694/112008515-8bad2b80-8af3-11eb-9200-3b02ee4e8700.png) -> ![image](https://user-images.githubusercontent.com/18356694/112008573-9b2c7480-8af3-11eb-87e8-cc319cedacb6.png)
> * Does the font change when you enter vim, then return to the original when you exit?
> 
> I'm thinking this is probably the same root cause as #415.

Thanks! 
Before opening Vim:
![before_vim](https://user-images.githubusercontent.com/12294679/112076174-e65a8c00-8bb4-11eb-8f76-290b3324553c.png)
After opening Vim:
![after_vim](https://user-images.githubusercontent.com/12294679/112076269-1144e000-8bb5-11eb-8b0e-0bcd627560a9.png)

Yeah, font changed from "Consolas" to "新宋体"（Chinese font）

**Comment by zadjii-msft** [comment]
Yea, this looks exactly like /dup #415
