### ISSUE TITLE
Use newer powershell icon?

### ISSUE THREAD

**Issue by Summon528** [microsoft/terminal#952]
# Summary of the new feature/enhancement

The default PowerShell icon included in #934 looks that it was from Win7 era. Should we use newer Powershell icon like [this one](https://github.com/PowerShell/PowerShell/blob/master/assets/Powershell_64.png)?

**Comment by DHowett-MSFT** [comment]
The icon included in #934 is directly out of the Windows PowerShell executable shipped in-box on Windows 10.

@stevel-msft Windows Terminal intends to ship a Windows PowerShell profile by default until convergence; which version of the blue powershell icon should we use for it?

**Comment by DHowett-MSFT** [comment]
You know, I must have grabbed the wrong one. I’ll generate new scaled versions from the blue svg.

**Comment by SteveL-MSFT** [comment]
@DHowett-MSFT I wouldn't necessarily use the assets we have in Windows; simply because we're trying not to touch that code unless necessary.  My suggestion is to use https://github.com/PowerShell/PowerShell/blob/master/assets/powershell_128.svg (for Windows PowerShell) and https://github.com/PowerShell/PowerShell/blob/master/assets/ps_black_128.svg for PSCore6 (and eventually PS7)

**Comment by DHowett-MSFT** [comment]
@stevel-msft thanks!
