### ISSUE TITLE
Can't copy correctly when a folder or a file that contains Japanese dot (。) dragged to Windows Terminal or the path is copied from Windows Explorer to Windows Terminal

### ISSUE THREAD

**Issue by AlifianK** [microsoft/terminal#9550]
Windows Terminal can't copy correctly when a folder or a file that contains a Japanese dot or full stop (。) dragged or the path copied from Windows Explorer. I've tried the same folder with Windows PowerShell and Powershell but it seems it only affects Windows Terminal.
I've tried using ```Get-ChildItem``` to check, and it displayed the folder correctly
```
PS D:\> Get-ChildItem

    Directory: D:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          26/02/2021    16:32                Data
d----          05/01/2021    19:13                Games
d----          29/01/2021     6:39                Master
d----          23/02/2021    22:32                Multimedia
d----          07/11/2020    12:10                SUPERVISI MUTU LPMP
d----          03/03/2021    15:03                Tools
d----          05/03/2021    19:16                君の名は。 (Deluxe Edition)
-a---          17/08/2020    22:22         193632 JADWAL PELAJARAN DAN LAPORAN MATERI AJAR BDR SMP 5.docx
-a---          30/12/2019     8:55         403928 TIME TABLE GANIJIL TATAPMUKA.roz
```
when I tried to change the directory to ```君の名は。 (Deluxe Edition)``` via dragging the folder or copying the folder path from Windows Explorer, Windows Terminal can't do it.
```
PS D:\> Set-Location "D:\君の名は (Deluxe Edition)"
Set-Location: Cannot find path 'D:\君の名は (Deluxe Edition)' because it does not exist.
```
notice that Windows Terminal didn't display (。) at all.

Then I typed (。) manually or copied (。) separately from the folder name and it worked
```
PS D:\> Set-Location "D:\君の名は (Deluxe Edition)"
Set-Location: Cannot find path 'D:\君の名は (Deluxe Edition)' because it does not exist.
PS D:\> Set-Location "D:\君の名は。 (Deluxe Edition)"
PS D:\君の名は。 (Deluxe Edition)>
```

# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0
```

# Steps to reproduce

Name a folder with Japanese full stop
```
a。
```
then drag the folder or copy the folder path from Windows Explorer or to Windows Terminal then run ```Set-Location``` or ```cd``` command to go to the folder

# Expected behavior

Windows Terminal read the folder path correctly
```
PS D:\> Set-Location "D:\君の名は。 (Deluxe Edition)"
PS D:\君の名は。 (Deluxe Edition)>
```

# Actual behavior

Windows Terminal doesn't display (。) at all when the folder is dragged or when the directory path is copied or when the folder name is copied
```
PS D:\> Set-Location "D:\君の名は。 (Deluxe Edition)"
```
becomes
```
PS D:\> Set-Location "D:\君の名は (Deluxe Edition)"
```

**Comment by DHowett** [comment]
If you `remove-module psreadline`, does it work?

**Comment by AlifianK** [comment]
It worked.

**Comment by DHowett** [comment]
Okay, this is a well known bug with PSReadline where it deletes certain characters when they are inserted.

**Comment by tsukumijima** [comment]
As you can see at https://github.com/PowerShell/PowerShell/issues/14949, this issue is

- PSReadline is enabled
- Using Windows Terminal

It only happens if. It happens in both Windows PowerShell 5.1 and PowerShell 7.

On the other hand, as a similar problem, if you enter a path that includes Japanese Full-width Midpoint (・), Midpoint will be dropped. This happens with Windows PowerShell 5.1, PowerShell 7, and even without Windows Terminal.

In either case, you can run `Remove-Module PSReadLine` to disable PSReadLine and the characters will be typed in without omissions. From this, I think it is certain that the bug in PSReadLine has an effect.

Various sites in Japan have suggested that the solution is to set `Remove-Module PSReadLine` in the profile to disable his PSReadLine.
PSReadLine provides beautiful highlights, so it's a shame that the Japanese need to disable it just for this bug.

I'm not sure if this issue is also caused by Windows Terminal, but I don't think it's preferable that it hasn't been resolved for years, so I think some action should be taken. This problem is fatal.

I'm using translation. The sentence may be unnatural.
