### ISSUE TITLE
Auto save tabs or save option

### ISSUE THREAD

**Issue by jineshnag** [microsoft/terminal#9565]
In Windows Terminal, is there a:
1. Auto save tabs  OR
2. Save tabs option

If not,  can this be provided.  It will be very useful, if multiple tabs are open and for whatever reason WT is closed, user has to rebuild the tabs, which is pain-staking and time consuming.

**Comment by skyline75489** [comment]
#961

**Comment by zadjii-msft** [comment]
So for reference, I like to do like the following each time I boot up the Terminal in the morning:

```json
{ "command": { "action": "wt", "commandline": "new-tab --title OpenConsole cmd.exe /k #work 15 ; split-pane -s .30 --title OpenConsole cmd.exe /k #work 15 ; split-pane  -s .25 -H cmd.exe /k media ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },

```

(you could probably make it shorter by replacing `new-tab`/`split-pane` with `nt`/`sp`, respectively).

I add that to the `keybindings`/`actions`. This creates a new command in the [Command Palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette) named "Good Morning". That opens up a few tabs & panes, running various build environments. I like having it in a command rather than `startupActions`, because I only really want this in _one_ terminal window, not _every single one I launch_. It's personal taste. 

You could repeat this for multiple different "session"s if you wanted. That way you could have layouts pre-defined for various different dev environments. 

We're also tracking adding commands to the new tab dropdown in #1571.

/dup #961
