### ISSUE TITLE
Feature Request - Restore closed tab

### ISSUE THREAD

**Issue by AClerbois** [microsoft/terminal#960]
Hello, 

I'd suggest a restore tag feature like in internet browser. For example, you close a tab and press [CTRL] + [SHIFT] + [T] and that will restore the latest tab closed. 

May be without the context in the first step but with the latest path. 

P.S. : Thank you for your awesome project,, I'm very excited to use the final preview version with the new font.

**Comment by zadjii-msft** [comment]
So tracking the most recently closed tab wouldn't be that hard. We could keep a stack of profiles as we close them, and just pop from that stack when we want to reopen one. That's not _too_ hard.

What _is_ hard is restoring state. Even restoring the path of the executable that was running might be incredibly tricky - can we get the cwd of an arbitrary executable? What if the executable was ssh, which in some directory in a remote machine? We certainly wouldn't be able to restore that connection. What if the path no longer exists? If we CreateProcess a process in a directory that doesn't exist, what happens? Do we just default to the profile's default? What if your cmd.exe profile was running powershell, and powershell had changed to some other directory? We can't restore the process tree, and because this is Windows, there isn't the concept of a "foreground" process attached to a conpty, so we'd have to default to using the state from the executable at the root of the process tree.

Just some thoughts off the top of my head. I'm sure @malxau actually has a lot more on this if I remember my email inbox correctly.

I want to make sure that this issue specifically tracks "restoring the last closed tab's profile" and not "restore it's state" because the former is easy and the latter is _hard_. We should probably have more discussion of the latter in a new issue, #961.

<hr> 

Actually now that I've typed #961 up, I had an idea. This might have to be something that the user opts in to, but we could _theoretically_ just keep the TermControls from the N most recently closed ~~tabs~~ panes alive in the stack, and when the user reopens the tab, we just put the control back into the ~~tab~~ pane. I'm suggesting this is opt-in, since we'd be keeping some number of controls alive, including all the processes attached to them. This would definitely _seem_ like a memory leak, unless the user has opted in to this behavior, and the user would almost certainly

  1. need to know this was happening
  2. have a way to manually shut these saved instances down

**Comment by desmondkung** [comment]
I don't think restoring state is a good idea, especially from a security perspective. If I'm a bad actor and try to run terminal that restores state, it's like opening a box of surprises, which might make my work easier.

**Comment by DHowett** [comment]
When we market this feature, we should be very clear on what it does. If I recall correctly:

_This does not restore the application running in the closed tab. The restore action restores a facsimilie of the closed session, but the application that was running in it doesn't keep running._

**Comment by josseth** [comment]
> 🎉Este problema se solucionó en #11471, que ahora se ha publicado correctamente como .`Windows Terminal Preview v1.13.10336.0`🎉
> 
> Enlaces prácticos:
> 
> * [Notas](https://github.com/microsoft/terminal/releases/tag/v1.13.10336.0)
> * [Descargar tienda](https://www.microsoft.com/store/apps/9n8g5rfz9xk3?cid=storebadge&ocid=badge)

Aun existe un loop al iniciar el terminal. ocurre despues de guardar los cambios del terminal y al abrirlo de nuevo. queda abriendo y cerrando el proceso pero nunca lo muestra.

**Comment by swinder0161** [comment]
The problem with this is the tab position is not restored, if tab closed is first one, the restored tab is the last one.
the position should also be restored
