### ISSUE TITLE
Bug Report Scrollbar not updating while holding enter in powershell

### ISSUE THREAD

**Issue by Summon528** [microsoft/terminal#963]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18898.1000]
Windows Terminal version (if applicable): 3f95d588051723

Any other software?
```

# Steps to reproduce
1. Open PowerShell in terminal  (It works normally in `cmd` and `wsl`)
2. Hold down <kbd>enter</kbd>

# Expected behavior
Scrollbar should be scrollable after content passed the screen

# Actual behavior
Scrollbar is still disabled  

#### Demo video (see the scrollbar only update after the `ls` command)
![Imgur](https://i.imgur.com/yJDxMoa.gif)

**Comment by zadjii-msft** [comment]
Oh hell, this is PSReadline doing something terrible with conpty. Not sure what quite yet, but the same behavior can be repoduced in conhost by running wsl, then powershell.exe. At this point, powershell.exe will be running in a conpty. The problem also goes away if you `Remove-Module PSReadline`.

My bet is that they're trying to detect the size of the console buffer, and if they're at the bottom, they're scrolling the buffer content upwards (either with the API or VT) instead of just emitting a newline. Since the buffer in conpty is only the size of the viewport, this happens immediately.

@lzybkr or @SteveL-MSFT for commentary.

I could've swore there was an issue for this already, but my memory escapes me

**Comment by lzybkr** [comment]
Try [PSReadLine 2.0.0-beta4](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta4). I recall this being fixed, and if I understand the repro correctly, I'm not reproducing the problem myself.

**Comment by DHowett-MSFT** [comment]
Yeah, this was probably lzybkr/PSReadline#724.
