### ISSUE TITLE
WindowsTerminal.exe and OpenConsole.exe aren't signed

### ISSUE THREAD

**Issue by emmett-b** [microsoft/terminal#9670]
### Windows Terminal version (or Windows build number)

Windows Terminal version 1.6.10571.0

### Steps to reproduce

Open Sysinternal Process Explorer, enable the "Verified Signer" column and see "(No signature was present in the subject)".

### Expected Behavior

I would expect programs from Microsoft to be signed by Microsoft. All other programs from Microsoft installed on my machine are signed.

### Actual Behavior

I saw "(No signature was present in the subject)" in Sysinternal Process Explorer's "Verified Signer" column for both WindowsTerminal.exe and OpenConsole.exe

**Comment by emmett-b** [comment]
Here's a screenshot from Process Explorer:
![image](https://user-images.githubusercontent.com/28929018/113071267-a99a2080-91c4-11eb-8db7-c68abd90bee7.png)

**Comment by DHowett** [comment]
So, Terminal is distributed in a signed _container_, the `msixbundle`/individual `msix` archives. Packaged applications are signed as a single unit, and the signature is recorded as part of the app platform's package manager database. :smile:

You can verify the signature on the build artifacts on our Releases page.

**Comment by emmett-b** [comment]
So is it a bug in Process Explorer?

**Comment by emmett-b** [comment]
Hmmm, let's have Mark Russinovich's take on it? ;)

**Comment by DHowett** [comment]
![image](https://user-images.githubusercontent.com/189190/113183236-68802b80-9219-11eb-8d19-5de177ae0b9c.png)

:smile:

**Comment by DHowett** [comment]
In general, there are some things about packaged processes (or packaged applications in general) that don't play nicely with the established systems. I know that's not _great_... but this seems to be the case for every store-deployed signed app on my machine today. There's a signature file at the root of the package that attests to its contents, and a "block map" that is also signed that attests they haven't been tampered with!

![image](https://user-images.githubusercontent.com/189190/113184097-666a9c80-921a-11eb-8c06-9a5f03418818.png)
(Properties dialog -- since I can't actually get Process Explorer to display **anything** for Verified Signer ☹️; Anyway, no Digital Signatures page!)

However, this guy is here:

![image](https://user-images.githubusercontent.com/189190/113184167-797d6c80-921a-11eb-9b19-9ef29557894c.png)

Indeed, all in good fun!

**Comment by DHowett** [comment]
SO! A packaged process is one that has an "identity" and was downloaded from the store or installed from a signed `appx` or `msix` file. If you go to Process Explorer and enable the "Package Name" field, you can see the identity for each process.

That identity is used to control access to resources in a more fine-grained way than your user ID/user account ACL. It's part of the store's sandboxing system.

**Comment by b-dasass** [comment]
Hi @DHowett, I understand everything you wrote here.

However, `windowsterminalshellext.dll` also not signed, and the it is being blocked on my machine because of the missing digital signature. 

When I'm casually browsing my file system using File Explorer I'm being prompted by an alert that `ddlhost.exe` wasn't able to access `windowsterminalshellext.dll` because it's content cannot be verified, and it's being blocked to prevent any malicious things.

Is this something I need to open an issue for?

**Comment by zadjii-msft** [comment]
@b-dasass two questions:

* How did you install the Terminal? (from the store, from the Releases page, from `winget`, `choco`, `scoop`, etc)
* What program is displaying the alert about the missing signature?

**Comment by b-dasass** [comment]
@zadjii-msft 

It is installed from the store, and the alert is coming from Carbon Black.

**Comment by DHowett** [comment]
I suspect that the "security" software you're using doesn't respect package signatures and will throw a warning for _any_ packaged shell extension. :/

**Comment by johnstep** [comment]
Packaged executables _are_ signed, along with other files as [required](https://learn.microsoft.com/windows/msix/package/signing-package-overview) for deployment, but file signatures are stored in the package catalog, AppxMetadata\CodeIntegrity.cat (except for Windows system packages). Executables may also have embedded signatures, but those are not required when packaged, even for a verified publisher UAC elevation prompt.

Process Explorer currently only displays the package name (package full name*, not display name) for UWP processes, not _all_ packaged processes, and does not use the package catalog. We will fix both issues in Process Explorer. Thanks!

In the meantime, try the following workaround with [Sigcheck](https://www.sysinternals.com/downloads/sigcheck) from PowerShell:

```
$ (ps WindowsTerminal).Path
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.15.3466.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

$ cd "C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.16.3464.0_x64__8wekyb3d8bbwe\"

$ sigcheck.exe -f .\AppxMetadata\CodeIntegrity.cat .\WindowsTerminal.exe

Sigcheck v2.90 - File version and signature viewer
Copyright (C) 2004-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.16.3464.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe:
        Verified:       Signed
        Signing date:   10:03 2022-12-13
        Publisher:      Microsoft Corporation
        Company:        Microsoft Corporation
        Description:    WindowsTerminal.exe
        Product:        Windows Terminal
        Prod version:   1.16.221212004-preview
        File version:   1.16.2212.12004
        MachineType:    64-bit
```

\* Example package full name: Microsoft.SysinternalsSuite_2022.11.2.0_x64__8wekyb3d8bbwe
