### ISSUE TITLE
Acrylic Opacity doesn't work in WIndows Terminal v1.6.10571.0

### ISSUE THREAD

**Issue by saby22** [microsoft/terminal#9674]
### Windows Terminal version (or Windows build number)

1.6.10571.0

Hello everyone,

My installation of  Windows Terminal (v1.6.10571.0), from Microsoft Store doesn't render Acrylic Opacity.

### Steps to reproduce

- I have set "useAcrylic" property to be true
- "acrylicOpacity" has been set to 0.5
- Transparency Effects have been turned on in Settings > Personalization > Colors

### Actual Behavior

- Transparency in Calculator and the Settings menu doesn't work as well
- My laptop runs on Integrated AMD Radeon RX Vega 10 Graphics as well as NVIDIA GeForce GTX 1650
- Acrylic Opacity does not work in Windows Terminal as well

**Comment by zadjii-msft** [comment]
I'm just copy-pasting this from ~~#1414~~ #7047 & #8563:
 
* Acrylic doesn't work if there's not the GPU hardware for it. A ~~Surface Studio~~ Integrated AMD Radeon RX Vega 10 Graphics as well as NVIDIA GeForce GTX 1650 probably has the hardware, but it won't work if you're running the app in a VM or over remote desktop (for example).
* Acrylic can be disabled by the system for a number of reasons, like being in power saver mode, or when accessing a machine over Remote Desktop
* As a sanity check, is there Acrylic in the Start Menu?


Since acrylic isn't working in Calculator, then there must be some reason why you machine disabled it system-wide, not specific to the Terminal. If it was working in Calculator, but not the Terminal, I'd direct you to #7047

**Comment by AthsaraFernando** [comment]
instead of this line
"acrylicOpacity": 0.5
use this
"opacity": 50,
