### ISSUE TITLE
Unable to read keypresses using ($host.UI.RawUI.ReadKey('NoEcho,IncludeKeyUp')).character

### ISSUE THREAD

**Issue by jameswylde** [microsoft/terminal#9682]
### Windows Terminal version (or Windows build number)

10.0.18363.0
Latest WT and WT preview

### Other Software

Powershell 7.1.3
Powershell 5.1.18362.1171

Tested on both current WT and WT Preview, same results.

### Steps to reproduce

Simple TUI to demonstrate:

```
do
{
     Show-Menu
     $keyPress = ($host.UI.RawUI.ReadKey('NoEcho,IncludeKeyUp')).character
     switch ($keyPress)
     {
           '1' {
                Clear-Host
                functionHere
           } 'Q' {
                return
           }
     }
     pause
}
until ($keyPress -eq 'q')
```

### Expected Behavior

Powershell to progress and ReadKey from input. 

### Actual Behavior

Input is detected (writes into terminal) however on enter disappears and no action is executed. 

Working fine in normal PS shells (version numbers above).

**Comment by DHowett** [comment]
Thanks for the report! I don't have a `Show-Menu` commandlet -- can you point me to a module? Did you author this yourself?

**Comment by jameswylde** [comment]
Apologies Dustin, that's actually a function I named whilst quickly whipping up the above to demonstrate the issue - poorly named. Why I used a cmdlet naming convention I have no idea.

So Show-Menu would simply write to host something like:

```
function Show-Menu
{
     param (
           [string]$Title = "OMP Server Bouncer 5000"
     )
     Clear-Host
     Write-Host "Option 1"
     Write-Host "Option 2"
}

```

Apologies I didn't include, I didn't think it relevant. Let me know if you need anything else.

**Comment by DHowett** [comment]
Okay, so I think this is another case of ... well, this is pretty curious. When you press enter, we stuff an enter DOWN and an enter UP key into the input buffer. Because you're accepting a read on Key Up, you're immediately getting the "enter key up" event that you get from either pressing enter on the prompt line or enter after `pause`. If you press enter slowly in the traditional console, you can see this as well.

Recommendations are to either flush input (which I am not sure how to do from PS or .NET), or to not read key _up_ events. They're relatively uncommonly used as far as we can tell. :smile:

Marking this by-design. There's a couple other issues floating around for this that I may come back and deduplicate with this one.

Cheers!
