### ISSUE TITLE
Python not opening after winget install Python3

### ISSUE THREAD

**Issue by romanokeser** [microsoft/terminal#9697]
So after I installed python3 `winget python`, I couldn't run python script from terminal such as `python3 example.py`. Also, it's not showing me the version of python `python --version`, it says that it's not installed. Did I do something wrong with the installation?

**Comment by DHowett** [comment]
Hmmm.. have you re-launched terminal since then?

**Comment by romanokeser** [comment]
> Hmmm.. have you re-launched terminal since then?

My god... I just feel stupid right now. Didn't even think about that. Also, how's that my terminal switched language? I'd like it to be full English, but somehow it got changed even tho my input and system settings are all in English.

**Comment by DHowett** [comment]
> My god... I just feel stupid right now. Didn't even think about that. 

Don't worry about that- the environment variable stuff is more annoying on Windows than elsewhere, because there's no easy way to simply reload the environment for your running shell :smile:

That's an excellent question, about the language. Can you open up the system Language settings and send a screenshot of the "Preferred Language" list? We have seen some reports of issues where there are multiple copies of English in your language list that are in a specific order. (They can be dragged up and down to change the language's "priority")

**Comment by romanokeser** [comment]
> > My god... I just feel stupid right now. Didn't even think about that.
> 
> Don't worry about that- the environment variable stuff is more annoying on Windows than elsewhere, because there's no easy way to simply reload the environment for your running shell 😄
> 
> That's an excellent question, about the language. Can you open up the system Language settings and send a screenshot of the "Preferred Language" list? We have seen some reports of issues where there are multiple copies of English in your language list that are in a specific order. (They can be dragged up and down to change the language's "priority")

Alright, I got it, the Windows switched my Language preferences in settings. I switched it back to English and now it works, didn't even think that this might be the problem, thank you!
