### ISSUE TITLE
Don't require restart of Terminal on updating environment variables

### ISSUE THREAD

**Issue by parthopdas** [microsoft/terminal#9739]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

- Open a bunch of tabs in terminal + customize them by splitting pane
- Install anything that updates system environment variables
- Launch a new tab

PS: In my case I had to install Cuda stuff that updates environment variables required by tensorflow gpu libs 

### Expected Behavior

The new tabs / panes should have the update environment variables

### Actual Behavior

I have to kill all existing tabs and restart terminal

**Comment by KalleOlaviNiemitalo** [comment]
Reloading the environment variables is part of <https://github.com/microsoft/terminal/issues/1125>. It was already implemented but has been repeatedly reverted from stable branches (e.g. <https://github.com/microsoft/terminal/commit/ba534aaad693d942ec6da4380005a09f6520d0c5> for release-1.6) because the existing implementation makes an environment block that is not compatible with Windows PowerShell <https://github.com/microsoft/terminal/issues/7418>.

**Comment by zadjii-msft** [comment]
Yep, sure is!

/dup #1125
