### ISSUE TITLE
Way to save existing terminal tab / pane layouts

### ISSUE THREAD

**Issue by parthopdas** [microsoft/terminal#9740]
# Description of the new feature/enhancement

It will be good to have a way to save the current tab / pane configuration, perhaps including environment variable changes. 

This is so I can quickly get back to the tab / pane setup (that I'd have built over many days) in case I need to restart terminal.

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! [Looks like](https://github.com/microsoft/terminal/issues/766#issuecomment-779902831) we're tracking this in #776. 

/dup #766

<hr>
So for reference, I like to do like the following each time I boot up the Terminal in the morning:

```json
{ "command": { "action": "wt", "commandline": "new-tab --title OpenConsole cmd.exe /k #work 15 ; split-pane -s .30 --title OpenConsole cmd.exe /k #work 15 ; split-pane  -s .25 -H cmd.exe /k media ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },

```

(you could probably make it shorter by replacing `new-tab`/`split-pane` with `nt`/`sp`, respectively).

I add that to the `keybindings`/`actions`. This creates a new command in the [Command Palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette) named "Good Morning". That opens up a few tabs & panes, running various build environments. I like having it in a command rather than `startupActions`, because I only really want this in _one_ terminal window, not _every single one I launch_. It's personal taste. 

You could repeat this for multiple different "session"s if you wanted. That way you could have layouts pre-defined for various different dev environments. 

We're also tracking adding commands to the new tab dropdown in #1571.
