### ISSUE TITLE
startupActions not working when launching Terminal from an explorer folder

### ISSUE THREAD

**Issue by maicol07** [microsoft/terminal#9749]
### Windows Terminal version (or Windows build number)

1.7.572.0

### Steps to reproduce

1. Setup some startupActions in the JSON config
2. Go to a folder in explorer.
3. Right Click --> Open Windows Terminal

### Expected Behavior

All the startup actions are executed and all the tabs are opened

### Actual Behavior

Only the last tab is opened

**Comment by zadjii-msft** [comment]
I mean I guess this is "by-design" right now - the context menu entry is only supposed to open up your default profile in the specified directory. 

I guess this is a setting that we could use to combine with #6111

**Comment by DHowett** [comment]
Unfortunately, I'm going to close this one out as "By design". We'll have some more configurability when #6111 lands, but in general we cannot comport "open terminal with a profile here" with "also do these startup actions". I suspect that most users do _not_ want terminal to, say, "new-tab; new-tab; split-pane -p Ubuntu" when they just right-click-open-terminal-here.

That said, some of the experimental stuff we've been discussing around menu item to action binding would make this easier.
