### ISSUE TITLE
Cant open from run

### ISSUE THREAD

**Issue by RexTheCapt** [microsoft/terminal#9784]
### Windows Terminal version (or Windows build number)

19042.867

### Steps to reproduce

Windows+R, wt, ENTER

### Expected Behavior

Windows terminal opens up

### Actual Behavior

Error message: The application was unable to start correctly (0xc0000022). Click OK to close the application.

**Comment by zadjii-msft** [comment]
There's a [pile of issues](https://github.com/microsoft/terminal/issues?q=is%3Aissue+0xc0000022) already tracking this particular error message:

* #9452: [MSIX Bucket] Launch issues caused by bad permissions on WindowsApps, and others 
* #9399: Always crashes with 0xc0000022 
* #7974: 0xc0000022 error was occured while opening wt.exe after v1.2.2381.0 
* #7081: 0xc0000022 startup error when opening wt from file explorer or Run window 
* #6862: Error 0xd0000022 when launching any shell (PS, cmd, git bash, PS7, Azure Cloud Shell) in WT 

Please follow up in #9452 if none of the solutions in those threads work for you.

/dup #9452
