### ISSUE TITLE
wt.exe - The application was unable to start correctly (0xc0000022).

### ISSUE THREAD

**Issue by Dargoz** [microsoft/terminal#9797]
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Other Software

1. Windows Explorer
2. Run
3. cmd/ PowerShell, etc

### Steps to reproduce

tried all of these :
1. Run > wt.exe > error
2. run wt on search explorer > error
3. double click wt.exe from C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe > error

note : 
1. I'm only have 1 instance of Windows Terminal
2. Apps aliases already turned on

### Expected Behavior

Open windows terminal

### Actual Behavior

wt.exe - Application Error

The application was unable to start correctly (0xc0000022). Click Ok to close the application.

**Comment by zadjii-msft** [comment]
There's a [pile of issues](https://github.com/microsoft/terminal/issues?q=is%3Aissue+0xc0000022) already tracking this particular error message:

* #9452: [MSIX Bucket] Launch issues caused by bad permissions on WindowsApps, and others 
* #9399: Always crashes with 0xc0000022 
* #7974: 0xc0000022 error was occured while opening wt.exe after v1.2.2381.0 
* #7081: 0xc0000022 startup error when opening wt from file explorer or Run window 
* #6862: Error 0xd0000022 when launching any shell (PS, cmd, git bash, PS7, Azure Cloud Shell) in WT 

Please follow up in #9452 if none of the solutions in those threads work for you.

/dup #9452
