### ISSUE TITLE
Small quirk in tabs bar

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/terminal#9826]
### Windows Terminal version (or Windows build number)

v1.8.1032.0

### Steps to reproduce

Open two tabs

### Expected Behavior

No faint grey bar

### Actual Behavior

There is a small faint bar at the end of the tab strip

![image](https://user-images.githubusercontent.com/75278/114787858-b7cd6c80-9d80-11eb-8771-7c7a5821e05e.png)

**Comment by DHowett** [comment]
Thanks for the report! That is a divider between the tab strip and the buttons :smile:

(It's by design in the tab strip that the XAML people created for us, and due to a bug it was previously being occluded. Whether that occlusion was _correct_ versus whether it was _aesthetically pleasing_ is another discussion. We're trying to line up with other applications here on Windows.)

((We actually increased the space not so the divider would show up, but so that the _righthand corner shadow_ would show up!))

**Comment by Stanzilla** [comment]
Ohhh okay, it looked like a bug :D

**Comment by Stanzilla** [comment]
@DHowett if it's meant as a separator, I would probably move it a bit further away from the end of the tab so that it's more clear
