### ISSUE TITLE
add a real Terminal aka Remote Connection / Shell --> a putty alternative

### ISSUE THREAD

**Issue by Gunnar-GO** [microsoft/terminal#9871]
the app looks promissing, if connections like terminal, ssh etc. will be added it will become more usefull.

like a putty alternative. with saved account-data (verify by account-verification like fingerprint, pin, passw)

**Comment by DHowett** [comment]
Thanks for the request. Terminal is going to be a very good _local terminal_. We are not planning on adding specific ssh and telnet client support because ssh and telnet are already part of Windows. You can use them inside terminal.

If we add support for password and identity storage and management, we will become a security product and it will be harder and more complicated to develop. 😄
