### ISSUE TITLE
Slow loading time on first use

### ISSUE THREAD

**Issue by DrRZ** [microsoft/terminal#9905]
Windows Terminal Version: 1.7.1033.0
Windows Version 20H2 (OS Build 19042.928)

I use Windows Terminal with Ubuntu WSL2 and Windows Command Prompt profile.
In some previous version it would load quickly, but for some time when I first load a terminal it takes several seconds before the window loads. During this time there does appear an icon in the system tray with the title "DesktopWindowXamlSource" which eventually is replaced with the profile name when the window finally appears.

This occurs regardless if which profile I'm initially loading. 

After the terminal has loaded, if I close the window and load it again, it opens quickly. I can still see the original DesktopWindowXamlSource icon but it's only there for a split second. I can continue loading terminal windows, even after they are all closed, with no delay.

However, if I don't open a terminal window for some time (several minutes), there is a delay on loading the first instance again.

There was a previous issue Slow startup time #4886 reporting a similar problem in a previous version, which has been closed. I'm not sure if this is the same issue or not, but it hasn't been resolved.

I also experience this on both my desktop and laptop computers.

**Comment by zadjii-msft** [comment]
### days since I've been annoyed by WSL's lack on an API: 0

This is basically the same thing as #4886, with a touch of #9541 and #7199. Basically, the entire UI is waiting while we query the OS for the list of WSL distros. Unfortunately, that involves booting up WSL entirely just to ask it this question. 

We've got a deliverable on them for "make an API for us that doesn't require booting WSL.exe". We might have another issue laying around on this repo that's actually tracking that. @DHowett do you remember where that one is? 

I'm seriously 🤏 close to changing that code to the registry lookup that _won't_ hang.

**Comment by minhaj6** [comment]
Windows Terminal
Version: 1.8.1521.0 
Windows 10 version 21H1, Supporting the issue.

**Comment by Tronmech** [comment]
I'm seeing slow startup in  1.11.2921.0 -- just installed today. I think this happened after enabling WSL and installing ubuntu 20.04.

**Comment by elliottmejia** [comment]
bumping this, it is still an issue. installed recommended ubuntu wsl, terminal takes about 5-10 minutes to open.

**Comment by lhecker** [comment]
Please create a new issue. Issues closed for years are no good. 🙂
