### ISSUE TITLE
mouse input only work in the left of window

### ISSUE THREAD

**Issue by ch2925** [microsoft/terminal#9928]
# Description of the new feature/enhancement
when I am using tools like vim and htop,the mouse input only work in the left of the window,about 90 columns in the left.on the right mouse click is not working.
My 2 devices both met this problem.
![issue](https://user-images.githubusercontent.com/46040749/115826459-8b2eea00-a43d-11eb-9dc0-4d1e90e7b3d0.gif)

# Proposed technical implementation details (optional)
![image](https://user-images.githubusercontent.com/46040749/115827698-3d1ae600-a43f-11eb-91d4-b6c788ebcf62.png)

**Comment by DHowett** [comment]
These applications are using the legacy mouse encoding, which we must support for compatibility reasons. This is a snippet from the Vim help:

```
xterm	xterm-like mouse handling.  The mouse generates
     	"<Esc>[Mscr", where "scr" is three bytes:      
     		"s"  = button state                    
     		"c"  = column plus 33                  
     		"r"  = row plus 33                     
     	This only works up to 223 columns!  See "dec", 
     	"urxvt", and "sgr" for solutions.              
```

It says 223, but encoding issues practically limit it to ~93.

For `vim`, use `:set ttymouse=sgr` to choose the newest/best encoding that has support for inifinite coordinates. For htop, it would be good to report a bug to the htop issue tracker that it is requesting xterm mouse mode instead of SGR mouse mode.
