### ISSUE TITLE
Can't get fragments to work with an MSIX app

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/terminal#9968]
### Windows Terminal version (or Windows build number)

1.8.1032.0, 1.7.1033.0

### Other Software

A new MSIX installer for the Julia language that I'm working on (https://github.com/davidanthoff/winjulia). The installer is available for tryout at https://winjulia.david-anthoff.com/. The appx file that has the fragment in it and the JSON in the app manifest is available at https://winjulia.s3-us-west-1.amazonaws.com/JuliaApp-x64-1.0.0.32.appx.

### Steps to reproduce

Go to https://winjulia.david-anthoff.com/ and install Julia from the link on that page. That will trigger an MSIX App Installer setup and install Julia.

### Expected Behavior

I would have expected a new profile to show up in Windows Terminal for Julia automatically.

### Actual Behavior

No profile appears. I think I must be making some mistake in how I am creating the fragment, but I can't figure out what is wrong.

The appx manifest I'm using is https://github.com/davidanthoff/winjulia/blob/master/msix/appxmanifest.xml, the fragment I'm adding is https://github.com/davidanthoff/winjulia/blob/master/msix/Fragments/Julia.json, and that file is put into the folder `Public\Fragments` via https://github.com/davidanthoff/winjulia/blob/master/msix/PackagingLayout.xml#L8.

**Comment by zadjii-msft** [comment]
@PankajBhojwani can you help @davidanthoff here?

**Comment by PankajBhojwani** [comment]
Just an update (so you don't think we've abandoned this!):

It seems that we are detecting Julia as an app extension, but when we probe it for its public folder we get a null response. I am still trying to figure out why this is so - the extension and public folder names seem to be declared properly in the manifest file (the extension name almost certainly is since we are detecting Julia as an extension), so I wonder if it has something to do with the way the public folder/the json file is included. 

In the UWP app I use to test fragments with Terminal, I have a 
`<Content Include="Public\Fragments\fragment.json" />` line in the `.csproj` file, and it seems that the equivalent here is the
`<File DestinationPath="Public\Fragments\Julia.json" SourcePath="Fragments\Julia.json" />` line in the `PackagingLayout.xml` file, so that _should_ also be working, unless there's some difference there I'm not aware of

**Comment by davidanthoff** [comment]
Great, thanks for the update!

Could you maybe just check the actual content of the appx file of your UWP app and the appx file that you can download from my top post, and then unzip both and just see whether the fragment is stored differently?

**Comment by PankajBhojwani** [comment]
@davidanthoff can you try making this change in your appxmanifest file?

```
        <uap3:Extension Category="windows.appExtension">
          <uap3:AppExtension Name="com.microsoft.windows.terminal.settings" Id="Julia" PublicFolder="Public" DisplayName="Julia">
            <uap3:Properties>
              <Service>com.microsoft.powservice</Service>
            </uap3:Properties>
          </uap3:AppExtension>
        </uap3:Extension>
```

If that fixes it, then we are going to need to update our docs

**Comment by davidanthoff** [comment]
I just tried, and that doesn't seem to help :) Should I remove that again? Probably, right?

**Comment by PankajBhojwani** [comment]
> I just tried, and that doesn't seem to help :) Should I remove that again? Probably, right?

Yes, please remove it! I misunderstood its purpose when I told you to try it

**Comment by DHowett** [comment]
Okay, so we just had a long debugging session. This is going to seem like the ravings of a crazy person . . . but I think there's a difference in how app extensions work¹ when the app is installed as part of a `.appinstaller` or with optional/dependency packages installed next to it.

I:

* Accidentally used the 1.0.0.32 `.appx` directly
   * It worked, baffling @PankajBhojwani and me
* Pulled down the appinstaller
   * It didn't work!
   * Terminal found the extension, but the platform told us that the folder didn't exist (???)
* ... registered the contents of the app package separately, elsewhere
   * It went back to working (and then I unregistered it to make sure it wasn't a fluke)
* ... installed the 1.0.0.34 `.appx` directly
   * It continued working

¹ which I will be taking up with the App Extensions team here at Microsoft :)

**Comment by zadjii-msft** [comment]
To follow up - the App Extensions team actually found the root cause of this bug. Crazily, the AppInstaller actually does break this - and the underlying bug might date back to 2017. 

This is being tracked internally in MSFT:33093453. We'll make sure to post if there are any updates internally. I'm not sure if there is any workaround at the moment.

**Comment by davidanthoff** [comment]
Alright, I now managed to publish the Julia MSIX in the Windows Store, and the fragment works perfectly there! So, clearly that is a bug in app installer and not related to the terminal. Thanks for helping me figure this out!
