### ISSUE TITLE
PowerShell tabs often stop with "process exited with code 5"

### ISSUE THREAD

**Issue by campbellkerr** [microsoft/terminal#9973]
### Windows Terminal version (or Windows build number)

1.7.1033.0

### Other Software

OneDrive

### Steps to reproduce

(I **think** this is what's happening)

1. Have OneDrive installed/signed in
2. Open a bunch of PowerShell tabs and CD to your OneDrive ( `cd $env:\Onedrive` )
3. Open a PowerShell tab and CD to C:\ drive 
3. Put computer to sleep/hibernate
4. Wake the computer

### Expected Behavior

PowerShell tabs should remain available for use

### Actual Behavior

The PowerShell tabs in the OneDrive path display
`[process exited with code 5]`

![image](https://user-images.githubusercontent.com/38451588/116356068-1b09d500-a83e-11eb-9489-c753f718ddc4.png)

The busted tab will no longer receive any input.

Note that a normal PowerShell window seems unaffected.

**Comment by skyline75489** [comment]
This feels like a PowerShell issue for me, since we really don't control when & how the shell exits.

**Comment by DHowett** [comment]
I'm guessing that this is because the OneDrive filter driver is disconnected and as part of that, any process holding a handle to that path is killed. There's nothing we can do about this[1].

If you wouldn't mind filing feedback on OneDrive (and possibly sharing the link here,) that would be lovely.

Thanks!

1: Traditionally, console applications would just disappear when they were killed. Terminal at least warns you! :smile:

**Comment by campbellkerr** [comment]
Hi @DHowett I can definitely provide feedback to OneDrive however I still find it odd that a normal PowerShell window does not suffer from this problem and remains responsive after sleep/wake (unlike the Terminal tab). Thoughts?
